== Introductory Chapter

"`We walk by faith,`" says the apostle, "`and not by sight;`" (2 Cor. 5:7)
Now, the obedience which results from the walk of faith,
differs from that which merely springs from attention to an external rule,
in the same way as the motions of an automaton differ from those of a living man.

For, as the automaton, by means of certain springs,
may imitate some of the actions of a living man; so,
by adhering to certain religious precepts,
may the obedience which is required from the creature to the Creator,
be partially represented also.
But, as in the case of the automaton,
the nature of the living man cannot possibly in
any measure be obtained by the means used;
so neither in that of the obedience which is produced only by the sight of a rule,
can the least degree of the love of a child of God exist;
and it can require but little reasoning to demonstrate,
that it is love alone which can give life, power, and acceptableness, to any act of duty.
That husband, or father, or master of a family, whose will was obeyed by wife, children,
or servants, not because they loved him,
but because it was their interest to yield him obedience,
and who gave it according to the measure and kind, which written regulations from him,
stipulated as his right; such an one, we say,
would have small occasion to congratulate himself upon their services;
seeing how devoid they were of the lovely and endearing
nature which can alone give value to any obedience.

"`Love is the fulfilling of the law;`" and love to God is no natural feeling;
assuredly it is not born with us; neither is it a thing to be acquired,
"`If a man would give all the substance of his house for love,
it would utterly be contemned,`" (Song. 8:7) Love, in short,
is a living thing--"`God is love`"--and God is life-- eternal
life--and it is by this living principle of love,
that such an obedience as is acceptable to the Creator, and profitable to the creature,
can alone be wrought out.

We must have the divine life then, before we can perform the functions of it.
The natural will not reach to the super-natural.
We may love our friends and kindred with such a love as fallen humanity is capable of;
but to love God, we must have a new and a divine nature,
since like can only have affinity with like;
and hence the indispensable necessity of our being born again.
"`Except a man be born again,`" says the Saviour, "`he cannot see the kingdom of God.`"
The question is not whether he wishes it or not; he cannot--his present condition,
as an unregenerated man, renders it impossible.

Now, as it is clear to demonstration, that life wherever it exists,
is always evolved out of its own proper germ, are we to suppose that the divine life,
(of which we must be born, and of which our Lord speaks, in John,
iii.) is an exception to this universal law?--Is it said, "`We must be born again,
not of corruptible seed,
but of incorruptible,`" (1 Pet. 1:23) and yet that there exists
not in our fallen nature any portion of this incorruptible seed?

The scriptures do not warrant such an assumption; on the contrary,
they repeatedly testify to its presence in the soul.
Various names they give to it:
such as "`the word of the kingdom;`" the "`word nigh in the heart;`" "`the
ingrafted word which is able to save the soul;`" "`the voice of the good
Shepherd,`" etc.--but that by which its full sufficiency and appointed
office is the most frequently exhibited,
appears to be that of light.

"`That was the true light which lighteth every man that cometh into the world.`"
(John 1:9)

"`But all things that are reproved are made manifest by the light;
for whatsoever doth make manifest is light.`"

"`Wherefore he saith, awake thou that sleepest, and arise from the dead;
and Christ shall give thee light.`"
(Eph. 5:13-14)

And who is there, it may be confidently asked, that has not, at times,
been made deeply sensible of the presence of this "`true light`" in his soul,
manifesting there the darkness and disorder of the passions,
and with "`a still small voice,`" calling upon him to renounce their Egyptian slavery?

Who is there that can be considered as serious in thought or feeling,
that has not had cause to rejoice in obeying the call of this inward illuminator?
and who, that has faithfully followed as far as it has pleased to lead him,
but has found it to be a deliverer from sin, and a "`guide into all truth?`"

Let all those who question its power in this respect,
first answer to their own consciences,
how often and how sincerely they have submitted to its yoke, and borne its burden,
before they venture to decide upon its not being
that incorruptible seed of the kingdom of God,
of which, and into which, they are to be born again.

"`I am come a light into the world,`" says the Redeemer thereof,
"`that whosoever believeth on me should not abide in darkness.`"
Again he says, "`if ye believe not that I am he, ye shall die in your sins.`"

Now, dear reader, what is it to believe in Jesus Christ?
a question which may be answered by another: What is it to believe in anything spiritual?
What is it to believe in love, joy, peace, long-suffering, gentleness, goodness, faith,
meekness, temperance?
Is it not to be sensible,
and feelingly conscious of the blessed nature of these heavenly fruits?
Can these divine qualities be even understood,
unless the affections are in some degree partakers of their character?
And how, or where, is their power to be felt, but in the heart, that desert land,
which their presence makes to "`blossom as the rose?`"

The fact then is, that we can no otherwise have faith in Jesus Christ,
"`the light of the world,`" but as we know the power of
his life-giving spirit revealed in our own souls.
We may read descriptions of this divine life, and we may desire to possess it;
but if we seek for it in this or the other "`outward
observation,`" we are but wandering from the point,
and spending ourselves in taking profitless steps, which all must be retraced,
and our fugitive souls brought home, to sweep the house of the heart,
and look for the lost piece of silver there--or it never will be found.

In no other way can that obedience which befits a child, be born; for,
in no other way can the "`obedience of faith`" result.
We must know in whom we have believed;
we must have proved the nature of that Being to whom we can unhesitatingly,
and with loving confidence, resign ourselves.
"`Therefore thus saith the Lord God, behold I lay in Zion for a foundation, a stone,
a tried stone, a precious corner-stone,
a sure foundation:`" and everlastingly true is it,
that those who have built their house upon this rock, have found,
upon their own experience,
that the stone which the builders in every age of the church have rejected,
is nevertheless, "`the head of the corner.`"

But as living illustrations offer the most forcible of all arguments in support of truth,
I have been induced to compile the following narrations; of which I shall only say, that,
if the reader receives from the perusal,
as much valuable enjoyment as it has been permitted me
to experience in the writing of them,
he will rise from his occupation with feelings of no ordinary
esteem for the principles of the individuals herein recorded.

Yet, although I cannot doubt of obtaining the sympathy of many sincere Christians,
in the tender and grateful interest wherewith I myself
contemplate the memory of these departed saints;
I am nevertheless prepared to find some doubts here and there entertained,
as to their having been called by the will of God,
into many things to which they believed themselves so called,
seeing that they were thereby often led into circumstances, which, in human estimation,
appeared as unnecessary, as they were strange.

But to the pious and humble minded (and it is chiefly to such that a
work of this kind can be acceptable) it will surely be enough to say,
that God requires obedience of his creatures, and not reasonings.
Besides, that it ill becomes beings of our limited capacity, to say what is,
or is not strange; seeing that since,
if we would even understand the simplest fact in its origin,
such for instance as the means whereby we are enabled to lift our hand to our head,
we come in contact with something too strange for us to comprehend,
and of which we are constrained to say, "`such knowledge is too wonderful for me;
it is high, I cannot attain unto it;`"--we also find, and that almost invariably,
that when it pleases the Most High to manifest his mighty power,
and "`make bare his arm in the midst of the nations,`"
He does it in a way to confound the pride of reason.
"`I will overturn--overturn--overturn`"--this is his language,
and this his mode of action.

What could exceed in strangeness to human comprehension,
the requirements that were laid upon Abraham, Moses, the prophets,
and many others too numerous to mention?

The submission of the heart was what these holy men concerned themselves with;
not the strangeness of the mode in which that noble and God-glorifying
principle of obedience was outwardly to be exhibited.
They were used to strange things,--to terrible things to flesh and blood,
when they came to deal with the Father of Spirits.

They found it to be God`'s way to break, and bruise,
and batter and confound "`the wisdom of the wise,
and bring to nothing the understanding of the prudent,`" by
requiring them to submit to strange and humbling proceedings.
How often do they testify to this!

"`By terrible things wilt thou answer us, O God of our salvation,`" says the psalmist.
(Ps. 65:5)

Again, "`Thou hast showed thy people hard things;
thou hast made us to drink the wine of astonishment.`"
(Ps. 60:3) "`He breaketh me with breach upon breach,`" says the patriarch Job;
"`he runneth upon me like a giant.`"
(Job 16:14)

"`He hath enclosed my ways with hewn stone; he hath made my paths crooked.
He was unto me as a bear lying in wait, and as a lion in secret places,`" says Jeremiah.
(Lam. 3:10-9)

In fact, it is generally through obedience to some strange thing,
that the very stroke is given, whereby the stiff-necked, stiff-willed,
old Adam-nature is to be crucified and slain.

Certainly, it never did, nor ever will please God to accept of such a righteousness,
and such a conformity to the image of his self-denying and suffering Son,
as can be wrought out according to the conceptions of reason, which, at the very onset,
and as a necessary consequence of its own nature, can see nothing but strangeness,
and irrationality, in the need of a self-denying or suffering Saviour at all.

No;
we must cast down "`reasonings,`" with every other high
imagination that exalteth itself against the knowledge of God,
and bring every thought into captivity to the obedience of Christ,
before we are in any capacity to judge of the fit or the unfit,
in these deeply spiritual matters.
Everything is fit, that makes the heart a meet habitation for the Spirit of God;
and obedience,
when it is the result of the "`faith which worketh by love,`" is eminently
powerful to cleanse and purify and prepare this living temple,
for its appointed and legitimate sovereign.

That there have been instances, in which persons,
acting under a profession of the principles here advocated,
have assumed to have done so in obedience to the will of God,
when they have been manifestly in error, is not to be denied.
But it will generally be found on examination,
that such individuals were possessed of hasty and forward spirits;
and being too bold and confident to abide in the meekness and fear of the true teacher,
they have made "`shipwreck of the faith,`" just as they would,
in their unhumbled condition, have made shipwreck of their talents, their opportunities,
or any other precious thing entrusted to their keeping.

Nothing is safe from the assaults of evil, however exalted may be its own nature,
whilst humanity is what it is,
and the enemy of humanity has any power to practise upon its frailty.
But because there are hypocrites who pretend to be virtuous,
shall we doubt whether any man is conscientiously honest and true?
And because Satan has always endeavoured to overturn a real work of the Spirit of God,
as soon as it appears upon earth, by inviting his own ministers to imitate it;
shall we say there never was such a thing since the apostles`' days,
as a ministration of the Holy Ghost, and that the case of the persons herein recorded,
was one of delusion and imposture?

Assuredly, if they had not well known in whom they had believed,
they had been of all men, not only the most miserable,
but also the most foolish and besotted; seeing how great a sacrifice,
not only of those things which the world esteems,
but even of such as it is considered amiable and wise to respect,
they were well contented to make,
in order to preserve inviolate their principles of faith.

A man may endure much in the service of error,
when his sufferings tend to aggrandize him in the eyes of his fellow-creatures;
but willingly "`to become a fool,
and to be made the off-scouring of all things`" can only be
the result of a sincere fellowship in the Spirit,
and in the sufferings of a lowly-minded Lord and Saviour.

Away, then--and for ever away, with that cold, comfortless, death-like unbelief,
which questions and cavils at, the thought of a God so near to us,
and which would send us out of ourselves, for our king and our kingdom.
No! let the God of Abraham, of Isaac, and of Jacob, that same who said,
"`I am thy shield, and thy exceeding great reward!`"--that same who still says, "`Lo,
I am with you always,
even unto the end of the world!`"--let Him be
known as the Christian`'s glorious dwelling-place;
and let all his loving children say, "`This God is our God for ever and ever,
he will be our guide even unto death!`"

[.signed-section-signature]
M+++.+++ A. K.
