== Chapter II.

The English nation, at this period,
might be said to be wholly engrossed with the great subjects of religion and politics;
for both were mingled together in strange conjunction.
The chief rulers of the Commonwealth,
(more especially Oliver Cromwell,) had contrived to interweave their
own views on spiritual matters into the minds even of the soldiers,
who, in those days, commonly united with the profession of arms,
the profession also of Christianity; and,
as the unsettled state of the kingdom caused them to be stationed in
considerable numbers in most of the principal towns of the north,
several of them had made acquaintance with George Fox during his imprisonment,
and so much approved of him, that when the time of his emancipation drew nigh,
they were desirous of engaging him to remain with them, in the capacity of their captain!
The immediate cause of this desire arose from the circumstance of there
being a commission issued to levy troops for the service of the parliament,
and the commissioners probably wanting to get rid of
Fox in some way that should prevent his return,
proposed to constitute him captain over these recruits,
a measure which the soldiers seconded, by declaring that "`they would have none other.`"
"`So the keeper of the house of correction,`" says he,
"`was commanded to bring me up before the commissioners and soldiers,
in the market-place;
and there they proffered me that preferment (as they called it,)
asking me if I would not take up arms for the commonwealth,
against Charles Stuart?`"

To this he replied, that he knew, from the doctrine of the apostle James,
whence all wars did arise;
and that he lived in the virtue of that life and
power which took away the occasion of war.
But still continuing to urge him, "`I told them,`" he continues,
"`that I was come into the covenant of peace, which was before wars and strife were.
They said they offered it in love and kindness to me, because of my virtue,
and such like flattering words they used.
But I told them, if that was their love and kindness, I trampled it under my feet.
Then their rage got up, and they said, '`Take him away, gaoler,
and put him into the prison amongst the rogues and felons.`'`"
Upon which he was conveyed to a still worse place than before,
being of the most loathsome description as to uncleanliness;
his society about thirty felons, and, to increase his discomfort,
he was without a bed to lie down upon.
Here he was kept nearly another six months, having permission, at times,
to walk in the garden, "`for they had a belief of me,`" he says,
"`that I would not go away.`"

During his prolonged confinement, he wrote again to the authorities of the place,
giving them religious counsel respecting many of their proceedings,
especially in relation to the punishment of death for stealing; and, in one instance,
his representations appear to have had some effect; for he mentions,
that a young woman in the prison, who was condemned to death for robbing her master,
and who was not only brought at the time appointed, to the place of execution,
but actually had ascended the ladder, was nevertheless reprieved, brought back to prison,
and made a recipient of Divine truth.
He had written in her behalf to the judge and jury,
showing them how contrary it was to the law of God, in old time,
to put persons to death for stealing, and entreating them to be merciful to her.
But he does not directly specify that it was upon this
account that favour was extended to her,
although it probably might be the case.
In the interval of his confinement, he was again pressed to become a soldier;
"`the magistrates,`" he says, "`not being able to agree what to do with me.
One while they would have sent me up to the parliament;
another while they would have banished me to Ireland.
At length they were made to turn me out of gaol, about the beginning of winter 1651,
after I had been a prisoner in Derby almost a year,
whereof six months in the house of correction,
and the rest of the time in the common gaol and prison.`"

Once more at liberty, he pursued his course through many of the northern counties,
preaching with so much power, that he was instrumental in bringing an accession,
not only of believers, but also of ministers to the society.

In one place that he visited, in Yorkshire,
he mentions being well received by Justice Hotham,
who was so much struck by the simple eloquence
with which he advocated the cause of truth,
that he much wished to have sent for some of the
neighbouring ministers to discourse with him;
but this George Fox would not agree to, preferring to follow,
as he believed himself at the moment directed.
A curious incident resulting from such an impression,
is too characteristic of his mode of plain dealing, to be omitted.
It occurred whilst staying with Justice Hotham, at Crantsick, in Yorkshire.
"`In the afternoon +++[+++on a first-day]
I went to another steeple-house,`" he says, "`about three miles off,
where preached a great high priest called a doctor,
(being one of them whom Justice Hotham would have sent for to
have spoken with me.) So I went into the steeplehouse,
and stayed till the priest had done.
Now the words which he took for his text were these; "`Ho, every one that thirsteth,
come ye to the waters, and he that hath no money, come ye, buy and eat; yea come,
buy wine and milk, without money and without price.`"
Then was I moved of the Lord God to say unto him '`Come down, thou deceiver!
Dost thou bid people come freely, and take of the water of life freely,
and yet thou takest three hundred pounds a year of them?
Mayest thou not blush for shame?
Did the prophet Isaiah, and Christ do so, who spake the words, and gave them forth freely?
Did not Christ say to his ministers whom he sent to preach, '`freely ye have received,
freely give?`'
So the priest, like a man amazed, hastened away, and after he was gone,
and had left his flock, I had as much time as I could desire to speak to the people.`"

In recording the memorial of some of the primitive Friends,
the name of Francis Howgill must not be forgotten;
his useful labours and patient sufferings, as a minister amongst them,
appointing him a prominent place in their history.

He was born about the year 1618, and resided near Grayrigg, in Westmoreland.
He had been educated at one of the universities, and had entered the church;
but being dissatisfied with what he conceived to be corrupt in it,
he separated therefrom, and joined a party of Independents,
amongst whom he became a minister.
But as he has left a record of his religious experience,
we may obtain from his own statement, the best view of his feelings on this point.

"`From twelve years old,`" he says,
"`I set my heart to know that God whom the world professed,
and whom I read of in the Scriptures; and I fell into the strictest worship that was,
in that part wherein I lived, and often I desired to be alone,
and attended much to reading and meditation.`"^
footnote:[Memoirs of Francis Howgill, by James Backhouse, p. 14.]

After describing the various convictions of his conscience,
and his sometimes obeying and sometimes resisting them, "`when I turned within`" he says,
"`I was judged for all my former iniquities,
and my heart was still shown to me that it was corrupt; but,
as I kept within to the light in my conscience,
I was restrained from many actions that I had a will to do;
and in the instant when I was doing any unrighteousness in actions or words,
I was often stopped; and when I saw that I did it not, a great joy arose in me;
but when I had done anything forwardly, or rashly, was judged.`"

Surely we have, in this simple statement,
a practical illustration of that allusion to the purifying
nature of God`'s "`judgments`" with which the Scriptures,
(and the Psalms especially,) abound!
Indeed, it may be asked, how we are to understand this word judgment,
(in the 119th Psalm for instance,) except in this sense of inward
correction and instruction?--"`I have chosen the way of truth;
thy judgments have I laid before me.`"
(30.) "`Teach me good judgment and knowledge.`"
(65.) "`I know, O Lord! that thy judgments are right,
and that thou in faithfulness hast afflicted me.`"
(75.) "`I have not departed from thy judgments, for thou hast taught me.`"
(102.) "`My flesh trembleth for fear of thee, and I am afraid of thy judgments.`"
(120.) These quotations might, from the same Psalm, be greatly extended;
but I leave the subject for the thoughtful reader`'s serious, and I trust,
profitable consideration, and return to the narrative of Francis Howgill.

"`But this`" he continues,
(still speaking of the interior judgment upon his thoughts and ways, above alluded to;
"`but this, the teachers said, was a natural conscience, that kept from sin,
and restrained it;) so I hearkened to their imaginations, and slighted the light,
as too low a thing, that was but common grace that preserved me out of gross evils.`"

"`The saints,`" these teachers assured him, "`had a peculiar grace and faith,
and believing in Christ, his righteousness was accounted to be theirs,
and no sin was imputed to them.`"
But although he paid attention to their statements,
he could find no comfort under the burden of sin, which he continued to feel.
"`I fasted and prayed,`" he says, "`and walked mournfully in sorrow,
and thought none was like me, tempted on every hand.
So I ran to this man and the other, and they applied promises to me,
but it was only in words;
for the witness of Christ showed me that the root of iniquity stood,
and that the body of sin was whole.
Then I told them there was guilt in me; and they said that sin was taken away by Christ,
but the guilt would still remain whilst I lived;
and brought me the saints`' conditions to confirm it.
But I said in myself, this was a miserable salvation,
that the guilt and condemnation of sin should still stand in me.
Thus I was tossed from mountain to hill, and heard them preach confusion;
and therefore I mattered not for them, and said,
'`Surely this is not the ministry of Christ!`'`" The
conclusion he deduced from these conflicts was,
"`that none walked as the ministers of Christ;
none that pretended to the ministry had any such gift, neither pastor nor teacher;
nor were any of them such members as were in the apostles`' time.`"

Nevertheless, he was deeply impressed with a belief that better days were at hand;
a hope which was not disappointed; for after being by these,
and various other probations,
prepared by the invisible hand of Providence for
the place and work hereafter to be assigned him,
he fell in with George Fox, who, in the course of his travels, came to Sedburgh,
in the west of Yorkshire, where Francis Howgill happened to be also.

The account of the meeting at which he received the
convictions that ever after remained with him,
is preserved in George Fox`'s Journal.

"`The next first-day, (1652,)`" says Fox, "`I came to Firbank chapel, in Westmoreland,
where Francis Howgill and John Audland had been preaching in the morning.
While others were gone to dinner, I went to a brook, got a little water,
and then came and sat down on the top of a rock by the chapel.

"`In the afternoon the people gathered about me, with several of their preachers.
It was judged there were above a thousand people,
to whom I declared God`'s everlasting truth, and word of life, freely and largely,
for about the space of three hours; directing all to the Spirit of God in themselves,
that they might be turned from darkness to light, and believe in it,
that they might become children of it, and might be led into all truth,
and sensibly understand the words of the prophets, of Christ, and of the apostles;
and might all come to know Christ to be their teacher to instruct them,
their counsellor to direct them, their shepherd to feed them,
their bishop to oversee them, and their prophet to open divine mysteries to them,
and might know their bodies to be prepared, sanctified,
and made fit temples for God and Christ to dwell in.
In the openings of heavenly life, I explained unto them the prophets, and the figures,
and shadows, and directed them to Christ the substance.
Then I opened the parables and sayings of Christ, and things that had long been hid;
showing the intent and scope of the writings of the apostles.
I showed also the state of the apostacy since the apostles`'
days--that the priests have got the Scriptures,
but are not in the spirit which gave them forth, but make a trade of holy men`'s words,
and are found in the steps of the false prophets, chief priests,
scribes and pharisees of old, and are such as the true prophets,
Christ and his apostles cried out against.`"

If these remarks should seem somewhat harsh and unqualified, we must bear in mind,
that one of the strongest features of this period,
was a timeserving spirit amongst the priesthood;
a trait in the characters of too many of them,
which was curiously exhibited by the fact that several veered
round with all the changes of those inconstant times;
being Episcopalians with the first Charles and his bishops;
Presbyterians with Oliver and the parliament;
again on the side of the Episcopacy at the restoration;
and probably would have been as ready to unite with the Papists,
if Charles the Second had established Popery instead of Protestantism.`"^
footnote:[See "`Neale`'s History of the Puritans,`"
where some of these instances are recorded;
and also "`Sewel`'s History of Friends,`" vol. i. p. 209,
(edition printed at Lindfield,) where he says,
"`One Thomas Curtis, who was formerly a captain in the parliament army,
but afterwards entered into the society of the people called Quakers, wrote,
in a letter to Samuel Wells, priest of Banbury,
and a persecutor of those of that persuasion, amongst other words,
"`To thy shame remember, I know thee scandalous;`" and relating on what account,
the historian adds,
that "`none need think it strange that the Quakers called such as him, hirelings;
and that there were not a few of that sort, appeared plainly,`" he says,
"`when King Charles was restored; when those who had cried out against Episcopacy,
turned round, and put on the surplice to keep their livings, etc.`"]

A very great convincement accompanied the preaching of this sermon,
and both Howgill and Audland, from that time, united with the Quakers,
and became eminent ministers in the society.
Of Howgill`'s services, George Fox has left a short record, wherein he observes,
that he was one of the Lord`'s worthies, who preached the everlasting word of life,
from about the year 1652 until 1668.

It was in the course of these travels in the north, and in this year,
(1652,) that George Fox was made instrumental in convincing the mind of a person,
who afterwards, also distinguished himself as a champion in the cause of truth.
His name was Edward Burrough, at that time little more than a youth,
but endued with a mind of extraordinary powers.

This young man was a native of Westmoreland, and, for the times in which he lived,
pretty well educated, being trained up in such learning as his country afforded.
Like many other thoughtful persons in that age,
taking an interest in the subject of religion,
he conversed frequently with those who were in esteem for their piety.
He had been educated in the Episcopal worship,
but preferring the mode of the Presbyterians, he joined that sect, although dissatisfied,
in many respects, with what he saw in them; perceiving that, in general,
they were not in possession of the principles which they advocated.
In this state of mind, he heard George Fox, who, in the course of his travels,
coming to Kendal, had a meeting in the town-hall, which Burrough attended; and which,
without absolutely convincing, made such an impression upon him,
that he came afterwards to Fox, to reason with him upon what he had advanced;
and received so much illumination from his replies,
that doubting no more respecting his doctrines,
he himself henceforth became a preacher of them.

And now we approach some circumstances in the life of George Fox,
which had a material and lasting influence upon his history,
and also upon that of the society.
These circumstances were, his acquaintance, intimacy, and, many years afterwards,
his marriage with Margaret Fell, the wife of Judge Fell, of Swarthmore, in Lancashire.
An account of his first introduction to her, I transcribe, as recorded by herself.^
footnote:[Margaret Fox`'s testimony respecting her husband, prefixed to his Journal.]
"`And in the year 1652,`" she says, "`it pleased the Lord to draw him towards us;
so he came on from Sedburgh, etc. and John Blakeling came with him.
My then husband, Thomas Fell, was not at home at that time, but gone the Welsh circuit,
being one of the judges of assize;
and our house being a place open to entertain ministers and religious people at,
one of George Fox`'s friends brought him hither, where he stayed all night;
and the next day, being a lecture, or a fast-day, he went to Ulverstone steeple-house,
but came not in till the people were gathered.
I and my children had been there a long time before.
When they were singing before the sermon, he came in, and when they had done singing,
he stood upon a seat or form, and desired that he might have liberty to speak,
and he that was in the pulpit said he might.^
footnote:[If this intrusion on the part of George Fox,
and this concession on the side of "`he that was in the pulpit,`" should,
at the present day, appear strange, we must remember,
that independently of the mode of worship of the Church of England being then abolished,
there was a liberty of religious discussion professed, which no doubt prompted this,
and many more of the like measures adopted by George Fox and the Friends in general.]

She goes on to relate, that the first words that he spoke, were as followeth:
"`'`He is not a Jew that is one outwardly; neither is that circumcision which is outward;
but he is a Jew that is one inwardly; and that is circumcision which is of the heart.`'

"`And so he went on, and said, that Christ was the light of the world,
and lighteth every man that cometh into the world,
and that by this light they might be gathered to God, etc.
I stood up in my pew and wondered at his doctrine, for I had never heard such before.
And then he went on and opened the Scriptures, and said,
the Scriptures were the prophets`' words, and Christ`'s and the apostles`' words, and what,
as they spoke, they enjoyed and possessed, and had from the Lord.-- Then,
what had any to do with the Scriptures,
but as they came to the Spirit that gave them forth?
You will say, Christ saith this, and the apostles say this; but what canst thou say?
Art thou a child of light, and hast walked in the light?
and what thou speakest, is it inwardly from God?`" etc.

She then describes, in much simplicity,
the effect which his address produced upon her mind.
"`It cut me to the heart,`" she says, "`and I saw clearly, that we were all wrong;
so I sat down in my pew again, and cried bitterly; and I cried in my spirit to the Lord,
'`We are all thieves--we are all thieves!^
footnote:[Those words of our Lord, "`he that entereth not by the door into the sheepfold,
but climbeth up some other way,
the same is a thief and a robber,`" seem to receive an
illustration in these convictions of Margaret`'s.]
We have taken the Scriptures in words, and know nothing of them in ourselves!`"

But although permitted to begin his address,
it seems that he was not allowed to conclude it without opposition;
for she goes on to relate, that whilst he was declaring against the false prophets,
deceivers of the people, etc., one John Sawrey, a justice of peace,
and a religious professor, desired the churchwarden to take him away.

It does not, however, appear, but that George concluded what he had to say; for she adds,
that "`after awhile, he gave over, and came to our house again that night,
and he spoke in the family amongst the servants, and they were all generally convinced.`"

She speaks of her own impressions as very strong and clear;
"`I saw it was the truth,`" she says, "`and I could not deny it;
and I did as the apostle saith, I received the truth in the love of it.`"

Nevertheless, her husband being from home, and apparently,
the utmost harmony subsisting between them,
she could not but feel anxious till she knew how
her change of sentiment would be received by him.
"`I was stricken into such a sadness,`" she says, "`I knew not what to do,
my husband being from home.`"

In this state she received some comfort by a visit from two ministers of the society,
James Naylor and Richard Farnsworth, who being in quest of George Fox,
came to Swarthmore, about two weeks after this period.
"`They stayed awhile,`" she says, "`at our house, and did me much good,
for I was under great heaviness and judgment.`"
In about three weeks, Judge Fell returned from his circuit;
and as there are seldom wanting busy spirits who
delight in being on the alert to relate grievances,
the good man was met on the way to his own house,
by many of those whom Margaret calls "`the great ones of the country;`" who
furnished him with no very pleasant intelligence,
respecting what had been going on in his absence;
and consequently disposed him to return home greatly offended.
"`He was very much troubled,`" she says, "`with us all, in the house and family,
they had so prepossessed him against us.
But James Naylor and Richard Farnsworth were both then at our house,
and I desired them to come and speak to him,
and so they did very moderately and wisely.`"
The result of the whole was, that he became pacified; and after some hours, George Fox,
who seems to have been absent at the first return of Judge Fell, came back to the house.

"`And then at night,`" she says, "`George Fox came; and after supper,
my husband was sitting in the parlour, and I asked him if George Fox might come in?
And he said, "`Yes;`" so George came in, without any compliment,
and walked into the room, and began to speak presently; and the family, and James Naylor,
and Richard Farnsworth came all in.`"

George spoke so excellently, that, "`if all in England had been there,`" says Margaret,
"`I thought they would not have denied the truth of those things;`" and Judge Fell,
being a man of an impartial and temperate mind, received,
with the attention they deserved,
the deep and important truths which were thus unexpectedly, and unadornedly,
set before him.
"`My husband,`" she says, "`came to see clearly the truth of what he spoke,
and was very quiet that night, and said no more.`"
It was evident that his mind had received a strong
impression in favour of what had been advanced;
for, when the priest of Ulverstone, one Lampitt, called upon him the next day,
for the purpose of engaging him to act against the Quakers,
he found him indisposed to any such measures;
and although Judge Fell did not himself unite with them,
he not only offered no resistance to the union of his wife and family with the society,
but hearing several friends speaking in his presence,
of there being some difficulty in obtaining a place to meet in,
there being a large increase of their numbers in that part of the country,
"`he said of his own accord,`" as his wife relates, "`you may meet here if you will.`"
And then notice was given that day and the next to Friends;
and there was a good large meeting the first-day,
which was the first meeting that was at Swarthmore.`"

It is worthy of remark, that the meeting, thus set up in 1652,
continued in its appointed order till 1690.

After this introduction to Judge Fell, George Fox was well received by him,
in his future visits at his house; in one of which, in the same year,
he held a conference with some of the clergy, or, as he expresses it,
"`with four or five of the priests.
And coming to discourse,`" he says,
"`I asked them '`whether any one of them could say he ever had
the word of the Lord to go and speak to such or such a people?
None of them durst say he had; but one of them burst out into a passion, and said,
'`he could speak his experiences as well as I.`' I told him that experience was one thing;
but to receive and go with a message, and to have a word from the Lord,
as the apostles and prophets had and did, and as I had done to them,
this was another thing; and therefore I put it to them again,
could any of them say he had ever had a command
or word from the Lord immediately at any time.
But none of them could say so.
Then I told them the false prophets and false apostles and antichrists,
could use the words of the true prophets, and true apostles, and of Christ,
and would speak of other men`'s experience,
though they themselves never knew nor heard the voice of God and Christ.`"

"`At another time,`" he says, "`when I was discoursing with several priests,
at Judge Fell`'s house, and he was by, I asked them the same question,
whether any of them ever heard the voice of God or Christ,
to bid him go to such or such a people, to declare his word or message unto them?
for any one, I told them, that could but read,
might declare the experiences of the prophets and apostles,
which were recorded in the Scriptures.
Hereupon, one of them, whose name was Thomas Taylor, an ancient priest,
did ingenuously confess before Judge Fell, that he had never heard the voice of God,
nor of Christ, to send him to any people; but he spake his experiences,
and the experiences of the saints in former ages, etc.
This very much confirmed Judge Fell in the persuasion he had,
that the priests were wrong; for he had thought formerly,
as the generality of the people then did, that they were sent from God.

"`This Thomas Taylor,`" he states, "`was convinced at this time,
and travelled with me into Westmoreland; where it appears that,
though so newly converted from his former sentiments,
he preached boldly in condemnation of his first errors; and,`" says George,
"`like the good scribe that was converted to the kingdom,
he brought forth things new and old to the people.`"

And now that persons who were higher graduated in education, began to look at,
and consider the doctrines of Friends,
the persecution which attended them became more violent and general.
James Naylor and Francis Howgill were committed to Appleby gaol; the former,
under a pretence of his having spoken blasphemy;
and the latter for remarking that he had seen a good
deal of tyranny and persecution in that day`'s actions;
an observation to which the justice who was examining him, replied,
by turning to the people, and saying, "`Take notice, he saith the law I act by,
is tyranny and persecution;`" to which the people assented.
"`Then,`" said Francis, "`thou mayest give out to the people what thou wilt;
but I speak not of the law, but of your actions.`"
Upon that they made out a mittimus to send him to prison, etc.^
footnote:[Howgill`'s Life by Backhouse, p. 30.]
After being, together with James Naylor, confined in Appleby gaol for five months,
he was released.

George Fox, in the meanwhile, was valiantly contending for the faith,
in the northern counties, to which at present his labours were chiefly confined;
and in the prosecution of which,
he largely shared with his brethren in suffering and opposition.
To relate all the instances which he himself has recorded,
of his trials and provings in this respect,
would be to exhibit a very degrading picture of human nature; and one that,
in these happier days of religious toleration, could scarcely, perhaps,
be received as a faithful representation;
for in this age of diffusive education and more civilized feeling,
we may indeed hope that it would be difficult to find the
district whose inhabitants could unite in the display of such
barbarity as that spoken of in the following narration.

"`On a lecture-day,`" he says, "`I was moved to go to the steeple-house at Ulverstone,
where were abundance of professors, priests, and people.
I went up near to priest Lampitt, who was blustering on in his preaching;
and after the Lord had opened my mouth to speak, John Sawrey, the justice,
came to me and said, if I would speak according to the Scriptures, I should speak.
I stranged +++[+++wondered]
at him for speaking so to me, for I did speak according to the Scriptures;
and I told him I should speak according to the Scriptures,
and bring the Scriptures to prove what I had to say;
for I had something to speak to Lampitt and to them.
Then he said I should not speak; contradicting himself, who had said just before,
I should speak, if I would speak according to the Scriptures, which I did.
Now the people were quiet, and heard me gladly, until this Justice Sawrey,
(who was the first stirrer up of cruel persecution in
the north,) incensed them against me,
and set them on to hale, beat, and bruise me.
Then, on a sudden, the people were in a rage, and they fell upon me in the steeplehouse,
before his face, and knocked me down, and kicked me, and trampled upon me, he looking on;
and so great was the uproar, that some people tumbled over their seats for fear.
At last he came and took me from the people, and led me out of the steeple-house,
and put me into the hands of the constables and other officers,
bidding them whip me and put me out of town.
Then they led me about a quarter of a mile, some taking hold by my collar,
and some by my arms and shoulders, and shook and dragged me along;
and there being many friendly people come to the market,
and some of them come to the steeplehouse to hear me,
divers of these they knocked down also, and brake their heads,
so that the blood ran down from several of them; and Judge Fell`'s son,
running after to see what they would do with me, they threw him into a ditch of water,
some of them crying '`Knock the teeth out of his head.`'
Now, when they had haled me to the common moss-side, a multitude of people following,
the constables and other officers gave me some blows over my back with their willow-rods,
and thrust me among the rude multitude; who, having furnished themselves,
some with staves, some with hedge-stakes, and others with holm or holly-bushes,
fell upon me, and beat me on my head, arms, and shoulders, till they had amazed +++[+++stunned]
me, so that I fell down upon the wet common; and when I recovered myself again,
and saw myself lying on a watery common and the people standing about me,
I lay still a little while; and the power of the Lord sprung through me,
and the eternal refreshings refreshed me,
so that I stood up again in the strengthening power of the eternal God,
and stretching out my arms amongst them, I said with a loud voice,
'`Strike again!--here are my arms--my head-- and my
cheeks!`" an invitation which was not unheeded;
for he proceeds to state that "`there was in the company a mason, a professor,
but a rude fellow; he, with his walking rule-staff, gave me a blow with all his might,
just over the back of my hand, as it was stretched out;
with which blow my hand was so bruised, and my arm so benumbed,
that I could not draw it unto me again; so that some of the people cried out,
'`he hath spoiled his hand from having any use of it more.`'
But I looked at it in the love of God,
(for I was in the love of God to them all that had persecuted
me,) and the Lord`'s power sprung through me again,
and through my hand and arm, so that in a moment I recovered strength in my hand and arm,
in the sight of them all.`"

I, unwillingly, contemplate the possibility,
that this instantaneous supply of divine aid from the
Creator to his helpless and oppressed creature,
may be questioned; but if it should,
I can only entreat of the querist to examine the spirit which suggests the doubt;
and I think it will appear extremely difficult to
allege any other reason for disputing the matter,
than want of faith; a deplorable want, which keeps the professing church of Christ,
and whilst it subsists, ever must keep it, in poverty and destitution;
since we can only expect that the Divine Being should withdraw
the manifestation of his glorious presence and power,
wherever his willingness to bestow that manifestation is called in question.

So overpowering was the effect of this immediate restoration,
that the people were astonished, and began to fall out amongst themselves;
some of them offering, if he would give them money,
to secure him from the fury of the rest; but,
equally disdaining their protection or their persecution,
he addressed them upon the subject of their state and condition;
telling them they were more like heathens and Jews than true Christians,
and showing to them the fruits they were bringing forth,
from the ministry of those they were so zealously defending.

He then walked away to Ulverstone, and went through the market;
in going to which place a soldier met him,
and expressing grief to see him so ill-used as he had just been, offered to assist him;
"`but I told him,`" says George, "`the Lord`'s power was over all;
so I walked through the people in the market, and none of them had power to touch me.`"
Having finished his service there, he went to Swarthmore,
where he found his friends sufficiently employed in dressing
the wounds of those who had been hurt in the day`'s proceedings;
and in respect to himself, he says, "`my body and arms were yellow, black, and blue,
with the blows and bruises I received amongst them (viz. the religious professors,
etc.) that day.`"

Nevertheless, in about two weeks after, in going with James Naylor to Walney island,
and having a meeting at a little town called Cockan, he met with similar,
and even worse treatment;
so fearfully excited were the people against the subjugating
doctrines which the quiet ministry of Friends exhibited.
Nor is this extraordinary; since "`they that are after the flesh,
do mind the things of the flesh,`" and nothing else,
how can they bear to hear of that which preaches death
to everything that makes their life and happiness.
The fleshly mind loves words,--friends were very sparing of them;
it seeks honour from man--friends disowned and denounced all worldly distinctions;
it covets ease and indulgence--friends held up
the cross of Christ to everything of the sort.
Theirs was not the lip profession only of "`Lord,
thou knowest that I love thee`"--or the mere say so,
of "`I am ready to go with thee to prison or to death`"--but
it was the realization of Christ`'s meek and loving,
and self-crucifying gospel,
which they not merely preached but lived;--and
this was the offence which the flesh never did,
nor never can forgive; --for whilst the world continues,
"`the carnal mind is enmity against God,`" and, if against God,
against his ministers also.

I do not propose, however, to pain my reader or myself,
by any further detail of the sufferings of this patient and persecuted people,
than may be necessary for the true delineation of their primitive character;
I shall therefore merely state,
in reference to the cruelties exercised against George Fox, in the island of Walney,
that having narrowly escaped with his life, he was so severely bruised,
as to be scarcely able to bear the shaking of the horse
on which he next day rode to Swarthmore.
When he arrived there, the Justice Sawrey before spoken of,
and another justice named Thompson, of Lancaster, issued a warrant to apprehend him;
but Judge Fell (who had been absent during these atrocities) coming home,
it was not served upon him; but on the contrary,
the judge himself sent out warrants to apprehend the persons in the isle of Walney,
who had behaved so barbarously towards George Fox.
But George himself, so far from desiring this,
could not be prevailed upon to make any relation of the matter to his friend the judge:
saying, that "`the people could do no otherwise, considering the spirit they were in.`"

When the time of Lancaster Sessions came round,
though not apprehended by the warrant above-mentioned, he chose to appear there;
and being on the way thither with Judge Fell, the latter observed to him,
"`that he had never had such a matter brought before him,
+++[+++as that which was alleged against George,]
and he could not well tell what to do in the business.
Upon which, I told him,`" says George, "`that when Paul was brought before the rulers,
and the Jews and priests came down to accuse him,
and laid many false things to his charge, Paul stood still all that while;
and when they had done, King Agrippa beckoned to him to speak for himself:
which Paul did, and cleared himself of all those false accusations;
and so he might do by me.`"

The charge against him was, that he had depreciated the Scriptures,
and in other respects had spoken blasphemy; to support which accusations, there appeared,
as he states, "`about forty priests.`"
But upon examination of these witnesses, it turned out, that one and another of them,
could only say that they had heard he should speak so and so;
insomuch that the justices observed to them,
"`it seems you did not hear these words spoken yourself, though you have sworn it!`"

"`There were then in court,`" says George, "`several people who had been at that meeting,
wherein the witnesses swore I spake those blasphemous words,
which the priests accused me of;
and these being men of integrity and reputation in the country,
did declare and affirm in court,
"`that the oath which the witnesses had taken against me, was altogether false,
and that no such words as they had sworn against me, were spoken by me at that meeting.`"

So powerful an effect did their evidence in behalf of the simple truth,
produce upon the mind of Colonel West, a justice then upon the bench,
that being but infirm in health, he said,
"`the Lord had healed him that day;`" adding that "`he
never saw so many sober people and good faces together,
in all his life;`" and then turning to George Fox, he said, "`George,
if thou hast anything to say to the people,
thou mayest freely declare it;`" a permission of which George availed himself.

The substance of his address consisted in a declaration that
the Holy Scriptures were given forth by the Spirit of God,
and that therefore persons must, in the first place,
know the Spirit of God in themselves, in order to know God and Christ,
of whom the prophets and apostles learnt; and that, by the same Spirit also,
they could alone know the Holy Scriptures; for,
as the Spirit of God was in those persons who gave forth the Scriptures,
so the Spirit of God must be in all those that
come to know and understand the Scriptures;
and by this Spirit also, they might have fellowship with the Son, and with the Father,
and with the Scriptures, and with one another; and without this Spirit,
they would neither know God nor Christ, nor the Scriptures,
nor have right fellowship one with another.
"`I had no sooner spoken these words,`" he says,
"`but about half-a-dozen priests that stood behind my back, burst out into a passion;
and one of them whose name was Jackus,
amongst other things that he spake against the truth, said,
"`that the Spirit and the letter were inseparable.`"
I replied, "`then every one that hath the letter hath the Spirit;
and they might buy the Spirit with the letter of the Scriptures!`"

So preposterous a statement as that of Jackus,
occasioned Judge Fell and Colonel West to express their disapprobation;
"`according to such a position,`" they said,
"`they might carry the Spirit in their pockets,
as they did their Bibles!`" a remark which caused a great deal
of resentment amongst those to whom it was addressed.
The result of the inquiry was, that George Fox was discharged,
to the satisfaction of the greater part of the assembly; amongst which,
were some who received deep and lasting impressions of divine truth,
from the plain sincerity with which he had declared it;
and those none of the meanest neither; one, Justice Benson, and the Mayor of Lancaster,
whose name was Ripan, being of the number.
A person of the name of Briggs, a parishioner or hearer of Jackus,
and who had been a violent opposer of Friends,
became also that day a convert to their religious views, and in due time,
a faithful minister in the society; continuing such to the end of his life.

Thus honourably exonerated from the charge of blasphemy, George Fox continued,
through the divers persecutions of jangling opposers,
and now and then a beating or stoning, etc.,
to pursue his course till the following year; when, finding his way to Carlisle,
and preaching there, with his accustomed boldness,
it was not long before he was again sent to prison,
upon the old charge of being a blasphemer, etc.; a charge, of all others,
which at first sight appears the most singular to be preferred
against a man who was exhibiting a constant willingness to suffer,
even to the hazard of his life, for the defence of the gospel.
Yet, looking at the whole, unbroken, and easeful condition of his accusers,
and at the false views of Christ`'s religion by which
they pacified their consciences in such a state,
we cannot much wonder that they stigmatized him with the character of a blasphemer; for,
in preaching against their indulgences, or, in other words, against the "`gods many,
and lords many,`" that were the real objects of their worship, he, no doubt,
was guilty of sacrilege in their eyes.
That this was the true foundation of such a charge, we may well infer,
because experience proves, that there never has been a ministration of the Spirit,
which has not drawn upon the minister thereof, this accusation of being a blasphemer,
or a denier of some of the leading doctrines of Christianity.
Not to mention the case of Fenelon, or that of Madame Guion, or of Molinos,
on the continent, or that of the pious and blessed William Law, in our own country,
and many more that might be spoken of,
let us look at the testimony of Scripture to this point;
and here we find the great apostle of the Gentiles,
whilst a persecutor of the followers of Christ,
and whilst zealous for the law or the letter,--in high
acceptation with the Scribes and Pharisees,
or the doctors of divinity of the Jewish church; but the same Paul,
preaching Jesus and the resurrection,
and stating that he had received an immediate revelation and command from his master,
is greeted with, "`Away with such a fellow from the earth,
for it is not fit that he should live.`"^
footnote:[Acts 22:21-22, and also (ch. xxiv.
5,) where he is accused of being "`a pestilent fellow and a mover of sedition,`" etc.]
But need we seek for further instances,
to prove how inherent is this disposition in the unregenerate heart,
to stigmatize with the worst epithets, the purest doctrine:
seeing that it was levelled against the Fountain of Purity itself?
"`For a good work,`" say the real blasphemers to the holy Jesus,
when he meekly asks of his barbarous persecutors,
for which of his good works were they about to stone him,
"`for a good work we stone thee not; but for blasphemy!`"^
footnote:[John 10:33.]
