== Chapter IV.

Whilst George Whitehead and others were labouring and
suffering in the work of the ministry in the eastern counties,
Francis Howgill and Edward Burrough were similarly occupied in London;
whither they arrived in 1654, accompanied by Anthony Pearson,
the justice before mentioned, who had also become a preacher of righteousness.
These persons are said to have been the first who
publicly preached the doctrines of Friends in London.

There is a curious incident recorded by Sewel,
relative to the service of Edward Burrough, at this time.
He relates that, as he was passing, one summer`'s evening,
near a place where some persons were amusing themselves by wrestling with each other,
he observed a strong and dexterous man, who had thrown three opponents,
to be in vain challenging a fourth to enter the lists with him,
upon which Burrough himself stept into the ring.

The wrestler, anticipating the usual light, airy countenance of one of his own stamp,
was not a little surprised to see before him a young man,
whose composed and solemn demeanour might tell him, at a glance,
what kind of combat was about to take place.

Beginning to speak with much seriousness,
his address was accompanied (as Sewel expresses it) "`with such a heart-piercing power,
that he was heard by this mixed multitude with no less attention than admiration;`" for,
as he describes E. B. "`he was a breaker of stony hearts, and therefore,
by a certain author, not unjustly called a son of thunder.`"
And again, in speaking of his powerful gift,
"`to thunder against sin and iniquity,`" he says, "`was his peculiar talent.`"^
footnote:[P. 223. Lindfield edit.
Vol. i.]

After various meetings in the metropolis, in most of which,
though greatly opposed by Baptists and Ranters,
their plain and powerful appeals reached to the conscience of most of their hearers,
and awakened earnest desires of salvation, in the autumn of the year,
Howgill and Burrough went to Bristol, and the first Sabbath following,
had a meeting in the castle, which was attended by many hundreds of people,
and on every successive meeting (of which they
had several) an increase of numbers appeared.

It may be supposed that under these circumstances,
they would soon attract attention and inquiry from the authorities of the place;
and accordingly, the second week after their arrival, a sergeant was sent from the mayor,
alderman, justices of the peace, etc., assembled in the townhall,
desiring them to appear before the council.
On first appearing there,
having civilly informed the magistrates that they were come thither,
according to the request sent them, their not putting off their hats excited displeasure,
the magistrates inquiring, "`if they knew to whom they spoke?`"
They replied that they believed they were before the magistrates or rulers of the city;
and the hat being objected to,
they said that they did not omit putting it off in contempt of authority,
but for conscience sake.

A variety of questions were then asked and answered,
as to the reason of their coming to Bristol; and nothing being found against them,
the magistrates concluded the examination by commanding them to depart out of the city;
a mandate which they received, by stating, "`that they neither came, nor stayed,
in the will of man;`" and after a few more words to the same effect, they left the court,
but not the place, having several large meetings after this time,
at one of which it is supposed there were about three thousand persons present.

In company with Edward Burrough, Francis Howgill again visited London, and other places,
and also Ireland, where they spent three months in Dublin, without being disturbed;
but before the close of their visit in Ireland,
persecution was stirred up against them by the priesthood;
who procured an order from government, for the apprehension of Francis Howgill,
he being then in the country, preaching with much success in a garrison of soldiers,
the governor of which garrison was kindly disposed towards him.
These envious men sent him bound to Dublin, and from thence he was dispatched to Cork;
where the justices who examined him,
perceiving that malice was the real ground of the accusations brought against him,
set him at liberty.
At Cork he was again joined by Edward Burrough,
from whom he had been for a short time separated;
but the priests of that nation obtained an order from Henry Cromwell,
then Lord Deputy of Ireland, to banish them from that country;
and a guard of soldiers was ordered to conduct them from place to place,
till they were shipped off.
These soldiers, however, were kind to them,
and suffered them to hold meetings in their travels;
by which means many received the knowledge of the truth.

After returning from Ireland, Francis Howgill and Edward Burrough,
separating for a while, went through many counties of England, holding numerous meetings,
and met again at Bristol, at the time of the fair, where they had a meeting one Sabbath,
of about five thousand people.

The city of Bristol was, in particular,
a scene of such strange and cruel persecution of the Quakers,
that to narrate the circumstances of their different sufferings,
in this place would of itself make a volume.
But, besides that I may well hope to be forgiven for
omitting to enter into so painful a detail,^
footnote:[A minute account of the transactions alluded to,
and of the severe trials of the primitive Quakers in general,
may be found in [.book-title]#Besse`'s Sufferings of Friends#; the bare relation of which,
occupies two closely printed folio volumes;
and in which are records of cruelty on the one hand,
and of Christian patience on the other, which, unless too well authenticated,
would scarcely be credited as having actually occurred.]
I profess to confine myself in the present work,
to sketch rather than portray the history of the primitive friends.

I do not therefore stop to relate the occurrences connected with them in this place;
it may suffice to give the reader an idea how preposterous, oftentimes,
were the pleas made use of to trouble these unoffending people,
if I present him with the following warrant, which, on one occasion,
was issued against them by the magistrates.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`City of Bristol.

[.salutation]
"`To the constables of the peace, of the ward of +++_______+++, and every of them.

"`Forasmuch, as information hath been given unto us upon oath,
that certain persons of the Franciscan order, in Rome,
have of late come over into England, and under the notion of Quakers,
drawn together several multitudes of people in London.
And whereas, certain strangers, going under the names of John Camm, John Audland,
George Fox, James Naylor, and Edward Burrough, and others unknown,
have lately resorted to this city, and in like manner, under the same notion of Quakers,
drawn multitudes of people after them, and occasioned very great disturbances amongst us;
and forasmuch, as by the same information, it appeareth to us to be very probable,
and much to be suspected, that the said persons so lately come hither,
are some of those that came from Rome, as aforesaid.
These are, therefore, in the name of his Highness the Lord Protector,
to will and require you to make diligent search
throughout your ward for the aforesaid strangers,
or any of them, and all other suspected persons,
and to apprehend or bring them before us, or some of us,
to be dealt with according to law.

[.signed-section-context-open]
"`Hereof fail not.
Given the 25th of January, 1654.

[.signed-section-signature]
"`Signed, John Gunning, Mayor, and eight others have added their signatures.`"

--

Whilst at Bristol, on the occasion of the large meeting above mentioned,
Edward Burrough was called to London,
by hearing that some of their society had been deluded into erroneous views and notions,
which threatened a loss of comfort and union amongst Friends;
and shortly after his departure, he was joined by his faithful friend and coadjutor,
Francis Howgill, who laboured with him for the restoration of these seceders.

But little is recorded of Francis Howgill, from about this period till the year 1661,
when he was imprisoned in London, with many others,
on suspicion of being concerned in the insurrection of the Fifth-monarchy-men.
But being liberated from this charge, he travelled into various parts of the nation,
preaching the gospel, in which service he was eminently blessed with success.

In the latter end of the year 1662,
he was called to the melancholy task of bearing a last
testimony to the memory of his dear friend and companion,
Edward Burrough; who ended his short but valuable life in Newgate,
dying there a prisoner for the truth`'s sake.

The convincement of this young man, through the ministry of George Fox,
united him at a very early age with the society; in which his extraordinary endowments,
both of nature and grace, rendered him so useful,
that his premature death was more than commonly felt,
as it was more than commonly regretted by the friends in general.
George Fox, in his Journal, alludes to it, by saying, "`passing from thence to Sutton,
and into Cambridgeshire, I heard of Edward Burrough`'s decease;
and being sensible how great a grief and
exercise it would be to friends to part with him,
I wrote the following lines for the staying and settling of their minds.`"

The lines alluded to are but few, and expressed in his own peculiar mode,
which ever turned the soul to the divine seed, or holy germ of eternal life within it,
for all it stood in need of.
"`Be still and quiet,`" he says, "`in your own conditions,
and settled in the seed of God, that doth not change;
that in that you may feel dear E. B. among you;`"^
footnote:[The spiritual reader will, doubtless,
see an extraordinary depth in this expression.]
and with a few more words to the same effect,
he concludes by reminding them that in doing so,
they may continue to "`enjoy him in the life that doth not change, which is invisible.`"

Nor was it merely as a preacher, that Edward Burrough laboured in the cause of truth:
he was a diligent helper of the oppressed, by seeking at the fountain-head,
for the origin of their griefs, and there endeavouring to remove them.
For this purpose he not only wrote repeatedly to Oliver Cromwell,
to represent the sufferings which, if not occasioned, were at least permitted,
by his authority,
especially in relation to the cruelties which were exercised towards Friends,
touching their refusal to take oaths, and pay to the maintenance of a hired ministry;
but he also obtained a personal hearing from him on these subjects;
and as far as the wily Cromwell would speak intelligibly,
he received from him an assurance that all
persecution and cruelty was against his wishes;
and that he was not guilty of conniving at that
which had been practised towards the Quakers.

But it would seem that such concessions were without sincerity; for shortly after,
Burrough, in a letter to him, says, "`consider what the cause is,
that what thou desirest not to be done, is yet done.
Is it not that thou mayest please men,
by making it appear that thou art more willing to do the false
teachers of this nation and wicked men a pleasure,
than to own the people of God, in relieving them,
and easing them of their cruel burdens and oppressions, laid upon them by unjust men?
For a word of thy mouth, or a show of thy countenance,
in dislike of these cruel and unjust persecutions,
would bind the hands of many blood-thirsty men,`" etc.
It would appear, however, upon the testimony of Sewel,
that notwithstanding these reproofs,
Edward Burrough (and indeed many other sincerely pious men of that
time) had a latent feeling of affectionate interest in Cromwell;
as believing that at one period of his history,
he was certainly in earnest in his religious profession,
though afterwards misled by ambition.
A singular circumstance relative to his funeral, and connected with Edward Burrough,
is thus mentioned in Sewel:--

"`The funeral of Oliver Cromwell,`" he says, "`was solemnized with very great pomp.
On the day of this pompous funeral, which was the 23rd of September,
Edward Burrough came riding from Kingston into London,
not knowing anything of what was done there.
As he entered at Charing Cross,
he beheld a great multitude of people thronging exceedingly,
the streets being filled as far as he could see, and abundance gazing at the windows,
and upon the balconies and housetops.
There were also guards of horse and foot, that stopped his horse,
and it was told him that he might not pass that way.
Yet he did not know what was the matter; but at length,
he perceived that Cromwell`'s image, richly adorned,
was to be carried that way towards Westminster.
The consideration of this was like an arrow that pierced his breast;
and because of this idolatry, he felt such a fire kindled in him, that he was,
as it were, filled with the indignation of the Lord.`"
So ardent was his zeal, as Sewel relates, that, regardless of his own life,
had it been the will of God to require it,
he could have rode through the guards and multitude,
in order to have sounded the judgments of the Lord against such idolatry.
"`Alas for him!`"`' said he within himself, +++[+++alluding to Oliver]
"`who was once a great instrument in the hand of
the Lord to break down many idolatrous images!
Did not the Lord once stir up his heart against all such things?
And did not once his children, officers, soldiers, and army,
pull down all the images and crosses, and all such like popish stuff,
wherever they met with it?
What grievous and abominable work is this!
Have they now made a costly image of him, and are such as were once his soldiers,
now guarding it and watching over it, and his children and officers following it,
and multitudes of the inhabitants of London wondering and gazing after an image of him!`"

"`This zealous testimony,`" continues the historian,
"`Edward Burrough caused to be printed;
whereby he raised to himself a more lasting monument than by the
erecting of a statue to his quondam friend Oliver Cromwell.`"^
footnote:[[.book-title]#Sewel`'s History#, vol. ii. p. 51. Lindfield edit.]

Nor was it only with Oliver as the ruling authority,
that Edward pleaded in behalf of the oppressed;
for in the year of King Charles the Second`'s restoration,
he repaired to him in behalf of the suffering Friends in America;
four of whom had at that time been actually put to death,
by the sanguinary malice of their enemies in that country.
Nor did he unsuccessfully appeal to the king in this matter;
a mandamus being immediately granted to his pressing entreaties,
that the relief in this emergency might be expedited;
but as we shall probably hereafter have occasion
to relate the circumstances of the case itself,
we only briefly allude to Edward Burrough`'s share in it at the present.

In the exercise of his pen, also, he was very serviceable upon many occasions,
wherein the interests of the society were concerned;
more especially in the first year of the restoration of Charles the Second, when,
in consequence of the insurrection of the Fifth-monarchy-men, a new act was made,
which pressed heavily upon the Quakers,
as it required from them a violation of one of
their firmest principles in respect to oaths;
and also forbade their assembling in their usual mode of religious worship.^
footnote:[After stating the case respecting the
refusing to take oaths and the consequent penalties,
the act specifies, "`if the said persons, commonly called Quakers, shall, at any time,
after the four-and-twentieth day of March,
(1661,) depart from the places of their several habitations,
and assemble themselves to the number of five, or more,
of the age of sixteen years or upwards, at any one time, in any place,
under pretence of joining in a religious worship not authorised by
the laws of this realm,`" etc. for the first offence the fine was to
be five pounds on each person so offending;
ten pounds for the second offence; and for the third,
the delinquent was required to abjure the realm; and in case of refusal,
it was made lawful for the king to give order for the transportation of the offender;
and in default of payment of the fines within one week after conviction, the defaulter,
for the first noncompliance, was to be imprisoned for three months,
and for the second six, and to be kept to hard labour.]

Whereupon Edward Burrough drew up a statement, which he called,
"`The Case of the People called Quakers,`" etc. in which,
though he failed of obtaining for his fellow-sufferers the redress he desired,
he nevertheless helped their cause, and the cause of truth in general, by the plain,
manly, and conscientious record he exhibited of Friends`' principles,
and of their undeserving hardships in consequence of faithfully abiding by them.

"`What judgment,`" says he, in speaking of their mode of meeting for religious worship,
"`what judgment do our neighbours give in this case?
They say, concerning our meetings,
that they have known us to meet together in such manner, for divers years,
in towns and villages, and never knew nor understood of any harm or danger therein,
nor ever were any way prejudiced, either in their persons or estates, in our meetings.`"
"`Enquire,`" he continues, "`and they will tell you they believe in their consciences,
our meetings are for good, and have good effects, and are not evil,
nor bring forth evil to any.`"

"`And as for the manner of our meeting and sitting together, it is orderly, and decently,
and of good report among men; and for any doctrine that ever was there held,
or heard by any, none can truly accuse it to be either error, heresy, or sedition;
but on the contrary, they know it witnesseth against all sin and iniquity,
and tends to the turning of people from ungodliness to righteousness,
to truth and holiness; and many can tell that this is effected by our doctrine,
preached in our meetings;
and our neighbours can witness that we part again in peace and good order,
and in convenient time,`" etc.

Speaking of the objections often urged against them as violating the laws of the land,
by refusing to pay tithes, take oaths, etc., he says,
"`as to submitting to all known laws of the land,
this is known to God and our neighbours, that our principle and practice is,
and ever hath been, to submit to every government, and to submit to all laws of men,
either by doing or by suffering, as at this day.
This is well known,`" he continues, "`to our neighbours and all people,
that we are submissive to all laws of men, by patient suffering without resistance;
even when any law requires anything of us which we cannot perform for conscience sake,
that law we fulfill by patient suffering, resisting no man,
nor rendering evil for evil to any.
And the judgment of the Scriptures, which are according to both law and gospel,
and the precedents of saints, justify us in this case;
in choosing patiently to suffer the greatest penalties of the law,
rather than to obey any such law, as requires things contrary to our pure consciences.`"

He then specifies the examples from Scripture to which he alludes;
as in the case of Daniel, etc. third chapter; also of Daniel again, chapter six;
also of the apostles, Acts 4:18.

"`And as for our conversation among men,`" he says,
"`in respect of our daily walking and converse with them in our dealing,
in respect of honesty and faithfulness, and truth and justice, in works and words,
our neighbours shall give witness for us.
We will not justify ourselves; it is God that justifies us; and the law of God,
the gospel of Christ, the Scriptures, the examples of holy men, our neighbours,
and the witness of God in all men`'s consciences, shall bear witness to us;
and all these do give judgment for us in these cases,
to whom we do appeal for judgment.`"

And then, with a beautiful outpouring of soul,
the living witness within him springing up to seal the testimony he was giving,
"`O Lord God everlasting,`" he says,
"`do thou judge our cause! do thou make it manifest in thy due season to all the world,
that we are thy people; that we love thee above all; that we fear thy name more than all;
that we love righteousness and hate iniquity, and that we now suffer for thy holy name,
and for thy honour and justice, and for thy truth and holiness!
O Lord, thou knowest we are resolved to perish, rather than to lose one grain hereof!
Amen, amen!`"^
footnote:[[.book-title]#Sewel`'s History#, (Lindfield edition,) vol. ii. pp. 420, 425.]
Much more is subjoined;
but the foregoing extracts may suffice to show the
simple integrity with which he pleaded the case;
an integrity which he confirmed by his personal example upon all occasions,
and for the maintenance of which he was cast into prison, under circumstances which,
in all probability, occasioned the loss of his life.

In his addresses to the members of his own community, he was plain,
but powerful in the wisdom which "`is profitable to direct.`"
The severe pressure of these tribulating times (which pressure, as we have seen,
more peculiarly weighed upon the Quakers) called for every aid of counsel or of comfort,
which the strong could administer to the weak;
and herein was he made "`a succourer of many.`"
Several passages in proof of his possessing the gift of
speaking a word in due season to all conditions of the soul,
might be adduced from his different epistles to Friends; and I think,
in the following extracts, a spiritual mind will find much to approve, and unite with.

"`As for all the confusions, and distractions, and rumours of wars,`" he says,
in allusion to the broils and factions which at that time filled the kingdom,
"`what are they to us?
What have we to do with them, and wherein are we concerned in these things?
Is not our kingdom of another world, even that of peace and righteousness?
And hath not the Lord called us, and chosen us into the possession of that inheritance,
wherein strife and enmity dwell not?
Yea, he hath broken down that part in us that is related thereunto;
and being dead in that nature of strife, bloodshed, and wars,
how can we live in strife and contention in the world,
or have fellowship with any therein?`"
"`Our kingdom is inward--and our weapons are spiritual--and our victory and
peace are not of this world--and our war is against our soul`'s enemies,
and against the power of darkness, even by the sword of the spirit,
which God hath given us, and called us to war therewith,
and to convert people from sin and death,
and from the very occasion of wars and contentions about the things that are earthly.`"

"`The fruits of the Spirit of God are of another nature,
even peace and meekness towards all, and not enmity towards any;
in which spirit let us live and walk; admonishing all hereunto,
and praying for our enemies, and not hating them, but doing good for evil.`"
"`And this is the true Christian life learned of Christ,
and this life is blessed in this world, and in the world to come;
and they that live here, are redeemed out of the world,
wherein are troubles and confusion, war and strife.`"

Of the nearness of his departure from this world,
Edward Burrough seemed to have had some foreshadowing in his mind: for he said,
a few months before, to his particular friends, on parting from them at Bristol, that,
"`he did not know he should see their faces any more,
and therefore he exhorted them to be faithful to
that wherein they had found rest to their souls.`
And to his bosom friend, Francis Howgill, he said,
"`I can freely go to the city of London,
and lay down my life for a testimony of that truth which I
have declared through the power and Spirit of God.`"

Thus "`setting his face like a flint,`" to suffer or to die,
this faithful disciple of the King of martyrs, came to London, where,
in consequence of the act to which allusion has just been made,
persecution of the fiercest kind was raging against the poor Quakers.
Soon after his arrival,
Edward was found preaching at the meeting-house called the Bull and Mouth,
and being violently pulled down by some soldiers,
he was taken before Alderman Richard Brown, and committed to Newgate.
Several weeks afterwards,
he was examined at the sessions-house in the Old Bailey and was fined twenty-marks;
which, judging it to be his duty not to pay, he was remanded back to prison,
there to remain till payment was made.
Here he was confined about eight months in company with
about a hundred and forty prisoners besides;
and in consequence of the crowding together of
so many persons under the privation of air,
cleanliness, and every common comfort which human existence requires,
several of them sickened and died, of which number he was one.
We must not, however, omit to state,
that a special order for the release of Edward and of some others,
was sent from the king; but whether it arrived too late for his removal, or,
as it is said, the enmity of those who were concerned in his committal,
frustrated the execution of it, certain it is, that he never received the benefit of it.

During the time of his weakness, he was very fervent in prayer,
both for himself and his friends;
and many consolatory and glorious expressions escaped him.
The deep devotedness of soul,
wherewith from his youth he had given himself up to the cause of Truth,
not only permitted but prompted the holy boldness, with which at this trying hour,
he proclaimed himself the servant of the Lord.
"`I have preached the gospel,`" he said, "`freely in this city,
and have often given up my life, +++[+++as to will,]
for the gospel`'s sake.
And now, O Lord! rip open my heart, and see if it be not right before thee!`"
Again, appealing in prayer to his Heavenly Father,
"`Thou hast loved me when I was in the womb!`" he said,
"`and I have loved thee faithfully in my generation!`"

To his friends who were about him, and who he, no doubt,
anticipated would severely feel the want of him, he addressed a few words of comfort,
by reminding them, that the righteous were taken away from the evil to come;
and of exhortation, by saying, "`live in love and peace.`"

Nor was this heavenly-minded man unmindful to supplicate for his enemies and persecutors,
naming the most unrelenting of them, by saying, "`Lord,
forgive Richard Brown--if he may be forgiven!`" "`Being sensible,`" says Sewel,
"`that death was approaching, he said, '`though this body of clay must turn into dust,
yet I have a testimony that I have served God in my generation;
and that spirit which hath lived and acted, and ruled in me,
shall yet break forth in thousands.`'

"`The morning before he departed this life, which was about the latter end of this year,
+++[+++1662,]
he said,
'`Now my soul and spirit is centered into its own being with God! and
this form of person must return from whence it was taken!`'

"`This,`" continues the historian, "`was the exit of Edward Burrough! who,
in his flourishing years,
(viz. about the age of eight-and-twenty,) in an unmarried state,
changed this mortal life for an incorruptible!`"

The testimony to his memory from his dear friend and companion, Francis Howgill,
is very pathetic; and though too long for insertion, I cannot wholly pass it by,
without offering a few extracts therefrom.

"`Shall days, or months, or years, wear out thy name, as though thou hadst no being?`"
he says, affectionately apostrophizing his departed friend; and giving vent awhile,
in this strain, to his emotions, "`Oh, Edward Burrough!`" he continues,
"`I cannot but mourn for thee; yet not as one without hope or faith--knowing,
and having a perfect testimony of thy well-being, in my heart, by the Spirit of the Lord;
yet thy absence is great, and years to come shall know the want of thee!

"`When I think upon thee, I am melted into tears of true sorrow,
and because of the want that the inheritance of the Lord hath of thee,
my substance is even as dissolved.
Shall I not say, as David said of Saul and Jonathan,
when they were slain in Mount Gilboa,
'`the beauty of Israel is slain upon the high places!`' I am distressed for thee,
my brother: very pleasant hast thou been to me, and my love to thee was wonderful,
passing the lore of women.
Oh thou, whose bow never turned back, neither sword empty from the blood of the slain,
from the slaughter of the mighty,
who made nations and multitudes shake with the word of life in thy mouth,
and wast very dreadful to the enemies of the Lord; thou wert expert to handle thy weapon,
and by thee the mighty have fallen, and the slain of the Lord have been many.
Oh, how certain a sound did thy trumpet give?
Thou hast put thy hand to the hammer of the Lord,
and hast often fastened nails in the heads of the Lamb`'s enemies, as Jael did to Sisera;
and many a rough stone hast thou polished, and squared,
and made fit for the building of God; and much knotty wood hast thou hewn in thy day,
which was not fit for the building of God`'s house.
Oh, thou prophet of the Lord! thou shalt forever be recorded in
the Lamb`'s book of life-- among the Lamb`'s worthies,
who have followed the Lamb through great tribulations, as many can witness for thee,
from the beginning; and at last hast overcome,
and hast been found worthy to stand with the Lamb upon Mount Sion, the hill of God,
as I have often seen thee, with thy heart well tuned as a harp to praise the Lord,
and to sound forth his great salvation,
which many a time made glad the hearts of them that did believe,
and strengthened their faith and hope.`"

"`Well! thou art at rest! and '`bound up in the bundle of life;`'
and I know tears were wiped away from thy eyes,
because there was no cause of sorrow in thee! for I
know thou witnessedst the old things done away;
and there was no curse, but blessings were poured upon thy head as rain,
and peace as a mighty shower; and trouble was far from thy dwelling,
though in the outward man, trouble on every side;
and thou hadst a greater share in that for the gospel`'s sake,
(though a youth,) in thy time, than many besides.
But now thou art freed from that, and hast obtained a name, through faith,
with the saints in light.`"

"`Well, hadst thou more to give up than thy life, for the name of Jesus, in this world?
Nay. And now thou art freed from the temptations of him who hath the power of death,
and art freed from thy outward enemies,
who hated thee because of the life that dwelt in thee,
and remainest at the right hand of God, where there is joy and pleasure forevermore!`"
