== Chapter VI.

After being liberated from Carlisle prison, George Fox continued to travel and preach,
from place to place, meeting with his usual vicissitudes,
till he came into Leicestershire, his native county; where he visited his friends,
and had various conferences with his old antagonists, "`the priests.`"

It happened, in the course of his travels, in this year,
(1654,) that he came to Whetstone, in Leicestershire; where,
just as he and his friends were gathering together for a meeting,
he was visited by some soldiers, and the marshal of Colonel Hacker`'s regiment,
who took him, and another friend, named Alexander Parker, into custody,
and at night brought him before the colonel,
who was a leading person in the parliamentary army,
and one of those who had signed the warrant for the late king`'s execution.

The account of his treatment from Colonel Hacker is thus related in his Journal.

"`At night,`" he says, "`they had me before Colonel Hacker, his major, and captains,
and a great company of them; and a great deal of discourse we had, about the priests,
and about meetings; for at this time,
there was a noise of a plot against Oliver Cromwell.
Much reasoning I had with them,
about the light of Christ which enlighteneth every man that cometh into the world.

"`Colonel Hacker asked whether it was not this light of
Christ that made Judas betray his master,
and afterwards led him to hang himself?

"`I told him no; that was the spirit of darkness which hated Christ and his light.

"`Then Colonel Hacker said, I might go home, and keep at home,
and not go abroad to meetings.

"`I told him I was an innocent man, free from plots, and denied all such work.

"`His son Needham said, '`Father, this man hath reigned too long,
it is time to have him cut off.`'

"`I asked him for what?
What had I done, or whom had I wronged, from a child?
For I was bred and born in that country, and who could accuse me of any evil from a child?

"`Colonel Hacker asked me again, if I would go home, and stay at home?

"`I told him, if I should promise him so,
it would manifest that I was guilty of something, to make my home a prison,
and if I went to meetings, they would say I broke their order.
Therefore, I told them, I should go to meetings, as the Lord should order me,
and could not submit to their requirings; but I said we were a peaceable people.

"`'`Well then,`' said Colonel Hacker,
'`I will send you tomorrow morning by six o`'clock to my Lord Protector, by Captain Drury,
one of his lifeguard.`'

"`That night I was kept prisoner at the Marshalsea, and the next morning,
by the sixth hour, I was delivered to Captain Drury.

"`I desired he would let me speak to Colonel Hacker before I went,
and he had me to his bedside.

"`Colonel Hacker set upon me presently again to go home, and keep no more meetings.

"`I told him I could not submit to that; but must have my liberty to serve God,
and to go to meetings.

"`'`Then,`' said he, '`you must go before the Protector.`'

"`Whereupon I kneeled by his bedside, and besought the Lord to forgive him;
for he was as Pilate, though he would wash his hands;
and when the day of his misery and trial should come upon him,
I bid him then remember what I had said to him.`"

The prophetic spirit which spake in this remonstrance, is remarkable, inasmuch,
as upon the restoration of the king,
this Colonel Hacker was one of those impeached for high-treason,
in the affair of the late king`'s trial and execution; and in consequence thereof,
condemned and executed.
To this George Fox thus alludes: "`Afterwards,
when Colonel Hacker was imprisoned in London, a day or two before his execution,
he was put in mind of what he had done against the innocent; and he remembered it,
and confessed to Margaret Fell, saying, he knew well whom she meant,
and he had trouble upon him for it.`"

Continuing his relation, "`I was carried up prisoner,`" he says, "`by Captain Drury,
from Leicester; and when we came to Harborough, he asked me if I would go home,
and stay a fortnight.
I should have my liberty, he said, if I would not go to, nor keep meetings.

"`I told him I could not promise any such thing.
Several times upon the road did he ask, and try me after the same manner;
and still I gave him the same answers.
So he brought me to London, and lodged me at the Mermaid, over against the Mews,
at Charing-cross.`"

It is possible, that,
independently of any compassion which Captain Drury might feel for his prisoner,
he had also a latent motive of another kind for
wishing to part with him as speedily as he could;
for George was apt to take his own way when he considered it a right one;
and unless the captain sympathized with his views,
he would scarcely have much enjoyed his journey, seeing that, as usual,
his companion pursued his course of preaching and exhorting, as they moved along.

"`As we travelled,`" he says,
"`I was moved of the Lord to warn people at the inns and places where I came,
of the day of the Lord that was coming upon them.`"

When he was lodged at the Mermaid,
Captain Drury left him to go and give the Protector an account of him.

"`When he came to me again,`" he says,
"`he told me the Protector required that I should promise not
to take up a carnal sword or weapon against him,
or the government, as it then was; and that I should write it in what words I saw good,
and set my hand to it.
I said little in reply to Captain Drury;
but the next morning I was moved of the Lord to write a paper to "`The Protector,
by the name of Oliver Cromwell;`" wherein I did, in the presence of the Lord God,
declare, that I did deny the wearing or drawing of a carnal sword,
or any other outward weapon against him, or any man.
And that I was sent of God to stand a witness against all violence,
and against the works of darkness; and to turn people from darkness to light;
to bring them from the occasion of war and fighting, to the peaceable gospel;
and from being evil-doers, which the magistrates`' sword should be a terror to.
When I had written what the Lord had given me to write, I set my name to it,
and gave it to Captain Drury to hand to Oliver Cromwell; which he did.

"`After some time, Captain Drury brought me before the Protector himself, at Whitehall.
It was in a morning before he was dressed; and one Harvey,
who had come a little among Friends, but was disobedient, waited on him.
When I came in, I was moved to say,
'`Peace be in this house!`' and I exhorted him to keep in the fear of God,
that he might receive wisdom from him; that by it he might be ordered;
and with it might order all things under his hand, unto God`'s glory.

"`I spoke much to him of truth;
and a great deal of discourse I had with him about religion,
wherein he carried himself very moderately.
But he said, we quarrelled with the priests, whom he called, '`ministers.`'
I told him I did not quarrel with them, they quarrelled with me and my friends.
'`But,`' said I, '`if we own the prophets, Christ, and the apostles,
we cannot hold up such teachers, prophets, and shepherds, as the prophets, Christ,
and the apostles declared against; but we must declare against them,
by the same power and spirit.`'

"`Then I showed him that the prophets, Christ, and the apostles declared freely,
and declared against them that did not declare freely; such as preached for filthy lucre,
divined for money, and preached for hire, and were covetous and greedy,
like the dumb dogs that could never have enough.
And that they who have the same spirit that Christ and the prophets,
and the apostles had, could not but declare against all such now, as they did then.

"`As I spoke, he several times said it was very good, and it was truth.
I told him that all Christendom, (so called,) had the Scriptures;
but they wanted the power and spirit that those had, who gave forth the Scriptures;
and that was the reason they were not in fellowship with the Son, nor with the Father,
nor with the Scriptures, nor one with another.

"`Many more words I had with him; but people coming in, I drew a little back.
As I was turning, he catched me by the hand, and with tears in his eyes, said,
'`Come again to my house; for if thou and I were but an hour of a day together,
we should be nearer one to the other;`' adding, that he wished me no more ill,
than he did to his own soul.
I told him if he did, he wronged his own soul;
and admonished him to hearken to God`'s voice, that he might stand in his counsel,
and obey it; and if he did so, that would keep him from hardness of heart;
but if he did not hear God`'s voice, his heart would be hardened.

"`He said it was true.`"

"`Then I went out; and when Captain Drury came out after me,
he told me his Lord Protector said, I was at liberty, and might go whither I would.

"`Then I was brought into a great hall, where the Protector`'s gentlemen were to dine.
I asked them, what they brought me thither for?
They said it was by the Protector`'s order, that I might dine with them.

"`I bid them let the Protector know, I would not eat of his bread,
nor drink of his drink.`"

This may, perhaps, at first sight, seem a somewhat rude reply;
but when the principles and then existing
circumstances of George Fox are duly considered,
it will be seen that it resulted from feelings of admirable integrity, and which,
when Cromwell heard of, it occasioned him to say, "`Now I see there is a people risen,
that I cannot win either with gifts, honours, offices, or places;
but all other sects or people I can.`"
In reply to which, "`it was told him,`" says George, "`that we had forsook our own,
and were not like to look for such things from him.`"

Such was the result of the interview with Cromwell;
and finding himself in a wide field for exertion in the metropolis,
and at liberty to pursue his inclinations, we may be assured that George was not idle.
He had numerous meetings; at which, he says, "`so great were the throngs of people,
that I could hardly get to and from the meetings, for the crowds;
and the truth spread exceedingly.`"

A curious specimen of the keen sagacity, and native wit, which,
in the midst of more exalted traits, existed in his character,
he gave forth at this time, in a paper entitled:
"`To such as follow the world`'s fashions.`"

"`What a world is this!`" he begins, by exclaiming;
"`How doth the devil garnish himself! how obedient are people to do his mind and will!
They are altogether carried away with fooleries and vanities,
both men and women;`" upon which indisputable fact dilating awhile, "`young and old,
one puffs up another,`" he goes on to say: "`They must be in the fashion of the world,
else they are not in esteem; nay, they shall not be respected,
if they have not gold or silver upon their backs, or, if the hair be not powdered.
But if one have store of ribbands hanging about his waist, at his knees, and in his hat,
of divers colours, red, white, black, or yellow,
and his hair powdered,--then he is a brave man--
then he is accepted--then he is no Quaker.`"

"`Likewise the women having their gold, their patches on their faces, noses, cheeks,
forehead; their rings on their fingers, etc.; their cuffs double under and above,
like a butcher with his white sleeves;--their ribbands tied about their hands,
and three or four gold laces about their clothes-- '`this is no Quaker,`' say they.`"

After much more to the same purpose, "`Are these your fine Christians?`"
he says.
"`Yea, say they, they are Christians.
But say the serious people, they are out of Christ`'s life; out of the apostle`'s command;
and out of the saints`' ornament.
To see such as are in the fashions of the world before-mentioned,
a company of them playing at bowls, or at tables, or at shovel-board;
or each taking his horse with bunches of ribbands on his head,
as the rider hath on his own, perhaps, a ring in his ear too,
and so go to horse racing to spoil the creatures!
Oh, these are gentlemen indeed!--these are bred-up gentlemen!
these are brave fellows!--they must take their recreation;
for pleasures are lawful,`" etc.

"`These be they,`" he concludes,
"`that live in pleasures upon earth!--these be they who are dead while they live;
who glory not in the Lord but in the flesh.
These be they who are out of the life that the Scriptures were given forth from;
who live in the fashions and vanities of the world, out of truth`'s adorning,
in the devil`'s adorning, (who is out of the truth;) not in the adorning of the Lord,
which is a meek and quiet spirit, and which is with the Lord of great price,`" etc.

Many other papers to different persons, on different occasions,
he also gave forth during his stay, which was pretty long, in and about London;
but nothing of particular interest occurred in his history, till the following year;
when, being in Cornwall, with some of his friends, he was again made a prisoner,
and taken to Launceston jail.

Here his treatment, and that of his companions, was exceedingly hard and oppressive;
and such as to give a circumstantial account of,
would only be revolting to the feelings of the reader.
He met with the usual fare of his brethren at the time of the assizes;
which commonly was, that after being several weeks in prison, they were had up for trial;
and in consequence of adhering to their principles,
either in respect to not taking the required oath, or on some other ground,
they were remanded back to captivity, there to remain till the assizes came round again.
Such was the case at present; Fox and his friends, having been nine weeks in prison,
and being brought to trial at the assizes,
were fined twenty marks for not putting off their hats;
and not feeling it right to pay the money,
were sent back to prison to remain till payment was made.

At length, after several weeks more, they were offered their liberty,
provided they would pay the prison-fees;
but to recognise their unjust imprisonment as demanding anything of them but rebuke,
being far from the truth and purity of their principles,
they declined accepting of freedom upon these terms; and after awhile,
their steadfastness continuing, they were released without any demand.

In the course of his travels out of Cornwall, George Fox records in his Journal,
that he came to Exeter, "`where,`" he says "`many friends were in prison,
and amongst the rest, James Naylor.`"

The circumstances connected with this person, are of so extraordinary a kind,
as to claim a portion of our more particular attention.
He was a native of the north of England, being born at Ardesley, near Wakefield,
in Yorkshire.
He had served as quarter-master in the parliamentary army under General Lambert,
and by religious profession was an Independent.
He was one of the earliest of those who received the truth as declared by George Fox;
and being a man, although of limited education, yet of very comprehensive intellect,
he brought into the service of the society, a great ability for being useful;
more especially, as in the first period of his uniting with Friends,
he exhibited an extraordinary gift of holy wisdom and humility.

He came to London about the same time as Francis Howgill and Edward Burrough;
and preaching there with eminent power, it happened, as it too often does in such cases,
that many of his admirers began to draw comparisons
between him and his brethren in the ministry,
which necessarily paved the way to painful differences.
In this divided state, the females amongst his hearers, tended greatly,
by their ungoverned and intemperate feelings, to widen the breach;
and being reproved for their misconduct by Howgill and Burrough, they endeavoured,
though at first unsuccessfully, to enlist Naylor on their side,
by incensing him with complaints against these persons.
But James Naylor,
having too deep an understanding of the solidity of his brethren`'s judgment,
to decide against them,
Martha Simmons (which was the name of one of these persons) fell into a kind of paroxysm,
and exclaimed with a shrill, piercing voice, "`I looked for judgment,
but behold a cry`"--accompanying her words with such bitter lamentations,
that poor James, too easily yielding to feelings of compassion, instead of adopting,
as his brethren had, those of rebuke,
became entangled in the snare which the adversary of his soul was spreading around him.

From one step to another in the ladder of spiritual pride,
he at length arrived at such a height.
as to hear, not only without reproof, but even with a secret feeling of complacency,
the wildest adulation of this woman,
and of the other enthusiastic females who surrounded him.
Amongst these, was one Hannah Stranger, "`whom,`" says Sewel, "`I knew very well;
and have reason to believe a woman of high imaginations.`"
This person, it seems, addressed to him at this time,
several very wild and preposterous epistles, calling him,
"`the everlasting Son of Righteousness-- the Prince of
Peace--the fairest of ten thousand,`" etc.;
and whilst at this prison of Exeter, where George Fox found him, she,
together with some others, in their fanatic folly, would kneel before him,
and kiss his feet.

George Fox alludes to his meeting with James, by saying,
"`we came through the countries to Exeter, where many friends were in prison,
and amongst the rest, James Naylor; for a little before the time we were set at liberty,
James ran out into imaginations, and a company with him,
and they raised up a great darkness in the nation.

"`And he came to Bristol, and made a disturbance there;
and from thence he was coming to Launceston to see me; but was stopped by the way,
and imprisoned at Exeter.

"`That night,`" he proceeds, "`that we came to Exeter, I spoke with James Naylor;
for I saw he was out, and wrong, and so was his company.
The next day, being the first-day of the week,
we went to the prison to visit the prisoners, and had a meeting with them in the prison;
but James Naylor and some of them could not stay the meeting.

"`The next day I spake to James Naylor again, and he slighted what I said, and was dark,
and much out;`" and although it seems that James
testified affectionate feelings towards his good friend,
yet the unflinching integrity of George Fox disdained
to receive them whilst mixed with so much wilful error.
He concludes by saying, "`So, after I had been warring with the world,
there was now a wicked spirit risen up amongst friends to war against;`" but he adds,
"`I admonished him and his company; and when he was come to London,
his resisting the power of God in me, and the truth that was declared to him by me,
became one of his greatest burdens.`"

After he was released from Exeter prison, James Naylor rode into Bristol,
accompanied by his wild disciples; one of whom, named Thomas Woodcock,
went bareheaded before him, whilst one of the women led his horse; Martha Simmons,
Hannah Stranger, and others, spreading their scarfs and handkerchiefs before him,
and the whole of the company shouting hosanna! etc.
That such proceedings should attract the notice and judgment of the magistrates,
was as much to be desired as expected.
They had scarcely passed the suburbs of the city, before they were all apprehended,
and put into prison; and not long after, James Naylor was taken to London,
to be examined by the parliament.
We may well suppose, that, in this assembly, composed, as to many of its members,
of rigid sectarians, stiff adherents to notions,
and consequently bitter enemies to the spirit of religion, and amongst whom,
the pure and child-like simplicity of friends`' principles was recoiled from,
because of the secret reproof it inflicted upon their complicated,
doctrinal head-knowledge; a knowledge which,
whilst it helped to fill their mouths with the letter,-- too often left
their hearts void of the life of the Scriptures;--we may well suppose,
I say, the exulting joy with which they found within their clutches,
this straying sheep from a fold so hated.

It seemed as though they could never have enough of the matter,
although the accusations that were brought against him,
respecting the strange conduct of his followers in Exeter prison,
and his mode of riding into Bristol, were never denied by him or them,
when they were examined before the committee of parliament.
The report of this examination was made on the 5th of December, 1656.

On the 16th, according to Sewel`'s statement,
this business was brought before the house for the twelfth time,
after having been discussed, forenoon and afternoon in the interim,
many members of the parliament not approving the
severity proposed to be used against him.

On the 17th, after a long debate, they came to the following resolution; viz.,
"`That James Naylor be set on the pillory, with his head in the pillory,
in the palace-yard, Westminster, during the space of two hours, on Thursday next;
and be whipped by the hangman through the streets, from Westminster to the Old Exchange,
London; and there likewise be set on the pillory, with his head in the pillory,
for the space of two hours, between the hours of eleven and one, on Saturday next;
in each place wearing a paper containing an inscription of his crimes;
and that at the Old Exchange,
his tongue be bored through with a hot iron! and that he be
there also stigmatized on the forehead with the letter B.;
and that he be afterwards sent to Bristol, and be conveyed into,
and through the said city on horseback, with his face backward;
and there also publicly whipt, the next market-day after he comes thither;
and that from thence, he be committed to prison in Bridewell, London;
and there restrained from the society of all people; and there to labour hard,
till he shall be released by parliament; and during that time,
be debarred the use of pen, ink, and paper,
and shall have no relief but what he earns by his daily labours.`"

After reading this sentence,
we need not wonder that they were some time before they
could agree in deciding to give it forth.
There seemed also a difficulty about properly calling him a blasphemer;
for whatever of blasphemy had been committed,
it did not appear that his tongue had ever given utterance to it.
Upon the whole, it was considered by the public,
to be too severe a judgment upon a man whose sin seemed
more the result of a clouded understanding,
than a depraved heart;
and accordingly several persons of different persuasions in religion,
offered petitions to the parliament on his behalf;
which petitions it was resolved not to read,
till the sentence was pronounced against him.
After judgment was concluded,
and the Speaker authorized to issue warrants for the execution of it,
a doubt arose whether any warrant would be valid
without it were ratified by the Protector,
who was unwilling to have any thing to do with it.
However, this difficulty did not operate to the nullifying of the sentence,
which Naylor was brought to the bar to hear.

When the Speaker (Sir Thomas Widdrington) was about to pronounce it, Naylor said,
"`he did not know his offence.`"

To which the Speaker replied, "`he should know his offence by his punishment.`"
After it was pronounced, James Naylor received it with great calmness,
yet as if he wished to have said something.
But being refused permission, he was only heard to say with a composed manner,
"`I pray God he may not lay it to your charge.`"

On the 18th of December he suffered part of the sentence;
for after he had remained two full hours in the pillory, he was stript,
and whipped from Palace-yard to the Old Exchange;
receiving three hundred and ten stripes, and which would have been one more,
but the executioner`'s foot slipping, the intended stroke fell upon himself,
and hurt him much.
The patience and quietness with which Naylor sustained
this treatment astonished many of the spectators;
especially when they beheld the pitiable condition of his poor lacerated body; in which,
according to a certificate made by the person
who afterwards washed and dressed his wounds,
and which certificate was presented to the parliament and afterwards printed,
"`there was not the space of a man`'s nail free from stripes and blood,
from his shoulders near to his waist! his right arm sorely striped:
his hands so much hurt with cords that they bled, and were swelled:
the blood and wounds of his back, did very little appear at first sight,
by reason of the abundance of dirt that covered them,`" etc.

In fact the severity of his sentence was such,
that many persons considered it would have been a more compassionate one,
had it been immediate death; "`and it seemed,`" says Sewel,
"`that indeed there was a party,
who not being able to prevail so far in parliament as to have him sentenced to death;
yet strove to the utmost of their power to make
him sink under the weight of his punishment.`"

On the 20th of December,
(two days subsequent to the first infliction,) he was to have
undergone the further punishment of being branded on the forehead,
and having his tongue bored through;
but by reason of the cruel flagellation he had received,
he was found to be in so weak a state, that many persons of note, moved with compassion,
presented petitions to parliament on his behalf; in consequence of which,
his further punishment was respited for one week.

During this interval, several persons presented another petition,
in which the concession of the parliament is thus noticed,
and their further favour requested.

"`Your moderation and clemency, in respiting the punishment of James Naylor,
in consideration of his illness of body,
hath refreshed the hearts of many thousands in these cities,
altogether unconcerned in his practice: wherefore we most humbly beg your pardon,
that are constrained to appear before you in such a suit,
(not daring to do otherwise,) that you would remit the
remaining part of your sentence against the said James Naylor,
leaving him to the Lord, and to such gospel remedies as he hath sanctified;
and we are persuaded you will find such a course of love and forbearance,
more effectual to reclaim,
and will leave a zeal of your love and tenderness upon our spirits.

"`And we shall pray,`" etc..

This petition was presented at the bar of the house,
by about one hundred persons in behalf of the whole, and was read and debated;
but not being likely to succeed, the petitioners addressed the Protector,
who thereupon sent a letter to the parliament,
which occasioned some discussion in the house.
But notwithstanding these and other efforts to prevent it,
the representations of Cromwell`'s favourite preachers, especially Caryl, Manton, Nye,
Griffith, and Reynolds, had such weight with him,
that he could not resolve to put a stop to the completion of the sentence.
These men, (who were particularly hostile to the Quakers`' principles,) being,
as it was said, commissioned by the parliament, visited Naylor on the 24th of December,
to speak with him concerning the occasion of his punishment.

Before Naylor would enter into any conference with them,
he desired that some impartial person should be present as a witness to what passed.
But this they refused; upon which he declined saying anything,
unless what was said was written down, and a copy thereof given him to keep,
or left with the jailer, with their signatures affixed.

To this having agreed, they propounded several questions to him,
and took down his answers.

Upon being asked if he was sorry for the blasphemies of which he had been guilty,
and whether he did recant and renounce the same?
he replied, by inquiring what blasphemies?
and desired they might be named.
But they not being able to particularize their charge,
"`Would you have me recant and renounce you know not what?`"
said he.

They then inquired, whether he did believe there was a Jesus Christ?
To which he replied, he did believe there was;
and that Jesus had taken up his dwelling in his heart and spirit;
and for the testimony of Jesus he now suffered.

Upon which one of them said,
"`but I believe in a Jesus that never was in any man`'s heart.`"
To which Naylor replied, he knew no such Christ, for the Christ he knew,
filled heaven and earth, and dwelt in the hearts of believers.

They then inquired why he suffered those women to worship, and adore him?
To which he replied, "`Bowing to the creature I deny, +++[+++or disallow,]
but if they behold the power of Christ, and bow to it, wherever it is,
I have nothing wherewith to resist or gainsay it.`"

Here it would seem that poor Naylor was still in some degree
in bondage to the gross delusions which had misled him;
since he could not as yet perceive that the behaviour of the
fanatics who had drawn him into such error and suffering,
was wrong.

"`Have you thus long professed the Scriptures,`" said he,
"`and do you now stumble at what they hold forth?`"
Whereupon they desired him to produce an instance from Scripture,
wherein such a practice was held forth.

"`What think you of the Shunamite`'s falling down at the feet of Elisha,
and bowing before him?`"
said he, "`as divers others also, in Scripture spoken of; as that of Abigail to David,
and that of Nebuchadnezzar to Daniel?`"

Upon which they paused a little while, and then said, "`That was but a civil act,
or acknowledgment.`"

"`So you might interpret the act of these women also,`" he replied,
"`if your eye were not evil, seeing the outward action is one and the same;`" and then,
perceiving that their intentions towards him were anything but conciliatory and kind,
"`How soon,`" said he,
"`have you forgotten the works of the bishops!`" alluding to the severities, which,
in the recent times of episcopal dominion, had been exercised against themselves,
as non-conformists;
"`who are now found in the same,`" he continued--"`seeking to ensnare the innocent.`"
A remark which, in all probability, was too true to be forgiven; for, on hearing it,
they burnt what they had written, and with some bemoaning expressions, rose to depart.
He then desired that whatever questions the parliament wished him to answer,
might be brought to him in writing,
with permission for him to return his replies in writing also.

If there had been any intention to favour James Naylor
by sending these ministers to confer with him,
the result of their visit was inimical to it; and accordingly,
the execution of the remainder of his punishment was performed on the 27th of December.
Sewel relates, that on the morning of that day, one Robert Rich, a London merchant,
and a great favourer of Naylor`'s, placed himself at the door of the parliament-house,
from eight in morning till about eleven; addressing to each of the members of parliament,
as they passed by, such quotations from Scripture,
as from what he might know of their individual circumstances,
he supposed applicable to them in reference to their conduct to Naylor.
To one,
whom he considered as innocent of consenting to the cruelties practised against him,
he said, "`He that dwelleth in God, dwelleth in love; for God is love.`"
To another, whom he believed to be actuated by malice,
"`He that hateth his brother is a murderer.`"

Having performed this service for his friend, he went to the Exchange,
the place appointed for Naylor`'s suffering;
and placing himself on the pillory by his side, he held the poor victim by the hand,
whilst he was burned on the forehead, and bored through the tongue;
and at the conclusion of these barbarities, he actually licked the wounds,
in his zeal to allay the pain.

It would seem that compassion had taken the place of fury in the public mind,
respecting James Naylor;
for although it is supposed that many thousand persons were assembled on this occasion,
yet few were heard to revile, or seen to throw anything at him;
and whilst he was enduring the sentence of branding on the forehead, the people,
as if with one consent, stood bareheaded.

The remainder of his sentence was executed, as it related to Bristol,
by his being sent there, and whipped from the middle of Thomas-street, over the bridge,
up High-street, to the middle of Broadstreet; all which,
(according to J. Whiting`'s account,) "`he bore with wonderful patience,
as related by an eye-witness; and then, being sent by Tower-lane,
the back-way to Newgate, he was, from thence, returned to London,
according to his sentence.`"

It may well be supposed, that so great a fall in an esteemed pillar amongst the Friends,
would be cause of triumph to their numerous enemies.
Such indeed was the case; and as if dissatisfied that it should not have been worse,
the vilest calumnies respecting his moral character,
were also set afloat against poor Naylor.
But from all these he was enabled to clear himself,
by irrefragable testimonies to his innocence.
His transgressions had their source in spiritual pride,
which the adulation of weak fanatics excited, and which, when once in dominion,
the adversary of his soul knew how to use to his own purposes.
Going about as a roaring lion, seeking whom he may devour, amongst all the human race;
who is there in that vast and helpless family,
that this furious foe more delights to tear in pieces, than the heritage of the Lord?

But though the wanderer from the flock may fall, "`he shall not be utterly cast down,
for the Lord upholdeth him with his hand.`"
And it is relieving to the mind, after dwelling upon the foregoing painful history,
to find that a full deliverance from his past delusions,
and a penitential acknowledgment of his transgressions,
was satisfactorily manifested by James Naylor.

During the time of his imprisonment, subsequent to the last part of his punishment,
he obtained the use of pen and ink;
and as the mists of error faded away under the
reviving power of the Sun of Righteousness,
he felt the healing of his Saviour`'s wing, and poured forth, in many touching effusions,
the penitence of his soul.

In one of his papers, given forth by way of recantation of his errors,
"`Glory to God Almighty,`" he says, "`who ruleth in the heavens,
and in whose hands are all the kingdoms of the earth: who raiseth up,
and casteth down at his will; who hath ways to confound the exaltation of man,
and to chastise his children, and to make man to know himself to be as grass before him;
whose judgments are above the highest of men, and his pity reacheth the deepest misery;
and the arm of his mercy is underneath, to lift up the prisoner out of the pit,
and to save such as trust in him from the great destruction, which vain man,
through his folly, brings upon himself; who hath delivered my soul from darkness,
and made way for my freedom out of the prison-house,
and ransomed me from the great captivity; who divides the sea before him,
and removes the mountains out of his way,
in the day when he takes upon him to deliver the oppressed out
of the hands of him that is too mighty for him in the earth!
Let his name be exalted forever! and let all flesh fear before him!

"`And to the Lord Jesus Christ be everlasting dominion upon earth, and +++[+++be]
his kingdom above all the powers of darkness! even that Christ,
of whom the Scriptures declare; which was, and is, and is to come:
the light of the world to all generations.`"

This Saviour, he feelingly acknowledges to have been the rock of his salvation;
"`and his spirit,`" he says,
"`hath given quietness and patience to my soul in deep affliction,
even for his name`'s sake-- praises forever!`"

"`But condemned forever,`" he proceeds, "`be all those false worships,
with which any have idolized my person in the night of my temptation,
when the power of darkness was above.
All their casting of their clothes in the way, their bowings and singings,
and all the rest of those wild actions which did any ways tend to dishonour the Lord,
all that,`" he says, "`I condemn.

"`And all those ranting, wild spirits,`" he continues,
"`which gathered about me in that time of darkness, and all their wild actions,
and wicked words against the honour of God, and his pure spirit and people, I deny.
+++[+++I deny]
that bad spirit, the power, and the works thereof.
And as far as I gave advantage, through want of judgment,
for that evil spirit in any to arise, I take shame to myself justly.`"

He then adverts to the cause of his transgression, as want of watchfulness and obedience;
and that thus the adversary got advantage;
"`and being taken captive from the true light,`" he says,
"`I was walking in the night when none can work, as a wandering bird fit for a prey.
And if the Lord of all my mercies had not rescued me, I had perished;
for I was as one appointed to death and destruction, and there was none could deliver me.
And this I confess, that God may be justified in his judgment,
and magnified in his mercies without end; who did not forsake his captive in the night,
even when his Spirit was daily provoked and grieved,
but hath brought me forth to give glory to his name forever!`"

He then proceeds to clear himself from the charges of immoral conduct,
which had been unjustly added to his other delinquencies; declaring his innocence,
with simple, and almost self-evident integrity;
and after exhorting the reader not to rely upon gifts, or wisdom, or knowledge,
and giving other advice, he thus concludes:--

"`This I have learned in the deeps, and in secret, when I was alone,
and now declare openly, in the day of thy mercy, O, Lord!
Glory to the Highest forevermore,
who hath thus far set me free to praise his righteousness and his mercy!
And to the eternal, invisible, pure God, over all, be fear, obedience, and glory,
forevermore!-- Amen!

[.signed-section-signature]
"`James Naylor.`"

In another paper, wherein he relates more circumstantially,
how he was betrayed into these glaring errors,
after having experienced such unusual favour,
in being kept wise and humble in the exercise of his ministerial gift,
he states it as remarkable, that,
especially courageous as he had ever found himself in meeting and passing through,
the opposition of the foes of truth, yet in coming to London,
he entered it with extraordinary fear,
foreseeing in spirit that something of deep exercise was to befal him there.

He uses a remarkable expression in alluding to some of his delusions, attributing it,
in a great measure, to his "`not minding to stand single and low,`" etc.
"`If thine eye be single,
thy whole body shall be full of light;`" and "`Be
clothed with humility,`" are two sacred aphorisms,
which none have more need to remember continually, and abide in the sense of,
than those who are distinguished by peculiar advantages, whether of nature or grace.

His address to his brethren bespeaks the real repentance of his heart, as much, or more,
than any other of the numerous testimonies given forth during his imprisonment.
It is as follows:--

"`Dear Brethren,`"

"`My heart is broken this day for the offence
that I have occasioned to God`'s truth and people;
and especially to you, who in dear love followed me; seeking me in faithfulness to God,
which I rejected, being bound wherein I could not come forth, till God`'s hand brought me;
to whose love I now confess.
And I beseech you, forgive wherein I evilly requited your love in that day.
God knows my sorrow for it!`" etc.

He then entreats to see them.
"`Unless the Lord keep you from me,`" he says,
"`I beseech you let nothing else hinder your coming to me,
that I might have your help in the Lord: in the mercies of Christ Jesus,
this I beg of you, as if it was your own case:--let me not be forgotten of you.`"

"`And I entreat you speak to Henry Clarke, or whoever else I have most offended;
and by the power of God, and in the spirit of Christ Jesus,
I am willing to confess the offence; that God`'s love may arise in all hearts as before,
if it be his will, who only can remove what stands in the way,
and nothing thereof do I intend to cover, God is witness!`"

In another paper addressed to the weak and young in the faith,
to whom his grievous fall was likely to be most prejudicial,
he thus touchingly expresses himself:--

"`And concerning you, the tender plants of my Father, who have suffered through me,
or with me, in what the Lord hath suffered to be done with me,
in this time of great trial and temptation:--the Almighty God of love,
who hath numbered every sigh, and put every tear in his bottle,
reward it a thousand fold into your bosoms, in the day of your need,
and when you come to be tempted!`"

At the close of this address, he said, "`I beseech you (all that can) to receive it,
even as you would be received of the Lord: and for the rest,
the Lord give me patience to suffer, till he make up the breach!`"

He also addressed a letter to the parliament during his imprisonment,
wherein he declared a true and sound faith in the Saviour of the world;
renouncing with distinct and strong condemnation,
the idolatry which his fanatical admirers had been guilty of.

Nor can I refrain from adding, though in a different strain,
and as a specimen of the energy of his mind,
a sentence or two from a reply which he addressed to the author of a malicious pamphlet,
wherein his failures and sins were mixed up with other matters,
expository of what was considered as the delusions of the Quakers;
and not only his actual delinquencies,
but all that had unjustly been alleged against him on the score of immorality,
was on this occasion revived, to stigmatize the society.

"`O man, or men,`" he says, "`whoever you be, whose work it is,
to gather the failings of God`'s people in the time of temptation,
or night of their trial, and aggravate them,
and add thereto the wickedness and mischievous lies of your own hearts,
as thou hast done in thy book;
you do but show yourselves to be enemies to God and to his children;
and it is our sorrow that any of us should give such spirits occasion to blaspheme;
and it hath been trouble of soul to all the people of God,
that have ever loved righteousness, when they have thus occasioned the joy of the wicked,
or fed the man that watches for iniquity, and feeds on mischief.
Yet know this, you that are of that brood; God will not cast off his people;
though he be sometimes provoked to correct them, even before their adversaries,
(which is a sign to them,) yet is his anger but for a moment,
and his favour shall return as streams of life.

"`Then shall the food be taken out of the mouth of the viper,
and the prey from between the teeth of the devourers;
and God will feed them with their own vomit,
and the poison that hath long lain under their tongues,
shall be bitter in their own bowels.

"`But that which was, and is the sorrow of my heart,`" he says,
in allusion to the calumnies which were forged against him in the day of his distress,
"`is the advantage the enemy then took against the name of Christ, his truth,
and his despised people,`" etc.

"`To God alone I look,`" he adds, in conclusion,
"`in his time to be cleared from all offences in his sight,
who only knows my heart in this thing; in whose presence I can say,
that nothing is more odious and burdensome to my soul,
than that any of the glory or worship which belongs to God or to Christ,
should be given to flesh and blood in myself or others.
And how it was with me in that day, many talk of, but few know;
so the judgment of such I bear; desiring that none in judging me,
might have condemned themselves in God`'s sight, whose counsels are a great deep,
and the end of his work past finding out, till he himself reveal them.
But in the end he will be justified of all, and in all he doth,
that all flesh may be silent before him.`"

True it is, as he remarks, that many can talk of the exercises of a tempted soul,
and comment upon, and censure its delinquencies;
but few--how few are there who can sympathize, by a deep,
experimental knowledge of their own weakness, and their own bitter repentance,
in the failures of an erring brother!

It must therefore be the part of true wisdom, to scan but cautiously, the cause,
or the consequences of such a fall as James Naylor`'s.
That it was great and grievous is manifest;
and so likewise was his visible chastisement.
But of the nature or extent of his inward chastenings,
and of the anguish of that wounded spirit, which even an inspired prophet says,
"`who can bear?`"
we know nothing.
This may we be well assured of; that even in the midst of all the disorder of nature,
in others, or in ourselves,
the great Governor of the universe is working out his secret results,
and reducing all things to the most perfect harmony.
Hence, every sort of sin brings to the sinner, in the natural course of cause and effect,
its necessary consequence.--"`If ye walk contrary to me,`" saith the Lord,
"`I will walk contrary to you.`"
Nevertheless, as a skilful musician, after running through divisions, sub-divisions,
and apparently endless modulations, at last gathers up all,
and concludes in the key-note;
so the Divine Artist winds up his beautiful variety in the everlasting unity
of making "`all things work together for good to those that love Him.`"

The rest of James Naylor`'s life,
which was not of long duration after his fall and recovery therefrom,
was spent in great self-denial, and watchfulness over himself.
It is stated, respecting his decease,
that departing from London about the latter end of the year 1660,
he set forward towards the north,
for the purpose of visiting his wife and children at Wakefield in Yorkshire.
He was seen by a friend at Hertford,
sitting by the way-side in a very solemn and retired frame of spirit.
This person invited him to his house, but he declined it,
signifying a wish to proceed into Huntingdonshire.
In passing on foot through the town of Huntingdon,
he was observed by another friend to be in a particularly solid frame of mind,
like one who felt himself to be a stranger in the earth,
and who was seeking a better country and inheritance.

Some obscurity hangs upon the circumstances which shortly after befel him;
for going some miles beyond Huntingdon, he was found in a field towards evening,
by a countryman, very ill; having (as it was said) been robbed and left bound.
Whether he received any personal injury, is not known;
but he was taken to a friend`'s house at Holm, not far from King`'s Rippon,
where one Dr. Parnell, a physician, came to visit him.
On being asked if any friends from London should be sent for to visit him,
he declined it, but expressed his love and interest in them;
and noticing the attention of his friends, he said,
"`You have refreshed my body--the Lord refresh your souls!`"

About two hours before his death, he spoke in the presence of several witnesses,
these remarkable words:--

"`There is a spirit which I feel, that delights to do no evil, nor to revenge any wrong;
but delights to endure all things, in hope to enjoy its own in the end.
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptations; as it bears no evil in itself,
so it conceives none in thought to any other.
If it be betrayed, it bears it;
for its ground and spring is the mercy and forgiveness of God.
Its crown is meekness; its life is everlasting love unfeigned.
It takes its kingdom with entreaty, and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regard it, or can own its life.
It is conceived in sorrow, and brought forth without any to pity it;
nor doth it murmur at grief and oppression.
It never rejoiceth, but through sufferings; for with the world`'s joy it is murdered.
I found it alone; being forsaken.
I have fellowship therein, with those who lived in dens and desolate places in the earth;
who through death obtained this resurrection, and eternal, holy life!`"

Such was the end of James Naylor; who, in his forty-fourth year, "`chastened,
but not killed-- cast down, but not destroyed`"--through much tribulation, entered,
we may humbly hope, into the kingdom of God.`"
