== Chapter VII.

The ministerial services of George Fox were confined to different parts of England,
Scotland, and Wales, till the year 1658; when,
after a remarkable meeting in Bedfordshire, at the house of John Crook,
a valuable minister in the society, he returned to London.
He had not been long there, when he heard that a Jesuit,
who had come to England in the suite of the Spanish ambassador,
had challenged all the Quakers to dispute with him, at the Earl of Newport`'s house.
"`Whereupon,`" says George, "`some friends let him know that we would meet him.
Then he sent us word, he would meet with twelve of the wisest, learned men we had.
Awhile after, he sent us word he would meet with but six; and after that,
he sent us word again, he would have but three to come.
We hastened what we could, lest, for all his great boast,
he should put it quite off at last.
When we were come to the house, I bid Nicholas Bond, and Edward Burrough go up,
and enter the discourse with him; and I would walk awhile in the yard,
and then come up after them.`"

The purport of sending these his companions on before, was to inquire of the Jesuit,
"`whether the Church of Rome as it now stood,
was not degenerated from the true primitive church, in life, doctrine, power, and spirit?
to which inquiry, the Jesuit returned for answer,
that the Church of Rome was still in its primitive purity.`"
At which period of the conference, George Fox appeared;
and a further question having been put to the Jesuit,
whether his church had the Holy Ghost poured out upon them as the apostles had,
and he answering, "`No,`"--"`then,`" said George,
"`if you have not the same Holy Ghost poured forth upon you,
and the same power and spirit that the apostles had,
ye are degenerated from the power and spirit which the primitive church was in.`"

"`Then I asked him,`" he proceeds,
"`what Scripture they had for setting up cloisters for nuns,
and abbeys and monasteries for men, and for all their several orders;
and for their praying by beads, and to images, and for making crosses,
and for forbidding of meats, and marriages, and for putting people to death for religion?
'`If,`' said I, '`you are in the practice of the primitive church in its purity,
then let us see by scripture, wherever they practised any such things.
(For it was agreed on both hands, that both he, and we, should make good by scripture,
what we said.)

"`Then he told us of a written word, and an unwritten word.

"`I asked him, what he called his unwritten word?

"`He said, '`the written word is the scriptures;
and the unwritten word is that which the apostles spake by word of mouth;
which,`' said he, '`are all those traditions that we practise.`'

"`I bid him '`prove that by scripture.`'

"`Then he brought that scripture, where the apostle says,
(2 Thess. 2:5) '`When I was with you, I told you these things.`'
'`That is,`' said he, '`I told you of nunneries and monasteries,
and of putting to death for religion, and of praying by beads, and to images,
and all the rest of the practices of the Church of Rome; which,`' he said,
'`was the unwritten word of the apostles, which they told then,
and which has since been continued down by tradition, unto these times.`'

"`Then I desired him to read that scripture again,
that he might see how he had perverted the apostle`'s words.
For that which the apostle there tells the Thessalonians,
'`he had told them before,`' is not an unwritten word, but is there written down, namely;
that '`the man of sin, the son of perdition shall be revealed,
before that great and terrible day of Christ,`' which he was writing of, should come.
So this was not telling them any of those things, that the Church of Rome practises.
In like manner, the apostle, in the third chapter of that epistle, tells the church,
of some disorderly persons +++[+++who]
he heard were amongst them; busy bodies, who did not work at all; concerning whom,
he had commanded them by his unwritten word, when he was among them,
that if any would not work, neither should he eat; which now,
he commands them again in his written word in this epistle, (2 Thess.
iii.) So this scripture afforded no proof for their invented traditions;
and he had no other scripture proof to offer; therefore,
I told him this was another degeneration of their church into such inventions and
traditions as the apostles and primitive saints never practised.

"`After this he came to his sacrament of the altar; beginning at the paschal lamb,
and the shew-bread, and so came to the words of Christ,
'`this is my body,`' and to what the apostle wrote of it to the Corinthians; concluding,
'`that after the priest had consecrated the bread and wine, it was immortal and divine;
and he that received it, received the whole Christ.`'

"`I followed him through the scriptures he brought, till I came to Christ`'s words,
and the apostle`'s; and I showed him, that the same apostle told the Corinthians,
after they had taken bread and wine in remembrance of Christ`'s death,
that '`they were reprobates if Christ was not in them.`'^
footnote:[2 Cor. 13:5.]
But if the bread they eat was Christ,
he must of necessity be in them after they had eaten it, etc.

"`Then, as to those words of Christ, '`this is my body,`' I told him, Christ calls himself,
a '`vine,`' and a '`door;`' and is called in scripture, a rock.
Is Christ therefore, an outward rock, door, or vine?

"`'`O!`' said he, '`those words are to be interpreted.`'

"`So,`" said I, "`are those words of Christ, '`this is my body.`'`"

"`Now having stopped his mouth as to argument, I made him a proposal thus; that, seeing,
he said, the bread and wine was immortal and divine, and the very Christ;
and that whosoever received it received the whole Christ;
let a meeting be appointed between some of them (whom the pope
and his cardinals should appoint) and some of us;
and let a bottle of wine, and loaf of bread, be brought, and divided each into two parts;
and let them consecrate which of those parts they would; and then set the consecrated,
and the unconsecrated bread and wine in a safe place, with a sure watch upon it,
and let trial thus be made,
whether the consecrated bread and wine would not lose its goodness,
and the bread grow dry and mouldy, and the wine turn dead and sour, as well and as soon,
as that which was unconsecrated?
'`By this means,`' said I, '`the truth of this matter may be made manifest;
and if the consecrated bread and wine change not, but retain their savour and goodness,
this may be a means to draw many to your church: if they change, decay,
and lose their goodness, then ought you to confess and forsake your error,
and shed no more blood about it; for much blood hath been shed about these things,
as in Queen Mary`'s days.

"`To this the Jesuit made this reply: '`Take,`' said he, '`a piece of new cloth,
and cut it into two pieces, and make, two garments of it;
and put one upon King David`'s back, and the other upon a beggar`'s,
and the one garment shall wear away as well as the other.`'

"`'`Then,`' said I,
'`by this the company may all be satisfied that
your consecrated bread and wine is not Christ.
Have ye told people so long, that the consecrated bread and wine was immortal and divine,
and that it was the very and real body and blood of Christ;
and dost thou now say it will wear away or decay, as well as the other!
I must tell thee, Christ remains the same, today as yesterday, and never decays;
but is the saints`' heavenly food in all generations, through which +++[+++food]
they have life.`'

"`He replied no more to this, being willing to let it fall;
for the people that were present saw his error, and that he could not defend it.

"`Then I asked him,
why their church did persecute and put people to death for their religion?

"`He replied, it was not the church that did it, but the magistrates.

"`I asked him whether those magistrates were not counted and called,
believers and Christians?

"`He said '`Yes.`'

"`'`Why then,`' said I, '`are they not members of your church?`'
"`'`Yes,`' said he.

"`Then I left it to the people to judge, from his own concessions,
whether the Church of Rome doth not persecute, and put people to death for religion?`"

And here it seems the conference was brought to a close;
the subtlety of the Jesuit serving him in no stead, against the simplicity of the Quaker.

"`About this time,`" he says in his Journal, "`the Lady Claypole, (so called,) was sick,
and much troubled in mind, and could receive no comfort from any that came to her; which,
when I heard of, I was moved to write to her.

The letter itself is too long for insertion here; but the counsels it contains,
(though from being worded in his own very peculiar phraseology, they are not,
at first sight, very perspicuous,) are such as must be valuable to every spiritual mind,
in seasons of trial.

He begins by desiring her to "`be still and cool in her own
mind and spirit,`" in order that the principle of God,
(or gift, or seed of the Holy Spirit,) sown in her heart, may have power to arise,
"`to turn thy mind,`" he says, "`to the Lord God, from whom life comes;
whereby thou mayest receive his strength and power,
to allay all blustering storms and tempests.`"
He then tells her, that it is this divine principle which, as he expresses it,
"`works up into patience, into innocency, into stillness, into stayedness,
into quietness,`" etc.
He describes the mind, in a transgressing state,
as "`flying up into the air,`" and "`then,`" he says,
"`the creature is led into the night,`" +++[+++into obscurity.]
"`Therefore, be still awhile, from thy own thoughts, desires, imaginations, etc.,
and be stayed +++[+++or rest]
in the principle of God within thee; and thou wilt find him to be a God at hand,
a present help in the time of trouble.`"

He then tells her she must deny herself, and from her own will,
(which is the earthly will,) she must be kept.
Following these directions, he says, she will know the physician of value,
who clothes people with their right mind, in which mind they may serve God,
and do his will.

He counsels her, especially, not to look at the evil which this divine principle,
or light within her, reveals, "`for looking down,`" he says, "`at sin, and corruption,
and distraction, +++[+++confusion,]
ye are swallowed up in it; but looking +++[+++up]
at the light, +++[+++or Holy Spirit,]
which discovers these evils, ye will see over them.`"

In thus placing the power of redemption from evil, in the light,
he is as sound in scriptural doctrine, as he is wise in moral experience.
"`Look unto me, and be ye saved,`" says he, who proclaims himself the light of the world;
and who shines not partially on this or that individual,
but who is "`the true light that enlighteneth every man that cometh into the world.`"
And who is there that, under the heaviest pressure of conscious guilt,
has yet fixed a calm, humble, silent,
but inwardly supplicating eye upon this day-star in the heart--this mighty one,
who wounds but to heal --who kills but to make alive--who is there,
we may confidently ask, that has steadily and perseveringly done this,
and has not experimentally known, as this man of God testifies,
that the Most High "`is a God at hand, and a present help in the time of trouble?`"

When this letter was read to Lady Claypole, she said it stayed her mind for the present.
"`Afterwards,`" says George, "`many friends got copies of it,
both in England and Ireland, and read it to people that were troubled in mind;
and it was made useful for the settling of the minds of several.`"

This Lady Claypole was the favourite daughter of Oliver Cromwell,
who deeply felt her loss,
(for she died shortly after the period of receiving this letter.) Nor was it long,
before Oliver himself followed her; both he and his daughter dying in the same year.

It was about this time, that some circumstances occurred at Boston in America,
of such peculiarly painful interest to the Society of Friends, that,
revolting to humanity as the recital of them may be,
it would scarcely be excusable to omit it; but in recording these sad events,
it should be remembered,
that in no nation would such barbarities be note more reprobated, than in America.

So early as the year 1656, two female members of the society, named Mary Fisher,
and Ann Austin, arrived in the road before Boston;
no prohibition then having been issued against
the entrance of the Quakers into that city.
Nevertheless, officers were sent on board their ship, who searched their chests,
took away about one hundred books, which they carried ashore,
and having commanded the women to be kept as prisoners in the vessel, the books,
by an order from the council, were burnt in the market-place, by the hangman.
The females were then brought on shore, and upon the proof that one of them, in speaking,
had said thee, instead of you, they were committed to prison as Quakers.
Being closely confined, their pens, ink, and paper were taken from them;
and under pretence of examining if they practised witchcraft,
very cruel indignities were offered to their persons; added to which barbarities,
they were so little cared for as to food, that if one Nicholas Upshall,
a pious and benevolent man, resident in the town,
had not purchased provision for them of the jailer, at the rate of five shillings a week,
they must have been starved.

After having been about five weeks imprisoned, one William Chichester,
the master of a vessel, was bound in one hundred pounds`' bond, to carry them home,
and not to suffer any person to speak to them whilst on board.

"`Such,`" says Sewel, from whom this account is taken,
"`was the entertainment the Quakers first met with at Boston, and that,
from a people who pretended that, for conscience sake,
they had chosen the wildernesses of America before the well-cultivated Old England.

Anomalous indeed, as is such a case,
it happened that the perpetrators of so much persecution,
were those who had themselves experienced the rod of the oppressor;
being for the most part, persons who, in the days of the first Charles and his bishops,
not feeling easy to conform to the mode of national worship, and either unable, or,
as they supposed, uncalled upon, to sustain the penalty attached to non-conformity,
had fled for safety into America,
where they had succeeded in establishing themselves in ease and authority.

It will now naturally be inquired,
what motive could stimulate such extreme severity
towards such apparently harmless individuals,
and that before the possibility of offending had been afforded them.

The answer to this inquiry must be sought in the darkest depths of human corruption.
In those gloomy caverns indeed, must we search for the secret springs of all oppression;
but a degree deeper, and a shade darker than ordinary,
must we expect to find the subtle iniquity which
moved the hearts of the English refugees,
to show so much cruelty to their brethren.

I do not however urge as a reason,
but only offer it as an hypothesis to the consideration of the reader,
whether there might not occur moments in the life of these refugees,
when it would seem to them, that they had acted a nobler part,
had they stood their ground, in the fiery trial appointed them in their native land,
rather than to have sought their safety in flight?
and whether, under these secret goadings of conscience,
the contemplation of those who were "`enduring hardness as good
soldiers of Jesus Christ,`" counting not their lives dear unto them,
so that they might fulfill the will of God,
(as was almost universally the case with the Quakers,)
would not be so insupportably painful a reflection,
as to urge them to the strongest measures in order to escape from it?

Upon such a view of the case, the treatment which the Quakers received at their hands,
is accounted for; whilst upon any other ground it is unaccountable.

And as, according to the poet`'s statement respecting ambition:

[verse]
____
"`It oft o`'er leaps itself, and falls on t`'other side,`"
____

So, it commonly happens with sinister designs for individual security.
This excessive determination, on the part of the inhabitants of Boston,
not to be molested by the Quakers,
was the cause of drawing the attention of Friends to that quarter;
many amongst them conceiving themselves especially called upon to appear there,
as witnesses against the cruelties that had been
practised upon the unoffending members of their society.
We will not stop to detail the ill-usage which these persons successively received;
but briefly stating that divers penalties having been
vainly levied upon masters of vessels for bringing them,
and upon themselves for coming, at last, at a general court held at Boston,
the 20th October, 1658, the following act was made; which no doubt,
would seem to the framers thereof, to be perfectly effectual to prevent their return.

"`Whereas there is a pernicious sect, (commonly called Quakers,) lately risen,
who by word and writing have published and maintained many dangerous and horrid tenets,
and do take upon them to change and alter the received laudable customs of our nation,
in giving civil respect to equals, or reverence to superiors;
whose actions tend to undermine the civil government,
and also to destroy the order of the churches,
by denying all established forms of worship,
and by withdrawing from orderly church-fellowship,
allowed and approved by all orthodox professors of the truth; and instead thereof,
and in opposition thereunto, frequently meeting by themselves,
insinuating themselves into the minds of the simple,
or such as are least affected to the order and government of church,
and commonwealth whereby divers of our inhabitants have been infected;
and notwithstanding all former laws made,
upon the experience of their arrogant and bold
obtrusions to disseminate their principles among us,
prohibiting their coming in this jurisdiction,
they have not been deterred in their impetuous attempts to undermine our peace,
and hazard our ruin;

"`For prevention thereof, this court doth order and enact, that every person, or persons,
of the cursed sect of the Quakers, who is not an inhabitant of, but is found within,
this jurisdiction, shall be apprehended without warrant, where no magistrate is at hand,
by any constable, commissioner, or select man, and conveyed from constable to constable,
to the next magistrate, who shall commit the said person to close prison,
there to remain without bail, unto the next court of assistants,
where they shall have a legal trial;
and being convicted to be of the sect of the Quakers, shall be sentenced to be banished,
upon pain of death; and that every inhabitant of this jurisdiction,
being convicted to be of the aforesaid sect,
etc. etc. shall be committed to close prison for one month, and then,
unless they choose voluntarily to depart this jurisdiction,
shall give bond for their good behaviour, and appear at the next court, where,
continuing obstinate, and refusing to retract and reform the aforesaid opinions,
they shall be sentenced to banishment, upon pain of death; and any one magistrate,
upon information given him of any such person, shall cause him to be apprehended,
and shall commit any such person to prison, according to his discretion,
until he come to trial as aforesaid.`"

If it should be supposed that the originators of this sanguinary act,
never intended to proceed to the execution of it, but only proposed the hanging of it,
in terrorem, over the heads of those who were the subjects of it,
it will be seen that they were perfectly in earnest in their terrific threats,
as the event too plainly manifested.

The two first martyrs to this inhuman procedure, were natives of England;
one a London merchant, named William Robinson, and the other Marmaduke Stevenson,
a countryman of Yorkshire.
These persons coming to Boston in the beginning of September, 1659,
were sent for by the court of assistants, and sentenced to banishment, on pain of death;
and William Robinson, being considered as a teacher,
was condemned to be severely whipped; which was fulfilled,
by his being brought into the street, and there stripped;
and his hands being put through the apertures of the carriage of a great gun,
the jailer held him,
whilst the executioner gave him twenty stripes with a three-fold cord whip.

Besides Robinson and his friend, there were two others, at that time at Boston,
upon whom the same sentence of banishment, on pain of death, was passed.
One of these, named Mary Dyar, was a native of Rhode Island, and who had, once before,
been imprisoned as a Quaker at Boston, and only released by her husband`'s interference;
he himself, not being a member of the society.
This person, (Mary Dyar,) and the other, named Nicholas Davis,
departed from the jurisdiction for that time; but Robinson and Stevenson,
though they quitted Boston, did not feel themselves at liberty to quit the jurisdiction,
though their lives were at stake;
they therefore went to Salem and other places thereabouts, to visit their friends,
and establish them in the faith.

It was not long before they were again in custody, and Mary Dyar returning also,
they were all three imprisoned once more at Boston.

On the 20th of October they were brought into court; where the governor Endicot,
and others were assembled;
and after some remarks upon the futility of the laws which had
hitherto been made to prevent their appearance at Boston,
some of which, he said, had been eminently severe, such as whipping, imprisoning,
and even cutting off ears,
(a sentence which had been already executed upon some of the Quakers,) he added,
that banishing, upon pain of death,
would not suffice to keep them from coming amongst them.
And although he professed that neither he, nor those acting with him,
desired their death, yet, the next words he uttered were, "`Give ear,
and hearken to your sentence of death.`"

William Robinson then desired that he might be permitted to read a paper
giving an account of the reason why he had not departed that jurisdiction;
but this Endicot, with much fury, refused.
It was therefore laid upon the table by Robinson, and being handed to Endicot,
he read it to himself; observing, when he had done,
that Robinson need not have been so anxious to have it read,
as he had said more the day before, than what was there written.

The substance of the writing was explanatory of the
reasons which had induced him to come to Boston.
Being on Rhode Island, he said, on the 8th of the 8th month,
the Lord had commanded him to go to Boston, and lay down his life there.
That, at the same time,
he felt an assurance that his soul was to enter into everlasting peace and rest.
That he durst not disobey; believing that it became him, as a child,
to show obedience to the Lord, without any unwillingness.
That this was the cause, why, after banishment on pain of death,
he still stayed in their jurisdiction; adding, "`now with sincerity of heart, I can say,
blessed be the Lord, the God of my life, who hath called me hereunto,
and counted me worthy to testify against wicked and unjust men!`"

Again he requested that this paper might be read aloud, that all present might hear it.
But in vain.
Nothing was he to receive but sentence of death; which Endicot then pronounced.

His companion, Stevenson, being called,
received permission to speak anything he might have to say.
But he remained at that time silent; knowing how it had just fared with his companion.

His mouth however was opened as soon as his sentence was pronounced;
and an awful testimony delivered from it upon his unrighteous judges.

"`Give ear, ye magistrates,`" he said, "`and all who are guilty;
for this the Lord hath said concerning you, and will perform his word upon you;
that the same day ye put his servants to death,
shall the day of your visitation pass over your heads,
and ye shall be cursed forevermore.
The mouth of the Lord hath spoken it.
Therefore in love to you all, I exhort you to take warning before it be too late,
that so the curse may be removed.
For assuredly, if you put us to death, you will bring innocent blood upon your own heads,
and swift destruction will come upon you.`"

As soon as this was uttered, he was taken away,
and Mary Dyar was called and also received sentence of death;
to which she merely replied,
"`The will of the Lord be done!`" and being ordered from the bar, "`yea,
joyfully I go,`" she said;
assuring the marshal who was appointed to conduct her to prison,
that he might leave her free, for she would go there without restraint.

"`I believe you, Mrs.
Dyar,`" said he; "`but I must do what I am commanded.`"

Being sent back to prison, she wrote an address to the General Court of Boston,
refuting a charge which had been made against her, in common with her fellow-sufferers,
that they were guilty of their own death, by their obstinacy,
and urgently entreating the governor and authorities of the place,
to consider what they were doing, in shedding innocent blood, etc.

The day appointed for the execution of these victims,
was the 27th of October in the afternoon,
when they were led to the gallows by two military officers,
accompanied by a band of about two hundred armed men, besides many horsemen;
a measure which plainly indicated that some fear of popular indignation was apprehended.

And, that no appeal might be made to the feelings of the multitude,
a drummer was appointed to march before the condemned persons, to beat the drum,
especially when any of them attempted to speak.

Glorious signs of heavenly joy and gladness were
visible in the countenances of these holy martyrs,
who walked hand in hand to the place where they were to suffer;
a circumstance which drew upon Mary Dyar, even at that solemn moment,
an unfeeling taunt from one of the barbarians who conducted them; and who asked her,
if she was not ashamed to walk thus, hand in hand between two young men.

"`No,`" replied she, "`this is to me an hour of the greatest joy!`" adding,
that no eye could see, no ear could hear, no tongue could utter,
no heart could understand, the sweet refreshings of the Spirit of the Lord,
which she then felt.

Some further insults were their portion, which it would be only painful to relate.
Suffice it to say, that, for the two men, deliverance from every woe was shortly near;
for the female, a strange, and, according to her estimation,
an undesired reverse of circumstances occurred.
Being come to the ladder, and having taken leave of each other with tender affection,
Robinson and Stevenson yielded up their lives into the hands of their enemies.
Robinson`'s last words being, "`I suffer for Christ, in whom I live,
and for whom I die;`" and those of Stevenson,
"`This day shall we be at rest in the Lord!`"

And now, Mary Dyar, seeing her beloved friends hanging dead before her,
also stept up the ladder; every preparation for her execution being made,
even to the rope being put about her neck,
and her face covered with a handkerchief,-- when suddenly a
cry was made--"`Stop!--for she is reprieved!!`"

"`Her feet then being loosed,`" says Sewel, "`they bade her come down.
But she, whose mind was already as it were in heaven, stood still,
and said she was there, willing to suffer as her brethren did;
unless they would annul their law.
Little heed was given to what she said; but they pulled her down,
and the marshal and others taking her by the arms, they carried her to prison again.`"

Her reprieve was the result of the intercession of her son, whom,
on some account or another, the court of Boston were disposed to favour.

On the following day, she addressed another letter to the court,
wherein she said the reprieve was "`a disturbance to her,
when she was so freely offering up her life to him that gave it,
and who had sent her there to do so--"`which obedience,`" she says, "`being his own work,
he gloriously accompanied with his presence and peace, and love in me;
in which I rested from my labours.`"
She assured them, that she chose rather to die than live, accepting of their mercies,
who had embrued their hands in the blood of the innocent.

"`I leave you,`" she continues, "`to the righteous Judge, and searcher of all hearts;
who, with the pure measure of light he hath given to every man to profit withal, will,
in his due time, let you see whose servants you are, and of whom you have taken counsel, etc.

"`Read your portion,`" she says, with holy indignation--"`read your portion,
Proverbs 1:24 to 82. For, verily the night cometh on you apace,
wherein no man can work; in which you shall assuredly fall to your own master.
In obedience to the Lord, whom I serve with my spirit, and pity to your souls,
which you neither know, nor pity,
I can do no less than once more warn you to put away the evil of your doings;
and kiss the Son (the light in you) before his wrath be kindled in you;
for where that is, nothing without you, can help or deliver you out of his hand at all;
and if these things be not so, then say there hath been no prophet from the Lord,
sent amongst you; though we be nothing, yet it is his pleasure, by things that are not,
to bring to nought things that are.`"

It was not without the manifestation of much discontent,
that the populace beheld these murderous transactions; and by way of calming them,
it was resolved to send Mary Dyar away.
Being put on horseback, she was conveyed by an escort of four persons,
fifteen miles towards her own habitation in Rhode Island; and from thence,
she was to have been conducted by a man and horse home; but sending him away,
she repaired thither alone.

A singular circumstance, and by many considered as a token of the divine displeasure,
occurred, as the people were returning sad, and heavy,
from the execution of Robinson and his friend; a drawbridge over which they had to pass,
falling at one end, hurt several persons; and, amongst the rest,
one woman who had insulted over the poor victims, was so severely injured,
as to remain in a condition of suffering worse than death, for the rest of her days.

But, although for a short time delivered from the hands of her persecutors,
Mary Dyar found it impossible to resist the internal impulse,
(coming as she believed it did from God,) which, after the winter was past,
drew her again to Boston.
On the 21st of May in the following year, (1660,) she appeared there once more; and,
on the 31st, she was summoned by the general court, and questioned by the governor,
Endicot, if she was the same Mary Dyar that was there before;
another person of her name having newly returned from England, and he being,
as it seemed, desirous of favouring her, by supplying her with the means of evasion;
but disdaining any subterfuge,
she immediately acknowledged herself to be the same he inquired for.

After some little discourse, Endicot again pronounced sentence upon her;
and on her telling him, that he said no more than what she had heard before, he replied,
that now it would assuredly be executed;
desiring her to prepare for the fulfilment of it, by nine o`'clock the next day.

To this she replied, "`I came in obedience to the will of God, the last general court,
desiring you to repeal your unrighteous laws of banishment on pain of death;
and that same is my work now, and earnest request; although I told you,
that if you refused to repeal them,
the Lord would send others of his servants to witness against them.`"

Some more words she would have uttered, in reply to a sneering inquiry from Endicot,
whether she was a prophetess?
But, as she began to speak, he commanded her to be taken away;
and being again lodged in her former prison,
she was there closely confined till the following day; when, for the second time,
this noble-minded woman was led forth to death.

A band of soldiers attended her, the drums being beaten on every side,
that none might hear her speak, all the way she passed,
(which was about a mile,) to the place of execution.

Having ascended the ladder, it was told her by some standers by, that even now,
she might come down and save her life.

"`Nay,`" said she, "`I cannot; for in obedience to the will of the Lord, I came;
and in his will, I abide faithful to death.`"

Several remarks were addressed to her by the standers-by, but mostly of a malignant kind;
no persons, probably, but those who favoured these unrighteous dealings,
having the means of speaking to her.

To all of them she replied with firmness and simplicity;
and on some one reminding her that she had said she had been in paradise,
she promptly answered, "`Yea, I have been in paradise several days.`"

In no degree did this magnanimous sufferer, (to all intents and purposes,
twice a martyr,) shrink from her doom; but, well knowing in whom, and for whom,
she was about to die, contentedly laid down her life.

One more victim remains to be spoken of, by name William Leddra.
This individual, in company with one William Brend,
had been imprisoned in Boston the preceding year,
for coming into the jurisdiction of that city,
in defiance of the law which proscribed the Quakers therefrom.

Humanity forbids the recital of the cruel treatment
inflicted upon William Brend on this occasion;
or the condition to which (being an aged man) his afflicted body was reduced,
by the stripes that were laid upon him.
Some idea of the case may be formed, by the fact, that when the report of the surgeon,
who had seen his wounds, was known to the populace, they were so exasperated,
that the magistrates were obliged to make a show of regret,
by affixing a paper on the door of a public building,
expressing dislike of the treatment Brend had received;
and promising that the jailer who had inflicted it,
should be dealt with at the next court.

One of the refugees, a minister of the gospel, John Norton by name, who,
from the beginning had been a fierce persecutor of the Quakers,
endeavoured to justify such proceedings,
by saying that William Brend had endeavoured to
beat their gospel ordinances black and blue;
if he therefore, were himself beaten black and blue, it was but just; adding,
that he himself would appear on behalf of the person who did so.

It pleased God, however, almost by a miracle to heal this poor sufferer;
but not deterred by so undeserved a favour, from prosecuting their cruelties,
(than which,
the records of the Inquisition scarcely furnish greater,) the
persecutors of these helpless people,
ordained, that whoever amongst the imprisoned Quakers,
refused to work (which had been the offence of Brend) should be whipped twice a week.

The submitting to work,
appearing to be a tacit acknowledgment of the justice of their imprisonment,
it was not to be supposed they could conscientiously accede to it.
Four of them were therefore subjected to this ignominious sentence of whipping;
amongst whom was William Leddra, the remaining victim just alluded to.

Being at length released from prison, and banished from Boston on pain of death,
he was under such distress of conscience,
that he could find no peace till he returned thither; which he accordingly did,
the year subsequent to the death of the three friends above mentioned.
He was soon taken prisoner again; and being fastened to a log of wood,
was kept night and day locked in chains, in an open place, during a very cold winter.

Early in the year 1661, he was brought into the court of assistants,
with his chain and log at his heels;
and after various futile questions on the part of his judges,
he was asked by one Broadstreet, if he would go to England?

"`I have no business there,`" he replied.

"`Then you shall go that way,`" said Broadstreet, pointing to the gallows.

"`What, will you put me to death,`" he replied,
"`for breathing the air of your jurisdiction?
And as for what you have against me, I appeal to the laws of England for my trial;
and if by them, I am found guilty, I refuse not to die.`"

Of this reply, no notice was taken;
but they proceeded to persuade him to recant what they called his errors.
But, with noble disdain, "`What!`" said he, "`to join with such murderers as you are!
Then, let every man that meets me say, lo,
this is the man that hath forsaken the God of his salvation!`"

Whilst this trial of William Leddra was going on, it happened that Wenlock Christison,
a Quaker who had been banished on pain of death, suddenly came into court.
A mysterious awe attended his appearance; insomuch, that, according to Sewel,
for some space of time, there was silence in the court.

But, as if their safety consisted in their effrontery,
one of this sanguinary council called out, "`Here is another;
fetch him up to the bar;`" which the marshal performing, the secretary Rawson said,
"`Is not your name Wenlock Christison?`"

Which being acknowledged,

"`Well, what dost thou here?`"
inquired the governor Endicot.

"`I am come,`" he said, "`to warn you that you should shed no more innocent blood;
for the blood which you have shed already,
cries to the Lord God for vengeance to come upon you.`"

It would seem that the hour for the strivings of God`'s good spirit in their hearts,
was past; for this, and all other appeals to their conscience, was made in vain.
"`Take him away, jailer,`" was the reply to this expostulation;
and Leddra remaining firm to his resolution not to depart their city or jurisdiction,
in any will, but the will of God,--they proceeded to pass sentence upon him--which over,
he was led back to prison.

The day before his death, he wrote a letter to his friends,
in which he describes himself to be "`so filled with the joy of the Lord,
in the beauty of holiness, that my spirit,`" he says,
"`is as if it did not inhabit a tabernacle of clay,
but is wholly swallowed up in the bosom of eternity, from whence it had its being.

"`Alas! alas!`" he proceeds, "`what can the wrath and spirit of man,
that lusteth to envy, aggravated by the heart and strength of the king of the locusts,
which came out of the pit,^
footnote:[Rev. 9:1-3.]
+++[+++what can it]
do unto one that is hid in the secret place of the Almighty,
or unto them that are gathered under the healing wings of the Prince of Peace?
under whose armour of light, they shall be able to stand in the day of trial,
having on the breastplate of righteousness, and the sword of the Spirit,
which is their weapon of war against spiritual wickedness, principalities, and powers,
and the rulers of the darkness of this world, both within and without?`"

He then pathetically reminds them of the earnestness
with which he had waited for Divine direction,
in addressing them; fearing, even greatly as he loved them,
to communicate anything but what the Spirit of his Heavenly Father gave him to say.

"`Oh, my beloved!`" he says, "`I have waited as a dove, at the windows of the ark,
and have stood still in that watch, which the Master,
(without whom I could do nothing,) did, at his coining, reward with fulness of love;
wherein my heart did rejoice, that I might, in the love, and life of God,
speak a few words to you, sealed with the spirit of promise,`" etc.
Yet, he assures them, that had he been altogether silent,
the Lord would have confirmed in their hearts,
a sense of the innocence with which he was about to suffer.
He addresses many words of counsel adapted to their severe exercises of spirit,
and concludes by commending them to the grace which was sufficient for them,
and by which alone they could witness salvation.

On the day after this letter was written, the execution of William Leddra took place.
Having taken leave of his friend, Wenlock Christison, and others who were in bonds,
he was escorted by a guard to the place of slaughter,--
a friend of the name of Edward Wharton,
accompanying him.
Being brought to the foot of the ladder, he was pinioned;
and as he was about to ascend it, he took leave of his friend, to whom he said,
"`All that will be Christ`'s disciples, must take up the cross.`"

Whilst standing upon the ladder,
some one asked him if he had anything to say to the people?

To which he replied, "`For the testimony of Jesus, and for testifying against deceivers,
and the deceived, I am brought here to suffer.`"

These words producing some emotion amongst the crowd, a person of the name of Allen,
one of their ministers, addressed the spectators in these words: "`People!
I would not have you think it strange, to see a man so willing to die;
for that is no new thing.
And you may read how the apostle said, that some should be given up to strong delusions,
and even dare to die for it.`"

"`But,`" observes Sewel, "`he did not say where the apostle speaks so;
neither have I found it anywhere in holy writ;
though I know that Paul saith (Rom. 5:7) "`Peradventure,
for a good man some would even dare to die.`"

But nothing disturbed the steadfastness of Leddra, who,
patiently submitting himself whilst the executioner put the halter about his neck,
departed with these words, "`I commit my righteous cause unto thee,
O God!`" and as he was turned off, "`Lord Jesus receive my spirit!`"

It is some relief to find that he was the last victim to this sanguinary law; for,
although others were then in confinement,
with the prospect of having the sentence of death pronounced and executed upon them, yet,
it happened that by this time,
such tidings had reached the ears of the English government, of these proceedings,
that prompt measures were set on foot to frustrate the continuance of them.

"`The news of William Leddra`'s death coming to England,`" says Sewel,
"`with an information of the danger that others were in of going the same way,
their friends took it so to heart, especially Edward Burrough, that,
having got audience of the king, he said to him,
"`there was a vein of innocent blood opened in his dominions, which,
if it were not stopped, would over-run all.`"
To which the king replied, "`But I will stop that vein.`"
Then Burrough desired him to do it speedily;
"`for we know not,`" said he "`how many may be put to death.`"
The king answered, "`As soon as you will.`"

The result of this permission was, the sending out, on the part of the English friends,
a vessel, conducted by a Quaker, Samuel Shattock by name; who,
being an inhabitant of New England, had been banished on pain of death,
if ever he returned thither.
To him the king granted a deputation, with full power to carry the following mandamus:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Charles R.

"`Trusty and well beloved, we greet you well.
Having been informed that several of our subjects amongst you, called Quakers, have been,
and are imprisoned by you, whereof some have been executed,
and others (as hath been represented unto us) are in danger to undergo the like;
we have thought fit to signify our pleasure in their behalf for the future;
and do hereby require, that if there be any of those people called Quakers amongst you,
now already condemned to suffer death; or other corporal punishment,
or that are imprisoned, and obnoxious to the like condemnation,
you are to forbear to proceed any further therein;
but that you forthwith send the said persons,
(whether condemned or imprisoned,) over into this our kingdom of England,
together with the respective crimes or offences, laid to their charge;
to the end that such course may be taken with them here,
as shall be agreeable to our laws, and their demerits.
And for so doing, these our letters shall be your sufficient warrant and discharge.

[.signed-section-closing]
"`Given at our court at Whitehall, the 9th day of September,
1661, in the thirteenth year of our reign.

[.signed-section-closing]
"`By his Majesty`'s command,

[.signed-section-signature]
"`William Morris.

[.postscript]
====

"`Addressed: To our trusty and well-beloved John Endicot, Esq.,
and to all and every other the governor, or governors of our plantations of New England,
and of all the colonies thereunto belonging, that now are, or hereafter shall be;
and to all and every the ministers and officers of our said plantations and colonies whatsoever,
within the continent of New England.`"

====

--

This mandamus being obtained, no time was lost in dispatching it; and in six weeks`' time,
Samuel Shattock, the bearer of it, entered the Bay of Boston, on a Sunday morning.

The usual officers were immediately dispatched from the town; who, on arriving on board,
asked if they brought any letters from England?

"`Yes.`"

Would they not be delivered?
"`No, not today.`"

"`So they went a-shore,`" says Sewel,`" and reported there was a ship full of Quakers,
and that Samuel Shattock was amongst them; who, they knew, was by their law,
liable to be put to death, for coming again, after banishment.`"

On the next morning, Shattock, and Ralph Goldsmith, the commander of the vessel,
(himself also a friend,) went on shore, and knocked at governor Endicot`'s door.
A man being sent to know their business,
they replied "`that their business was from the King of England;
and that they would deliver their message to no one but the governor himself.`"
Upon which, they soon obtained admission; and Endicot shortly coming to them,
his first salutation was a command that Shattock`'s hat should be taken off;
(not impossible, perhaps, but a slight wish might cross his mind,
that the head could be taken off also.)

As soon as he had read the mandamus, the governor also took off his hat;
and ordered that Shattock`'s hat should be given him again; and then going out,
he went to the deputy-governor, and bade the king`'s deputy,
and the master of the ship to follow him.
Having consulted with the deputy-governor about the matter,
he returned to the two friends, and said, "`We shall obey his majesty`'s command.`"
The master of the ship afterwards giving liberty to the passengers to come ashore,
they met together with their friends of the town, and offered up praises to God,
for this wonderful deliverance.
