== Chapter VIII.

It may be supposed, that the foregoing acts of cruelty did not transpire,
without some attempts at palliation by the perpetrators thereof; of which attempts,
the best judgment will be formed,
by viewing them in connexion with the reception they met with,
from some members of the society in England.
Francis Howgill, and also others, wrote very forcibly on the subject;
but passing by these, I select some passages from the work of Isaac Penington, entitled,
"`An Examination of the Grounds or Causes, which are said to induce the Court of Boston,
in New England, to make that Order, or Law of Banishment, upon pain of Death,
against the Quakers,`" etc.^
footnote:[See vol.
I. of his Works, p. 260. Edition of 1761; printed for Kendal, Colchester,
in two quarto vols.]
and which, being chiefly written in reply to an apologetic work of the minister Norton,
will sufficiently inform the reader,
what sort of excuses were found for the atrocities above related.

"`The grounds, or causes,`" (says Penington,) expressed,
of their making that law of banishment, are, in substance, three.

The first cause stated it to be, the coming of the Quakers from foreign parts,
and from other colonies, at sundry times, and in several companies and numbers,
into the jurisdiction of the Massachusetts.

"`This of itself,`" he observes, "`is far from any warrant;
for the earth is the Lord`'s and the fulness thereof.
And though they +++[+++the inhabitants of Boston]
claim a propriety in it, yet it is still more the Lord`'s than theirs;
and he may send any one of his servants into it, at his pleasure, upon what message,
or service, it seemeth good unto him.
So that the great question to be determined here, is this;
"`whether these persons came from the Lord, in his will, and at his appointment,
or whether they came of themselves, and in their own will,`" etc.
He then inquires of them, if they were sufficiently cautious in searching into this;
"`If, at their first coming,`" he says, "`you imprisoned them,
and engaged yourselves against them,
ye thereby made yourselves unfit for an equal consideration of the cause;
and God might justly then leave your eyes to be closed,
and your hearts hardened against his truth and people,
for beginning with them so harshly and unrighteously.`"

The second reason alleged for this law, was, that,
"`the lesser punishment of the house of correction, and imprisonment for a time,
had been inflicted on some of them, but had not sufficed to deter and keep them away.`"

"`Why do ye omit cutting off of ears?`"
he asks, (such a law having been made and executed upon some of the friends,
by these fierce legislators.) "`Are ye ashamed to mention that amongst the rest?`"
he says.
"`Indeed, the remembrance of it strikes upon the spirits of people here,
and perhaps in New England also.`"

He then proceeds to answer this, their second reason, by saying,
"`They that are sent by the Lord, and who go in the guidance of his spirit,
cannot be deterred from obedience to him, in his service and work,
either by lesser or greater punishments.
For they whose lives (in the power of God) are sacrificed to the will of God,
are no more afraid of death, than they are of whips, prisons, cruel usage in prisons,
and cutting off of ears.`"
He tells them, that, upon their own showing,
their severity resulted from the evil report of the Quakers,
which had preceded their arrival in Boston; "`which report,`" said they,
+++[+++in one of their manifestos on the subject,]
they had received "`from good hands in Barbadoes and England.`"
"`And so,`" says Penington, "`they of Damascus might have said,
if they had received the letters from the high-priest,
or relations from zealous and devout Jews.`"
He tells them, that he had heard, from good authority,
that the persecuted Quakers were never allowed a fair hearing at their court;
"`nor suffered to plead the righteousness and innocency of their cause, etc.
Your consciences,`" he adds, "`know how true these things are,
and will one day give in a clear and true testimony,
although ye should be able to bribe them at present.`"

The third reason alleged, was,

That their coming thither, was upon no other ground or occasion,
for aught that could appear, than to scatter their corrupt opinions,
and to draw others to their way, and so to make disturbance.

In answer to this, he remarks, that Christ said to his disciples,
"`Ye are the salt of the earth,
and the light of the world;`" and they were not to lie still,
and keep their light under a bushel; but to lighten and season the world,
as the Lord required them; "`and if,`" he continues,
"`the Lord had seen that New England,
notwithstanding all its profession and talk of the things of God,
had need of further enlightening, and so sent his servants and messengers amongst them,
they had no reason to be offended with him for this, or with his people,
or with the truths they brought.`"
In reference to their calling the principles of friends "`corrupt opinions,`" he says,
with great justice, "`Those that pick a quarrel with truth,
and seek matter against it to persecute it, do not call it truth; but error,
corrupt opinions, the way of a sect, the making of disturbance, or such like.`"

"`And how can ye say,`" he asks, "`for aught that could appear?
when ye were so unfit (through receiving of prejudices and reports,
and beginning so roughly with them,) to consider what might be made appear;
and also so far from giving way to them to make what they could, appear, etc.
There may be a just, righteous, and warrantable cause of their coming,
in relation to God, and his service, though it doth not yet appear to you;
and in a meeker, cooler temper, when another eye is opened in you,
ye may see and acknowledge that cause, and who are the Lord`'s servants;
and whether they come in his name, or no--and whether they are his truths or no,
which they bring with them.
These are things,`" he continues, "`which God opens to the humble, to the meek,
to such as fear before him, and wait for his counsel therein;
but those that can determine things by intelligence before-hand, from other parts,
and imprison persons as soon as they come, and so proceed on,
with a stiff resolution against them;--how are these in
any capacity to seek or receive counsel from God,
in a case of so great concernment?
So that at last, even when they have drunk their blood, they must be forced to say,
'`for aught that could appear,`' this was their only end, work, and intent;
but whether it was so or no, they do not certainly know?`"

Having thus noticed the account they gave,
by way of preface to their reasons for making these laws,
he proceeds to examine the grounds upon which they held
themselves excused in so doing-- and for the first:

"`'`The doctrine of this sect of people`" say they,
"`is destructive to fundamental truths of religion; of which doctrine,
four instances are given; viz. I. The Sacred Trinity; II. The Person of Christ; III.
The holy Scriptures as a perfect rule of faith and life; IV. The doctrine of perfection.`"

I only glance at the answers of Isaac Penington to these charges; on the first of which,
concerning "`The Sacred Trinity,`" he observes, "`That friends generally,
both in their words and writings, set their seal to the truth of that Scripture,
(1 John 5:7) that '`there are three that bear record in heaven; the Father, the Word,
and the Holy Spirit;`' but, that these are distinct, as three several beings or persons,
they read not; but, in the same place they read,
that '`they are One.`' And as for this title of '`Sacred Trinity,`'`" he says,
"`they find it not in Scripture;
and they look upon Scripture words as fittest to express Scripture things by.
And surely,`" he continues, "`if a man mean the same thing as the Scripture means,
the same words will suffice to express it;
but the papists and school-men having missed of the thing which the Scripture drives at,
and apprehended somewhat else in the wise, imagining part,
have brought forth many phrases of their own invention,
to express their apprehensions by; which we confess we have no unity with;
but are content with feeling the thing which the Scripture speaks of,
and with the words whereby the Scriptures express it.

"`The true trial of spirit,`" he says, "`is not by an assent to doctrines,
which the hypocrite may assent to on the one hand, and the true believer may start at,
on the other; but by feeling them in the inward virtue,`"etc. etc. "`This`" he observes,
"`was the apostle`'s way of trial;
(1 Cor. 4:19-20) '`I will know not the speech of them which are puffed up,
but the power; for the kingdom of God is not in word, but in power.`'
A man,`" he continues, "`may speak high words concerning the kingdom,
and get all the doctrines about it; and yet be a stranger to it,
and quite ignorant of the power; and another may want divers doctrines concerning it,
(perhaps some of those which men call fundamentals,) and yet be a citizen of it,
and in the power.
But now, under the anti-Christian apostasy, men,
wanting the feeling of the life and power, wherein the true judgment is,
own or disown one another, upon an assent or dissent to such and such doctrines,
and so fall into this great error of disowning many whom Christ owns;
and if they find persons not assenting to, or dissenting from,
any of those doctrines which they call fundamentals,
then they think they may lawfully excommunicate and persecute them.
So, by this mistake, they cut off that which is green;
they persecute that wherein is the living sap, and cherish the dry and withered.`"

2nd. Concerning the person of Christ.
"`They believe,`" says Penington, speaking of the Society of Friends,
"`that Christ is the eternal light, life, wisdom, and power of God,
which was manifested in that body of flesh which he took of the virgin:
that he is the king, priest, and prophet of his people; and saveth them from their sins,
by laying down his life for them, and imputing his righteousness to them;
yet not without revealing and in measure bringing forth, the same righteousness in them,
which he wrought for them.
And by experience they know,
that there is no being saved by a belief of his death for them, and of his resurrection,
ascension, intercession,
etc. without being brought into a true fellowship with him in his death,
and without feeling his immortal seed of life, raised, and living in them.
And so they disown the faith in Christ`'s death,
which is only received and entertained from the relation of the letter of the Scriptures,
and stands not in the divine power,
and sensible experience of the begotten of God in the heart.`"

3rd. Concerning the holy Scriptures being a perfect rule of faith and life.
"`The new covenant,`" he says, "`is the covenant of the gospel;
which is a living covenant, a spiritual covenant, an inward covenant,
and the law or rule of it, cannot be written outwardly.
Read the tenor of the new covenant, (Heb. 8:10) '`I will put my laws into their minds,
and write than in their hearts.`'

"`The new creature, which God hath new created in the heart,
in which life breathes and nothing but life breathes, which is taught by God,
and true to God, from its very infancy; that is his rule, whereby he is to walk;
the apostle expressly calls it so, (Gal. 16:15-16) That which is begotten by God,
is a Son; and the Son as he is begotten by the breath of the Spirit,
so he is preserved and led by the same breath; and such as are so led, are sons,
and none else.
For it is not the reading of scriptures, and gathering rules from thence,
that make a son; but the receiving of the Spirit, and being led by the spirit.`"
(Rom. 8:14-15)

4th. "`That opinion of theirs`" say the apologists,
"`of being perfectly pure and without sin, which tends to overthrow the whole gospel,
and the very vitals of Christianity; for they that have no sin, have no need of Christ,
or of his satisfaction, or blood to cleanse them, nor of faith, repentance,`" etc. etc.

Isaac Penington replies to this objection,
by bringing forward the command of Christ--"`be ye
perfect;`" and also the exhortation of the apostle,
"`let us go on unto perfection`"--acknowledging
that it is the steadfast belief of the Quakers,
that the Lord God is able perfectly to redeem from sin in this life:
that he can cast out the strong man, cleanse the house,
and make it fit for himself to dwell in;
that he can "`finish transgression and sin in the heart,
and bring in everlasting righteousness;`" that he can
tread down Satan under the feet of his saints,
and make them more than conquerors over him.
"`But, that every one that is turned to the light of the Spirit of Christ in his heart,
is presently advanced to this state, they never held forth; but that the way is long,
the travel hard, the enemies and difficulties many; and that there is need of much faith,
hope, patience, repentance, watchfulness against temptations,
etc. before the life in them can arise to such a pitch.`"

"`I dare appeal,`" he says, "`to any unbiassed spirit, whether it +++[+++perfection]
be not a precious truth of the gospel of Christ; and a great encouragement, etc.
He that feeleth the everlasting Arm working one sin out of his heart,
cannot but believe that the same arm can work out all,
and pluck up every plant which the Heavenly Father hath not planted;
which hope and belief, causeth him with joy to follow this arm, through the regeneration.
But, if I did believe,`" he says,
"`there were no perfecting the work of redemption in this life, but I must still,
in part, be a slave to Satan, still crying out of the body of sin and death,
and never have my heart purified for the Holy One to inhabit it, etc.
Oh how heavily should I go on!
I am sure it would be as a weight upon my spirit, in resisting of sin and Satan.
This is not the glad tidings of the everlasting gospel;
but sad news from the borders of death,`" etc.

Having proved, after their manner,
that the doctrines of the Quakers were destructive to the fundamental truths of religion,
their opponents conclude that it is lawful for them, and indeed their duty,
to put them to death; a conclusion which is thus expressed;
"`Now the commandment of the Lord is plain;
that he that presumes to speak lies in the name of the Lord,
and turns people out of the way which the Lord hath commanded to walk in,
such an one must not live, but be put to death,`" Zech. 13:3; Duet. 13:6--xviii.
20.

"`By what hath been said against them,`" replies Penington,
"`it is not manifest that they have spoken lies in the name of the Lord.
Nay, if they themselves, who thus charge them, could but soberly and mildly,
and with a Christian spirit, weigh the thing, would it not rather appear, that they,
in thus falsely charging them,
and managing such untrue and unrighteous arguments against them, have spoken lies,
both concerning them, and against the Lord and his truth?
And as for turning men out of the way, that cannot be justly charged on them,
who turn men to Christ the living way,
and deliver the same message that the apostles did; that '`God is light,
and in him is no darkness at all;`' and who point them to that place, where God hath said,
the light is to be found; which is the heart, where God writes the new covenant,
and the laws thereof.
Surely they that direct hither, do not turn men out of the way.
But they that point men to guess at the meaning of Scriptures,
and to gather knowledge and form rules to themselves out of them,
by their own natural wit and, understanding,
which can never reach the mysteries of the kingdom of God,
and which God hides the true knowledge of the Scriptures from,
these are those that turn men out of the way.
For they that rightly understand the Scriptures,
must first receive a measure of the Spirit to understand them with;
even as they that wrote any part thereof,
did first receive a measure of the Spirit to write it by.

"`I would but put this question to your consciences,`" he says,
with searching earnestness; "`whether,
in a conscientious submission to the will of God in this scripture, ye put them to death;
or, whether from the scripture, ye seek a shelter and cover for the thing;
having already done it, or fully purposed to do it?`"

The sixth and last ground whereby the law of banishment
and death against the Quakers is defended,
is this:--"`It was the commandment of the Lord Jesus unto his disciples,
that when they were persecuted in one city, they should flee unto another;
and accordingly, it was his own practice, and the practice of the saints, who,
when they have been persecuted, have fled away, for their own safety.`"

"`This,`" they say, "`reason requires; that when men have liberty unto it,
they should not refuse so to do; because otherwise, they will be guilty of tempting God,
and of incurring their own hurt, as having a fair way open for the avoiding thereof,
but they needlessly expose themselves thereto,`" etc.

"`If, therefore,`" they proceed to say, "`that which is done against the Quakers,
were indeed persecution, what spirit may they be thought to be acted and led by, who are,
in their actings, so contrary to the commandment and example of Christ and his saints,
in the case of persecution, which these men suppose to be their case?
Plain enough it is, that if their case were the same, their actings are not the same,
but quite contrary; so that Christ and his saints were led by one spirit,
and these people by another; for,
rather than they would not show their contempt of authority,
and make disturbance amongst his people,
they choose to go contrary to the express direction of Jesus Christ,
and the approved example of his saints, to the hazard and peril of their own lives.`"

The answer of I. Penington to this subtle reasoning,
is throughout so fine a specimen of the penetrating, but meek dignity,
with which truth detects sophistry,
that I can only regret that the scope to which I
am obliged to confine myself in the present work,
prevents me from offering it entire to the reader`'s perusal.
A few extracts, however, must be given.

"`Afflictions,`" he observes, "`tribulations, trials, persecutions,
are not to be fled from, but to be borne and passed through +++[+++in the way]
to the kingdom; into which, the entrance is, through many of these; and Christ saith,
he that will be his disciple, must take up his cross daily, and follow him.
Now, persecution for Christ, is part of the cross,
which the disciple must not run away from, but take up, and follow Christ with.
Yea, the apostle is very express, (2 Tim. 3:12) '`Yea,
and all that will live godly in Christ Jesus, shall suffer persecution.`'

Christ, warning of persecution,
bids the church to fear none of those things which she should suffer,
but '`be faithful unto death;`' and the apostle Peter says,
'`if ye suffer for righteousness`' sake, happy are ye,`' 1 Peter 3:14. The apostle Paul,
bids the Philippians '`stand fast in one spirit,
with one mind striving together for the faith of the gospel,
and in nothing terrified by your adversaries,`' etc.
And the same apostle,
who commended the Hebrews as having done well in bearing '`a
great fight of afflictions,`' encouraged them to go on still,
and '`not to be weary or faint in their minds,
but to resist even to blood,`' eyeing Christ,
who endured the contradiction of sinners to the very last,
(Heb. 12:3-4) And Paul practised as he taught;
for he was not terrified with bonds or afflictions, nor accounted his life dear unto him;
but that which was dear unto him, was the serving of his Lord and Master,
in preaching and witnessing to his truth, as his Spirit led him,
(Acts 20:23-24) trusting in the Lord to uphold him in enduring of them,
or to deliver him out of them, as he pleased, (2 Tim. 3:11) But that which he,
and the rest of the apostles and saints of Christ applied themselves to,
in case of persecution, was to suffer, 1 Cor. 4:12.
There is a time to suffer persecution,
and a time to flee from persecution; and both these are to be known in the Lord,
and to be obeyed in the leadings of his spirit;
but to lay it down for a general rule for Christians to observe,
that when they are persecuted they should flee,--this is
expressly contrary to the scriptures afore-mentioned;
which show, that Christians are not generally to flee;
but to stand in the service and work to which they are called.`"
... "`And whereas you plead that reason requires it,
what kind of reason is it which bids avoid the cross of Christ, and flee for safety?
And what kind of spirit is that,
which preacheth this doctrine of laying it down as a general rule for Christians to flee,
when they are persecuted?
Is it not that spirit which would fain be at ease in the flesh,
insomuch that itself will rather persecute, than be disturbed in its fleshly liberty,
though it is very unwilling to bear the reproach of being accounted a persecutor?`"

He then comes to the root of the matter.

"`Consider,`" he says, "`whether ye did not flee from the cross,
in your transplanting into New England.
Safety,`" he tells them, "`is in standing in God`'s counsel; in bearing the cross;
in suffering for the testimony of his truth; but if at any time,
there be a fleeing of the cross (whether inward or outward) without God`'s direction,
the evil spirit is thereby let in, his part strengthened, and the life weakened.
. . . And, if ye fled your proper cross in your removal from hence into New England,
though ye meet with many others there,
yet hereby you lost your proper advantage of
serving and honouring God in your generation;
yea, ye lost that which would have kept your spirits tender,
and open to the voice of God`'s spirit; and then, no marvel if afterwards ye grew hard,
and fit to persecute, who first had shown yourselves unfit and unworthy to suffer.
Ye might meet with many crosses afterwards, which might neither be able to humble you,
nor keep you tender, having once lost that cross which was appointed of God to do it;
for all crosses do not break, humble, or keep the heart low and meek;
but such as are sent and sanctified by God thereunto.

"`Consider when ye came to New England, whether tenderness grew up in you,
and was abundantly exercised towards such as might differ from you;
or whether ye were as eager for the way that ye thought to be right,
as the Conformists you fled from were, for the way they thought to be right?
When Israel came out of Egypt into their own land,
they were to be tender even towards an Egyptian; much more toward their own brethren.
Now, when ye were out of danger of being persecuted yourselves,
did ye lay a foundation of tender usage towards all that should differ from you;
or did you lay a foundation of persecuting such as should differ;
and would suffer none differing from you, but persecuted them,
just as the bishops persecuted you?
Did ye flee the having yourselves persecuted; or did ye flee the persecuting spirit?
For if ye did flee only your own persecution,
and not the persecuting spirit in yourselves, no marvel though it fell a persecuting,
so soon as the fear of your own persecution was over.`"

"`Look over your writings,`" he says,
in drawing to the conclusion of his address to them, "`consider your cause again,
in a more meek and upright spirit; and ye yourselves will easily see, how in your heart,
ye have been mistaken, and dealt more injuriously with others,
than ye yourselves were ever dealt with.`"
