== Chapter IX.

I cannot omit to pause here awhile,
for the purpose of presenting the reader with a brief memorial
of the interesting writer of the foregoing transcripts.
Brief indeed it must necessarily be;
for little is to be known of the history of Isaac Penington,
beyond what is to be gathered from the testimonies given forth concerning him,
at his death, and such incidental notices of him,
as are to be found in the life of his friend, Thomas Ellwood.

According to the testimony of William Penn, who married his step-daughter,^
footnote:[Gulielma Maria Springett, daughter of Sir William Springett,
whose widow Isaac Penington married, in 1654.]
he was well descended as to his worldly parentage;
being the eldest son of Alderman Penington,
who was two years successively mayor of the city of London,
and a noted member of the long parliament.
Isaac, his son, was born about the year 1617, and received a liberal education,
"`having,`" according to Penn,
"`all the advantages the schools and universities of his own country could give,
joined with the conversation of some of the most
knowing and considerable men of that time.`"

"`From his childhood,`" says Ellwood, "`as I have occasionally heard him say,
he was religiously inclined;`" and, in a paper written by himself,
and found after his death amongst his writings,
we have such a living portrait of a deeply exercised mind,
as demonstrates that godliness, with him, was indeed the "`One Thing needful.`"

"`I have been a man of sorrow and affliction,`" says he, "`from my childhood,
feeling the want of the Lord, and mourning after him: separated by him, from the love,
nature, and spirit of this world, and turned in spirit towards him,
almost ever since I could remember!

"`In the sense of my lost estate, I sought after the Lord; I read the Scriptures;
I watched over mine own heart,
and whatever I read in the Scriptures as the way of God to my understanding,
I gave myself to the faithful practice of.

"`But my soul was not satisfied with what I met with, nor indeed could be;
there being further quickenings and pressings in my spirit, after a more full, certain,
and satisfactory knowledge; even after the sense, sight, and enjoyment of God,
as was testified in the Scriptures, to have been felt and enjoyed in the former times;
for I saw plainly, that there was a stop of the streams,
and a great falling short of the power, life, and glory,
which they +++[+++the scripture saints]
partook of.
We had not so, the spirit, nor were so, in the faith, nor did so walk and live in God,
as they did.
So that I saw the whole course of religion among us, was, for the most part, but a talk,
to what they felt, enjoyed, possessed, and lived in.
"`This sense made me sick at heart indeed; and set me upon deep crying to God,
close searching the Scriptures,`" etc.^
footnote:[This account is taken from Ellwood`'s Testimony, prefixed to Penington`'s Works;
in which testimony, Ellwood says of this paper, that "`it was written with his own hand,
above a dozen years ago, about (1668,) when, being in bonds for Christ`'s sake,
he was sick, near unto death.`"]

After dwelling awhile upon his exercises of mind in this respect,
and the total insufficiency of any thing he found amongst the different
sects and professions of that most sectarian and professing age;
"`At last,`" he says, "`after all my distresses and wanderings, etc.
I met with some writings of this people, called Quakers, which I cast a slight eye upon,
and disdained, as falling very short of that wisdom,
etc. which I had been longing and searching after.`"

After a long time, he was invited to meet one of them; and on this occasion,
was so powerfully impressed by the internal evidence of the Spirit in his own conscience,
that what he heard was given forth in the authority and power of God,
that he describes himself as inwardly exclaiming, "`This is he!
This is he!
There is no other!
This is he whom I have waited for, and sought after from my childhood;
who was always near me, and had often begotten life in my heart;
but I knew him not distinctly, nor how to receive him, nor dwell with him.`"

And it is remarkable how deep and abiding was the
memory of this sudden and piercing conviction.
Scarcely does he ever speak of his first union with friends, without adverting to it,
and that almost in the same words.^
footnote:[See his letter to the Independents at Canterbury, p. 241. Barclay`'s Edit,
of I. Penington`'s Letters.]
Yet, rejoiced as he was,
to hear the sound of the bridegroom`'s voice in the secret of his soul,
he also discovered, as those who enter upon the spiritual life commonly do discover,
that he had no longer to wrestle with flesh and blood, but, as the apostle expresses it,
with the principalities, and powers of darkness.

"`What I met with, in my spiritual exercises, after this,`" he says,
"`is not to be uttered; only in general, I may say this,
I met with the very strength of hell.
I also met with deep subtleties and devices to entangle me in that
wisdom which seemeth able to make wise in the things of God;
but which indeed is foolishness, and a snare to the soul,
bringing it back into captivity.

"`And what I met with outwardly, from my own dear father, from my kindred,
from my servants, from the people and powers of the world,
for no other cause but fearing my God, worshipping him, as he hath required of me,
etc. the Lord my God knoweth, before whom my heart and ways are.`"

"`Neither to him,`" (says Ellwood,
in his testimony to the memory of Isaac Penington,) "`was it given, only to believe,
but to suffer also for the sake of Christ.
His imprisonments were many, and some of them long,
which with great quietness and constancy of mind, he underwent.`"

Proceeding to specify them, he states, that his first imprisonment was in Aylesbury gaol,
in the years 1661 and 1662; being committed there for worshipping God in his own house;
where, for seventeen weeks, great part of it in winter, he was kept in a cold,
and very incommodious room without a chimney,
from which usage he contracted so severe an indisposition, that for several weeks after,
he was unable to turn himself in his bed.

He was five times imprisoned after this; and the last time in 1670,
for the space of a year and three quarters, in Reading gaol;
whither he went to visit his suffering friends.
George Fox narrowly escaped the same fate;
as we gather from the following passage in his Journal.

"`At Reading, most of the Friends were in prison, and I went to visit them, etc.
When the meeting was ended, the gaoler understanding I was there,
friends were concerned how to get me safe out again; for they feared he should stop me.`"
After he had stayed awhile, and had eat with them, he went down stairs;
and the gaoler being at the door, "`I gave him something,`" he says,
"`and bade him be kind and civil to my friends in prison, whom I came to visit,
and he let me pass out without interruption.
But soon after, Isaac Penington coming to visit them, he stopped him,
and caused him to be made a prisoner.^
footnote:[[.book-title]#G. Fox`'s Journal#, p. 419.]

One of the most unrelenting foes of this excellent man, was the Earl of Bridgewater,
who upon some account or another,
had the power of being his persecutor on the score of his religious principles, and who,
more than once, was the cause of his imprisonment.
It was during one of these occasions, that he addressed a letter to him,
from which a few extracts are here made.

[.embedded-content-document.letter]
--

[.letter-heading]
To The Earl of Bridgewater.

[.salutation]
"`Friend,

"`It is the desire of my heart to walk with God, in the true fear of his name,
and in true love and good will to all men, all my days here upon the earth.
For this end I wait upon God night and day, to know his will,
and to receive certain instruction from him concerning what is acceptable in his sight.
After he hath in any thing made manifest his pleasure,
I wait upon him for strength to perform it; and when he hath wrought it by me,
my soul blesseth him therefore.
If this be a right course, I am not to be condemned herein; if it be not,
and thou knowest a better, show me in love, meekness, and tenderness,
as I would be willing to make anything known to thee for thy good,
which the Lord hath shown me.`"

After some close reasoning with him,
on the account he would one day have to give of the deeds done in the body; "`yet,
I do not desire,`" he says, "`that thou shouldest suffer from God or man, on my account;
but that thou mightest be guided to, and preserved in that, which will be sweet rest,
peace, and safety, to all that are sheltered by it, in the troublous and stormy hour,
in which the Lord will distress man, and make him feel his sin and misery.
And, friend, know this assured truth;
it is not a religion of man`'s making or choosing (neither the pope`'s,
nor any other man`'s,) but only that which is of God, which is acceptable to Him.
And what will become of that man, whose very religion and worship is hateful to God?
Where will he stand, or what account will he be able to give, when he appears before him?
Thou hast not often met with such plain dealing as this.
These things very nearly concern thee.
Oh, wait upon God for his true light, that thou mayest not be deceived about them;
because thy loss thereby will be so great and irreparable.`"

--

But however painful to the nature of the "`outward man`" these sufferings might be,
the "`hidden man of the heart`" was thereby perfected, in no ordinary degree,
in the case of Isaac Penington.
Most of his inestimable letters, as well as the above,
were written within the walls of a prison; and of the preciousness of these testimonies,
many, then unborn, have tasted with profit and delight.

Yes, good and faithful servant! --well-instructed scribe!-- bringing forth out of thy treasures,
things new and old--thou hast fed many!
Be thy just memory blessed! and let a heart that owes thee much, thus,
in most true and tender love, record its gratitude.

Of his deportment in the tribulations that befel him,
there are many pleasing testimonies; but I select one only from the pen of Robert Jones,^
footnote:[Prefixed to the [.book-title]#Works of Penington#.]
his friend, and often, fellow-prisoner.

"`What shall I say?`"
exclaims this writer;
"`he was a man wholly devoted in his heart to serve the Lord his God; yea,
I am persuaded it was his delight to do his will.
I have had knowledge of him near twenty years, especially in suffering;
for it pleased the Lord so to order it, that our lot fell together in prison,
several times; and I may say, it was well it was so; for,
being made willing by the power of God, to suffer with great patience, cheerfulness,
contentedness, and true nobility of spirit, he was a good example to me, and others.
I do not remember that ever I saw him cast down, or dejected in his spirit,
in the time of his close confinement; nor speak hardly of those that persecuted him.
Indeed I may say, in the prison he was a help to the weak,
being made instrumental in the hand of the Lord to that end&hellip;
Oh, the remembrance of the glory that did often overshadow us in the place of confinement;
so that indeed, the prison was made, by the Lord unto us, as a pleasant palace.`"

But the Christian grace which of all others,
the most eminently characterized Isaac Penington, appears to have been that of humility;
which prompted him on all occasions, to esteem those very highly for their works`' sake,
whose faithfulness rendered them worthy of it.
The following letter from him to George Fox,
exemplifies this amiable disposition very pleasingly:--

[.embedded-content-document.letter]
--

[.salutation]
"`Dear G. F.

"`I feel the tender mercy of the Lord, and some portion of that brokenness, fear,
and humility, which I have long waited for, and breathed after.
I feel unity with, and strength from, the body: O! blessed be the Lord,
who hath fitted and restored me, and brought up my life from the grave.
I feel an high esteem and dear love to thee, whom the Lord hath chosen, anointed,
and honoured, and of thy brethren and fellow-labourers in the work of the Lord.

"`And, dear George Fox, I beg thy love, I entreat thy prayers,
in faith and assurance that the Lord hears thee, that I may be yet more broken,
that I may be yet more filled with the fear of the Lord,
that I may be yet poorer and humbler before the Lord,
and may walk in perfect humility and tenderness of spirit before him, all my days.

"`Dear George Fox, thou mayest feel my desires and wants more fully than my own heart.
Be helpful to me in tender love, that I may feel settlement and stability in the truth;
and perfect separation from, and dominion in the Lord, over all that is contrary thereto.

[.signed-section-signature]
"`I. P.

[.signed-section-context-close]
"`Aylesbury Gaol, 15th Fifth month, 1667.`"

[.postscript]
"`I entreat thy prayers for my family, that the name of the Lord may be exalted,
and his truth flourish therein.
Dear G. F., indeed my soul longs for the pure, full,
and undisturbed reign of the Life in me.`"

--

Being well fitted and prepared by sanctified suffering, he was ready for death; and,
as William Penn describes him, under that exigency, "`had nothing else to do but to die,
when that summons was served upon him, which was in the sixty-third year of his age:
at which time, it pleased the Lord, he fell sick, under a sharp and painful distemper,
which hastened his dissolution.`"

"`However,`" he adds, "`to internal peace so well established,
the anguish of that bitter exercise could give no shock; for he died as he lived,
in the faith that overcomes the world.`"

Of the domestic life and relations of Isaac Penington,
some brief notices are to be found in the history of Thomas Ellwood,
who lived many years under his roof, in the capacity of tutor to his children.

To this office, Ellwood was guided, not by profession,
but by the pressure of circumstances,
resulting from his father`'s indignation at his uniting himself with the despised Quakers.
Whilst this young man was a child, the elder Ellwood,
being much engaged on the side of the parliament during the civil wars,
had left his country residence in Oxfordshire,
for the purpose of being near his allies in London; and during this period,
an acquaintance was formed with Lady Springett, who afterwards married Isaac Penington.
At the end of the contest between the king and parliament,
Mr. Ellwood returned to his estate at Crowell, in Oxfordshire; and in the course of time,
hearing that his friends, the Peningtons,
were come to live upon their own estate at Chalfont in Buckinghamshire,
about fifteen miles from Crowell, he went to visit them, taking his son Thomas with him,
who was then about twenty years of age.

Great was the surprise of both father and son, on coming to this place, to hear,
and still more to see, that their friends had become Quakers.

"`So great a change,`" says Ellwood, "`from a free, debonair,
and courtly sort of behaviour, which we formerly had found them in,
to so strict a gravity as they now received us with, did not a little amuse us,
and disappoint our expectation of such a pleasant visit as we used to have,
and now promised ourselves.
Nor could my father have any opportunity, by a private conference with them,
to understand the ground or occasion of this change;
there being some other strangers with them, related to Isaac Penington,
who came that morning from London, to visit them also.`"

In this dilemma, young Ellwood bethought himself of the fair Gulielma,
Isaac`'s step-daughter, who had been his play-fellow in former times,
when his father lived in London and was on terms
of intimacy with Lady Springett her mother.
"`I became an early and particular playfellow,`" he says, alluding to this circumstance,
"`to her daughter Gulielma; being admitted, as such,
to ride with her in her little coach, drawn by her footman, about Lincoln`'s Inn-fields.`"

On the strength of this early alliance, he now sought her company;
and found her gathering flowers in the garden, attended by her maid,
who was also a Quaker.
"`But when I addressed myself to her,`" he says, "`after my accustomed manner,
with intention to engage her in some discourse which might tend to
introduce conversation on the foot of our former acquaintance,
though she treated me with a courteous mien, yet, as young as she was,
the gravity of her look and behaviour, struck such an awe upon me,
that I found myself not so much master of myself,
as to pursue any further converse with her; wherefore,
asking pardon for my boldness in having intruded myself upon her private walks,
I withdrew, not without some disorder, (as I thought, at least,) of mind.

"`We stayed dinner,`" he continues, "`which was very handsome,
and lacked nothing to recommend it to me, but the want of mirth and pleasant discourse;
which we could neither have with them, nor, by reason of them, with one another,
amongst ourselves; the weightiness that was upon their spirits and countenances,
keeping down the lightness that would have been up in us.
We stayed, notwithstanding, till the rest of the company took leave of them, and then we,
also, doing the same, returned, not greatly satisfied with our journey;
nor yet knowing what, in particular, to find fault with.`"

Some time after this,
the elder Ellwood having obtained some further account of the Quakers,
and being desirous to see a little more of them, made another visit to Isaac Penington,
taking his son and also his two daughters, with him.

"`It was in the tenth month, in the year 1659,`" says Ellwood, "`that we went thither,
where we found a very kind reception, and tarried some days; one day at least,
the longer, for that, while we were there,
a meeting was appointed at a place about a mile from thence, to which we were invited.

"`To this meeting came Edward Burrough, besides other preachers; as Thomas Curtis,
and James Naylor; but none spake there at that time, but Edward Burrough; next to whom,
and as it were, under him, it was my lot to sit,
on a stool by the side of a long table on which he sat; and I drank in his words,
with desire.`"

The meeting being ended, they returned to their friend`'s house;
and "`after supper,`" he says, "`the evenings being long, the servants of the family,
(who were Quakers,) were called in, and we all sat in silence.
But long we had not so sat, before Edward Burrough began to speak among us;
and although he spake not long, yet what he said, did touch, as I suppose,
my father`'s religious copyhold, as the phrase is; and he, having been from his youth,
a professor, though not joined in that which is called close communion with any one sort,
and valuing himself upon the knowledge he esteemed himself to have,
in the various notions of each profession,
thought he had now a fair opportunity to display his knowledge,
and therefore began to make objections to what had been delivered.

"`The subject of the discourse, was the universal free grace of God to all mankind;
to which he opposed the Calvinistic tenet of particular, and personal predestination;
in defence of which indefensible notion,
he found himself more at a loss than he expected.
Edward Burrough said not much to him upon it, though what he said was close and cogent.
But James Naylor interposing, handled the subject with so much perspicuity,
and clear demonstration, that his reasoning seemed to be irresistible;
and so I suppose my father found it, which made him willing to drop the discourse.

"`As for Edward Burrough, he was a bright young man, of a ready tongue,
and might have been, for aught I then knew, a scholar,
which made me the less admire his way of reasoning.
But what dropped from James Naylor, had the greater force upon me,
because he looked but like a plain simple countryman,
having the appearance of a husbandman or shepherd.`"

And here,
a striking remark of Isaac Penington`'s may be observed as corroborating this statement.
Speaking of the power which accompanied the preaching of some of the
plain and illiterate ministers amongst the primitive Friends,
"`Oh the breathings and meltings of soul,`" he says,
"`the sense of the living presence of God, the subjecting of the heart unto the Lord,
etc. which hath often been known, and sealed to, from the powerful appearance of God,
in their ministry!
Indeed, when I have considered these and such-like things in my heart,
and narrowly marked them in my converse with them,
I have been often forced to cry out concerning them, '`truly,
here is man very weak and contemptible; but God very glorious and powerful!`' And, indeed,
when at any time I looked on the man, I was hardly able to forbear disdaining them;
but on the other hand,
when the eye of my spirit beheld the power and glory of the Lord in them,
I could hardly forbear over-esteeming, and exalting them.`"^
footnote:[[.book-title]#Penington`'s Works,# vol. i. p. 632.]

But is not this the way of the Lord,--the invariable way?--we would ask.
Is it not his established purpose to "`stain the pride of
human glory,`" by choosing "`those whom man despiseth,`" to be
the instruments of his noblest purposes?
Man, vain man, seeing no further than the shell, craves to have that well ornamented;
and he gets his gold and his scarlet, his languages and his learning--and what then?
Are these the things wanted, to renew a fallen, degenerated soul?

It is easy indeed, to take the outside pattern of the high-priest`'s garments;
but where is the Urim and the Thummim;--the lights and perfections?-- where is the
breast-plate of judgment?--where is its engraving like that of a signet,
with "`Holiness unto the Lord?`"
"`Here was more,`" says Margaret Fell,
writing on this subject--"`here was more than the long gown and the surplice,
the tippet and the hood;--this is far beyond the long robes of our days,`" she continues;
"`for there is not holiness graven upon them;
neither lights nor perfections;--and if they do take the long robes and surplices,
and hoods and tippets from Aaron, they miss the garb and fashion of this.
And, upon the hem of Aaron`'s garment,`" she proceeds,
"`there were bells and pomegranates of gold.
A golden bell and a pomegranate--a golden bell and a pomegranate round about the hem;
and this was to be upon Aaron when he went to minister,
that his sound might be heard when he was to go into the holy place.
But they set bells upon the top of their steeples instead of these,
to make people hear the sound when they go to their worship.`"

As I do not propose to enter upon the circumstances of Ellwood`'s life,^
footnote:[I refer the reader who may desire the perusal of a very amusing book,
and one that gives much insight into the history of the primitive Friends,
to "`The Life of Thomas Ellwood, written by himself.`"]
any otherwise than as they are connected with Isaac Penington,
I pass over the many interesting incidents with which his history abounds;
but in doing this, I except one, which,
as it respects one of the most illustrious of our poets,
I think will be acceptable to the reader.

"`I mentioned before,`" he says, "`that when I was a boy,
I had made some good progress in learning,
and lost it all again before I came to be a man;
nor was I truly sensible of my loss therein, until I came amongst the Quakers;
but then I both saw my loss, and lamented it,
and applied myself with the utmost diligence, at all leisure times, to recover it;
so false I found that charge to be,
which in those times was cast as a reproach upon the Quakers,
that they despised and decried all human learning,
because they denied it to be essentially necessary to a gospel ministry,
which was one of the controversies of those times.

"`But though I toiled hard, and spared no pains to regain what once I had been master of,
yet I found it a matter of so great difficulty,
that I was ready to say as the noble eunuch to Philip, in another case, '`how can I,
unless I had some man to guide me?`'

"`This I had formerly complained of, to`" my especial friend Isaac Penington;
but now more earnestly:
which put him upon considering and contriving a means for my assistance.`'

"`He had an intimate acquaintance with Dr. Paget, a physician of note in London, and he,
with John Milton, a gentleman of great note and learning throughout the learned world,
for the accurate pieces he had written, on various subjects and occasions.

"`This person having filled a public station in the former times,
lived now a private and retired life in London: and having wholly lost his sight,
kept always a man to read to him;
which usually was the son of some gentleman of his acquaintance, whom in kindness,
he took to improve in his learning.

"`Thus, by the mediation of my good friend Isaac Penington with Dr. Paget,
and of Dr. Paget with John Milton, was I admitted to come to him,
not as a servant to him (which at that time he
needed not) nor to be in the house with him;
but only to have the liberty of coming to his house at certain hours when I would,
and to read to him what books he should appoint me; which was all the favour I desired.`"

Having arranged matters for his residence awhile in London,
Ellwood hastened to pay his respects to his accomplished tutor.

"`He received me courteously,`" he says,
"`as well for the sake of Dr. Paget who introduced me,
as of Isaac Penington who recommended me; to both of whom he bore a good respect;
and having inquired divers things of me with
respect to my former progression in learning,
he dismissed me to provide myself with such accommodations as
might be most suitable to my future studies.`"

"`I went therefore,
and took myself a lodging as near to his house (which
was then in Jewin Street) as conveniently I could;
and from thenceforward went every day in the afternoon,
except on the first days of the week, and, sitting by him in his dining-room,
read to him in such books in the Latin tongue, as he pleased to hear me read.

"`At my first sitting to read to him, observing that I used the English pronunciation,
he told me if I would have the benefit of the Latin
tongue not only to read and understand Latin authors,
but to converse with foreigners either abroad or at home,
I must learn the foreign pronunciation.
To this I consenting, he instructed me how to sound the vowels,`" etc.

The difficulty he found in obeying these instructions, was considerable; but,
"`labor omnia, vincit improbus;`" "`incessant pains, the end obtains,`" he observes;
"`and so did I; which made my reading more acceptable to my master.
He, on the other hand, perceiving with what earnest desire I pursued learning,
gave me not only all the encouragement, but all the help he could.
For, having a curious ear, he understood by my tone, when I understood what I read,
and when I did not; and accordingly, would stop me, and examine me,
and open the most difficult passages to me.

"`Thus I went on for about six weeks time, reading to him in the afternoon;
and exercising myself with my own books in my chamber in the forenoons,
I was sensible of an improvement.`"

But the air of London not agreeing with his health,
he was obliged very soon to relinquish this agreeable connection; he resumed it, however,
as soon as a retreat for a time into the country had restored him; but,
"`as if learning,`" he says, "`had been a forbidden fruit to me,
scarce was I well settled in my work, before I met with another diversion,
which turned me quite out.`"

This was the rising of a sudden storm,
from a surmise of some plot against the government,
which fell heavily upon the dissenters in general, and especially the Quakers;
many of whom (and Ellwood among the rest) were
taken at their respective meetings in the city,
and put into prison.

Being at length set at liberty,
Ellwood could not prevail upon himself to resume his studies with his master Milton,
until he had paid a visit of gratitude to his friends Isaac Penington and his wife;
from both of whom he had received tokens of kindness and affection in his imprisonment.
It was during this visit, that Isaac Penington,
being then in want of a tutor for his children,
suggested to Ellwood that he should remain with him in that capacity,
till he met with a person to suit him; a proposition which being complied with,
of course separated him from his engagement with Milton.

He did not, however, wholly lose sight of his quondam tutor; for,
being desired to take a house for him in the neighbourhood,
during the time that the plague raged in London, that, as Ellwood states,
"`he might go out of the city, for the safety of himself and his family,
the pestilence then growing hot in London;
I took a pretty box for him in Giles Chalfont,`" he says, "`a mile from me,
of which I gave him notice, etc.;
and soon making him a visit to welcome him into the country,
after some common discourse had passed between us, he called for a manuscript of his;
which, being brought, he delivered to me, bidding me take it home with me,
and read it at my leisure; and when I had so done, return it to him,
with my judgment thereupon.

"`When I came home, and had set myself to read it,
I found it was that excellent poem which he entitled '`Paradise Lost.`'
After I had, with the best attention, read it through, I made him another visit,
and returned him his book,
with due acknowledgment of the favour he had done me in communicating it to me.
He asked me how I liked it, and what I thought of it; which I modestly,
but freely told him; and after some further discourse about it, I pleasantly said to him,
'`Thou hast said much here of paradise lost; but what hast thou to say of paradise found?`'
He made me no answer, but sat some time in a muse; then broke off that discourse,
and fell upon another subject.`"

"`After the sickness was over, and the city well cleansed,
and become safely habitable again, he returned thither;
and when afterwards I went to wait on him there, which I seldom failed of doing,
whenever my occasions drew me to London, he showed me his second poem,
called '`Paradise Regained`' and, in a pleasant tone said to me, '`This is owing to you;
for you put it into my head, by the question you put to me at Chalfont,
which before I had not thought of.`'`"

I must not close this brief sketch of the domestic history of Isaac Penington,
without glancing also at that of his wife, a person of no ordinary excellence,
as it respects the qualities either of her head or heart.
She was the widow of Sir William Springett,
who died about two years after their marriage, leaving her pregnant with a daughter,
the Gulielma spoken of by Ellwood; and who, afterwards, became the wife of William Penn.

When Lady Springett first married Isaac Penington,
they were not in connection with the Society of Friends;
but were both in the same state of earnest desire and expectation,
of obtaining a better rest for their soul than
the current religion of the day afforded them.
Before her first marriage, even from her earliest youth, she describes her condition,
in a memoir written by herself, as one of intense anxiety respecting her eternal welfare;
but the circumstances of her rank and connections in life,
probably tended to keep this anxiety from much outward manifestation,
until her marriage with Isaac Penington.
Then, a similarity of feeling seems to have melted and prepared her heart,
equally with his, to receive the truth in the love of it,
and to unite willingly with him in joining the society
from whose ministrations it was imparted to them.

A most affecting and beautiful testimony to the memory of her husband,
is subjoined to those of the other friends, prefixed to his works;
and with some extracts from which, we will conclude the subject.

"`No likeness, or appearance, or taking sound of words,`" she says,
tenderly apostrophizing him, "`wouldst thou take up with,
instead of him that was life indeed!
O, the many years thou puttest thy mouth in the dust, and wentest softly,
and hadst anguish of soul, weeping and groaning!
Oh, who can tell the one half of the bitterness of thy soul.
Thou wouldst not feed on that which was not bread from heaven!
In this state I married thee, and my love was drawn to thee,
because I found thou sawest the deceit of all notions,
and was as one that refused to be comforted,
by anything that had the appearance of religion--till He came to his temple,
who is truth and no lie.
And in this my heart cleft to thee;
and a desire was in me to be serviceable to thee in this desolate condition;
for thou wast alone and miserable in this world,
and I gave up much to be a companion to thee, in this thy suffering.

"`Ah me, he is gone! he, that none exceeded in kindness, in tenderness,
in love inexpressible to my relation as a wife.
Next to the love of God in Christ Jesus to my soul,
was his love precious and delightful to me!--My bosom-one!--
that was as my guide and counsellor!--my pleasant companion;
my tender, sympathizing friend! as near to the sense of my pain, sorrow, grief,
and trouble, as was possible.
Yet this great help and benefit is gone; and I, a poor worm, a very little one to him,
and compassed about with many infirmities, through mercy, let him go,
without one unadvised word of discontent or inordinate grief!`"

After a few more words, she concludes by saying,
"`this testimony to dear Isaac Penington,
is from the greatest loser of all that had a share in his life,

[.signed-section-signature]
"`Mary Penington.`"
