== Chapter X.

Amongst the various probations wherewith different members of
the Society of Friends were exercised in this period,
few are more observable,
than those which relate to the trials of Catherine Evans and Sarah Cheevers.

In the year 1658, these two females,
believing themselves required to travel towards Alexandria, departed from England,
and landed at Leghorn; where, finding some of their countrymen and friends,
they remained several days, dispersing books, and speaking with many persons,
without receiving any molestation.
From this place they took their passage in a Dutch ship bound for Alexandria;
but the master of the vessel, being in company with another ship going to Malta,
determined upon going thither also, though he had no business in that place.

A remarkable presage of affliction seems to have impressed Catherine Evans,
at their being thus involuntarily carried to Malta; for before they came there,
she fell into great anguish of mind, during which she exclaimed,
"`Oh! we have a dreadful cup to drink at that place!`" and being come into the harbour,
and seeing the people standing on the walls,
as though anticipating they would be her enemies, she said within herself,
"`Shall ye destroy us?
If we give up to the Lord, then he is sufficient to deliver us out of your hands;
but if we disobey our God,
all these could not deliver us out of his hand!`" in which assurance of faith,
she and her companion felt a deliverance from the fear of man.

The next day they went on shore; and being met by the English consul,
he inquired their purpose in coming there:
to which they replied what seemed to them proper, and gave him some books.
He told them of the Inquisition; apparently wishing to apprize them of their danger;
and invited them, with proffers of service, to go to his house; which they did.

Here they were visited by several persons, to whom they spoke with seriousness;
and a good impression was made by their discourse, upon the minds of many.
They returned on board their ship at night;
but the next day they came again into the city, and going to the governor,
he told them that he had a sister in a nunnery, who desired to see them; upon which,
they went there, and talked with the nuns, and gave them some books.
One of the priests who brought them into the chapel,
desired them to bow to the high altar; which command it is scarcely necessary to say,
they refused; and their visit being over, they returned to the consul`'s house,
where they stayed some weeks.
During this period, they once went into one of the churches at the time of mass;
when Catherine, standing in the midst of the people, turned her back upon the high altar,
and kneeling down, lifted up her voice in prayer to God.

Extraordinary as this action was by such a person in such a place,
it would seem that it was not displeasing to the officiating priest;
since he put off his surplice,
and knelt down by her side till she had concluded her supplication.
He then beckoned with his hand to her and her companion to approach him;
offering her a piece of money, which she refused.

He would then have put it into Sarah`'s hand; but she declined it also;
at the same time showing him her purse,
in token that they were not in want of pecuniary aid.

He inquired if they were Calvinists, or Lutherans?
and on their replying in the negative, he asked, if they would go to Rome, to the pope?
which, declining, he queried if they were Catholics?
to which they said, they were true Christians, and servants of the living God!
But as they knew but little of the language,
they could only express themselves very defectively,
and that as much by signs as by words.

On a second visit to this, or some other church in the place,
they happened to arrive at a time when some
peculiarly idolatrous ceremonies were proceeding;
which occasioned them both, and especially Catherine,
so much visible distress and horror of mind for
the space of about three quarters of an hour,
that the whole congregation were struck with amazement,
and began to get out of their way with a movement of fear.

As their abode was at the English consul`'s,
(where they remained three months,) he fell under a suspicion of favouring them;
which induced him, contrary to the rites of hospitality,
and in defiance of his previous proffers of service, to connive at,
if he did not absolutely aid, the demand of the officers of the Inquisition,
that these helpless, harmless women should be delivered up into their hands.
Previous to this, he had forbidden them to go abroad;
and perceiving that something was working to their prejudice,
they told him their doubts respecting his good intentions towards them.

To this he made no other reply, than that,
"`If they were the servants and messengers of God, they should give him a sign thereof.`"

"`This,`" they told him, "`might serve for a sign; that it would be well with them;
but that it would not go off well with him.`"

In a short time the consul informed Catherine,
that the Inquisition having received letters from Rome,
had sent for her and her friend to be brought before them; but he hoped, he said,
that they might be liberated: a hope which he knew to be fallacious;
inasmuch as it appeared afterwards,
he was aware that a room was then prepared for them as prisoners of the Inquisition.

It would appear, though it is not so stated in the history,
that some examination into their principles, had before this time,
been made on the part of this tribunal; for on now being brought before it,
they were asked by the Lord Inquisitor, if they had changed their minds?

No, they replied; neither should they change from the truth.

He then asked what new light it was they talked of?

It was no new light, they replied;
but the same which the apostles and prophets bore witness to.

He inquired how this light came to be lost since their day?

It was not lost, they said; men had this light still within them,
but they did not know it,
by reason of the night of apostacy which had overspread the nations.

Being again required to say if they would recant what was called their errors,
and again signifying their determination to abide in the truth,
they were taken into an inner room in the Inquisition,
which had only two little holes in it for the admission of light and air;
in consequence of which confinement,
the weather and the climate being exceedingly sultry and oppressive,
they were almost suffocated.

Although nothing of an evil nature appealed in their answers, either at the foregoing,
or at any subsequent examination,
(of which they had several,) yet they were kept in close imprisonment;
a circumstance which occasioned great remorse of conscience to the English consul;
who came to them, and with tears in his eyes, expressed regret for their condition;
"`for it seems,`" says Sewel, "`that he had received something for delivering them up,
which he would willingly have given back, if thereby,
he could have obtained their liberty.`"
But this not being practicable,
he had to eat the bitter fruits of repentance for his treachery; in doing which,
he amply justified the prophetic words of Catherine, for it went so ill with him, that,
as the forementioned historian relates, he tasted of peace no more in this life.

But not thus was it with his victims.
Sad and oppressive as was their outward condition,
they tasted within of those sweet refreshments,
which oftentimes converted their gloomy prison into the very courts of heaven.

"`As dying and behold we live!`"--such indeed
was the befitting motto of these and many more,
who, in these dark and troublous times,
lifted up the holy banner which God had put into their hands,
with a command to "`display it, because of the truth.`"

The interruption to quiet which they had to endure from the frequent
visits and troublesome discourse of a friar named Malachi,
who was constantly urging their reception of popery, was in itself a perpetual vexation;
but, added to this trial, their sufferings from the heat were such,
as nothing but Divine aid could have rendered supportable.
They were also so exceedingly stung with mosquitoes,
that their faces were perfectly swollen; which caused the angry friar to tell poor Sarah,
that he could spy an evil spirit in her face.

After a short interval, Catherine fell ill;
upon which a physician was brought to visit her;
but not feeling easy to take any of their remedies, she declined his assistance.
It would have been but of little avail, in her circumstances, to seek for medical aid,
whilst the apparent cause of her malady (which was the
heat and confinement of her apartment) was not removed.

She inquired, indeed, on seeing the physician,
why they should be confined in a room calculated to destroy them,
and then a physician brought to keep them the longer alive?

To which the friar made answer, that the inquisitor would lose his head,
if he removed them thence; and that it was better to keep them there, than to kill them.

Some idea of the sufferings of these poor creatures may be formed,
from the circumstance of their often lying down before the crevice of their door,
to inhale what air could be obtained from it.
In this state, their skin was parched, the hair fell off their heads,
and they frequently fainted;
and in moments when the strength and glory of the Divine
presence was not so feelingly experienced as at others,
it cannot occasion surprise, that through human weakness they wished for death;
their distress sometimes being such, that when it was day they longed for night,
and yet when night came, it was only to prompt the constant sigh for returning light.

There was but one drop of bitterness needed, to augment this cup of trembling,
which for wise and necessary purposes, the Most High commanded them to drink.
It was their separation from each other!
Whilst they could converse, and weep, and suffer,
and supplicate together--they were yet possessed of a rich mine of happiness.
Too rich it would seem!
Their hearts were not yet bankrupt enough in worldly love and joy,
to sink wholly and unreservedly into the bosom of their beloved.
And so the blessed bridegroom of the soul, in beautiful jealousy,
interposed to make them absolutely his own,
by compelling them to take their all of satisfaction from himself.
"`That they may be one, Father, as we are one--that they all may be made perfect in one.`"

This measure of separating them,
was not carried into immediate execution when first proposed;
which was in consequence of Catherine`'s illness;
the inquisitor causing them at that time to be told, that he would have them separated,
for the purpose of Catherine`'s being taken into a cooler apartment;
but that Sarah should remain there.
Upon hearing this,
Catherine declared that she would rather die than be separated from her friend.
"`The Lord hath joined us together,`" said she, taking the arm of her dear companion,
"`and woe be to them that part us!`"

This tender stroke appears to have softened the hard heart
even of the friar who brought them this intelligence;
for he went away without further urging the matter,
and they saw him no more for five weeks.

At the end of that time,
some monks came to them with a renewal of the order for their separation;
but Catherine being then much worse in health, they again brought the doctor to her,
who said she must have air, or she would die; in consequence of which statement,
their prison doors were set open for six hours every day.

At last the painful sentence which had so long been threatened, was actually executed;
and though both of them declared, and doubtless, with truth,
that death itself would not have been so grievous to them as separation,
they found no pity from the merciless monks with whom they were dealing.
The reason assigned for this cruel measure, was,
that they only hardened each other in refusing to recant their errors;
and therefore when separated, they would perhaps cease to be contumacious.
But so far from their being intimidated by this accession of sorrow,
they acquired fresh courage therefrom;
a result which the spiritual mind would anticipate as probable;
since such an one can conceive, when put into the furnace of affliction,
how safely the soul may cast itself into the keeping of the Great Refiner,
assured that he himself will sit by, to watch his gold; (Mal. 3:3) permitting,
in the painful process,
no higher degree of suffering than that which is absolutely needful,
to purify the vessel, and make it meet for the Master`'s use.

A remarkable dream of Catherine`'s during their imprisonment,
is strikingly illustrative of this truth.

She found herself (in her dream) in a large room,
in the chimney of which was a great fire made of wood.
In a chair by the side of this fire, a person was sitting,
whom she took to be the Son of God; and over the fire,
so that it appeared impossible but it must be consumed,
she perceived a very lovely child, which she would fain have taken up,
to save it from being destroyed; but he that sat in the chair,
commanded her to let it alone.
Although the fire was flaming about it, the child played and seemed merry.
On turning round, she perceived an angel;
and at the same time she was desired by the person sitting in the chair,
to take the child up; which she did, and found that it had received no harm.

"`He knoweth the way that I take,`" said the holy patriarch;
(Job 23:10) "`when he hath tried me, I shall come forth as gold.`"

In the course of their imprisonment, "`it happened,`" says Sewel,
"`that the inquisition-house was new built, or repaired;
which took up about the space of a year and a half; and during this time,
some of the great ones came often to see the building,
which gave opportunity to these women to speak to them,
and to declare the truth in the name of the Lord.`"

He also states,
that although they were threatened by the monks
for preaching the light of Christ so boldly,
yet not only the magistrates, but the Lord Inquisitor grew moderate towards them,
and gave orders that they should have pens, ink, and paper, to write to England.
And they also seemed inclined to have set them at liberty;
but the friars counteracted all such measures,
seeming bent upon annoying them to the utmost of their ability.
A variety of somewhat disjointed conversations between them and their usual visitor,
Malachi, is preserved in the history of this transaction,
which is contained in a small volume chiefly collected
from letters and papers written by them in prison,
and published in England, not long after their return in 1662.

But these discourses being desultory,
and evidently written down soon after their occurrence, rather by way of diary,
or for private interest, than public edification, I do not insert them.

I am induced, however, to subjoin a specimen of the heavenly content, which,
upon the whole, was their portion in this dark and cloudy day,
by offering to the reader a few stanzas of Catherine`'s humble, but very sweet poetry,
looking at it in spirit.

[verse]
____
HYMN TO GOD.^
footnote:[Only a selection is given from this poem.]

All praise to him that hath not put,
Nor cast me out of mind;
Nor yet his mercy from me shut,
As I could ever find.

Oh none is like unto the Lamb,
Whose beauty shineth bright!
O! glorify his holy name,
His majesty and might.

My soul, praise thou the only God,
A fountain pure and clear;
Whose crystal streams spread all abroad,
And cleanseth far and near.

My sweet, and dear beloved one,
Whose voice is more to me
Than all the glory of the earth,
Or treasures I can see.

My soul, praise thou the Lord I say,
Praise him with joy and peace;
My spirit and mind, both night and day,
Praise him and never cease.

Oh, praises, praises, to our God!
Sing praises to our King;
O teach the people, all abroad,
His praises for to sing.

A Sion song of glory bright,
That doth shine out so clear;
O manifest it in the sight
Of nations far and near.

That God may have his glory due,
His honour and his fame;
And all his saints may sing anew
The praises of his name.
____

It is worthy of observation, and certainly tending to spiritual progress,
to consider how much the soul thrives in the exercise of praise.
How continually do we find "`the high praises of God,`" in the
mouth of the scripture saints!--and how almost invariably,
as it advances nearer to the Fountain of blessedness, and the sweet Source of its being,
does the spirit of the creature, when in its right state,
pour forth enraptured songs of thanksgiving, to its all glorious, and all lovely Creator!

Hence, how many at, or very near the moment of their departure from the body,
break forth into singing; "`the joy of the Lord being their strength.`"

I cannot refrain from adding another extract or
two from the papers of these exalted captives,
for which, I think I shall receive the thanks of at least some of my readers.
The following passages are selected from a letter of Catherine to her husband,
and which she superscribes,

"`For the hands of John Evans, my right, dear, and precious husband,
with my tender-hearted children;
who are more dear and precious to me than the apple of my eye.`"

She then addresses him as her "`Most dear and faithful husband, friend,
and brother,`"--telling him that she has unity and fellowship with him day and night.

"`Oh my dear husband and children,`" she says,
"`how often have I poured out my soul to the everlasting Father for you,
with rivers of tears night and day,
that you might be kept pure and single in the sight of our God. . .

"`My dear hearts, you do not want teaching; you are in a land of blessedness,
which floweth with milk and honey! among the faithful
stewards whose mouths are opened wide to righteousness,
to declare the eternal mysteries of the everlasting
kingdom of endless joys and eternal glory,
whereinto all the willing and obedient shall enter, and be blessed forever.

"`My dear hearts, the promises of the Lord are large,
and all yea and amen to those that fear his name.
He will comfort the mourners in Zion,
and will cause the heavy-hearted in Jerusalem to rejoice, because of the glad tidings.
They that do bear the cross with patience, shall wear the crown with joy;
for it is through long suffering, and patient waiting,
that the crown of life and immortality comes to be obtained.
The Lord hath exercised my patience, and tried me to the uttermost; to his praise,
and my eternal comfort, who hath not been wanting to us in anything, in his own due time.
We are witnesses that he can provide a table in the wilderness,
both spiritual and temporal. . .

"`In our deepest affliction, when I looked for every breath to be the last,
I could not wish I had not come over the sea;
because I knew it was my eternal Father`'s will to prove me,
with my dear and faithful friend.
In all afflictions and miseries, the Lord remembered mercy, and did not leave us,
nor forsake us, nor suffer his faithfulness to fail;
but caused the sweet drops of his mercy to distil upon us,
and the brightness of his glorious countenance to shine into our hearts.`"

She concludes this tender effusion by committing her beloved
husband and children to the hands of the Almighty,
and to the word of his grace--adding, as her last words,
"`I do believe we shall see your faces again with joy.

"`This was written in the Inquisition at Malta, in the 11th month, in the year 1661.`"

The address of Sarah to her husband and children, is less touching,
but not less "`strong in the faith, giving glory to God.`"

She begins by assuring them of her soul`'s rest
and peace in the bosom of her Lord and Saviour.
"`Therefore,`" she says, "`doth my soul breathe to my God for thee and my children,
night and day, that your minds may be joined to the light of the Lord Jesus,
to lead you out of Satan`'s kingdom into the kingdom of God,
where we may enjoy one another in the life eternal,
where neither sea nor land can separate.`"
And in that light she tells him, that she salutes him and her dear children;
entreating them to turn to the everlasting Fountain,
which had been opened to them by the messengers of Christ;
"`who preach to you,`" she says, "`the word of God,
'`in season and out of season,`' directing you where you may find your Saviour.`"

She tells them that she cannot by pen and paper,
set forth the extent of the love of God to her soul,
in fulfilling his gracious promises to her in the wilderness.

It appears indeed, in the history of these prisoners,
that they were permitted to sing the Lord`'s song in a
strange land--and that in the midst of heaviness,
"`their mouths were often filled with laughter, and their tongues with joy.`"

At length, after a captivity of four years,
it pleased God to order matters for their deliverance;
which was effected through the instrumentality of Lord D`'Aubigny,
a Roman Catholic priest, then in England in the service of the queen-mother;
and whose interposition in the affair was sought by Gilbert Latey,
a valued minister in the society.

An account of the transaction is preserved in Latey`'s life; and which,
as it comprizes some allusions to other subjects of an interesting land,
I transcribe as follows:--

"`In the year 1660, and upon the coming in of King Charles II.,
the queen-mother resided at Somerset House;
and it having pleased the Lord to lay a necessity on two of his servants and handmaids,
to visit divers parts beyond the seas, warning the people to turn to the Lord,
after having passed through several parts, they arrived at the Island of Malta; where,
for bearing testimony to the power of God, etc., they were taken up and confined;
the tidings of which, some time after, came to London;
and Gilbert being often in the service of soliciting
ease for the suffering servants of the Lord,
made it his business to find out some here who had an interest in those parts.
And after some time and pains spent in this affair,
he soon got information that one Lord D`'Aubigny, who came over with the queen-mother,
and was lord-almoner to her, had both interest, power, and command,
in the island of Malta.

Having obtained access to this individual, the history relates,
that Gilbert "`found him to be a well-tempered man;
and notwithstanding the way of the Lord was evilly spoken of,
and his people were looked upon by many, as speckled birds,
and went as with their lives in their hands;
the power of God so wrought on this Lord D`'Aubigny,
(although he was a priest in orders,) that he was very kind and free to Gilbert;
and reasoned with him like Felix with Paul, about the principles of truth,
and way of the Lord.
And being informed concerning the power of God, and the manner of the Spirit`'s working,
answered, that some of their people thought our friends were mad; '`but,`' said he,
'`I do not think so of them.`'

"`And upon further discourse with him at another time, he confessed further, and said,
'`Let me talk with you ever so long, and you will tell me of the Spirit of God,
and the grace of God, and the works and operations thereof, etc.,
which I believe may in a measure be true.
But do you not think it is well to have something to represent that,
which you so much love?`'

"`To which Gilbert answered, that the substance of all things was come;
viz. '`Christ in us the hope of glory;`' and all the outward types,
representations and shadows, must come to an end,
and be swallowed up in our blessed Lord; who told his disciples,
it was expedient for them he should go away; '`for,`' said he, '`if I go not away,
the Comforter will not come; but if I depart, I will send him;
even the Spirit of truth which shall guide you into all truth.`'
And he also said, that '`he who was with them should be in them.`'
So that this being witnessed,
there needed nothing outwardly to represent or put them in mind;
for he being so near men and women, was +++[+++himself]
the saint`'s daily remembrancer.

"`Upon this they parted; but Gilbert often visited him,
to desire and remember him to show kindness to the
suffering friends that were under confinement,
both in a strange place, and at so great a distance from their friends,
and their native country.

"`Coming another time to wait on him, he bid Gilbert follow him; which doing,
he went into the queen`'s chapel, where Gilbert seeing the people on their knees,
and the candles lighted on the altar, made a halt,
and asked the Lord D`'Aubigny what he meant by bidding him come in there?

"`'`Thou knowest,`' said he, '`that I can bow to nothing.`'

"`To this the Lord D`'Aubigny answered, '`Follow me, and nobody shall hurt you,
nor meddle with you.`'
Upon which, Gilbert followed him through the chapel, to a room behind the altar,
where was another of the queen`'s priests; and there being some lesser altars,
the Lord D`'Aubigny said to Gilbert, '`You never yet saw me in my priestly habit,
but now you shall.`'
And whilst he was making ready, the power of the Lord worked so much on Gilbert,
that he stepped up on a place they called a private altar,
and the word of the Lord came to him to preach truth unto them; when,
among other expressions, he said, '`We have an altar of which you have no right to eat.`'
Whereupon the queen`'s priest asked, '`What altar is this you speak of?`'

"`'`The altar I speak of,`' said Gilbert,
'`is that on which the saints daily offer up their prayers to the living God.`'

"`Then the priest replied, '`Friend,
there is no greater state attainable than what you speak of.`'

"`But Gilbert ceased not to visit the Lord D`'Aubigny,
still renewing his request for kindness to be shown to his suffering friends.
And some time after, going again to wait upon him,
to see if he had any answer to the letters which
he had promised to write on the friends`' behalf,
he acquainted Gilbert, that his friends were at liberty, and free,
and clear from all confinement; which was joyful news to him.`"

In due time they arrived in England, and went to visit their friend Gilbert;
and after acknowledging his love and endeavours for their liberty,
they desired him to bring them to the sight of the Lord D`'Aubigny,
whom it had pleased God to make the instrument of their enlargement.

"`Gilbert,`" we are told, "`was very willing to accompany them;
and according to their desire, went with them to wait on the Lord D`'Aubigny; who,
when they came,
understanding that Gilbert was desirous to have the liberty of seeing him,
came down to them;
on which Gilbert told him that the friends who
had been made partakers of his great kindness,
and released of their bonds in Malta,
were come to pay their acknowledgments to him for the same.
Whereupon he asked if they were the women.
To which they replied they were; and according as the Lord put it into their hearts,
they spake to him; adding that were it in their power,
they should be as ready in all love to serve him.
To which he replied, '`Good women, for what service or kindness I have done you,
all that I desire of you is, that when you pray to God,
you will remember me in your prayers.`'

"`And so they parted.`"
