== Chapter XIII.

After a short imprisonment at Leicester, and, on his release,
travelling awhile in the work of the ministry,
George Fox found himself once more at Swarthmore,
at the house of his friend Margaret Fell;^
footnote:[Then a widow; Judge Fell dying in 1658.]
where he had not been long, when,
at a meeting of justices held at Houlker-hall in that neighbourhood,
a warrant was granted for his apprehension.

"`I heard over night,`" he says, "`both of their meeting and of the warrant,
and could have got out of their reach, if I would.
But I considered, there being a noise of a plot in the north, if I should go away,
they might fall upon friends; but if I gave myself up to be taken, it might prevent them,
and friends should escape the better.`"

On the following day, an officer was sent to apprehend him;
and George willingly surrendering himself, was taken to Houlker-hall,
to be examined before the magistrates, Margaret Fell accompanying him.

"`When we came thither,`" he says, "`there was one Rawlinson, a justice,
and one called Sir George Middleton, and many more that I did not know,
besides old Justice Preston that lived there.

A difficulty existing, how to frame a sufficient charge for committing him to prison,
some expressions were attributed to him as having been used to one Thomas Atkinson,
which signified "`that he had written against the plotters, and had knocked them down.`"

"`These words,`" said he,
"`they could not make much of;`" but allusion being made to a
work upon language written by some of the friends,
a sneering inquiry was put by old Justice Preston to Fox,
"`whether he had any hand in it; and whether he understood languages?`"

"`Sufficient for myself,`" he replied.
"`I told them,`" he proceeds, "`that to understand those outward languages,
was no matter of salvation; for the many tongues began but at the confusion of Babel;
and if I did understand any thing of them, I judged and knocked them down again,
for any matter of salvation that was in them.

"`Thereupon he turned away, and said,`' George Fox knocks down all the languages:
come,`' said he, '`we will examine you of higher matters.`'

"`'`Then,`' said George Middleton, '`you deny God, and the church, and the faith.`'

"`I replied, '`Nay, I own God, and the true church, and the true faith.`'

"`'`But what church dost thou own?`'
said I; for I understood he was a Papist.
Then he turned again and said, '`You are a rebel, and a traitor.`'
I asked him whom he spoke to, or whom did he call a rebel?`"

This plain question being answered by a declaration that "`he spoke
it to him`" a noble disdain filled the spirit of this honest man,
who so often had proved the integrity of his heart,
by sufferings which most of these pampered worldlings would have fled from with dismay.

"`With that,`" says George, "`I struck my hand on the table,
and told him I had suffered more than twenty such as he, or than any that were there:
for I had been cast into Derby prison for six months together: and had suffered much,
because I would not take up arms against the king, before Worcester fight.
I had been sent up prisoner out of my own country, by Colonel Hacker, to Oliver Cromwell,
as a plotter to bring in King Charles, in the year 1654;
and I had nothing but love and good will to the king,
and desired the eternal good and welfare of him, and all his subjects.

"`'`Did you ever hear the like?`'
said Middleton.

"`'`Nay,`' said I, '`ye may hear it again, if ye will.
For ye talk of the king!--a company of ye!
But where were ye in Oliver`'s days?
and what did ye do for him then?
I have more love to the king for his eternal good and welfare, than any of you have.`'`"

Some conversation then ensued respecting the plot in the north;
which he told them he had heard of, and had written against;
and nothing being made of this, the usual snare was laid by Middleton`'s calling out,
"`Bring the book, and put the oaths of allegiance and supremacy to him.`"
"`He being a Papist,`" says George,
"`I asked him whether he had taken the oaths of supremacy, and was a swearer.
As for us, we could not swear at all; because Christ and his apostle had forbidden it.`"

In consequence of his refusing the oath,
he was about to have been committed to Lancaster jail, but upon further consideration,
he was dismissed, upon his promise to appear at the sessions.

"`The sessions coming on,`" he says, "`I went to Lancaster,
and appeared according to my engagement.
There was upon the bench, Justice Fleming, who had bid five pounds in Westmoreland,
to any man that would apprehend me.-- There were also Justice Spencer, Colonel West,
and old Justice Rawlinson, the lawyer, who gave the charge,
and was very sharp against truth and friends.
The session was large, the concourse of people great; and way being made for me,
I came up to the bar, and stood with my hat on, they looking earnestly upon me,
and I upon them, for a pretty space.
Proclamation being made for all to keep silence, upon pain of imprisonment,
and all being quiet, I said twice, '`Peace be among you!`'

"`The chairman asked if I knew where I was?
"`'`Yes I do,`' said I: '`but may be, my hat offends you.
That is a low thing: that is not the honour I give to magistrates;
for the true honour is from above.`'`"

He then remarked,
that he hoped it was not the hat which they looked upon to be the honour.

The chairman said, they looked for the hat too;
and asked wherein he showed his respect to magistrates, if he did not put off his hat.

He replied, "`in coming when they called him.`"

They then bid some one take off his hat.

He was then questioned, as before, respecting his knowledge of the plot in the north;
and as before, had also the oath of allegiance tendered him; which declining to take,
he was committed to prison.

This was again a time of severe persecution to the society;
who generally bore the brunt of the renewed scrutiny and punishment, that,
on the part of government, accompanied every fresh plot.

Amongst those who were at this time in prison, Margaret Fell was one;
of whose examination at Lancaster assizes, there is an account preserved,^
footnote:[In a [.book-title]#"`Brief Collection of Remarkable Passages, etc relating to Margaret Fell,`"# p. 276.]
which, taken in conjunction with that of George Fox,
respecting his trial at the same place, and time, and on the same occasion,
affords a curious specimen of the calm, and somewhat amusing inflexibility,
with which the poor oppressed friends,
in their turn perplexed and troubled their persecutors.

Being called to the bar,
(where she appeared with four of her daughters
by her side,) order was given by the judge,
that she should be accommodated with a seat; and at the same time he called out,
"`Let not Mrs.
Fell`'s daughters stand at the bar;
but let them come up hither:--they shall not stand at the bar.`"

Her mittimus being read, which assigned as the reason of her committal,
her refusing to take the oath of allegiance, she replied,
"`I was sent for from my own house and family;
but for what cause or transgression I do not know.`"
To which the judge made answer, "`I am informed by the justices of peace in this county,
that you keep multitudes of people at your house, in pretence to worship God;
and it may be, you do worship him in part; but we are not to dispute that.`"
He then told her, that if she would give security to have no more meetings,
he would not tender her the oath again.

Upon this, she desired liberty to answer to the two charges brought against her:
viz. refusing the oath, and keeping meetings at her house.
"`And first,`" said she, "`for that which is looked upon to be matter of fact, which is,
concerning our meetings.
There are several of my neighbours which are of the same faith, principle, and spirit,
and judgment that I am of; and these are they that meet at my house,
and I cannot shut my doors against them.`"

"`You begin at the wrong end, mistress;`" said the judge;
"`for the first charge is the oath.`"

"`As for that,`" said Margaret, "`if I have begun at the wrong end,
I shall begin at the other.`"
She then replied to the charge respecting the oath,
by declaring her true allegiance to the king;
but "`Christ Jesus the King of kings,`" she says, "`has commanded me not to swear at all,
neither by heaven, nor by earth, nor by any other oath.`"
The judge then called for the statute-book,
and one of the justices who committed her said, "`You know, Mrs.
Fell, that before the oath was tendered you, we offered,
if you would put in security to have no more meetings at your house,
we would not tender you the oath.`"

She said she did not deny that; and the judge making the same proposal,
she appealed to the whole assembly,
whether the meetings held at her house were hurtful or prejudicial to any one;
and beginning to speak of obedience to Christ`'s commands, the judge interrupted her,
by saying,

"`You are not here for obedience to Christ`'s commands,
but for keeping of unlawful meetings: you think that if you do not fight, and quarrel,
or break the peace, that you break no law:
but there is a law against unlawful meetings.`"

M+++.+++ F. "`What law have I broken for worshipping God in my own house?`"

Judge.
"`The common law.`"

M+++.+++ F. "`I thought you had proceeded by a statute.`"
Here the judge probably floundering a little,
one of the sheriffs whispered him of a statute, 35th Elizabeth!`"

The latter part of the statute being read, the judge informed her, and also the jury,
what would be the penalty of her refusing the oath; to which statement she replied,
that if it were the king`'s pleasure to take her estate from her,
upon the account of her adhering to the dictates of her conscience,
he must do as he would.
She then desired to speak to the jury.

Judge.
"`The jury is to hear nothing but me tender you the oath; and you refuse, or take it.`"

M+++.+++ F. "`You will let me have the liberty that other prisoners have;`" which having said,
she turned to the jury, and once more related the cause of her imprisonment,
and her reasons for not swearing.
"`I am here,`" she said, "`this day, upon the account of my conscience,
and not for any evil or wrong done to any man.`"
She then proceeded to consider the statute, which was made for popish recusants.
"`Now let your consciences judge,`" said she "`whether we be the people it was made for,
who cannot swear any oath at all, for conscience sake.`"

Here the judge in anger declared,
that she was not there upon the account of her conscience;
observing that she had "`an everlasting tongue;--
you draw the whole court after you,`" said he.
But Margaret pursuing her point, still continued speaking,
regardless of his repeated queries, "`Will you take the oath or no?`"
till, in much wrath, he commanded that the book should again be tendered her.

Judge.
"`Will you take the oath of allegiance, yea, or nay?`"

M+++.+++ F. "`I have said already, I own allegiance and obedience to the king,
and his just and lawful commands;
and I do also own allegiance and obedience unto Christ Jesus, who is the King of kings,
who hath commanded me not to swear at all.`"

Judge.
"`That is no answer.
Will you take the oath, or not take it?`"
A question which only brought the same reply, that she owed allegiance to Christ,
who forbade her swearing.

At length one of the justices observed, "`Mrs.
Fell, you may with a good conscience put in security to have no more meetings at your house,
if you cannot take the oath.`"

"`Wilt thou make it good,`" said she, "`that I may, with a safe conscience,
make an engagement to forbear meetings, for fear of losing my liberty and estate?
Wilt not thou and all here, judge of me, that it was for saving my estate and liberty,
that I did it?
And should I not in this, deny my testimony; and would not this defile my conscience?`"

Finding it impossible to move her constancy, she was ordered from the bar,
and George Fox was called to take his trial: which,
in point of confusion and perplexity to judge and jury, is scarcely to be surpassed.

When two days or thereabouts,
had been fruitlessly occupied in tendering him the oath of allegiance,
"`we were called again,`" he says, "`to hear the sentence;
and Margaret Fell being called first to the bar, she had counsel to plead,
who found many errors in her indictment; whereupon,
after the judge had acknowledged them, she was set by.
Then the judge asked what they could say to mine?

"`I was not willing to let any man plead for me, but to speak to it myself; and indeed,
though Margaret had some that pleaded for her,
yet she spoke as much herself as she would;`" a
fact of which the reader has received some proof.

"`I, having put by others from pleading for me,`" he says,
"`the judge asked me what I had to say, why he should not pass sentence upon me.

"`I told him I was no lawyer; but I had much to say,
if he would but have patience to hear.
At that he laughed, and others laughed also, and said, '`Come, what have you to say?
he can say nothing.`'

"`'`Yes,`' said I; '`I have much to say; have but the patience to hear me.`'

"`I asked him whether the oath was to be tendered to the king`'s subjects,
or to the subjects of foreign princes?

"`He said, '`to the subjects of this realm.`'

"`'`Then,`' said I, '`look into the indictment;
ye may see that ye have left out the word subject, so,
not having named me in the indictment as a subject,
ye cannot premunire me for not taking an oath.`'

The error being discovered, was confessed as such by the judge.

"`But I told him I had something else,`" says George, "`to stop his judgment;
and desired him to look what day the indictment said
the oath was tendered to me at the sessions there.

"`They looked, and said it was the eleventh day of January.`"

"`'`What day of the week was the sessions held on?`'
said I.

"`'`On a Tuesday,`' said they.

"`'`Then,`' said I, '`look at your almanacks,
and see whether there was any sessions held at Lancaster on the eleventh day of January,
so called.`'

"`So they looked and found that the eleventh day was the day called Monday;
and that the sessions was on the day called Tuesday;
which was the twelfth day of that month.

"`'`Look now,`' said I,
'`ye have indicted me for refusing the oath in the quarter-sessions held at Lancaster,
on the eleventh day of January last,
and the justices have sworn that they tendered
me the oath in open sessions here that day,
and the jury, upon their oaths, have found me guilty thereupon; and yet ye see,
there was no session held at Lancaster that day.`'

A great ferment among the justices, succeeded this stroke;
some of them stamping on the ground,
and declaring that the mistake must have been made on purpose.

"`But this is not all;`" continues George; "`I have more yet to offer,
why sentence should not be given against me.`"

He then asked, "`in what year of the king, was the last assize here holden,
which was in the month called March last?`"

"`In the sixteenth year of the king;`" said the judge.

"`But,`" said George, "`the indictment says, it was in the fifteenth year.`"

This error was also discovered, and compelled to be acknowledged.

"`Then they were all in a fret again,`" says he, "`and could not tell what to say:
for the judge had sworn the officers of the court,
that the oath was tendered me at the assize mentioned in the indictment.`"

But another lash of George`'s whip yet remained to be inflicted.

"`I told the judge,`" he says, "`I had yet more to offer, to stop the sentence;
and I asked, whether all the oath ought to be put into the indictment, or no.

"`'`Yes,`' said he, '`it ought to be all put in.`'

"`'`Then,`' said I, '`compare the indictment with the oath,
and there thou mayest see these words, viz.,
+++[+++or by any authority derived or pretended to be derived, from him or his see,]
left out of the indictment, which is a principal part of the oath.
And in another place, the words heirs and successors, are left out.`'`"

The judge acknowledged these, also, to be great errors.

"`'`But,`' said I, '`I have something further to allege.`'

"`'`Nay,`' said the judge, '`I have enough; you need say no more.`'

"`'`If,`' said I, '`thou hast enough, I desire nothing but law and justice at thy hands;
for I do not look for mercy.`'

"`'`You must have justice,`' said he, '`and you shall have law.`'

"`Then I asked, '`am I at liberty,
and free from all that ever hath been done against me in this matter?`'

"`'`Yes,`' said he, '`you are free from all that hath been done against you.
But then,`' he continued, starting up in a rage, '`I can put the oath to any man here,
and I will tender it to you again.`'

"`I told him,`" says Fox, "`he had examples enough yesterday,
of swearing and false swearing, both in the justices and the jury.`"

Nothing, however, would suffice to deliver the prisoner, but taking the oath.
"`Give him the book,`" said the judge;
and "`give him the book!`" re-echoed the sheriffs and the justices.

"`If it be a Bible,`" said George, "`give it me.`"

"`Yes, yes,`" said the judge, "`give it him.`"

The oath was then read; but probably,
without any supposition that the prisoner was going to take it;
though he stood with the book in his hand.

"`When it was read, he asked me,`" says George, "`whether I would take the oath or no?`"

"`'`Then said I, '`ye have given me a book here, to kiss and to swear on;
and this book which ye have given me to kiss,
says '`Kiss the Son!`' and the Son says in this book,
'`Swear not at all;`' and so says also the apostle James.
I say as the book says, and yet ye imprison me!
How chance ye do not imprison the book for saying so?
How comes it, that the book is at liberty amongst you, which bids me not to swear,
and yet ye imprison me for doing as the book bids me?`'`"

No answer was returned to this appeal, except by the judge; who,
doubtless somewhat wincing under this unusual mode of address, replied, "`Nay,
but we will imprison George Fox:`" a promise which he failed not to perform.

Of the place of confinement to which he was now removed, he gives a dismal account;
describing it as a tower into which the smoke from the other parts of the prison,
came up so thick that he could scarcely see the light of his candle;
and as he was kept under three locks,
the turnkey would hardly be persuaded to come and unlock the outermost door,
to make a draught for the smoke, even to prevent his being suffocated.
Added to this, the rain came in upon his bed:
and frequently when he went in his shirt at night to
fasten the window in order to prevent it,
the wind would drive the rain in upon him, till he was in a worse condition than before.
"`And the place being high,`" he says,`" and open to the wind,
sometimes as fast as I stopped it, the wind blew it out again.
In this manner did I lay, all that long cold winter, till the next assize; in which time,
I was so starved with cold and rain, that my body was greatly swelled,
and my limbs much benumbed.
But the Lord`'s power,`" he says, "`was over all; supported me through all,
and enabled me to do service for him, and for his truth and people,
as the place would admit.
For while I was in Lancaster prison, I answered several books; as the Mass,
the Common Prayer, the Directory, and the Church Faith;
which are the four chief religions that are got up since the apostles`' days.`"

After passing through another examination at the next assize, in which,
although great care was taken that no errors should be found in his indictment,
there were nevertheless some, especially, that again, the word "`subject`" was omitted;
he was hurried away from the bar--and some difficulty
occurring about passing sentence upon him,
and still more, as to what was to be done with him, he was,
in about six weeks from the time of the assizes, removed to Scarborough Castle;
a measure which the magistrates promoted to the utmost;
not relishing the idea of his remaining amongst them.
"`After the assize,`" he says,
"`Colonel Kirby and other justices were very uneasy with my being at Lancaster;
for I had galled them sore at my trials there,
and they laboured much to get me removed to some remote place.
Colonel Kirby threatened I should be sent far enough.

"`When they had prepared for my removal,`" he proceeds to say, "`the under sheriff,
with the head sheriff`'s man, with some bailiffs, came and fetched me out of the castle;
when I was so weak with lying in that cold, wet, and smoky prison,
that I could hardly go, or stand.
They had me into the jailer`'s house, where was Colonel Kirby, and several others,
and they called for wine to give me.

"`I told them I would have none of their wine.`"

"`Then they cried, '`Bring out the horses.`'

"`I desired them first to show me their order or a copy of it,
if they intended to remove me; but they would show me none but their swords.`"
And totally inattentive to his remonstrances against the injustice of the action,
they haled him out, and lifted him upon one of the sheriff`'s horses.

"`They hurried me away,`" he continues, "`about fourteen miles to Bentham;
though I was so very weak I was hardly able to sit on horseback.
The wicked jailer, one Hunter, a young fellow, would come behind,
and give the horse a lash with his whip, to make him skip and leap, so that I,
being weak, had much ado to sit him.
Then he would come and look me in the face, and say, '`How do you, Mr. Fox?`'

"`I told him it was not civil in him to do so.`"
A calm remonstrance, which probably was of little service, except to heighten the joke.

When arrived at Scarborough, he was lodged as a prisoner in the castle,
in a room facing the sea, and therefore exposed to violent winds;
which driving in the rain,
caused his present abode to be quite as forlorn and
comfortless as that he had just quitted in Lancaster Castle.

In this place he was visited by a great variety of persons;
and amongst the rest by Dr. Cradock; of whose interview with him, he thus speaks:--

"`After this came Dr. Cradock, with three priests more; and the governor with his lady,
(so called,) and another that was called a lady, with a great company.

"`Dr. Cradock asked me what I was in prison for?

"`I told him for obeying the command of Christ and the apostle, in not swearing.
But, if he, being both a doctor and a justice, could convince me,
that after Christ and the apostle had forbid swearing,
they commanded the Christians to swear, then I would swear.`"

As he seconded this proposition by offering him the Bible,
in order that such a command might, if possible, be produced,
the Doctor brought forward the words from Jeremiah; "`It is written,
ye shall swear in truth and righteousness.`"

"`Aye,`" said George, "`it was written so in Jeremiah`'s time;
but that was many ages before Christ commanded "`Not to swear at all.`"
I could bring as many instances out of the Old Testament for swearing as thou,
and it may be, more; but of what force are they,
to prove swearing lawful in the New Testament, since Christ and the apostle forbade it?
Besides, in that text where it is written, '`Ye shall swear,`' etc.; what ye was this?
Was it ye Gentiles, or ye Jews?`"

To this the doctor would not reply; but one of the priests said,
"`It was to the Jews this was spoken;`" and Dr. Cradock agreed that it was
so-- an acknowledgment which for that time disposed of the question.

After remaining a prisoner at Scarborough Castle above a year,
he relates that he sent a letter to the king;
"`in which,`" says he,`" I gave him an account of my imprisonment,
and the bad usage I had received in prison;
and also that I was informed that no man could deliver me but he;`" which statement,
in connection with the representations of some of his friends,
at length succeeded in procuring an order for his release.
