== Chapter XV.

Amongst the Christians, who, in the seventeenth century,
submitted themselves to "`the obedience which is of faith,`" the names of Robert Barclay,
the Apologist, and of his father, David Barclay must not be forgotten.

David Barclay was born at Kirtounhill in Scotland, in 1610,
at the seat and birth-place of his ancestors;
but owing to some embarrassment in his father`'s affairs,
this ancient estate which had been in the family for upwards of five hundred years,
was obliged to be sold.
David, however, with the rest of the children, received a liberal education, and,
according to the custom of the times, when old enough he went on his travels;
and coming into Germany, he enlisted as a volunteer in the, army of Gustavus Adolphus,
King of Sweden; and after having been engaged in many battles,
on the breaking out of the civil wars in his native country, he returned home.

Here he was employed with great success, against the rebels, upon several occasions;
was appointed a colonel of horse, and to command in the shires of Ross, Sutherland,
and Caithness.
But after the overthrow of the adherents of Charles I., at Preston,
and the assumption of power by the opposite party, he, with his brother officers,
was turned out of his post:
from which period it does not appear that he
ever afterwards engaged in military concerns.

Being now, by the situation of public affairs,
incapable of rendering any further service to his prince, he retired to Gordonstoun;
between which place, and Edinburgh, he chiefly passed his time, until the year 1663;
at which period he experienced the trial of losing his excellent wife.^
footnote:[He had married Catherine Gordon, eldest daughter of Sir Robert Gordon,
of Gordonstoun, second son to the Earl of Sutherland.]
Added to this affliction, he was by some strange misapprehension,
about the same time committed to Edinburgh castle,
by an order from government after the Restoration,
on the plea of his having been a trustee under the usurper, Cromwell;
but the facts of his having suffered in the cause of Charles I.,
in the loss of his military appointments, and also in the seizure for several years,
of his estate, were so notorious, that at the interposition of the Earl of Middleton,
he was liberated without any thing being laid to his charge.

Having now passed through many vicissitudes of a personal kind,
and witnessed also in these changeful times,
the shadowy and unsatisfying nature of earthly
distinctions and enjoyments in the case of others,
it was the desire of David Barclay`'s heart,
to retire from any further walking "`in a vain show,`" and to
seek his future happiness in a life devoted to God.

With this view,
he looked round upon the various professors of
religion with which the kingdom was then filled;
but he saw, that, whilst each party laid claim to be the only possessors of the truth,
they not only differed from, but persecuted each other, with the greatest violence,
whenever they had an opportunity.
He betook himself therefore to the close reading of the New Testament,
as the only certain way of knowing the religion of Christ in its primitive purity;
and in this study, he discovered that the bickerings and disputes,
the railings and heart-burnings which the professors thereof too often displayed,
did not take their rise from any knowledge they
had of the thing for which they clamoured;
but rather from their ignorance of it; the religion in itself, being nothing but,
"`righteousness, and peace, and joy in the holy Ghost.`"

He was under the influence of these considerations,
when he heard of the much-derided Quakers--"`and why derided?`"
he inquired.
The answer was obvious.
Because they were singular, in faithfulness to the commands of Jesus Christ.
They stood almost alone, in lifting up a testimony against the spirit of the world,
in dress, in speech, in action, in almost everything.
On the whole, he considered within himself,
that if they were really such as even their enemies were forced to acknowledge,
there must be somewhat extraordinary about them.
A conclusion, which, upon several occasions, he afterwards mentioned to his friends.

With much earnestness therefore,
did he proceed to inform himself about the way which was "`everywhere
spoken against;`" and being about this time,
in London, he had discourse there, and elsewhere, with several friends;
from which converse, his mind became convinced of the truth of their tenets,
and under this conviction he joined their society.

If much was to be endured by those amongst the primitive friends,
whose habits and education inured them in some degree to hardships;
still more exercising were the difficulties to which persons were often called, who,
like David Barclay,
had been accustomed to partake of the ease and indulgences of the higher ranks of life.

In the north of Scotland, and chiefly at Aberdeen, in the vicinity of which he resided,
the Quakers were particularly ill used;
being often insulted at their meetings by the lowest dregs of the populace,
whom the zealots of that day encouraged to molest them.
It was remarked,
that none bore these indignities with greater calmness than David Barclay; and, when,
upon an occasion of uncommon rudeness,
one of his relations lamented that he should experience such a
reverse of treatment from what he had formerly known in that place,
he replied, "`that he found more satisfaction, as well as honour,
in being thus insulted for his religious principles, than when, some years before,
it was usual with the magistrates as he passed the city of Aberdeen,
to meet him several miles, and conduct him to a public entertainment in their town-house,
and then convey him so far out again, in order to gain his favour.

Soon after his convincement, which took place in 1666, he sent his son Robert,
(the celebrated apologist,) to reside on his estate of Ury, near Stonehaven,
accompanied by his agent, David Falconer, a worthy friend,
who had several times suffered imprisonment for conscience sake, at Edinburgh.
The first public meeting for worship, was kept at Ury that year;
Robert Barclay being about nineteen years of age;
and having then become newly united in faith and fellowship, with the Society of Friends.

This young man was born at Gordonstoun in 1648, and when very young,
was sent by his father to the Scotch college at Paris, of which his uncle was rector.
Here his talents so much distinguished him,
and he became so great a favourite with his uncle,
that he offered to bequeath him all his property,
(which was very considerable,) provided he would continue with him.
But his father fearing he might become tinctured with popish superstitions,
and also in compliance with the dying request of his mother, went himself to Paris,
in order to bring him home.
This measure was strongly opposed by his uncle; who, in order to detain him,
proposed to purchase, and immediately bestow upon him,
an estate superior in value to his paternal one.
But to this, Robert replied, that his father must be obeyed;
and the uncle finding himself disobliged, left his property to the college,
and to other religious houses in Paris.

It was far from the design or endeavour of David Barclay,
to proselyte his son to his own religious views; on the contrary,
it was his particular wish that he should imbibe
his religion from the force of conviction.
That it was in this manner he did receive very deep and
abiding impressions of the truth of friends`' principles,
he has himself left a record,
and that united with so powerful a delineation of the effect of their silent meetings,
that few readers of reflection will object to hear his statement; which,
with some slight omissions, is as follows:--

"`As there can be nothing,`" he says,
"`more opposite to the natural will and wisdom of man, than this silent waiting upon God,
so neither can it be obtained, nor rightly comprehended by man,
but as he layeth down his own wisdom and will,
so as to be content to be thoroughly subject to God.
And therefore it was not preached, nor could be so practised,
but by such as found no outward ceremony, no observation, no words, yea,
not the best and purest words, even the words of Scripture,
able to satisfy their weary and afflicted souls; because, where all these may be,
the life, power, and virtue, which make such things effectual, may be wanting.
Such, I say, were necessitated to cease from all outwards,
and to be silent before the Lord;
and being directed to that inward principle of life and light in themselves,
as the most excellent teacher,
which can never '`be removed into a corner,`' (Isaiah 30:20) came thereby,
to be learned to wait upon God, in the measure of life and grace received from him&hellip;

"`When people are gathered thus together, not merely to hear men, nor depend upon them,
but all are inwardly taught to stay their minds upon the Lord,
and wait for his appearance in their hearts, the forward working of the spirit of man,
is thereby stayed and hindered from mixing itself with the worship of God:
and the form of this worship is so void of all outward and worldly splendour,
that all occasion for man`'s wisdom to be exercised in that superstition and idolatry,
hath no place here: and there being also an inward quietness and retiredness of mind,
the witness of God ariseth in the heart, and the light of Christ shineth,
whereby the soul cometh to see its own condition.
And there being many joined together in the same work, there is an inward wrestling;
and as the measure of grace is abode in,
an overcoming of the power and spirit of darkness;
and thus we are often greatly strengthened and renewed in the spirit of our minds,
without a word.

"`Such is the evident certainty of that divine strength,`" he proceeds to say,
"`that is communicated by thus meeting together, and waiting in silence upon God,
that sometimes,
when one hath come in that hath been unwatchful and wandering in his mind,
or suddenly out of the hurry of outward business,
and so not inwardly gathered with the rest, so soon as he retires himself inwardly,
this power being in a good measure raised in the whole meeting,
will suddenly lay hold upon his spirit, and wonderfully help to raise up the good in him;
even as the warmth would take hold of a man that is cold, coming into a stove, or,
as a flame will lay hold upon some little combustible matter being near unto it.
Yea, if it fall out, that several met together, be straying in their minds,
(though outwardly silent,) and so wandering from the measure of grace in themselves,
(which, through the working of the enemy, and negligence of some,
may fall out,) if either one come in, or may be in, who is watchful,
and in whom the life is raised in a great measure, as that one keeps his place,
he will feel a secret travail for the rest,
in a sympathy with the seed which is oppressed in the other,
and kept from arising by their thoughts and wanderings.
And as such a faithful one waits in the light, and keeps in this divine work,
God oftentimes answers the secret breathings of his own seed, through such a one;
so that the rest will feel themselves secretly smitten, without words:-- yea,
sometimes when there is not a word in the meeting, but all are silently waiting,
if one come in that is rude and wicked,
and in whom the power of darkness prevaileth much,
perhaps with an intention to mock or to do mischief:
if the whole meeting be gathered into the life, and it be raised in a good measure,
it will strike terror into such an one, and he will feel himself unable to resist;
but by the secret strength and virtue thereof,
the power of darkness in him will be chained down,
and if the day of his visitation be not expired,
it will reach to the measure of grace in him,
and raise it up to the redeeming of his soul.

"`And this we often bear witness to: so as we have had frequent occasion,
in this respect, since God hath gathered us to be a people,
to renew the old saying of many, '`Is Saul also among the prophets V for,
not a few have come to be convinced of the truth after this manner: of which I myself,
in part, am a true witness; who, not by strength of argument, or,
by a particular disquisition of each doctrine,
and convincement of my understanding thereby,
came to receive and bear witness of the truth;
but by being secretly reached by this life.
For when I came into the silent assemblies of God`'s people,
I felt a secret power among them, which touched my heart; and as I gave way unto it,
I found the evil weakening in me, and the good raised up;
and so I became thus knit and united unto them,
hungering more and more after the increase of this power and life,
whereby I might feel myself perfectly redeemed!`" -- ([.book-title]#Barclay`'s Works#, vol.
ii. p. 353--356.)

It is not easily believed,
how solemnizing is the effect of deep silence in a large assembly.
It is so natural for us to be busy,
and to think we are effecting something by our own doings,
that when we are not worshipping God in words,
or when we are not bewailing our sins in language,
we can scarcely believe that we obtain any moral improvement.
Whereas, if we would but make the trial in humility, and with due resolution,
we should soon know by experience,
that we never retire in spirit decidedly and perseveringly to
wait upon God in passive silence of thought,
but that we gain some benefit therefrom.
If we fail to receive enjoyment or consolation, we shall certainly get a deeper, newer,
and more humbling sense of our spiritual condition,
as to our souls`' wants and their remedy.
We shall feel baptized into another state, and that a more real,
and a more edifying state.
We shall be delivered for a time, from our naturally fractional, dissipated,
wandering imaginations; and know something, though it be but little,
of a gathering under the shadow of the Almighty,
and of that holy cementing whereby "`Jerusalem
is built as a city that is compact together.`"
Even heathens were sensible that such a disposition of
mind was necessary to the attainment of moral good.

"`The knowledge of the Good, (or the supreme principle of things,`") says Plotinus,
"`is a divine silence, and the quiescence of all the senses;`"and again he says,
"`this therefore, is the life of the gods, and of divine and happy men;
a liberation from all terrene concerns, a life unaccompanied by human pleasures,
and a flight of the alone, to the alone.`"

It was a remarkable circumstance in Robert Barclay`'s religious history,
that in uniting himself with the simplest external mode of worship,
he escaped being connected with the most elaborate one: for in his youth,
he had become somewhat entangled with the corruptions of the Romish church.

"`I had scarce got out of my childhood,`" he says, "`when I was,
by permission of Divine Providence, cast among the company of Papists;
and my tender years and immature capacity not being able to withstand and
resist the insinuations that were used to proselyte me to that way,
I became quickly defiled with the pollutions thereof; until it pleased God,
in his rich love and mercy, to deliver me out of those snares,
and to give me a clear understanding of the evil of that way.`"^
footnote:["`Treatise on Universal Love,`"
--[.book-title]#Barclay`'s Works#, vol. iii. p. 186.]

About the year 1670, Robert Barclay married Christian Molleson,
a very estimable young woman, united in profession with friends.
A letter of Robert Barclay`'s, addressed to her before their marriage,
and apparently at an early stage of their acquaintance, is extant,
which contains some very pleasing thoughts,
and which strongly evince that deeper feelings than those of personal attachment,
prompted his desire for their union.

"`The love of thy converse,`" he says, "`the desire of thy friendship,
the sympathy of thy way, and the meekness of thy spirit, have often,
as thou mayest have observed,
occasioned me to take frequent opportunity to have the benefit of thy company&hellip;
Many things in the natural +++[+++mind]
will concur to strengthen and encourage my affection towards thee,
and make thee acceptable unto me; but that which is before all, and beyond all, is,
that I can say in the fear of the Lord,
that I have received a charge from him to love thee,
and for that I know his love is much towards thee, and his blessing and goodness is,
and shall be unto thee, so long as thou abidest in a true sense of it.`"^
footnote:[[.book-title]#The Friends in Scotland#, by John Barclay, p. 295.]

It was the lot of Robert Barclay, in common with many others amongst friends,
to feel himself commanded by the Divine will,
to "`become a fool for Christ`'s sake;`" and by a very humiliating exercise,
to prove his willing obedience to every call of apprehended duty.
Under this ready devotion of heart, conceiving himself required,
like one of the prophets of old,
to pass through three of the principal streets of the city where he dwelt,
clothed in sackcloth, and calling the people to repentance, --he yielded to the service.
And here it will be concluded, (as it indeed came to pass,) that by such a proceeding,
he would draw upon himself severe reproach,
from even those who were not insensible to his merits, both as a man and as an author.
And how should it be otherwise; seeing that the deep springs of such actions,
must necessarily be veiled from the reasoning faculty?
But be it so; there is nevertheless
"`a path which no fowl knoweth, and which the vulture`'s eye hath not seen;`"
"`God understandeth the way thereof, and he knoweth the place thereof;`"
and often doth he, in his infinite wisdom,
constrain his children to feel that it is a way in which they
must submit to learn the obedience which is of faith.
It is a way that is marked "`by the footsteps of the flock;`"
strait indeed and narrow, but it leads to everlasting life.
And scoff not at it,
ye that are mighty in the wisdom of this world! it is foolishness perhaps, to you;
but it is no foolishness with Him who seeth in secret, and who looks not, as you do,
at the outward action,
but at the humble resignation of heart which submits to perform it.
How severe an exercise of soul this service was, in the case of Robert Barclay,
we may gather from his own account, in a paper written upon the occasion,
and entitled "`A seasonable Warning to the Inhabitants of Aberdeen.`"

"`Among many others,`" he says,
"`whom at sundry times he hath caused to sound forth his testimony, I also have,
in the name, power, and authority of God, proclaimed his everlasting gospel among you.
But because many of you have despised this day,
and as ye have made merry over God`'s witness in your hearts,
etc. therefore was I commanded of the Lord God, to pass through your streets,
covered with sackcloth and ashes, calling you to repentance,
that ye might yet more be awakened and alarmed
to take notice of the Lord`'s voice unto you;
and not to despise those things which belong to your peace, while your day lasteth,
lest hereafter they be hid from your eyes.

"`And the command of the Lord concerning this thing,
came unto me that very morning as I awakened; and the burthen thereof was very great;
yea, seemed almost insupportable unto me; for such a thing until that moment,
had never entered me before, not in the most remote consideration.

"`And some, whom I called to declare to them this thing,
can bear witness how great was the agony of my spirit,
and how I besought the Lord with tears, that this cup might pass away from me!--Yea,
how the pillars of my tabernacle were shaken, and how exceedingly my bones trembled,
until I freely gave up unto the Lord`'s will.
And this was the end and tendency of my testimony; to call you to repentance,
by this signal and singular step; which I, as to my own will and inclination,
was as unwilling to be found in,
as the worst and the wickedest of you can be averse from receiving,
or laying it to heart.`"

Nor was this the only occasion in which the
faithfulness of Robert Barclay was put to the test;
he, with some other friends,
having to endure an unjust imprisonment by the magistrates of Montrose,
for exercising their right of meeting together to worship God.
There is no record how long he and his companions were confined on this occasion,
nor by what means they were liberated: but,
that it was by no concessions inimical to truth on their side, we have ample testimony,
in a noble appeal made in their joint names, to the magistrates who had committed them,
and which begins thus:--

[.embedded-content-document.letter]
--

[.salutation]
"`Friends,

"`Our case being as it was, and as some of us fully represented it to you,
how could you in justice deal with us as you have done;
in the middle of winter to send us, whose occasions lie elsewhere,
to a cold and desolate prison?--Well! the just
God beholdeth your injustice and oppression;
iniquity lieth at your door, and we are to lay it upon you,
and to charge you in the name of the Lord God, that you beware for the future,
to be found in such practices; and in the sense that you have done evil herein,
be resolved to do so no more; that, if possible,
your iniquities in this and the like cases,
(for this is not the first,) may be forgiven you.

"`As for us, we are not afraid of you, nor ashamed of our testimony,
and you cannot vanquish us.
You imagine a vain thing, and you will herein weary yourselves with very vanity.`"

--

After some close expostulations, it thus concludes:--

[.embedded-content-document.letter]
--

"`Well! we ask nothing of you, but that you come to a sense of your past way,
that you may not fall into the like for the future.
And as for us, we are well contented to stay here,
until the due time of our deliverance come.
And our expectations, (be it known unto you,) are neither from the hills,
nor from the mountains, but from God alone.
Our cause is committed to him who judges righteously!
We are, as regards our testimony, and for its sake, well contented, well pleased,
well satisfied to be here; our bonds are not grievous unto us,
glory to the Lord for ever! who hath not been, and who is not wanting to us.

[.signed-section-signature]
"`John Swintoune, William Napiek, John Milne, Robert Barclay, James Nuccoll,
William Low.`"^
footnote:[Barclay`'s [.book-title]#Friends in Scotland#, p. 315-- 316.]

--

Whilst the younger Barclay was thus valiantly contending for the truth,
and also suffering in its behalf, David Barclay, the father,
had also a share in "`enduring hardness`" under the banner of the cross; he,
with other friends to the number of

twelve, being taken at a meeting, and committed to the Tolbooth, at Aberdeen; where,
after three months`' confinement, under much oppression and many painful circumstances,
they were brought up for examination;
and being fined for the offence of frequenting and keeping conventicles,
and refusing to pay such fines, they were remanded back to their former prison.

At this time, Robert Barclay was engaged in ministerial service in Holland and Germany;
and on his return home, heard in London of his father`'s, and the other friends`',
imprisonment: whereupon, he applied to the king in their behalf;
and although it does not distinctly appear that owing to this application,
David Barclay was released, yet such shortly after, being the case,
it is to be concluded that it was so.

Robert Barclay had not long returned home,
when he was himself apprehended with some others while attending a meeting for worship,
and by order of the provost of Aberdeen, conveyed to prison.
Intelligence of his captivity having reached the
knowledge of an illustrious friend of his,
Elizabeth, Princess Palatine of the Rhine,^
footnote:[She was the eldest daughter of Frederick V. Elector Palatine,
and King of Bohemia, by Elizabeth, daughter of King James I. of England.]
a distant relation of his mother`'s,
and with whom he had contracted an intimate
acquaintance during his recent travels in Germany,
she manifested her sincere desire to serve him,
by addressing the following letter in his behalf to her brother, the Prince Rupert;
by the tenor of which epistle,
she seems to have received information of somewhat an exaggerated kind,
respecting his case.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Herford, December 19th, 1676.

[.salutation]
"`Dear Brother,

"`I have written to you some months ago, by Robert Barclay, who passed this way,
and hearing I was your sister, desired to speak with me.
I knew him to be a Quaker, by his hat,
and took occasion to inform myself of all their opinions;
and finding they were so submiss to the magistrates in real, omitting the ceremonial,
I wished in my heart, the king might have many such subjects.
And since, I have heard that notwithstanding his majesty`'s gracious letter on his behalf^
footnote:[Robert Barclay had interested Princess Elizabeth in behalf of his father;
and she had at his request engaged her brother, Prince Rupert,
to apply to the king for the liberation of David Barclay;
to which circumstance she probably here alludes
in speaking of the king`'s gracious letter,
etc.--'`I should admire,`" she says,
in a former letter to R. B.--"`I should admire God`'s providence,
if my brother could be a means of releasing your father and forty more in Scotland:
having promised to do his best,
I know he will perform it.`" --Barclay`'s [.book-title]#Friends in Scotland,# p. 354.]
to the council of Scotland,
he has been clapped up in prison with the rest of his friends,
and they threaten to hang him
(at least those they call preachers among them)
unless they subscribe to their own banishment, etc.
Therefore, dear brother, if you can do any thing to prevent their destruction,
I doubt not but you would do an action acceptable to God Almighty,
and conducive to the service of your royal master;
for the Presbyterians are their main enemies; to whom they are an eye sore,
as bearing witness against all their violent ways.
I care not though his majesty see my letter;
it is written no less out of an humble affection for him,
than in a sensible compassion of the innocent sufferers.
You will act herein according to your own discretion:
and I beseech you still consider me as yours,

[.signed-section-signature]
"`Elizabeth.`"

--

It does not appear that the above application was speedily, if at all, influential,
in the liberation of Robert Barclay; who, with his friends,
giving increased offence to the magistrates of Aberdeen,
by preaching to the populace from the windows of their prison in the Tolbooth,
were removed to a place out of the town, called the chapel;
in which the commissioners who gave orders for their removal,
expected the prisoners would be better accommodated.
But instead of this, they found themselves placed in a small, cold, narrow place,
which had a great door opening to the eastern ocean, without any fence.
Here, they had scarcely more room than sufficed to contain their beds;
and the window was so small, that they could not see even to eat their food,
except by candle-light,
or whilst the door was set open by the keeper when he brought their provisions.
But hard as this treatment was,
the case of the rest of the friends who were
left at the Tolbooth was if possible still worse;
and their hardships from want of room, etc.,
were augmented by the addition made to their number, of eight more of their brethren,
taken at religious meetings; in consequence of which, as a miserable alternative,
some of them (for want of space) were obliged to take up their
lodging amongst the debtors and other prisoners,
who lay in the lower vaults, much thronged.

In this exercised state,
these poor sufferers were not without some ministrations of
comfort from their "`companions in tribulation,
and in the kingdom and patience of Jesus Christ;`" as the
following extracts from an epistle of Isaac Penington evince.

He superscribes it, "`For my dear suffering friends in Scotland.`"

After reminding them of the "`blessed visitation`" and
tender mercy of the Lord towards them as a people,
he says,

[.embedded-content-document.letter]
--

"`Indeed the Lord is with us--what can we desire more?
preparing us for himself, preserving us in the life of his blessed truth,
building us up more and more,
and causing his spirit of glory and living power to rest upon us.

"`So, my dear friends, none look out, either at outward or inward sufferings; but,
to the Lord only, whose life, spirit, and power is above them,
and bears up all over them, who are in spirit joined to him, faithfully waiting upon him;
which God daily teaches and enables his to do.

"`Be of good faith, my dear friends; look not out at any thing;
fear none of those things ye may be exposed to suffer, either outwardly or inwardly,
but trust the Lord over all; and your life will spring and grow, and refresh you,
and the love and power will cleanse out, and keep out what would hinder its growth;
and ye will learn obedience and faithfulness, daily more and more,
even by your exercises and sufferings; yea,
the Lord will teach you the very mystery of faith and obedience (oh blessed
lesson!) and ye shall not be disappointed of your hope or crown,
by any thing the enemy can plot, or bring about against you;
but have the weight of glory increased and enlarged by his temptations,
and your manifold sufferings; the wisdom, power,
love and goodness of the Lord ordering everything for you,
and ordering your hearts in everything, etc.

"`This is the salutation and tender visit of the love of your brother in the truth,
whose breathings are to God for you, and his praises unto him,
through the sense of his being with you, and daily showing mercy to you,
upholding and preserving you in the midst of your sore trials and afflictions.

[.signed-section-signature]
"`Isaac Penington.`"

[.signed-section-context-close]
"`London, 5th of 5th month, 1676.`"

--

One of the pretences made use of by the authorities of Scotland,
for their cruel proceedings against the Quakers,
was an allegation of their being popishly affected;
and advancers of the interests of the Romish Church.
But a curious inconsistency manifested,
that even if such had been the case (than which nothing seemed more improbable)
there were occasions in which the advocates of popery were not considered as
deserving of ill-treatment at the hands of the magistrates of Aberdeen.
The case was this.
The Marquis of Huntley, as noted a papist as any in Scotland,
and one who greatly promoted that class, was bringing home his wife,
the daughter of the Duke of Norfolk,
one of the foremost of the same persuasion in England;
when on their entrance into Aberdeen,
the magistrates assembled a large concourse of the citizens, and with much parade,
went forth to meet them, expressing all the usual tokens of profound respect;
so that on that occasion,
"`the whole town appeared in a manner taken up with the grandeur of the ceremony.`"^
footnote:[J. Barclay`'s [.book-title]#Friends in Scotland#, p. 385.]

On reading which,
the mind involuntarily recurs to the homely proverb of "`one may steal a horse,
whilst another may not look over a hedge.`"

However, in a few months, many persons applying in behalf of the imprisoned Quakers,
the commissioners decreed,
that "`considering the extraordinary trouble sustained
by the magistrates and burgh of Aberdeen,
through the many Quaker conventicles held in the Tolbooth,
and that others have been urged to throw themselves into the snare of imprisonment,
for the purpose of molestation,
the following persons (amongst whom was Robert Barclay)
be removed to the Tolbooth of the burgh of Banff,
till further orders.
(Here follow their names.) Likewise,
that sundry others (including David Barclay) be removed from the prison of Aberdeen,
and confine themselves to their country-houses and parishes,`" etc.

When those who were ordered to be removed to Banff, were delivered over to the sheriff,
he gave them also their liberty, on condition of being forthcoming,
when he should appoint a time to convey them thither; a mode of getting rid of them,
when found impossible to subdue their constancy,
which seems to have been often practised by the persecutors of friends in these times.

Before this took place, the suffering friends had made an effort in their own behalf,
by representing their case to the council; and Robert Barclay,
being informed that Archbishop Sharpe was a chief instigator of their sufferings,
addressed to him a very searching appeal, in which he reminds him,
that a memorial of their sufferings was intended
to be presented at the first sitting of council;
"`by which the archbishop would be informed,
how we have been upwards of a year prisoners,`" he says,
"`and the goods of many poor people miserably spoiled;
of which thou art said to be the chief and principal author;
and that the attempting to persecute us, as well as the prosecution of it,
doth proceed from thy influence; as being done either at thy express desire,
or by some others, in hopes thereby to gratify thee.

"`How far thou art truly guilty thereof, thine own conscience can best tell;
but surely such practices (if thou hast either directly or indirectly
had a hand in them) will neither commend thee to God,
nor good men.
I presume thou lookest upon it as thy chiefest honour, to be reputed a Christian bishop,
deriving thy authority from Christ and his apostles.
But they never gave warrant for any such doings;
being preachers and practisers of patience, and suffering, but never of persecuting,
or causing to rob any of their goods or liberties, for conscience sake.`"

He proceeds in an argumentative strain for awhile, and then in conclusion,
(one would say assuredly, in the spirit of prophecy,) he leaves with him these words:

"`And thou mayst assure thyself, that the utmost rigour that can be used to us,
shall never be able to make us doubt of, or make us depart from,
that living precious truth, that God in his mercy hath revealed to us, and which, by us,
is embraced; nor yet fright us from the public profession of it, yea,
though we should be pursued to death itself; which, by the grace of God,
we hope cheerfully to undergo for the same; and we doubt not, but God would,
out of our ashes, raise witnesses who should outlive all the violence and cruelty of man.
And albeit thou shouldst thyself be most inexorable and violent towards us,
thou mightest assure thyself, not to receive any evil from us, therefore; who,
by the grace of God, have learned to suffer patiently,
and with our Lord and master Jesus Christ, to pray for, and love our enemies.
Yet, as thy so doing to an innocent and inoffensive people,
would be an irreparable loss to thy reputation, so the God of truth,
whom we serve with our spirits in the gospel of his Son,
and to whom vengeance belongeth (so we leave it) would, certainly,
in his own time and way, avenge our quarrel;
whose dreadful judgments should be more terrible unto thee,
and much more justly to be feared,
than the violent assaults or secret assassinations of thy other antagonists.`"

"`That thou mayest prevent both the one and the other,^
footnote:[The historical reader will remember,
that in about two years from the date of this epistle, (viz. 1679,) Archbishop Sharpe,
as he was passing on his way in his coach and six,
was cruelly assassinated by some of the Presbyterians,
(to whom he had been himself a rigid persecutor,) and who, as they were murdering him,
loaded him with the epithets of "`apostate,`" "`betrayer`" and "`persecutor,`" etc.]
by a Christian moderation, suitable to the office thou layest claim to,
is the desire of thy soul`'s well-wisher,

"`R. Barclay.`"
"`From the chapel prison of Aberdeen, the 26th of the 1st month, 1677.`"

"`With the same measure that thou metest,
it shall be measured to thee again;`" is a solemn axiom,
which was often strikingly verified in the case of the persecuted Quakers,
as their records testify.
One instance in particular, may here be profitably related;
because it is soothing to remark,
that sincere repentance (as we may humbly hope) mingled with,
and ameliorated the bitterness of that cup of retributive justice, which, in this case,
the offender was required to drink of.

The individual alluded to, was one Matthew Hide,
a person of some note in the city of London; who had made it his business,
for the space of nearly twenty years,
publicly to contradict the Quakers in their meetings, and, as far as he could,
to disturb them in their mode of worship.
It would seem, however, that a blind zeal to put down what he considered as heresy,
was his motive for acting thus,
rather than any furious hatred against their retired and serious devotions;
which as being so contrary and reproving to the bustle and stir of the fleshly mind, was,
no doubt, the great offence for which they were generally so much opposed, and ill used.

It was not by noise and clamour, but by gainsaying what they advanced,
that this man interrupted the preaching of ministers amongst friends;
insomuch that William Penn would sometimes be
moved to pray very earnestly for his repentance,
and to tell him in the presence of many auditors,
that God would assuredly plead with him by his righteous judgments;
and that the time would come,
in which he would be forced to confess the sufficiency
of those very principles which he then opposed.

This prophetic warning, at the close of many years, was at last affectingly verified;
for this Hide, being by sickness, brought to the brink of death,
began to take that new and distinct view of things, which is seldom or never taken,
in times of health and worldly prosperity.
Oh, it is an easy thing to dispute about truth;
and to contend for one way against another,
whilst we appear to have time enough before us, to follow which we choose!
But when the soul is brought into that amazing state,
in which an untried eternity is before it--that which brings
into peace with God-- that--(call it by what name you will--
deride it how you may)--that which has power to support,
to comfort, and to direct,
in times of tribulation--that is found to be the truth--the tried and everlasting truth.

And now in the hour of his great exigency, when principles were to be proved,
this man was reminded by the monitor within, of those of friends.
Well essayed--well proved--doubtless he had seen them oftentimes;
himself having been one that had helped to try them.
Ah--there was no chaff there!--no vain words without a meaning--no letter doctrines,
dry and dead as the unbelief to which they spake--no empty notions --no sapless,
lifeless phraseology--but Christ the true vine--the good shepherd,
breaking the bread of life through his own true and
faithful servants--these were things he remembered--and,
alas!--remembered also, that they were things which he had mocked and rejected!

But though it were so, he believed that as the ministers of a merciful Lord,
he had but to ask their attendance at his dying bed, and the request would be granted.
He therefore desired that George Whitehead, and some of his friends might be sent for;
and although it was late in the evening when the message was delivered to them,
they immediately visited him.

"`I am come,`" said George Whitehead, "`in love and tenderness to see thee.`"

"`I am glad to see you,`" said Hide.

"`If thou hast any thing upon thy conscience,`" said Whitehead,
"`I would have thee to clear it.`"

To this Hide returned for answer, that what he had to say,
he spake as in the presence of God.
"`As Paul was a persecutor of the people of the Lord,`" he said,
"`so have I been a persecutor of you his people; as the world is,
who persecute the people of God.`"

He added more; but being extremely weak, his words could not well be understood.

"`Thy understanding being darkened,`" said George Whitehead,
"`when darkness was over thee, thou didst gainsay the truth, and people of the Lord;
and I knew that that light which thou didst oppose,
would rise up in judgment against thee.
I have often, with others, laboured with thee, to bring thee to a right understanding.`"

To this Hide made answer, by again declaring as in the presence of God,
that he had done evil in persecuting Friends; and that he was heartily sorry for it;
adding, "`The Lord Jesus Christ show mercy unto me!--and the Lord increase your number,
and be with you!`"

After some interval of silence, George Whitehead addressed him with an earnest entreaty,
to ease his conscience of every burden that oppressed it.
"`My soul,`" said he, "`is affected to hear thee thus confess thy evil,
as the Lord hath given thee a sense of it.
In repentance, there is mercy and forgiveness; in confessing and forsaking of sin,
there is mercy to be found with the Lord, who, in the midst of judgment remembers mercy,
that he may be feared;`" and after a little more discourse,
and some intervals of silence, he tenderly inquired, "`How is it with thy soul?
Dost thou not find some ease?`"

"`I hope I do,`" answered the dying man; "`and if the Lord should lengthen out my days,
I should be willing to bear a testimony for you,
as publicly as I have appeared against you.`"

"`And if the Lord should not lengthen out thy days,`" said Whitehead,
"`dost thou desire that what thou sayest, should be signified to others?`"

"`Yes:`" he replied; "`I do`"--and perceiving him to be suffering much from weakness,
and want of breath, George Whitehead and his friends took their leave of him,
commending him to the mercy and forgiveness of God.

As this occurred on a Saturday night, he several times desired,
after the friends had withdrawn, that he might be permitted to live till the next day;
since,
as it was on a Sunday that he had most often opposed them in their meetings for worship,
he now wished on that day, to bear witness in their favour.

But this was not allotted to him;
for he died in about two hours after the above interview; signifying before he departed,
that he was favoured to feel some relief in his spirit.
