== Chapter XVI.

Page 359 Soon after his release from prison in 1677, Robert Barclay,
in company with George Fox, William Penn, Benjamin Furly and some others,
proceeded to Holland and Germany, on ministerial service; in the course of which, he,
with some of his companions, paid their respects to his kind friend, Princess Elizabeth.

A very interesting memoir having been written by William Penn of this journey,
I borrow an account of it from that source; previous to which,
some brief sketch of the journalist himself, may be desirable.

Scarcely any name in the Society of Friends,
is more generally known or respected by those of other religious persuasions,
than that of William Penn.
Indeed, so familiar are most readers with what relates to him,
that it may seem superfluous to enter into his history.

It may suffice then, but briefly to state, in reference to his birth and education,
that both were good; he being the son of Admiral Penn, who was knighted by Charles II.;
and became a great favourite of the Duke of York, afterwards James II.

William, his son, was born on the 14th of October, 1644,
and in the fifteenth year of his age entered a student at Christ Church, Oxford;
at which place he first imbibed some predilection for the principles of friends,
through the powerful ministry of Thomas Loe, a member of the society.
On his return home, he exhibited a religious seriousness of manner and deportment,
which (as likely to stand in the way of his worldly
preferment) was so displeasing to his father,
that finding all efforts ineffectual to remove it, he turned him out of doors.

In due time, however, the admiral somewhat relented towards his son;
and in hope of his relinquishing his present views, he sent him to France,
in company with some persons of quality;
from which measure so great an alteration took place in his behaviour,
that his father joyfully received him back, hoping his point was gained.

Still, the better impression, happily for the young man, was deepest;
and being in the year 1666, sent over by his father to Ireland,
to superintend an estate of his in that country, he fell in once more,
after a lapse of some years, with Thomas Loe, the minister amongst friends,
whose preaching had so deeply affected him at Oxford.

The first words which he now heard him utter, when he stood up in the meeting, were these:

"`There is a faith that overcomes the world;
and there is a faith that is overcome by the world;`"
on which subject the good man enlarged so powerfully,
that the finishing stroke was put to the convictions of William Penn, and he, henceforth,
constantly attended the meetings of friends; at one of which, in Cork, he was,
some little time after, apprehended, and with many others, carried before the mayor,
and committed to prison.

Here his confinement was but short; and his father hearing of the danger his son was in,
of being proselyted to Quakerism, commanded him to return home.
When arrived there, he had to undergo a severe conflict of mind,
between his duty to his heavenly Father,
and that which was required of him by his earthly parent;
but continuing steadfast in adhering to the Supreme Governor,
he was once more discarded from the paternal roof.

At length, finding it in vain to combat with his resolutions,
the admiral submitted to connive at his return home;
and though he would not seem to countenance his views,
he did not fail to use his interest in getting him released,
when he shared the usual fate of the other friends, in being taken at meetings,
and conveyed to prison.

In the year 1668,
in consequence of the unsatisfactory conduct of some Presbyterian ministers, with whom,
he and George Whitehead held, by appointment, a conference upon doctrinal points,
he wrote and published a little book called "`The Sandy Foundation Shaken;`"
which gave so much offence to some in authority in the church,
that he was committed to the Tower, as a punishment for what was considered as heresy.
In this place, he employed his time in writing his most popular production, "`No Cross,
no Crown;`" as well as several other religious treatises.
Amongst these, was one which he gave forth,
in order to clear himself from the charge of denying certain religious doctrines,
and which he entitled,
"`Innocency with her open Face;`" in which he so successfully vindicated himself,
that soon after its publication, he was released from his confinement,
which had been of about seven months`' continuance.

In the year 1670, the passing of the conventicle act, (prohibiting dissenters meetings,
under severe penalties,) occasioning friends upon many occasions, and one in particular,
to be kept out of their meeting-house in Gracechurch-street,
they met as near it in the street as they could; and William Penn preaching there,
was apprehended by a warrant from the lord mayor, Sir Samuel Starling;
and together with his friend William Mead, committed to Newgate, and at the sessions,
underwent their trial at the Old Bailey.

At this trial, he and his companion nobly stood their ground,
against every sort of insult both in speech and action,
that malice could exhibit towards them.
So evident indeed, was the innocence of the accused,
and the oppression of those appointed to be their judges,
that the jury would not bring them in guilty, in the sense stated in their indictment;
although remanded several times to consider of their verdict; and that,
under circumstances of personal discomfort; having twice to remain the whole night,
debating about it.

Not long after his trial, William Penn`'s father died,
being perfectly reconciled to his son;
to whom he uttered many instructive expressions on his death-bed,
of which the following memorial is preserved in "`No Cross, no Crown.`"

After specifying some instances,
of the different estimate the mind takes of things at the solemn hour of death,
to that which it makes in a time of health and strength; he says,

"`My own father, after thirty years`' employment, with good success,
in divers places of eminent trust and honour in his own country,
upon a serious reflection not long before his death, spoke to me in this manner;`"

"`Son William, I am weary of the world!
I would not live over my days again, if I could command them with a wish;
for the snares of life are greater than the fears of death.
This troubles me: that I have offended a gracious God, who hath followed me to this day.
Oh, have a care of sin!
That is the sting both of life and death.
Three things I commend unto you: First,
let nothing in this world tempt you to wrong your conscience: I charge you,
do nothing against your conscience; so will you keep peace at home;
which will be a feast to you in the day of trouble.
Secondly, whatever you design to do, lay it justly, and time it seasonably;
for that gives security and dispatch.
Lastly, be not troubled at disappointments; for, if they may be recovered, do it;
if they cannot, trouble is vain.
If you could not have helped it, be content;
there is often peace and profit in submitting to Providence; for afflictions make wise.
If you could have helped it,
still let not your trouble exceed instruction for another time.
These rules will carry you with firmness and comfort through this inconstant world.`"

"`Wearied to live, as well as near to die,`" he adds, "`he took his leave of us;
and of me, with this expression, and a most composed countenance: '`Son William,
if you and your friends keep to your plain way of preaching,
and keep to your plain way of living, you will make an end of the priests,
to the end of the world.
Bury me by my mother;--live all in love:--shun all manner of evil;
and I pray God to bless you all!
And he will bless you!`'`"

Many thick veils does a death-bed remove; and here was one strikingly taken away.
That persuasion, which once seemed a mass of foolishness and errors so great, that,
for continuing in it, the admiral had more than once, turned his son out of doors;
he now, with his last breath, bears witness to, as truth;--and, no doubt,
in remorse for those things of which he himself, in the days of his ignorance,
bad been guilty, he above all things, enjoins his son,
"`never to do any thing against his conscience!`"

In the year 1671, William Penn was again committed to Newgate for six months,
in consequence of being apprehended at a meeting in Wheeler-street.
On being released from this imprisonment, he went over to Holland and Germany;
and on his return home, he married, in 1672, Gulielma Maria Springett,
who has already been introduced to the reader`'s notice, as the playmate,
in her childhood, of Thomas Ellwood, and as the step-daughter of Isaac Penington.
Soon after his marriage, he took up his residence at Rickmansworth in Hertfordshire,
after first visiting the meetings of friends.

Various publications were the fruits of his labours in this retirement;
but that with which we are now concerned,
is the journal of his travels in Holland and Germany,
in company (as was before stated) with Robert Barclay, George Fox, Benjamin Furly,
and some others.

After remaining together in their travels for a short time, William Penn, Robert Barclay,
and two other friends, took leave of George Fox at Amsterdam,
and proceeded on their way to Herwerden, where Princess Elizabeth held her court.

It appears from the statements in this journal, that the princess,
and her friend and companion, the Countess de Hornes,
had formerly been followers of De Labadie;
of whom William Penn gives the following account.

"`This man was a Frenchman, who,
being dissatisfied with the looseness and deadness of the French Protestants,
even at Geneva itself, left them, and came for Holland;
and so vehemently declaimed against the apostacy of the priests and people there,
that the clergy were enraged, and stirred up the magistrates against him; and the rather,
because many followed him, and several women of great quality.
Upon this, the princess gave them an invitation, and they came, and were protected by her.
But since, some misconduct falling out in that place, she thereupon, in good measure,
withdrew her favours from them, and they removed into another place.

"`I was moved to visit this man and his company, six years ago; and did see him,
and his two great disciples; but they would not suffer me to see the people,
which I laboured for.
I, in that day, saw the airiness and unstableness of the man`'s spirit;
and that a sect-master was his name; and it was upon me, both by word of mouth,
and writing, to let them know that the enemy would prevail against them,
to draw them into inconvenient things,
if they came not to be stayed in the light of Jesus Christ, and to know the holy silence;
and that at last, they would come to fall out with one another, and moulder away;
which is in some measure come to pass, as I feared.

"`And in this, was the Countess (De Homes) commendable; in that she left all,
to have joined with a people that had a pretence at least,
to more spirituality and self-denial,
than was found in the national religion she was bred up in; for God had reached her,
as she told me, about nine years ago, and that by an extraordinary way.

"`Now it seemed great pity to us, that persons of their quality in the world,
should so willingly expose themselves for the false Quaker,
the reprobate silver--the mixture;
and that they should not be acquainted with the life and testimony of the true Quaker.

"`About a year since, Robert Barclay and Benjamin Furly,
took that city in the way from Frederickstadt to Amsterdam, and gave them a visit;
in which they informed them somewhat of friends`' principles,
and recommended the testimony of truth to them, as both a nearer and more certain thing,
than the utmost of De Labadie`'s doctrine.
They left them tender and loving.`"

He then states, that other friends resident in Holland,
had since visited these illustrious ladies; "`and though they,`" he adds,
"`especially the countess, made some objections in relation to the ordinances,
and certain practices of friends, yet she seemed to receive, at that time,
satisfaction from them.`"

"`These visits,`" he proceeds,
"`have occasioned a correspondence by way of letter betwixt them and several of us;
wherein the '`mystery of truth,`' hath been more clearly opened to their understandings,
and they have been brought nearer into a waiting frame, by those,
instructions which they have frequently received by way of epistles,
from several of us.`"

He then inserts a letter of Princess Elizabeth, in answer to two from him;
and which is as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Herford, May 2, 1677.

"`This, friend, will tell you, that both your letters were very acceptable,
together with your wishes for my obtaining those virtues,
which may make me a worthy follower of our great King and Saviour, Jesus Christ.
What I have done for his true disciples, is not so much as a cup of cold water;
it affords them no refreshment;
neither did I expect any fruit of my letter to the Duchess of L. as I have
expressed at the same time unto B. F. But since R. B. desired I should write it,
I could not refuse him;
nor omit to do any thing that was judged conducing to his liberty,
though it should expose me to the derision of the world.
But this a mere moral man can reach at; the true inward graces are yet wanting in

[.signed-section-closing]
"`Your affectionate friend,

[.signed-section-signature]
"`Elizabeth.`"

--

On coming to the city where she resided,
the friends made their arrival known to the princess,
with a request to hear at what time in the course of the next day,
it would be agreeable to her to receive them.
Her reply signified, that she was pleased to hear of their arrival,
and would be ready to receive them about seven o`'clock the next morning.

"`The next morning being come,`" says Penn,
"`(which was the sixth day of the week,) we went about the time she had appointed us,
and found both her and the countess, ready to receive us;
which they did with a more than ordinary expression of kindness.`"

He describes his mind, as "`very deeply and reverently affected,
and filled with an holy testimony to them;`" which he says,
was followed by that of his brethren, and the meeting concluded about eleven.

"`The princess,`" he says, "`entreated us to stay and dine with her; but,
with due regard both to our testimony and to her, at that time we refused it; desiring,
if she pleased, another opportunity that day; which she, with all cheerfulness,
yielded to; she herself, appointing the second hour.

"`So we went to our quarters, and some time after we had dined, we returned.

"`The meeting soon began; there were several present,
beside the princess and the countess.
It was at this meeting that the Lord, in a more eminent manner, began to appear.
The eternal word showed itself a hammer on this day; yea,
sharper than any two-edged sword, dividing asunder between the soul and the spirit,
the joints and the marrow.
Yea, this day was all flesh humbled before the Lord.
It amazed one:--struck another:-- broke another: yea,
the noble arm of the Lord was truly awakened; and the weight and work thereof,
bowed and tendered us also, after an unusual and extraordinary manner,
that the Lord might work a heavenly sign before them, and among them;
that the majesty of him that is risen among the poor Quakers,
might in some measure be known unto them; what God it is we serve,
and what power it is we wait for, and bow before.
Yea, they had a sense and discovery that day,
what would become of the glory of all flesh, when God shall enter into judgment!
Well! let my right hand forget its cunning, and my tongue cleave to the roof of my mouth,
when I shall forget the loving kindness of the Lord,
and the sure mercies of our God to us his travelling servants, that day!
O, Lord! send forth thy light and thy truth, that all nations may behold thy glory!

"`Thus continued the meeting till about the seventh hour; which done,
with hearts and souls filled with holy thanksgivings to the Lord,
for his abundant mercy and goodness to us, we departed to our lodging;
desiring to know whether our coming the next day,
might not be uneasy or unreasonable to her,
with respect to the affairs of her government; it being the last day of the week,
when we were informed she was most frequently attended by addresses from her people.
But with a loving and ready mind, she replied,
that she should be glad to see us the next morning, and at any time we would.`"

I feel persuaded, that I cannot better please my reader,
than by continuing the account which William Penn proceeds to give,
of the communication between the friends and this excellent lady;
from whose touching humility, an instructive lesson may be derived.

"`The next morning,`" he says, "`being the seventh day, +++[+++Saturday,]
we were there betwixt eight and nine; where,
Robert Barclay falling into some discourse with the princess,
the countess took hold of the opportunity, and whispered me to withdraw,
to get a meeting for the more inferior servants of the house;
who would have been bashful to have presented themselves before the princess; and,
blessed be the Lord! he was not wanting to us;
but the same blessed power that had appeared to visit them of high,
appeared also to visit them of low degree;
and we were all sweetly tendered and broken together;
for '`virtue went forth of Jesus`' that day;
and the life of our God was shed abroad amongst us, as a sweet savour;
for which their souls bowed before the Lord, and confessed to our testimony;
which did not a little please that noble young woman, to find her own report of us,
and her great care of them, so effectually answered.
Oh! what shall we say?
Is there any god like to our God, who is glorious in holiness, fearful in praises,
working wonders?
To his eternal name, power, and arm, be the glory forever!

"`The meeting done, the princess came to us,
expressing much satisfaction that we had that good opportunity with her servants;
telling us she much desired they should have a true and right character of us,
and that therefore she chose to withdraw, that they might have free access,
and that it might look like their own act, etc.

"`The twelfth hour being come, we returned to our inn, letting them understand,
we purposed, (the Lord willing,) to visit them some time of that afternoon.

At about three o`'clock, they repaired again to the princess; where, being come,
after some little time,`" he says,
"`the princess and countess put me in remembrance of a
promise I made them in one of my letters out of England;
namely, that I would give them an account,
(at some convenient time,) of my first convincement,
and of those tribulations and consolations which
I had met withal in this way of the kingdom,
which God had brought me to.

"`After some pause, I found myself very free, and prepared, in the Lord`'s love and fear,
to comply with their request; and so, after some silence began.
But before I had half done, it was suppertime,
and the princess would by no means let us go.
We must sup with her; which importunity not being well able to avoid, we yielded to,
and sat down with her to supper.

"`Among the rest present at these opportunities,
it must not be forgotten that there was a countess, sister to the Countess de Hornes,
then come in to visit her, and a Frenchwoman of quality;
the first behaving herself very decently, and the last often deeply broken:
and from a light and slighting carriage towards the very name of a Quaker,
she became very intimately and affectionately kind and respectful to us.

"`Supper being ended, we all returned to the princess`'s chamber;
where making us all to sit down with her, she, with both the countesses,
and the Frenchwoman pressed from me the continuance of my relation;
but none more than the countess`'s sister; which, though late,
I was not unwilling to oblige them with;
because I knew not when the Lord would give me such an opportunity.

"`And I found them affected.
It continued till about ten at night; yet many particulars omitted,
partly through forgetfulness, and partly for want of time.
Howbeit I must needs say, they heard me with an earnest and tender attention,
and I hope and believe the Lord hath made it profitable unto them.

"`This done, some discourse they had upon it,
and afterwards we spoke about a meeting for the next day,
being the first day of the week;
and that we might have not only as many of her own family, but as many of her town,
as would willingly be there, she yielded to it,
and appointed the meeting to begin at the second hour.
So we parted, being near the eleventh hour at night.`"

Of the meeting on the next day, he gives the following pathetic description.

"`The second hour being at hand, we went to the meeting, where were several of the town,
as well as of the family.
The meeting began with a weighty exercise, and travail in prayer,
that the Lord would glorify his own name that day.
And by his own power he made way to their consciences,
and sounded his awakening trumpet in their ears, that they might know that he was God,
and that there is none like unto him.
Oh! the day of the Lord livingly dawned upon us,
and the searching life of Jesus was in the midst of us.
Oh! the word that never faileth them that wait for it, and abide in it, opened the way,
and unsealed the book of life!
Yea, the quickening power and life of Jesus, wrought and reached to them;
and virtue from him, in whom dwelleth the Godhead bodily, went forth,
and blessedly distilled upon us his own heavenly life,
sweeter than the pure frankincense, yea,
than the sweet-smelling myrrh that cometh from a far country.
And as it began, so it was carried on, and so it ended.
Blessed be the name of the Lord, and confided in, be our God, forever!

"`As soon as the meeting was done,
the princess came to me and took me by the hand (which she usually did to us all,
coming and going,) and went to speak to me of the sense she had,
of that power and presence of God that was amongst us.
But she was stopped;--and turning herself to the window,
broke forth with an extraordinary emotion, crying out, '`I cannot speak to you,
my heart is full!`' clapping her hands upon her breast.

"`It melted me into a deep and calm tenderness,
in which I was moved to minister a few words softly to her;
and after some time of silence, she recovered herself,
and as I was taking my leave of her, she interrupted me thus;
'`Will ye not come hither again?
Pray call hither, as ye return out of Germany.`'

"`I told her we were in the hand of the Lord, and being his,
could not dispose of ourselves.
But the Lord had taken care that we should not forget her, and those with her;
for he had raised an heavenly concernment in our souls for her and them;
and we loved them all, with that love wherewith God had loved us;
with much more to that purpose.

"`She then turned to the rest of her friends,
and would have had us all gone to supper with her.
But we chose rather to be excused.
We should eat a bit of her bread, and drink a glass of her wine, if she pleased,
in the chamber where we were.
At last we prevailed with her to leave us.

"`After the princess had supped, we went all down, and took our solemn leave of her,
the countess, her sister, and the Frenchwoman, with the rest of the family,
whose hearts were reached and opened by our testimonies; recommending unto them,
holy silence from all will-worship, and the workings, strivings,
and images of their own mind and spirit;
that Jesus might be felt of them in their hearts;
and his holy teachings witnessed and followed in the way of his blessed cross,
that would crucify them unto the world, and the world unto them; that their faith, hope,
and joy might stand in Christ in them, the heavenly Prophet, Shepherd, and Bishop,
whose voice, all that are truly sheep, will hear and follow,
and not the voice of any stranger whatever.

"`So we left them in the love and peace of God,
praying that they might be kept from the evil of this world.`"
