== Chapter XX

After his marriage, George Fox continued in the same line of ministerial service,
which seldom allowed him to continue long in one place.
But the winter following this event, he was confined by illness at Enfield,
during which time he describes his spiritual sufferings
in relation to the apostate state of the church,
as very great.
It was a time of great persecution amongst friends,
owing to the enforcing of the recent act against conventicles;
and though by reason of his weakness he was incapable of visiting them in person,
he sent them an epistle by way of encouragement, in which he desires them,
"`not to be amazed at the weather,`" alluding to the
storms of persecution which were then befalling them.
"`Always,`" he says, "`the just suffered by the unjust, but the just had the dominion.
Though the waves and storms be high, yet your faith will keep you,
so as to swim above them, for they are but for a time, and the truth is without time.
Therefore keep on the mountain of holiness.

"`Do not think that any thing shall out-last the truth,
which standeth sure--and is over that, which is out of the truth.
So be faithful, and live in that which does not think the time long.`"

When he was recovered, "`it was upon me from the Lord,`" he says,
"`to go beyond sea to visit the plantations in America;`" he accordingly
wrote to his wife to come up to London to take leave of him,
preparatory to his departure.

Several friends accompanied him upon this service, his account of which is very concise,
and not expressive of much, that in the detail would be particularly interesting.

The death of one individual of his company we must not however, omit to mention,
that person well deserving an honourable remembrance in this record,
as one who in these tribulating times, faithfully bore her testimony to the truth.

"`About a week after we landed in Jamaica,`" he says, "`Elizabeth Hooton,
(or Hutton,) a woman of great age, who had travelled much in truth`'s service,
and suffered much for it, departed this life.
She was well the day before she died, and departed in peace like a lamb,
bearing testimony to truth at her departure.`"

This person was one of the very first of George Fox`'s hearers,
and also of those convinced by him;
and of whom he thus speaks in his Journal in the year 1647.

"`Travelling through some parts of Leicestershire and into Nottinghamshire,
I met with a tender people, and a very tender woman, whose name was Elizabeth Hutton.`"
She is said by Sewel, to have been the first woman preacher amongst friends.

In the year 1661, after the cruel treatment inflicted upon the Quakers at Boston,
this woman, accompanied by another female,
conceiving herself commanded from the Lord to proceed there to
witness against the recent proceedings of the magistrates,
prepared to obey; and,
because of the laws which enacted a fine upon every Quaker that was brought there,
they could not meet with any master of a vessel who would take them,
they went round towards Virginia, from whence they made their way to Boston.
But when arrived there, they, with great difficulty found a place of reception,
because of the penalty upon those who received a Quaker into their houses; yet at last,
some kindly disposed woman accommodated them.

On the following day they went to visit their suffering friends in prison,
when the jailer took and carried them before the governor Endicot,
who with much scurrilous language after abusing them for witches,
enquired of Elizabeth what she came there for?

"`To warn thee,`" she replied, "`that thou shed no more innocent blood!`"

This, and some more of her replies so much displeased him,
that he sent both her and her companion to prison, where,
after consulting what was best to be done with them,
they were taken two days`' journey into a desolate wilderness,
infested by wolves and bears, and left there to take their chance of life or death.
Through the protecting hand of Providence, they got from hence to Rhode Island,
whence they took ship for Barbados, from thence to New England again, and,
nothing daunted, once more they made their appearance at Boston.
But here being again taken, they were put on board a ship which carried them to Virginia,
from whence Elizabeth at that time departed home to England,
and stayed some time in her own habitation.
But her mind probably being still burdened with a sense that
her service in America had not been satisfactorily concluded,
she felt impelled once more to return to Boston, which she did,
accompanied by her daughter Elizabeth;
and when arrived there and her presence amongst them discovered,
an attempt was made on the part of the magistrates to
fine the master of the ship one hundred pounds,
for bringing her over.
But as he was able to make it appear that she had been with the king,
and that she had liberty from him to come thither,
and even to purchase a house there to dwell in, they found themselves at a loss,
and having by this time had an intimation (as we
have before stated) from the British monarch,
that they were to refrain from molesting the Quakers, they did not in this instance,
urge the penalty against the ship-owner.

Against Elizabeth herself the chief of their resentment was directed.
In vain did she plead permission from the king to buy herself a house;
she could obtain nothing from them but contempt and refusal.

Finding it useless to remain there, she proceeded to another town,
where she was taken and cast into prison with no bed to lie upon,
and for two days and nights she was kept absolutely without food.
Being then brought into court for judgment,
she was ordered to be whipped as a vagrant at three different towns,
receiving at each town, ten stripes with a three-stringed whip,
having three knots at each end; to all which, she patiently submitted,
and then lacerated as she was, they put her on horseback,
and carried her many miles into the wilderness, and towards night left her there,
once more to take her chance of escape from the wild beasts that infested it.
But these it seems,
were less to be dreaded than the savages in human form which she had encountered,
if dread, as applicable to fear of the oppressor, had found a place in her heart.
But sustained and comforted by a well-tried though invisible friend,
she came in the morning to a town called Rehobath, neither weary nor faint,
and proceeding from thence, to Rhode Island, she appeared before her friends there,
triumphant in the faith and giving thanks to God who had
counted her worthy to suffer for his great name`'s sake.

After some stay here, she had to return to the place where she had been imprisoned,
for her daughter, in which expedition she was again taken prisoner,
and very severely and oppressively treated, as was also her daughter,
and a female friend who accompanied her.
But to dwell upon these atrocities,
any further than as a medium whereby the sustaining power of God to
his confiding and afflicted creatures is most distinctly exhibited,
is not my aim.
It is enough that in these living illustrations,
we see that nothing of grief or oppression, as it respects the outward man,
can separate the believing soul from its God; but that on the contrary,
every heavenly grace, and spiritual beauty,
grows in transcendent loveliness by such severe exercises.

"`She departed like a lamb!`'`" says George Fox,
in speaking of the end of this faithful woman, who,
at an advanced age formed one of his company upon the work of the ministry,
in a far distant land, and subject to manifold personal discomforts and inconveniences.
"`She departed like a lamb, and how could it be otherwise?
She knew in whom she had believed--a friend long tried,
and ever faithful found--what then but sweetness and peace,
could accompany her sinking forever into his protecting arms?

After nearly two years spent in America, spreading the knowledge of the Truth,
oftentimes through more hardships from the want of
personal comforts than the persecution of opposers,
(which did not seem to befall him in this particular
service,) George Fox returned to England;
and the law against holding conventicles being then rigidly enforced,
he was not many months in his native land before he
experienced his usual lot of being taken before a magistrate,
and committed to prison.

Upon this occasion he was apprehended whilst in Worcestershire;
which county he was visiting, in company with his wife and some other friends.
The night before whilst he was sitting at supper,
he felt in his spirit a foreshadowing of evil,
which gradually strengthened into an assurance of what was about to happen to him;
and which he thus curiously expresses in a letter to his wife:
he having sent her with one of her daughters home into the north as
soon as he was taken prisoner and committed to Worcester jail.

[.embedded-content-document.letter]
--

[.salutation]
"`Dear Heart,`"

"`Thou seemedst to be a little grieved when I was speaking of prisons,
and when I was taken.
Be content with the will of the Lord God; for when I was at John Rous`'s, at Kingston,
I had a sight of my being taken prisoner; and when I was at B. Doiley`'s in Oxfordshire,
as I sat at supper, I saw I was taken: and I saw I had a suffering to undergo.
But the Lord`'s power is over all, blessed be his holy name forever!

[.signed-section-signature]
"`G. F.`"

--

His companion in this imprisonment was Thomas Lower,
who had married one of Margaret Fell`'s daughters, whose brother, Dr. Lower,
being one of the physicians to the king, an offer for his enlargement was soon tendered.
But such was the regard of this young man for George Fox,
that he could not be prevailed upon to leave him in captivity.

After being examined at the sessions and remanded back to
prison on account of declining to take the oath of allegiance,
they were removed by an habeas corpus to London,
where he underwent an examination at the bar of the King`'s Bench,
which concluded by his being ordered to be sent back to prison at Worcester,
with permission however, to go thither in his own way,
provided he promised to be there at the ensuing assizes.
He did not fail to be punctual to his engagement, and took his trial at Worcester;
which turning chiefly upon the usual matter of the oath,
concluded by his being again sent back to prison; but in about two hours after,
he received permission from the justices to be at liberty till the next quarter-sessions,
which interval he passed in London attending meetings, and especially the yearly one,
which he says was an "`exceeding glorious one beyond expression.`"

The result of his next appearance at the assizes
at Worcester was the sentence of a premunire;
upon which, being cast into prison for a period which threatened to endure for life,
his wife came out of the north to be with him.

Endeavours were used for his release, and not unsuccessfully,
for the king would readily have granted him a pardon, but pardon,
obviously implying guilt, which,
as to any offence against his king or country this
honest man could not justly charge himself with,
he would not accept of his liberty upon such terms.

The king seemed really anxious to have him thus released, saying to one Thomas Moore,
"`That George Fox needed not to scruple being released by a pardon,
for many a man that was as innocent as a child, had had a pardon granted him.`"
"`But I would rather have laid in prison all my days,`" says George,
"`than have come out in any way dishonourable to truth.`"

He chose therefore to try the validity of the indictment, which,
like the one by which on a former occasion he had been committed to Lancaster jail,
was full of errors.

Again being removed by an habeas corpus to London to
have this question tried at the bar of the King`'s Bench,
it was his happy lot to have for his judge,
one whose revered name is associated with thoughts of mercy and justice;
for Sir Matthew Hale had to decide the case.

The errors in the indictment being many and obvious,
the judges were all of opinion that it ought to be quashed and the prisoner liberated;
but George Fox being considered a dangerous man,
some movements were made to tender him the oaths, which, as it respected him,
was nothing else than taking measures to make him again a prisoner.

But as to his being a dangerous man, Judge Hale said,
"`he had indeed heard some such reports,
but he had also heard many more good reports of him;`" he therefore,
(obtaining the consent of the rest of the judges,)
desired him to be freed by proclamation.

During the time of his imprisonment at Worcester,
George had a severe fit of sickness which brought him into a state of great debility;
"`and I continued so,`" says he, "`a pretty while,
insomuch that some friends began to doubt of my recovery.
I seemed to myself to be amongst the graves and dead corpses,
yet the invisible power did secretly support me,
and conveyed refreshing strength unto me,
even when I was so weak that I was almost speechless.`"

He received also a strong internal assurance that the
Lord had a great deal more work for him to do,
before he took him to himself.

After his release from the prison at Worcester, he went down to Swarthmore with his wife,
and remained there for some time, visiting friends`' meetings occasionally in the north,
but chiefly employing himself in writing epistles to the society,
and compiling or finishing his other writings.

In the year 1677, he accompanied the party which William Penn and Robert Barclay joined,
in a journey to Holland and Germany, and of which we have already spoken in these pages.

Although he was not amongst the friends who
visited Princess Elizabeth upon this occasion,
he addressed a long epistle to her, which he thus commences:

[.embedded-content-document.letter]
--

[.salutation]
"`Princess Elizabeth,

"`I have heard of thy tenderness towards the Lord and his holy truth,
by some friends that have visited thee,
and also by some of thy letters which I have seen; which indeed,
is a great thing for a person of thy quality to have such a tender mind after the Lord,
and his precious truth;
seeing so many are swallowed up with voluptuousness and the pleasures of this world.`"

His observations about the scriptures, in this epistle, have great force of truth,
though not much elegance of diction in them.

"`The holy men of God,`" he says,
"`wrote the scriptures as they were moved by the Holy Ghost.
And all Christendom are on heaps about these scriptures,
because they are not led by the same Holy Ghost as those were,
that gave forth the scriptures; which Holy Ghost they must come to in themselves,
and be led by, if they would come into all the truth of them,
and have the comfort of God, Christ, and them.

"`O! therefore, feel the grace and truth in thy heart, that is come by Jesus Christ,
and that will teach thee how to live, and what to deny.
It will establish thy heart, season thy words, and bring thy salvation,
and will be a teacher unto thee at all times.`"

He added, in a postscript, "`The bearer hereof, is a daughter-in-law of mine,
that comes with Gertrude Dirick Nieson, and George Keith`'s wife, to give thee a visit.

[.signed-section-signature]
"`G. F.`"

--

To this plain and unceremonious epistle, the princess returned the following reply:--

[.embedded-content-document.letter]
--

[.salutation]
"`Dear Friend,

"`I cannot but have a tender love to those that love the Lord Jesus Christ,
to whom it is given not only to believe in him, but also to suffer for him.
Therefore your letter, and your friends`' visit, have been both very welcome to me.
I shall follow their, and your counsel, as far as God will afford me light and unction,
remaining still

[.signed-section-closing]
"`Your loving friend,

[.signed-section-signature]
"`Elizabeth.`"

[.signed-section-context-close]
"`Hertford, 30th Aug. 1677.`"

--

On his return home,
the labours of George Fox were more directed towards
obtaining redress for the sufferings of the society,
(which were still very great,) than, as heretofore, in travelling about,
promulgating the gospel message.
That was the service of his earlier days: he had now a different office in the vineyard.

For the purpose of petitioning parliament in behalf of friends,
as well as upon other accounts, his chief abode was in, and about London,
where he was occasionally joined by his wife.

Another very active petitioner with the king and government on behalf of the society,
was George Whitehead; who, in his Journal,
has preserved some interesting particulars relative to these matters.

"`Although,`" he says, (writing in the year 1683,) "`with God`'s assistance,
we prevailed with the king for relief in certain extreme cases of suffering,
yet hitherto there remained great oppressions
throughout most counties and cities of England,
by divers kinds of severe prosecutions; insomuch that several of us, (namely, George Fox,
Gilbert Latey,
etc.) were weightily concerned to have a general
statement of our suffering friends case and condition,
comprehensively composed, and drawn up by way of address and supplication,
to be presented to the king,
in order to make him the more sensible of the great
oppression and persecution we still were exposed to.
This measure being carried into effect by the drawing up a suitable
representation of the subject in the form of an address,
he states that "`it was presented to King Charles II.
and by him accepted at Windsor Castle,
on the 8th of the sixth month, 1683, by George Whitehead, Alexander Parker,
Gilbert Latey, and Francis Camfield, and read distinctly to the king and the duke,
in the presence of many more of the nobility, by me.

"`After I had read it to the king,`" he continues, "`our ancient friend,
Francis Camfield, declared a few words very weightily,
reminding him of the mercy of the great God to him, both in his great deliverances,
preservation, and restoration; desiring, that,
as the Almighty had shown mercy and compassion to him in his afflictions and straights,
he would extend mercy and compassion to his afflicted people;
and withal prayed for the king--to which the king said, '`I thank you.`'`"

He adds,
that the king at that time appeared seriously
affected with the sufferings of the friends,
and that he said to one of the noblemen who stood by,
"`What shall we do for these people; the prisons are filled with them?`"
But the person to whom he addressed himself, in order to draw him from the subject,
and to divert him from his concern therein, led him into other discourse.
