== Concluding Address To the Society of Friends

And thus having ended the proposed task of exemplifying the obedience which is of faith,
the labours of the writer of these pages, might perhaps, conclude.
But she feels that a further service is required of her, from which,
however she might desire it, she cannot conscientiously be exonerated.

It is in simplicity, and as she humbly trusts, in a measure of godly sincerity,
to urge upon you, who are the descendants of these witnesses of the Lord,
and who profess the same principle of truth as that by which they
glorified God,--to consider the immense responsibility which attaches
to your walk and conversation before your fellow-creatures.
Let other religious professors be what they may, let their habits,
whether of business or of pleasure, of public or of domestic life,
manifest what spirit they will--you are called, and loudly called,
to be a marked and separate people;
and that not by a system of peculiarities and a rigid
attachment to singularities and distinctions,
in which it is obvious, that the most insincere can vie with the greatest saint;
not by the most rigid faithfulness to any and all of these,
will your requirements be fulfilled--but by the display of that "`banner of
the Lord,`" which your holy forefathers carried so nobly,
and which they transmitted as a sacred trust to you.
It is by the unfurling of this ensign,
with "`holiness to the Lord`" engraved on every part of
it--and by being "`living epistles of Christ,
known and read of all men`"----that you are to evince the illustrious stock from
whence you are derived;--illustrious in that true nobility which comes from God.

"`What is it,`" says one of those truly illustrious ones,^
footnote:[Isaac Penington.--See his Epistle to Friends,
vol. ii p. 645, of his [.book-title]#Works#, in two vols.]
--"`What is it to have a distinct name,
or distinct meetings from the world, unless the power of the Lord be felt in your hearts,
and his presence in your assemblies?`"
What is it indeed, but setting up a broader mark than common,
for the profane scoffer at all religion, to shoot his arrows at?
For what, (it may, and it ought to be asked,) do these distinctions denote?
Is it not the profession of something deeper, something more real, more influential,
more solemn, more divine, more spiritual and interior,
than the generality of religionists profess?--Is it not
that which your honest ancestors well called truth?
that glorious principle for which they suffered,
and for which some of them were content to die?
The external nature of formularies, and an adhesion to the letter of scripture,
with the aid of this and the other man`'s notions about such things,
may greatly contribute to keep the generality of persons at
ease in a low and worldly profession of Christianity.
But you can find no such comfort in your mode of faith; since "`one is your master,
even Christ--Christ the light of the world-- Christ within, the hope of glory.`"
He will not flatter nor deceive you--he will give you
no forced or false construction of your case.
If, as your professed principle directs,--you come
to him and to his light in your consciences,
he will show you how and where you stand; and remember, that if you do not come to him,
as your living and ever-present teacher, dwelling and speaking to you in your hearts,
you do not come to that which, as it forms the glory,
so it forms the life of your profession of religion.
Wherein do ye differ from others?
Surely in nothing but in eccentricity, it might justly be replied,
if this were not your obvious distinction;--that,
whilst the greater part of religious professors are but
gazing at the letter which describes truth;
you seek after, and endeavour to walk by the powerful,
internal guidance of the thing itself.

This then,
is to be your glorious peculiarity,-- that you are men and
women of Truth!--Whilst many who name the name of Christ,
so far from departing from iniquity,
have it written in living characters upon all their transactions;
whilst they are known and despised as cunning and overreaching in
commercial dealings--subtle and deceitful in daily intercourse--
worshippers of money --watchers for self-advancement,
and in all things proving that the advantages of this world, are the "`gods many,
and lords many`" of their genuine devotion;--whilst this, we say,
is their condition-- you are to be separated in heart and life,
from all such defilements;--casting them from you to the moles and to the bats.

Suppose it be the degrading era, when commerce best thrives,
where conscience truckles most to the corruptions of
mankind;--suppose the day--the awful day,
be come, "`when no man can buy or sell,
save he that hath the mark or the name of the beast in his right hand;`"--still,
with the holy patriarch, every individual amongst you should be able to say,
"`my righteousness I hold fast, and will not let it go;
my heart shall not reproach me so long as I live.`"

But I feel compelled to pause,
and ask if it be needful to make to you this earnest appeal--to you,
whose membership is in a society, respecting which,
an individual could once thus nobly testify?

"`This light,`" he says, "`teacheth not to covet,
not to desire earthly dignities or estates.
Let it be looked at over England; which of us, so much as mind these things?
Nay, the Lord knows,
that the love of these things is daily rooted out of our hearts more and more,
and we are a people whom the world cannot charge with covetousness or love of the world,
wherewith all sorts of professors hitherto have been too justly chargeable.`"^
footnote:[Isaac Penington, vol i. p. 302 of his [.book-title]#Works#.]

Oh, friends! if in the least measure,
a mightier hand than that frail one which traces these lines,
should thereby knock at the door of your hearts, and ask if all be well there;--if,
"`in the cool of the day,`" that still small voice,
which spoke in love and consolation to your fathers, pleads somewhat sorrowfully,
and as it may be, in this wise, speaking unto you; "`I remember thee,
the kindness of thy youth, the love of thine espousals,
when thou wentest after me in the wilderness,
in a land that was not sown--Israel was holiness unto the Lord,`" --if,
to this tender appeal, it might be added, "`but now they are gone far from, me,
and have walked after vanity, and are become vain`"--if such should be the case,--oh,
think once more,-- how solemn is the admonition!

No common trust was that consigned to you, no common principles--no common, notional,
outside religion.
It was a Reality--a life--and a ministration of life to those who received it?
Where is it then?--for be assured,
that God will require it at your hands?--Where is the
true gospel message that was left with you?
for this was the message which was declared unto you, that "`God is light,
and in him is no darkness at all.`"
If any come amongst you, seeking for the declaration of this gospel-message,
do they find your ministers breaking that bread of life to hungry souls,
which their predecessors in the Master`'s vineyard dealt out so freely?
Suppose the case, that some wounded, wandering sheep,
who had long gone astray in the wilderness, asking its way to the true fold,
first of one hireling, and then of another, should meet, in its distress,
with the living ministrations of one of your forefathers;
which flowing as they did from the same spirit that gave forth the scriptures,
caused scripture itself to be understood by this inquirer,
as it never was before--suppose such an one as this to say,
"`Here is the ministry of Christ!--here is his true
apostle telling me where to seek for my beloved!--Oh,
here is indeed a '`feeder of the flock`'--a faithful
overseer!--Here I am met with bread--not with the dry,
hard stones of words and notions;--here I am turned to the life within--the light
within --and not drawn out into a labyrinth of confused conceptions about it.
Let me join myself to the people who are thus taught--and who are
walking by the counsels of this living and ever-present Teacher.`"
Suppose, I say,
such an one to come into your assemblies:--does he find
this peculiar feature of your professed principle,
and of your ancestor`'s ministry, distinctly exhibited, and livingly enforced?
I ask again,
does he find the peculiar excellence and truth of an inward revelation of
Christ the light of life,--a Redeemer working redemption within,
which formed the unvarying and unceasing theme of the
ancient friends`' labours,-- continually declared,
its power testified to,--and the way to experience it explained?--or does he find that,
commonly, and with very rare exceptions, the declarations of your ministers,
are as lifeless, as outward, as doctrinal, as notional, and as profitless,
(in so far as respects the turning persons to the living and true Redeemer and Teacher,
in their own souls,) as the effusions of those who openly profess the
letter of scripture to be their only safe and sufficient guide?

Permit me also to suppose the case yet further.
If such an one as this, warmed with affectionate esteem for the memory of the just,
grateful for the binding up of many wounds,
the strengthening of much weakness--and in humility,
hoping also the guiding into much good, from the faithful, precious,
and sincere example of your predecessors-- if such an one as this, I say,
should turn an inquiring look upon you as their descendants and proper representatives;
does he find you honouring their memory,
not merely by an outward adherence to visible distinctions, but by that inward,
spiritual, and vital separation from all evil, that holy scorn of a vain, proud,
covetous, money-loving, worldly spirit,
which marked them as a people whom God had set apart for himself?

Believe me,
it is no light or superficial feeling that prompts me
to submit these queries to your consideration;
for if he that converteth a sinner from the error of his ways,
does a great and faithful service to the Lord;
he that in any wise casts a stumbling-block in a brother`'s way,
hath need to pause in time, and see that he discover and remove it.

I say not that such is your case--I only say, that, considering how great and glorious,
in respect to the work of God, were the services and example of your predecessors;
how influential and important their ministrations in life and power,
and especially in preaching that wherein alone life and power consists,
or can ever be found;
even in an abiding acquaintance with "`the true light which
enlighteneth every man that cometh into the world,`"--it
behooves you to see that the talent entrusted to you,
is not "`laid up in a napkin`"--neither that you
dig in the earth after the gold that perisheth,
and thereby hide your Lord`'s money.

One word of affectionate and humble suggestion yet remains upon my spirit,
to offer to the single-minded and upright among you,
of whom I doubt not but there are many.
Dear friends, and honourable descendants of those who "`have been succourers of many,
and of myself also,`" suffer the word of exhortation,
upon a point wherein it seems to me you are in some danger; especially you who,
in early life, are called to minister in holy things.
It is that of mixing up the pure, distinct,
interior principle of faith in the gift of God, as an invisible and spiritual thing,
only to be known, apprehended, believed in, felt, and obeyed,
by the inward senses of the new-born creature-- I say, it is to be feared,
that you occasionally mix and confound this precious, living thing, with the notional,
historical knowledge, which is to be picked up from the letter that describes it.
If such be the case, you can never hope, whilst it continues,
to meet with full acceptance at your Master`'s hands.
He will have no clipping and paring down of his message.
No trimming to suit the religious taste of the times.
Remember that it was the marked distinction of the mystery from the history
and the vast difference between the birth of Christ in the heart,
to mere words and doctrines about it,
which formed the whole of the Christianity preached by the primitive friends; as,
in point of fact, it forms the whole truth of the matter; just as the living man,
and not his picture, forms the reality of his existence.

You must not suffer yourselves to be deluded
with an idea that you are living in better times,
as to religion, than your forefathers;
and that the apostasy of which they spoke so frequently, and so forcibly,
exists no longer; for assuredly, it exists in far greater strength of life than ever.
In their times it was not the fashion to be religious; knowledge was more circumscribed;
whilst the want of toleration in those who were at the helm of affairs,
subjecting conscientious persons to the fiery ordeal of severe persecution,
dissent to the authorized and national mode of worship,
was then generally the result of deep conviction.
But it is not so now--"`Many run to and fro,
and knowledge is increased;`" but with respect to that
religion which your ancestors preached and lived,
and by the strength of which they were more than conquerors over all
their foes both inward and outward--where is it to be found?
With most other religious professors beside yourselves, it has always been,
as truth commonly is, a despised and rejected thing.
So clearly does all experience confirm the disaffection of mankind for truth,
that we might well doubt the value of those religious principles,
that met with no opposers.

Take heed then, dear friends, that you slide not insensibly into the religion of the day.
Beware of outwardness in your ministrations.
All the world are now worshipping in the outward court;
but your profession calls upon you to "`measure the temple of God, and the altar,
and them that worship within.

"`But the court that is without the temple, leave out, and measure it not;
for it is given unto the Gentiles.`"
(Rev. 11:1-2) With them let it remain,
and "`let the dead bury their dead;`" but come ye forth in the strength of the Lord,
to fight his battles.

Oh there is much for you to do,
and much for every honest-hearted man and woman in the land to do; and that,
not by attacking the enemy only in his open and visible camp of vice and abomination;
for these are not now his most important strongholds.
When there, we see and know what he is about;
but he now sits enthroned where we neither see nor suspect his presence;
and our eye must be opened of the Lord,
and our arm strengthened to resist him with a double
portion of the spirit of holiness and power,
if we hope to conquer him now.
In a word, he has clothed himself with the mantle of religion.
He has laid aside for awhile the character of "`the roaring
lion going about seeking whom he may devour;`" for he has
found out something in these intellectual times,
which better answers his purpose.
Satan is now the theologist.

Every thing favours his assumption of this character.
There is no fiery ordeal of persecution to try the
power of the spirits that are "`up and doing.`"
And where is the appointed and proper antagonist of the serpent?
Where is the living spirit of the living God?
Where is he who, in Elijah of old, troubled the false Israel,
and who separated between the worshippers of Baal and of God?
Alas! must it not be said that "`Ephraim hath mixed himself with the people?`"
Is not the pleasant plant of the Lord crushed under the
heavy weight of lifeless words and barren doctrines?
Is not the deliverer silenced, and the usurper,
who has assumed his likeness and stolen his sayings, set above him?
Is there not, with much variation in the description of it, yet virtually but one way,
and one faith, and that a letter-learned and an outside faith?
And is it not the work of the deceiver to keep it on
the outside and to imprison it in the letter?
Ah! doubt it not.
Doubt not but he,
(this subtle theologian) will furnish a religion for the religious world; doubt not,
but he will supply them with a plentiful store of external doctrine--an abundant
flow of letter-learning;--and an amplification of manuals of head-divinity.

It is his day--his triumphant day--though the darkest hour of
midnight upon the time church of God;--which sits,
indeed, "`like a pelican in the wilderness,
or like the lonely sparrow on the housetop,`" mourning for her beloved.

What doth that desolate widow see,
in all the pomp and paraphernalia of these imposing times?
What doth she hear in the din, and bustle, and talk about moral improvement?
What doth she feel,
when the way to the kingdom is made like the highways in the natural world,
of such railroad facility, that a man may hear, and read, and talk himself into it,
at pleasure?

Oh, doth she not say in the spirits of the faithful,
"`How is the gold become dim! how is the most fine gold changed! the
stones of the sanctuary are poured out in the top of every street?`"
And oh, especially, to you, ye children of "`her Nazarites,
who were purer than snow--whiter than milk--and whose
polishing was of sapphires`"--doth she not cry,
"`Awake--awake-- shake yourselves from the dust,--loose
yourselves from the bands of your neck,
ye captive children of Zion?`"

Doth she not say--"`Stand up and plead my cause!--be
valiant for the truth upon the earth?`"
Doth she not remind you that a cross is to be borne--a cross that gives
offence--even the cross of boldly testifying to the light within.
This is the stone of stumbling, and rock of offence.
Oh, beware that you pass it not by, as that with which you have nothing to do!
The faithful minister of truth must give offence, and if he gives it not,
he cannot give the truth of God.
"`If I yet pleased men,`" says Paul, "`I should not be the servant of Christ.`"
(Gal. 1:10) Beware then that you suffer not the
subtle serpent to beguile you with seducing words,
as though your ministry should be such as suits the fashion of the day.
Hearken not to him, when he fixes upon some roughness in the shell,
and so would cajole you to believe,
there was no soundness in the fruit your ancestors brought forth.
Rude and unpolished as to the outward, no doubt,
many of them were--but all glorious within, their clothing was of wrought gold,
in the eyes of him who "`is fairer than the children of men.`"

Yes, ye departed saints--ye spirits of the just made perfect,
how beautiful to the enlightened eye is your memorial!
Ye were God`'s building; and of that edifice which the Almighty rears,
how truly doth one amongst you thus express the character.^
footnote:[Isaac Penington.
See his [.book-title]#Letters#, published by J. Barclay, p. 84.]

"`Into thy holy building, O God! into thy heavenly building,
into the spiritual Jerusalem, which thou rearest and buildest up in the Spirit,
no unclean or defiled thing can enter;
nor is there any room there for that which loves and makes a lie!
Without, indeed, are swine and dogs, vulturous eyes, and crooked serpents,
who make a show of what they are not, and lay claim to that which belongs not to them.
But within are the children--within is the heavenly birth,
even the new creation of God in Christ Jesus.

"`For God doth not strip his people, and gather them out of the spirit of this world,
that they should be empty and desolate for ever; but he gathers them into,
and fills them with his own Spirit; fills them with light, fills them with life,
fills them with holiness, fills them with righteousness,
fills them with peace and joy in believing and obeying the gospel!

"`And in this Spirit is the kingdom known,
which is not of this world,--the inward kingdom -- the spiritual kingdom --
the everlasting kingdom!--where the everlasting throne is near,
and the everlasting power revealed! and the Lord God Omnipotent
reigns in the hearts of his! and other lords do not reign,
but their horns are broken--and the horn of God`'s Anointed exalted,
who sits ruling as king on his holy hill of Zion!--and they that have suffered with him,
and gone through great tribulation, do reign with him--blessed be his name for ever!
Amen!`"

Such, dear friends,
was the testimony of one who had been a workman in the raising of
this holy edifice--"`a workman that needed not to be ashamed.`"
Oh that the same Holy Spirit which spoke and taught in him, may rest upon you;
and that in this day of outwardness of observation--and cry of lo
here! and lo there! you may be found faithful--giving forth that,
and that only which you have received, and that not of man,
nor by any of the natural workings of your own minds;
"`but by the revelation of Jesus Christ!`"

[.the-end]
Finis
