== Chapter VI. The Tangled Skein of Silk.

One of Miss Robson`'s rules with her young people was, that "`whatever was begun by them,
was to be finished.`"
This was a rule which bore very hard upon the restless,
impatient spirits of Harriet and Charlotte,
and was not sometimes exercised without bringing a trial also upon Gertrude,
as I shall have occasion to show you in the history of a skein of silk,
which she was one day beginning to wind, and which she asked Charlotte to hold for her.

Charlotte consented, on condition that she might wind, instead of hold it,
which was readily granted by Gertrude,
and they entered upon their occupation with much cheerfulness, and the more so,
as a shower of rain had hastily come on, which prevented their going out,
as they usually did when school was over.

"`Oh, this is so nice,`" said Charlotte.
I delight in winding silk or cotton--`"

Scarcely had she made the remark, when some unexpected knot in the silk,
which a little patience would have soon set to rights, began to try her temper,
and caused her to twitch it this way, and that way, till she had so entangled it,
that it really did require, not merely more patience, but also more wisdom,
than Charlotte was possessed of, to extricate it from confusion.

Poor Gertrude saw with alarm the perilous condition of her property; for,
unable to proceed, Charlotte seized upon a pair of scissors which were on the table,
and was going to cut the knots which she could not unravel.

Oh, Charlotte dear, pray do not do so!`" said Gertrude, "`if you will hold it,
I will try and undo the knots.`"

"`__You__ undo them,`" replied Charlotte rather scornfully, for, to say the truth,
she was getting so angry that she wanted something to wreak her vexation upon,
and therefore was too much disposed to let it fall upon Gertrude.
"`__You__ undo them, indeed!
I think little Johnny could undo them as well.`"

It was always so much easier for Gertrude to bear ill temper, than to reply to it,
that she said nothing to this taunt,
and was on the point of submitting to the determination of Charlotte to cut the silk,
when the door opened, and Miss Robson came into the room.

There was an end now of Charlotte`'s intended work of destruction;
for this was an occasion in which she felt assured she should have an opportunity
of learning that she must pay obedience to the rule of her governess,
that whatever her pupils began, they were required to finish.

"`You seem to have made sad work with that skein of silk,`" said Miss Robson;
"`bring it to me, and let me see if I can help you;`" and she took her seat.

"`Gertrude, do you hold it,`" said Charlotte, we cannot both of us, you know.`"

"`Yes, you can,`" said Miss Robson; "`come, and stand by me,
and I will give you directions what to do; at least, to the one who winds.
The other is only required to hold her hands still.`"

If it had been any one but Miss Robson that Charlotte had at this moment to deal with,
she would certainly have rebelled, and refused to proceed in her occupation,
which was far enough from being one of which she could now say, as she did just before,
that she delighted in it.
But there was a something that ruled in Miss Robson, which made itself be felt,
and that without words.

It was not, however, without great uneasiness, even to tears,
that Charlotte brought up to her governess the tangled skein,
as she was desired,--neither could she refrain from saying, "`I shall wait, another time,
before I offer my services in winding a skein of silk;`" which ungracious
remark she accompanied with a look equally ungracious towards Gertrude.

"`I thought you said just now, dear Charlotte,
that you delighted in winding silk or cotton;
if I had thought it was disagreeable to you,
I would not have asked you to do it,`" said Gertrude.

"`Charlotte is like most young persons,`" replied Miss Robson,
"`she delights in things whilst they are agreeable.
But the true way to be happy, Charlotte,
is to delight in them when they are disagreeable.`"

"`I do not think any body can do that,`" said Charlotte.`"

"`Not, at the time, I grant,`" said Miss Robson.
"`Nobody can delight in disagreeable things when they are felt to be so;
but there is a something which can only be obtained when things are disagreeable,
which it is our interest to delight in.
Can you guess what that is?`"

Charlotte stood with the tangled skein hanging on her hands, and,
either unable or unwilling to answer the question,
began to employ herself in trying to find the right end of the silk,
in doing which she was only tangling it still more.

"`I believe you are not likely to benefit much by the subject before us this morning,
Charlotte,`" said Miss Robson,
or else I would say that you have now an opportunity of solving my meaning,
and knowing for yourself that there is a delight
to be found in things when they are disagreeable,
which can be found at no other time, and in no other way.
But, as the shower is over,
you can put on your things and join your sister in the garden;
and Gertrude and I will try and discover what was the delight I meant.`"

In saying this,
Miss Robson was about to take off the tangled skein from Charlotte`'s hands,
but the little girl, with subdued and altered feelings,
and tears in her eyes that had a better source than
those which filled them but a few minutes before,
begged to be allowed to remain,
and to share with Gertrude in the lesson that was to be imparted.

Permission to do so was readily granted by her governess; who,
having placed Charlotte as the winder of the silk,
in the most advantageous situation for receiving her instructions,
proceeded to give them; prefacing what she had to advise,
by reminding the little girls that they would want
a great deal of patience to get through their task.

"`Ah! now I know,`" said Gertrude, with a smile;
"`now I know what that thing is which we should delight in,
and which is only to be found when things are disagreeable.`"

"`And so do I, too,`" said Charlotte, smiling also.
"`It is _patience_ that Miss Robson means.

"`Well,
let us see if we can find any of this precious thing
in our present occupation,`" she replied.
"`Hold your hands out as straight and as still as you can, Gertrude;
you must not mind your arms aching a little,`" said she; "`and now, Charlotte,
let us begin.
Observe, you must pass the card of silk under that thread--mind, that thread;--there.`"

The order was obeyed, and some little advance made;
but the passing of the card in a particular direction had to occur at every round,
and Charlotte had scarcely ever experienced any thing so exceedingly trying.
For the first two or three times, she sighed heavily, as she came round to the obstacle;
but Miss Robson cheered her with repeating,
"`A little longer--only a little longer,`"--and,
ashamed that Gertrude should outdo her in the matter,
by exhibiting more patience and perseverance than she did,
she made great efforts to restrain her spirit, and so far succeeded,
that at length the silk was fairly and safely wound, without any detriment to it.

"`Well now, that really is delightful!`" said Gertrude,
"`though my arms did ache very sadly,
and it was once or twice almost as much as I could do,
not to ask to rest a little while.`"

"`But you are very glad now, I dare say, that you persevered; are you not?`"
inquired Miss Robson.

"`That I am,`" said Gertrude.
I am glad on two accounts, I am glad I did not spoil my silk by cutting it;
and I am very glad to have learnt what a delightful thing patience is.`"

Charlotte.--And so am I, I can feel now that there is a great pleasure in it.
But, Miss Robson, is there no way of learning patience, except by bearing, or doing,
disagreeable things?

Miss Robson.--I shall answer your question by asking you one, Charlotte; and it is this.
What is patience?

Charlotte.--(after a little pause.)--I think it is looking
contented and happy when you are ready to cry;
and being still and quiet, when you feel a wish to break everything to pieces.

Miss Robson.--I suppose you are giving me a description
of what was passing in your own mind,
whilst winding the silk.
Well, it must surely be a delightful and a desirable thing,
which can deliver any human being from such outrageous
and degrading conduct as you have made mention of;
and I dare say you think so.
Do you not feel very glad that you did not expose yourself, either by crying,
or cutting the silk to pieces?
Do you not enjoy the calmness you now experience, and can you not see, at a glance,
what a poor, childish, contemptible creature you would have appeared, if,
instead of standing there so serene and smiling, with the silk neatly wound upon a card,
you had exhibited yourself with the silk cut into shreds,
to Gertrude`'s loss and mortification, and yourself sobbing like a baby.

Charlotte.--Oh yes,
Miss Robson--I cannot bear to think of it.
I shall always love disagreeable things, if they teach me any thing so good as patience.
But I don`'t see quite, just yet, why I cannot learn it in a less unpleasant manner.

Miss Robson.--What do you think about that, Gertrude?

Gertrude.--I don`'t think we can want patience when things are pleasant and agreeable.
Suppose the silk had gone on as pleasantly, you know, Charlotte, as when you said, "`Oh,
this is so nice!`"
I don`'t see what occasion we should have had to be impatient about it.

Charlotte was obliged to confess that this was forcible reasoning,
and to admit that patience was only to be learned at a time
when things were going contrary to our wishes;
or, as she had expressed it, when they were disagreeable.

Miss Robson.--I think, then, I have made out my case;
and proved that it is our interest to delight in things when they are disagreeable.

Charlotte.--I certainly never felt the sort of pleasure I now feel,
in having conquered my impatience about this skein of silk.
But then, Miss Robson,
that seems such a little thing either to be troubled or to rejoice about.

Miss Robson.--As little as it is, you see, Charlotte,
that it was almost too much for you to bear.
You must not fall into the error which people so commonly do fall into,
of talking about this or the other matter as a little thing.
Nothing is so little as not to produce some consequences;
and whatever is of a kind to excite your feelings, and try your temper,
is a very important thing, however trifling it may seem to you.
But your mistake, and the general mistake in talking in this way,
arises from looking at the outward thing or action;
and not at the inward temper and feelings which accompany it.
As, for instance, on the present occasion;
winding a skein of silk is a very insignificant thing,
and might be done without its being necessary to say six words respecting it.
But, being hasty and impatient, and fretful and injurious,
as you were about to be in doing this simple thing, are very serious matters,
and must be encountered in a very serious way.
So serious are they, indeed, my dear child,
that I know of but one method to propose to you of avoiding to be their victim,
and that is by remembering that whatever you do, you are to do it as unto the Lord,
and not as unto man.
The thought that this or the other thing is a trifle,
will never help you to bear it with the right patience.

Gertrude.--Are there two sorts of patience, then, Miss Robson?

Miss Robson.--There is a kind of false patience, Gertrude,
which often enables people to control their feelings, so that, upon trying occasions,
they shall seem to those around them to possess a great deal of self-command and fortitude.
This does not deserve to be called by the name of patience, for patience is a holy thing.

Charlotte.--What is the name of this false patience, Miss Robson?

Miss Robson.--Its name is PRIDE.
Do you know any thing about it?

Charlotte.--What way does it show itself?

Miss Robson.--It feels as if it would rather die than seem to be troubled.
Hence, as you said just now,
it tries to _look_ contented and happy when it is ready to cry;
and it is still and quiet when it feels a wish to break everything to pieces.

Charlotte.--I`'m afraid I was feeling some of this false patience, then;
for I certainly was very unwilling to seem troubled,
and I did not at all like that Gertrude should show more patience than I did.

Miss Robson.--It is very likely, my dear,
that pride had more to do with your perseverance than patience had.
There must be a deep feeling of the presence of God in the heart,
before we are able to perform all our actions as in His sight,
and in every trial of our spirits to breathe a desire for His help and favour.
Yet, most certain is it, that nothing of the true patience can be found,
except as bestowed by Him: for patience, I must once more observe to you,
is a holy thing; and as you will often require to be reminded of its value,
I will repeat to you some lines written by a friend of mine, of which, if you like them,
I will give you a copy, and then you can learn them by heart.

Both the little girls requested to hear them,
and Miss Robson then recited the following address:

TO PATIENCE.

Meek and submissive Patience! born in woe,

Yet smiling through thy tears; how soft and low,

And tranquil is thy presence!
Modest Grace!

How humble are the scenes where thy pale face

Unveils its pensive beauty!
Deep the cup

Of bitterness thou calmly drinkest up!

For welcome is it to thy loving heart

In pain and grief to take the largest part;

And sweetly doth thy gentle spirit share

In what thy Master giveth thee to bear

Of his sad portion!
Oh, Thou Holy One,

Whose latest sigh breathed forth "`Thy will be done!`"

And with that sigh expired for lost mankind,

Let my tried soul thy holy patience find!
