== Chapter VII. An Advance in the Narrative.

I shall not detain you, my young readers,
with a detail of the various circumstances and events which
occurred in Mr. Allen`'s family during the next two years.
It seems a long interval;
and perhaps you may think that something sufficiently interesting
to be related must have taken place whilst it was rolling away;
and I could, no doubt, make a book, and a pretty large one,
were I to proceed as I have begun,
and relate to you the different little matters that
transpired between the children and their governess,
and the other members of the family, for the space of two years.

But I have some other things to treat of; and must, therefore,
content myself with informing you, in a general way,
that Harriet and Charlotte were very much improved;
that Johnny was grown into a stout little fellow, running about the house,
and chattering to any body who had time to listen to him; and that Mr. and Mrs.
Allen, and Miss Robson, were in all respects,
(with the exception of being two years older,) pretty
much the same as you have ever known them to be.
"`But what of Gertrude?`"
methinks I hear you say.
"`How is it that you tell us nothing of her?`"

We are generally unwilling to communicate, or to hear,
what may be considered as melancholy intelligence;
and therefore I have been slow to tell you,
that matters have not been so unmixed with sorrow to Gertrude
as to the rest of the inhabitants of the Rectory.

I have already hinted to you that she was of delicate health;
and her naturally weak constitution had received a severe shock from a fever which,
in the past winter, had attacked most of the family,
but from which all the other members of it had recovered.
This fever had left on Gertrude a spinal complaint,
which required her to remain constantly in a reclining position,
and several months had now elapsed,
during which the poor little girl had only been moved
from her bed to a couch placed for her in the nursery.
Under these circumstances, of course,
there was an end to the school lessons she used to share with Harriet and Charlotte.

But although she was no longer a scholar to Miss Robson,
there was a school in which this dear child was taking some very precious lessons;
and that was, in the school of Christ.
Here she was daily learning what can only be learned of that Divine Master.
She was learning to suffer pain, and wearisomeness, and solitude, with patience;
she was learning to delight in the Holy Scriptures, which she loved to read;
and above all, she was learning to meditate upon, and pray to that blessed Saviour,
through whom she felt confidence to approach unto God, as her Father and her Friend.
You will suppose that she could now find a use for
the poetry with which we concluded the last chapter.
Indeed, she often wanted whatever had a tendency to strengthen patience,
and therefore delighted in frequently repeating it.

Nor was the benefit of her affliction con fined to herself;
for her young friends observing the calm and quiet constancy with which
she accustomed herself to bear the many privations that attended her case,
were very desirous to emulate so good an example; and would often,
when on the point of being "`overcome of evil,`" be prevailed upon
by their governess to accompany her to the couch of Gertrude,
and, in her placid smile and look of welcome,
were constrained to see so lively a picture of the beauty of a
"`meek and quiet spirit,`" and to contrast it with what was sometimes
the ugliness of their own fierce and violent tempers,
that, as Mr. Allen said, "`she proved a dear little teacher,
whose very silence preached an instructive sermon.`"

We all want those lessons which affliction, and affliction alone can teach us;
and more especially, we want them in early youth, when the spirits are high,
and when pain and sorrow are seldom experienced.
It is because they scarcely know any thing of suffering themselves,
that children and young persons are sometimes apt
to give way to a selfish feeling of dissatisfaction,
when the illness and suffering of their parents or others brings restraint upon them.
This was the case with Harriet Allen, one day, in respect to Gertrude; who,
after being so much better the preceding evening,
as to give hope of her being able in a short time
to be removed downstairs into the parlour,
was on the next day so much worse, that,
instead of indulging any expectations of this kind,
there was increased reason for fearing that she would never quit her room any more.

Now, Harriet was a fine sensible girl, and, as I have told you,
very much improved under the judicious tuition of Miss Robson;
neither was she wanting in affectionate feelings, but, upon the whole,
was very amiable in her conduct towards the poor little invalid.
However, she had naturally such high spirits,
and such a dislike of everything that was dull, (as a sick chamber must, no doubt,
be thought by those who do not entirely know the value of it,) that it was, sometimes,
an exercise to her better feelings to show the tenderness and consideration
which the trying circumstances of Gertrude made her due.

Full of hope at the improved state of her young friend`'s health for several days previous,
and especially the preceding evening,
she ran to her room as soon as she was dressed the next morning,
not so much to inquire how Gertrude was,
as to tell her all the pleasant things she had planned
to amuse her when she came downstairs.
Wholly unprepared for disappointment, she was not only surprised, but also angry,
to find her hasty entrance into the room checked by Sarah`'s uplifted finger,
and her gently exclaiming, "`hush! hush!`"

"`There now, Miss Harriet, you have woke her!`" said Sarah, with much vexation,
as Gertrude, moaning with pain, opened her eyes,
evidently disturbed by Harriet`'s opening the door.

"`Dear me!
I expected to find you on the couch in the nursery, and not in bed,`" said she,
addressing Gertrude; "`I thought last night you were almost well?`"

"`She is far enough from that,`" said Sarah, "`poor little thing I and I wish,
Miss Harriet, you wouldn`'t come bursting into the room in that way;
waking her out of the first hour`'s sleep she has had since two o`'clock this morning.`"

"`Grievous words stir up anger;`" and these were
felt to be exceedingly grievous by Harriet.

"`I wish you would know who you speak to,`" said she, in much anger,
and venting some of the many uncomfortable feelings
that weighed upon her spirit in attacking Sarah;
"`I am sure mamma would never approve of your taking
me to task in that impertinent manner.`"

Well, I`'m not going to make a disturbance,`" said Sarah;
"`if you had any proper feeling, I think you wouldn`'t be wrangling here,
to vex the poor little suffering girl.

Scarcely any thing makes selfish people so angry as to be accused of want of feeling;
and Harriet still went on murmuring at Sarah`'s ill behaviour to her,
till the poor little invalid, too weak to interpose,
and too much exhausted with pain to support her noise, burst into a flood of tears.

This put the finishing stroke to Sarah`'s patience; which, in truth,
had been sorely tried by the unfeeling behaviour of Harriet,
both towards herself and her little charge; and, without more ado,
taking her by the shoulder, she quietly put her out of the room; saying, as she did so,
"`It does not signify talking, Miss Harriet, whether you are affronted or not,
you shall not stay here to make this noise.`"

What an affront upon the dignity of a girl in her fourteenth year!
What was to be done!
Tamely pass it by?
No, that she would not.
No, that she never would!
Such were the thoughts which occupied the mind of
Harriet as she walked into the breakfast parlour,
which, from its being earlier than the usual hour of assembling there,
she expected she should find empty.
But she was mistaken; her papa sat in his usual seat, with the Bible before him,
from which he was reading.

It was customary with the children,
on first seeing their father and mother in the morning,
and on parting with them at night, to go up and kiss them.
But Harriet`'s heart, at this moment, was little disposed for any testimony of affection.
Such is the sad consequence of indulging evil feelings!
As has been remarked by a great poet, on another occasion,

"`They come not single spies, but in battalions.`"

Mr. Allen turned his head on hearing the door open, and, seeing Harriet,
extended his hand, though still continuing his eye upon the book, as he said,
"`Good morning, my dear.`"

Harriet came up and kissed his cheek, as usual,
when she gave him the salutation for the day; but scarcely spoke loud enough to be heard.

"`Poor little Gertrude is not so well again,
I find,`" said he still turning over the leaves,
as if looking for some particular verse or chapter.
It was happy for Harriet that his attention was thus occupied,
and that he did not see the tumultuous expression of her face, as she replied,
"`She never keeps well long together, I think, papa.`"

"`Poor little girl!`" he replied, "`she is greatly tried; but she is a sweet,
patient child.
A dear little saint;`" he continued, with his eye still upon the book,
and speaking rather as if he were remarking something to himself,
than addressing another.
Another opening of the door, brought Charlotte into the room,
and again occasioned him to turn his head.
Having also, like Harriet, given and received the usual greeting,
Charlotte went to the window, over the seat of which Harriet was leaning,
apparently occupied in looking into the garden; Charlotte,
unconscious of the storm that was working in her poor sister`'s bosom,
went bounding towards her, and,
perhaps a little more roughly than might be quite agreeable,
put her hand on her shoulder, to help herself towards the window seat,
in order to look into the garden also.

"`How can you be so disagreeable, Charlotte,`" exclaimed Harriet;
"`I declare you have torn my frock with your violence.`"

Poor Harriet!
She did not at that moment know where the most dangerous violence existed;
and what far more precious thing than her frock was then its victim!

"`I tear your frock!`" replied Charlotte, whose temper,
in no degree more mild than her sister`'s, resented this rough, and,
as far as appeared from the absence of any visible fracture in the frock,
also unjust attack upon her, "`I`'m sure I have not hurt your frock.`"

"`Subdued as was the tone of these angry words,
it nevertheless reached the ears of their father,
who inquired of them what was the matter.

Neither of them at first gave any answer; but when he proceeded to say,
that it was very sad to hear these bickerings between them,
and he had pleased himself in thinking that they had, in a great measure,
been enabled to subdue that evil in their hearts which occasioned such contentions;
Harriet began to excuse herself by saying,
that "`Charlotte was so violent--she was herself
only just looking out of the window quietly,
and she came upon her all at once, almost enough to push her down.`"

"`Oh, Harriet, that I`'m sure I didn`'t! Papa, I will just show you`"--

"`I don`'t want to be shown any thing more than what I see already,`" replied Mr. Allen;
"`I can see by Harriet`'s countenance that she is not in a good temper,
and therefore she would be likely to vent her uncomfortable feelings
upon the first thing or person that came in her way,
whom she could take liberties with.--Come here, Harriet,
come to me;`" and he extended his hand once more --and once more, with a softening,
rather than a softened heart, she went towards him.

"`What is it, now, that troubles you, my child,`" said this good father,
tenderly putting his arm round her; "`tell me what makes you unhappy,
for unhappy I see you are.`"

Without speaking, Harriet laid her head upon her father`'s shoulder, and wept bitterly;
whilst Charlotte, though scarcely knowing why, felt as if she must have cried also.

At last,
Harriet replied to the soothings and tender inquiries of her affectionate parent,
by telling him that it was a bad feeling of anger at Gertrude`'s relapse,
which had occasioned her to be selfish and unkind in her behaviour to her that morning.
She did not allude to the altercation which had taken place between her and Sarah,
but said, and with truth, that the uneasiness of her conscience,
in knowing that she had pained and disturbed Gertrude,
at a time when her bodily afflictions were so heavy, so vexed and irritated her,
that she was ready to quarrel with Charlotte only for touching her.

"`But I am very sorry,
Charlotte dear,`" she added.--She did not need to add more,--her sister ran towards her,
and, whilst his two dear girls embraced and forgave one another, their father,
with glistening eyes, folded his arms round both, and pressed them to his heart.

"`This is the balm for every wound, my children!`" he exclaimed.
"`This precious love!`"
He was silent a few moments, his head bowed down upon his hand.
At length he spoke again: "`It is a trial for you,`" he said,
"`it is a trial to all of us, to have long continued sickness brought to our door.
But who sends it us?`"
and he looked earnestly at them both, as he repeated, "`who sends it?`"

"`The Lord sends it,`" said Harriet thoughtfully, "`and we ought to bear it.`"

"`We should do more than merely bear it, my love,`" replied Mr. Allen;
"`we should make use of it as a blessed means of spiritual improvement.
Old as I am, I have got great good, and great instruction too,
out of poor Gertrude`'s affliction;`" and he smiled.

"`Oh, papa,`" said Charlotte, "`how much we should learn, then!`"

"`Well, I hope and believe that you do both learn a great deal.
You learn to be kind;--yes, yes, I have seen instances of it,
and seen them with pleasure and thankfulness.
It is at these trying times, that the good and the evil in all hearts appear; and if,
sometimes, an ugly weed is found among some pretty flowers,
what must we do but pluck them out?
Eh, my Harriet?`"

Harriet smiled her willing assent, and Mrs.
Allen and Miss Robson then entering the room, the rest of the family were summoned,
and Mr. Allen selected for the morning`'s reading the parable of the Good Samaritan.
When he came to the words, "`and who is my neighbour?`"
he paused a little, and then repeated "`who is my neighbour?
Observe,`" he went on to say,
"`observe the manner of our Lord`'s replying to this question.
Not with a wordy description,
which the empty inquisitive temper of the man he was addressing would have cavilled at,
and argued about, and probably disallowed to be a just description;
but by holding up a mirror to the man`'s conscience,
in which he might see what was the conduct that one
fellow creature ought to show towards another,
and in which he should also detect how far he himself came up to, or fell short of it.`"

Mr. Allen then proceeded to read the parable,
without making any comment till he had concluded it.
He then called the attention of his hearers to some thoughts,
which he said always presented themselves to his mind in
connection with this portion of Scripture.

"`I do not say,`" he remarked,
"`that it was our Lord`'s intention to represent our wretched condition as sinners,
assaulted and wounded by the malice of Satan and evil spirits,
into whose power we have fallen; I do not say,`" he continued,
"`that it was his intention to shadow this forth
by the man who goes down from Jerusalem to Jericho,
and falls among thieves; but this I am sure of,
that it is a very apt and striking figure of our real state.
We are surrounded with thieves, the worst of thieves, in our own evil passions.
If it were not for these traitors within the house,
the adversary would not find such an easy entrance upon us as he does.

"`And then, when they have beaten and wounded us,
and left us half dead--what happens next?
Does the right helper appear?
Alas, no!
The priest and the Levite, this individual, and the other, look on us;
but either they have no help to give,
or they view it as no business of theirs to meddle with us,
or they fear they may be involved in trouble if they do; or, for some cause or another,
they leave us to battle with our misery as well as we can, and take themselves out of it,
by passing by on the other side.
Ah, how like human nature is this conduct!
Truly indeed, are we told, that '`Jesus knew what was in man.`'

"`This selfish, cool,
determined way of passing on the other side of a fellow creature`'s distress,
and leaving it as a matter that we may get out of, if we like,
is a very common feature in the character of too many persons.
Indeed, I should say, that scarcely any person who was not, in his general conduct,
in the habit of acting as unto the Lord, and not as unto men,
but would be likely to possess it.
Selfishness is such a root and branch matter with us: no pruning will keep that under.
The axe must be laid to the root of the tree;
the sword of the Spirit must cut it in twain.

"`'`But a certain Samaritan, as he journeyed, came where he was.`'

"`Now this is remarkable, because the Samaritans were held in great contempt by the Jews,
insomuch that they would have no intercourse with them.
We have an instance of this in the astonishment expressed by the Samaritan woman,
that our Lord should speak to her.
'`How is it,`' said she, '`that thou, being a Jew,
askest drink of me which am a woman of Samaria?
for the Jews have no dealings with the Samaritans.`'

"`Wherefore, then, should this individual,
of a nation abhorred by those whom Jesus was addressing,
be selected by him as the representative of amiable and edifying conduct,
in preference to the priest and the Levite, whom, as the ministers of their religion,
they were accustomed to venerate and look up to?
To show us that God is no respecter of persons, but in every nation, he that feareth Him,
and worketh righteousness, is accepted of Him.`'

"`For this reason, as I conceive,
was the Samaritan chosen as the representative of that conduct, and those feelings,
which recommend a human being to the favour of God,
and the good will of his fellow creatures.

"`Let us, therefore, my dear children and people,
avoid all that narrow exclusiveness which looks wholly to self,
as the priest and the Levite did,
and which passes by on the other side of everything that may produce us trouble;
and let us fix upon our hearts and memories,
the sweet and sincere conduct of the Good Samaritan.
And on the morrow, when he departed, he took out twopence, and gave them to the host,
and said unto him, Take care of him; and whatsoever thou spendest more,
when I come again I will repay thee.`' How simple, how unostentatious!
How like a man who was doing his work as unto the Lord, and not as unto man!
How instructive, not only as to the act of kindness,
but as to the right way of performing it!
How many are the occasions in life, where such conduct is needed!
How lovely are those who practise it!
Ah, these are amongst the Lord`'s hidden ones; little known and less cared for;
for they are not to be found in the prominent places of the earth.
The sick chamber, the abodes of suffering,
and the valley of tears--these are their haunts.
There they pour in the oil and the wine, there they bind up the wounds,
there they pursue their Master`'s work in their Master`'s spirit,
contented to suffer and to share in the burdens of those who suffer;
for suffering was the portion of Jesus, and suffering is that of his followers.`'

"`Precious suffering!
How much it does for us which nothing else does!
How it melts, how it tenders the heart!
How it fertilizes every green and growing plant that the Heavenly Father has planted!
Therefore, my dear family, whatever you pass by,
never pass by an opportunity of sharing in the sorrows of your fellow creatures.
There is a nature, no doubt, in all of us, which resists sorrow, and would always,
if it could, be found in the enjoyment of whatever this world has to give of joy;
but this is a selfish, low, corrupt nature,
which has nothing in it of the dignity that belongs
to a renunciation of our own will and our own pleasure.
It has been well described by a lovely-spirited Christian^
footnote:[Madame Guyon.
See her Hymn entitled "`The Joy of the Cross,`" translated by Cowper.]
in these lines:

Self-love no grace in sorrow sees,

Consults her own peculiar ease,

`'Tis all the bliss she knows;

But nobler aims true love employ;

In self-denial is her joy,

In suffering her repose.`'

Mr. Allen then closed the sacred volume,
and concluded the morning`'s engagement with devout and earnest supplication,
that the Holy Spirit of Him whose nature and whose name is Love,
might open in all their hearts the lovely nature
and tempers of the Redeemer of the world.
