== Chapter VIII. Visitors.

From the period of Gertrude`'s relapse, alluded to in the last chapter,
she continued gradually declining,
insomuch that the medical man who attended her could give
no hope that she would ever recover from this long illness,
although he believed it possible that she might linger some time;
the nature of her complaint being usually slow in unfolding its results.

In order to alleviate her affliction with as much
variation of scene and circumstance as possible,
she had been brought down to a room on the ground floor,
from whence she was daily removed for a longer or shorter time,
as she was able to bear it, into the family apartment, where she reclined upon the sofa,
peaceful and happy, and, though seldom able to bear much conversation,
yet pleased to be amongst those whom she so dearly loved,
and who had an equal affection for her.
Every member of the family sedulously endeavoured to do
what could be done for her comfort and gratification;
and none more than Mrs.
Allen, who was a very tender-hearted woman, and, as I have before told you,
rather apt to indulge young people too much.

Her great solicitude to cheer and amuse Gertrude occasionally induced her to
manifest it in a way which the poor child would willingly have excused;
for, naturally timid and shy as she was at all times, she now, more than ever,
shrunk from the presence of strangers; but kind Mrs.
Allen (for she meant nothing but kindness) was not aware of this; and therefore,
sometimes, when she thought to please her,
by asking this and the other person into her apartment, she, in fact,
was the means of occasioning her much discomfort.

One evening, when Mr. Allen, Miss Robson, and the rest of the family,
were out of the way, a lady of the name of Thomson and her daughter,
called at the Rectory.
They were not unknown to Gertrude; and on expressing a wish to see her,
they were taken by Mrs.
Allen into her bed-room; for, having been more indisposed than usual that day,
she had not been brought into the sitting-room.

Now, it so happened,
that if there were any persons more than others whom she particularly
wished to avoid having to see and discourse with,
it was Mrs.
Thomson and her daughter.
I dare say you will like to know why?
I must just whisper in your ear, then, dear young friends, that Mrs.
Thomson was a person who rather too much loved the world and the things of the world,
even though she talked a great deal about the things of God; indeed,
she talked so much and so well, on religious subjects, that many persons, (and Mrs.
Allen among the rest,) considered her conversation very edifying and instructive.
Her daughter Laura also, who was about fifteen, had learnt to copy her mamma`'s phrases,
as well as many other of her mamma`'s fashions,
and consequently was as vain and superficial as most young persons are who imitate,
not what is good, but what their vain mind thinks pretty and becoming in their elders.
This sort of imitation, ridiculous as it was, had not that offensiveness in it,
which accompanied Laura`'s adoption of her mother`'s religious mode of discourse;
and it was a secret distaste to that, which made Gertrude shrink,
when the elder ladies having retired, Laura took a chair by the side of her bed,
and said she wished for a little profitable conversation with her.

"`I trust, my dear,`" she began by saying,
"`I trust you find your mind in a happy state.`"

"`Very!`" replied Gertrude.
"`You experience the promises of the Gospel to be precious to you, I make no doubt?`"

Gertrude was entirely silent to this indirect question, and after a few moments,
Miss Thomson repeated it in such a tone as seemed to demand an answer.

But Gertrude was still silent; and the young lady,
mistaking her reserve for ignorance and darkness of mind,
proceeded to administer such instructions as she thought suitable,
concluding her observations and counsel, with some remarks upon the vanity of the world,
and the preferableness of going to the house of mourning rather than the house of feasting;
which would have been very just,
and very becoming even in the mouth of a girl of fifteen,
if there had been ground to believe that they came from her heart; but,
in the present case, this was, to say the least of it, very doubtful; and Gertrude,
not being able to receive or reply to them,
began so earnestly to wish for her companion`'s absence, that Miss Thomson,
perceiving her to be somewhat uneasy, soon rose to take her leave.

She was scarcely gone, when Miss Robson,
having returned from a walk she had been taking with Harriet and Charlotte,
entered the room, leaving the two girls with their mamma to entertain Mrs.
and Miss Thomson.

Welcome as Miss Robson`'s presence always was to Gertrude, it was doubly welcome now,
after the fatiguing interview she had been constrained to undergo with Laura Thomson.

"`You look exhausted, my Gertrude,`" said Miss Robson as she approached her.

"`You have had some visitors, I find?`"

Gertrude related what had passed, and when she concluded,
said she had something upon her mind which she wished to say about Mrs.
Allen, only she was afraid that, after all her kindness to her, it might seem ungrateful.

Miss Robson assured her that her feelings would not be misconstrued,
and urged her to express what lay upon her mind relative to Mrs.
Allen.

"`I think, then,`" said Gertrude, with some hesitation,
"`I should be so glad if she would not ask any visitors into my room.`"

"`She does it out of kindness, my dear,`" said Miss Robson,
"`and in the hope of diverting you by a little change of company.`"

"`She is very kind,`" said Gertrude; "`but they don`'t divert me.
I like better to be alone.`"

"`It is very sweet to be alone,
when we have good thoughts with us;`" replied Miss Robson; "`and yours, my love,
I hope and believe are such.

"`I try to think good thoughts, Miss Robson,`" and she looked earnestly at her friend,
"`but I have not always good thoughts.
Sometimes they are very bad.
They are very bad tonight,`" and she began to cry.

Miss Robson tenderly soothed her;
and after a little time inquired into the nature of the thoughts which so disturbed her.

"`I don`'t think I can tell you, they were so dreadful.`"

"`I don`'t wish you to tell me, my love,`" replied Miss Robson, "`if that is the case;
I would only say to you, endeavour to fear them not.
Wicked thoughts are cast into our minds by the adversary of souls,
and in that case they are not ours,
and we are no more answerable for them than you would have to answer for it to Mrs.
Allen, were I to take a bottle of ink,
and throw its contents over your clean white counterpane.
The wicked thoughts which Satan casts into our minds,
are only made ours _when we join with them, and delight in their company,
and talk with them, and give them entertainment._
As, for instance, to go on with the comparison of the ink,
it could not be supposed I should do such a thing as throw the ink over Mrs.
Allen`'s property to spoil it, unless I felt some malice towards her,
and took that way of gratifying it.
Well, suppose that I not only do this, but that I say to you while doing it, '`Oh,
Gertrude, Mrs.
Allen is a very ill-natured, disagreeable person, and we have a right to punish her,
and do whatever we like to trouble and displease her;
help me to cut her feather-bed and pillows,
and let us together do her all the mischief we can; and you readily agree to it,
and begin immediately to lend your assistance,
and talk with me on the best way of accomplishing our evil purposes; then, indeed,
my wickedness becomes yours also; because,
instead of disliking and rejecting my proposals, you approve of, and unite with them.
But if, instead of this, you take no notice of them;
and not thinking it safe to argue or speak in reply to them,
endeavour to keep your mind as still as possible,
and silently breathe a prayer to your Heavenly Father to
preserve you from the advice of so detestable a counsellor;
suppose this to be your conduct, can you think, my dear child,
that you would be joined in my guilt, and be considered as a partaker of it?`"

"`But suppose I did listen to the wicked one, when he told me to hate any body?`"
said Gertrude, half trembling as she spoke.

"`It would be very sad to give ear to such suggestions,`" replied her friend; "`but,
Gertrude, I am greatly mistaken in my opinion of you, if you could cherish any bitter,
hateful thoughts towards your fellow creatures.
Remember, my dear child,
there is a great difference between those sudden emotions of dissatisfaction with others,
which, as I have just told you, may be the work of Satan,
and which also may arise from the stirrings of our own corruption; I say,
there is a great difference between these and such indulged evil
thoughts as constitute the dreadful feeling which is called hatred.
Besides, my love, whom have you to hate?
You love all that dwell in this house, don`'t you?`"

"`Oh yes, dearly,`" and a sweet smile overspread her face.
"`It was nobody here that I felt those wicked thoughts about.`"

Miss Robson believed she could penetrate into the secret of Gertrude`'s discomfort,
when she remembered her manner in relating what had passed during Miss Thomson`'s visit,
and her desire, so earnestly expressed, that Mrs.
Allen would not again bring visitors into her room;
and thinking it would be a great relief to her to disburden her mind,
she told her she thought she could guess who was the person
that the adversary was trying to render hateful to her;
and, bending down her head on a level with Gertrude`'s,
she whispered in her ear the name of Laura Thomson.

"`Oh, Miss Robson!
How well you can read my heart!`" she replied;
"`it was indeed Laura Thomson I felt those sad wicked thoughts about.`"

"`You felt angry at her talking to you, as her mamma talks, I suppose.`"

"`I don`'t know what I felt most angry at,`" said Gertrude.
"`I think the worst feeling I had was something that
made me think it hard I should lie here,
so weak and ill, and she be so well and cheerful; and, and,`"--she paused.

"`And be dressed so smart, perhaps?`"
said Miss Robson, helping out the confession.
"`You thought she was very nicely dressed, I dare say.`"

"`I did not think about her dress, at first.
I was so happy before she came into the room.
I had been reading in the Bible where our Lord says,
'`Suffer the little children to come unto me; and he took them up in his arms,
put his hands upon them, and blessed them.`'
And I was thinking how sweet Jesus must
have looked with the little children in his arms, blessing them.`"
She ceased to speak, but, evidently, not for want of matter, but of words to express it.
"`I could not say what I was feeling,`" she at last continued--"`but I was very happy.`"

"`I do not doubt it, my dear child,`" replied Miss Robson.
God is very merciful to his suffering children.
He sends a gracious rain upon his inheritance,
and refreshes it when it is weary.`' And I dare say, Gertrude,
that you have known happy moments upon that bed of suffering,
which you would not exchange for all the health, and pleasure,
and fine clothes that Laura Thomson possesses?`"

"`Ah, that I have,`" replied Gertrude.
"`It was because I never felt such unhappy thoughts before,
that I did not know how to bear them now.

"`They were not _your_ thoughts,`" said Miss Robson; "`if they were,
you would have no such pain in their company as they have occasioned you.
The state of the case, my dear, is simply this.
You are by nature, as we all are, a poor sinner,
and have a root of evil wherein the enemy of your soul strives to work,
and produce his bad fruits.
He has been labouring to do so this evening, by stirring up angry, envious,
and bitter feelings towards Laura Thomson;
confounding and darkening your mind by his artifices,
so that you cannot separate the evil from the good, and know what is yours,
or what is his, in the thoughts that possess you.
This is a very common state with minds much more experienced than yours;
and nothing can possibly be done at such times, but to be perfectly still.
Tomorrow morning you will have forgotten all that now disquiets you.

"`I feel as if I had forgotten it now,`" said Gertrude,
"`and I should be very glad if Laura Thomson was not gone, to see her once more.
And, Miss Robson,
don`'t you think she would be pleased if I were to make her a little present?`"

"`What would you give her, my dear?
She has so many fine things of her own,
that I am afraid she would not set much store by any present
which you have it in your power to make her,
my Gertrude.`"

"`Oh, it wasn`'t any fine thing that I was thinking of giving her.
It was my little text-book.
I have two or three little books with daily texts in them.
I thought I should like to give her one.
It might do her good, you know.`"

Miss Robson readily acceded to this proposal,
and hastened to see if the young lady and her mamma were still in the parlour.

They were on the point of taking their leave,
but willingly remained a few minutes longer,
in order to gratify Gertrude`'s wish of once more seeing Laura.

The little offering was soon made, for, as you are aware,
Gertrude`'s way of doing things was with as few words as possible,
and it was kindly and thankfully accepted; for Laura Thomson, with all her faults,
had something amiable in her disposition,
and as it is always far more desirable for us to look at
the good rather than the evil side of our fellow creatures,
so is it far more easy,
if we only incline our hearts to the practice of that "`charity which thinketh no evil.`"

Our favourite little Gertrude (for I am willing to hope
she is a favourite with you) so deeply felt this,
that her affectionate parting with Laura Thomson,
compared with the cold leave-taking that, but half an hour before,
had passed between them, seemed like a gleam of sunshine after a thunder-shower;
and when Miss Robson, after Laura was gone, kissed her,
and told her now to be happy--now to rest in peace.`' "`Oh I am happy,`" she replied;
"`I am in peace!--for now I love every body!`"
