== Chapter IX. Judge Not, That Ye Be Not Judged.

Whilst we leave Gertrude to an interval of quiet and repose,
I shall ask you to accompany me to the parlour, where,
the visitors having taken their leave, there only remained Mrs.
Allen, Miss Robson, and Harriet and Charlotte;
amongst whom the following conversation took place,
whilst they were engaged at their work.

[.discourse-part]
_Harriet._--What an affected girl Laura Thomson is!

[.discourse-part]
_Charlotte._--I never saw any thing so ridiculous.
Here she goes mincing round the room!

[.small-break]
'''

These words were accompanied by a variety of sinkings and slidings of her person,
which Charlotte exhibited as a representation of Miss Thomson`'s movements.

[.discourse-part]
_Mrs.
Allen._--(trying to suppress a smile).
Charlotte, Charlotte, that really is very wrong.
She should not do so, should she, Miss Robson?

[.discourse-part]
_Miss Robson._--I think Charlotte would not herself like to be represented in that manner.

[.discourse-part]
_Charlotte._--I represented!
I hope that I don`'t make myself quite so ridiculous as Miss Thomson does.

[.discourse-part]
_Miss Robson._--You may not, perhaps, imitate in her particular way.
You may not be affected after her manner.

[.discourse-part]
_Harriet._--But, Miss Robson, I don`'t think Charlotte is at all affected.

[.discourse-part]
_Mrs.
Allen._--No, really, Miss Robson, I must think you are a little too hard upon Charlotte.

[.small-break]
'''

Strengthened by her mother`'s remark, Charlotte assumed the tone of an ill-used person,
and said she believed that, whatever were her faults,
they were not those of affectation and conceit.
"`And indeed, Miss Robson,`" she continued,
with a boldness she would neither have felt nor shown out of her mother`'s presence,
"`I think you would be puzzled to mention when you ever
saw me make myself so ridiculous as Miss Thomson does.

[.discourse-part]
_Miss Robson._--I am not fond of being puzzled, especially by my pupils; for,
if there is to be any puzzling at all between us, I think it is my place to puzzle them.
So I believe, Charlotte, I must give you the puzzle of finding out what I meant.

[.small-break]
'''

There was a plain straight-forwardness about Miss Robson,
that never suffered her to turn aside from the point,
when she believed it to be a right one; and Mrs.
Allen felt assured, from her manner,
that there was something more to be brought forward than
what appeared at present in her remark to Charlotte,
and as she herself was a person who had a great,
and too much indulged dislike to any thing she thought disagreeable,
(as the reproving of her children always was to her,) she
chose to end her part in the matter by quitting the room.
With the departure of her mother, the greater part of Charlotte`'s bravery departed also;
and she would have been very glad to have ended the subject;
and endeavoured to do so by making some remark to
her sister respecting the work she was employed about.
Her efforts on this head were, however, in vain; for Harriet,
being determined to know what was Miss Robson`'s aim,
instead of answering Charlotte`'s remark about her work, returned to the former subject,
by begging of her governess to say wherein she thought Charlotte affected and conceited.

[.discourse-part]
_Miss Robson._--I don`'t recollect saying she was either.

[.discourse-part]
_Harriet._--No, not exactly; but you seemed to think she was both.

[.discourse-part]
_Miss Robson._--I gave Charlotte the puzzle of finding out what I meant by my remarks.
Perhaps, she has solved the riddle;
and then you can hear from her all that I have to say on the subject.

[.small-break]
'''

Whilst this was passing, Charlotte had been manifesting great signs of restlessness,
looking into this work-box, and that basket,
as if in search of something that she wanted, though without naming the absent article.
Harriet constrained her now to return to the point she evidently wished to avoid,
by asking her plainly "`if she knew what was Miss Robson`'s meaning?`"

[.discourse-part]
_Charlotte._--(colouring deeply.)-- I believe I do.

[.discourse-part]
_Harriet._--Oh then, do tell me, I must hear what it is.

[.discourse-part]
_Miss Robson._--I will give you an opportunity.

[.small-break]
'''

And, as she spoke, she was rising to leave the room; but Charlotte prevented her,
by throwing her arms round her,
and hiding her blushing face upon Miss Robson`'s shoulder, as she said to her,
in a low voice, "`Dear Miss Robson, don`'t go.
Oh, you have made me so ashamed of myself.`"

Miss Robson kindly kissed her cheek.
"`Shame is generally a valuable feeling, Charlotte,
and those who can really and deeply experience it,
are never to despair of moral improvement.
I will leave you while you relate to Harriet that
which I can see she so much wishes to hear;
but as you are thus placed in circumstances which oblige you to be your own reprover,
I must suggest to Harriet that it was not kind to indulge the impatient
curiosity which has drawn you into such a painful situation.`"

[.discourse-part]
_Harriet._--Indeed I am to blame.
But I will not hear what Charlotte has to tell; I will punish myself that way.
I am sure, dear Miss Robson, you have a reason for everything you say,
or even hint to us, and that is quite enough.

[.small-break]
'''

Miss Robson was highly pleased with the conduct of both her beloved pupils,
and there the matter was suffered to rest.

But, as I am not without hope,
that some of my young readers may derive instruction from the relation,
I shall gratify the wish, which I do not doubt they feel,
to be informed what really was Miss Robson`'s meaning
in the remarks she had addressed to Charlotte;
in doing which,
I must go back to some circumstances that had occurred only the preceding week,
which were known but to Charlotte and her governess.

It happened one morning that a lady called at the Rectory, who wore under her bonnet,
as many ladies do, some artificial flowers,
which were articles of finery that Mr. Allen had a particular objection to;
always remarking, whenever he saw them,
that it seemed to him little less than an insult upon the lovely
flowers to ape their beauties in bits of coloured cloth.
"`If people will wear flowers,`" he would say, "`let them gather them fresh and real;
but better is it for all things to keep their proper places;
and the flowers to ornament the ground,
and the spiritual blossoms of good feeling and intelligence the ladies.
Those are the flowers that are not artificial, and will never fade.`"

Now, amongst her other failings,
Charlotte Allen possessed a great deal of vanity and love of dress;
which were infirmities that had little encouragement in her father`'s house;
for everything there was of the plainest and simplest kind.
But, notwithstanding these restraints upon her fancy,
she seldom saw any smartly-dressed persons,
that she did not experience more or less desire to imitate them.
On the morning now alluded to,
she had suffered her mind to be so much captivated
by the artificial flowers under the visitor`'s bonnet,
and had so minutely observed and remembered them, that, as soon as the lady departed,
she went into the garden to make an assortment as near like them as possible.
It was a time of day when she usually walked out with Miss Robson
and her sister to visit some of the poor people in the village;
but on this morning she made some trifling excuse
of wishing to employ herself in the garden,
and they, together with Mrs.
Allen, went without her.
And here, I would pause to observe, that it is desirable for young persons,
always to assign the _real_ reason to themselves for all their actions,
especially when they are of a kind which incline them to wish to be alone.
Now, in this case, had Charlotte spoken the truth to herself, and said,
"`I wish to be alone,
because I want to see how I should look with flowers under my bonnet,`" she would,
most likely, have been so ashamed of herself,
that she would have relinquished her intention.
But, by glossing over her design with saying,
(and I suppose really thinking,) that she was going to employ herself in gathering flowers,
forgetting, or not choosing to remember, what she was going to gather them for,
she went into a crooked path,
which was likely to lead her further into error than she had any idea of.
But to proceed.
She made her selection as nearly as possible like the pattern in her memory.
There was a moss-rose and a sprig of jessamine to start out from the side of one cheek,
and there was a sweet-pea and a bit of mignionette to do the like on the other.
"`But then I should have a cap like Miss Smith`'s!`" thought Charlotte.

This was indispensable to the right effect of all this frippery;
but certainly no cap in the house was of that sort.--No matter;
"`where there`'s a will there`'s a way,`" and Charlotte believed
she could give a twist and a turn to her own bonnet cap,
which would produce the desired effect.
Accordingly she hastened to the room in which she and her sister slept,
in doing which she had to pass through Miss Robson`'s, which opened into it.

The flowers she had gathered were all twisted together, and placed in order upon the cap,
and altogether tied on before the looking glass, and her straw bonnet put over them,
when she recollected that the visitor had a veil partly shading her face.
Where was a veil to be found?
She had none; but Miss Robson had one, though she seldom wore it,
except when the weather was cold.
Charlotte had seen her take it out of her drawers, and knew where she kept it.
But to go to Miss Robson`'s drawers in her absence, and to take any thing from them!
This was, indeed, a startling consideration;
and she hesitated some time before she could proceed.

"`But you are not going to steal the veil,`" said the artful tempter in her ear,
"`you are going to put it back again almost directly.

Poor Charlotte!
How clearly at any other moment would she have seen the shame of such
practices as she had involved herself in by entering upon one wrong step!
But now she could see nothing but her own will, and so, to gratify it,
she went to Miss Robson`'s drawers, and took out the veil, and tied it upon her bonnet.

Thus adorned like the visitor, who was not only fashionable in her attire,
but fashionable in her manner and conversation, and sprightly and clever in her remarks,
and altogether a sort of person who was likely to
awaken some feelings of admiration in an intelligent,
observing girl,
Charlotte next proceeded to imitate the way in which
Miss Smith had talked during her visit.
Here I must leave you to imagine the scene;
not being willing to expose all the absurdities she uttered.
Perhaps some of my young readers may have happened to meet with
a little girl here and there who has been tempted to indulge,
as poor Charlotte then did,
a foolish desire of copying the manners of some one or another
whom she has wished to resemble--in that case,
they can understand as well as I could tell them,
how exceedingly ridiculous she made herself.
I shall only, therefore, relate the conclusion of the matter, which was, indeed,
a very painful and unexpected one to Charlotte; who,
in her eagerness to accomplish her purpose,
had forgotten to shut the door of Miss Robson`'s room, when she returned with the veil.
Great, therefore, was her confusion, when, on rising from her seat,
and making a low curtsey, and saying as Miss Smith had done on taking her leave,
"`my dear Mrs.
Allen, I must now tear myself away; for, indeed,
it is by force only that I can ever get away from the Rectory;`"--great, I say,
was her surprise, and unutterable her confusion,
in feeling a hand laid upon her shoulder,
at the same time that a voice inquired of her "`where she was going?`"

"`Oh, Miss Robson!`" she exclaimed; for it was indeed her governess,
returned from her walk, not sooner than usual, but sooner than Charlotte,
in her manifold occupations, had calculated upon.

"`Oh, Miss Robson!`" she repeated, as she sat down,
and in extreme confusion covered her face with both her hands.

"`And oh, Charlotte!
I think I must say,`" replied Miss Robson,
standing motionless with surprise a few moments.
Then looking earnestly at her, "`what have you made yourself this ridiculous figure for,
and why have you taken my veil out of my drawers?`"

"`I don`'t know what to say,`" replied Charlotte,
beginning to cry bitterly,--"`I am so ashamed!`"

The flowers, and the finery, and the mimicry of Miss Smith`'s parting speech,
told their own story; nor was it one that greatly surprised Miss Robson,
who had often remarked with concern,
Charlotte`'s disposition to be pleased with fine clothes and fashionable people;
and also an inclination (not uncommon in little girls)
to imitate the manners of their elders.

"`I shall not say much to you, my dear Charlotte,`" she observed,
after a little interval of silence, during which Charlotte sobbed bitterly,
"`I shall not say much to you,
because I am persuaded that what you are now feeling
is a far better reprover to you than I can be;
but I would earnestly exhort you to remember it when
the present painful impression is passed away.
Yes, I would earnestly counsel you to bear in mind that it is not merely the
folly of mimicry which this indulgence of vanity has betrayed you into,
but also a breach of trust, and a violation of good faith, which is far worse.
When I leave my drawers open, I feel that I can so far confide in your principles,
and also in your sister`'s,
as to be persuaded that you will abstain from meddling with them.
I do not believe you ever opened a drawer of mine before.`"

"`No, that I never did,`" said Charlotte; "`I only knew you kept your veil there,
because I have seen you take it out.
And to think that, for such foolishness as this, I should do such a thing,
and lose your good opinion!`" and she burst into fresh tears.

"`You will not lose my good opinion,`" said Miss Robson, affectionately embracing her;
"`on the contrary, I trust henceforth to find you more deserving of it than ever;
for I hope that what has now passed will tend to make you so watchful over yourself,
that you will not again be betrayed into any thing so foolish and degrading.
Come, let us get rid of these trappings (_traps_ indeed for you,
poor child!) before Harriet comes up to change her frock.`"

"`I shall be long enough before I want to wear flowers again,`" thought Charlotte, as,
in a kind of disdain at her own folly, she took off the ornamented cap,
and began to disarray it of its accompaniments.

We might have hoped that it would be long enough
also before she practised any arts of imitation;
but here, I believe, I must again unveil the truth of the matter,
and tell you that it was a secret stirring of envy at Laura Thomson`'s smart clothes
that caused her so hastily to forget the humiliation of the preceding week.
Such poor creatures are we when governed by our own evil nature!
