== Chapter XI. A Farewell.

Another year rolled over the heads of the family at the Rectory,
and brought with it only an increase of languor and
debility to our poor little friend Gertrude.

It had long been evident,
that she was gradually sinking under the disease with which she was afflicted, and,
from the statements I have already made,
you will have been prepared for intelligence respecting her which, perhaps, you may,
at first, think somewhat melancholy;
but I hope when you have read the following letter from Mr. Allen,
wherein he gives an account of her peaceful departure from this vale of tears,
you will rather rejoice than regret to take leave of her.
It is addressed to the lady

under whose care Gertrude was placed on leaving India,
and who delivered her over to the charge of Mr. Allen.
This lady had been to see her several times during her long illness; and on quitting her,
at her last visit, had requested to hear from Mr. Allen respecting her.
Several letters had been addressed to her, in compliance with this request;
and at last came the following, with which I shall close this little narrative.

[.asterism]
'''

My Dear Mrs +++_______+++.

The black seal on this letter will have prepared you for its contents.
Our little suffering Gertrude is now a rejoicer with the saints in light,
and if it were not that you will be desirous of a few particulars,
I should be glad to avoid recurring to any other remembrances concerning this dear child,
than those connected with her present state.
You will, therefore, excuse my being somewhat brief.

On Saturday last, she was extremely languid and drowsy, and having for several days,
observed appearances of her dissolution to be approaching,
we expected that that day would terminate her sufferings.
But, contrary to what we looked for, she revived towards the evening,
insomuch that she was able to converse a little,
and seemed particularly pleased to have me and our beloved friend Miss Robson near her.
I read a few verses from the 14th chapter of John,
which was always a very favourite portion of scripture with her.
I paused at the words,
"`in my father`'s house are many mansions,`" for
she seemed as if she had a remark to make upon them;
but she only uttered the words "`all beautiful,`" and smiled.

"`Yes, my love,`" said I, "`all!
There are no mansions like those, Gertrude!`"

"`Oh no!
I long,`" but, as if fearing to indicate impatience by expressing her wishes,
she did not say more.

"`You long to be gone, dear child,`" said Miss Robson.
"`But we do not wish to part with you, dearest,
whilst the Lord permits you to remain;`" and our dear friend,
though a person of unusual self-command, was unable to restrain her tears.

Gertrude seemed grieved at this,
and the emotion was quickly resisted on the part of Miss Robson, who,
with a pleasant smile, wiping away her tears,
repeated to her little friend and beloved pupil, these lines,
which Gertrude had been fond of hearing during her illness.
They were written by a friend of Miss Robson`'s who was in suffering circumstances,

When they their little hour have stayed,

The roses droop and die;

The lilies of the valley fade,

And so, alas, must I!

But wherefore do I say, alas,

And wherefore do I sigh?

The wintry season soon will pass,

And summer days draw nigh:

The lovely rose will re-appear,

The lilies bloom once more;

And spring, returning fresh and fair,

Creation`'s face restore;

And saints of God shall rise renewed

With better life than this;

To dwell with the Supremely Good,

In everlasting bliss.

She smiled sweetly as though these thoughts were very precious to her;
and when I said "`through One, who died for all,
we may hope to rise to everlasting bliss,`" she earnestly exclaimed "`Yes; through Jesus,
the blessed Saviour!`"

"`You feel that you have no other hope, my love, than what you find in Him?`"
I asked.

"`Oh no,`" she replied quickly.
"`I can only think of God through Him--He is the good friend that intercedes.`"

"`The sinner`'s friend,`" said Miss Robson,
"`the friend that sticketh closer than a brother.`"

She looked her joy and satisfaction in this blessed thought,
but was too weak to express it.
Our dear Gertrude, as you are aware, was, even in health,
one who seldom gave utterance to her feelings.

After having spent a few minutes in prayer, I took leave of her for the night,
and the girls and Mrs.
Allen came into her room for the same purpose, leaving her, as usual,
under the kind care of Miss Robson.

Having parted with her thus composedly,
we were not prepared to be summoned at day-break with the painful intelligence
that she was suddenly so much worse as to be apparently on the eve of dissolution.
Yet such was the case.
We hastened to her room, that is, my wife and myself;
for I did not desire to have my dear girls called up to witness the scene.

It was from our sweet Gertrude`'s living graces, and not her parting bodily struggles,
that I expected them to be instructed.
Happily these last were of short duration.
She was passing away as we entered the room, and that with a smile so beautiful,
that any feeling but that of joy seemed forbidden to any of us.
We were all rejoicers, that is, Miss Robson, our faithful servant Sarah, and myself.
But my poor wife, though not the mother of the dying child,
felt her parent`'s heart stirred up within her,
and clasping her arms round the dear Gertrude, as she was supported by Miss Robson,
wept bitterly.

The grey dawn of day, and the solemn circumstances around me,
so forcibly recalled those beautiful and affecting
lines of Mr. Cecil`'s on one of his own children,
an infant of a month old, who died at day-break, that I uttered aloud, the first verse--

Cease here longer to detain me,

Fondest mother, drown`'d in woe;

Now, thy kind caresses pain me,

Morn advances, let me go!

"`Thy day breaketh upon thee, happy child!`"
I exclaimed, as I pressed my lips upon her cheek,
and breathed a few words to Him who seeth in secret.

One little sigh released the happy spirit; and we had now no pain left,
but that of by and by meeting the young and buoyant natures of our dear children,
with the intelligence, which we were aware they must, for a time,
consider as very mournful.

It was indeed a painful stroke, though long expected;
and I suffered the emotions of nature for a season to have their sway.
These somewhat subdued,
I endeavoured to improve the occasion to theirs and all our benefit;
and I hope was not unsuccessful.

"`Thus, my dear children,`" said I, in conclusion, "`we have lost our gentle Gertrude;
but we have not lost that which made her gentle -- He, whose parting words were '`Lo,
I am with you always, even unto the end of the world--He,
who was meek and lowly in heart,
and who calls the heavy burdened to come unto Him
and be refreshed--He remains to bless us,
and to do us good; to gather the lambs with his arm, and to carry them in his bosom.
Oh then, my children,
cultivate those sweet and lamb-like tempers which
shall make you meet to be gathered into his fold;
so that whenever, and however, your summons shall appear,
you may know as peaceful a departure as our Gentle Gertrude.`"

In this desire for myself also, and for you, my Christian friend,
and all my fellow creatures, I rest sincerely yours,

John Allen.

The End.
