== Chapter I.

In observing the dealings of Providence towards the human race,
we generally discover that the most important consequences have resulted from what,
in common estimation, are considered as very inefficient causes;
and that material revolutions have been effected
in the moral and religious condition of mankind,
by the instrumentality of persons whom the greater part of
their fellow creatures account to be mean and insignificant.

Perhaps there are few instances in which this is more obvious,
than in the rise and progress of the Society of Friends: a community,
which devoid of any advantages on the side of worldly power, were enabled,
under the severest pressure of the persecuting spirit of the times,
not merely to stand their ground, but to substantiate themselves into a body, which,
as to its principles,
may justly challenge the world to produce any more truly in
accordance with the pure and meek religion of the holy Jesus.
The chief instrument in the organization of this society, was George Fox,
a man of humble birth, and of little or no education;
but manifestly endowed with extraordinary powers of mind,
both as to intellectual and moral qualities.

The portion of his history which in the course
of this narration it may be desirable to give,
cannot be more appropriately presented to the reader, than in his own words,
which I therefore use, abbreviating them when not material to the subject.

"`I was born,`" he says, "`in the month called July, in the year 1624,
at Drayton in the Clay, in Leicestershire.
My father`'s name was Christopher Fox: he was by profession a weaver;
an honest man--the neighbours called him '`Righteous Christer.`'
My mother was an upright woman, and of the stock of the martyrs.`"^
footnote:[G. Fox`'s Journal, p. 1. And it may suffice here to say,
that whenever George Fox`'s words are quoted, they are taken from his own Journal.]

Then, proceeding to speak of his nature and disposition,
"`in my very young years,`" he says, "`I had a gravity and stayedness of mind and spirit,
not usual in children.
While I was a child, I was taught how to walk to be kept pure.
The Lord taught me to be faithful in all things, and to act faithfully two ways; namely,
inwardly to God, and outwardly to man; and to keep to yes and no in all things.`"

It seems to have been the intention of his parents to bring him up to the church; or,
as he expresses it, "`my relations thought to have made me a priest,
but others persuaded to the contrary.
Whereupon, I was put to a man that was a shoemaker by trade, and that dealt in wool,
and used grazing, and sold cattle, and a great deal went through my hands.
I never wronged man or woman,`" he observes, "`in all that time,
for the Lord`'s power was with me, and over me, to preserve me.
While I was in that service, I used in my dealings the word verily:
and it was a common saying among people that knew me, '`If George says verily,
there is no altering him.`'
When boys and rude people would laugh at me, I let them alone and went my way.
But people had generally a love to me for my innocency and honesty.`"

In this way he appears to have passed his time, till the nineteenth year of his age,
when a revolution of such importance occurred in his habits of life,
as gave the colour not only to his own destiny, but to that of thousands besides.
Before, however, we enter upon this part of our narration,
it will be desirable to take a brief review of
the situation of public affairs at that period.

A variety of mistakes, and worse than mistakes, on the part of that unhappy monarch,
Charles I. and his advisers, had, about this time,
issued in the beginning of a civil war,
in which religion had a share--the people disliking,
and the well-principled clergy resisting,
the many indications of a return to Roman Catholicism, which most of the bishops evinced.
In Scotland, endeavours were made to bring in Episcopacy,
which caused so great a ferment among the people, as to amount to an insurrection.
But not to involve myself, or my reader, in the wars between Charles and his parliament,
I would merely say, that in order to sympathize with the feelings of George Fox,
and others similarly affected with himself,
we must contemplate them as not merely actuated by religious zeal in the abstract,
but religious zeal awakened in times of oppression and darkness,
when a mighty struggle for truth and moral liberty was
to be made by every valiant soldier of Jesus Christ.
Much indeed had been done in the preceding century,
by those faithful reformers who sealed their honest testimony with their blood;
but much yet remained to do:--they had, as it were, but secured the pass;
"`the sword of the Lord and of Gideon`" had yet the battle to fight.
It was a great and glorious victory which they indeed had accomplished,
in asserting and maintaining the right of every
individual to follow the dictates of his own conscience,
and in liberating their country, in so great a degree,
from the insupportable yoke of religious fraud and superstition;
but still further advances into a pure and spiritual
worship were yet required by that Great Being,
who, as a Spirit, can only be acceptably worshipped "`in spirit and in truth.`"
(John 4:24)

It was about the period when the contest was warmest between the king and the parliament,
and when, as yet, neither side had prevailed, that George Fox,
guided by that invisible hand which "`shapes our ends,
rough hew them how we will,`" was led, in the course of events,
to abandon his occupation, and enter upon the work which occupied his whole future life.

The immediate occasion of his throwing up his employment,
was the disgust he received from the conduct of
some persons who made a profession of religion,
and whom he accidentally met at a fair, where he was transacting his master`'s business.

"`When I came towards nineteen years of age,`" he says, "`being upon business at a fair,
one of my cousins, whose name was Bradford, (being a professor,
and having another professor with him,) came to me,
and asked me to drink part of a jug of beer with them; and I, being thirsty,
went in with them, for I loved any that had a sense of good,
or that did seek after the Lord;
and when we had drunk a glass a-piece they began to drink healths,
and called for more drink; agreeing together,
that he that would not drink should pay for all.
I was grieved that any that made profession of religion should offer to do so:
wherefore I rose up to be gone, and putting my hand into my pocket I took out a groat,
and laid it down upon the table before them, and said,
'`If it be so I will leave you:`' so I went away,
and when I had done what business I had to do, I returned home,
but did not go to bed that night, but sometimes walked up and down, and sometimes prayed,
and cried to the Lord, who said to me, '`You see how young people go together into vanity,
and old people into the earth, +++[+++earthly things,]
and you must forsake all, both young and old, and keep out of all,
and be as a stranger unto all.`'`"

This secret admonition, which he believed to come from God, so deeply affected him,
that he resolved to separate himself from all his connection,
to renounce familiar interaction either with young or old,
and to leave his dwelling-place; which resolution he fulfilled,
by departing first to Lutterworth, from there to Newport Pagnell, in Buckinghamshire,
and finally to Barnet, where he arrived in June 1644,
being then near twenty years of age.

Here he led a solitary life, walking frequently in the open fields,
in great conflicts of mind, with his Bible only for his companion.
He also fasted often, and manifested so much seriousness of deportment,
that many religious people took notice of it, and desired his acquaintance;
but not finding them in practice what they professed in sentiment,
he was shy of entangling himself in any connection with them; and,
in the hope of meeting with those who were more in accordance with his expectations,
he proceeded, in much distress of mind, to London,
where he had an uncle who had joined the Baptists.

The character of the parliament being religious,
it gave the tone of religion to most of the restless spirits of those disordered times,
especially in the metropolis,
where a great variety of thinkers and talkers upon this subject, abounded;
and where George Fox anticipated that he should obtain both the
counsel and the sympathy which he had sought in vain in the country;
but he found himself mistaken, discovering that, for the most part,
the religious professors of the great city were like those he had encountered elsewhere;
rich only in notions and doctrines, learned in the letter, but lifeless in the spirit,
and totally incapable of affording him any comfort.

Having failed in the object of his wishes,
and doubting whether he had not erred in quitting his relations,
after some little time had elapsed, he returned home, where he continued about a year,
in great anguish of mind, and suffering an increase of sorrow,
from the impossibility of meeting with any person who understood,
or could administer to his case.

He made several efforts to obtain spiritual counsel; visiting, as occasion offered,
those persons whom he supposed likely to befriend him by their advice.
Of some of these visits he speaks with amusing simplicity,
especially of that to a person whom he describes as "`an ancient priest, at Mansetter,
in Warwickshire,`" whom he "`reasoned with upon the subject of despair and temptations.`"

"`But he was ignorant of my condition,`" he says,
"`and he bid me take tobacco and sing psalms: tobacco was a thing I did not love,
and psalms I was not in a state to sing.
Then he bid me come again, and he would tell me many things;
but when I came again he was angry and pettish, for my former words had displeased him.`"

He was not more happy in his next application, as the following record testifies:

"`Then I heard of a priest living about Tarnworth, who was accounted an experienced man;
and I went seven miles to him; but I found him but like an empty hollow cask.
Then I heard of one called Dr. Cradock, of Coventry, and I went to him,
and I asked him the ground of temptations and despair,
and how troubles came to be wrought in man.
He asked me who was Christ`'s father and mother?
I told him Mary was his mother, and that he was supposed to be the son of Joseph,
but he was the Son of God.

"`Now, as we were walking together in his garden, the alley being narrow, I chanced,
in turning, to set my foot on the side of a bed, at which the man was in such a rage,
as if his house had been on fire; and thus all our discourse was lost,
and I went away in sorrow, worse than I was when I came.`"

About the year 1646, being at Coventry,
he appears to have received some new and strong
impressions respecting the work of a Christian minister;
and which inclined him totally to separate himself from the national mode of worship,
in which he had been educated, and to which, up to this period, he seems to have adhered.

The chief result of these impressions was a fixed belief that "`God, who made the world,
did not dwell in temples made with hands,`" and that consequently not the place,
but the spirit in which men met to worship the Most High, was the important point.
He also was led to believe, that there was an unction from the holy one,
in every man who was called of God to minister in holy things,
of which the apostle John makes mention, when he says,
"`but you have an unction from the Holy One,
and you know all things;`" (1 John 2:20) and to which he
also refers when he reminds them of its abiding in them,
(ver. 27,) "`but the anointing which you have received of him,`" he says,
"`abides in you, and you need not that any man teach you;
but as the same anointing teaches you of all things, and is truth, and is no lie,
and even as it has taught you, you shall abide in it.`"

Nor was it merely to those who were called of
the Lord to take the office of the priesthood,
that he saw this anointing to be peculiar, but that it extended to all believers;
such being the character of those to whom the apostle was writing.
He was taught indeed to see that there was a divine principle, or holy seed,
in the hearts of the whole human race,
even a spark of that "`light which enlightens every man that comes into the
world;`" (John 1:9) and although this "`light shines in darkness,
and the darkness comprehends it not,`" yet still it was there; and,
as from the power of that light the true minister of
God was enabled to exercise his ministration,
so to the power of that light in the hearts of his hearers,
those ministrations were intended to appeal.

It is obvious that the inward and spiritual nature of such views,
would meet with continual and fierce opposition from those
religious professors who moulded their opinions upon the
different creeds and formularies of their respective parties;
which creeds and systems being, for the most part,
founded upon the various expositions which this and the
other man had made of the letter of Scripture,
had provided a set of notions and dogmas for their different partisans to defend,
rather than had helped to turn them from the cry of "`lo here!
and lo there!`" to the living spirit in their own hearts.

Under such impressions as he believed to be the work of the Spirit of God,
George went forth upon his travels.
"`Having forsaken all evil company,`" he says, "`and taken leave of father and mother,
and all other relations, I travelled up and down as a stranger in the earth,
which way the Lord inclined my heart.
Taking a chamber to myself, in the town where I came, and tarrying sometimes a month,
sometimes more, sometimes less in a place; for I dared not stay long in any place,
being afraid both of professor and profane.
I kept myself much as a stranger, seeking heavenly wisdom,
and getting knowledge from the Lord;
and was brought off from outward things to rely wholly on the Lord alone:
and though my exercises and troubles were very great,
yet were they not so continual but that I had some intermissions,
and was sometimes brought into such a heavenly joy,
that I thought I had been in Abraham`'s bosom.
Oh, the everlasting love of God to my soul, when I was in great distress!
When my troubles and torments were great, then was his love exceeding great.
You, Lord, make a fruitful field a barren wilderness,
and a barren wilderness a fruitful field!
You bring down and set up!
You kill and make alive!
All honour and glory be to you, O Lord of glory!
The knowledge of you in the spirit, is life; but that knowledge which is fleshly,
works death.`"

One of the strongest of the new impressions which his mind had received,
he thus somewhat quaintly describes: "`As I was walking in afield,
on a first-day morning, the Lord opened unto me, that being bred at Oxford, or Cambridge,
was not enough to fit and qualify men to be ministers of Christ; and I wondered at it,
because it was the common belief of people;
but I saw it clearly as the Lord opened it to me, and was satisfied.`"

He therefore, in reverting to the subject, observes, "`Now,
after I had received that opening from the Lord, I regarded the priests less,
and looked more after the dissenting people.`"

Yet here he met with disappointment; finding none that could, as he expresses it,
"`speak to his condition.`"

"`And when all my hopes in them, and in all men were gone,`" he says,
"`so that I had nothing outwardly to help me, nor could tell what to do, then, oh, then,
I heard a voice which said, '`There is one, even Christ Jesus,
that can speak to your condition:`' and when I heard it, my heart did leap for joy.`"

He then relates,
that he was permitted to see why he had been
unable to obtain the comfort of human sympathy,
in the deep and trying exercises of soul through which he was passing; namely,
that Jesus Christ might have the preeminence, who alone enlightens and gives grace,
and faith, and power;
and that he might come to an experimental acquaintance with his Saviour, without,
as he observes, "`the help of any man, book, or writing.`"

"`For though I read the Scriptures,`" he says, "`that speak of Christ and of God,
yet I knew him not, but as he who has the key did open,
and as the Father of life drew me to his Son by the Spirit;
and then the Lord did gently lead me along, and did let me see his love,
which is eternal, and surpasses all the knowledge that men have in the natural state,
or can get by history or books.`"

"`And when at any time,`" he continues, "`that my condition was veiled, +++[+++or depressed]
my secret belief was stayed firm, and hope underneath,
held me as an anchor in the bottom of the sea,
and anchored my immortal soul to its bishop, causing it to swim above the world,
where all the raging waves, foul weather, tempests, and temptations are.`"

Thus simply yielding himself up to the instruction and guidance of God,
this faithful man was silently and secretly receiving in his own experience,
a realization of the promise, "`they shall not teach every man his neighbour,
and every man his brother, saying, know the Lord, for all shall know me,
from the least to the greatest;`" and being able,
from a sure and certain acquaintance with the living teacher in his own heart,
to point others to the same, he set forth upon his work, which,
like that assigned to the apostle Paul, was to open the eyes of men`'s understandings,
and "`turn them from darkness unto light, and from the power of Satan unto God.`"

The situation of public affairs at this time,
(1647) was rather favourable to such religious views as he advocated,
being of a kind to solemnize and deeply affect every thoughtful mind; for the king,
now drawing near the close of his unhappy career, had withdrawn to the Isle of Wight,
where he was kept in close custody,
and no more regarded as a sovereign to whom obedience was due; and,
as such extreme measures necessarily excited strong and
conflicting feelings in the public mind,
they tended to pave the way for the reception of doctrines so
eminently calculated to promote peace and true piety,
as those of which George Fox was the minister.

It happened also, that,
amidst the variety of sects and parties which the
contest upon religious questions had brought forth,
there were several persons, who,
wearied with the doubt and discord they everywhere
encountered while seeking the right Teacher without,
were well disposed to listen to that preaching
which pointed them to an infallible Guide within,
where they knew that help and direction was most needed.
These persons, therefore, entered into fellowship with him; and thus united,
they began to have meetings in Nottinghamshire, which were visited by many people.

Of the peculiar scope of his ministry, we have his own definition:--"`With,
and by the divine Spirit of God, and the light of Jesus,`" he says,
"`I was to bring people off from all their own ways, to Christ, the new and living way;
and from their churches, which men had made and gathered, to the church in God,
the general assembly written in heaven, which Christ is the head of;
and off from the world`'s teachers made by men, to learn of Christ, who is the way,
the truth, and the life; of whom the Father said, '`This is my beloved Son,
hear you him;`' and off from all the World`'s worships,
to know the spirit of truth in the inward parts, and to be led thereby;
that in it they might worship the Father of spirits, who seeks such to worship him.
Moreover, when the Lord sent me forth into the world,
he forbade me to put off my hat to any, high or low;
and I was required to thee and thou all men and women,
without any respect to rich or poor.
And as I travelled up and down,
I was not to bid people '`good morrow,`' or '`good evening;`' neither might I bow,
or scrape with my leg to anyone.`"

With respect to these last peculiarities which
distinguished George Fox and his followers,
and which, at the first glance, might appear too trivial to cause them much trouble,
it may not be too much to say,
that they involved them in nearly as much persecution
as the profession of any other of their principles;
for their using the plain language of thee and thou,
and abstaining from the usual unmeaning ceremonies of society, was,
as William Penn observes,
"`a close and distinguishing test upon the spirits of those they came among;
showing what predominated in their interior,
notwithstanding their high and great profession of religion`" And,
speaking of their mode of address, he says, "`This, among the rest,
sounded so harsh to many of them, and they took it so ill, that they would say,
'`thou me!--thou my dog!
If thou thouest me, I`'ll thou your teeth down your throat.`"^
footnote:[William Penn`'s preface to George`'s Fox`'s Journal, p. 13.]

"`Oh, the storm, heat, and fury that arose,`" says George,
speaking of the treatment they encountered for the circumstance of keeping on their hats,
or, what he calls, the "`hat honour;`" "`Oh, the blows, punchings, beatings,
and imprisonments that we underwent, for not putting off our hats to men!
Some had their hats violently plucked off, and thrown away, so that they quite lost them.
The bad language and evil usage we received on this account, is hard to be expressed;
besides the danger we were sometimes in of losing our lives for this matter.`"

Nevertheless, having entered upon the work which, assuredly,
he believed to be assigned to him from God, he unflinchingly pursued it; and,
as was to be expected, in times so unsettled,
it was not long before he was taken notice of by persons in authority,
and called to account for his proceedings.

The first instance of this kind, appears to have been at Nottingham, in the year 1648;
and which arose from his controverting the mode in which he found the
minister of what he calls "`the great steeple-house,`"^
footnote:[One of the chief points of his ministry,
was to overturn that insidious reverence for names and things,
which is too frequently substituted for the worship that is "`in spirit and in truth.`"
Few instances more distinctly exhibit this sort of covert idolatry,
than the general notion of sanctity which is attached to the building called a church.
Hence, this notion was more particularly the object of attack,
not only from the primitive Friends, but from most of the religionists of those times;
for it is recorded by Sewel, in his history of the Society, (Lindfield edition, vol.
i.p. 165,) that some of the parliamentary soldiers, observing over the doors of a church,
the words of Jacob, "`This is none other but the house of God,
and this is the gate of heaven,`" could not endure to
see this gross conceit concerning these buildings,
but erased the words "`of God`" and "`of heaven;`" so that nothing was left,
but "`This is none other but the house, and this is the gate;`" a truth,
which in so far as it respects a building made with hands,
it would be rather difficult to gainsay.]
+++[+++church,]
expounding a text.
"`As I went towards Nottingham,`" he says, "`on a first-day, in the morning,
with Friends to a meeting there, when I came on the top of a hill in sight of the town,
I saw the great steeplehouse; and the Lord said unto me,
'`You must go cry against yonder great idol,
and against the worshippers therein;`'`" which,
after having attended his companions to the meetinghouse,
and remained there a certain time, he returned to do.
The preacher seems just to have given out his text as he arrived,
and the portion of Scripture lie had selected,
were the words from the second epistle of Peter:
"`We have also a more sure word of prophecy,`" etc.;
which he informed his hearers was the Scriptures,
by which they were to try all doctrines, religions, and opinions.
Upon hearing this, he observes, "`the Lord`'s power was so strong in me,
that I could not hold; but was made to cry out, Oh no, it is not the Scriptures!`"
He then told them that "`it was by the Holy Spirit,
by which the holy men of God gave forth the Scriptures, that religions, opinions,
etc. were to be tried; for that spirit led into all truth,
and therefore gave the knowledge of truth.
The Jews,`" he said, "`had the Scriptures, and yet resisted the Holy Ghost,
and rejected Christ; persecuting both him and his apostles,
and yet professing to try their doctrine by the Scriptures.`"

In the midst of his address, he was taken into custody, and conveyed to a prison,
of which, in a few words, he gives a very disgusting and, no doubt, faithful picture.
Having been examined, and again sent back to prison, after some time,
the head sheriff sent for him to his house; for having, with his wife and family,
made part of the congregation on the day when George spoke in the church,
both he and they were so much impressed by what he advanced,
that a further acquaintance with him was desired; the wife even greeting him,
on his entrance, with the words, "`Salvation is come to our house!`"

With this sheriff, whose name was John Reckless, George stayed some time,
and had meetings in his house, to which many persons of some consideration came,
who were, in general,
much solemnized by the appeal he made to the witness in their consciences,
Reckless himself being of this number;
and feeling touched with a consciousness of some fraud,
in conjunction with his brother sheriff,
towards an individual with whom they had had dealings,
he sent for the person in question, and also for his colleague,
acknowledging to the party his own share of the fault,
and calling upon the other sheriff to do the same,
which he was not so willing to submit to.

Nor was it merely in this instance, that the power of his preaching influenced Reckless;
for, on the following market-day,
the sheriff felt himself impelled to go into the
streets to preach repentance to the people;
in which measure he was accompanied by some others in the town,
who were induced in like manner to address religious
counsel to the mayor and other magistrates.

"`Hereupon,`" says Fox, "`the magistrates grew very angry;
sent for me from the sheriff`'s house, and committed me to the common prison.`"
Here he was kept till the court sessions came round;
and then the sheriff`'s man being somewhat dilatory in bringing him,
the judge had risen before he arrived at the sessions-house,
and he was carried back again to prison, and having been kept there for some time,
was at last set at liberty.
He continued to travel from place to place,
preaching as he felt himself internally guided,
and not according to any purpose or plan of his own.
Numerous were the instances in which a mighty
and marvellous effect accompanied his addresses;
though manifold also were those in which he was opposed, not only with resentment,
but cruelty.
A case of this kind occurred at Mansfield Woodhouse,
where the people fell upon him while he was, as he says, "`declaring the truth.`"
After being beaten and bruised till he was scarcely able to stand,
"`they put me,`" he continues, "`into the stocks, where I sat some hours;
and they brought dog-whips and horsewhips, threatening to whip me.
After some time they had me before the magistrates, at a knight`'s house,
where were many great persons, who, seeing how evilly I had been used,
after much threatening, set me at liberty;
but the rude people stoned me out of the town for preaching the word of life to them.`"

In these vicissitudes he passed his time till the year 1650, when he came to Derby,
accompanied by a friend of two.
Here he was received into the house of some person, whom he describes as "`a doctor,
whose wife was convinced,`" and, as he adds, "`several more in the town.`"

As he was walking in his chamber in this town, he heard the church-bell ring;
"`the very hearing of which,`" he says, "`struck at my life.
So I asked the woman of the house what the bell rung for.
And she said there was to be a great lecture there that day;
and many of the officers of the army, and priests and preachers were to be there,
and a colonel that was a preacher.
Then was I moved of the Lord to go up to them; and when they had done,
I spoke to them what the Lord commanded me, and they were pretty quiet;
but there came an officer, and took me by the hand,
and said I must go before the magistrates, and the other two that were with me.`"

His examination, which lasted several hours,
and which consisted chiefly in questions relative to the doctrines he preached,
was concluded about nine o`'clock at night,
by committing him and another man to prison for six months,
on the charge of "`uttering and broaching several blasphemous opinions,
contrary to a late act of parliament.`"
It may be requisite to remind the reader, that the king,
having at this period ended his life on the scaffold, and his son, an exile,
being proscribed by a declaration which made it treason
to promote him or any other person to the throne;
the house of peers being also abolished,
the parliament had assumed to themselves the government of the nation,
with the title of "`The Parliament of the Commonwealth of England;`"
and as the general character of this assembly was rigidly sectarian,
they viewed with a jealous and severe scrutiny,
such sentiments as were not in accordance with their own;
and as the views of George Fox differed more manifestly than those of most others,
so was the treatment which he and his adherents received at their hands,
more severe than that with which they visited the like offences in others.

The person who was committed with Fox, not being as deeply convinced,
or as sincere as his companion, recanted his opinions, and thus obtained his liberty.
"`But my spirit was strengthened,`" says George, "`when he was gone.`"

He employed himself during his confinement, in writing, according as he felt impelled,
to the priests, magistrates, and different authorities of the place;
warning them to consider of what they were doing, in persecuting those who, like himself,
were only desirous of promoting their best welfare.

It was in this place, and at this time,
that he and his followers received the appellation of Quakers,
of which he speaks in but few words.
Relating that it had been reported to him that one of the justices
remarked that they had been troubled for committing him to prison,
he adds, "`this was Justice Bennet, of Derby, who was the first that called us Quakers,
because I bid them tremble at the word of the Lord.`"

And, as by reason of his confinement,
he was restrained from going among the small community he had gathered together,
he visited them with an epistle, from which I shall make a few short extracts,
in the belief that they may not prove unprofitable to the reader; premising, however,
that some indulgence must be granted to the writer for the defects of his style,
on the score of his very limited education,
and also in regard to the inferior state of the times in literary advantages.
He begins by reminding them that the Lord discovers
unto man all the secret workings of the heart.
"`A man,`" he says, "`may be brought to see his evil thoughts, and running mind,
and vain imaginations, and may strive to keep them down; but he cannot overcome them,
nor keep his mind within to the Lord.
Now, in this state, submit to the spirit of the Lord that shows them,
+++[+++the vain imaginations, etc.,]
and this,`" he says, "`will bring to wait upon the Lord; and he that has discovered,
will destroy them.`"

He strongly urges this point, and bids them to mind the anointing which is in them,
and which is to teach them, and discover to them all the workings of their hearts.
And as they were taught, "`so obey and forsake,`" he says,
"`else you will not grow up in the faith, nor in the life of Christ,
where the love of God is received.
Now love begets love, its own nature and image.`"

He reminds them, that "`that which cannot bear the world`'s judgment,
is not the love of God; for love bears all things, and is above the world`'s judgment;
for the world`'s judgment is but foolishness.`"

He then points them to the diversity of modes in which the fallen nature manifests itself.
"`Some men,`" he says, "`have the nature of swine, wallowing in the mire;
and some men have the nature of dogs, to bite both the sheep and one another;
and some men have the nature of lions, to tear, devour, and destroy;
and some men have the nature of the serpent, (that old adversary,) to sting, envenom,
and poison.
'`He that has an ear to hear, let him hear,`' and learn these things within himself.`"

After dilating a little more on these resemblances, "`thus,`" he says,
"`the evil is but one in all, but it works many ways;
for whatsoever a man`'s nature is addicted to, the evil one will fit him with that,
and will please his nature and appetite, to keep his mind in his inventions,
and in the creatures, and from the Creator.

"`O, therefore, let not the mind go forth from God; for if it do, it will be stained,
and venomed, and corrupted; and if the mind go forth from the Lord,
it is hard to bring it in again.
Therefore mind that which is eternal and invisible,
and him who is the Creator and mover of all things; '`for the things that are made,
are not made of things that do appear.`'`"

And then, after a few words more of counsel,
he breaks out into a strain of thanksgiving affectingly fervent.
"`To you, O God,`" he says, "`be all glory and honour,
who are Lord of all visibles and invisibles; to you be all praise,
who brings out of the deep to yourself, O powerful God, who are worthy of all glory!
For the Lord who created all, and gives life and strength to all, is over all,
and merciful to all.
So you, who have made all, and are over all, to you be all glory!
In you is my strength, refreshment and life, my joy and my gladness,
my rejoicing and glorying forevermore!`"

How vain are bonds and imprisonments, or any other human infliction,
to the soul thus magnifying the Lord, and whose spirit thus rejoices in God its Saviour!
To such, there is but one language, "`It is well.`"^
footnote:[2 Kings 4:20]

It was not for the lack of friends to effect his release,
that George continued a prisoner; for his relations visited him,
and went to the magistrate that committed him,
offering to bail him in a security of two hundred pounds, (themselves in half the sum,
and two inhabitants of Derby in the remainder,)
that he should come there no more to preach.

But to this he would not consent; saying that he would have no man bound for him,
as he was innocent from all ill-behaviour in speaking the word of truth and life.
As this was spoken in the presence of the Justice Bennet above-mentioned,
"`he rose up,`" says George, "`in a rage;
and as I was kneeling down to pray to the Lord to forgive him, he ran upon me,
and struck me with both his hands, crying, '`Away with him,
jailer;`' whereupon I was had back again to prison,
and there kept until the time of my commitment was expired.`"
But though remanded back to confinement,
he had leave to take exercise beyond his prison walls.
"`I had the liberty,`" he says, "`of walking a mile by myself,
which I made use of as I felt freedom; and sometimes I went into the market and streets,
and warned the people to repent of their wickedness, and so returned to prison again;
and there being persons of several sorts of religion in the prison,
I sometimes went and visited them in their meetings on first-days.`"
Among those whom his preaching affected the most deeply, was the jailer of his prison.
This person, although, after the fashion of the times, a high professor of religion,
was nevertheless a very wicked man, and disposed, in the first instance,
to exercise much cruelty towards his prisoner; but afterwards,
being touched in conscience,
he came and acknowledged to him what he suffered on account of his severity.
"`I have been like a lion against you,`" he said; "`but now I come like a lamb,
and like the jailer that came to Paul and Silas, trembling.`"
He then opened to him the state of his mind, and confessed that,
whenever he had been requested by George to let him go and preach to the people,
and he refused him, he had experienced, subsequently, a distress,
which rendered him for a time, inaccessible to all comfort.

But, besides George Fox, there were now some others of both sexes,
holding the same views, and passing under the same denomination of Quakers,
who were induced, under a sense of being divinely called, to go forth and preach.

The absence, therefore, of the individual who, as to external means,
might be considered as their leader, was not any material hinderance to their progress.
In communities where the influence of human power of any kind, was recognized,
such a loss would, no doubt, have been deeply felt;
and in the infancy of an association so constructed,
would probably have been fatal to its continuance.
But the ground-work of George Fox`'s doctrine,
being to draw the mind away from all external dependencies,
to a clear acquaintance with the spark or principle of
eternal light and life within itself,
and this acquaintance with interior and heavenly power,
necessarily inspiring strong faith and unshaken confidence in the Divine Being,
there was a secret unity in this little band of believers,
which delivered them more than most other religious professors,
from any fear or probability of being scattered, or brought to loss,
under such a bereavement.
