== Chapter III.

While he was in confinement at Carlisle,
George Fox was visited by many different sorts of persons, both his name, principles,
and increasing followers,
having by this time rendered him an object of extensive fame and curiosity;
a circumstance, which,
added to a natural hatred of the kind of religion he taught and practised,
so much incensed his adversaries, that efforts, it seems,
were not lacking to consider the possibility of even taking his life.

"`When the court sessions came,`" he states,
"`all the talk and cry was that I was to be hanged, and the high-sheriff,
whose name was Wilfred Lawson, stirred them much up to take away my life,
and said he would guard me to my execution himself.`"
He also says,
that "`great ladies (as they were called) came
to see the man that they said was to die.`"
As closely was he guarded as if his crime had been of the blackest dye,
three musqueteers keeping watch upon him continually.
Nevertheless, the project of getting rid of him by the hand of the executioner,
was frustrated by some point of law, which, as he says,
"`confounded all their counsels;`" and this difficulty,
indisposing or incapacitating them for bringing him to trial,
he was left in prison at the time of the court sessions;
an act of cruelty which caused the Justice Pearson,
whom he had so greatly impressed by his preaching at Lancaster,
to address a letter to the judges and court in his behalf; and which,
as manifesting the view that was taken of his case by a judicious and educated man,
it may be desirable to give at length.

[.embedded-content-document.letter]
--

[.salutation]
"`To the judges of court sessions and jail-delivery for the northern parts,
sitting at Carlisle.

"`You are raised up to do righteousness and justice,
and sent forth to punish him that does evil, and to encourage him that does well,
and to set the oppressed free.
I am therefore moved to lay before you the condition of him who is called George Fox,
whom the magistrates of this city have cast into prison,
for words that he is accused to have spoken, which they call blasphemy.
He was sent to the jail till he should be delivered by due course of law;
and it was expected he should have been proceeded
against in the common law course at this court sessions.
The informations against him were delivered into court,
and the act allows and appoints that way of trial.
How hardly and unchristianly he has been hitherto dealt with, I shall not now mention;
but you may consider that nothing he is accused of has any bearing in the truth; and,
to my knowledge, he utterly abhors and detests every particular which,
by the act against blasphemous opinions, is appointed to be punished;
and differs as much from those people, against whom the law was made,
as light from darkness.
Though he be committed, judgment is not given against him;
nor have his accusers been face to face, to affirm before him,
what they have informed against him;
nor was he heard as to the particulars of their accusations;
nor does it appear that any word they charge against him is within the act.
But, indeed, I could not yet so much as see the information, no, not in court,
though I desired it both of the clerk of the court sessions,
and of the magistrates' clerk; nor has he had a copy of them.
This is very hard;
and that he should be so close restrained that his friends may not speak with him,
I know no law nor reason for.
I do, therefore, claim for him a due and lawful hearing,
and that he may have a copy of his charge, and freedom to answer for himself;
and that rather before you, than to be left to the rulers of this town,
who are not competent judges of blasphemy, as by their court order appears,
who have committed him upon an act of parliament,
and mention words as spoken by him at his examination, which are not within the act,
and which he utterly denies.
The words mentioned in the court order he denies to have spoken,
and has neither professed nor avowed them.^
footnote:[G. Fox's Journal, folio edit.
p. 101, 102.]

[.signed-section-signature]
"`Anthony Pearson.`"

--

But the friendly efforts of this gentleman were fruitless.
It was resolved not to bring George Fox to trial; and he was left,
at the close of the court sessions, to the jurisdiction of the magistrates of the town:
who testified what sort of favour he was likely to receive from them,
by ordering him into a still worse place of imprisonment than the jailer's house,
where he had hitherto been confined, but from which he was now removed into the jail,
amongst moss-troopers, thieves, and murderers;
the painfulness of whose society was augmented by the
accompaniment of every other sort of abomination,
which the filthy and degraded condition of prisons, in that age,
and of those that inhabited them, could exhibit.

"`Yet, as bad as the place was,`" he says,
"`the prisoners were all made very loving and subject to me,
and some of them were convinced of the truth, as the publicans and harlots were of old.`"

Amongst the persons who visited him, was one James Parnell,
whom he describes as a "`little lad of about sixteen years of age,`" and who,
though but a youth, received such deep convictions from the discourse of Fox,
that he gave himself, from that time, entirely to the service of God.
The displeasure, and even the renunciation of his relatives,
could in no degree shake his determination to unite himself to the Quakers,
amongst whom he became, in his eighteenth year, a valiant minister of the gospel.
"`Being imprisoned at Cambridge,`" says Sewel, "`for his zealous testimony,
and afterwards turned out of town like a vagabond, he soon came back,
and disputed with the scholars of the university,
but met with rude and bad entertainment from them.`"

This historian relates, that after preaching boldly at Colchester,
and with so much power that many embraced the
truth in consequence of hearing him declare it,
he was induced to go to Coggeshall, in Essex,
where a fast had been proclaimed to be held,
for the express purpose of praying against the errors of the Quakers.
James Parnell coming there at this time, went to the parish church,
the minister of which was an Independent;^
footnote:[The reader will remember, as observed before,
that at this period the Episcopal mode of worship was wholly abolished;
which will account for the seeming anomaly of an
Independent minister officiating in the parish church.]
and having remained silent till the preacher came out of his pulpit,
Parnell being of a society whose members had been just stigmatized as deceivers,
conceived that he ought (as Sewel observes) "`to say something to that.`"
He began his communication by observing, that "`the order of the true church prescribed,
that all may speak one by one, and if anything were revealed to him that stood by,
the first was to hold his peace.`"^
footnote:[2 Cor. 14:30-31.]

He then proceeded in defence of the doctrines of Friends, in the course of which,
as usual, some jangling occurred on the side of his opponents;
and amongst other objections, it was stated against him,
"`that he acknowledged no church;`" which he denying to be true,
and being asked what church he acknowledged, he said, "`the church in God.`"

A priest of the name of Willis then stood up, and said he spoke nothing but nonsense.

Parnell replied by desiring him to specify what nonsense he had spoken.

"`For saying the church in God,`" said Willis.

Upon this Parnell took out his Bible, and read 1 Thess. 1:1,
where the apostle writes to "`the church which
is in God the Father;`" and therefore he said,
it was he, Willis, that was a blasphemer, in saying that,
"`the church in God`" was nonsense.

The vanquished Willis was then reinforced by a minister of the name of Stellum,
who having accused Parnell of uttering slanders and falsehood,
without suffering him to justify himself, got up into the pulpit, and began to pray!
But Parnell not taking off his hat, a commotion ensued,
which he ended by quitting the church.

He had not proceeded far before a justice of the peace followed him,
and striking him on the shoulder, said he arrested him in the name of the Lord Protector,
Oliver Cromwell; and after passing an examination, which, when it concerned the Quakers,
was rather a matter of form than of equity,
he was fined to the value of above forty pounds,
on the ground of contempt for the magistracy and ministry,
and in default of payment to be committed to prison;
and as it was not the practice of the sufferers in this society,
to acknowledge themselves delinquents, as they virtually would have done,
by paying fines for misconduct, Parnell was carried to Colchester prison,
where none of his friends were suffered to visit him.

The sequel of the narrative is more than commonly melancholy,
even amidst the many painful details of the sufferings of the primitive Friends;
for the jailer and his wife being both exceedingly
bitter against persons of his persuasion,
seemed to vie with one another which should torment him the most;
the woman more particularly, by setting others to take away his food,
refusing to let him have a bed to lie upon,
even when his friends in the town would have brought him one,
and in every possible way that she could devise, afflicting him.
At last, because he did not seem to these barbarians to be sufficiently persecuted,
he was put into a place called the Hole in the Wall,
which Sewel says that he himself had seen,
when he visited James Parnell`'s prison at Colchester;
and which prison he described as "`an old ruinous castle, built, as it was reported,
in the time of the ancient Romans.`"
The "`Hole in the Wall,`" he says, was "`a room much like a baker's oven;
for the walls of that building, which is indeed a direful nest,
are of an excessive thickness, as I have seen myself,
having been in the hole where this pious young man ended his days.
Being confined in the said hole, which was, as I remember,
about twelve feet high from the ground, and the ladder too short by six feet,
he must climb up and down by a rope on a broken wall, to fetch his food, etc.;
for though his friends would have given him a cord, and a basket to draw up his food in,
yet such was the malice of his keepers that they would not allow it.`"

He then states, that owing to the dampness of this wretched place,
his limbs became benumbed; and thus it once happened,
that as he was climbing up the ladder with his food in his hand,
and catching at the rope by which he was to reach his dwelling, he missed it,
and fell down upon the stones, exceedingly wounded in his head,
and altogether so much hurt as to be taken up for dead.
One might have hoped,
that in this pitiable condition he would have been placed in a less miserable apartment;
but his abode was only changed from an upper to a lower oven,
there being two rows of them one over another; and that which he occupied after his fall,
was, if possible, worse than the former; for, when the door was shut,
there being no window or aperture to admit the air, he was almost suffocated;
and although several of his friends in the town offered to pay
down a sum of money for his reappearance after his recovery,
if he might be permitted to come to the house of one of them,
till he was restored from the effects of his accident, yet it was denied; no,
so immovably were they set against him, that, according to Sewel,
they would not permit him to walk out for the benefit of the air,
even in the yard of the prison;
and the jailer once finding him walking between two high walls, in a narrow yard,
from which, had he been inclined, he could not have escaped,
was nevertheless so incensed against him, that he locked up the hole he inhabited,
and shut him out in the yard all night, though it was in the coldest time of the winter.

Such complicated hardships concluded, as might be expected,
in the dissolution of the perishable part; but in that which is imperishable,
this young and innocent sufferer was more than
conqueror over the combined malice of his enemies.

After ten or eleven months' endurance of their cruelties, he fell sick; and then,
it appears, that two of his friends, named Thomas Shortland and Ann Langley,
were allowed to be with him.

During their attendance upon him, feeling his end approach, he turned his head to Thomas,
and said, "`This death I must die--I have seen great things--do not hold me!`" meaning,
"`do not wish to keep me with you,`" or "`do not detain me by praying for my recovery.`"
He then said again, "`Will you hold me?`"
To which Ann Langley replied, "`No, dear heart, we will not hold you.`"
The last words he was heard to utter, were, "`Now I go.`"
He then stretched himself out, and having fallen into a sleep which lasted about an hour,
he breathed his last.
The circumstance of his sleeping for an hour just before his decease,
was thought remarkable by those about him,
because he had often been heard to say during his sickness,
that one hour's sleep would cure him of all.`"

These particulars of the sufferings and death of James Parnell,
Sewel states that he himself received from the mouth of eye-witnesses,
who lived at Colchester at the time of his imprisonment.

Indeed, had they not been too truly attested, such instances of inhumanity as the above,
(and they were fearfully numerous in the annals of the society,)
could scarcely have been received as authentic.
We do not immediately, nor very easily,
detect the deep root from which the peculiar antipathy
and consequent persecution of these persons arose.
It has been touched upon,
but it is not by a cursory glance that the aversion can be exhibited in its true colours;
the philosophic mind must search for it in the deepest depths of the human heart.
It may be said, perhaps, that their harsh, disrespectful mode of address,
or the occasional criticism in their addresses,
drew ill-usage upon the primitive Friends; but instances were frequent,
in which their very silence was the means of their giving the greatest offence.
A curious case of this kind is recorded respecting Miles Halhead,
one of the ministers of the society.
Coming, in the year 1653, to Furness, in Lancashire,
he went to the house of a Captain Adam Sands,
where a large meeting of religious professors had assembled,
and where the minister Lampitt (already mentioned as being at Swarthmore,
when George Fox first appeared there) was preaching;
but immediately on the entrance of Halhead he became silent, which continuing,
for a considerable time, the captain enquired if anything was the matter with him,
fearing he might be suddenly taken ill; to which the minister replied, "`I am well;
but I shall speak no more, as long as this dumb devil is in the house.`"
"`A dumb devil!`" said the captain, "`where is he?`"
"`This is he,`" said the minister, pointing with his hand to Halhead,
"`that stands there.`"
"`This man is quiet,`" said the captain, "`and says nothing to you.
I pray you, sir, go on, in the name of the Lord, and if he trouble or molest you,
in my house, I will send him to Lancaster castle.`"

But in vain was the request, the only answer he obtained was,
"`I shall not preach as long as this dumb devil is in the house.`"

Thus unsuccessful with one preacher, the captain tried what he could do with another;
and turning to one Camelford, who was also a minister, "`I pray you, sir,`" said he,
"`stand up and exercise your gift, and I will see that you be not disturbed.`"
But he met with the same reply; this one answering like the other,
"`I shall not speak as long as this dumb devil is in the house.`"

So extraordinary an effect from the presence of a silent man,
began to create an alarm in the assembly, and several of the people cried out,
"`The Lord rebuke you, Satan!
The Lord rebuke you, Satan!
What manner of spirit is this that stops our ministers' mouths!`" and at length,
as the only resource, the captain came to Halhead, and taking him by the hand,
led him out of the house; in all which time the man had never spoken a single word.^
footnote:[Sewel's Hist.
(Lindfield edit.) vol.
i.p. 201.]

But it is time now to return to George Fox, whom we left in Carlisle prison,
in very bad company, and with little prospect of being released from their society.
However, it happened that a report of his case coming to the knowledge of the parliament,
by whose authority the country was at that time governed,
a letter was sent down to the sheriff and other magistrates concerning him,
and not long after he was liberated.
And now the society having much increased, not only in members,
but also in able ministers, their doctrines began to be more generally known,
and considered;
and although the persecution they met with from hypocritical professors of religion,
and profane deriders of it, was in no degree lessened;
yet the general integrity and uprightness, not merely of their principles,
but their practice, had gradually removed the prejudices which, in the first instance,
threatened to impoverish them,
by causing the different customers of such of them as were in trade,
to cease from dealing with them.

"`But afterwards,`" says George, with his accustomed simplicity,
"`when people came to have experience of Friends' honesty and faithfulness,
and found that their yes was yes, and their no was no,
that they kept to a word in their dealings,
and that they would not swindle and cheat them;
but that if they sent a child to their shops for anything,
they were as well used as if they had come themselves;--
the lives and conduct of Friends did preach,
and reached to the witness of God +++[+++in the conscience]
of the people.`"

"`Then things altered so,`" he goes on to say, "`that all the enquiry was,
where was a draper, or shop-keeper, or tailor, or shoe-maker,
or any other tradesman that was a Quaker?
Insomuch that Friends had more business than many of their neighbours,`" etc.

In the same plain way, he afterwards speaks of the approbation which,
when more duly organized, and their different meetings permanently established,
their orderly mode of conducting the society's affairs,
and their method of assisting the poor, extracted even from their enemies.
"`When they saw Friends' books,`" he says,
"`and accounts of collections for the relief of the poor, how we took care,
one county to help another, and to help our friends beyond sea, and provide for our poor,
that none of them should be chargeable to their parishes,
etc. the justices and officers confessed that we did their work,
and would pass away peaceably and lovingly, commending Friends practice.
Sometimes,`" he proceeds, "`there would come two hundred of the poor of other people,
and wait till the meeting was done,
(for all the country knew we met about the poor,) and after the meeting,
Friends would send to the baker's for bread,
and give every one of those poor people a loaf, how many soever there were of them;
for we were taught to do good unto all, though especially to the household of faith.`"

There being at this time (1654) above sixty ministers in the society, who were,
for the most part, travelling in the service of truth,
the fame and name of the Quakers began to spread in other parts of the kingdom,
as well as in the northern counties, to which it had primarily been chiefly confined.
But as it would exceed the limits proposed in this brief sketch,
to enter into any minute detail of their proceedings,
I am compelled to pass by the history of many in the society,
whose eminent and faithful services deserve to be recorded by a far abler pen;
and to confine the narrative to the labours of such of them as
were more particularly prominent in the work of the ministry,
amongst whom the name of George Whitehead must not be omitted.

This individual was a native of the north of England,
and educated in the Presbyterian mode of faith, in which,
finding many things that displeased him,
and hearing of the newly-risen society of the Quakers,
(so called,) he determined to attend one of their meetings,
in which he was much affected by perceiving how greatly
the spirits of most of those who were there assembled,
seemed broken and contrited; more especially in the case of a young woman, who,
on quitting the meeting, he observed to sit down upon the ground,
"`with her face towards the earth, as if,`" he says, "`she regarded nobody present, but,
moaning bitterly, cried out, 'Lord, make me clean!
O Lord, make me clean!' which,`" he adds,
"`did far more tenderly and deeply affect my heart than what I had heard spoken,
and more than all the preaching that ever I had heard from man or men;
and was a certain testimony to me,
(the Spirit of the Lord evidencing to my spirit,) that
it was a real work of his power upon her heart,
which also operated upon the hearts of others, causing both trembling, sorrow,
and contrition.`"^
footnote:[G. Whitehead's Journal, p. iii.
from which source all that relates to him in this work is taken.]

Such is the result of the preaching which is not of man,
but "`in the demonstration of the Spirit, and of power.`"
It is not uncommon for persons gifted with intellectual advantages,
to convince the understanding, and affect the feelings; but to wound the conscience,
and prompt an earnest sympathy in the psalmist's prayer, "`make me a clean heart, O God,
and renew a right spirit within me`"--is the province only of that ministry,
which stands not in the wisdom of men, but in the power of God.
In consequence of his impressions, Whitehead quitted the Presbyterians,
and joined the Quakers, in the earliest days of their society,
and at a youthful period of his own life, being but eighteen years of age,
when he felt himself called upon to go forth in the ministry.
Bending his course on foot, towards the eastern parts of the kingdom,
he arrived at Norwich, where Richard Hubberthorn, another minister of the society,
was then imprisoned upon the usual plea of sedition and blasphemy.

In this city George Whitehead stayed some time, holding several meetings,
and visiting his imprisoned friends, to their mutual strength and comfort:
but it was not long before he himself shared the same fate;
for on attempting to speak upon one occasion, at St. Peter's church,
be was committed to the same jail where several more of his friends were also lodged.

In this place he underwent many hardships, of which he gives a curious statement.
"`In the said prison at Norwich,`" he writes, "`we were but hardly treated by the keeper,
one Hunt, who demanded for one bed for three of us, four-pence a night of each:
we thought it was hard measure to demand twelve-pence a night of prisoners,
for one mean bed for three men to be crowded together in,
and that in a cold room where another prisoner lodged in a bed to himself;
so that not finding freedom to gratify the jailer in his oppression and covetousness,
and afraid to bring any charge upon any of our friends,
to procure us better accommodation,
on these considerations we thought ourselves
necessitated to lodge upon the bare boards on the floor,
in our wearing clothes, and little covering besides;
and thus we lodged for eight weeks together, in the cold winter; whereby,
though we endured much cold, yet were we, through the Lord's mercy,
generally preserved in health.
Such kind of hardship,`" he adds, "`I might think the greater to me,
having been tenderly brought up by my parents,
and then so young as but about eighteen years old, that same winter,
when thus imprisoned in 1654.`"

In the month of March, 1655, he and James Lancaster, another Friend,
were released from captivity; but Whitehead going to the jail a short time after,
to visit a person, was apprehended; and on being taken before the mayor,
was re-committed, and again imprisoned for three weeks.
No record of oppression and grief can surpass, and few can equal,
those of the primitive Friends,
in the instances wherein their patience was proved and manifested,
by unjust and long imprisonments; which, in many cases, were no sooner ended,
than they began again; and we must remember,
that lightly and amusingly as these things pass over the mind in reading of them,
there are few sorrows of a more trying kind, than the incarceration of the body,
accompanied with all that can molest and oppress the spirit.

Once more at large,
George Whitehead proceeded from place to place in the counties of Norfolk and Suffolk,
preaching as he travelled,
and gathering many to more serious and solid views of
divine things than they had before entertained;
insomuch that numbers in these parts of the kingdom, were, at this time,
induced to unite themselves to the society.
In the early part of his ministry in these counties,
he felt the lack of a suitable co-worker; his dear and highly-gifted friend,
Richard Hubberthorn, being still detained in prison; but after Richard's release,
he speaks with much satisfaction of the meetings
they held as fellow-labourers in the cause.

Having, for the present, concluded his services, in the eastern counties,
he turned his face towards London; but some circumstances occurred,
which occasioned a delay in his travels there,
and which will be best given in his own words:--

"`After considerable labour and service in testimony
for the truth and gospel of Christ Jesus,`" he says,
"`in Norfolk and Suffolk, in the year 1654 and 1655,
besides the imprisonment in Norwich before related, my dear friend Richard Clayton and I,
meeting again in High Suffolk, in the fifth month, 1655,
travelled into Essex to Colchester,
where James Parnell (that early servant of Christ) was prisoner in the castle;
he being committed but a little time before.
We visited him in prison; he was given up to suffer for his faithful testimony,
was comforted in our visit, and we were glad to see him so well,
being under that confinement.
So we travelled forward on foot towards London,
being desirous to see our brethren and friends in that city, if the Lord had permitted.
We went that day from the White Elm, near Ipswich, to near Chelmsford, on foot,
being above thirty or near forty miles; and on the road,
meeting with our dear friend and brother, George Fox, and Amos Stoddart,^
footnote:[A military man by profession, when first brought into acquaintance with Friends.
George Fox, speaking of him in his Journal, as a Captain Stoddart,
(p. 14,) at a meeting held by several religious professors at Mansfield, in 1648, says,
"`a captain, named Amos Stoddart, came in;`" at the close of which meeting,
G+++.+++ F. being opposed in what he had advanced, touching the blood of Christ,
this captain claimed for him a hearing, saying,
"`Let the youth speak!--hear the youth speak!`"
and being convinced by means of his preaching,
Amos Stoddart joined the society in its infancy, and became a steady,
faithful member and minister thereof, to the end of his life.]
coming from London into Essex, we were very glad to see them;
insomuch that our desires of going forward, were in part answered for that time,
and we were willing to stay with them at some meetings in Essex, which we did.`"

He then speaks of having a good meeting in Essex,
in which he found many who were favourably disposed to the truth,
owing to the preparation for its reception, which the ministry of the youth,
James Parnell, had effected on their hearts; for, as he observes,
"`James Parnell had been instrumental to convince many in those parts, that summer,
before his imprisonment at Colchester; and by his testimony and living ministry,
many professors were shaken, and at a loss in their professions and notions,
which they had gathered in their heads,
without experience of a true heart-work by the power of Christ.
For profession and talk of religion and church, did greatly abound in those days,
amongst many, as well as pride and self-conceit;
which the Lord was about to stain and abase, as he manifestly did in a short time after;
for those summer shows of religion, would not endure a stormy winter.
I must confess to the glory of God in my own self-abasement,
and his bearing sway over my will and affection, by his own power, wisdom,
and providence, I was at that time prevented from going to London,
to visit my brethren and friends there, according to my own desire and affection;
the Lord having then more work and service, as well as suffering for me to go through,
in the country; and particularly in the county of Suffolk,
before I might obtain my desire of going to London.
Having had blessed and effectual service, by the special assistance of the Lord's power,
in Norfolk and in High Suffolk, I must now be a sufferer in Low Suffolk,
and bear my testimony for him in a hard confinement, and inhuman treatment in prison.

"`For in those days,
among the exercises which befel many of us whom the Lord so early called,
and sent forth to preach the gospel of repentance unto life and salvation, we were led,
moved, and excited at one time to run to and fro,
that knowledge might increase among people in the ways and dealings of the Lord;
and at other times to be snapped up, taken and imprisoned,
strictly confined and severely used, and many times inhumanly and barbarously treated,
as the subsequent accounts may in part show;
and also what manner of spirit did rule and act in some sorts of men,
under high professions, and great pretensions of religion, and Christianity,
and how unchristian under these, they were in practice.`"

The circumstances of suffering to which the
foregoing statements of George Whitehead refer,
were his being apprehended, and again sent to prison,
on the ground of his being "`a disturber of the public peace.`"
His place of confinement, in this instance, was the common jail, at Bury St. Edmunds;
where he was committed, with five others, who were also of the society,
about the beginning of August, 1655.

His account of the usage they received in this prison,
is as instructive as it is curious;
conveying to the mind which is disposed to receive it,
a simple and affecting lesson of trust in God, and submission to his holy will,
under privations and oppressions, which, without religious aid,
it would have been impossible for humanity to endure.

"`After two of us,`" he says, "`were first sent to prison,
we had a lodging in an upper room, for two or three weeks; and then,
understanding that the jailer would exact upon us for rent,
and expecting our confinement might be of long continuance, we desired a free prison;
whereupon we were turned into the common ward among felons; where,
after continuance a few weeks, a friend, (Samuel Duncan,) in compassion to us,
privately gave the jailer some money to let us lodge above again, from the felons.
But, when the time for that money was ended,
the jailer insisted upon his old exaction of four-pence a night from each of us;
which we were neither free to yield to,
nor to allow any of our friends to be charged therewith, but again desired a free prison;
and thereupon we were again turned into the common ward.`"

"`We now were settled in the common ward among felons, in a low dungeon-like place,
under a market-house; our poor lodging being upon rye-straw, on a damp earthen floor;
though we were therewith content, and the place sanctified to us.
But not being willing to contribute to the jailer's avarice or extortion,
nor free to buy any of his beer, (he keeping a tap-house,
and many of his prisoners often drunk,) his anger and rage arose,
and grew very much against us, after we were so many as five sent to prison successively,
one after another, and all in the common ward,
and in the time of our confinement drinking only water.`"
He then states, that his anger was increased,
because George and his friends testified against the disorders and abuses
which he occasioned by allowing excessive drinking among the prisoners.
It may be thought that it was not without reason, that the preachers amongst friends,
were led to testify against the general hypocrisy of the professors of that day,
seeing that in many cases, as in the present one,
their persecutors were those who made a claim to be called religious.

"`The Lord stirred us up,`" says Whitehead,
"`to cry aloud against the wickedness of the jailer, his servants, and prisoners,
for these gross evils and disorders,
because the jailer made a profession of religion and piety,
(being a member of a Presbyterian church in Bury,)
calling in the prisoners on first-days,
towards evening, to instruct them; and because I told him of his hypocrisy therein,
his fruits being so much contrary, his daughter was offended, saying,
'What! call my father a hypocrite, who has been a saint forty years!'`"

And then,
in evidence of his not having unjustly been accused of
bringing forth fruits that were contrary to righteousness,
George Whitehead proceeds to narrate some of the instances to which he alluded;
of which it may suffice in general terms to say,
that they evidenced a barbarity of heart towards
the helpless and harmless Quakers under his care,
which it is shocking to humanity to contemplate.
Yet, in the midst of these atrocities,
the spirits of the sufferers were exalted by the sustaining power of God,
and enabled to soar above that region in which the
persecution of men or devils had power to operate.
On one occasion, George Whitehead, with three more Friends, were put into a dungeon,
four yards under ground, by this inhuman jailer and his turnkey,
because they would not desist from crying against the wickedness that surrounded them.
He describes the place by saying, "`it was very dark,
and but a little compass at the bottom, and in the midst thereof an iron grate,
with bars above a foot distant from each other, and under the same, a pit or hole,
we knew not how deep; but being warned thereof by a woman that saw us put down,
and pitied us, we kept near the sides of the dungeon,
that we might not fall into the said pit, and there we were detained near four hours,
singing praises to the Lord our God,
in the sweet enjoyment and living sense of his glorious presence;
being nothing terrified nor dismayed at their cruelties;
but cheerfully resigned in the will of the Lord,
to suffer for his name and truth's sake.`"

Of the extent of their trials, not merely from the keeper of the prison,
but from the wickedness of the prisoners,
who were generally encouraged by him to molest these patient people,
he relates a striking instance.
After mentioning one of the culprits who was the most rude and abusive to them,
("`being,`" as he says,
"`one of the jailer's drunkards,`") and the circumstance of
his throwing a knife fiercely at one of them,
and as it missed inflicting a wound, his declaring that he would kill some of them,
he relates, "`the said most abusive prisoner,
taking so much encouragement as he did from the example of the jailer, turnkey,
and tapster, one night, being furiously drunk, he must needs kill some of us,
after we were locked and bolted close in the common ward; whereupon,`" he continues,
"`in faith in the name and power of the Lord, we stood over him,
believing be should not have power to hurt any of us,
though he attempted it by taking up a firebrand, etc.

"`He had a boy,`" he continues, "`in the same ward, about ten years old,
(as supposed,) and as the boy was kneeling by the wall,
and frightened to see his father in such a rage,
the father presently took up an earthen or stone bottle,
and violently threw it at his own poor affrighted boy, but missed him,
and broke it to pieces against the wall, the poor boy narrowly escaping with his life;
for, if it had hit him on the head, he had probably been killed.
Still the drunken, outrageous fool continued in his fury:
he must needs kill somebody that night, either his poor boy, or some other,
or else he would not be pacified.
Seeing him thus murderously resolved, it immediately came upon me with great weight,
as I believed from the Lord,
'let us not see murder committed in our presence;' whereupon,
I said to my fellow-sufferers,' let us seize on him, and hold him hand and foot,
till he will be quiet;' whereupon they presently laid hold upon him,
laid him gently upon his back, and held him fast hand and foot, as I think,
above an hour's time; in which he made a roaring noise, but to no purpose;
for we were all closely warded up in a low, dark place,
hard to be heard in other parts of the prison; no, I am persuaded,
if any of us had cried out 'Murder!' we should
scarcely have had one come to relieve any of us!`

"`We glory in tribulation,`" says the blessed apostle;
and those that follow him "`who was made perfect through sufferings,
have ever poured forth the same triumphant acknowledgment,
even in the midst of the purifying furnace.
"`I am still truly humbled and thankful,`" says George Whitehead, when,
many years afterwards, he reverted to these fiery trials;
"`I am still truly humbled and thankful to the Lord our God,
in remembrance of his great kindness to us;
how wonderfully he supported and comforted us,
through and over all these our tribulations, strait confinement, and ill-usage,
and preserved us in bodily health.`"
And speaking of the painfulness of the circumstances which attended their imprisonment,
in regard to the filth and abominations of the place in which they were kept;
"`yet,`" says he, "`the Lord by his power, so sanctified the confinement to me,
that I had great peace, comfort, and sweet solace;
and was sometimes transported and wrapt up in spirit, as if in a pleasant field,
having the fragrant scent, and sweet smell of flowers, and things growing therein.`"

He says that the happiness enjoyed by him and his companions, surprised the prisoners.
Speaking of the merciful support and consolations of God,
"`in the comfortable enjoyment of his glorious,
divine power and presence,`" he says "`several of us have
often been made to sing aloud in praise to his glorious name;
yes, his high praises have been in our mouths,
oftentimes to the great amazement and astonishment of
the malefactors shut up in the same ward with us.
When walking therein, our hearts have been lifted up in living praise to the Lord,
often for several hours together, with voices of melody.
Oh the sweet presence and power of the Lord our God,
how precious to be enjoyed in prisons and dungeons!
Oh, my soul, still bless the Lord, and forever praise his excellent name, for the true,
inward sense and experience you have often, and long had, and still have,
of his divine power, and unspeakable goodness!
Glory and dominion be to our God,
and to the Lamb that sits upon the throne forever and ever!`"

Beautiful strains of Zion! which, when the King of sufferers hears,
"`he sees of the travail of his soul,
and is satisfied!`" who would exchange them for a thousand years of this
world's empty joys! "`Your joy no man takes from you,`" was a promise,
the sweet realization of which, the primitive Friends experienced as often and as truly,
as most of the followers of Him who gave it.
Nor were they ever backward in restoring the praise thereof to Him to whom it was due;
as the above testimonials, and many more, abundantly show.
But that all-wise Dispenser of what is needful for his servants, who says,
"`I will not contend forever, neither will I be always angry;`" knowing,
to a hair's breadth, what measure of purification we stand in need of, and can endure,
now saw fit to grant a reviving interval to these sufferers, by making way,
in the course of his providence, for their liberation from prison.

"`When the barbarous treatment and hardships we
endured in the said jail,`" says Whitehead,
"`was much noised abroad,
many of our friends at London were compassionately concerned for our relief;
and thereupon, Oliver Cromwell was several times applied unto,
and particularly by Mary Sanders, a friend of ours,
who was a waiting-gentlewoman in Cromwell's family.
She often took her opportunities to remind him of our suffering condition,
and of other friends also being confined in various prisons, as she has often told me.`"

The result of these or other intercessions,
occasioned an order to be sent down for their discharge;
of which he gives the following copy:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Thursday, the 16th of October, at the Council at Whitehall.

"`Ordered by his Highness the Lord Protector and the council,
that the Quakers imprisoned at Colchester, in the county of Essex, and Edmundsbury,
and Ipswich, in the county of Suffolk, be forthwith released and set at liberty;
and it is referred to Sir Francis Russell to take care that the same be done accordingly;
as also to consider how the fines set upon them,
or any of them (if any) may with most conveniency be taken off and discharged;
and likewise to take order, that upon their being set at liberty, as aforesaid,
they be forthwith sent to their respective homes.

[.signed-section-signature]
"`W. Jessop, clerk of the council.`"

--

Being thus aided,
George Whitehead and his friends were not long before they received their freedom;
and "`although,`" he says, "`our hardships in Bury prison were extreme,
yet the Lord caused all to work together for good unto us.
Our faith and strength in Christ came to be greatly increased;
the blessed truth promoted; many convinced thereof, and added to the church,
and gathered into our spiritual communion and society,
through the great sufferings of those times, and our faithful testimony therein.`"

One of the persons confined at this time with him, was another George Fox, who,
though senior in point of age,
always distinguished himself from the founder of the society,
by humbly styling himself George Fox the younger.
He was a faithful and gifted minister,
and steadfast in bearing a powerful testimony against all iniquity.

It would occupy more time than we can spare,
to narrate the many further persecutions which befel George Whitehead,
in the course of his travels and ministerial labours,
before he found his way back to his parents, whom, after three years' absence,
he desired to visit.
Compared with his long and hard imprisonment at Bury, his trials were unimportant;
though, upon one occasion,
his being ordered by a Justice Gusden to be whipped for a vagrant, and on another,
his being put into the stocks for several hours,
were not light exercises of his patience.
At length,
through "`evil report and good report,`" he was favoured to reach his native place,
where he met with a welcome reception from his parents, who,
as he says had esteemed him either lost or dead;
and finding the great hardships and persecutions he had undergone,
they received him with great joy and kindness, and with less prejudice than heretofore,
against the principles he had adopted, and the society to which he had united himself.
