== Chapter V.

But a few months elapsed after the loss of his beloved friend thus tenderly lamented,
when Francis Howgill was himself cast into prison.
Being engaged in some business at Kendal in Westmoreland, about the latter end of May,
1668,
he was summoned by the high-constable to appear before
the justices of the peace then present at a tavern,
for the purpose of taking the oath of allegiance and supremacy;
but on the oath being tendered to him, declining it on conscientious grounds,
he was forthwith committed to Appleby goal, where he was kept till the court sessions;
and the same oath being then again tendered him, and he again declining it,
he was indicted, but had liberty to answer to the indictment the next court sessions.

Appearing then in court, the judge, (whose name was Twisden,) observing,
in his charge to the grand jury, that there was a sort of people, who,
under pretence of conscience and religion,
seemed to build upon the king's declaration from Breda,^
footnote:[When it was resolved by the English nation to recall Charles II. from exile,
and place him as lawful heir upon the throne, the king being then at Breda,
gave forth a declaration, in which, amongst other indulgences, he promised as follows,
respecting religion:--
{footnote-paragraph-split}
        "`And because the passion
and uncharitableness of the times have produced several opinions in religion by
which men are engaged in parties and animosities against each other,
which, when they shall hereafter unite in a freedom of conversation, will be composed,
or better understood; we do declare a liberty to tender consciences,
and that no man shall be disquieted or called in question for
differences of opinion in matters of religion,
which do not disturb the peace of the kingdom;
and that we shall be ready to consent to such an act of the parliament, as,
upon mature deliberation,
shall be offered to us for the full granting of that indulgence.`"]
and under colour of this, hatched treasons and rebellions,
he recommended them to enquire after and present such,
that the peace of the nation might be preserved.

The jury being empanneled, and Howgill called to the bar,
the judge made nearly the same statement to him respecting the hatching of plots,
under pretence of conscience.
"`Not,`" says he, "`that I have anything to charge you with;
but seeing the oath of allegiance was tendered to you the last court sessions,
and you refused to take it,
it was looked upon that such persons were enemies to the king and government.`"
He then said, "`I will not trouble you now to answer to your indictment,
but I must do that the next court sessions;
in the meantime you must enter into recognizance for good behaviour.`"

This being declined,
on the just and becoming ground of his not having violated the rules of good behaviour,
and had therefore no need to be bound over to keep them; seeing also, that he was bound,
by the love of the truth which he professed, not to misbehave himself;
he was given till the next day to consider of it: but at that time,
persevering in his intention of declining both the oath and the bond,
he was committed to prison, where he was detained about five months,
after which he was brought to a final trial.

That he might not seem obstinate,
he drew up a paper containing the substance of the oath arranged under several heads,
which he declared himself willing to subscribe,
though for conscience sake he could not agree to swear.
He also drew up another paper,
addressed to the judge (Turner,) showing the court the cause of his first commitment,
and the former proceedings against, him,
and how unequal it was that they waived the other
statutes lately made against nonconformists,
and prosecuted him upon a statute formerly made against Catholic recusants +++[+++
those who would not recongnize or submit to the Church of England]
. He said,
that it was merely upon a spiritual and conscientious account that he could not swear,
seeing it was against the command of Christ, and the apostles' doctrine.
He said also, that he was able to make it appear,
that it was against the example of the primitive Christians for several hundred years,
and therefore no new opinion.
That it was neither in wilfulness nor obstinacy, that he refused it,
being sensible of the damage that would ensue if they prosecuted him on that statute,
he having a wife and children, and some small estate,
which he knew lay at stake in the matter; but if it were his life also,
he said he could not revolt from, or deny that which he had most certainly believed in.
But if any persons could convince him that he was in error,
either by Scripture or reason, he had an ear to hear.`"

These papers were delivered in court, and read before he was called in.
When he appeared and was permitted to speak,
a great deal of discussion ensued respecting his determination to refuse the oath;
and amongst other reasons that he gave in justification of it, he said,
"`that some of the principal pillars of the Church of England, as, for instance,
Bishop Usher, sometime Primate of Ireland, had said in his works,
that the Waldenses did deny all swearing in their age,
from the command of Christ and the apostle James, and that it was a sufficient ground.
"`And Dr. Gauden,`" said he, "`late Bishop of Exeter, in a book of his I lately read,
cited very many ancient fathers to show, that, for the first three hundred years,
Christians did not swear; so that it is no new doctrine.`"

But in vain were all his pleas! the business closed by the judge pronouncing
the following sentence upon him;--"`You are put out of the king's protection,
and the benefit of the law: your lands are confiscated to the king during your life,
and your goods and chattels forever, and you to be a prisoner during your life.`"

"`A hard sentence,`" said Francis, "`for my obedience to the law of Christ!
The Lord forgive you all!`"

So he turned from the bar, but the judge speaking, he turned again,
and many more words passed to the same purpose as before, the judge saying,
that if he would be subject to the law, the king would yet have mercy upon him.

"`The Lord has showed mercy unto me,`" said Howgill,
"`and I have done nothing against the king, nor government, nor any man;
blessed be the Lord, therein stands my peace, for it is for Christ's sake I suffer,
and not for evil doing.`"

Being remanded back to a captivity which was to continue during his life,
Francis Howgill did not sink into sloth or despondency.
His prison labours breathe a sublime spirit which indicated
that the thraldom of the outward man did but the more nobly
enlarge the liberty of the hidden man of the heart.

He was chiefly occupied with his pen, writing many epistles to Friends, who,
at that time, being severely persecuted,
and from their faithful adherence to their
testimony in respect to tithes and taking oaths,
suffering more than those of other religious persuasions,
stood in need of having their hands strengthened by the
counsel and example of the elders of the church.
How well and faithfully he helped to do this,
may be seen in almost every letter he addressed to them,
a few extracts from one of which is here subjoined.

He entitles it, "`A visitation of love, peace, and good will to the whole flock of God,
now in their day of trial and hour of temptation.`"
He commences by reminding them how graciously they had
been visited of God with divine illumination,
and exhorts them to be watchful that the adversary in these perilous times,
get no advantage over their faith.
"`He is let loose,`" he says, "`for a season.
Blessed are they that hide themselves under the shadow of the Almighty,
and under the wings of Christ Jesus, who is given for a Redeemer, a Saviour,
and a Preserver of men, that the wicked one touch them not.

"`This is the day of the Lamb's war indeed, and a day of battle,
though his weapons are not carnal but spiritual.
And there is none that goes to war, and that has a purpose to hold out,
and is resolved to continue with him in suffering,
but will shake off those things that encumber, lest he should not obtain the victory,
promise, or crown, which all that endure hardship to the end, shall receive.
Oh, dear friends! look above all visible things, and stand out of them all,
and loose from them, that the enemy do not ensnare you.`"

Then reminding them of many examples from Scripture, as of Abraham, Daniel, Shadrach,
etc. who held not their lives dear for the testimony of Jesus, he comes nearer home,
and asks, respecting their own community, "`Have not many died in prison with hard usage?
Have not some been hanged, and died a shameful death,^
footnote:[At this time four members of the Society had
been publicly put to death in America.]
and finished their course with joy and peace?
Have not many endured great, hard, and long imprisonments for years,
and are they yet weary?
No, have not many suffered great spoil of their goods,
and have they not a reward seven-fold into their bosom?

"`Oh! let the consideration of these things dwell upon your hearts,
and provoke you unto suffering with joyfulness; that, in the midst of all tribulation,
as it abounds, you may feel, according to the promise of God, your joy much more abound,
to carry you above it.
Indeed, now is the time come,
that he that will manifest himself to be on the Lord's side, must suffer;
and he that will not, but turns back into the broad way,
and runs with the herd of swine into the sea of common pollution, must perish there;
and indeed there is no place for halting: if God be God, follow him; if Baal be he,
go after him.
And therefore,
let none draw you aside from that which you are persuaded of in your conscience,
by the Spirit of the Lord; neither join with that +++[+++which]
you know he disallows; and in obedience, you will have peace and joy.
Look not at them which draw back, for they go to perdition;
but rather after them that continue faithful, that shall receive honour, glory,
immortality, and everlasting life.`"

After a few more words of exhortation,
he thus affectionately concludes:--"`The God of
heaven and earth establish all your hearts,
that you may glorify him in your generation,
and be a sweet smell unto him in bonds or liberty, in life or death,
is the prayer of him who has besought the Lord,
and is determined so to do on all your behalf, till the Lord by his power,
tread Satan under your feet, that you may triumph over all,
rejoicing and praising God and the Lamb, that lives forever and forevermore.
Amen! "`Your dear brother in the patience and sufferings of Christ,
who abounds in perfect love to all the faithful flock of Christ everywhere.

"`F. H.

"`From Appleby jail, the place of my rest, where my days and hours are pleasant unto me;
the 4th of the 5th month, 1664.`"

I should do injustice to any sketch however slight, of this good man's character, if,
in noticing his epistles, I were to omit making mention of that to his daughter,^
footnote:[Now published as a tract for distribution.]
which he calls "`the unchangeable testament, and will, and counsel of Francis Howgill,
left to his daughter, Abigail Howgill,`" and which, with solemn fervour,
he enjoins her to observe, saying, it is the chief thing he has to bestow upon her.

"`Seek the kingdom of God,`" he says, "`and the righteousness thereof;
it is not far from you, it is within you; it consists of life and power,
and it stands in righteousness, truth, equity, justice, mercy, long-suffering, patience,
love, light, and holiness.
This is the being and centre thereof;
therefore seek not lo here! or lo there! without you,
in this or that outward observation, for many seek there and never find it; but seek,
and you shall find; wait, and you shall receive.

"`If you enquire in what must I seek, and what must I wait in, and how must I seek?
I inform you, you must silence all your own thoughts,
and you must turn your mind to that which is pure, holy, and good within yourself,`" etc.

He much urges and insists upon this, as indeed being the basis of his own faith.
"`Take heed unto that, +++[+++i.e. the holy life, or light within,]
and it will show the evil motions and thoughts, and as you love it, it will subdue them,
and preserve you for the time to come, out of evil;
for though you be born into the world a reasonable creature, yet, you must be born again,
and be made a new creature, or else you can not enter into God's kingdom.`"

He therefore proceeds to set before her the necessity of
understanding how this new and divine birth is to be produced.
And here in passing, I would venture to suggest,
as worthy of the reader's deep consideration,
the views which this wise and pious parent presents to his child,
on this all-important subject.

"`You must know the seed of the kingdom in yourself,`" he says;
"`of which you must be born and formed again, into God's image.
I have told you that God has sown it in you;--a grain of it, a portion of it,
a measure of light and truth, of righteousness and holiness.
Keep in your mind to that, and love it,
and you will feel the Heavenly Father working in you, and creating you to life,
through Jesus Christ, who has enlightened you,
and you will feel the power of the Lord strengthening you in your little,
+++[+++faith and obedience,]
and making you to grow in the immortal seed of his kingdom,
and to out-grow and overgrow all evil; so that you will daily die to that +++[+++evil]
and have no pleasure in it; but in the Lord,
and in his goodness and virtue shed abroad in your heart,
which you will taste and feel within, and have joy and comfort therein.`"

Again reverting to the same subject, "`God is a Spirit,`" he says,
"`a pure spirit of life, light, and power.
He it is that searches the heart, and shows you when you do evil, or think evil,
or speak evil; and shows unto men and women their thoughts.
That which shows the evil is good, and that which shows a lie is truth.
This is within, take heed to it.
This is called God's Spirit in the Scriptures; believe in it, love it,
and it will quicken your heart to good, and it will subject +++[+++or subjugate]
the evil.
Here is your teacher near you; love it.
If you act contrary to it, it will condemn you, etc.
This Spirit never errs; but leads out of all error into truth.`"

Such was the religion of Francis Howgill! a
religion which enabled him and thousands more,
to stand their ground in a day of no ordinary proving.
Yet, strange as it is, beyond all comprehension, this religion,
breathing nothing but purity and peace--this religion,
which has been the comforter and counsellor of saints and martyrs in all ages,
is the religion which is generally the most decried, as unsafe, unscriptural, and unholy,
and which, in its manifestation amongst the primitive Friends,
drew down upon them a spirit of tenfold hatred and persecution.
Would we know why?
The answer is at hand; in the heart, and in the conscience.
It was too true--too real a religion; it went to the root--it did its work there.
It held for nothing the lopping off the branches and the leaves,
and the making clean the outside of the cup and platter.
It recognized no lip-professions,
no doctrines of free grace which sanctioned the belief that the most holy
God could account them to be righteous who were yet under the power of sin.
But let us, as a last extract, hear what Francis Howgill, (in some sense,
we must remember, a martyr for the truth,) says, in another portion of his works,
respecting the free grace of God.

"`The grace of God is his free gift: it is the appearance of Christ.
It is that through which God makes known his will, and by which he teaches us.
He reveals his saving health through it to those who are taught by it;
and those who are taught by it are built up in the truth through it,
and become a habitation for God.
No man can do anything to purchase it; none need say, where can I get it;
or how may I know its teachings?
It is near all, it is in all, it has appeared to all;
and it shows ungodliness in the heart of man by its brightness; yes,
it shows all men the motions to sin; it draws the heart of men from them;
it never joins to sin; nothing can alter its purity or property,
and though some who have turned to it, have again turned from it,
and may turn in themselves to licentiousness, yet it still keeps its purity,
and reproves their licentiousness.`"

"`Many,`" he goes on to say, "`have been talkers of it, in this professing age,
who have neither known of what they spoke,
nor have informed the minds of men where it was to be waited for,
nor how it might be known, nor how, nor what the operation of it was;
but have said in their own imaginations,
'we are justified by his free grace from all sin, past, present,
and to come;' and in this conceit, thousands have been led into the pit of darkness,
imagining that they were justified by the free grace of Christ,
while they were out of the fear of God which it would have taught them,`" etc.
"`All you,`" he says, "`that have been preaching free grace in words, and now,
when God has given those that have waited upon him,
an understanding to declare the thing itself that you have spoken of,
and which you now cry is not a sufficient teacher--let me ask you a question;
Is that which teaches to deny ungodliness, not a sufficient teacher?
If it be not, why did the apostles commend the believers to the word of his grace,
which was able to save their souls?
(Acts 20:32; JamEst. 1:21) Is not that which is able to save the soul,
a sufficient Teacher?`"

"`Seeing, then, that God's free grace, which is his pure appearance,
has thus manifested itself; and that God through it, shows sin, and leads from it;
and that God has so loved the world, that he sent his Son into the world, who was,
and is the light of the world, and has shed abroad his grace and made it appear to all;
and all that wait upon it, come to be taught by it, and feel its assurance;--therefore,
all are without excuse.
Wait therefore in that which has appeared in you; for that which shows the lust,
and thoughts, and motions to sin, is God's gift, God's grace, and is sufficient;
and though all men in the world should say it is not, yet,
this would not make your faith void, nor mine, who have received it;
because we have the witness of our faith in ourselves;
which gives pure and perfect feeling of the operation of the Spirit of the Lord;
which saves all them that believe in it, out of sin, and gives them dominion over it.`"^
footnote:[From a selection from the works of Howgill, published by James Backhouse.]

If this reasoning should still seem insufficient,
I would ask the doubting reader to consider these words,
with which we will conclude the subject: "`The grace of God, that brings salvation,
has appeared to all men, teaching us that, denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly in this present world.`"
(Titus 2:11-12)

The meek resignation and Christian patience with
which Francis Howgill endured his imprisonment,
procured him the love and esteem of the jailer and his family,
and also of many others in the town of Appleby;
and such was the confidence reposed in him,
that many persons resorted to him for counsel in their difficulties,
and referred their differences to his arbitration.

He was declining in health about the year 1668;
and towards the close of it was taken ill; and though his sickness increased,
and at length his dissolution drew nigh, his faculties were preserved clear,
and he was often engaged in fervent supplication.
About two days before his departure, his beloved wife and several friends being present,
he observed to them that he felt but little on his mind to communicate.
"`As to the matter of words,`" said he, "`you must not expect much more from me;
neither is there any great need of it; as to speak of matters of faith to you,
who are satisfied--only that you remember my dear love to all friends who inquire of me;
for I ever loved friends well, or any in whom the truth appeared.`"

More he said to the same effect; adding, "`as for me, I am not at all afraid of death.`"
Indeed, he had often been heard to say, during his sickness,
that he was content to die--that he was ready;-- and that he praised
God for the sweet enjoyments and refreshments he had received on that,
his prison-house bed, whereon he lay;
freely forgiving all who had any part in his restraint.

Several persons of note, as the Mayor of Appleby, and others dwelling in the town,
went to visit him; some of whom praying that God might speak peace to his soul,
he replied, "`he has done it.`"
A few hours before his departure,
some friends who lived at a distance coming to visit him;
he inquired of the welfare of all of them; praying fervently,
with many heavenly expressions, that the Lord, by his mighty power,
might preserve them out of all such things as would pollute or defile them.
Something he was heard to say shortly afterwards; but his weakness being extreme,
but little could be gathered, except a few words,
which seemed prophetic of a time when persecution would cease.
A little while after, regaining some strength, he said,
"`I have sought the way of the Lord from a child, and lived innocently as among men;
and if any inquire concerning my latter end,
let them know that I die in the faith which I lived in, and suffered for.`"

After a few words of prayer to God, he spoke no more;
but entered into his blissful and everlasting rest, in the fiftieth year of his age,
having been a prisoner for the testimony of Jesus, nearly five years.

