== Chapter XI.

In the year 1660, the rightful heir to the throne being restored to his dominions,
the whole face of public affairs was changed;
and from the sombre appearance which the nation had
worn in the days of the sectarian commonwealth,
it then went to the other extreme of manifest and almost unbridled licentiousness.

It was not very likely in this state of things,
that an appeal from a plain man like George Fox,
could tend to stop the current of iniquity which was streaming through the country;
but believing himself called upon to witness against it,
he attacked it at its chief source, in the following curious address to the king;
which he thus introduces in his Journal:--

"`I was moved, also, to write to the king,
to exhort him to exercise mercy and forgiveness towards his enemies,
and to warn him to restrain the profaneness and
looseness that was got up in the nation on his return.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To The King.

[.salutation]
"`King Charles,

"`You entered not into this nation by sword, nor by victory of war,
but by the power of the Lord.
Now if you do not live in it +++[+++that is, the power of the Lord]
you will not prosper.
If the Lord has showed you mercy and forgiven you, and you do not show mercy and forgive,
God will not hear your prayers, nor them that pray for you.
If you do not stop persecution and persecutors,
and take away all laws that hold up persecution about religion; if you persist in them,
and uphold persecution, that will make you as blind as those that have gone before you.
For persecution has always blinded those that have gone into it; +++[+++and]
such God by his power overthrows, does his valiant acts upon,
and brings salvation to his oppressed ones.
If you bear the sword in vain, and let drunkenness, oaths, plays, and May-games,
with such-like abominations and vanities, be encouraged or go unpunished,
as setting up of May-poles with the image of the crown a-top of them,
etc. the nations will quickly turn like Sodom and Gomorrah,
and be as bad as the old world, who grieved the Lord till he overthrew them;
and so he will you, if these things be not suppressed.
Hardly was there so much wickedness at liberty before, as there is at this day;
as though there was no terror nor sword of magistracy; which does not grace a government,
nor is a praise to them that do well.
Our prayers are for them that are in authority, that under them we may live a godly life;
in which we have peace, and that we may not be brought into ungodliness by them.
Hear, and consider, and do good in your time, while you have power.
Be merciful and forgive; that is the way to overcome, and obtain the kingdom of Christ.

[.signed-section-signature]
"`G. F.`"

--

At the time of writing this epistle, George was a prisoner in Lancaster Castle;
where he had been roughly taken, while visiting his friend Margaret Fell at Swarthmore,
and committed on the plea of being a disturber of the nation;
but the court order which more particularly
specified in what way he created disturbances,
he could not obtain a sight of.
The only favour granted him, was permission that two of his friends might read it,
at a visit they made the jailer to request a copy thereof;
and being able to retain and repeat to him the substance of it, (which, in general,
was simply what has been stated,
with the addition of his holding fanatic
opinions,) he answered it by a sort of manifesto,
which is far too lengthy for insertion as it stands;
but from which a few extracts may be acceptable.

[.embedded-content-document.letter]
--

"`I am a prisoner at Lancaster, committed by Justice Porter.
A copy of the court order I cannot get; but such expressions I am told are in it,
as are very untrue;
as that I am generally suspected to be a common disturber of the nation`'s peace,
an enemy to the king, and that I with others, should endeavour to raise insurrections,
etc.; all which is utterly false, and I do, in every part thereof, deny it.

"`And whereas Major Porter says, I am an enemy to the king, this is false;
for my love is to him, and to all men; even though they be enemies to God,
to themselves, and to me&hellip;
It is much he should say I am an enemy to the king; for I have no reason so to be;
he having done nothing against me.

"`And whereas he says, that I, together with others of my fanatic opinion,
as he calls it, have of late endeavoured to raise insurrections, etc.;
this is altogether false.
To these things I am as a child, and know nothing of them.
The postures of war, I never learned; my weapons are spiritual, and not carnal,
for with carnal weapons I do not fight&hellip;
And as for the word fanatic, which signifies '`furious, foolish, mad,`' etc.,
we are not furious, foolish, or mad; but through patience and meekness, have borne lies,
slanders, and persecutions, many years, and have undergone great sufferings.
The spiritual man that wrestles not with flesh and blood,
and the Spirit that reproves sin in the gate, which is the Spirit of truth, wisdom,
and sound judgment, is not mad, foolish, furious, which fanatic signifies:
but all are of a mad, foolish, furious spirit, that wrestle with flesh and blood,
and with carnal weapons, in their furiousness, foolishness and rage.
This is not the Spirit of God, but of error, that persecutes in a mad, blind zeal,
like Nebuchadnezzar and Saul.`"

He subscribes this paper,

[.signed-section-closing]
"`From an innocent sufferer in bonds, and close prisoner in Lancaster Castle; called

[.signed-section-signature]
"`George Fox.`"

--

In the meantime many exertions were making on the part of his friends,
towards his emancipation; Margaret Fell going herself to London,
to petition the king in his behalf.
In this purpose she was joined by Ann Curtis, whose father, a sheriff of Bristol,
had been executed in the past times, for endeavouring to aid the restoration of the king:
upon the strength of which circumstance, she was kindly received by Charles,
and an order given,
that his secretary should desire George Fox to be had up for a hearing in London.

"`But when they came to the secretary for the order,`" says George,
"`he said it was not in his power; he must go according to law,
and I must be brought up by a habeas corpus, before the judges.`"

Accordingly an order was sent,
and delivered to the sheriff (signifying it was the king`'s pleasure
he should be sent up by a habeas corpus.) "`But because it was
directed to the Chancellor of Lancaster,`" he continues,
"`the sheriff put it off to him; on the other hand,
the chancellor could not make the warrant upon it, but said the sheriff must do that.
At length both chancellor and sheriff were got together; but being both enemies to truth,
they sought occasion for delay, and found an error in the order; which was,
that being directed to the chancellor it said,
'`George Fox in prison under your custody`'--Whereas the prison I was in,
was not in the chancellor`'s custody, but the sheriff`'s;
so the word your should have been his.
Upon this, they returned the order to London again, only to have that one word altered.`"

When it is remembered,
that these were days in which the mail-bags were not carried by railroads, and probably,
not even with the dispatch of a carrier`'s cart,
it will seem no ordinary trial of patience,
to have to wait in prison the outcome of such frivolous mistakes.
But the principles of that faith which George professed and practised,
had their deepest root and most nourishing growth,
in circumstances of this exercising kind.
Hence Isaac Penington, in one of his letters, desires a suffering friend,
to "`Prize inward exercises, griefs, and troubles;
and let faith and patience have their perfect work in them.`"

When the order was altered and brought down again,
the matter was never the nearer being settled;
"`for the sheriff refused to carry me up,`" says George,
"`unless I would seal a writing to him, and become bound to pay for the sealing,
and the charge of carrying me up; which I denied;
telling them I would not seal anything to them, nor be bound.
So the matter rested awhile, and I continued in prison.
Meanwhile the court sessions came on; but as there was an order for removing me,
I was not brought before the judge.`"

It was long before the sheriff would yield the point of removing him to London,
without his consenting to bear the expense thereof;
at last finding him immoveable on this point,
he was desired to put in bail for his appearance in London on such a day,
in which case he was to have permission to go there in his own way,
and with any of his friends.

"`I told them,`" he says, "`I would neither put in bail,
nor give one piece of silver to the jailer; for I was an innocent man;
they had imprisoned me wrongfully, and laid a false charge upon me.
Nevertheless, I said, if they would let me go with one or two of my friends,
I might go up and be in London on such a day, if the Lord should permit;
and if they desired it, I, or any of my friends that went with me,
would carry up their charge against me.

"`When they saw that they could do no otherwise with me,
the sheriff consented that I should go with some of my friends,
without any other engagement than my word, to appear before the judges in London,
such a day of the term, if the Lord should permit.`"
Accordingly, being released, after a few visits among his friends, he,
at the appointed time, appeared in London, carrying his own charge with him; which,
having delivered into the hands of the proper authorities, he repaired,
as he was directed to do, at a certain time, to the bar of the King`'s Bench,
accompanied by some of his friends.

"`I was brought into the middle of the court,`" he says, "`and as soon as I came in,
I was moved to look about, and turning to the people said, '`Peace be among you!`'`"

The charge against him being read, and some emotion testified on the part of the court,
at the statement which represented him and his friends
as attempting to embroil the nation in blood,
by raising a civil war, etc. he stretched out his arms, and exclaimed,
with a simplicity quite his own, "`I am the man whom that charge is against;
but I am as innocent as a child concerning it.
I have never learned any war postures.

"`Do you think,`" he continued,
"`that if I and my friends were such men as the charge declares,
that I should have brought it up myself, against myself?
or that I should be suffered to come up, with one or two of my friends with me?
Had I been such a man as this charge sets forth,
I had need to have been guarded up with a troop or two of horse.
But the sheriff and magistrates of Lancaster,
thought fit to let me and my friends come up with it ourselves, almost two hundred miles,
without any guard at all; which you may be sure they would not have done,
if they had looked upon me to be such a man.`"

The result of the whole was, that,
after having been a prisoner somewhat more than twenty weeks, he was,
by the king`'s command, liberated.

"`Some degree of quietness was at this time enjoyed by friends in their meetings;
the king, in good humour with his pleasant reverse of circumstances,
being disposed to extend his protection to them;
"`Richard Hubberthorn,`" says George Fox, in his Journal, "`had been with the king,
who said, none should molest us, so long as we lived peaceably;
and promised this upon the word of a king,
telling him we might make use of this promise.`"

An account of this conversation of Richard Hubberthorn`'s with the king,
was published by Richard shortly after, and is preserved in Sewel`'s History,
from which the following extracts are taken.

Having stated to the king the sufferings from persecution which friends had endured,
Charles replied, "`It is true; those that have ruled over you, have been cruel,
and have professed much which they have not done.`"

"`To which Richard replied, that the same sufferings still abounded in the nation;
many friends being in prison,
because they could not burden their consciences
by taking the oath of allegiance and supremacy.

[.discourse-part]
"`__King__--But why cannot you swear?
for an oath is a common thing among men to any engagement?

[.discourse-part]
"`__R. H.__--Yes: it is manifest, and we have seen by experience,
that it is so common among men to swear, and engage either for, or against things,
that there is no regard taken to it, nor fear of an oath.
That therefore, which we speak of, in the truth of our hearts,
is more than what they can swear.

[.discourse-part]
"`__King__--But can you promise before the Lord?
which is the substance of an oath.

[.discourse-part]
"`__R. H.__--Yes; what we do affirm, we can promise before the Lord,
and take him to our witness in it.
But our so promising has not been accepted;
but the ceremony of an oath they have stood for; without which,
all other things were accounted of no effect.

[.discourse-part]
"`__King__--But how may we know from your words, that you will perform?

[.discourse-part]
"`__R. H.__--By proving us: for they that swear, are not known to be faithful,
but by proving them; and so we, by those that have tried us,
are found to be truer in our promises, than others by their oaths;
and to those that do yet prove us, we shall appear the same.

[.discourse-part]
"`__King__--Pray what is your principle?

[.discourse-part]
"`__R. H.__--Our principle is this;
that Jesus Christ is '`the true light that enlightens every one that
comes into the world,`' that all men through him might believe;
and that they are to obey and follow this light, as they have received it;
whereby they may be led unto God, and unto righteousness, and the knowledge of the truth,
that they may be saved.`"

Some further discourse ensued upon the subject of the sacrament,
in which the lords in waiting also joined; after which, the king asked him,
"`How know you that you are inspired by the Lord?`"

[.discourse-part]
"`__R. H.__--According as we read in the scriptures,
that '`the inspiration of the Almighty gives understanding,`' so, by his inspiration,
is an understanding given us of the things of God.`'

One of the lords in waiting then inquired,
"`How do you know that you are led by the true spirit?`"

[.discourse-part]
"`__R. H.__--This we know, because the Spirit of truth reproves the world of sin; and by it,
we are reproved of sin, and are also led from sin unto righteousness,
and obedience of truth; by which effects, we know it is the true Spirit;
for the spirit of the wicked one does not lead into such things.`"

The king and his courtiers both agreed to the truth of this; and Charles,
apparently well pleased with the plain sense of his visitor, then said; "`Well,
of this you maybe assured;
that you shall none of you suffer for your opinions or religion,
so long as you live peaceably; and you have the word of a king for it;
and I have also given forth a declaration to the same purpose, that none shall wrong you,
or abuse you.`"

After a few more questions and answers, the king in a courteous manner, withdrew.

At this time the face of affairs, as it respected the society,
wore a more smiling aspect than it had ever done before.
About seven hundred friends, who in the time of the Commonwealth,
had been committed to prison (for contempt,
as stated in their accusations,) were set at liberty;
and some were even admitted in the House of Lords,
to specify their reasons for refusing to take oaths, pay tithes,
or conform to the national mode of worship.
But suddenly, these flattering appearances were clouded with disappointment;
for the insurrection of the Fifth Monarchy men,
causing the seceders generally to be accused of a share in it, the society of friends,
though one of the most harmless of the body of dissenters, were, as usual,
stigmatized with the suspicion of being the most offending.

A declaration of their principles and faithfulness to their king and country,
was put forth by them in writing, and presented to the king; which, George Fox says,
"`did somewhat clear the dark air that was over the city and country; and soon after,
the king gave forth a proclamation,
that no soldiers should search any house without a constable.
But the jails,`" he says, "`were still full; many thousands of friends being in prison;
which mischief was occasioned by the wicked rising of those Fifth Monarchy men.`"

Much blood,`" he continues, "`was shed this year;
(1660;) many of the old king`'s judges being hanged, drawn, and quartered.
Among those that suffered, Colonel Hacker was one,
who sent me prisoner from Leicester to London, in Oliver`'s time.
A sad day it was; and a repaying of blood with blood.
But there was a secret hand in bringing this day
upon that hypocritical generation of professors;
who, being got into power, grew proud, haughty, and cruel, beyond others,
and persecuted the people of God without pity.`"
Perhaps a more living portrait of the characters and conduct of those, who,
in the preceding times had usurped authority,
cannot easily be found than in these few lines.

"`Yet some of them,`" says George, "`were so hardened in their wickedness,
that when they were turned out of their places and offices, they said,
if they had power they would do the same again.
And when this day of overturning was come upon them, they said, it was all along of us.
Wherefore, I was moved to write to them and to ask,
did we ever resist them when they took away our ploughs and plough-gear,
our carts and horses, our corn and cattle, our kettles and platters from us?
and whipped us, and set us in the stocks, and cast us into prison, and all this,
only for worshipping and serving God in spirit and truth,
and because we could not conform to their religions, customs, manners and fashions?
Did we ever resist them?
Did we not give them our backs to beat, our cheeks to pull off the hair,
and our faces to spit upon?
Why then would they say, it was all along of us?`"

He concludes this cogent appeal by stating, that,
notwithstanding all the depredations they had
suffered at the hands of these their enemies,
friends could praise God, "`that they had a kettle, a platter, a horse,
and a plough still.`"
