== Chapter XII.

Among the sufferers in consequence of the insurrection above mentioned,
was George Whitehead, already introduced to the reader`'s notice; who,
with some other friends, was taken while attending a meeting in Norfolk,
and once more committed to his quondam residence in Norwich Castle.

Of their lodgings in this place, he gives the following account:
"`There being a hole in a corner of the castle wall, called the Vice,
we betook ourselves to that to lodge in, though a poor narrow place,
without any chimney in it; yet, there we got up two little beds, and lodged two in each;
John Lawrence and his brother Joseph, in one bed, and William Barber and I, in the other.
It was a very incommodious habitation and lodging room, for lack of a chimney;
and having an old decayed stone arch over it, the rain came in so much upon us,
that we could not well keep it off our beds,
though we set dishes and basins to keep off what we could.
In the cold of winter, we burnt a little charcoal in evenings,
which we found somewhat injurious, and suffocating, having no chimney to vent the smoke;
and in the daytime, we endeavoured often to keep ourselves warm,
by walking upon the castle-hill, and under the wall,
(being within the liberty of the prison): though it was but a cold bleak place in winter,
yet we were glad that we had that benefit of the air.

"`Our friends, William Barber and John Lawrence,
having been men of note and captains in the commonwealth`'s day,
it appeared in them a great piece of self-denial and subjection to the cross of Christ,
to suffer so patiently for his name and truth`'s sake, in such a poor,
incommodious lodging.
I remember one morning when we were in bed, Joseph Lawrence, after his pleasant manner,
said to his brother John, "`Oh, Captain Lawrence,
I have seen the day that you would not have lain here!`"

During this imprisonment, George Whitehead had so severe an attack of ague,
that some of his friends, supposing it would end in his dissolution,
were ready to take their last leave of him.
"`I was one night in particular,`" he says,
"`sorely affected with the smoke of the little charcoal fire,
and earnestly called to have it presently put out,
otherwise I questioned whether I should live till next morning.`"

In this suffering state, he was, nevertheless, required to take a journey to Thetford,
there to take his trial with his companions: of which he gives the following account:--

"`The time for our appearing at the spring court sessions at Thetford drawing near,
I believed I should be enabled to ride there: for,
we were all to appear there who were prisoners for our religious meetings;
and in order to my going to the court sessions, my horse was brought to the prison-door,
three days before the court sessions began.

"`I rode with John Lawrence to his house at Wramplingham, on the seventh day of the week;
it being five or six miles on my way towards Thetford,
and stayed there the next day and night following.
But that day, I had again a very sick fit of the ague,
but grew better before the next day; and then we took horse for Thetford, being about,
or above twenty miles from Norwich.
The weather being cold, a hail-shower overtook us,
and I was again taken with a fit of ague on the road, before we got to Thetford: yet,
with the Lord`'s help, I held on, and grew better before,
or by the time we came to Thetford;
and that same afternoon could readily walk up to the
top of that noted mount or hill which is by the town.
We met the rest of our friends who came from Norwich Castle, at Thetford prison,
where we were in the daytime, after the court sessions began;
but at night we had liberty to lodge at our friends houses, in or near the town.`"

Judges Hale and Windham were then upon this circuit; but unhappily, for the poor friends,
their cause, instead of coming before the benevolent Hale,
fell into the hands of Windham; who,
"`terribly threatened dissenters,`" says Whitehead,`" and such
as would not go to the parish church and conform,`" etc.
He also, in his charge, gave notice of many ancient penal laws, made against such;
and caused some of them to be read in court; insomuch that "`an ancient friend,
Elizabeth Hawes, then living at Snare Hill, near Thetford, gave me a full account,
with tears, after she had heard the said charge.
She, being very sorrowful, to see how they were bent on persecution, to encourage her,
I signified, that the Lord would plead our cause, and stand by us;
and I would have no friends discouraged, but be faithful to the Lord,
and valiant for the truth upon earth.`"

The usual inquiry of what had brought them from their own home,
into that part of the country, having been asked, and the usual reply,
"`to preach repentance, and bear testimony to the truth,`" having been answered,
they were required to take the oath of allegiance; which,
being with their accustomed steadfastness declined,
they were all remanded to the prison in Thetford,--and after being again examined,
and persisting in their determination not to swear, six of them,
(among whom was George Whitehead,
and his aforesaid friends,) were sent back to Norwich Castle; from which,
after an imprisonment of sixteen weeks,
they were at last released by the king`'s proclamation of grace, wherein, notwithstanding,
says Whitehead, "`his grace or favour thereby expressed towards the Quakers,
it was not without a menace or threat, i.e. '`not intending their impunity,
if they should offend in the future, in like manner as they had done,`'`" etc.

As such a clause was not likely to operate upon the constancy of the Quakers,
however it might upon that of some other dissenters,
this proclamation of grace produced but little grace for them.

Their fixed principle respecting the question of oaths,
laid them peculiarly open to oppression;
and when they fell into the hands (as they commonly did)
of those who were maliciously disposed towards them,
it presented a means of afflicting them, which was constantly and cruelly resorted to.^
footnote:[The clause which particularly affected the society in this respect,
was the eighteenth,
in "`An Act to prevent and suppress seditious Conventicles,`"
and which was substantially as follows:--
{footnote-paragraph-split}
"`And in regard a certain sect called Quakers,
and other sectaries,
are found not only to offend in the matters provided against by this act,
but also to obstruct the proceedings of justice,
by their obstinate refusal to take oaths lawfully
tendered unto them in the ordinary course of law:
(2) Therefore be it further enacted by the authority aforesaid,
that if any person or persons being duly and
legally served with process or other summons,
to appear in any court of record,
etc. shall refuse to take any judicial oath legally tendered to him, etc.; that then,
and in such case, the several and respective courts in which such refusal shall be made,
shall be, and are hereby enabled to record such refusal, etc.;
which record or entry shall be, and is hereby made, a conviction of such offence:
and all and every person and persons so, as aforesaid, offending,
shall for every such offence incur the judgment and punishment of transportation in
such manner as is appointed by this act for other offences.`"]

"`Upon that occasion,`" says George Fox, "`friends published in print,
'`The grounds and reasons, why they refused to swear:`' besides which,
I was moved to give forth these few lines following, to be given to the magistrates:--

"`The world says, '`kiss the book but the book says, '`kiss the Son,
lest he be angry;`' and the Son says, '`swear not at all;`' but keep to yes and no,
in all your communications; for whatsoever is more than this, comes of evil.
Again the world says, '`lay your hand on the book;`' but the book says,
'`handle the word;`' and the word says, '`handle not the traditions, nor the inventions,
nor the rudiments of the world.`'
And God says, '`this is my beloved Son, hear him,`' who is the life, the truth, the light,
and the way to God.

"`G. F.`"

As this reasoning may be somewhat too concise,
a few observations upon the subject are inserted from a work of Isaac Penington`'s,
entitled, "`The great Question concerning the Lawfulness or Unlawfulness of Swearing,
under the Gospel, stated,`" etc.^
footnote:[Penington`'s Works, in 2 vols, quarto.--1st vol. p. 435.]

He considers, in the first place, "`what an oath is?`"

"`A true and lawful oath under the law,`" he says,
"`was an engagement or bond upon the soul, (Numbers, xxx, ii.) by the name of the Lord,
(Duet. 10:20) to the speaking of truth in things affirmed,
and to the performance of truth in things promised.
It was a seal to bind fallen man +++[+++that is, man fallen from truth and uprightness]
to truth in his words and promises, either to God or man.`"

He inquires secondly, into the ground or occasion of an oath,
which he states to be "`the fall of man from truth and innocency,
and the uprightness which made truth natural to him before his fall.`"
"`This,`" he says, "`made the Jews stand in need of this bond, under the law,
in then purposes and promises towards God;
and the same thing made them stand in need of it one from another,
to ratify and confirm truth between them.`"

Thirdly: in what case was an oath to be used?
He specifies four occasions in which it was chiefly required.

[.numbered-group]
====

[.numbered]
I+++.+++ In case of a promise or vow to God.

[.numbered]
II. In case of promise to man.

[.numbered]
III. In case of pronouncing or declaring the truth of a thing, etc.

[.numbered]
IV. In case of controversy between parties, where it could not be determined,
but by taking the confession of one party for truth.

====

He goes into further divisions of the subject; but those above stated,
comprise the substance of the rest.

He then speaks of four states or conditions of the soul, since the creation,
preparatory to his applying the matter to the case of friends.

[.numbered-group]
====

[.numbered]
1+++.+++ A state of integrity, wherein man could not lie nor deceive.

[.numbered]
2+++.+++ A state of deep captivity to evil, etc.

[.numbered]
3+++.+++ A state of shadowy redemption from evil, etc.,
wherein were figures of heavenly things--but not the very things themselves.

[.numbered]
4+++.+++ A state of true redemption, which state, he thanks God,
is (after a long night of apostasy) again brought forth.

====

And here it may be necessary to add for the information of those who are but
little acquainted with the principles of the primitive friends,
that this view of complete redemption from evil, was the groundwork of their hopes,
their sufferings, and their joys.
In a word, they trusted to "`go on unto perfection.`"

"`In this state`" (of true redemption) he says, "`the soul is brought back from death,
from captivity, from deceit, from the fall, and from the shadows, into truth,
wherein Christ (the power of God) is witnessed,
and the soul newly formed in his pure image,
is become '`a new creature;`' having a new eye, a new ear, a new heart, a new nature,
a new life and spirit, (in the newness of which life,
it is to live and walk,) etc. wherein all old things that came in by the fall,
and all the old shadows of the law, are to pass away.`"

In one of the above-mentioned conditions, he says, that all men have been to be found;
and according to that state and condition in which man is found,
is the law of God to him, and his requirings of him.

"`Now, let any man, in the fear of the Lord God,`" he continues, "`weigh and consider,
to which sort, or sorts of these, an oath was useful in itself, and allowed by God,
and to which not.
Was it useful in the innocent state?
Or is it useful in the redeemed state, where a greater bond is received,
and professedly held forth, than the innocency of man`'s nature was?
Were not all the oaths and shadows of the law to last till Christ the substance came?`"

"`Men may reason subtly,`" he says, "`and persuade strongly, against the truth;
but we know certainly and infallibly, in the light of the Lord,
that the use of an oath was not for man in innocency;
nor for man under the power and virtue of the redemption by Christ;
(which brings man back into the truth,
and into that life and strength which preserves in truth;) but, for fallen man;
for man erred from the truth, and covenant of God.
And it is very manifest to us, that for a disciple of Christ,
who has received the law from his lips against swearing,
to be brought back again to swearing (the bond of man in the fallen state,
and under the law) is no less than a denial of Christ,`" etc.

Towards the end of this tract, he addresses himself to the king.

"`Now, O king,`" he says, "`shall not God`'s people be faithful and obedient to the Lord,
as well as to you?
Has God raised up in them a principle which cannot deceive,
and will not the yes and no of that serve, after so much experience,
through so many changes, but they must either break Christ`'s command,
and hazard their souls, or else lose their liberties and estates?

"`Oh! that men would wait on the Lord,`" he exclaims,
"`for his pure fear to be written on their hearts, by the finger of his Spirit;
that they might come out of the fleshly wisdom, into the eternal wisdom,
from which our principle came: that they might be able to see, and justify, the purity,
righteousness, nobility, and worth of it;
and that they might feel its security from all that is out of good will, out of love,
out of life, and out of peace; and so, there might be an end of all strife, rebellion,
heart-burnings, plots, etc. which have no place in it; but which daily waste and wither,
where it is sown and grows, even till they come to an end; and righteousness,
and pure innocency, fill the room and place which they +++[+++the evil feelings]
had, both in the heart and mind within, and in the life and conduct outwardly!`"

It may not be uninteresting to revert, in this place,
to Isaac Penington`'s feelings upon another point; respecting which, he,
with most others of the Society, was often made the subject of suffering.
I allude to the question about the payment of tithes;
upon which he thus expresses himself in a letter addressed to one James Eeles;

[.embedded-content-document.letter]
--

[.salutation]
"`Friend,

"`God is my witness, to whom I must give an account of all my actions,
that it is my desire to be found in all true love, courtesy, and righteousness,
in my dealings towards all men; and that I would by no means deny any man his just due,
which he can, by any just law or right, claim from me.

"`Now, as touching tithes, the payment or refusing of them,
is to me a matter of conscience, weighty on my heart before the Lord;
and I would do therein as he would justify, and not condemn me.
I know tithes were ordained by God to be paid to the Levitical priesthood under the law;
but the same power that ordained them under the law, disannulled them under the gospel.
(Heb. 7:12 and 18.) Now, that any man or men have true right, power,
and authority to set up or require to be paid under the gospel,
what God`'s power has disannulled,--indeed I do not see;
nor can I be subject to any human law or authority in this thing,
without sinning against God, and incurring his wrath upon my soul.

--

He then observes, that Christ sent forth his ministers without tithes.

[.embedded-content-document.letter]
--

"`Now tithes,`" he continues, "`were set up in the dark times of Roman Catholicism,
and not by the gospel light; and they who know the gospel light,
dare not be subject to that which was set up in matters of
religion by the dark power of Rome in the time of darkness.

"`I do not contend with you by the law of the land;
but I must be subject to the law of God; who shows me from what root, tithes came;
and that they are not the maintenance of the ministers of Christ, or allowed by Christ;
but the maintenance of the ministry Rome`'s power set up;
both which ministry and its maintenance, is to be denied and witnessed against,
by those whom he calls forth to testify to his truth in these things.`"^
footnote:[Penington`'s Letters, p. 157.]

--

Such being the views of Isaac Penington, and of the members of the Society in general,
upon these questions, it appears a necessary consequence,
that they should resolutely maintain the ground they had taken,
and willingly devote themselves to persecution, even had it been to death,
rather than violate such truly pure and exalted principles.
