== Chapter XIV.

In the midst of the various scenes of licentiousness and tumult, spiritual pride,
hypocrisy, and general disregard of God,
which characterized the English nation at this period, there were not lacking persons,
who, in the deep retirement of their exercised souls, were led to perceive,
that some signal judgment, some manifest token from the hand of the Almighty, would,
before long, proclaim him to be the avenger of his own insulted laws.

The cruelty displayed towards the good, and the favour extended to the bad, seemed,
indeed to call aloud for that exhibition of the Divine displeasure,
which two great national calamities at length produced.

It was in the year 1665 that the first of these judgments was manifested,
in the breaking out of the plague, in the city of London; in connection with which,
George Whitehead gives the following statement.

"`Near the beginning of the summer, 1665, when the pestilence was begun in London,
I was in the county of Surrey, and having a meeting at John Smith's house at Worplesdon,
his brother Stephen, etc. came to the meeting.
. . . And the Lord having laid it upon me to come to London,
as I signified to some friends present after the said meeting,
Stephen questioned how I could then adventure to come,
seeing the plague was then begun and broken out there.

"`I gave account of my submission to the will of God,
and of my faith and trust in him for preservation;
whereupon Stephen appeared the more satisfied,
and confirmed in the belief of the truth borne testimony to, amongst us at the meeting.

"`I soon came to London, and my lodging was at the house of William Travers,
tobacconist in Watling-street: who, with his wife Rebecca,
kindly received and entertained me, as did also her sister Mary Booth,
who lived with her; and the whole family were loving to me and friends.
And the Lord preserved that family, that none of them were infected with the pestilence,
though it greatly increased, and the mortality thereby; so that in a few weeks,
great numbers quickly died.

"`It was a time of great calamity, sorrow, and heaviness, to many thousands of all sorts.
I had not freedom, satisfaction, or peace to leave, the city, or friends,
in and about London; but was concerned and given up in spirit,
to stay among them to attend friends' meetings; to visit friends in prison,
and at their houses, even when many of them lay sick of the contagion, both in prison,
and their habitations.
And in all that time, the Lord preserved me by his power, through faith,
from that infectious distemper; which mercy I esteemed great and wonderful,
and hope ever thankfully to remember.
I well remember,
that although it was judged the prisons were
then infected and poisoned with the contagion,
I was freely given up to suffer imprisonment; and on first-days,
took my night-cap in my pocket when I went to meeting,
as not knowing but I might be apprehended, and committed to prison.`"

Some slight indications of illness he mentions as occurring to him.

"`I well remember,`" he says,
"`one evening after I had been visiting friends in some places in the city,
I was taken sick in my stomach and head,
and was concerned lest any of the family where I lodged,
should be surprised and affrighted thereat.
Whereupon, I spoke to my friend Rebecca Travers,
to desire her sister Mary Booth not to be afraid on my account; for,`" said I,
"`I shall be well to-morrow,--wishing her to tell her sister so.
And, through the Lord's mercy, I was very well next morning,
though I had been very sick over night.`"

This wide-spreading calamity had scarcely ceased,
when another severe and striking judgment afflicted the city of London,
in the great lire of 1666; in relation to which,
there is a very remarkable passage in Whitehead's Journal.

"`The next year,`" he says, (after the city and suburbs of London,
were so greatly thinned and depopulated by the plague) the dreadful fire began,
and broke out in Pudding-lane, over against the place where the Monument stands; whereby,
in a few days' time, a very great part of the city within the walls, was burnt down,
and the habitations consumed, except a few streets, and parts of streets,
to the great amazement, terror, and destruction of the inhabitants,
who were forced to flee for their lives, with what goods they could save,
into Moorfields, and the out-parts,
and there to lie abroad with their goods for several nights and days,
the country bringing in bread, etc. for their relief.

"`One morning, as my friend and brother, Josiah Cole and I, were at Gerard Roberts's,
in Thomas Apostle's, London, and going up toward the top of the house,
observed how violently the fire went on towards Thames-street,
and those parts of the city,
and hearing what rattling and crackling the fire made in the houses, Josiah said,
'This looks like a popish plot or work!' and we were both in the same mind.
I observed afterward, the fire broke out in several places distinct one from another;
so that it was very probable several wicked agents were at work in carrying it on,
and putting it forward.

"`One passage I may not omit by the way, because it has been misrepresented,
and false reports spread about it, is as follows: one Thomas Ibbott,
a Huntingdonshire man, who was convinced of the truth,
at a large meeting which I had at Thomas Parnell's,
in his barn at King's Rippon in Huntingdonshire, came to London,
two days before the fire, in great haste, being on a sixth day of the week,
and alighted off his horse, with his apparel loose,
and supposed by some to be a person under distraction or discomposure of mind,
as I understood by several; and very much hastened, or ran through the city,
towards Whitehall, in such a posture as many of the inhabitants were in,
when forced to flee from the fire, when they had scarce time to put on,
or fasten their wearing apparel.
Such a sign he appeared to be; and foretold the vision he had,
that the city would be laid waste by fire; (according as I was informed;
for I saw him not until that day-morning when the fire was broke out.)

"`But the evening after the said Thomas Ibbott had passed through the city,
I met with some of our women friends at the Bull and Mouth near Aldersgate,
who gave me a pretty full account of him; and how he had been with them that day,
and told them his vision of the fire, and message to London; and that to them,
he appeared very zealous and hot in his spirit, when he told them thereof;
and that they were afraid he was under some discomposure of mind,
which made them somewhat question and doubt of what he told them.

"`When they related the same to me, I had a fear and caution upon my spirit,
so that I dared not oppose nor question his vision, or message; but told them,
'I knew the man; he was convinced by me at a meeting at King's Rippon;
and was a sort of manly person, zealous, and somewhat of a hot spirit;
so that his spirit was nearer to those destroying angels,
or fiery spirits that are ministers of wrath, and severe judgments,
than those friends are, who have attained to a further growth in the spirit of the Lamb,
Christ Jesus; and that he,
(the said Thomas,) might sooner have a discovery of such an
evil or judgment permitted to come upon the city,
than they whose spirits were more meek and gentle,
and more settled in quietness and peace.

"`Yet I was not at that time without some secret fear concerning this friend,
Thomas Ibbott, lest he might run out or be exalted by the enemy,
into some conceit or imagination or other,
especially when he saw his vision coming to pass.

"`That morning the fire broke out, some of us met at Gerard Roberts's house aforesaid,
where the said Thomas Ibbott met us, and told us, he must go to the king with a message;
which was to warn him to release our friends out of prison,
or else the decree of the Lord would be sealed against him, in three days' time,
to his destruction or overthrow.

"`Upon which, I was afraid he would be too forward, and give occasion against friends,
and cause others to reproach truth and them.
Whereupon I earnestly charged him, if he went, not to limit a time, etc.
I was indeed greatly concerned for truth and his own sake,
poor man! lest he should be hurried into distraction;
for I clearly saw where his danger was; though his vision of fire was apparently true;
which I never opposed, but rather granted that it might have been foreshown him.

"`Also, I did observe in a letter of his before the fire was over,
he mentioned the number of days when the vision of fire should be accomplished;
so that he had a certain vision and discovery given him in that particular.
And to show that there remained a sincerity in the man,
after his mind came to be settled, he wrote a letter to some friends in London,
wherein he has these words following:--

"`'I dare not much stir up or down any way, for people's looking at what was done;
lest the Lord should be offended, etc.

"`'I have been much tempted and exercised; yet, through mercy,
have found help in the needful time.
Whatsoever slips or failings friends saw in me, in the time I was with them,
I would have none take notice of; for I was under great exercises,
and often ran too fast, which the Lord in his due time, gave me a sight of.
In the love of my Father, farewell!

"`'T. I. '`"

Nor was it only to this person,
that a foreshadowing was vouchsafed of this fearful calamity: George Fox, in his Journal,
also mentions a mysterious representation of an impending judgment,
which he beheld while a prisoner in Lancaster castle.
But these subjects, not being fitted for general discussion,
remain in their safest position, when, for humiliation and moral advancement,
they are reverently "`pondered in the heart,`"
rather than questioned by the understanding.

In the year 1669, an important event took place in the history of our friend George Fox,
which was that of his marriage with Margaret Fell; whose first husband, Judge Fell,
had then been dead eleven years.

As they lived but little in each other's society after their marriage, it would seem,
on a superficial survey of the case, that this measure might as well have been avoided.
But, that a very sincere affection and respect existed between them,
cannot admit of a doubt; and though such a motive is not even hinted at,
in the account which George Fox gives of the matter, it appears probable,
that to avoid those insidious reflections which the world commonly
makes upon intimate friendships between unmarried parties,
as well as to strengthen their mutual usefulness in the society,
they entered into this engagement.

His relation of the way in which it was brought about,
is not amongst the least amusing of his concise and simple narrations.

"`After we had discoursed the matter together,`" says he,
"`I told her if she also was satisfied with the accomplishing of it now,
she should first send for her children;`" which she did.

"`When the rest of her daughters were come, I asked both them and her sons-in-law,
if they had anything against it, or for it;
and they all severally expressed their satisfaction therewith.
Then I asked Margaret, if she had fulfilled her husband's will to her children.

"`She replied, the children knew she had.

"`Whereupon I asked them, whether if their mother married, they should not lose by it;
and I asked Margaret, whether she had done anything in lieu of it,
which might answer it to the children.
The children said she had answered it to them, and desired me to speak no more of it.

"`I told them I was plain, and would have all things done plainly;
for I sought not any outward advantage to myself.`"

This plain statement being made they took each other in marriage,
in Friends' meeting-house at Broad Mead, Bristol; at which city,
he happened at this time, to meet with his friend Margaret,
who was then on a visit to one of her married daughters residing there.

"`We stayed about a week,`" he says, "`in Bristol, and then went together to Oldstone;
where taking leave of each other in the Lord, we parted;
betaking ourselves each to our several services;
Margaret returning homewards to the north,
and I passing on in the work of the Lord as before.`"

