== Chapter XVII.

In passing near the residence of some of De Labadie`'s followers,
William Penn was led to seek an interview with them;
of which he has left so edifying a record,
that although it may be somewhat of a digression,
I venture to transcribe a few extracts therefrom.

"`We took waggon,`" he says, "`for Wiewart,
the mansion-house of the family of the Somerdykes, where J. De Labadie`'s company resides;
it being strong upon my spirit to give them a visit.
We got there about five: and as we were walking over a field to the house,
we met a young man of that company, who conducted us in.`"

Having inquired for one Ivon, the pastor, and a lady named Anna Maria Schurmans,
he and his friends were well received by the former;
but some difficulty was made respecting his introduction to the latter,
on the score of her being advanced in life, and of feeble health, etc.
Upon which, William Penn reminded them,
that he had occasion to think himself but unhandsomely treated six years before,
by their leader De Labadie; who,
although he (William Penn,) had come a long journey to visit him and his people,
would not allow of his speaking with them.

Upon hearing this, his request to see the lady was granted; but the evening coming on,
he proposed that their meeting should be put off till the following morning.

The next day, he, and a friend (whom he merely names as J. C+++_______+++,) went to them again;
and were immediately admitted to the apartment of Anna Maria Sehurmans,
with whom they found a lady of the Somerdyke family.
Somerdyke was a nobleman of the Hague, and as Penn describes it,
he and his three daughters were "`people of great breeding and inheritances.`"

Anna Maria Sehurmans was a single woman above sixty;
of such great note and fame for learning, in languages and philosophy,
that she had obtained a considerable place among the most learned men of the age.

"`These,`" he says, "`with several other persons,
being affected with the zealous declamation of J. De Labadie,
against the dead and formal churches of the world,
and awakened to seek after a more spiritual fellowship and society,
separated themselves from the common Calvinist churches,
and followed him in the way of a refined Independency.

"`They are a serious, plain people,`" he observes; "`and are come nearer than others,
to friends, in silence, in meetings, women speaking, preaching by the Spirit,
plainness in garb, and furniture in their houses.

"`With these two,`" he continues, "`we had the company of the two pastors,
and a doctor of medicine.
After some silence, I proposed this question to them:
'`What was it that induced them to separate from the common way they formerly lived in?`'
I desired that they would be pleased to be plain and open with me,
as to the ground of their separation; for I came not to dispute,
but in a Christian spirit, to be informed.

"`Upon this, Ivon the chief pastor, gave us the history of J. De Labadie`'s education;
how he was bred among the Jesuits, and deserted them,
and embraced the Protestant religion; and finally,
with his great dissatisfaction with the Protestant churches of France;
and that if God would not give them a purer church,
they three would sit down by themselves,
resolving never more to mix among the Babylonish assemblies of the world;
adding several solemn appeals concerning the simplicity
and integrity of their hearts in these things.

"`Ivon having done, Anna Maria Schurmans began in this manner:
'`I find myself constrained to add a short testimony.`'

"`She told us of her former life, of her pleasure in learning,
and her love to the religion she was brought up in; but confessed she knew not God,
nor Christ truly, all that while.
And though, from a child, God had visited her at times,
yet she never felt such a powerful stroke, as by the ministry of J. De Labadie.
She saw her learning to be vanity, and her religion like a body of death.
She resolved to despise the shame, desert her former way of living and acquaintance,
and join herself to this little family, that was retired out of the world;
among whom she desired to be found a living sacrifice, offered up entirely to the Lord.`"

He describes these as but short hints of what she said:
which he represents as being delivered in much seriousness, and brokenness of spirit.

"`After she had done,`" he continues, "`one of the Somerdykes began,
in a very reverent and weighty frame of mind,
and in a sense that very well suited her contempt of the world.
She told us how often she had mourned from her young years,
because she did not know the Lord as she desired; often saying within herself,
'`If God would make known to me his way,
I would trample upon all the pride and glory of the world.`'
She earnestly expressed the frequent anguish of spirit she had,
because of the deadness and formality of the Christians she was bred among:
saying to herself, '`Oh, the pride!
Oh, the lusts!
Oh, the vain pleasures in which Christians live!
Can this be the way to heaven?
Is this the way to glory?
Are these the followers of Christ?
Oh, no!--Oh, God! where is your little flock?
Where is your little family that will live entirely to you, and that will follow you?
Make me one of that number!`"
And when the servant of the Lord, J. De Labadie came into Holland, I, among others,
had a curiosity to hear him.`"

She then spoke of the convincing power which his preaching exercised upon her conscience;
"`He spoke the very thoughts of my heart,`" she said; "`and I resolved,
by the grace of God, to abandon all the glory and pride of this world,
and to be one of those that should sit down with him,
in a separation from the vain and dead worships of this world.
I count myself happy that I ever met with him and these pastors, who seek not themselves,
but the Lord; and we are a family that live together in love, of one soul and one spirit,
entirely given up to serve the Lord; and this is the greatest joy in the world!`"

When she had concluded, Du Lignon, the other pastor,
related the reasons for his embracing the views of De Labadie; but his account,
Penn says, was not given "`so livingly.`"

"`After him,`" he proceeds, "`the doctor of medicine that had been bred for a priest,
but voluntarily refused that calling, expressed himself, after this manner;

"`'`I can also bear my testimony, in the presence of God,
that though I lived in as much reputation at the university, as any of my colleagues,
or companions, and was well reputed for sobriety and honesty, yet,
I never felt such a living sense of God, as when I heard the servant of the Lord,
J+++.+++ De Labadie.

"`'`The first day I heard him, I was so struck and affected, that I can truly say,
through the good grace of God, and the guidance of the Holy Spirit, it was to me,
as the day of my salvation; he did so livingly touch my heart,
with a sense of the true Christian worship.
Upon which, I forsook the university, and resolved to be one of this family.
And this I can say in the fear of the Lord.`'`"

The chief pastor, Ivon, then concluded their testimony, by saying,
"`This is what we have to say concerning the work of God amongst us.`"

"`All this while,`" says Penn, "`I minded not so much their words, as I felt,
and had unity with, a measure of divine sense that was upon them.
Certainly, the Lord had been amongst them; yes, I had a living sense in my heart,
that somewhat of the breath of life had breathed upon them;
and though they were in great mixtures, yet that God`'s love was towards them.

"`After some silence, I began in this way:--

"`'`I come not to judge you, but to visit you; not to quarrel or dispute,
but to speak of the things of God`'s kingdom; and I have no prejudice,
but great love and regard in my heart, towards you;
wherefore hear me with Christian patience and tenderness.

"`'`I do confess and believe, that God has touched your hearts with his divine finger,
and that his work is amongst you;
that it was his Spirit which gave you a sight of the folly and vanity of this world,
and that has made you sensible of the dead religions that are in it.
It is this sense I love and honour;
and I am so far from undervaluing or opposing this tender sense I feel upon you,
that this it is, I am come to visit; and you, for the love of it.
And as for the reproaches that may attend you on the score of your separation,
with all the reports that thereof go concerning you, they are what I respect you for;
being well acquainted with the nature and practice of this world,
towards those that retire out of it.

"`'`Now, since I have with patience, and I can truly say with great satisfaction,
heard your account of your experiences,
give me the like Christian freedom to tell you mine;
to the end you may have some sense of the work of God in me;
for those who are come to any measure of a divine sense,
they are as looking-glasses to each other, as face answers to face in a glass.`'`"

He then proceeded to inform them of the dealings of God with his soul,
of which he was first sensible about the twelfth year of his age.
He told them of the persecution he underwent at Oxford,
on account of his religious sentiments, and afterwards from his own father.
He spoke of the deep sense it pleased God to give him, of the vanity of the world,
and of the irreligiousness of all the religions in it; and "`yet after all this,
the glory of the world,`" he says, "`overtook me,
and I was even ready to give myself up to it, seeing as yet, no such thing,
as the primitive spirit and church on the earth; and being ready to faint,
concerning my hope of the restitution of all things.

"`It was at this time,`" he continues,
"`that the Lord visited me with a certain sound and testimony of his eternal word,
through one of those the world calls Quakers, namely, Thomas Loe.

"`I related to them,`" he says, "`the bitter mockings and scornings that fell upon me;
the displeasure of my parents, the invectiveness and cruelty of the priests,
the strangeness of all my companions; what a sign and wonder they made of me;
but above all, that great cross of resisting and watching against,
my own inward vain affections and thoughts.

"`Here,`" he observes,
"`I had a fine opportunity to speak of the mystery of
iniquity and ungodliness in the root and ground:
and to give them an account of the power and presence of God
which attended us in our public testimonies and sufferings;
after an indirect manner, censuring their weaknesses,
by declaring and commending the contrary practices among friends, etc.

"`And, notwithstanding all my sufferings and trials,`" said he, in his address to them,
"`by magistrates, parents, companions, and above all,
from the priests of the false religions that are in the world,
the Lord has preserved me to this day, and has given me a hundred-fold in this world,
as well as the assurance of life everlasting;
informing them of the tenderness of my father to me, before, and at his death, and how,
through patience and long-suffering, all opposition was conquered.`"

He then began his exhortation, which, in substance, was as follows:--

That since God had given both to him and them, a divine sense of him,
their eye should be to him, and not to man;
that they might come into more silence of themselves,
and a growth in that heavenly sense.
That this was the work of the true ministry: not to keep people to themselves,
and be ever teaching them; but to turn them to God, the new covenant teacher,
and to Christ, the great gospel minister.
Thus did John, and thought it no dishonour that they left him to go to Christ.
"`Behold the Lamb of God!`" said he, "`that takes away the sin of the world!`"
And even John`'s disciples, left him to follow Christ.
No, John testifies of himself, that he was to decrease, and Christ was to increase.
"`Wherefore,`" he says, "`I pressed them to have their eye to Christ,
that takes away the sin;
to him that is from heaven-- heavenly--and see that he increase in them.
Yes, that henceforth they should '`know no man after the flesh;`' no, not Christ himself.
That their knowledge of, and regard, and fellowship with one another,
should stand in the revelation of the Son of God in them;
who is God`'s great Prophet by whom he speaks in these latter days--and,
if their ministers be true ministers,
they will count it their glory to give way to Christ; and that they should decrease,
and he should increase; for the instrument gives way to him that uses it,
and the servant to the Lord, etc.

"`Therefore,`" said he, "`let Christ have his honour: let him preach and speak among you,
and be in you, and you in him: and by him only, sigh, groan, pray, preach, sing,
and not otherwise, lest death come over you; for thereby the apostacy came in;
by their going before Christ, instead of Christ going before them.`"

After addressing himself in particular with a serious and tender spirit to the ladies,
he left, he says, "`the blessing and peace of Jesus among them,
departing in the love and peace of God.`"

In their way home, William Penn and the friends again visited Herwerden,
and the amiable Princess Elizabeth, and received from her and the Countess de Homes,
her companion, the same cordial welcome as before.

He observed them, he says, to be much subdued in their minds;
which he attributed to the blessed effect of their former addresses to them.

"`That afternoon,`" he says, "`was employed in the narrative of our travels,
which they heard with great attention and refreshment.
The whole discourse ended with a precious little meeting.

"`The house being clear of strangers, they both earnestly pressed us to sup with them;
which, not being well able to decline, we submitted to.

"`At supper, the power of the Lord came upon me, and it was a true supper to us;
for the hidden manna was manifested, and broken among us: yes,
a blessed meeting it proved to us.--Oh! the reverent tenderness, and lowly frame,
that appeared this evening,
both in the princess and countess.-- The Frenchwoman we found greatly improved,
both in her love and understanding; yes, she was very zealous and very broken,
and was always with us on these occasions.

"`After supper, we returned to the princess`'s chamber,
where we stayed till it was about ten at night.
At parting, I desired the princess would give us such another opportunity the next day,
being the first day of the week, as we had the last time we were with her.
She answered me, '`With all my heart; but will you not come in the morning too?`'

"`I replied, '`Yes, willingly.
What time will you be ready to receive us?`'

"`She answered, '`At seven.`'`"

Of the two meetings on the succeeding day, he speaks in pleasing terms;
but we must now hasten to the interviews of the following one,
being the last which these interesting friends were permitted to spend together.

On that morning about eight, William Penn and his companions repaired to the court,
"`where the princess and countess,`" he says, "`were ready to receive us.`"

"`The morning was employed in a very serious relation, touching the affairs, practices,
and sufferings of our friends in England, with which they seemed greatly affected;
when about the eleventh hour, the rattling of a coach interrupted us.`"

This interruption proved to be the arrival of the Graef of Donau, with two young princes,
who were nephews of the Princess Elizabeth, and who were all come to make her a visit;
upon which the friends withdrew; but as they were to quit the place that night,
William Penn entreated that they might not be disappointed of
a parting interview-- which was readily promised them;
the visitors just arrived, being only come to dine, and be gone again.

"`As we went to the door,`" he says, "`the countess stepped before and opened it for us;
and as I passed by, she looked upon me with a weighty countenance,
and fetched a deep sigh, crying out, '`Oh,
the cumber and entanglements of this vain world!
They hinder all good!`' Upon which I replied, looking her steadfastly in the face, '`Oh,
come out of them, then!`'`"

After the friends had dined, a message was brought from the princess,
that she desired their company,
as the Graef of Donau had a great wish to see and to converse with them;
a request with which, after some exercise of spirit, they complied.

"`Being arrived,`" he says, "`the graef approached us in French:
at first he took no notice of our unceremonious behaviour,
but proceeded to inquire of us our success in our journey, etc.

"`Then we fell to points of religion, and the nature and end of true Christianity,
and what was the way that leads to eternal rest.
After some short debate about sanctification in this life, we both agreed,
that self-denial, mortification, and victory, was the duty,
and therefore ought to be the endeavour of every sincere Christian.

"`From this, I fell to give him some account of my retreat from the world,
and the inducements I had thereto; and the necessity of an inward work,
with which he seemed much pleased.

"`After this, he fell to the hat, etc.`"

"`This,`" says Penn, "`chokes; and the rather, because it tells tales;
it tells what people are; it marks men for separatists;
it is blowing a trumpet visibly across the world:
and that the fear of man (greatly prevalent with too
many serious people in that land,) cannot abide,
but starts at, and runs away from.

"`Howbeit, the Lord enabled me to open the thing to him; as that it +++[+++the hat honour]
was no plant of God`'s planting, but a weed of degeneracy and apostacy;
a carnal and earthly honour, the effect, feeder, and pleaser of pride,
and of a vain mind, and that no advantage redounded to mankind by it: and how could they,
that ought to do all to the glory of God, use that vain and unprofitable custom,
which cannot be done to the glory of God?
I entreated him seriously to consider with himself, the rise and end of it;
from where it came, what it pleased, and what that was,
which was angry that it had it not?`"

He reminded this great man,
of the sincere and serviceable respect which truth
substituted in the place of this unmeaning ceremony;
and after exhorting him to simplicity and poverty of spirit,
and to be like that Jesus whom he professed to take for his Saviour, they parted;
the graef taking his leave, first of the princess, and then of them, with great civility.

"`After he was gone,`" he says, "`the princess desired us to withdraw to her apartment,
and there we began our farewell-meeting.
The thing lay weighty upon me, and that,
in the deep dread of the Lord.--And eternally magnified be the name of the Lord,
that overshadowed us with his glory!
His heavenly, breaking, dissolving power, richly flowed amongst us;
and his ministering angel of life, was in the midst of us.
Let my soul never forget the divine sense that overwhelmed all!
-- At that blessed farewell that I took of them,
much opened in me of the hour of Christ`'s temptation, his watchfulness, perseverance,
and victory, etc.
And in the conclusion of that torrent of heavenly,
melting love with which we were all deeply affected, I fell on my knees,
recommending them unto the Lord;
crying with strong cries unto him for their preservation,
and beseeching his presence with us;--and so ended.`"

He then particularizes their last adieu, so touchingly,
that I should not have the thanks of my reader, for omitting it.

"`After some pause,`" he says, "`I went to the princess, and took her by the hand,
which she received and embraced,
with great signs of a weighty kindness;--being much broken.
I spoke a few words apart to her, and left the blessing and peace of Jesus with,
and upon her.
Then I went to the countess, and left a particular exhortation with her,
who fervently besought me to remember her, and implore the Lord on her behalf.
From her I went to the Frenchwoman,
and bid her be faithful and constant to that which she knew.
She was exceedingly broken, and took an affectionate and reverent leave of us.

"`Then I spoke to the rest, and took leave severally of them.
My companions did all the like.
They followed us to the outward room, and there it was upon me to step to the countess,
and once more to speak to her, and take my leave of her; which she received,
and returned, with great sense, humility and love.

"`So, turning to them all, my heart and eye to the Lord, I prayed that the fear,
presence, love, and life of God, with all heavenly blessings,
might descend and rest with, and upon them, then, and forever!`"

[.asterism]
'''

The sweet and precious Christian love which animated the heart,
and flowed from the lips of William Penn towards Princess Elizabeth, and her friend,
occasioned him, shortly after quitting them,
to testify his deep interest (more especially in the
countess) by addressing to the latter an epistle,
from which, before we conclude this memorial, some extracts may be acceptable:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`For Anna Maria de Hornes, styled Countess of Hornes, at Herwerden in Germany.

[.salutation]
"`My Dear Friend,

"`Oh that you may ever dwell in the sweet and tender sense of
that divine love and life which has visited your soul,
affected and overcome your heart!
Oh tell me!
Has it not sometimes raised your spirit above the world,
and filled you with fervent and passionate desires, yes,
holy resolutions to follow Jesus, your blessed Saviour,
who has given his most precious blood for you, that you should not live to yourself,
but to him that has so dearly purchased you?

"`Oh! the retired, humble, reverent frame that I have beheld you in,
when this blessed life has drawn you into itself,
and adorned and seasoned you with its own heavenly virtue;
beautifying your very countenance,
beyond all the vain and foolish ornaments of the shameless daughters of Sodom and Egypt;
for therein are charms not known to the children of this world.

"`My dearly beloved friend! be steadfast, immoveable, without wavering;
and work out your great salvation, with fear and trembling,
and lose not that sweet and precious sense which the Lord has begotten in you.
It is soon lost, (at least weakened,) but hard to recover.
Wherefore, let not the spirit of the world, in any of its appearances, vain company,
unnecessary discourse, or words, or worldly affairs,
prevail upon the civility of your nature; for they will oppress the innocent life,
and bring grievous weights and burdens upon the soul.
. . Oh beware of this compliance!
Let me put you in mind of that sensible resolution, so frequently,
and so passionately repeated by you: '`Il faut queje rompe!--il faut que je rompe.`' +++[+++I must be broken. I must be broken]

"`Now be assured,
that till obedience be yielded to that present manifestation and conviction,
the good things desired and thirsted after, can never be enjoyed.

"`Wherefore, my dear friend, be faithful,
and watch against the workings of the spirit of this world in yourself;
that the nature and image of it in all things, may be crucified,
that you may know an entire translation, with holy Enoch, and walk with God.

"`Oh faint not; look not back.
Remember the holy ancients, the holy pilgrims of faith; the royal generation of heaven,
(Heb.
11.) You believe in God, believe also in Jesus,
for the work`'s sake that he has already wrought in you; he will minister unto you,
as he was ministered unto by his Father`'s angels in the
hour of his abasement and great temptation.
Oh watch and be faithful, and you shall be a noble witness for the Lord!

"`How is my soul affected with your present condition!
It is the fervent supplication of my heart, that you may,
through the daily obedience of the cross of Jesus,
conquer and shine as a bright and glorious star
in the firmament of God`'s eternal kingdom.
So let it be, Lord Jesus!
Amen.`"

--

It may not be esteemed an irrelevant close to this interesting subject,
if the following tribute from William Penn to
the memory of his friend Princess Elizabeth,
(who died four years after this period,) be here inserted.

"`The late Princess Elizabeth of the Rhine, of right claims a memorial in this discourse;^
footnote:[Serious dying, as well as living testimonies, chap.
xxi. sect.
34. [.book-title]#No Cross, No Crown.#]
her virtue giving greater lustre to her name, than her quality,
which yet was of the greatest in the German empire.
She chose a single life, as freest of care,
and best suited to the study and meditation she was always inclined to;
and the chiefest diversion she took, next the air,
was in some plain and housewifely entertainment, as knitting, etc.
She had a small territory, which she governed so well,
that she showed herself fit for a greater.
She would constantly, every last day in the week, sit in judgment,
and hear and determine causes herself; where her patience, justice, and mercy,
were admirable; frequently remitting her forfeitures, where the party was poor,
or otherwise meritorious.
And, which was excellent, though unusual, she would temper her discourses with religion,
and strangely draw concerned parties to submission and agreement;
exercising not so much the rigour of her power, as the power of her persuasion.
Her meekness and humility appeared to me extraordinary.
She never considered the quality, but the merit of the people she entertained.
Did she hear of a retired man, hid from the world,
and seeking after the knowledge of a better?
she was sure to set him down in the catalogue of her charity, if he wanted it.
I have casually seen,
I believe fifty tokens sealed and superscribed
to the several poor subjects of her bounty,
whose distances would not allow them to know one another, though they knew her,
whom yet some of them had never seen.
Thus, though she kept no sumptuous table in her own court,
she spread the tables of the poor in their solitary cells;
breaking bread to virtuous pilgrims, according to their need, and her ability.
Temperate in herself, and in apparel void of all ornaments, I must needs say,
her mind had a noble prospect;
her eye was to a better and more lasting inheritance than can be found below;
which made her often to despise the greatness of courts, and learning of the schools,
of which she was an extraordinary judge.

"`Being once at Hamburgh, a religious person whom she went to see for religion`'s sake,
telling her it was too great an honour for him,
that he should have a visitant of her quality come under his roof,
that was allied to so many great kings and princes of this world; she humbly answered,
'`if they were godly as well as great, it would be an honour indeed;
but if you knew what that greatness was, as well as I, you would value less that honour.`'

"`Being in some agony of spirit, after a religious meeting we had in her own chamber,
she said, '`It is a hard thing to be faithful to what one knows! oh, the way is strait!
I am afraid I am not weighty enough in my spirit, to walk in it.`'

"`After another meeting, she uttered these words: '`I have records in my library,
that the gospel was first brought out of England here into Germany, by the English;
and now it is come again.`'

"`She once withdrew on purpose to give her servants the liberty of discoursing with us,
that they might the more freely put what questions of
conscience they desired to be satisfied in;
for they were religious; suffering both them, and the poorest of her town,
to sit by her in her own bedchamber, where we had two meetings.
I cannot forget her last words, when I took my leave of her:
'`Let me desire you to remember me, though I live at this distance,
and you should never see me more.
I thank you for this good time; and know, and be assured,
though my condition subjects me to various temptations,
yet my soul has strong desires after the best things.`'

"`She lived her single life till about sixty years of age,
and then departed at her own house at Herwerden, which was about two years since;^
footnote:[She died in 1680,
and this passage was inserted in a second edition of "`No Cross, No Crown.`"]
as much lamented as she had lived beloved of the people; to whose real worth I do,
with religious gratitude for her kind reception, dedicate this memorial.`"
