== Chapter XVIII

The following letter of Robert Barclay to Princess Elizabeth,
written soon after his return to England,
indicates that he had not been of the number of
those friends who visited her a second time.
It appears also from this document,
that he had interested himself in the welfare of the suffering friends in Scotland,
by making applications to the Duke of York in their behalf,
and that with a nobility of spirit,
which exhibits an admirable specimen of the integrity of his character.

[.embedded-content-document.letter]
--

[.letter-heading]
Robert Barclay To The Princess Elizabeth.

[.signed-section-context-open]
"`Theobald's, near London, 12th of the 7th month, 1677.

[.salutation]
"`Dear Friend,

"`By your letter of the last of the month past,
I understood that the friends were with you,
and was refreshed by the account they gave me of your kind and Christian
entertainment of them;-- they having overtaken me in Holland.
God will not be lacking to reward your love, as well as to increase the same.

"`Finding no ready passage for Scotland, I came over here;
and albeit I had no great expectation of success,
I resolved once more to try your cousin, the Duke of York.^
footnote:[Afterwards James II.]
So I told him, that I understood from Scotland, notwithstanding Lauderdale was there,
and had promised, before he went, to to do something, yet,
our friends' bonds were rather increased;
and that there was now only one thing to be done, which I desired of him,--and that was,
to write effectually to the Duke of Lauderdale,
in that style wherein Lauderdale might understand, that he was serious in the business,
and did really intend the thing he did write concerning, should take effect:
which I knew he might do, and I supposed the other might answer;--which, if he would do,
I must acknowledge as a great kindness.
But if he did write, and not in that manner,
so that the other might suppose him to be serious,
I would rather he would excuse himself the trouble; desiring withal,
to excuse my plain manner of dealing,
as being different from the court way of soliciting; all which,
he seemed to take in good part, and said he would so write as I desired,
for my father and me, but not for the persecuted friends in Aberdeen, in general.
So, he has given me a letter; whether it will prove effectual or not, I cannot determine;
but of this you may hear hereafter.

"`I am now entered into my journey, and intend to pass by the way of Ragley.^
footnote:[The seat of Lord Conway.
Lady Conway was a person of great piety, and a favourer of friends.
In a letter to the learned and excellent Dr. Henry More (who was her particular
friend) she thus expresses herself concerning them:
{footnote-paragraph-split}
"`Your conversation with them (the Friends) at London,
might be, as you express it, charitably intended,
like that of a physician frequenting his patients for
the increase or confirmation of their health;
but must profess, that my converse with them is,
to receive health and refreshment from them.`"--See Appendix
to Barclay's Second Edition of [.book-title]#I. Penington's Letters,#
p. 311.]

"`What you write of the counsellor of the elector, and the other preachers,
is very acceptable to me to hear;
whose joy it is to understand that the eyes of any are
opened to see the truth as it is this day revealed;
as it should be much more, to hear that any came into that universal obedience,
which the life and power thereof lead to; which life and power,
as they are felt in the inward parts,
are more than all the words that can be spoken:--of which, I know you have, at sometimes,
not been insensible.
And therefore, my soul's desire for you is,
that you may more and more come out of all that which cumbers,
to feel this power of truth to operate in,
and redeem your soul from all the difficulties that do, or may attend you.
This, in the nature of it, it is powerful to do,
albeit your temptations were greater and more numerous than they are,
if received by you in the love of it,
and with a heart fully resigned to obey it in all its requirings,
without consulting with flesh and blood,
or turning by the plain and simple leadings thereof, by wise and fleshly reasonings,
which will never admit of the government and
rule of the cross of Christ;--as you well know,
and will not refuse to acknowledge,
and therefore are the more concerned to watch against it in your own particular,
as I hope in measure you do, and my heart's desire is.

"`You may make mention of my dear and tender love to Anna, whose servant,
as also the Frenchwoman, I forget not.
To Anna, I thought to have written apart; but must now leave it until another opportunity.
If you see fit to salute that counsellor of the elector in my name, you may do it.

"`I shall add no more at present, but that I am your real and unfeigned friend,

[.signed-section-signature]
"`Robert Barclay.`"

--

"`The memoirs of the family,`" says John Barclay,^
footnote:[See [.book-title]#Jaffray and the Friends in Scotland,# by J. Barclay, p. 415.]
"`state in general terms,
that the release of both the father and son +++[+++David and Robert Barclay]
took place by an order from court, with a reprimand for meddling with either of them;
and that the son afterwards procured the liberation of his other friends,
who were detained after them.
It is presumed,`" he continues,
"`that this must be understood of the imprisonment of David Barclay and others,
in the course of this year, +++[+++1677,]
but it does not expressly appear,
how soon Robert's lot was cast among the prisoners after his return home,
nor when his release with that of his father, was effected.`"

The ascertaining of this point is not material; since it is pretty clear,
that the few last years of the pious and venerable David Barclay,
were unmolested by persecution.
His son Robert has preserved an account of his father's death,
in the third volume of his works, from which we learn,
that he died (as for the last twenty years he had lived)
in unity with the principles of friends,
and with "`a hope full of immortality.`"

In the latter end of October, 1686, being then past the seventy-sixth year of his age,
he was seized with a fever, which continued with him for two weeks; during which time,
he evinced a quiet, contented mind, freely resigned to the will of God;
he also gave several striking testimonies to the truth, and to the love of God,
"`shed abroad in his heart by the Holy Ghost.`"
Not once during the course of his illness, though at times his sufferings were great,
was he heard to murmur, or betray any symptom of impatience; only on one occasion,
did he, under a sense of extreme weakness,
evince a feeling that seemed like a fear of death, while uttering the words,
"`I am going now.`"
But if there were a moment's natural shrinking from the approach of "`the
king of terrors,`" it was checked as soon as felt;
for, immediately he added, "`but I shall go to the Lord,
and be gathered to many of my brethren,
who are gone before me;--and to my dear son!`"--This was his youngest son David,
who died at sea about a year before, on his voyage to East Jersey.`"

His son relates, that on the 11th of October, early in the morning, he grew much weaker;
upon which, says he, "`I drew nigh to him.
He said, 'Is this my son?'
I said, 'Yes;' and spoke a few words, signifying my travail, that he that loved him,
might be near him to the end.

"`He answered, 'The Lord is nigh;' repeating it once again, saying,
'You are my witnesses, in the presence of God,
that the Lord is nigh;' and after a little, he said,
'the perfect discovery of the day-spring from on high,
how great a blessing has it been to me, and my family!'

"`My wife desiring to know if he would have something to wet his mouth, he said,
'It needed not.'
She said it would refresh him.
He laid his hand upon his breast, saying, he had that inwardly, that refreshed him.
And after a little while, he added several times, these words, 'The truth is over all!'

"`He took my eldest son to him, and blessed him, saying,
he prayed God he might never depart from the truth;
and when my eldest daughter came near, he said,
'Is this Patience?--Let patience have its perfect work
in you!' and after kissing the other four,
he laid hands on them, and blessed them.

"`He called for my father-in-law, and two of his daughters that were present,
and spoke some weighty words to them very kindly; and perceiving one of them,
(who was not a friend,) weeping much,
he wished she might come to the knowledge of the truth; and bid her not to weep for him,
but for herself.

"`A sober man, an apothecary that attended him, coming near, he took him by the hand,
saying, 'You will bear me witness, that in all this exercise,
I have not been curious to tamper nor to pamper the flesh.'
He answered, 'Sir, I can bear witness,
that you have always minded the better and more substantial part,
and rejoice to see the blessed end the Lord is bringing you to.'

"`He replied, 'Bear a faithful and true witness:
yet it is the life of righteousness--it is the life of righteousness,
that we bear testimony to, and not to an empty profession!'

"`Then he called several times, 'Come, Lord Jesus!--Come!--Come!' and again,
'My hope is in the Lord!'

"`Now and then he slept, for about the space of ten hours.
On observing a countryman come into the room,
he thought it had been one of his tenants who was a carpenter,
and telling him it was not he, but another, he said,
'See you charge him to make no manner of superfluity upon my coffin.'`"

"`About three in the afternoon, there came several friends from Aberdeen, to see him.
He took them by the hand, and said several times, they were come in a seasonable time.
After some words were spoken, and Patrick Livingstone had prayed,
(which ended in praises,) he held up his hands and said, 'Amen!
Amen! forever!'

"`Afterward, when they stood looking at him, he said,
'How precious is the love of God among his children! and their love one to another!
Thereby shall all men know that you are Christ's disciples, if you love one another!
How precious it is, to see brethren dwell together in love!
My love is with you--I leave it among you.'

"`About eight at night, several friends standing about the bed, he,
perceiving some of them to weep, said, 'Dear friends!--all mind the inward man;
heed not the outward.
There is one that does regard--the Lord of Hosts is his name!'

"`After he heard the clock strike three in the morning, he said,
'Now the time comes!' and a little after, he was heard to say, 'Praises, praises,
to the Lord!
Let now your servant depart in peace.--Into your hands, O Father!
I commit my soul, spirit, and body.--Your will, O Lord! be done on earth,
as it is in heaven.'

"`These sentences he spoke by short intervals, one after another;
and at a little after five in the morning, fell asleep, like a lamb,
in remarkable quietness and calmness.`"

The death of David Barclay, "`in a full age,
like as a shock of corn comes in in his season,`"
was an event that might have been expected;
but that of his estimable son Robert, four years subsequent to his father's decease,
and in the forty-second year only of his useful life,
was a sudden and unlooked-for affliction to his family, and to the society in general.

"`Surprising,`" says William Penn, "`was the death of dear Robert Barclay,
to me particularly, from the share I claimed in him, and the esteem I had for him;
but that which gave weight to my sorrow,
was the loss which thereby comes to the church of God, and especially in Scotland.
That he lived no longer,
who was so well fitted to live for the service and honour of the truth,
and the good of God's people, must render his death most afflicting to all those,
who desire to be reckoned amongst this number.
Oh, friends!`" he continues,
"`if precious in the sight of the Lord is the death of his saints,
ought not their labours and death to be precious to the Lord's people?

The latter part of Robert Barclay's life, was employed in the affairs of the society;
in furtherance of which, he was several times in London,
where he made use of his influence at court,
in endeavouring to obtain some improvement of the
circumstances which more peculiarly oppressed the friends.
It was in one of his journeys home from London, that an incident occurred,
which strongly manifests the composure of his mind,
even under the most appalling circumstances.

It is thus recorded by his grandson:-- "`Having stayed most of the summer in London,
visiting his friends, as he with his wife and brother-in-law, Gilbert Molleson,
and his intimate friend, Aaron Sonnemans, an eminent merchant in Holland,
were travelling homeward in company together, they were, upon the 8th of August,
attacked in Stonegate Hole, Huntingdonshire, by highwaymen.
One of them presented a pistol to my grandfather, who took him by the arm very calmly,
and asked him how he came to be so rude, for he knew his business.
The fellow trembling,
dropped the pistol out of his hand upon the ground in great surprise,
and did not so much as demand anything.
But his brother-in-law was rifled; and poor Sonnemans was shot through the thigh,
(it was thought more by accident than design,) who
being with some difficulty brought to Stilton,
died in a few days of the wound.`"
He adds, "`I had the above account from my grandmother; who likewise told me,
that she observed my grandfather that morning, before they were attacked,
more pensive than usual; and that he told her it was his opinion,
some unusual trial or exercise was to befal them that day; but when the affair happened,
he enjoyed a remarkable serenity.`"^
footnote:[Barclay's [.book-title]#Friends in Scotland#, p. 443.]

It was in the year 1690,
that it pleased the Divine will to summons Robert Barclay from this world.
He had been engaged a short time previous to his decease, accompanied by another friend,
in a religious visit to some parts of the north of Scotland;
and on returning home to his house at Ury, he fell ill with a violent fever,
which continued about eight or nine days, when it terminated in death.

Though much oppressed by the disorder, an entirely resigned, peaceful,
and Christian frame of mind shone through his dying circumstances.
A friend, of the name of James Dickenson,
(the same who had accompanied him in his recent religious visits,) attended his sick bed;
to whom, with tears,
he expressed the love he bore towards all the faithful brethren in England,
who kept their integrity in the truth.

"`Remember my love,`" said he, "`to friends in Cumberland, at Swarthmore,
and to dear George; (meaning George Fox,) and to all the faithful,
everywhere;`" concluding with these comfortable words: "`God is good,
still! and though I am under a great weight of sickness and weakness,
as to my body-- yet my peace flows.
And this I know--that whatever exercises may be permitted to come upon me,
they shall tend to God's glory, and my salvation; and in that I rest.`"

He died on the 3rd of October;
and his remains were attended to the family burial-place at Ury, by many friends,
and others of the neighbourhood.
The following letter from the pen of George Fox, addressed on this mournful occasion,
to the widow, is too characteristic to be omitted.

[.embedded-content-document.letter]
--

[.letter-heading]
George Fox to Christian Barclay

[.signed-section-context-open]
"`28th of 10th month, 1690.^
footnote:[George himself lived, not much above two weeks after the date of this epistle.]

[.salutation]
"`DEAR FRIEND!

"`With my love to you and your children, and all the rest of friends, in the holy seed,
Christ Jesus, that reigns over all; in whom you have all life, and salvation, and rest,
and peace with God!

"`Now, dear friend, though the Lord has taken your dear husband from you, his wife,
and his children, the Lord will be a husband to you, and a father to your children.
Therefore, cast your care upon the Lord, and trust in him.
Let him be your confidence, and let your eye be unto Him, at all times:
who is a great Ruler and Orderer of all, both in heaven and earth,
and has the breath and souls of all, in his eternal, infinite hand.
And all the creation is upheld by his word and power, by which they were made;
so that a sparrow cannot fall to the ground without his will and pleasure;
--and his sons and servants in his image, are of greater value in his eye,
than many sparrows.
Therefore,
you and your family may rejoice that you had such an offering to offer up unto the Lord,
as your dear husband; who I know, is well in the Lord, in whom he died;
and is at rest from his labours, and his works do follow him.

"`And now, my dear friend, do your diligence in your family,
in bringing up your children in the fear of the Lord, and his new covenant of life;
that you may present them to God as his children, and all your servants and tenants,
in the wisdom of God.
You must answer the truth in them all;^
footnote:[A phrase peculiar to this age, and to this society; and which signifies,
"`you must come up to the apprehension of what is right,
which exists in their consciences`"--or "`you must not
disappoint their perception of what is good;`"--and it will be
scarcely necessary to suggest to the thoughtful reader,
that it is by a very high standard of rectitude,
that the conduct of religious professors is measured; how low soever,
be that whereby the measurers may estimate themselves.]
in truth, holiness, righteousness, justice, and walking humbly before God.
You will always feel His presence to assist,
and enable you to perform whatsoever he requires of you; so, that whatsoever you do,
it may be to the honour and glory of God.
And do not look at the outward presence of your husband; but look at the Lord,
and serve him with a joyful heart, soul, mind, and spirit,
all the days you live upon the earth.

"`From him who had a great love and respect for your dear husband,
for his work and service in the Lord; who is content in the will of God,
and all things that he does;--and so must you be.
And so, the Lord God Almighty, settle and establish you and yours,
upon the heavenly rock and foundation; that, as your children grow in years,
they may grow in grace, and so in favour with the Lord.--Amen

[.signed-section-signature]
"`George Fox.`"

--

The character of Robert Barclay is best given in the words of a contemporary and friend;
both of whom were combined in William Penn, who thus describes him:--

"`He was distinguished by strong mental powers, particularly by great penetration,
and a sound and accurate judgment.
His talents were much improved by a regular and classical education.
It does not however appear,
that his superior qualifications produced that elation of mind,
which is too often their attendant.
He was meek, humble, and ready to allow others the merit they possessed.
All his passions were under the most excellent government.
Two of his intimate friends in their character of him,
declare that they never knew him to be angry.
He had the happiness of early perceiving the infinite superiority of religion,
to every other attainment;
and Divine grace enabled him to dedicate his life and all that he possessed,
to promote the cause of piety and virtue.
For the welfare of his friends, he was sincerely and warmly concerned;
and he travelled and wrote much, as well as suffered cheerfully,
in support of the society and principles to
which he had conscientiously attached himself.

"`But this was not a blind and bigoted attachment.
His zeal was tempered with charity,
and he loved and respected goodness wherever he found it.--His uncorrupted integrity,
and liberality, of sentiment, his great abilities and the suavity of his disposition,
gave him much interest with persons of rank and influence;
and he employed it in a manner that marked the benevolence of his heart.
He loved peace, and was often instrumental in settling disputes,
and in producing reconciliation between contending parties.
In private life, he was equally amiable.
His conversation was cheerful, guarded, and instructive.
He was a dutiful son, an affectionate and faithful husband, a tender and careful father,
a kind and considerate master.
Without exaggeration, it may be said,
that piety and virtue were recommended by his example;
and that though the period of his life was short, he had, by the aid of Divine grace,
most wisely and happily improved it.`"

The work by which the name of Robert Barclay is generally known,
is his "`Apology for the True Christian Divinity,`" etc. which he
presented to the king (Charles II.) by an address of singular merit,
for its plain sense and plain dealing,
both as respects the statements therein made concerning
the principles and practices of the Society of Friends,
and also in relation to the extraordinary circumstances of the king's own history.

After premising that the condition of kings and princes,
exposes them to greater observation than that of others, he remarks,
in this prefatory epistle,

"`But,
among all these transactions which it has
pleased God to permit for the glory of his power,
and the manifestation of his wisdom and providence,
no age furnishes us with things so strange and marvellous,
whether with respect to matters civil or religious,
as those which have fallen out within the compass of your time; who,
though you be not yet arrived at the fiftieth year of your age,
have yet been a witness of stranger things, than many ages before produced.
So that, whether we respect those various troubles wherein you found yourself engaged,
while scarce yet out of your infancy;
the many different afflictions with which men of
your circumstances are often unacquainted;
the strange and unparalleled fortune that befel your father;
your own narrow escape and banishment following thereupon,
with the great improbability of your ever returning, (at least, without very much pains,
and tedious combatings,) or finally,
the incapacity you were under to accomplish such a design,
considering the strength of those who had possessed themselves of your throne,
and the terror they had inflicted upon foreign states;–and yet that after all this,
you should be restored without stroke of sword, the help or assistance of foreign states,
or the contrivance and work of human policy; all these do sufficiently declare,
that it is the Lord's doing, which, as it is marvellous in our eyes,
so it will justly be a matter of wonder and astonishment to generations to come;
and may sufficiently serve, if rightly observed, to confute and confound that atheism,
with which this age does so much abound.`"

The conclusion of this address,
more especially commends the noble sincerity of the writer's heart; while,
to the credit of the king, it must be remembered,
that he took no offence at the Christian freedom it displays:

[.embedded-content-document.letter]
--

"`God has done great things for you,`" says Barclay.
"`He has sufficiently shown you, that it is by him princes rule,
and that he can pull down, and set up, at his pleasure.
He has often faithfully warned you by his servants,
since he restored you to your royal dignity;
that your heart might not wax careless against him to
forget his mercies and providences towards you;
whereby he might permit you to be soothed up, and lulled asleep in your sins,
by the flattering of court parasites, who, by their fawning,
are the ruin of many princes.

"`There is no king in the world,
who can so experimentally testify of God's providence and goodness; neither is there any,
who rules so many free people, so many true Christians;
which thing renders your government more honourable, and yourself more considerable,
than the accession of many nations, filled with slavish and superstitious souls.

"`You have tasted of prosperity and adversity;
you know what it is to be banished your native country,
to be over-ruled as well as to rule, and sit upon the throne: and being oppressed,
you have reason to know, how hateful the oppressor is, both to God and man.
If, after all these warmings and advertisements,
you do not turn unto the Lord with all your heart,
but forget him who remembered you in your distress,
and give up yourself to follow lust and vanity, surely, great will be your condemnation.

 "`Against which snare, as well as the temptation of those, that may, or do feed you,
and prompt you to evil; the most excellent and prevalent remedy will be,
to apply yourself to that light of Christ which shines in your conscience,
which neither can, nor will flatter you, nor allow you to be at ease in your sins;
but does and will deal plainly and faithfully with you, as those,
that are followers thereof, have also done.

"`God Almighty, who has so signally hitherto visited you with his love,
so touch and reach your heart, before the day of your visitation be expired,
that you may effectually turn to him, so as to improve your place and station,
for his name.
So wishes, so prays,

[.signed-section-closing]
"`Your faithful friend and subject,

[.signed-section-signature]
"`Robert Barclay.`"

--

This work was first published in Latin,
when the author had only attained his twenty-eighth year,
and has since passed through many English, and also foreign editions;
being translated into several languages.

"`The method and style of the book,`" says William Penn, "`may be somewhat singular,
and like a scholar; for we make that sort of learning no part of our divine science.
But that was not to show himself, but out of his tenderness to scholars; and,
as far as the simplicity and purity of the truth would permit,
in condescension to their education, and way of treating these points herein handled.`"

It would not come within the scope of a work like this,
to attempt any lengthened analysis of this valuable production.
It must be read through attentively, and above all things,
with a mind not only free from prejudice,
but imbued with a fervent desire of discovering truth,
in order to obtain a just insight into its merits.
But, a brief sketch of some of the leading subjects which it embraces,
and with great force, and calmness of spirit, enlarges upon, may not be unacceptable;
and which I, the rather feel inclined to offer to the reader's notice,
in the hope of its inducing him to turn to, and consider the work itself.
