== Chapter XIX

The [.book-title]#Apology for the True Christian Divinity#,`" is an
enlarged discussion of fifteen propositions,
which the author, in his address to the reader,
describes as briefly comprehending the chief principles and doctrines of truth.
As I propose to dwell upon those only,
which are best calculated to open the principles of the Society of Friends, the first,
"`Concerning the true Foundation of Knowledge,`" being of universal application,
may be merely stated, as an introduction to those we proceed to notice.
"`Seeing,`" he says,
"`that the height of all happiness is placed in the true knowledge of God,
(John 17:3) the true and right understanding
of this foundation and ground of knowledge,
is that which is most necessary to be known and believed, in the first place.

"`II. and III.
Concerning immediate Revelation; and the Scriptures.
"`Seeing, no man knows the Father but the Son, and he to whom the Son reveals him;
(Matt. 11:27) and seeing the revelation of the Son is in, and by the Spirit;
therefore, the testimony of the Spirit is that alone, by which the true knowledge of God,
has been, is, and can only be revealed.

"`It was by the revelation of this Spirit,
that God manifested himself unto the patriarchs, prophets and apostles:
which revelations, whether by outward voices and appearances, dreams,
or inward objective manifestations in the heart, were of old,
the formal object of their faith; and remain yet so to be,
since the object of the saints' faith, is the same in all ages,
though set forth under various administrations.
These divine inward revelations,
which we make absolutely necessary for the building up of true faith, neither do,
nor can ever contradict the outward testimony of Scripture, or right reason;
yet are they not to be subjected to the test of Scripture, or the natural reason of man;
because this divine illumination, is that which is evident and clear of itself; forcing,
by its own evidence, the assent of the well-disposed understanding,
even as the common principles of natural truths incline the mind to
assent thereto--as that "`the whole is greater than its part,`" etc.

"`From these revelations of the Spirit of God to the saints,
have proceeded the Scriptures of truth; but,
because these are only a declaration of the fountain, not the fountain itself, therefore,
they are not to be esteemed the principal ground of all truth and knowledge;
nor yet the adequate primary rule of faith and manners.

"`For,`" as he says, in more largely discussing this question in the body of the work,
"`that, whereof the certainty and authority depends upon another,
and which is received as truth, because of its proceeding from another,
is not to be accounted the principal ground and origin of all truth and knowledge.

"`But the Scripture authority and certainty depend upon the Spirit,
by which they were dictated; and the reason why they were received as truth is,
because they proceeded from the Spirit;
therefore they are not the principal ground of truth--which argument also holds as
to the Scriptures not being the primary adequate rule of faith and manners;
for that which is not my rule in believing the Scriptures themselves,
is not the primary adequate rule of faith, etc.
But the Scripture is not,
nor can it be the rule of that faith by which I believe Scripture;
therefore it is not the primary or adequate rule of faith.

"`Next, the very nature of the gospel itself declares,
that the Scriptures cannot be the only and chief rule of Christians;
else there should be no difference between the law and the gospel, which differ in this:
in that the law being outwardly written, brings under condemnation,
but has not life in it to save: whereas,
the gospel as it declares and makes manifest the evil, so it, being an inward,
powerful thing,
gives also ability to obey and deliver from the evil--hence it is
called '`glad tidings'--consisting not so much in words as virtue.
Wherefore, such as come to be acquainted with it,
feel greater power over their iniquities, than all outward laws or rules can give them.
Hence, the apostle concludes, (Rom. 6:14) "`sin shall not have dominion over you;
for you are not under the law, but under grace`'--this grace then,
which is an inward and not an outward law, is to be the rule of Christians.
Hence,
the apostle commends the elders of the church to it--(Acts 20:32)--to that spiritual law which makes free from sin,
(Rom. 8:2) which was not outward--as Rom. 10:8--manifests; where,
distinguishing it from the law, he says, "`it is nigh you; in your heart,
and in your mouth;' and this is the word of truth which we preach.`"

He further argues, that "`that which is given to Christians for a rule,
must needs be so full,
that it may distinctly guide and order them in all things that may occur.

"`But, because there are many hundreds of things,`" he says,
"`which Christians may be concerned in,
for which there can be no particular rule had from Scripture; therefore,
the Scripture cannot be an adequate and primary rule to them.`"

He illustrates this by some striking instances; and in particular,
in relation to a call to the ministry.

"`Paul said,
"`there was a necessity upon him to preach the gospel--and woe unto
him if he preached it not.`' If it be necessary that there be now
ministers of the church as well as then,`" he argues,
"`there is the same necessity upon some more than upon others, to occupy this place;
which necessity, as it may be incumbent upon particular persons,
the Scripture neither does, nor can declare.

"`If it be said, that the qualifications of a minister are found in the Scripture,
and by applying these qualifications to myself,
I may know whether I be fit for such a place or no, I answer,
the qualifications of a bishop or minister,
as they are mentioned both in the epistle to Timothy, and Titus,
are such as may be found in a private Christian; and which ought, in some measure,
to be in every true Christian; so that that gives a man no certainty.
Every capacity to an office, gives me not a sufficient call to it.
Next, by what rule shall I judge if I be so qualified?
How do I know that I am sober, meek, holy, harmless,
etc.? Is not the testimony of the Spirit in my conscience,
THAT which must assure me hereof?
And suppose that I were qualified and called,
yet what Scripture rule shall inform me whether
it be my duty to preach in this or that place;
in France, England, Holland or Germany?
Whether I shall take up my time in confirming the faithful, or converting infidels,
or in writing epistles to this or that church?

"`The general rules of the Scripture, namely: to be diligent in my duty,
to do all to the glory of God, and for the good of his church,
can give me no light in this thing:
seeing two different things may both have a respect that way,
yet may I commit a great offence and error in doing the one,
when I am called to the other.
If Paul, when his face was turned by the Lord toward Jerusalem,
had gone back to Achaia or Macedonia,
he might have supposed he could have done God more acceptable service,
in preaching and confirming the churches, than in being shut up in prison in Judea:
but would God have been pleased herewith?
No, certainly!
Obedience is better than sacrifice; and it is not our simply doing that which is good,
that pleases God; but that good which he wills us to do.`"

No observations can be more fitting than these, to the times in which we live.
Oh would, that in this day of bustle and stir in the way of good doings,
many busy ones would indeed remember,
that it is not their doing what they conceive themselves called upon to do,
that pleases God; but their doing what he would have them to do.
And what is that He has showed you, O man, what is good;
and what does the Lord require of you, but to do justly and to love mercy,
and to walk humbly with your God?

"`IV. Concerning the Condition of Man in the Fall.

"`All Adam's posterity, as to the first Adam, (or earthly man,) is fallen, degenerated,
and dead-- deprived of the feeling of the inward testimony or seed of God,
and subject to the nature and seed of the serpent, which he sows in men's hearts,
in this natural and corrupted state; from which it comes,
that not their words and deeds only,
but all their imaginations are evil in the sight of God.
Man, therefore, as he is in this state, can know nothing aright; yes,
his thoughts and conceptions concerning God, and things spiritual,
are unprofitable to himself and others, until he be disjoined from this evil seed,
and united to the divine light.
Nevertheless, this seed is not imputed to infants,
until by transgression they actually join therewith.

"`V. and VI. Concerning the Universal Redemption by Christ,
and the saving and Spiritual Light with which every man is enlightened.

"`God, out of his infinite love, who delights not in the death of a sinner, but,
that all should live and be saved, has so loved the world,
that he has given his only Son, a light, that whosoever believes in him should be saved;
who enlightens every man that comes into the world,
and makes manifest all things that are reproveable, and teaches all, temperance,
righteousness, and godliness,`"^
footnote:[See Ezekiel 18:23; Isaiah 49:6; John 3:16, and i. 9; Titus 2:11;
Eph. 5:13; Heb. 2:9.]
etc.

"`This certain doctrine then,
being received (namely,) that there is an evangelical and saving light and grace in all,
the universality of the love and mercy of God towards
mankind (both in the death of his beloved Son,
the Lord Jesus Christ,
and of the manifestation of the light in the heart,) is established, etc.;
the benefit of whose offering,
is not only extended to such as have the distinct
outward knowledge of his death and sufferings,
as the same is declared in the Scriptures;
but even unto those who are necessarily excluded from the benefit of this knowledge,
by some inevitable accident; which knowledge,
we willingly confess to be very profitable and comfortable,
but not absolutely needful unto such from whom God himself has withheld it,`" etc.

As the doctrine of a "`universal saving light,`" is that upon
which the peculiarity of Quakerism (so called) mainly depends,
it may be desirable to enter somewhat more minutely,
into what he advances respecting it.

Having considered man's fallen and lost condition by the fall,
"`it is fit to inquire,`" he says,
"`how and by what means he may come to be freed
out of this miserable and depraved condition?`"

And because the doctrine of the Calvinists, respecting election and reprobation,
lies in the way of what he has to state upon this point,
he begins his discourse by attacking that obstacle.

And first he affirms, that we may safely call this doctrine a novelty;
"`seeing,`" he says, "`that for the first four hundred years after Christ,
there is no mention made of it; for, as it is contrary to the testimony of scripture,
and the tenor of the gospel,
so all the ancient teachers of the church pass it over with a profound silence.
The first foundation of it was laid in the writings of Augustine, who,
in his heat against Pelagius, let fall some expressions,
which others unhappily have gleaned up for the establishing this error.
This doctrine was further fomented by Dominicus and the monks of his order:
and at last taken up by Calvin, (whom he admits to be a man, otherwise,
in several respects, to be commended,) but in this instance guilty of an error,
which tended to pollute his own reputation, and defame the Christian religion.
Not that they should call into question this doctrine, he says,
"`for the silence of the ancients respecting it; nor upon any other ground of that kind,
if they perceived it to have any foundation in the
writings or sayings of Christ and his apostles;
and if they did not see, that it is highly injurious to God himself,
to Jesus Christ our Mediator and Redeemer, and to the power, virtue, nobility,
and excellency of his blessed gospel, and also unto all mankind.`"

He then goes into the proof of these assertions; which, (the case being, as it were,
of a self-evident mature,) will scarcely stand
in need of any proof to the unprejudiced reader;
and all proof being useless to the prejudiced one, it may be passed by.
Neither need we follow him in his arguments to
establish the fact of Christ having died for all men;
the scripture more clearly and fully testifying to this,
than to any other point of Christian doctrine.
We come therefore to consider three propositions,
in which he states the subject of "`a universal saving light.`"

First.
"`That God, who, out of his infinite love,
sent his Son into the world to taste of death for every man, has given to every man,
whether Jew or Gentile, Turk or Scythian, Indian or Barbarian,
of whatsoever nation or place, a certain day or time of visitation,
during which day or time, it is possible for them to be saved,
and to partake of the fruit of Christ's death.

Secondly.
"`That, for this end, God has communicated and given unto every man,
a measure of the light of his own Son;–a measure of grace;--or, a measure of the Spirit;
which the scripture expresses by several names,
as sometimes of '`The seed of the kingdom,`' (Matt. 13:18-
19) '`The light that makes all things manifest,`' (Eph. 5:
13) '`The word of God,`' (Rom. 10:17) or,
'`Manifestation of the Spirit given to profit withal,`' (1 Cor. 12:
7) '`A talent,`' (Matt. 25:15) '`A little leaven,`' (Matt.
xiii.33;) '`The gospel preached in every creature,`' (Col. 1:23)

Thirdly.
"`That God in, and by this light and seed, invites, calls, exhorts,
and strives with every man, in order to save him; which,
as it is received and not resisted, works the salvation of all,
even of those who are ignorant of the death and sufferings of Christ, and of Adam's fall;
both by bringing them to a sense of their own misery,
and to be sharers of the sufferings of Christ inwardly,
and by making them partakers of his resurrection, in becoming holy, pure, and righteous,
and recovered out of their sins.
By which also are saved, they that have the knowledge of Christ outwardly,
in that it opens their understandings,
rightly to use and apply the things delivered in the scriptures,
and to receive the saving use of them.
But that this may be resisted and rejected in both; in which case,
God is then said to be resisted and pressed down, and Christ to be again crucified,
and put to open shame, in and among men, and to those that thus resist and refuse him,
he becomes their condemnation.

And with regard to the first proposition, i.e. the time of visitation granted to all,
during which they may be saved;
he does not understand it the whole time of every man's life;
though to some it may be extended to the hour of death,
as in the case of the thief upon the cross.
But he conceives it to be extended to such a season,
as sufficiently exonerates the Most High from every man's condemnation:
and if men outlive this day of salvation, God may justly allow them to be hardened,
as a just punishment of their unbelief, and even raise them up as instruments of wrath,
and make them a scourge one against another.
This is expressed by the apostle, (Rom.
i. from verse 17 to the end,) but especially verse 28, where it is said,
"`and even as they did not like to retain God in their knowledge;
God gave them over to a reprobate mind, to do those things which are not convenient.`"
That persons may outlive the day of God's gracious visitation to them,
he shows from the case of Esau,
(Heb. 12:16-17) and also by Christ's weeping over Jerusalem, and saying,
"`If you had known in this your day, the things that belong unto your peace;
but now they are hid from your eyes.`"
(Luke 19:42) which plainly imports a time when they might have known them.

Secondly.
By this seed, grace, word of God, and light, with which, he says, every man is,
in a measure, enlightened, he understands a spiritual, heavenly, and invisible principle,
etc. which, of its own nature, draws, invites, and inclines to God;
and this some call vehiculum Dei, or the spiritual body of Christ;
or the flesh and blood of Christ which came down from heaven,
of which all the saints do feed, and are thereby nourished unto eternal life.
And, as every unrighteous action is witnessed against and reproved, by this light,
and seed, so by such actions, it is hurt, wounded, and slain, and flees from them;
even as the flesh of man flees from that which is of a contrary nature to it.
Now because it is never separated from God, nor Christ, but wherever it is,
God and Christ are, as it were, wrapped up therein, so in that respect,
as it is resisted, God may be said to be resisted; and where it is borne down,
God is said to be pressed, "`as a cart under sheaves,`" (Amos 2:18) On the contrary,
as this seed is received into the heart,
and suffered to bring forth its natural and proper effect,
Christ comes to be formed and raised; of which spiritual birth,
the scripture makes so much mention,
calling it "`the new man,`" "`Christ within the hope of glory,`" etc.

"`This,`" he says, "`is that Christ within, which we are heard so much to speak,
and declare of: everywhere preaching him up,
and exhorting people to believe in the light, and obey it,
that they may come to know Christ in them, delivering them from all sin.`"

And here, it may humbly be suggested to the reader's consideration, whether such a view,
which turns the whole strength of faith upon that which is holy, heavenly, invisible,
internal, and precisely to be found where the evil which it is appointed to subdue,
is found, even in the spirit and soul of man--is not a more living, real,
and influential view of Divine help and salvation,
than that which fixes the mind's attention upon anything on the outside of it?
We need the presence of God within us; and therefore it is,
that he who is appointed to be our Saviour from sin and misery, says, "`Lo,
I am with you always, even unto the end of the world!`"

But, by what is herein stated, he affirms,
that it is not intended to represent that the Eternal Word dwells in us,
as it did in the Holy Jesus: inasmuch as it dwelt immediately and without measure,
in him; whereas in us, it dwells both measurably and mediately, in this holy seed.

Christ is the head, and we the members; he is the vine, and we the branches; and,
as the soul of man dwells in a far more immediate manner in the head and heart,
than in the hands or legs; and as the sap, virtue, and life of the vine,
lodges far otherwise in the root than in the branches,
so God dwells otherwise in the holy Jesus, than in us.

Neither does he, by these statements,
intend any way to derogate from the atonement and sacrifice of the Lord Jesus Christ;
but, on the contrary, he magnifies and exalts it:
firmly believing all things recorded thereof, in the Holy Scriptures;
and seeing a necessity that Christ should come, that by his death and sufferings,
he might offer up himself a sacrifice to God for our sins;
and that it is only by that sacrifice, we obtain remission of them;
since "`by the obedience of that one, the free gift is come upon all to justification.`"
For, as all men partake of Adam's fall, and the evil seed thereby communicated to them,
though thousands be ignorant of Adam's fall,
neither ever knew of the eating of the forbidden fruit; so also,
many may come to feel and obey the good influences of the holy and Divine seed and light,
which Christ's obedience and sufferings purchased for them,
though they know nothing of his coming in the flesh.

"`And as we affirm,`" he says,
"`it is absolutely needful that those do believe
the history of Christ's outward appearance,
whom it pleases God to bring to the knowledge of it; so we do freely confess,
that even that outward knowledge is very comfortable to such as are subject to,
and led by, the inward seed and light.
For, not only does the sense of Christ's love and sufferings tend to humble them,
but they are thereby also strengthened in their faith,
and encouraged to follow that excellent pattern which he has left us:
"`who suffered for us, as says the apostle Peter,
(1 Peter 2:21) leaving as an example that we should follow his steps.
And many times,
we are greatly edified and refreshed with the
gracious sayings which proceed out of his mouth.
The history then is profitable with the mystery, and never without it;
but the mystery is, and may be profitable,
without the explicit and outward knowledge of the history.

He states further,
that he understands not this divine principle to be the
relics of any good left in man's nature at the fall,
or any part of man's nature at all; but that it is totally separate from man's soul,
and all the faculties of it.
Man indeed may apprehend in a notional way, a knowledge of God and of spiritual things;
but it not being by the right organ, it cannot profit him towards salvation,
but rather hinders; "`and indeed,`" he says, "`the great cause of the apostacy has been,
that man has sought to fathom the things of God,
in and by the natural and rational principle; and to build up a religion in it,
neglecting and overlooking this principle and seed of God, in the heart: so that herein,
in the most universal and catholic sense, has anti-Christ in every man, set up himself,
and sits in the temple of God, as God, and above every thing that is called God.`"
For man being the temple of the Holy Ghost, as says the apostle,
(1 Cor. 3:16) when the rational principle sets up itself there,
above the seed of God, to reign and rule as a prince in spiritual things,
while the holy seed is bruised and wounded,--there is anti-Christ in every man,
or somewhat exalted above and against Christ.
Nevertheless, we do not hereby affirm as if man had received his reason to no purpose;
we look upon reason as fit to order and rule man in things natural.
For, as God gave two great lights to rule the outward world, the sun and moon,
the greater light to rule the day, and the lesser light to rule the night;
so has he given man the light of his Son, a spiritual, divine light,
to rule him in things spiritual, and the light of reason to rule him in things natural.
And, even as the moon borrows her light from the sun, so ought men,
(if they would be rightly and comfortably ordered in natural things,)
to have their reason enlightened by this divine and pure light.`"

He further distinguishes this light from the conscience, which last, experience shows,
may be corrupted and darkened,
(which this light cannot be,) as is expressly stated of the impure,
(Titus 1:15) "`That even their mind and conscience is defiled.`"
He illustrates this by the case of a Turk, who, thinking it unlawful to drink wine,
is troubled by his conscience if he does so;
but if he lives in open licentiousness in some other respects, he feels no remorse,
because his judgment is already defiled by a false
opinion that it is lawful for him to do the one,
and unlawful to do the other; whereas, if the light of Christ in him had been minded,
it would have reproved him for impurity; and also, as he became obedient thereto,
would have informed him that Mahomet was an impostor,
as well as Socrates was informed by it, in his day,
of the falsity of the heathen's gods.

This seed or light is also distinguishable from man's natural powers of mind,
inasmuch as these, when in health, he can exercise as he will; and,
except there be some natural impediment in the way, he is absolutely master of them.
But this light and principle of God, he cannot move and stir up when he pleases;
but it moves and strives with every man, as the Almighty sees fit.
For, though there be a possibility of salvation to all during the day of visitation,
yet cannot a man at any time when he has some sense of his misery,
stir up that light and grace,
so as to procure to himself tenderness and contrition of heart.
But he must wait for it; since it comes upon all at certain times and seasons,
wherein it works powerfully upon the soul, at which time, if man resist it not,
but unites with it, he comes to know how it saves and delivers from sin;
for even as the lake of Bethesda did not cure all those that washed in it,
but such only as washed first after the angel had moved upon the waters,
so God moves in love to mankind, in this seed in his heart, at some singular times,
setting his sins in order before him, and seriously inviting him to repentance,
offering him remission of sins and salvation, which, if man accept of, he may be saved.

"`Now,`" he says, "`there is no man alive,
and I am confident there are none to whom this paper shall come, who,
if they will deal faithfully and honestly with their own hearts,
will not be forced to acknowledge, but they have been sensible of this, in some measure,
less or more;
and that it is a thing which man cannot bring
upon himself with all his pains and industry.
This then, oh man, and woman I this,
is the day of God's gracious visitation to your soul, which, if you resist not,
you shall be happy forever.
This is the day of the Lord, which, as Christ says,
is like the lightning which shines from the east unto the west,
and the wind or spirit which blows upon the heart,
and no man knows where it goes nor from where it comes.`"

He describes the operation of this principle in the heart,
to depend in the first instance, upon its not being opposed.
"`The working is of the grace,`" he says, "`and not of the man, and it is a passiveness,
rather than an act; though afterwards as man is wrought upon,
there is a will raised in him by which he comes to be a coworker with the grace.
So that the first step is not by man's working, but by his not contrary working.
He illustrates this statement by supposing the case of a man greatly diseased, (which,
as to the soul, is true of the human race universally.)

"`I suppose,`" he says, "`God, who is the great physician,
not only to give this man medicine but to come and pour the remedy into his mouth,
and as it were, to lay him in his bed: so that if the sick man be but passive,
it will necessarily work its effect; but, if he be stubborn and untoward,
and will needs rise up and go forth into the cold,
or eat such fruits as are hurtful to him while the medicine should operate, then,
though of its own nature it tends to cure him, yet will it prove destructive to him,
because of the obstructions it meets with.
Now, as the man that should thus undo himself would certainly be the cause of his own death,
so, who will say that, if cured, he owes not his health wholly to the physician,
and not to any deed of his own?`"

The second example whereby he further explains himself,
is that of several men lying in a dark pit together,
where all their senses are so stupified,
that they are scarcely aware of their own misery; to which condition,
he compares the state of man, in his fall.
"`I suppose not,`" he says, "`that any of these men, wrestling to deliver themselves,
do thereby stir up or engage one able to deliver them, to give them his help;
saying to himself, '`I see one of these men willing to be delivered,
and doing what in him lies, therefore he deserves to be assisted;`' as say the Socinians,
Pelagians, and Semi-Pelagians.

"`Neither do I suppose that this deliverer comes
to the top of the pit and puts down a ladder,
desiring them that will, to come up, as do the Jesuits and Arminians,
who suppose the ladder to be the grace by which they are delivered.
But I suppose that the Deliverer comes at certain times,
and fully discovers and informs them of the great misery and hazard they are in,
if they continue in that noisome and pestiferous place, yes,
forces them to a certain sense of their misery;
(for the wickedest men at times are made sensible of their misery,
by God's visitation;) and not only so, but also lays hold upon them,
and gives them a pull, in order to lift them out of their misery: which,
if they resist not, will save them, only they may resist it.`"

And in all this, the grace of God is not frustrated,--only its effect is changed; seeing,
that as it is the ministration of love and mercy in those who receive it,
(John 1:12) so is it the ministration of wrath and condemnation,
in those who reject it.

The whole of these statements in so far as respects a
time of visitation granted by God to all men,
wherein it is possible for them to be saved, and that inward, holy,
heavenly principle or light of Christ, whereby their salvation is effected,
he then proceeds to prove from Scripture; as in the case of Cain,
who evidently had a day of mercy offered him,
(Gen. 4:6-7) before the evil seed began to tempt him and work in his heart; God,
thus giving warning to Cain in season, and showing him,
that in doing well he would be accepted.
Also in the case of the old world, when the Lord said,
"`My Spirit shall not always strive in man;`" (for so he says it ought to be
translated:) which expression manifestly implies that his Spirit did,
and does strive for a season in man.
God is also said in Scripture, to be long-suffering and waiting to be gracious,
(Isaiah 30:18; Exodus 34:6; Numbers 14:18; Ps. 86:15;
Jer. 15:15) The apostle Peter also says expressly,
that the long-suffering of God waited in the days of Noah for those of the old world;
(1 Pet.
iii.20;) and again the same apostle says,
that "`the long-suffering of God is to be accounted salvation.`"
Also, the apostle Paul (Rom. 2:4) says,
"`Do you despise the riches of his goodness and forbearance, and long-suffering;
not knowing that the goodness of God leads you to repentance;`"
and here Paul is speaking to the unregenerate and wicked,
who (in the following verse he says,) treasure up wrath unto the day of wrath;
and yet to such it is,
that he commends the riches of the forbearance and longsuffering of God.

It appears also from the prophet Isaiah 5:4, that a day of grace is granted to mankind;
the inhabitants of Jerusalem and men of Judah being
called upon to judge between the Lord and his vineyard;
which example of a vineyard is also used by Christ, (Matt. 21:33; Mark 12:1;
Luke 20:9) where he shows how, for some it was planted,
and all things given them that were necessary to produce fruit,
to pay or restore to their master;
and how the master many times waited to be merciful to them,
in sending servants after servants,
and passing by many offences before he determined to destroy and cast them out;
which parable, he says, cannot be understood of the saints,
or of such as repent and are saved, for it is said expressly, "`he will destroy them.`"
Neither would the parable have any ways answered the end for which it is produced,
if these men had not been in a capacity to have done good; yes, such was their capacity,
that the Spirit of Christ says in the prophet, "`What could I have done more?`"

In regard to that whereby God offers salvation to every man,
he proves it to be the light of Christ, from that text in John 1:9;
"`that was the true light which enlightens every
man that comes into the world;`" which assertion,
he says, flows as a consequence or deduction,
from two propositions stated in the former verses of this chapter: first,
that "`the light that is in him (Jesus Christ) is the light of men;`" and secondly,
that "`the light shines in darkness:`" from which is inferred,
"`He is the true light that enlightens,`" etc.

Here, the divine apostle distinctly calls Christ "`the light of men;`" also,
that "`this light shines in darkness,
though the darkness comprehend it not;`" and thirdly,
that this "`true light enlightens EVERY man that comes into the world.`"

For what end this light is given, is expressed verse 7,
where John is said to come for a witness to the light,
"`that all men through it might believe; that is, through the light, __di auton__,
which,`" he says, "`does very well agree with __phogos__, as being the nearest antecedent,
though most translators (to make it suit with
their own doctrine) have made it relate to John,
as if all men were to believe through John`"--which was not possible,
because all men could not know of John's testimony; whereas,
all men being lighted by this light, may thereby come to believe.
John shone not in darkness, but this light did, that having dispelled that darkness,
it might produce faith.

We are commanded to believe in this light by Christ's own words, (John 12:36) and,
that a measure of it is given to all, we are told in the parable of the sower,
(Matt.xiii.
Mark, iv.
Luke,8.) He says also, that this seed sown in those several sorts of grounds,
is "`the word of the kingdom,`" which the apostle calls the word of faith,
(Rom. 10:8) and James, the implanted, "`the engrafted word,
which is able to save the soul,`"--and that it is that which is saving,
the words themselves declare, since in the good ground it fructified abundantly.

Many more testimonies in proof of these propositions,
he produces from Scripture as well as from other authorities;
but having already exceeded the expected limit to this subject, they must be omitted,
in order that a small space may be allotted to his views upon the subject of worship.

He introduces this important topic by remarking,
that "`as obedience is better than sacrifice,`" so neither is any sacrifice acceptable,
but that which is done according to the will of him to whom it is offered.

"`But men finding it easier to sacrifice in their own wills,
than to obey God's will,`" says he, "`have heaped up sacrifices without obedience,
and thinking to deceive him as they do one another, give him a show of reverence,
honour and worship,
while they are inwardly alienated from his holy and righteous life.`"

He then refutes the so often alleged charge against the Quakers,
that they denied all public worship, because they denied all forms and ceremonies, etc.
"`We are none of those,`" he says,
"`who forsake the assembling of ourselves together;`" and reverting to this matter again,
he sufficiently establishes this fact by what follows;
"`for when the magistrates,`" he says,
"`stirred up by the malice and envy of our opposers, have used all means possible,
and yet in vain, to deter us from meeting together, both death, banishments,
imprisonments, finings, beatings, whippings, and other such devilish inventions,
have proved ineffectual to terrify us from our holy assemblies.`"

That they met together, frequently at the hazard of their lives,
was a fact too notorious to be questioned; since it was more often than not,
at this period, that their meetings were disturbed by the arrival of rude soldiers,
who dispersed them with severe wounds and bruises, so that in some instances,
even death ensued in consequence thereof.
There was no difficulty therefore in proving that they met together;
but what they met together for, without priest, bell, or book,
baffled all the conceptions of worship which the natural man could form; and here it was,
that they fell under various suspicions of assembling to plot against government,
or to set up Roman Catholicism, or to do anything in the world,
but to "`be still`" before God.

The duty of assembling together for the purpose of divine worship being acknowledged,
he proceeds to state what he believes that worship to consist in: which he simply,
and in scripture terms describes, as "`waiting upon God.`"

"`Now, how is this waiting upon God,`" he asks,
"`or watching before him--+++[+++to be accomplished]
but by silence`" which, as it is in itself a great and principal duty, so it necessarily,
both in order of nature and time, precedes all other.

He admits that mention is made (in scripture) of the duties of praying, preaching,
and singing; but what order or method should be kept in so doing,
or that these duties should be set about so soon as persons are gathered together,
there is no direction; and man in his natural state if unaided by the Spirit,
being incapable of acting rightly in spiritual things,
how shall he exercise his first and previous duty of
waiting upon God for the help of his good Spirit,
but by bringing the natural part to silence?
and this,`" he says,
"`can only be accomplished by abstaining from his own thoughts and imaginations,
as well in things materially good, as evil; that he being silent--God may speak in him,
and the good seed may arise.`"

He illustrates this very happily in the following example.

"`He that comes to learn of a master,`" he says,
"`if he expect to hear his master and be instructed by him,
must not continually be speaking of the matter to be taught, and never be quiet;
otherwise how shall his master have time to instruct him.
Yes, though the scholar were never so earnest to learn the science,
yet would the master have reason to reprove him as untoward and indocile,
if he would always be meddling of himself, and still speaking,
and not patiently wait in silence to hear his master instructing and teaching him.
. . So also, if one were about to attend a great prince,
he would be thought an impertinent and impudent servant, who,
while he ought patiently and readily to wait
that he might answer the king when he speaks,
and have his eye upon him to observe the least motion and inclination of his will,
and to do accordingly, would be still deafening him with discourse,
though it were in praises of him,
and running to and fro without any particular and immediate
order to do things that perhaps might be good in themselves,
or might have been commanded at other times to others.
Would the kings of the earth accept of such servants and services?`"

He confirms the duty of waiting for the inspiration of
the Holy Ghost preparatory to praying or preaching,
by various scriptures, and also by a citation of considerable power,
from Franciscus Lambertus, (Tract v. chap.
3.) "`Beware,`" he says,
"`that you determine not precisely to speak what before you have meditated,
whatsoever it be; for,
though it be lawful to determine the text which you are to expound,
yet not at all the interpretation; lest if you so do,
you take from the Holy Spirit that which is his, i.e., to direct your speech,
that you may prophesy in the name of the Lord, void of all learning, meditation,
and experience, and as if you had studied nothing at all; committing your heart,
your tongue, and yourself, wholly unto his Spirit,
and trusting nothing to your former studying or meditation, but saying within yourself,
in great confidence of the divine promise, "`The Lord will give a word,
with much power unto those that preach the gospel.`"

"`But above all things,
be careful you follow not the manner of hypocrites who
have written almost word for word what they are to say,
as if they were to repeat some verses upon a theatre,
having learned all their preaching as they do that act tragedies, and afterwards,
when they are in the place of prophesying, pray the Lord to direct their tongue;^
footnote:[It seems indeed,
somewhat incongruous to hear a supplication for the aid of the Holy Spirit "`to
give a word in season,`" when such words as are to be spoken are already gathered,
and lying in black and white on the desk before the preacher!]
but in the meantime shutting up the way of the Holy Spirit,
they determine to say nothing but what they have written.

"`Why do you pray to the Lord, you false prophet,
to give you his Holy Spirit by which you may speak things profitable,
and yet you repel the Spirit?`"

Thus briefly having scanned some of the most prominent of the topics
discussed in this valuable manual of true Christian divinity,
we will close the subject with a testimony to its merits from Mr. Norris,
a minister of the Church of England, and himself no mediocre writer.

"`I cannot think Quakerism inconsiderable,`" he says,
"`as the principles are laid down and managed by Barclay.
That great and general contempt they lie under,
does not hinder me from thinking the sect of Quakers to be by
far the most considerable of any that divide from the church,
in case the Quakerism that is generally held be the same with
that which Mr. Barclay has delivered to the world,
as such; whom I take to be so great a man, that I profess freely,
I had rather engage against a hundred Bellarmines, Hardings, and Stapletons,
than with one Barclay`"--(Of Divine Light.--Tract II. p. 32.)^
footnote:[Sir James Mackintosh also observes,
with respect to Barclay and his [.book-title]#Apology#: "`Of those first who systematized,
and perhaps insensibly softened the Quakers' creed, was Barclay, a gentleman of Scotland,
in his Apology for the Quakers; a masterpiece of ingenious reasoning,
and a model of argumentative composition, which extorted praise from Bayle,
one of the most acute and least fanatical of men.`"-- Mackintosh's [.book-title]#Revolution in England#,
p. 169.]
