== Chapter XXI

The pages of this memorial might yet be greatly prolonged,
since many names are still unmentioned of those amongst the primitive friends,
who faithfully distinguished themselves on the side of God and truth,
"`in the midst of a crooked and perverse generation.`"
But the purpose of the writer being, as she humbly conceives, now sufficiently answered,
by the testimonies already recorded,
it appears desirable for her to draw to a conclusion; more especially,
as little of striking or important incident occurred in the
history of him who may be said to be the hero of the work,
after his imprisonment at Worcester.

In the year 1684 George Fox paid another visit to Holland; and on his return,
describing himself in his Journal,
as being "`weak with travel and continual exercise,`"
he stayed some time in London to rest himself,
and recover his health.
Indeed, from this period, we find him occasionally remarking in his Journal,
the decline of his health,
and the necessity he found of getting now and then into the country,
to recruit his strength.

On these occasions, he frequently visited Kingston upon Thames,
where one of his wife's daughters, Margaret Rouse, resided;
at the house of another of her son's-in-law, William Mead, in Essex,
he also made frequent visits.

He speaks of himself in the year 1688,
as having been three months in the country for the sake of his health,
"`which,`" he says, "`was very much impaired;
so that I was hardly able to stay in a meeting the whole time,
and often after a meeting was eager to lie down on a bed.`"

And truly, when we remember the sufferings of his earlier years,
and the injury which his constitution must thereby have sustained,
it is rather a matter of surprise that his course was so far extended,
although he had not numbered the allotted years of man,
when it pleased the Lord to summon him from here.

"`Yet, did not my weakness of body,`" he adds,
"`take me off from the service of the Lord:
but I continued to labour in and out of meetings, in the work of the Lord,
as he gave me opportunity and ability.`"
"`But the time was come that Israel must die!`"

Yet came this time upon George, so gently, that even to the last,
he was found about his Master's business.
For the few months previous to his departure,
his time was chiefly occupied in writing different epistles, to warn,
or to build up friends in the truth.
About a year before his decease,
he speaks of having a concern upon his spirit with respect to
a twofold danger that attended some who professed the truth.

"`One,`" he says, "`was of young people's running into the fashions of the world;
and the other was of old people's going into the earth`" under
the pressure of which exercise he wrote an epistle,
which he addressed:

[.embedded-content-document.letter]
--

[.salutation]
"`To all that profess the truth of God.

"`My desires,`" he says, "`are, that you walk humbly in it:
for when the Lord called me forth,
he let me see that young people grew up together in vanity,
and the fashions of the world, and old people went downwards into the earth,
raking it together.
And now, friends, I see too many young people that profess the truth,
grow up into the fashions of the world, and too many parents indulge them.
And amongst the elder, some are declining downwards, and raking after the earth.
Therefore take heed that you are not making your graves while you are alive outwardly,
and 'loading yourselves with thick clay.'
(Hab. 2:6) For, if you have not power over the earthly spirit,
and that which leads into a vain mind, and the fashions of the world,
and into the earth;--though you have often had the rain fall upon your fields,
you will but bring forth thistles, briars, and thorns, which are for the fire,`" etc.

--

His last work of this kind was an epistle of
consolation and counsel to friends in Ireland,
who had been, and still were, under peculiar trials and hardships.
Two days afterwards, being Sunday, the 11th of January, 1691, or,
according to the ancient friends mode of reckoning, who, following scripture,
made the month of March the first in the year, "`the 11th of 11th month, 1690,
he went to the meeting in Gracechurch-street,
which was as large as it usually was on the first day of the week.

Here he was favoured with ability to preach the
everlasting gospel with great power and clearness;
after which he prayed, and when the meeting was ended, he went,
in company with some other friends, to the house of one Henry Gouldney,
in White-Hart Court, near the meetinghouse.

It would seem as though the moment his faithful labours were accomplished,
the messenger of death was sent to summons him;
for he told some of his friends he thought he felt the cold strike his heart,
as he came out of the meeting; yet, he added, "`I am glad I was here.
Now I am clear-- I am fully clear!`"

As soon as his friends had quitted him, he lay down, as he sometimes did, after meeting,
but he soon rose again; and the sensation of cold still continuing,
with a manifest decline of strength, he retired at once to his bed,
where he lay in much contentment and peace, and very sensible to the last.

"`As he lived,`" says William Penn,^
footnote:[In his preface to [.book-title]#G. Fox's Journal#, pp.
30 and 31.]
"`so he died; feeling the same eternal power that had raised and preserved him,
in his last moments.`"

"`So full of assurance was he,`" continues the same writer,
"`that he triumphed over death; and so, even to the last,
as if death was hardly worth notice or mention; recommending to some with him,
the dispatch and dispersion of an epistle just before
written to the churches of Christ throughout the world,
etc.; but above all--friends --and of all friends, those in Ireland and America;
twice over, saying, 'Mind poor friends in Ireland and America!'

"`To some who came in, and inquired how he found himself, he answered,
'Never heed! the Lord's power is over all weakness and death!
The Seed reigns! +++[+++his accustomed and favourite expression,]
blessed be the Lord!' He was at the great meeting near Lombard street,
on the first day of the week, and it was the third following, about ten at night,
when he left us; being at the house of H. Gouldney, in the same court.

"`In a good old age he went,`" proceeds William Penn,`"
after having seen his children's children in the truth,
to several generations.
He had the comfort of a short illness, and the blessing of a clear sense to the last;
and we may truly say, with a man of God of old, that 'being dead,
he yet speaks,' and though absent in body, he is present in spirit;
neither time nor place being able to interrupt the communion of saints,
nor dissolve the fellowship of the spirits of the just.
His works praise him, because they are to the praise of Him that worked by him;
for which his memorial is, and shall be blessed.
I have done,
(as to this part of my preface,) when I have left this short epitaph to his name:
'Many sons have done virtuously in this day; but dear George!--you excel them all!'`"

Such was the testimony of William Penn,
whose acquaintance with George Fox was of so intimate a nature,
as to qualify him in no common measure, to speak thus decidedly upon his merits.

"`I write my knowledge,`" he says, alluding to his character of him,
in the preface to his Journal, "`I write my knowledge, and not report;
and my witness is true, having been with him, for weeks and months together,
on several occasions, and those of the nearest and most exercising nature:
and that by night and by day, by sea and by land, in this and in foreign countries;
and I can say, I never saw him out of his place,
or not a match for every service and occasion.
For, in all things, he acquitted himself like a man; yes, a strong man,
a new and heavenly-minded man, a divine, and a naturalist,
and all of God Almighty's making.
. .

"`He was a man,`" he says,
(in the former part of this preface,) "`that God
endowed with a clear and wonderful depth;
a discerner of other's spirits, and very much a master of his own.
And though the side of his understanding which lay next the world,
and especially the expression of it, might sound uncouth and unfashionable to nice ears;
his matter was, nevertheless, very profound,
and would not only bear to be often considered, but the more it was so,
the more weighty and instructive it appeared.

"`He had an extraordinary gift in opening the scriptures;
he would go to the marrow of things, and show the mind, harmony, and fulfilling of them,
with much plainness, and to great comfort and edification.

"`But above all, he excelled in prayer!
The inwardness and weight of his spirit,
the reverence and solemnity of his address and behaviour,
and the fewness and fulness of his words,
have often struck even strangers with admiration,
as they used to reach others with consolation.
The most awful, living, reverent frame I ever felt or beheld, I must say, was his,
in prayer.
And truly, it was a testimony that he knew, and lived nearer to the Lord than other men;
for they that know him most,
will see most reason to approach him with reverence and fear.`"

Such, and much more than is here transcribed, is the testimony of William Penn,
to the memory of his well-known and beloved friend.

George Fox departed this life in the sixty-seventh year of his age,
and was buried in friends' burying-ground, near Bunhill Fields;
his body being borne to the grave by friends,
and accompanied by great numbers of persons of those who were,
and of those also who were not, in profession with the society.

Previous however to this, a meeting was held in the meeting-house in White-Hart Court;
where he had so often,
(and only on the preceding sabbath,) borne witness to "`the truth as it is in Jesus.`"
Upon this occasion, a great, and as it is described, a heavenly solemnity,
covered the assembly; in which many deep and affecting testimonies were borne,
under a feeling sense of the powerful and God-glorifying
ministry of that dear and ancient servant of the Lord,
whose mortal remains were then about to be consigned to the tomb.

Few indeed could be the occasions in which there would be experienced
more melting of heart in paying the last tribute of respect and love,
than on this,
in which (in a certain sense) every individual present mourned
the loss of a father-- and of a prince in Israel.

Various were the testimonies given to his memory by different individuals in the society.
In that of his wife, she gives an account of his services and call to the ministry,
in a very direct and original way; concluding it with a sort of explanation, of what,
no doubt, appeared extraordinary to many; namely,
the state of separation as to their outward habitation and relation,
in which they lived with respect to each other.

"`And though the Lord,`" she says, "`had provided an outward habitation for him, yet,
he was not willing to stay at it, because it was so remote and far from London,
where his service most lay.
And my concern for God, and his holy eternal truth, was then in the north,
where God had placed and set me,
and likewise for the ordering and governing of my children and family;
so that we were willing both of us to live apart some years, upon God's account,
and his truth's service, and to deny ourselves of that comfort which we might have had,
in being together.
And if any took occasion, or judged hard of us because of that, the Lord will judge them,
for we were innocent.`"

She then proceeds to state how often she took long journeys to visit him,
and to be serviceable also in the cause of truth.

"`Though I lived two hundred miles from London,`" she says,
"`yet have I been nine times there upon the Lord's, and upon his truth's account;
and of all the times that I was in London, this last was most comfortable,
that the Lord was pleased to give me strength and ability to travel that great journey,
(being seventy-six years of age,) to see my dear husband.
. . I look upon it that the Lord's special hand was in it, that I should go there;
for he lived but about half a year after I left him.
. . .

"`And now,`" she concludes her statement by saying, "`And now he has finished his course,
and his testimony, and is entered into his eternal rest and felicity.
I trust in the same powerful God,
that his holy arm and power will carry me through whatever he has yet for me to do,
and that he will be my strength and support, and the bearer up of my head unto the end,
and in the end.
For I know his faithfulness and goodness, and I have experience of his love:
to whom be glory and powerful dominion forever.
Amen!`"

It seems superfluous to add any remarks to the testimony of a
contemporary upon the character and labours of George Fox;
but some few tributary words appear to be due from the compiler of this memorial,
not only as it respects his peculiar gift and calling,
but also with regard to the opinion that may be formed of both,
by those into whose hands these pages may fall,
and to whom he was previously altogether unknown.
It may be desirable therefore to state,
that should any reader of this eulogy by William Penn,
be induced to search in the works of George Fox for
confirmation of the superiority so warmly commended,
he would meet with disappointment; and that,
not because George Fox was unworthy of the praises bestowed upon him,
but because they were rendered to a very different kind
of merit than any which distinguished him as a writer;
for, in this capacity, as well as in that of a speaker, he was, even in his own times,
exceedingly illiterate and uncouth;
and he that seeks to know and admire his endowments on that side,
will probably turn away with a feeling even stronger than disappointment.
But as it nowhere appears, throughout his history,
that he ever claimed anything upon this score, but that on the contrary,
it was his glory to acknowledge that no arts or parts of human advantages,
had been made instrumental in the work and service to which he was called,
and that God alone, in and through the weakness of the creature,
had glorified the Spirit of his Son;--it would be as ungenerous,
as it assuredly would be unjust,
to contemn him for his lack of that to which he not only never laid claim,
but which the very nature of his mission excluded.

The errand he was sent upon, as he himself repeatedly states,
was to turn persons away from all human dependencies, to the rock, Christ Jesus,
teaching, and strengthening them in their own souls.
It would be an anomaly indeed, if a person fraught with such a message as this,
were selected from those who are clothed with the accomplishments of learning,
and the graces of oratory.
To make such a choice for such a purpose, would be acting indeed as man acts,
but not as He acts whose thoughts are not as man's thoughts, neither are his ways.

It is not to be said that God never selects his
ministers for a new and mighty work of conversion,
from the schools of learning and science;
but all experience proves that he but rarely does so.
And the reason why he does not, cannot but be obvious to every considerate mind,
that observes with due humility, the immense corruption of the natural heart,
and its liability to run into idolatrous attachments,
even upon points where the least danger is suspected.
And hence it is, that since the creation of the world, as a pious writer well observes,^
footnote:[William Law.]
when God is about to do a great work, he chooses (virtuous indeed, but) illiterate,
and in the eyes of man, contemptible instruments, whereby to accomplish it;
in order that the creature may be forever excluded from having
any share in the glory which belongs only to the Creator;
an exclusion which scarcely ever is made, however it may be pretended to,
while the proneness of the human heart to worship human advantages,
and to make an idol of that which ministers to its satisfaction,
has anything to nourish it.

Slight and insignificant therefore, to the natural eye,
were the recommendations of George Fox as a minister of the gospel.
Some persons have doubted whether he could even read or write;
but that he could do both (though but indifferently) is very certain.

His qualifications for the post assigned him, were as peculiar as the service itself;
and consisted, as that did, in the solidity of truth and wisdom.
He neither said or did anything that had not weight and reality in it.
Though evidently gifted by nature (so to speak,) with no ordinary portion of wit,
it never ran out into frivolity; but was advantageously used, as occasion served,
for the advancement of his Master's cause.
It is probable from the spirit manifested in his life and writings,
that the tender and loving graces were not so much the characteristic of his ministry,
as the more lofty and severe.
A noble man, in truth he was; glorious and comely,
with the comeliness which his heavenly Master put upon him.
To realize this, we need but recur to his unflinching deportment before his oppressors;
his rejection of every measure for his liberation from prison,
when liberty was offered him upon terms that did but seem
inimical to the purity of his profession of religion;
and his faithfully bearing to different authorities, his own court order,
and the unjust charges which made him liable to unmerited punishment.
These, and such as these, are lineaments in the portrait of George Fox,
which stamp it with its peculiar attraction;
an attraction which can have but little power
over the inquirer after such things as appeal to,
and charm, the merely intellectual faculties.

No; it is not for these beholders that he is to be made the object of attention,
but simply to the lovers of truth wherever truth is to be found.
To such he offers a striking and valuable specimen of the sort of instrument by
which it most commonly pleases the wisdom of God to accomplish his infinite designs,
and by "`the foolishness of whose preaching, to save them that believe.`"
(1 Cor. 1:21)

George Fox was survived several years by his wife Margaret,
of whom it is no slight commendation to say, that she was worthy of him.

This excellent individual was of good family, her father, John Askew, Esq.
being, as she describes him, "`one of those esteemed and called gentlemen,
who left a considerable estate which had been in
his name and family for several generations.`"

Before she was eighteen, she married Judge Fell, of Swarthmore in Lancashire,
in which county her father also resided.
With her first husband, who was sixteen years her senior,
she appears to have lived in great peace and comfort,
undisturbed by any opposition from him,
although he was never so far brought over to her religious principles,
as to unite himself to the society she had joined.
"`But he was loving and kind,`" she says, "`to our friends called Quakers;
. . . and a merciful man to the Lord's people.`"

Her services in behalf of the suffering members of the society,
in appealing to the king and other authorities both personally and in writing,
were of the most persevering and undaunted kind;
and such as manifested her to be one in spirit and courage with her friend George Fox.

"`In the year 1660,`" she says, "`King Charles the Second came into England;
and within two weeks after, I was moved of the Lord to go to London,
to speak to the king concerning the truth, and the sufferers for it;
for there were then many hundreds of our friends in prison,
in the three nations of England, Scotland, and Ireland,
which were put in by the former powers.
And I spoke often with the king, and wrote many letters and papers to him.

"`And I wrote and gave papers and letters to every one of the family, several times;
i.e. to the king, to the Duke of York, to the Duke of Gloucester, to the queen-mother,
to the Princess of Orange, and to the Queen of Bohemia.

"`I was moved of the Lord to visit them all, and to write unto them,
and to lay the truth before them; and did give them many books and papers,
and did lay our principles and doctrines before them,
and desired that they would let us have discourse with their priests, preachers,
and teachers, and if they could prove us erroneous, then let them manifest it;
but if our principles and doctrines be found according to the doctrine of Christ,
and the apostles and saints in the primitive times, then let us have our liberty.^
footnote:[From an old work, entitled [.book-title]#A brief Collection of remarkable Passages, etc. relating to Margaret Fell#, (p. 4,) and from which the present account of her is taken.]

"`But,`" as the reader will not be surprised to hear,
"`we could never get a meeting with any sort of them.`"

But though King Charles and his friends could not be
prevailed upon to comply with this proposal,
he appears to have been generally courteous and
kind in his reception of her applications;
and an order had been actually signed by him in council
for the release of the imprisoned Quakers,
when the insurrection of the Fifth-monarchy men totally nullified it,
by causing friends to be suspected of treachery;
no plot of any kind appearing but it was laid at their door.

The prisons being then thronged with them, "`many a time,`" says this valiant woman,
"`did I go to the king about them,
who promised me always that they should be set at liberty;
and we had several in the council who were friendly to us,
and we gave many papers to them;`" the result of which was,
that after "`much ado`" as she expresses it,
some favours were extended to the imprisoned friends,
and many of them were liberated by proclamation from the king and council.

While thus active in behalf of other sufferers,
she was not unacquainted herself with the rod of the oppressor;
having been a prisoner in Lancaster castle above four years,
for her faithful adherence to her principles in refusing to take the oaths of allegiance.

It was at the same court sessions in which so many
errors were found in the indictment of George Fox,
and where she herself passed an examination of which a
sketch was offered to the reader's notice,
that sentence of premunire was passed upon Margaret Fell,
for keeping religious meetings at her house at Swarthmore;
by which sentence it was directed, "`that she should be put out of the king's protection,
and forfeit all her estates real and personal to the king, and be imprisoned for life.`"

"`But the great God of heaven and earth,`" she says,
"`supported my spirit under this severe sentence, that I was not terrified,
but gave this answer to Judge Turner, who gave the sentence:
"`Although I am out of the king's protection,
yet I am not out of the protection of the Almighty God.`"

"`So there I remained,`" she continues, "`in prison twenty months,
before I could get so much favour of the sheriff, as to go to my own house;^
footnote:[It would seem by this and other instances,
that the execution of the severe sentence of premunire, was somewhat mitigated,
or Margaret would have had no house to go to.
In the case of Francis Howgill also, who was premunired, and died in prison,
it appears that he had liberty to make a will, and dispose of his estate.]
which then I did for a little time, and returned to prison again;
and when I had been a prisoner about four years,
I was set at liberty by an order from the king and council, in 1668.`"

After her marriage with George Fox,
she was again made prisoner and sent to Lancaster castle,
where she continued a twelvemonth; and probably would have remained there longer,
but that her husband being in London, used every effort to procure her release,
and at length succeeded by obtaining an order under the great seal for her liberation.

Not that it fared much better with her, when out of prison, on the score of persecution;
for "`the justices,`" she says, "`were very severe, and much bent against me,
because I kept a meeting at my house at Swarthmore-hall:
so they did not fine the house as his, (that is George Fox's;) but fined it as mine,
as being the widow of Judge Fell.
This fine was £20; to which they added £20 more, for her speaking in the meeting;
which not sufficing, they raised it to £40. "`They also fined other friends,`" she says,
"`£20 for the first time speaking, and £40 for the second;
and those that were not able to pay, they fined others for them;
and made great spoil amongst friends, by distraining and selling their goods,
sometimes for less than half the value.
They took thirty head of cattle from me.

"`So I was moved of the Lord,`" she says, "`to go to London,
in the seventieth year of my age; and the word was in me,
that as I had gone to King Charles, when he first came into England,
so I should go and bear to him my last testimony, and let him know how they did abuse us,
to enrich themselves.
And so I went up to London,
and a paper was drawn up to give a true and certain
account how they dealt with me and other friends.`"

But when she found access to the king,
"`he was so rough and angry that he would not take my paper.`"

In a week or two after this,
she and George Whitehead went together to one of the lords in waiting
who had promised to intercede with the king on friends' behalf;
but on presenting themselves at his apartments at Whitehall "`early in the morning,
thinking to speak with him,`" she says, "`before he went out,
his servants told us he was not within, being gone to the king, who was not well.
Then we came forth into Whitehall court again; but all the gates were shut,
that we could not get forth.
So we waited, and walked up and down; and several came down from the king, and said,
he could not stand; others said, he could not speak.
Then, after some hours waiting, we got through Scotland yard, and came away;
and the king continued sick and ill, until the sixth day after, and then he died.
So this,`" she says, "`confirmed that word,
that I was sent to bear my last testimony to the king.`"

How much Margaret Fox was beloved by her immediate connections,
we may gather from the following few lines,
which I extract from the memorial signed by her daughters and their husbands,
after her decease.

"`And as for us, who are her sons-in-law,
we cannot but give our testimony of our sense of her worthiness, etc.;
and we account ourselves happy,
and it is a singular mercy to us that the Lord gave us
wives of the daughters of such a worthy person,
and that we are partakers of their virtuous education,
whereby they are made a blessing to us,`" etc.

Having faithfully fulfilled her allotted labours,
she died peacefully in her house at Swarthmore, the 28rd of April, 1702,
being near the eighty-eighth year of her age,
having survived George Fox about twelve years.

Some remarkable expressions of assured happiness
fell from her lips during her last illness,
if that could be called illness, which in all probability was the mere decay of nature.

"`Cleave to me,`" she said to one of her daughters,^
footnote:[She had seven daughters and one son by her first marriage.]
who was expressing her sense of what a blessed mother she had been to her children,
and their posterity; "`cleave to me, and you will not do wrong,
for I am joined to the Lord.

"`Come, come,`" she said, "`let us join to the Lord,
and be of one spirit--join to the eternal God, and be of one spirit.`"

At one time, under the meltings of heavenly love, "`Oh, my sweet Lord!`" she said,
"`into your holy bosom do I commit myself freely;
not desiring to live in this troublesome,
painful world-- it is all nothing to me,--for my Maker is my husband.`"

A little before her departure, she called her daughter Rachel to her, saying,
"`Take me in your arms`"--after which, she said, "`I am in peace!`"
