== Preface

"`Make the tree good, and the fruit will be good also,`" says our blessed Lord.
It is not, therefore, by lopping the _branches_ of corruption,
that the instructor of youth can hope to be of much service to his charge;
any more than the physician, who merely attacked symptoms,
instead of going to the root of the disease,
could expect to see his patients restored to health.
That there "`__is__ balm in Gilead`"--that there
"`is a physician there,`" for the sin-sick soul,
the Scriptures of truth sufficiently testify;
and on not far distant from every one of us.
"`This commandment which I command you this day,`" says Moses,
in the authority of God "`is not hidden from you, neither is it far off,
(Duet. 30:11-14) But the word is _very near you;_
in your mouth, and in your heart, that you may do it.`"

To a distinct consciousness, therefore, of this word _in the heart,_
the attention of the child can scarcely too soon, and too earnestly be directed;
and with a humble hope that for this purpose,
some aid may be derived from a mode of instruction found useful by the Author,
this little work is published;
and which is to be considered merely in the light
of _hints_ for the educator to follow out,
and enlarge upon, as opportunity occurs;
that being the most effectual teaching which springs from the occasion,
and which approaches the heart while the feelings are fresh and livingly excited.

If it should be objected, that the view here taken,
is confined to the education of female youth, it may be answered, that the _general idea,_
(which is all that the author aims to exhibit) is equally applicable to both sexes.
