== Dialogue III.

[quote.section-epigraph, , Ps. 51:10]
____
_Create in me a clean heart, O God, and renew a right spirit within me._
____

[.discourse-part]
_Mary:_ Will you tell me today, mamma,
why it is wrong for me to play at ordering the dinner, and fancying myself you?

[.discourse-part]
_Mamma:_ Yes, dear child; but in the first place,
I would ask you a few questions on the subject.
How is it, that every now and then, while you are playing at this sort of make-believe,
you turn round to see if I am watching you; and if you think that I am,
you look silly and ashamed?
How is this?
You do not colour up, and attempt; to laugh, and look confused, when you catch my eye,
while you are playing with your Chinese puzzle, or putting your maps together.

[.discourse-part]
_Mary:_ Because I do not mind your looking at me then, mamma.

[.discourse-part]
_Mamma:_ But you do mind my watching you at the other.

[.discourse-part]
_Mary:_ Yes, I do not like it.

[.discourse-part]
_Mamma:_ Why do not you like it?

[.discourse-part]
_Mary:_ Because I am afraid you should laugh at me.

[.discourse-part]
_Mamma:_ Why should I laugh at you, dear?`"

[.discourse-part]
_Mary:_ You would think it so silly.

[.discourse-part]
_Mamma:_ But do I think it silly when you are playing at ball,
or at battledore and shuttlecock, or running with your hoop round the garden,
or skipping the rope, or when you are engaged in many other diversions that I could name?

[.discourse-part]
_Mary:_ Oh, no, mamma, those are not silly plays.

[.discourse-part]
_Mamma:_ But it is silly, you think, to fancy yourself me, or any body else but yourself?

[.discourse-part]
_Mary:_ I do not know that I ever thought about that.

[.discourse-part]
_Mamma:_ But you are sure you do not like that I should see you,
when you are fancying yourself me?

[.discourse-part]
_Mary:_ Oh, yes, mamma!
I am quite sure I do not like that.

[.discourse-part]
_Mamma:_ Well, my dear, I think you may take it as a sign that there is something wrong,
in such a play, that you dislike to be caught at it.

[.discourse-part]
_Mary:_ What is it, mamma, that makes me dislike to be caught at it?

[.discourse-part]
_Mamma:_ It is the good feeling that I want you to observe, and attend to.
It is, in short, the true light that shows to you somewhat of foolishness in such a play;
and foolishness, even in a child, is a thing that must be kept under,
as much as possible.
You do not like to be foolish, do you?

[.discourse-part]
_Mary:_ Oh no, mamma: it is because people think children foolish,
that I want to be like a woman.

[.discourse-part]
_Mamma:_ I do not think children foolish because they are children,
but because they have a foolish nature.

[.discourse-part]
_Mary:_ Had you a foolish nature, mamma, when you were a little girl?

[.discourse-part]
_Mamma:_ Yes, my dear; and I have got the same nature now; only the good Spirit,
the true light, shows me when that nature troubles me,
and then I turn away from it as quick as I can.

[.discourse-part]
_Mary:_ But, mamma, you never play at make-believe, and fancying yourself somebody.

[.discourse-part]
_Mamma:_ The foolish nature does not act in that way with me now,
because I am too old to play as you do;
but it would fill my head with many vain and idle notions about myself,
if I would let it.

[.discourse-part]
_Mary:_ Has every body got that foolish nature, mamma?

[.discourse-part]
_Mamma:_ Yes; and it is that which makes them act so foolishly.
Little girls that have no watchful mother or teachers, to warn them of the danger of it,
as I am now doing to you, are without any sense of their real state.
They play at fancying themselves somebody of consequence,
till they really think they are so; and so they grow up to be vain, conceited girls,
wondering that every body does not admire them as much as they admire themselves.

[.discourse-part]
_Mary:_ I think, mamma, I will never play at making-believe any more.
It certainly is a very foolish thing.

[.discourse-part]
_Mamma:_ It is not the playing at it, dear child, that you have first to give up,
but that which causes you to play in this manner.

[.discourse-part]
_Mary:_ What is that, mamma?

[.discourse-part]
_Mamma:_ The vain mind, my dear, the foolish nature, the evil part, the dark,
ugly weeds which we have said so much about;
these are what are to be taken out of your heart.
Now, the true light always shows you when and where they spring up,
and makes you feel ashamed of them.
Attend greatly to feelings of shame, for they generally come from the good Spirit.
Do you know what I mean, when I tell you to attend to feelings of shame?

[.discourse-part]
_Mary:_ I think I do, mamma.
You would have me give up any thing I was about to do,
if I felt that I should be ashamed any body should see me doing it.

[.discourse-part]
_Mama:_ Yes, that was my meaning; as for instance, if I were to come into the room,
and find you opening my drawers, or looking into my papers,
or taking any cakes or sweetmeats off the table, should you not feel ashamed?

[.discourse-part]
_Mary:_ Oh, yes, mamma, very much ashamed.

[.discourse-part]
_Mamma:_ Why would you be ashamed?

[.discourse-part]
_Mary:_ Because you would think me so sly.

[.discourse-part]
_Mamma:_ You would not like to be thought sly, I suppose?

[.discourse-part]
_Mary:_ Oh, no, I could not bear it.

[.discourse-part]
_Mamma:_ Why should you dislike so much to be thought sly?

[.discourse-part]
_Mary:_ Because it is such a mean thing.

[.discourse-part]
_Mamma:_ But suppose you were quite sure I was out of the house,
and there was no danger of your being seen by any one;
and you then felt a wish to look into my drawers, or read my papers, or take a cake,
or any thing of that sort; would you think it a mean thing to do?

[.discourse-part]
_Mary:_ I do not think I should be so much ashamed, mamma,
if I was quite sure I should not be seen.

[.discourse-part]
_Mamma:_ There is no shame, then, in prying into other people`'s concerns,
or taking what does not belong to you, if you are not seen doing it.
Is that what you mean to say?

[.discourse-part]
_Mary:_ Oh, no, mamma! those are very wrong things to do,
whether any one sees me do them or not.

[.discourse-part]
_Mamma:_ Then should you not be as much ashamed to do them when you are alone,
as you would be if any body saw you?
Mary.
Yes, I think I ought to be.

[.discourse-part]
_Mamma:_ Do you think you ever are alone?

[.discourse-part]
_Mary:_ Oh, yes, mamma, I know I am, very often.

[.discourse-part]
_Mamma:_ I do not mean alone, as to having nobody with you that your eyes can see;
but I mean, is there ever a moment of your life in which some one, and that a Great One,
is not beholding you?
If you think there is, you are greatly mistaken.
Turn to the hundred and thirty-ninth Psalm, and read me the first four verses.

[.discourse-part]
_Mary:_ "`O Lord, You have searched me and known me.
You know my sitting down and my rising up; you understand my thought afar off.
You comprehend my path and my lying down, And are acquainted with all my ways.
For there is not a word on my tongue, But behold, O Lord, You know it altogether.`"

[.discourse-part]
_Mamma:_ Thus you see, my child, that you never are alone:
and if you would be ashamed that I, or any of your fellow creatures,
should find you doing any sly, mean, or foolish thing,
how much more cause have you to shrink from being
found guilty of meanness and folly and deceit,
in the sight of a pure and holy God!
It is His divine and good Spirit in your heart,
that makes you sensible of what is base and unworthy; always, therefore, attend to it,
with reverence and humility; and when you are tempted to do any thing wrong,
do not ask yourself whether you should be ashamed if I should find you doing it;
but ask yourself, am I ashamed that God should see me do this?
and as the cause of all evil is in the heart,
and the vain and sinful thoughts that rise up there,
let this short and good prayer be often in your mind; "`Create in me a clean heart,
O God! and renew a right spirit within me.`"
