== Dialogue IV.

[quote.section-epigraph, , Prov. 20:11]
____
_Even a child is known by his doings,
whether his work be pure, and whether it be right._
____

[.discourse-part]
_Mamma:_ When you were reading to me this morning, Mary,
you remember I told you to leave off; and when you asked me why I wished you to do so,
before your lesson was finished, I said I would tell you the reason another time.
Do you wish to hear it?

[.discourse-part]
_Mary:_ If you please, mamma.

[.discourse-part]
_Mamma:_ No, it is as you please.
If you think it would be painful to you to hear the reason,
I will not compel you to hear it.

[.discourse-part]
_Mary:_ I think, mamma, it was because you were a little displeased with me,
that you told me to leave off.

[.discourse-part]
_Mamma:_ Are you conscious, then, that you were doing any thing to displease me,
while you were reading your lesson?
Come, I see there is a little consciousness of something wrong.
You are aware, are you not,
that you were pretending not to know the meaning of this and the other word,
as I asked it of you; and that I saw through this pretence?
Is not this the case?

[.discourse-part]
_Mary:_ Well, mamma,
I think I did know the meaning of one or two of the words I pretended not to know;
but I wanted you to have a nice long talk with me,
and I could not get you to do what I wished.

[.discourse-part]
_Mamma:_ And so you took this crooked way of bringing it about!
Well, my dear, another time, when you wish for any thing, ask in a plain, open manner,
whether it can be granted you, and do not let the dark,
subtle spirit put you upon such sort of contrivances to accomplish it.
But I think, Mary, if you will try to recollect,
you and I have more than once had some talk upon this subject.
It is not the first time, by many,
that I have had occasion to warn you of this disposition to pretend something or another,
that is not true.
For instance, sometimes you pretend

[.discourse-part]
_Mary:_ Oh, dear mamma! pray do not use that ugly word "`pretend.`"

[.discourse-part]
_Mamma:_ Is not the _thing_ a great deal uglier than the _word?_

[.discourse-part]
_Mary:_ Oh, yes! but then I do not see its ugliness till you tell me of it.

[.discourse-part]
_Mamma:_ But you would see it, my dear child,
if you were attentive to the true light within you,
which is that good feeling which makes the very idea of pretence hateful to you.

[.discourse-part]
_Mary:_ How do you know I am pretending, mamma, when I do not know it myself?

[.discourse-part]
_Mamma:_ You know it when I point it out to you.

[.discourse-part]
_Mary:_ Yes, but what makes you able to point it out to me?

[.discourse-part]
_Mamma:_ A deep acquaintance with my own heart, which is naturally as evil as yours;
and a reverent attention to the good Spirit,
who makes me able to distinguish between truth and falsehood.

[.discourse-part]
_Mary:_ Oh, mamma! what an awful thing that good Spirit is!
I feel afraid when I think how near it is to me!

[.discourse-part]
_Mamma:_ Do you wish it was at a greater distance from you?

[.discourse-part]
_Mary:_ I think sometimes I do wish it, a little.

[.discourse-part]
_Mamma:_ You would like better that it should not disturb you in your pretences,
and make-believe;
you do not wish to see the evil that is in your heart.--Is that the case?

[.discourse-part]
_Mary:_ I do not know, mamma.
I like to see it, and yet I do not like it.

[.discourse-part]
_Mamma:_ The fact is this, my dear; you have two natures in you,
the one good and the other evil;
and "`these are contrary the one to the other;`" but the
evil nature being as yet so much the strongest of the two,
it gets above the other, and is every now and then perking up its ugly face,
and performing all these ridiculous antics;
and it would be well if they were nothing more than ridiculous;
but they are as sinful as they are silly,
and that makes me so anxious to point out to you the necessity of watching against them.

[.discourse-part]
_Mary:_ Thank you, dear mamma.
I like to hear you point out these things to me;
for sometimes I am not aware of them till you show them to me.

[.discourse-part]
_Mamma:_ No, my dear, I dare say you are not.

[.discourse-part]
_Mary:_ Yet, mamma, I wonder I am not, since that good light you speak of is in me,
to show the evil.

[.discourse-part]
_Mamma:_ But if you are not well acquainted with that good light, and its way of teaching,
and above all things, if you are not very _obedient,_ when it shows you what is wrong,
you will never understand your own nature,
and will be apt to fancy that all is well with you, when indeed it is very ill.
It is because poor sinners are so ignorant of the power
and use of the true light that shines in their dark hearts,
that they often get to such a pitch of insensibility,
as not to know that they have such a thing at all.
As that holy man, Job, said of such persons,
"`they are of those that rebel against the light; they know not the ways thereof,
nor abide in the paths thereof.`"
(ch. 24:13.)

[.discourse-part]
_Mary:_ While you are talking to me about this true light, mamma,
I feel such a love for it,
that I seem as if I should never again do any thing which it shows me to be wrong.
But then in a little while I forget it, and fall into something that I am sorry for.
How does this happen?

[.discourse-part]
_Mamma:_ Partly from the heedlessness of your early age,
which prevents you from watching over your thoughts and wishes,
and partly from the hatred of the bad part of your nature against the good;
a hatred which keeps you from praying earnestly to God to increase His true light in you,
by giving you more and more of his Holy Spirit.

[.discourse-part]
_Mary:_ Oh, mamma, I do wish to have this true light increase.
I do wish to be good.
I am always so sorry and so ashamed when I see these ugly weeds in my heart.
What can make them come up, when I dislike them so much?

[.discourse-part]
_Mamma:_ The love of self, my dear--the desire to bring self into notice.
For instance, I was rather grave today, and not inclined for conversation;
and you had made several attempts to engage my attention, and you could not draw me out;
so, in order to make me observe you,
you fell upon the device of pretending not to know
the meaning of this and the other word;
and now and then not being able to find the place where you left off, and so on,
only for the sake of bringing self into notice; till seeing what you were about,
and who it was that was governing you, I desired you to leave off,
and I would tell you the reason for it another time.

[.discourse-part]
_Mary:_ Well, mamma, I thought what the reason was, before you told me.
But what is it you mean, when you say who it was that was governing me?

[.discourse-part]
_Mamma:_ I mean the evil spirit, who is the enemy of all good,
and whom you read of in scripture, as that wicked one who goes about as a roaring lion,
seeking whom he may devour.
He that is called Satan, or the devil, he was leading you into foolishness and sin.

[.discourse-part]
_Mary:_ Is he so near me too, mamma?

[.discourse-part]
_Mamma:_ He is very near,
and always watching to puff you up with vain thoughts about yourself,
and making you anxious for notice, and unhappy when you are not noticed.

[.discourse-part]
_Mary:_ But, mamma, why is it so dangerous to love ourselves,
for there is nobody so near to us to love?

[.discourse-part]
_Mamma:_ It is dangerous for many more reasons than I can give you now,
as we have talked long enough for the present.
But on one account, if there were no other, it is dangerous to love ourselves too much,
and that is because it is contrary to the will of God,
and the example of our blessed Saviour, who says, "`if any man will be my disciple,
let him deny himself, and take up his cross daily, and follow me.`"
Now, we shall never deny ourselves so long as we are filled with self-love.

[.discourse-part]
_Mary:_ I do not think I exactly know what is meant by denying ourselves, mamma.

[.discourse-part]
_Mamma:_ Well, tomorrow, perhaps, we may talk a little more on that subject.
