== Chapter I. First Impressions.

Few observers of human nature can have failed to remark,
that a disposition to be violent is one of the first indications
which children betray of their fallen condition;
and it is one which should be far more seriously regarded and vigorously opposed,
than is commonly the case.
I confess, I seldom see an angry, screaming child,
and persons amusing themselves by smiling at its
futile but furious efforts to obtain its object,
without being disposed to shudder at the mistaken
view of the case which such pleasantry evinces.
Alas! how numerous are the instances, where, in after life,
those smiles have been exchanged for tears,
when the unchecked tempers of infancy and childhood,
having acquired a strength that no human curb can restrain,
remind the too indulgent parent that education and control were begun too late!
To "`begin at the beginning`" is good counsel with respect to every undertaking,
and especially in the education of children, whose discipline, to be effectual,
should commence with the earliest dawning of intelligence,
and the first manifestation of self-will;
for a child that is capable of knowing that it wants a thing,
is also capable of being made to know that it cannot have what it wants.
And in order that you, dear children, who read this book,
may see the advantage of being rightly controlled and advised by your parents and instructors,
I shall relate to you the history of three little girls;
one of whom went through some severe trials for one so young; but who,
through the grace of God, which is promised to those who ask for it,
was enabled to get a great blessing out of all of them,
and for the sweetness of her temper, and the kindness of her behaviour,
was often spoken of as "`Gentle Gertrude.`"

She was the only child of Mr. and Mrs.
Belton, and had her first sorrow to experience in the loss of both these dear parents,
who died within a few months of each other.
Her father had been a missionary stationed at Calcutta, in the East Indies,
and there little Gertrude was born,
and there she remained till the death of her parents
rendered it necessary for her to be sent to England,
both for protection and education.
She was taken care of during the voyage by a kind lady; who,
having delivered her safely into the hands of a clergyman
who had been a particular friend of her father,
then took leave of her.

Behold now, the little orphan girl, only eight years old, and naturally shy and timid,
cast entirely among strangers, and some of them strangers of a very rough kind.

But I shall let them describe themselves to you, after having just said, that Mr. and Mrs.
Allen, the lady and gentleman with whom she was now to live,
were very kindly disposed towards her,
and that it was not their fault if she was not as kindly
considered by their children as she was by them.
They were very desirous that she should be made happy under their roof;
but sometimes poor Mr. and Mrs.
Allen were not happy themselves; and that, from the same cause,
which often vexed and harassed poor Gertrude.

The fact was, that Mrs.
Allen had been too indulgent to her children,
and had sometimes forgotten that wise maxim of Holy Writ,
to "`train up a child in the way he should go;`" and also,
that other blessed remark in the Scriptures of truth,
that "`it is good for a man that he should bear the yoke in his youth.`"

However, as I have just said, I shall leave things and people to describe themselves,
by showing you different scenes and circumstances
as they occurred in Gertrude`'s little history;
only telling you, that, besides Mr. and Mrs.
Allen, the family consisted of two little girls, the eldest eleven,
and the other nine years old, and a baby boy aged about eight months.

The first morning after her arrival, she was awakened by the ringing of a bell,
and presently after, a kind-looking elderly woman,
whom she had seen the evening before in the nursery, and whom she, therefore,
rightly judged to be the nurse, came and told her that it was time to get up.
"`I will stay and dress you, my dear, if you please,`" said Sarah,
for that was the servant`'s name.
"`Thank you,`" replied Gertrude in rather a sleepy tone of voice,
for she was hardly yet roused from her sound slumbers,
and which had been the sounder from her having laid awake when she first went to bed,
thinking of her new home and new friends,
and wondering whether she should be happy with them.
At last, after having rubbed her eyes, and looked about her,
and stretched out her arms a little, she quietly began to dress herself,
though not without a sigh, which she did not, however, intend that Sarah should hear,
for she did not want to talk about what she was feeling, for if she did,
she thought she should cry; and Gertrude was very shy of being seen in tears.
Some little girls are as shy about that as she was;
and I do not know that it is a wrong feeling,
when they are not stubborn and proud with this unwillingness to be seen weeping.
Examine yourselves, therefore, dear children, when your minds are vexed about anything,
and you scarcely know how to refrain from tears: examine yourselves,
and if you find that you are wishing to pass off
your vexation with anything of noisy laughter,
that you may not seem to care for it, then, be sure,
that it is pride and stubbornness of heart that is governing you;
and that is a very dreadful thing to give way to; for we are told in the Bible,
that "`God abhors the proud;`" and nothing can be more to be dreaded,
than to make ourselves the objects of God`'s abhorrence.

But there was neither stubbornness nor pride indulged in Gertrude`'s present feelings;
but her natural extreme timidity and unwillingness to say much to a stranger,
caused her to be nearly silent while Sarah was dressing her.
This was so different from the usual behaviour of those
who were under her care for dressing and undressing,
that nurse at last could not help noticing it.

"`I am sure I wish Miss Harriet and Charlotte stood as still and quiet as you do,
my dear,`" said she,
"`and then I should not have so much trouble to make them fit to be seen, as I have,
every morning of my life.
But, it`'s no use my speaking;
they mind it no more than they do the boards they stand upon.
And then, there`'s such twitching and pulling, and this string`'s too tight;
and t`'other`'s too loose;--and a shoe or a stocking is
missing;--and such banging and tearing the things about,
to look for it!
Oh, what work it is!
If I had not brought them up from babies,
and so cannot but love them almost as much as if they were my own,
I`'m sure I never could bear it.`"

Here nurse paused;
perhaps to give Gertrude an opportunity for any little remark she might wish to make.
But she had nothing to say; and, after a short silence, Sarah changed her discourse,
and from having been a describer, she now took the form of an inquirer.

"`And so, my dear, you are come from a long way off to live with us?
Do you recollect your papa and mamma, dear,
or were you too young to know much about them?

Poor Gertrude`'s lips quivered, and her voice was hardly audible, as she replied,
"`I recollect them very well.`"

The kind-hearted Sarah saw the sorrowful workings of the little girl`'s mind,
and immediately attempted to soothe her by words of tenderness and encouragement.

"`Oh, you will be very happy, here, my dear, never fear!`" said she,
"`you must learn a little of our children`'s liveliness,
and they must learn a little of your meekness, and we shall do very well, I don`'t doubt.
Only you must not let them get the upper hand of you; for they are so masterful, that,
if you do, you`'ll never have a moment`'s peace.
They`'ll want every play-thing you have; ay, and snatch it away from you,
if you`'ll let them.
There`'s Miss Harriet, oh! what a little tyrant she is, when she wants a thing,
and cannot get it.
So be sure and take good care of your toys, dear.
Have you got many?`"

"`I have got a doll, and a little cradle;`" said Gertrude earnestly,
and half trembling at the ideas of spoil and plunder
which nurse`'s description awakened in her mind.
"`I shouldn`'t like to lose them.
I don`'t think I should care about my balls, if they chose to take them away.
But do you think they will?`"

"`Oh no, my dear; not if you take proper care not to let them domineer over you;
and depend upon it, I shall do my best to prevent their doing so.
But now, having finished dressing you, I must go and get them up;
which won`'t be quite so easy a matter, I doubt.`"

As soon as nurse was gone, Gertrude,
according to the good and proper habit which her dear mamma had trained her to,
knelt down by the side of her bed, and prayed to her Heavenly Father; and,
remembering how her beloved parent had often said to her that she should not so confine
herself to the words she had been taught to offer up at the throne of Grace,
as never to venture to use any other,--but that,
whenever she felt a wish to ask anything of her Father which was in heaven,
that was not particularly mentioned in her usual petition,
she should always yield to this wish, and express it in her own way,
she gave vent to some of the feelings of her heart,
and earnestly besought the Lord to take care of her and make her happy in her new situation,
for she was very unhappy now.

Her tears finished what her words could not:
and she was yet kneeling with her head upon her clasped hands,
when the door opened and Mrs.
Allen entered the room.

Gertrude instantly rose, and, in some confusion, was about to wipe away her tears;
but Mrs.
Allen perceiving them on her cheeks, tenderly drew her towards her,
and after having kissed her,
and expressed satisfaction in finding her so properly engaged in her morning duties,
"`What is it, my love,`" said she, "`that vexes your little heart?
Don`'t you think you shall be happy in your new home?
Oh, I hope you will.`"

The voice of kindness at such a moment was quite overpowering,
and Gertrude burst into fresh tears.

Mrs.
Allen waited till she was somewhat composed,
and then repeated her hope that the little girl would be happy with them.
Still Gertrude kept silence; and the lady,
as if half fearing that this behaviour was the effect of rather a sullen disposition,
then addressed her in a graver tone.

"`I am afraid, my dear,`" she said,
"`that you are disposed to give way to something of a dissatisfied temper.
Have we not shown you by all the kindness in our power,
in the little time we have been together,
that we desire to do all we can to make you comfortable?`"

She waited for an answer, and Gertrude in a low voice replied, "`Yes, ma`'am.`"

"`And what makes you think you shall not be happy, then, my love;
for it is clear to me that you are thinking so?`"

"`I am afraid Harriet and Charlotte will not like me, ma`'am.`"

"`Oh, is that all! never fear, then,`" said Mrs.
Allen.
They are rather high-spirited little girls, to be sure; but they have very kind hearts;
and I am sure they will love you, and so shall I, and so will Mr. Allen.
So, dry your tears, and now come with me to the breakfast parlour,
where we meet at this hour for family worship.

She then took Gertrude by the hand,
and led her downstairs into a room where Mr. Allen
was sitting at a table with the Bible before him,
waiting the arrival of the rest of the household.
He greeted the little Gertrude very kindly,
and desired her to take the seat to which he pointed,
and then rung the bell for the other members of the family.

A noisy scuffling of feet was now heard,
and presently Harriet and Charlotte came bustling into the room,
followed by the servants of the family.

Mr. Allen addressed the children with a few words of reproof for being so late,
which they seemed neither to hear nor to care for;
their whole attention being apparently fixed upon their young visitor Gertrude,
whose new morning frock caught their eye,
and occupied their fancy long after their papa had commenced reading.
At length Mrs.
Allen having shown them by a glance of her eye, and a shake of her head,
that she observed their improper behaviour, they became more sedate,
and at all events appeared to pay attention to what was going on.

The portion of Scripture which was read, was the last chapter of St. John`'s gospel;
and what was said upon it was very easy to be understood,
and Gertrude felt comforted by it.
The sweet spirit of love that breathes through the language
and conduct of the dear Redeemer towards poor penitent Peter,
was much dwelt upon by Mr. Allen;
and he seemed very anxious to enforce the lesson it was
fitted to impart to the minds of those around him.

"`How tender,`" said he, "`is our compassionate Saviour towards all his flock!
How truly the good Shepherd, not only caring for the sheep and lambs himself,
but giving them in charge to others, whom he binds over to be kind to them also!

"`For you are not to think that this charge which I am reading to you,
is only given to Peter.
It is given to all persons who have the power and opportunity of
instructing and influencing the minds of their fellow creatures.
More especially is it given to parents, and rulers of families.
It is given to me, at this moment.
Yes, at this moment, I seem to hear my Master`'s voice saying unto me, '`Feed my sheep,
feed my lambs!`' And how must I feed you?
Is it of the outward food that is now upon the table before us,
that the Lord commands me to give you?
No, my people, and children,
I am sure there are none present so ignorant as to suppose that
that is the nourishment I am here commanded to provide you with.
It is the living bread that comes down from God, that I am charged to set before you.
The bread that is spoken of in this blessed book; even He that says of himself,
'`I am the living bread.`'

"`He it is, that I set before you in all his lovely nature!
Jesus Christ, the Saviour of sinners, dying that they might live.
The Son of God, becoming man, to teach them what, as human beings, they are to suffer,
and to do, and to be.
The Lamb of God, calling to the harsh and the violent, those who,
being first injurious to themselves in not governing their tempers,
and denying their headstrong will, are soon led into injuring their fellow creatures;
calling to these, I say, to come unto him, because he is meek and lowly in heart,
and with him they shall find rest unto their souls.
He it is that I am to preach unto you.

He it is that you are to come unto.

"`But now, dear children,
perhaps you will be at some loss to know what this '`coming unto Jesus`' means.
Well, I will try to tell you as well as I can.
Suppose, (and the good man sighed, as he made a little pause,
and spoke with much solemnity,) suppose, that some of us,-- you children, for instance,
are troubled with very hasty, violent tempers; you want a thing, and you cannot have it;
or you think yourselves ill treated, and you are very angry,
and desire to revenge yourselves; or something or another, no matter what,
puts you into a passion; and in this state, you do or say something rash.
Perhaps, you call one another names; or you make some spiteful remarks, or you may,
(for alas!
I have known such things) even go the length of fighting and pinching one another;
and then, when the fit of passion is over, and you become cool, you are ashamed,
as you have good cause to be, of such disgraceful conduct,
and wish you had not given way to it,
and promise yourselves that you will never do the like again.

"`But you may as well promise yourselves that you will never eat or drink again;
for if it is your nature to be rough, and violent, and passionate;
it will be just as natural for you to say bitter things,
and fight and pinch the next time you meet with anything you don`'t like,
as it will be natural for you to eat and drink the next time you are hungry.
Your only refuge and way of help is in obeying the call of the blessed Lamb of God,
and going to him for assistance.
And it is thus you must go to him.
Whenever the sin and disgrace of yielding to a violent temper is really felt,
and you are ashamed of it, be still a little while,
and endeavour to cherish and love those good feelings of repentance.
Never, never, try to throw them off, as something that pains you,
and is therefore disagreeable; but keep them as long as you can, for they come from God,
and are his reproofs of instruction, which lead into the way of life.
Then look at that portion of Scripture in which Jesus
invites sinners to come and learn of him.
Here it is.
I will read it to you.`"

Mr. Allen then turned to the 11th chapter of St. Matthew,
and read from the 25th verse to the end.

"`When you have done this,`" he continued, try and think upon that expression,
'`Learn of me,
for I am meek and lowly in heart.`' Try and think what a sweet spirit
it describes! and what a lovely thing a meek and lowly heart is!
All really beautiful things are gentle, and humble, and happy, and contented.
They are at peace themselves, and they inspire peace in others.
When we saw your little brother, as we did yesterday, lying in his cradle,
and looking at his little hand and smiling, and, after his manner, talking,
and playing with it, I would ask you to consider what it was,
that made mamma take him up, and press him to her heart,
as if she loved him better than she ever did before?
And when you have considered, you will see that it was the true beauty of the innocent,
meek, contented state of heart, which the action of the babe exhibited.
The most violent temper would, for a moment,
have been calmed in contemplating the little child so simple and serenely happy.
How much more, then, is violence to be controlled,
by coming to the contemplation of the meek and lowly
character of Him who was called the holy child Jesus.
Therefore, to come to Jesus, is to think of him, to read descriptions of his character,
till you see its beauty;
and then to beseech of him to create in your hearts
such a love for his sweet childlike temper,
and innocent spirit, that you may hunger and thirst after the possession of them.
And depend upon it, that you will not have to wait long,
before you will feel a growing desire for all that is tender, and meek, and lowly.
There will be a new nature, like a little lovely flower, growing in your hearts:
and when you feel its sweetness, and what careful nursing it needs,
you will earnestly pray to God to preserve it for you,
and save it from the wild beast of your own corrupt and sinful passions.
Like David, you will pray, Rescue my soul from their destructions,
my darling from the lions.`' Oh, when once you have tasted that the Lord is gracious,
and beautiful, and full of love, and meek and lowly in heart,
you will be as much afraid of being violent, or revengeful,
or putting yourselves into a passion,
as mamma would have been yesterday afraid of putting
her innocent smiling baby into a den of dragons.`"

Mr. Allen here closed the Bible, and after a short pause, knelt down to pray.
More than one heart united in his earnest petitions for a large outpouring of the Spirit
of love and meekness to descend upon and clothe their souls with peace and humility;
but none experienced deeper sympathy in his holy exercise than his new inmate,
the little Gertrude.

Almost involuntarily, as soon as the servants had retired,
she softly stole near his chair.
There was something about him that recalled her own dear papa to her mind;
and she hoped in her heart that he would love her,
as she felt very sure that she should love him.
She was standing near him, afraid to intrude, but wishing to catch his attention,
when the elder of the little girls, and presently after the other also,
called to her to come and take a run in the garden while the tea was making.

Their voices, loud and quick, roused Mr. Allen from somewhat of a reverie, and,
turning his head, he perceived the soft brown eyes of Gertrude fixed upon him,
and a little smile playing round her mouth, which seemed to say, "`Good sir,
I want you to say a few kind words to me.`"

Such, at least,
seemed to be the interpretation he put upon the expression of her countenance; for,
taking her hand, and drawing her nearer to him, he kissed her with paternal affection.
"`Well, my little Gertrude,`" he said, "`and how do you think you shall like living here?
I hope you will be quite happy,
and be assured that we shall be glad to have you with us?`"

"`I am sure I shall`"--she then paused,
as if afraid she was going to make too bold a confession.

"`You shall what, my love?`"
said Mr. Allen.
"`I shall love you, sir--you make me think of dear papa.`"

Mr. Allen smiled, and was about to say something; but the two little girls, who,
during this scene, had been standing at the door, being quite tired of waiting for her,
came up, and taking her by the hands, one on one side, the other on the other,
ran off with her into the garden.

"`Come, I want you to tell me what plays you like best,`" said Harriet,
the elder of the two.
"`I`'m not going to let you stand mumchance in that mopish way.
We`'ll show you some fun, and put a little life into you.
Can you climb a tree, or leap over a hedge?`"

"`Oh no, that I cannot,`" said Gertrude,
shrinking and shuddering at the prospect that opened before her.
"`I never was up in a tree in my life; and I don`'t know how to leap over anything.`"

"`Well then, I`'ll show you.
Just see me climb up into that old mulberry tree;
you see how low that part is where it branches off; Charlotte and I often sit there.
I`'ll be up there in a minute.`"

"`Oh, pray don`'t,`" said Gertrude,
"`you will fall down and hurt yourself--you will tear your frock,
you will --`" But her words were not listened to.
Some steps that stood at the foot of the tree, were quickly mounted,
and Harriet having ascended, was loudly calling to the others to follow her,
when a summons arrived to go in to breakfast.
After greatly regretting the shortness of her present enjoyment,
Harriet unwillingly came down from the tree,
and with her sister and Gertrude returned to the house,
with her frock trailing after her on the ground,
in consequence of a long slit that had torn it out of the gathers.
As for Gertrude,
she felt almost as a delinquent in having been only a spectator of such doings,
which she expected would call for a sharp reprimand from Mrs.
Allen, as soon as she saw the injured frock.
But, merely observing that they were always to be waited for,
and were constantly tearing their frocks and getting into mischief,
the good lady said nothing more on the subject.
