== Chapter II. The Governess.

For the first three weeks after Gertrude`'s arrival,
there was little going on in the way of discipline or instruction among the young people;
as during the greater part of that time Mr. Allen was absent in London upon business;
and when he was not present,
the only restraint that appeared to be felt by the two little girls was entirely removed.
They did what they liked with their mamma;
and although she was frequently heard in the course of the day, saying, "`Now,
my dear Harriet, don`'t do so,`" or, "`Charlotte,
I really will not allow this,`" it cannot be said that she was minded; indeed,
her indulgence had produced so much disobedience,
that she herself spoke her wishes and desires only
as if it were a right thing to utter them;
not as if expecting they were to be attended to, and obeyed.
Noise and confusion, banging of doors, tossing down stools,
littering chairs and tables with doll`'s clothes, toys, and all sorts of rubbish,
wrangling and quarrelling, and then making it up, and hoydening and laughing,
seemed to be the chief occupation of Harriet and Charlotte Allen;
an occupation which they occasionally varied by playing tricks with Gertrude,
hiding her doll, or sometimes hanging it by a string to the mulberry tree,
filling her highly valued little cradle with stones, broken sticks, dried leaves,
and various other such things, flinging her balls over the hedges,
and many devices of the like nature,
which were all very hard to bear by a mild-spirited little girl like Gertrude.

Her chief resource at these times, was to get by the side of Sarah in the nursery,
where she was always sure of being protected,
and allowed to follow her little quiet ways of amusing herself without interruption.
Here, too, she found an unfailing source of delight,
in the intimate friendship she was daily forming with little Johnny Allen;--a fine healthy,
happy child, who was just beginning to want a great deal of amusement and attention.
Happy was Gertrude in bestowing both, as she sat by his side on the carpet;
and happy was Sarah (who was no longer young) in being spared
that really severe task of having to stoop after,
and follow the fancies of a sprightly child, wanting everything it beholds,
only to have the pleasure of throwing it upon the ground,
and giving others the trouble of picking it up again.
Satisfied in the attention of her young deputy,
and keeping a watchful eye over both parties, nurse sat at her work-table,
while Gertrude and Johnny, amusing and amused,
enjoyed life more innocently than most people during Mr. Allen`'s absence.

At length the time approached for his return;
an event that was anticipated with a variety of feelings
by the different inmates of the family,
for I must inform you, that he was not to return alone,
but was to bring with him a lady named Robson, who, in compliance with his wishes,
had consented to undertake the office of governess to his daughters.
I shall give you a little description of this lady,
that you may form some idea of one of whom you will
be likely to see a great deal to the end of our history.

Miss Robson was a person of good understanding, and considerable accomplishments,
who had been accustomed to the tuition of youth from
the time that she was eighteen years of age;
and as she was now eight and thirty,
you will suppose that during so long a period as twenty years,
in which she had known what it was to deal with the tempers and habits of the young,
she had formed a pretty correct judgment as to the best method of managing them.

In fact, it was owing to the high opinion he entertained of her sense and judgment,
(for she was a distant relation of his,
and he had known her many years) that Mr. Allen had
engaged her services as governess to his little girls.

Many individuals had, at different times, filled that situation,
but none of them had stayed longer than a few months: the violent,
ungoverned tempers of the children, and the injudicious indulgence of their mother,
rendering it so difficult a task to attempt the right education of them, that,
after a short effort,
it was usually abandoned by their instructress for something
that promised her a better recompense for her exertions.

It may seem strange that so good a man as Mr. Allen should
not have been able to regulate his family better;
but the fact was, that in attending to the duties of his parish,
and other avocations connected with his sacred office, his time was so fully occupied,
that he was in a great measure compelled to leave
the management of his children to their mother;
who, besides her fault of too much indulgence in her conduct towards them,
was often an invalid,
and unable from weak health and spirits to control them as they required.
Added to these circumstances,
there was another consideration which had some effect upon both parents,
who were each of them very tender-hearted people, and as you may suppose,
dearly loved their children.
This was their having lost several of them in their infancy;
which made them cling with somewhat of "`inordinate affection`"
to those whom it had pleased Providence to spare them.
Oh, dear children, how little do you know, and therefore how little do you,
generally speaking, consider what your parents experience on your behalf!
The dutiful attentions that you owe them, however regularly paid,
can scarcely equal the anxious cares, and various hopes and fears,
which they have been called to suffer on your account;
especially during the tedious and sometimes sickly
period of your infancy and early childhood,
when you had no sense or power of contemplating or caring for their sorrows,
but which was to them a season of love and tender watchfulness,
that prompted their constant endeavours to assuage
and bear the burden of your smallest discomfort.
Oh, if there be a sight to shock the feelings,
and create sensations so revolting that they border upon horror,
it is to witness parents treated with disrespect or unkindness,
by the child that they have carried in their arms, and pressed to their hearts,
and nourished and cherished, and, as far as human means permitted,
endowed with all the comforts and advantages in life which that child possesses!

But I must not lead you to suppose that so sad a
case was that of Harriet and Charlotte Allen.
What it might have been if they had been allowed to continue
a few years longer in their present indulged condition,
with their high spirits and violent tempers as much uncontrolled as they were now,
we have no power to predict, though great cause to apprehend; happily for them,
a strong check to their dangerous career was now about to be given,
in the steady and wholesome discipline of Miss Robson.

This lady, as I have already told you, had been accustomed to tuition from her youth,
having been educated with a view to obtaining her livelihood in that way.
She was, in the strictest sense of the word, a Christian;
one who feared God and loved righteousness; and as such,
she took little part or pleasure in the vanities and customs of the world.
These it may seem that she had no great merit in denying; since,
from her dependent situation, she was not likely to have many temptations to pursue them.
But, you must remember, that it is not always the _doing, or not doing,_
this or the other particular thing, that marks our character,
and shows what we really are in our hearts.
Some persons, I do not doubt, are often made unwilling sharers in worldly pursuits,
from their being placed in circumstances wherein they have
it not in their power to follow their own better inclinations.
But these are few,
in comparison of the great number who have all the _heart and will_ to partake of,
and follow them,
but who are in situations where they are compelled to forego these desires.
Now, dear children, do you not see, that those persons who would if they could be gay,
and worldly, and fashionable,
and "`lovers of pleasure more than lovers of God,`" really _are_ all this,
in the sight of that Great and Holy Being who sees not as man sees,
for man looks at the outward appearance, but the Lord looks on the heart?
Indeed they are; for such as our will and wishes are, such are we;
whether we can gratify that will and those wishes, or whether we cannot;
and it was because Mr. Allen was sensible of this truth,
that he so earnestly desired to obtain Miss Robson`'s instructions for his children.
He knew very well,
that it would be of little use that the governess should
talk against the uselessness and vanity of a love of dress,
or of the irreligion of the world and its pursuits,
if she herself was to be seen following the fashions as far as she could,
and taking more pains to impress upon the minds of her pupils a dread of being ungenteel,
than of being ungodly.
His great anxiety, therefore,
was to place his little girls under the care of a
person who acted out the principles of the Bible;
not one who merely talked about them.

Such a person he fully believed Miss Robson to be.
He had known her from her youth, and had seen her under very trying circumstances;
and through all her difficulties keeping a steady hold of that faith in God, which,
in the words of an old writer, "`anchored her immortal soul to its bishop;`" glad was he,
therefore, to delay his return home in this visit to London,
that he might have the satisfaction of bringing her with him as an inmate of his family.

Glad, I say, was Mr. Allen; but not altogether so glad his wife.
Mrs. Allen was not a stranger to Miss Robson,
and though she could not but respect her character,
she secretly wished that some person of a less rigid mode of thinking and acting,
had been selected as the instructress of her children.
But, as she was always in the habit of deferring to the wishes and judgment of Mr. Allen,
and had long been aware that he only waited for the
liberation of Miss Robson from a present engagement,
to propose her accepting one in his family,
she kept her thoughts upon the subject entirely to herself;
and prepared to receive the new inmate with the utmost kindness and good will.

To the little girls, Miss Robson was entirely a stranger; and various,
as you may suppose,
were the conjectures that passed between them as to who and what she would be like;
and whether or not they should like her as well as some of their former governesses.

They were standing at the nursery window, together with Gertrude,
when the chaise which had been sent to the neighbouring town to meet the coach,
drove up to the door with their papa in it, and a lady who, of course,
was the expected Miss Robson.
Exclamations of joy at the sight of their father,
and of curiosity respecting the stranger,
suspended their occupation of putting on their afternoon frocks.
Every head was making its way over another head to obtain a look at the new comer.
Even little Johnny in the arms of Sarah, appearing in the rear,
seemed to think that something new and strange was taking place in the world.

Well, I never saw such a figure!`" was the first exclamation of Charlotte.
"`Why, she is dressed as plain as Sarah!`"

"`What an old straw bonnet!`" said Harriet, and, dear me, how old she is!`"

"`I don`'t think I shall mind her much,`" continued Charlotte.

"`She may know how to make you,`" said Sarah, "`though she does wear an old bonnet,
you don`'t know what she has got under it.`"

"`I`'m sure she has got a very ugly face,`" replied
Charlotte in great displeasure at Sarah`'s remark.

"`Handsome is, that handsome does,`" said Sarah,
"`and I dare say we shall see in a little time, that she has got the true handsomeness.`"

Gertrude was silent during this parley, which was now ended by the voice of Mrs.
Allen calling to the children to come down and see their father,
and expressing wonder that they had not finished changing their dress.

This was soon accomplished,
and Harriet and Charlotte hastened down to give papa a kind kiss of welcome.
Gertrude was glad to wait behind a little while; for,
though no one in the house could more delight in the return of Mr. Allen,
she was in no hurry to make the acquaintance of one
whom she expected to find so formidable as Miss Robson.
This expectation had arisen not from any distinct or formal
description that she had received of this lady,
but from the vague hints which Mrs.
Allen occasionally dropped during the last fortnight,
whenever Harriet and Charlotte were more than commonly unruly;
and which hints always pointed to the probability
of their conduct requiring to be altered very shortly.

"`You will see what Miss Robson says to that,`" was her usual remark,
when her remonstrances against this or the other action were disregarded by her daughters;
so that Gertrude had learned to attach something
rather alarming to the very name of the new governess.

It was a great relief to her, therefore,
on going down with Sarah and Johnny to see Mr. Allen,
to find that Miss Robson had left the room to prepare for dinner;
and as the children had already dined,
Gertrude only waited to receive Mr. Allen`'s kind welcome,
and then retired with them to the nursery.

At the tea-table in the afternoon, they first met with Miss Robson,
whom they found sitting with Mrs.
Allen only,
Mr. Allen being engaged in his study with one of
his parishioners who had called upon business;
and, as he was likely to be detained some time,
he desired they would not wait tea for him.

"`Come in,`" said Mrs.
Allen, as Harriet, in her boisterous way, burst open the door,
and was then hastily retiring, nearly overturning her sister and Gertrude,
who were just behind her, and about to follow her into the room.

"`Come in, I say,`" repeated Mrs.
Allen, enforcing her command by rising from her chair and coming to the door,
in order to bring the little girls towards Miss Robson.
Having introduced them to her by name, and Gertrude as "`a little orphan girl from India,
placed under Mr. Allen`'s guardianship,`" she desired
them to take their places at the table.

Gertrude obeyed with her usual quietness,
and the other two with their usual bustle and noise.
As soon as they were seated, a deep silence ensued;
such as was sometimes the case in Mr. Allen`'s presence, who always commanded it,
when rough or foolish behaviour was in any way going forward;
but which seldom occurred in his absence.
Not to do as they liked then, was something so strange to Harriet and Charlotte,
that they knew not what to make of it; and therefore, like all uncontrolled,
selfish children, who care for nobody`'s feelings but their own,
supposing that the restraint they felt was owing to Miss Robson`'s presence,
they began to look first at her, and then at each other,
as if comparing their thoughts about her, then half laughing,--and, in short,
behaving in so unbecoming a way, that Mrs.
Allen was quite ashamed for them.
Finding, at last, that her many nods, and frowns, and shakes of the head were unheeded,
she spoke loudly, and told Harriet that "`if she did not mind what she was about,
she would send her out of the room.`"
This reprimand produced some reformation;
for Harriet knew that "`the sending out of the room`" never came but in extreme cases;
and that it comprised not merely going out of that apartment,
but generally the going into another, which was papa`'s study,
where she was certain of receiving reproof of a more severe and
searching kind than mamma was in the habit of administering.
There was scarcely anything that Harriet and Charlotte really feared, and,
in a certain degree respected, more than their father`'s rebukes;
for though they were violent and rough tempered children, they were not without feeling;
and when Mr. Allen spoke, it was to the heart and to the conscience,
and they always understood what he meant,
and were deeply humbled by the consciousness of deserving it.

During the time that they had been conducting themselves so improperly,
Miss Robson had been forming an acquaintance with little Gertrude,
in whose mild countenance and gentle manners, she saw so much that was engaging,
that she beheld with less concern than she otherwise
might the ill behaviour of her companions.
"`Here, at least,`" she thought to herself,
"`I may hope for a pupil that will afford me some fruit for my labours!
Nor was the good lady discouraged by what she saw in the other two little girls;
she perceived at once, from Harriet`'s manner at her first coming into the room,
and her mother`'s being obliged twice to speak her wishes,
and even to rise from her seat to enforce obedience to them on that occasion,
that these poor children laboured under the severest of all disadvantages,
even that of having been allowed to have their own way,
and not to mind when they were reproved.
It was not the first time by many,
that Miss Robson had been called upon to deal with children so circumstanced;
and when she considered their early years, and the hope held out thereby,
that they were not yet past being brought under proper control,
she felt only stronger desires and more fervent breathings
in her heart to the Father and Giver of all Goodness,
that, aided by His wisdom and power,
she might be instrumental in reclaiming them from their present dangerous condition.
