== Chapter III. The School-Room.

Ever since Gertrude had been resident at Woodside (the village where Mr. Allen lived,
and of which he was the rector,) there had been, as we have said,
but little like study or lesson learning, or lesson giving, going on.
It was a new thing to her, therefore,
to be summoned at nine o`'clock the next morning after Miss Robson`'s arrival,
to take her slate and school books into an apartment
hitherto known to her by the name of the play-room,
but which was now to be dignified with the title of school-room.

Finding it hopeless to wait the rummaging up Harriet`'s and her
sister`'s scattered books etc. and the adjusting of their hair,
and their frocks, and at the same time to obey Mr. Allen, who,
from the bottom of the stairs was calling out, "`Children,
Miss Robson is waiting for you,`" Gertrude went down alone,
with her books and slate in her hand.

She was kindly greeted by Miss Robson,
who inquired into her progress in spelling and grammar.
It was found to be but little, owing rather to various hindrances,
than to her disinclination to apply.

"`Well, we must endeavour to make up for lost time,`" said Miss Robson,
as she appointed her some words of spelling to learn by heart.

About half-past nine, Harriet and Charlotte came in, bustling and noisy,
and shoving each other out of the way to get to their seats.

"`I shall sit there, Charlotte,`" said Harriet, "`I`'m the eldest,
and I`'ve a right to choose my seat.`"

"`Sit here,`" said Miss Robson, calmly, pointing to a stool by her side.
Harriet stood in silence, somewhat awed by the composed demeanour of her governess,
but evidently determined to dispute the matter before she gave up her own will.

"`I always used to sit where Charlotte does, when Miss Singleton was here,`" she replied.

Miss Robson made no answer to this, but again pointed to the stool,
which there seemed no means of escaping; for Charlotte,
triumphing at being able to keep her own seat,
was looking on at this scene in a way which Harriet well enough understood,
and which plainly manifested that her sister wished for no better fun,
than to see her entangled in an argument with the new governess.
If it were for nothing else, therefore, than to disappoint these expectations,
it seemed advisable to end the matter by obeying; which she accordingly did,
though so much against her will, that the tears came into her eyes,
and she could scarcely conceal them.

Now, dear children, I am aware that these are very ugly feelings that I am unfolding;
but at the same time, if you are faithful in looking into your own hearts,
I fear that some among you will be forced to say
that you have known something very like them.
It is because of these ugly feelings that we experience in our childhood,
that we know the truth of that solemn description of fallen human nature,
given by the mouth of God himself, (Genesis 8:21):
"`The imagination of man`'s heart is evil from his youth.`"

But blessed be His holy name, though we are these evil creatures from our youth,
He has not left us without help; He has promised us a new heart, and a new spirit,
and such a one as shall enable us to overcome evil with good;
for it is a good and blessed Spirit, even His own pure Spirit of truth,
that is offered to all those that sincerely ask for it.
(Matt. 7:7-12)

The acquirements of Harriet and Charlotte being ascertained,
were found to be more ex tensive than those of Gertrude;
but in such disorder as to be of little value.
Copy-books blotted and blurred,
and the title-page ornamented both inside and out
with the names of their respective owners,
Harriet Allen, and Charlotte Allen, in all sorts of hand-writing,
diversified with various heads and pictures, meant for those of horses, dogs, cows,
lions,
etc. betrayed but too clearly the idleness which
had accompanied even their efforts at improvement.

"`It may be as well to mention, once for all,`" said Miss Robson,
"`that I never allow copy or exercise books to be scrawled in.`"

"`Miss Singleton didn`'t mind that,`" said Harriet, pertly.

"`Perhaps not,`" replied Miss Robson; "`but I am not Miss Singleton.`"

The lessons for every day, and the hours at which they were to be learnt and said,
already drawn out, and written on a card,
being first read and then presented to each of the little girls by their governess,
the business of the morning proceeded.

But Harriet, out of humour with what had taken place on her first coming into the room,
and puzzled and perplexed to know how to deal with the quiet,
steady manner of Miss Robson,
was not to be brought under the discipline prepared for her,
without some further attempts at resisting it,
and also of establishing her usual habit of doing pretty much as she pleased
with those who would not be at the trouble of encountering her violent spirit.
For this purpose, she had recourse to disputing everything that Miss Robson had arranged.
She did not do her French exercise at this hour with Miss Singleton;
nor her Lindley Murray at that.

She did not say Magnall`'s questions on such a day,
nor her Goldsmith`'s history on another.

"`Well, my dear,`" said Miss Robson, "`what is that to me?
I tell you again, I am not Miss Singleton.`"

Her extreme coolness only added to the fury and folly of poor Harriet.
Poor, indeed, at the present moment; for heating herself more and more with passion,
she went on in an impertinent speech, till, when she concluded it,
she was actually crying, though nobody could tell what for.

It is not only sad and sinful to give way to passionate and evil feelings,
but it is also very degrading.
People generally make themselves ridiculous in the eyes of their fellow creatures,
whenever they allow a furious temper to get the dominion over them.
Such was truly the case at the present moment with poor Harriet--for poor enough,
as we have just observed, was the figure she made in the eyes of all present;
especially as Miss Robson, to whom all her violent nonsense was addressed,
sat as motionless as a statue, while she was pouring it forth;
and when she had ended it by bursting into tears, only remarked with the utmost calmness,
"`You had better take a turn or two in the garden, my dear,
till you feel able to go on with your lessons.`"

Her indifference increased the confusion and rage of the misguided girl; who,
having calculated, or rather mis-calculated,
upon drawing her new governess into some such argument as she had
been in the habit of holding with her mamma and former governesses,
when she wanted to make out that her own way was the right one,
was entirely baffled by a mode of conduct as new as it was disagreeable to her,
that she was wholly overcome by her feelings, and sobbed so violently,
that both Charlotte and Gertrude began to weep in sympathy.
It was surely the strangest scene to behold three little girls crying,
and not one of them knew the cause of her tears!
But Miss Robson knew; and, truth to say,
she had met with something of the kind many times before,
when dealing with children of violent tempers.

She felt truly grieved for Harriet`'s exposure;
but she was assured that the only means of doing her any real good,
was to allow her to be her own chastiser,
by causing her to feel the disgrace and sorrow that evil tempers naturally,
and necessarily, bring upon those who indulge them.
She took her by the hand,
and leading her to a distant part of the room where there was a small table,
she placed a stool there, and desired her to sit down and compose herself,
and when she felt able, to go on with her lessons.
At first, Harriet resisted this advice;
making herself still more blameable and still more silly,
by shoving away Miss Robson`'s hand as she pointed to the seat,
and sobbing out the words "`I won`'t,`" as little Johnny might have done,
if he had been able to speak; but which, from the lips of a girl of eleven years old,
was disgraceful indeed.

"`If you don`'t choose to sit down, you must stand,`" said Miss Robson;
"`for I cannot lose time in talking about it.
Only I think it would be better for you to do as you are bid; come,
yield to what is for your own good.
You will be very glad, in a quarter of an hour, that you have done so.`"

Still sobbing, but rather less violently, Harriet took her seat,
and Miss Robson gently laying her hand on her shoulder, said "`Now,
you will be able presently to go on with your lessons;`" and pointing
to the place in a book which Harriet was to transcribe from,
she returned to her other pupils, whose tears were also wiped away.

The utmost silence was maintained for some time.

Harriet, after this first struggle for dominion, which had ended so disastrously,
at last went on with her prescribed task,
perceiving it best in every point of view to submit to the will of her instructress;
and having finished and brought up her lesson to Miss Robson`'s satisfaction,
was allowed to resume her place at the table with the other little girls;
where she conducted herself in a very orderly and
becoming manner for the rest of the morning.
When school was over, its labours and afflictions were forgotten;
for distress is never of long duration in young hearts.

[verse]
____
The tear down childhood`'s cheek that flows,
Is like the dewdrop on the rose;
When next the summer breeze comes by,
And waves the bush,--the flower is dry.`"^
footnote:[Walter Scott.]
____

It might have been expected, perhaps, that Miss Robson would have taken an opportunity,
at the close of the morning`'s business,
to discourse with Harriet on the impropriety of her conduct at the commencement of it;
but, besides that she was at all times a woman of few words,
she adopted the plan of letting children learn as much as possible from facts and circumstances,
rather than from formal and set discourses.
She felt assured, that,
in consequence of the degrading situation to which her own violent
and ungoverned temper had been the means of reducing her,
Harriet had that day learned a weightier and more
enduring lesson than had ever been taught her before;
and, indeed,
it was evident from her manner towards her governess for the rest of the day,
that it was one also which had convinced her,
that whoever she expected to thwart or perplex in the task of managing her,
Miss Robson would not be the person fit for her purpose.
