== Chapter IV. Reproof and Amendment.

In less than a month from Miss Robson`'s appearance at the Rectory,
a great change for the better had taken place in the state of affairs there.
Both Harriet and Charlotte became more orderly and obedient in their behaviour,
and so decidedly improved under the tuition of their present governess, that Mrs.
Allen no longer interfered, as she had been too much in the habit of doing,
with the plans pursued in their education.

Gertrude, also, benefited by the present state of things.
She was not a very quick, though a very diligent little girl, and being,
as you have already seen, exceedingly shy and timid,
her advancement in her school pursuits had hitherto been much hindered by the lack of
patience she had encountered in those who had been deputed to instruct her;
which, owing to the weak health of both her parents and then their death,
had been chiefly the different servants that had the charge of
her before she came to Mr. Allen`'s. These persons were not much
used to the task of bearing with the ignorance of childhood,
and patiently waiting for the opening of its mental powers.
Indeed, it is greatly to be feared,
that many among those who are in a higher station than that of servitude,
and better fitted by education to deal with young minds,
are still lacking in that first and greatest requisite
for guiding and managing them properly,
which consists in well understanding,
and constantly acting upon the precious precept of our blessed Redeemer,
"`In your patience, possess your souls.`"

But Miss Robson was not of this number.
She had been deeply exercised in sorrows of various kinds; and used often to say,
that the necessity of obtaining a maintenance by
bearing with the tempers and habits of children,
in the arduous task of tuition,
which many persons would consider as an aggravation of other trials,
had been to her among her chiefest blessings, in taking her, as it were,
out of herself and her own particular interests and feelings,
and constraining her to exchange many useless regrets,
and vain contemplations on this and the other disappointment, for the useful occupation,
not only of teaching, but also of being taught.
"`I have, on the whole,`" she would frequently observe,
"`learnt more that is valuable from my pupils, than they have learnt from me.
Many are the precious lessons of patience, and self-control,
and knowledge of the workings of the human heart,
that they have unconsciously imparted to me.`"

You may be assured, therefore,
that she was not the person to meet with any impatience or discouragement,
the laborious efforts of Gertrude to accomplish what the
other children could do without any effort at all;
for they were remarkably quick and acute in their understandings,
and lacked nothing but Gertrude`'s diligence to become, in due time,
well informed and accomplished girls.

I told you that I should let people and things describe themselves; and so, I think,
I must give you a little scene in the schoolroom,
which took place about two months after Miss Robson`'s arrival;
which will serve to show you how the nature of the
little girls operated upon themselves and each other;
and also, how the conduct of their governess affected them upon that occasion.
There was one difficulty in spelling, that Gertrude was almost always puzzled in;
and that was the proper disposition of the two vowels i and e,
as they occur in such words as believe, perceive, receive, niece, chief, etc.
They have been found puzzling to older heads than Gertrude`'s,
and Miss Robson heard the frequent misplacement of these letters with the utmost patience.
But not so Harriet and Charlotte, who used to smile at one another,
and sometimes whispered to Gertrude before she began her spelling lesson,
"`not to put the cart before the horse,`" in a way rather trying to the poor little girl;
and truth to say, it was the arch and quick glance of Charlotte`'s eye,
while she was repeating her lesson, that often so bewildered her,
that it produced the very errors she was labouring to the utmost of her ability to avoid.

One morning that this was more particularly the case, Miss Robson observed it;
and when Gertrude had finished saying her spelling lesson,
and had been corrected in her usual error of misplacing the letters in the words believe,
receive, etc., she said to Charlotte,
"`I think you can write well enough now to take your slate,
and accompany your sister in her exercise from dictation.`"

Much elated, as children generally are with being engaged in something new,
Charlotte was soon ready with her slate, and seated herself with Harriet to write,
as Miss Robson read to them a passage which she selected for a particular purpose;
and as it is a very valuable passage,
and one from which much instruction is to be derived, I shall transcribe it for your use;
just telling you, that it was written nearly two centuries ago,
by a wise and good man to his children, during a time in which,
from various circumstances, he was obliged to be absent from them; and therefore,
like a tender father, desired to admonish them by letter, of several things, wherein,
from the ignorance and heedlessness of youth,
they were likely to stand in need of warning.
"`And remember this one thing,`" he says, "`which as a father I admonish you of,
and charge you to take notice of, and observe; which is this,
that you do not fly out upon one another,
or complain because of the evils you observe in one another;
but first take notice of that evil in yourselves,
and if you find your own hearts cleansed from it, bless God who has done it,
and keep to His grace whereby he did it,
and watch that you be not overtaken in it for the future.
But, if you be guilty of the same evil, or have lately done the same thing, or,
are suddenly liable to do it, oh, for shame! forbear accusing, or blaming one another;
and, in the fear of God, wait on Him, and pray unto Him,
that you may be delivered from it, and kept out of it.
And then, in tender pity, admonish your brother, or sister, of his or her evil,
and watch to be helpful to preserve or restore them.

"`But that is the bad spirit and nature (which God
will sharply punish) that is ready to accuse others;
and though it be never so bad and guilty, yet will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible and ashamed of its own.

"`Dear children, if you bend your minds to learn these things,
the Lord will help you therein, and become your teacher, guide, and preserver,
and pour down his blessings upon you; and you will be a comfort to me and your mother,
and an honour to his Holy Truth; and He also may give me wise,
fatherly instructions to teach you further.
But, if you be careless, foolish, vain, following your own minds,
and what rises up there from the wicked one, you will grieve my heart,
and provoke God against you, to bring evil upon you, both in this world and forever.`"

When Harriet and Charlotte had finished writing this passage,
their slates were put aside till Miss Robson was at leisure to correct them,
which she always did before school ended;
and they proceeded with Gertrude in their other morning tasks.

At the usual hour their occupation concluded,
and according to the rule established by their governess
they were leaving the room quietly,
and Harriet, as the eldest of the party, going first.
But, somewhat to their surprise, she and her sister were desired to remain behind,
and Gertrude was sent away alone.

"`I wished you to stay,`" said Miss Robson,
"`because there are so many errors in both your slates, especially in Charlotte`'s,
that I was unwilling to expose you by pointing them out before little Gertrude;
especially as I am assured that, seeing how liable you are,
even with your greater advantages, to make mistakes in spelling as well as her,
you will not for the future be so quick and sharp upon her for her errors.`"

Miss Robson then pointed out the words that were mis-spelt.
In Charlotte`'s slate there were many more than in Harriet`'s, because,
in the heat and eagerness with which she rushed upon her new occupation,
she was less watchful than her sister; but Harriet`'s was still a careless production,
and what was worthy of remark,
in both their exercises the word grieve had the vowels i and e placed wrong.
Both of them were deeply humbled,
not only by being made to feel their own liability to err,
but also by the manner in which they were reproved
for their ungenerous conduct towards Gertrude.
They were not, as I have before told you, unfeeling little girls; far from it,
only their feelings, till of late, had not been properly guided or controlled.
Good and bad, like weeds and flowers, had grown up together; and as,
alas! the evil in fallen human nature sprouts so much more readily than the good,
that which should have been rooted up,
had overgrown and choked the springing up of the better part.

Harriet took her slate in silence; and with a face suffused with the deepest crimson,
sat down at her desk to make the necessary corrections in her exercise.
But Charlotte, who, though an exceedingly violent, was, nevertheless,
a very affectionate little girl, and who had become much attached to Miss Robson,
felt her reproof in a way that more deeply affected her than can easily be described.
She, too, took her slate, and sat down to her desk;
but not immediately to correct her exercise,
but rather to think what a different creature she was from Gertrude; who, she was sure,
would not laugh at her, in her present humbled condition,
although she herself had so often sported,
and made herself merry with Gertrude`'s mistakes in spelling.
Miss Robson, too, she thought, how kindly she had acted,
when she might have exposed her so greatly before Gertrude!

While these reflections were passing through Charlotte`'s mind, Harriet,
having corrected her slate, took it up to her governess,
and then receiving permission to do so, went to join Gertrude in the garden.
Charlotte no sooner found herself alone with Miss Robson, than,
coming towards her with emotion which scarcely left
her the power of speaking so as to be understood,
"`Oh, Miss Robson,`" said she, "`what a naughty girl I am!
What a bad heart I have!`"

"`We have all bad hearts, my love,`" replied Miss Robson, kindly taking her hand,
and making her sit down by her side; we have all bad hearts, dear Charlotte,
till God gives us new ones.`"

"`Oh, I`'m afraid I shall never, never--`",
here her sobs impeded her finishing what she intended to say.

"`You will never, certainly, give or make yourself a good one,`" said Miss Robson,
"`if that is what you fear.
But '`ask, and you shall receive; seek, and you shall find; knock,
and it shall be opened unto you.`' God has the new heart to give.
See here! let me read this precious Scripture to you;`" and taking up her Bible,
which never was absent from the school table, she read from Ezekiel 36:26-27,
these words: "`A new heart will I give you, and a new spirit will I put within you:
and I will take away the stony heart out of your flesh,
and I will give you a heart of flesh.
And I will put my Spirit within you, and cause you to walk in my statutes,
and you shall keep my judgments, and do them.`"

"`Now, dear child, at this moment, the Lord is fulfilling to you this gracious promise.
At this moment he is softening, or taking away, the stony, hard, selfish heart, which,
for the sake of a poor jest, an unworthy amusement,
has so often made you regardless of poor Gertrude`'s feelings.
I dare say, you would rather undergo any pain at the present moment,
than laugh at her about her mistakes in spelling?`"

"`Oh, that I would!
I will never laugh at her again.
Dear Gertrude!
Oh, if I were but as good as Gertrude!
She never laughs at any body!`"

"`You are different in your natures, my dear; Gertrude is a remarkably timid,
reserved little girl.
You are very high spirited, and violent, and fearless.
What makes you otherwise at the present moment?
Why are you acting contrary to your nature now?`"

Charlotte was silent, but deeply thoughtful at this question;
and Miss Robson did not interrupt the pause till it had continued for some little time.
She then rose, and taking Charlotte`'s hand,
she repeated with much solemnity the Scripture promise;
"`And I will put my Spirit within you.`"
"`It is a better spirit than your own, my love, that you now feel,`" said she;
"`even that blessed Spirit which the Lord here promises,
and which our compassionate Saviour has directed us to ask for;
tenderly suggesting to us how surely it will be given,
if only sought for in sincerity and truth.
'`If you, being evil,`' He says, '`know how to give good gifts unto your children,
how much more will your heavenly Father give the
Holy Spirit unto them that ask him!`' How much more!
Oh, Charlotte, what words are those!
How inviting!
How tender!
Ask, then, and it shall be given you.`"
Then kindly kissing her cheek, Miss Robson quitted the room; and Charlotte,
as soon as she was a little composed, corrected her exercise,
and then went to join her sister and Gertrude,
whom she found sitting in an arbour in the garden.

Their occupations during play-hours were generally such as to separate,
rather than bring these young people together.
The two sisters, indeed, from their similar love of active recreations,
were more often found in each other`'s company than in Gertrude`'s,
whose constant satisfaction in her doll and her cradle,
was so wearisome and insipid to their restless spirits,
that they seldom remained long in her society.
But this morning, Harriet, on quitting the school-room,
came to the little arbour where Gertrude usually repaired with her treasures; and,
in so gentle and altered a manner, asked if she might play with her,
that the little girl was quite surprised,
and being somewhat afraid that this agreeable behaviour
concealed a design of playing off some joke against her,
rather cautiously replied, "`I know you don`'t like playing with a doll, Harriet.`"

"`Oh, indeed I do, Gertrude,`" replied the other, "`I have been thinking, dear,
that I am not always so kind to you as I should be; no more is Charlotte.
And you are always very kind to us.`"

Gertrude looked a moment or two at Harriet as she said this,
and seemed to have some reply to offer to it.
But Gertrude was not eloquent.
She always felt more than she knew how to express in words,
and finding on the present occasion that they were not at her command,
she conveyed the meaning of her thoughts, by putting her arms round Harriet`'s neck,
and tenderly kissing her cheek.

Harriet, on the contrary, was a powerful talker;
and she had now no difficulty in uttering those feelings which prompted her to
express much regret for every instance of past unkindness to her young friend,
and promises to avoid it for the future.
As a token of her sincerity, she took the doll from the cradle,
with a regard almost equal to what Gertrude herself would have evinced;
and was soon as much engrossed and amused as her companion,
in the nursery affairs connected with it.

They were thus engaged, when Charlotte was perceived coming over the lawn to join them.
A sort of instinct at the first glance of her,
occasioned Gertrude to pop the doll into the cradle,
and place both under the bench on which she was sitting,
to conceal her prized possessions from danger.

"`Oh, Charlotte won`'t play any tricks with it this morning,`" said Harriet,
observing this hasty action, and too well detecting the reason for it.

Gertrude did not feel so sure of that as to resume her amusement,
until Charlotte herself, with a kindness and good humour that could not be resisted,
begged to be admitted of their party;
and hearing from Harriet that another doll would add greatly to their enjoyment,
ran off delighted to fetch her own, with which she soon returned,
having added to it all the scattered articles of its wardrobe
which in her haste she could collect together.

Gertrude was at first surprised at such unusual attention,
where she had been accustomed to meet only with neglect or even worse;
but as young minds are seldom disposed to inquire
into the causes of this or the other circumstance,
but remain contented with the present moment and the present thing,
so long as they bring pleasure in their train,
she quickly lost her astonishment at the kindness of her play-mates,
and if she had wondered at all,
it would have been that they had not been always as happy and comfortable together,
as at the present time.
