== Chapter V. Guilt and Remorse.

Some of my young readers,
who have travelled with me thus far in the history of things
and people which this little work professes to give,
may be apt to say, "`We hear a good deal of Harriet`'s faults, and Charlotte`'s faults,
but nothing about Gertrude`'s faults.
Was she not sometimes overtaken by temptation to evil, as well as they?`"
My reply must be, that she certainly was;
though inbred sin manifested itself in a different manner in her case,
to what it did in theirs; and, as a faithful historian,
I find it will now be my duty to lay open a transgression, of a very serious nature,
into which, in an unwatchful moment, she was betrayed by that cruel adversary,
"`who goes about as a roaring lion, seeking whom he may devour.`"

It was not, however, in his character of the roaring lion,
but in that of the wily serpent, as better suited to her particular temperament,
that he presented his baits to Gertrude.
But I must relate the circumstances to you.

I have told you that Gertrude passed a great deal of time in the nursery,
being very fond of playing with little Johnny, who was just as fond of being played with.
Now it happened one morning before school began,
that she came out of her little bed-room which opened into the nursery,
just as Sarah was called by her mistress downstairs.

"`Be so good as to stay with the baby a minute till I come back,`" said Sarah;
a request which Gertrude was willing enough to comply with,
and took her place on the carpet by the side of Johnny,
who was seated there with a rattle in his hand,
which he was brandishing about with great energy,
and somewhat to the danger of poor Gertrude`'s head and hands.
All at once, however, his eye caught sight of a sugar basin on a table very near to him,
which basin was filled to the top with lumps of sugar; and immediately he began,
after his manner of making his will and wishes known, to clamour for it.

At first, Gertrude steadily resisted his importunities, by repeating "`No, baby! no! no!`"
At last, however, the strong temptation began to work upon her imagination,
as well as Johnny`'s. She thought there could be no harm in giving him "`just a morsel,
poor little fellow!`"
Johnny no sooner saw her rise and approach the sugar basin, and just take up one bit,
and then another,
than his desire to obtain a lump became more impetuous
than ever,--and in order to accomplish his wishes,
he left no means untried that were within the compass of his abilities.
He clapped his hands together,
and uttered all the sounds of ta! and pa! and ma! that he had been used to find admired,
or, on particular occasions, called for,
and soon had the happiness of proving their success.
Gertrude selected a little bit, and gave it to him, and though this was wrong, yet,
alas! it was not the only wrong that accompanied the affair;
for after thinking that there was no harm in giving little Johnny a bit of sugar,
she began to think that there was no harm in eating a little bit herself;
and then she found it so nice,
that she thought she should like to put a lump or two in her pocket, to eat by and by.
Never parley with temptation, my dear young friends.
To hesitate, is most commonly to yield to the advances of the tempter.
Always remember that there must be no talking with yourself,
when you come in contact with anything you wish to have, or wish to do,
that you know you should not either desire or do.
"`Escape for your life, look not behind you!`" such was the counsel of the angel to Lot,
when he brought him out of Sodom; and such will be blessed counsel for you to follow,
when tempting objects present themselves to your notice, as they did now to Gertrude.

If, at the first glance she cast upon the sugar,
she had placed it out of the sight both of Johnny and herself, and thus,
as it were escaping for her life, had not then looked back to any remembrance of it,
what a deal of guilt, and sorrow, and remorse, would she have escaped!

She had now committed two faults; the one,
in giving the baby what was very improper for him to have,
and that contrary to an injunction which Sarah had often repeated,
never to give him anything to eat; and another, in pilfering the sugar for herself.
I have yet, with deep regret, to add one more, and that of a still deeper dye;
one that is seldom found to be absent when wrong doings are entered upon; and that was,
the telling of a lie.

One lump of sugar had been eaten by her, and a smaller one by Johnny,
and two lumps secreted in her pocket,
before the sound of Sarah`'s feet on the stairs created alarm in her heart;
but hastening to her seat on the carpet, by the side of the little boy,
she endeavoured to hide the workings of a guilty conscience, in talking to him,
and amusing him with the rattle and other toys that were scattered about him.

But Johnny, who had been quiet enough, as well as his companion,
while regaling upon the sugar, having come to the end of it,
was not to be put off with either rattle or ball,
when he found there was anything so much more agreeable within his reach.
In vain was Gertrude`'s exclamation of "`Hush! hush! here, baby,--see,--see here!`"
Sugar was what he wanted, and sugar he would have; and finding that he could not,
he beat away the play-things,
and set up such a tremendous cry just as Sarah opened the door, that alarmed,
and not knowing what had happened, she rushed forward and took him on her lap.
Her sitting down in a line with the sugar basin, immediately stopped his cries; for,
catching a nearer view of it, he began stretching out his hands,
and then clapping them together, and mumping with his mouth,
in a way which intelligibly enough explained what it was he was crying for.

"`Oh, you little rogue, is that what you want?`"
said Sarah.

Then, as if suddenly recollecting that it was odd he should so violently clamour for the sugar,
unless he had already tasted it, she turned to Gertrude and said, "`I hope, my dear,
you have not been giving him sugar?`"

Quite unlike her usual gentle manner of speaking, Gertrude now, rather angrily,
and almost in tears, replied, "`I`'m sure I didn`'t!!`"

There was something so agitated in her look and tone,
that Sarah more than suspected the truth; and, perhaps,
would have pursued her inquiries in a way that would have brought it out,
had not Charlotte at that moment entered the nursery,
to remind Gertrude that school was begun,
and Miss Robson waiting for her to come and read.
If you should ever have observed, dear young friends, on a summer`'s day,
a cloud suddenly arise, and cover the heavens,
thus darkening and spreading such a heavy gloom over things, that the trees, plants,
and flowers scarcely seem to be the same as they were but a little while before,
when they were gilded with the cheerful beams of the glorious sun,
you may form some idea, though but a faint one,
of the melancholy change which the last half hour
had been the means of effecting in Gertrude`'s feelings.
The sunshine of her spirit was, indeed, suddenly overcast, and a heavy gloom,
like that which the presence of a thunder-cloud spreads over a landscape,
darkened her mind.
She followed Charlotte, like a culprit,
to the schoolroom,--so little hearing or heeding the sprightly
remarks that her lively companion made to her in the way there,
that she, at last,
asked her "`if she were not well;`" a question not unlikely to be put to Gertrude,
as her health was very delicate,
and sometimes she was so much indisposed as to be unable to attend to her studies.

"`If you have got the head-ache, Gertrude,
I`'m sure Miss Robson will excuse you,`" said Charlotte.

Alas! it was a worse ache that oppressed poor Gertrude now.
It was the aching of a wounded conscience, of which it is said in holy writ,
"`the spirit of a man will sustain his infirmity; but a wounded spirit who can bear?`"

"`I`'m very well,`" said Gertrude, gloomily.
Her very nature seemed to have undergone a change,
and to have become dark and morose in consequence of yielding to the influence
of him who is among "`the rulers of the darkness of this world.`"

During the whole business of the morning, she was not merely silent,
for that was usual with her;
but there was a sullenness in her deportment which was so uncommon, that Miss Robson,
after having, like Charlotte, inquired if she were not well,
felt assured that something weighed upon her mind and occasioned her altered behaviour.

Poor Gertrude! she was now in a state by no means uncommon with sinners, and one,
which is as much to be dreaded and avoided as the transgressions which occasion it,
and that is, a state of hardness and obduracy.
Children like Gertrude are much more prone to fall into this state,
than those who are of a more lively and open cast of mind;
because their extreme reserve in communicating themselves, causes all their feelings,
whether evil or good, to sink deeper, and remain longer in their hearts,
than is the case with those who give vent to their emotions in words.
That wicked one, therefore,
who too well knows which of our weaknesses and sins will best serve his turn,
pursued his assaults upon the poor child through her pride and reserve of character;
and constantly suggesting to her not to be troubled, nobody could know what had passed,
and to take care that nobody did, by keeping it as close in her own heart as possible,
he reduced her exactly to the state most fitted to keep her his captive.

But, oh, it was a wretched state! and such a one as Gertrude had never before experienced.
In vain did she try to follow Harriet and Charlotte to the garden,
when the usual hour for recreation arrived.
In vain did she attempt to seem cheerful and unite with them in their sports.
The very thought of play made her more gloomy than ever.
She felt angry with them for asking her to join in it, and walked silently away.

"`How odd Gertrude is this morning!`" said Harriet to her sister,
as she walked out of the arbour.
"`I think she cannot be well.`"

"`She says she is very well,`" said Charlotte;
"`and I don`'t think there is anything the matter with her,
except that she is out of temper.`"

"`Gertrude is not often out of temper,`" said Harriet.
"`I`'ll go and ask her what`'s the matter.`"

"`I`'ll go too,`" said Charlotte;
and they hastened to her as she was bending her steps
slowly and sorrowfully towards the house,
and, in the kindest manner, asked her what was the occasion of her evident discomfort.

"`I cannot play this morning,`" she replied,
without answering their inquiries as to her uneasiness.
"`I cannot, indeed;`" and, to avoid further questions,
she turned away from them a second time, and went into the house,
and up stairs into her own little bedroom.

In passing through the nursery, she saw Miss Robson there, talking with Sarah;
but neither of them made any remark to her,
and she was glad to get unobserved into her apartment.

I must here tell you, that the cause which had brought Miss Robson into the nursery,
was to ask Sarah,
who had usually more of Gertrude`'s company than anyone else in the house,
if she knew of anything that had occurred to occasion
the unpleasant change in the little girl`'s behaviour,
which she had that morning observed.

Sarah related the circumstances of her leaving the baby in Gertrude`'s
charge when her mistress called her downstairs;
she often having done so before, when both were on the carpet,
and therefore safe from harm; her being detained rather longer than she expected; and,
on her return, the importunities of the little boy for sugar,
inclining her to suspect that he had tasted of it in her absence.
She mentioned also, as she felt it her duty to do, that,
from the confusion and quite unusual irritation in Gertrude`'s manner of replying,
when she questioned her on the subject,
she believed she had been guilty both of taking the sugar,
and telling an untruth about it.

This was sad intelligence for Miss Robson,
who loved all her pupils with more of a mother`'s affection than any other feeling;
and who had in a particular manner attached herself to the orphan Gertrude; and that,
not altogether so much on account of her helpless condition as being destitute of parents,
as from the endearing qualities which she had perceived in the little girl herself.
But sad as were the suspicions which were now excited respecting her,
they did not occasion much surprise.
Miss Robson was well versed in an acquaintance with the human heart,
and would have expected, from what she knew of Gertrude`'s nature,
that any deviation from the path of truth and uprightness, would be likely, in her case,
to lead her still deeper into evil,
by exciting a disposition to subtlety and concealment,
which she perceived to be the child`'s most dangerous and besetting sin.
It was some comfort to her to find that she could
not be happy under the consciousness of guilt.
That is always a satisfaction; for, next to the falling into sin,
the evil most to be dreaded is the throwing off the reproaches of conscience,
and assuming a gay and cheerful demeanour,
while something within is continually saying to us,
"`How could you do that great wickedness, and sin against God?`"

For the whole of the day Gertrude continued in the same state of gloom and depression.
In the evening Mr. Allen, who usually, before family worship,
read to the little circle for about half an hour,
from some biographical or historical work which he considered
likely to interest and instruct his young hearers,
sat down to his accustomed engagement; while Mrs.
Allen, Miss Robson, and the young people, pursued their needlework.
I shall not undertake to say whether it was accidental,
or whether some hint from Miss Robson might influence
his choice of a book for this evening;
but so it happened, that having selected the Life of Samuel Kilpin,
as that from which he was to read to them,
he had not proceeded far in it before he came to this anecdote.

"`When seven years old,`" says Mr. Kilpin, "`I was left in charge of the shop;
a man passed, crying, '`Little lambs, all white and clean,
at one penny each!`' In my eagerness to get one, I lost all self-command, and,
taking a penny out of the drawer, I made the purchase.
My keen-eyed, wise mother, inquired how I came by the money?
I evaded the question with something like a lie; in God`'s sight it was a lie,
as I kept back the truth.
The lamb was placed on the chimney-shelf, and much admired.
To me, it was a source of inexpressible anguish.
Continually there sounded in my ears and heart, '`Thou shalt not steal!
Thou shalt not lie!`' Guilt and darkness overcame my mind; and, in sore agony of soul,
I went to a hay-loft,
(the place is now perfectly in my recollection,) and there prayed and pleaded,
with groanings that could not be uttered, for mercy and pardon.
I entreated mercy for Jesus`' sake!
With joy and transport I left the loft, from a believing application of the text,
'`Your sins, which are many, are all forgiven you.`' I went to my mother,
told her what I had done, and sought her forgiveness, and burnt the lamb,
while she wept over her young penitent.`"^
footnote:[Life of Kilpin, p. 6.]

As soon as he had finished reading this touching anecdote, Mr. Allen made a pause,
as he usually did when he came to anything of a particularly interesting kind.
Then, closing the volume, "`I think, dear children,`" said he,
"`that I should do wrong to lead your minds away from the instructive
and affecting impression which this anecdote is fitted to leave upon them,
by pursuing the story.
I would rather talk with you a little about the feelings
which it has awakened in my own mind.
And first, I would draw your attention to two circumstances recorded in it,
which I confess do powerfully strike me.
The one is, the state of the child`'s mind when he entered the hay-loft, and the other,
the alteration which had taken place in it when he left it.

Guilt and darkness overcame my mind, and, in sore agony of soul,
I went to a hayloft.`' This, you observe,
was his sorrowful condition on entering the place; but, on leaving it, what a change,
what a blessed change had occurred!
With joy and transport,`' he says, '`I left the loft.
Now, we have not to inquire what had occasioned this happy transformation,
for he tells us, it was the result of a believing application of the text,
'`Your sins are forgiven you.`' We have not, I say,
to employ our minds in the way of inquiry or reasoning upon these circumstances,
but we are required to consider the great blessing
which attends a truly penitent confession of sin.
We are all liable to fall into temptation.
We are all poor helpless creatures,
encompassed about with the snares of the devil on every side,
and bearing in our hearts a treacherous foe,
that is continually ready to hearken to the subtle tempter.
But observe; though we may fall into the net that he is spreading for our feet,
we have it always in our power to turn to the Deliverer; to the dear Redeemer, who,
though he never sinned, was often tempted,
and who has a portion of the tenderest pity to impart
to all whose frailty causes them to be overcome.
Now the work and way of Satan with us, is first to draw us into the commission of evil,
and then to harden our hearts, by representing to us this and the other lie,
(for he can never represent anything else but lies)
in order to mislead and perplex us still further.
Sometimes he tells a poor sinner, that nobody knows of what he has done,
and nobody need to know, if he will only keep his own counsel,
and be steady in denying his fault whenever it is mentioned.
This is his favourite, and, alas! too successful way of proceeding;
and it is his favourite way,
because it holds the poor captive still faster in his chains,
by causing him to add lie to lie, and sin to sin, till the wretched creature thinks,
'`Now I may as well go on; I can sin no worse;
I have already made myself vile in God`'s sight:`' and thus, the heart gets hardened,
till it realizes that awful description contained in these words,
I knew that you are obstinate, and your neck is an iron sinew, and your brow brass.^
footnote:[Isaiah 48:4.]
But this was not the state of the boy of whom we have been reading.
Happily for him, he did not allow the wicked one to prevail in hardening his heart.
He took the only step left for him to take, after he had fallen into sin.
He arose, like the prodigal son, and went to his Father; and the Father of Mercies,
like him of whom we read in the parable, met him with such a welcome,
such a joyful welcome, that all his guilt and darkness, and sore agony of soul, was gone;
and in its place, both joy and transport filled his heart.
Therefore, my children, whenever the cruel adversary tempts any of you into sin,
remember the example of this dear child.
Don`'t go to Satan for counsel or comfort.
Abhor the rest or peace which you can find in anything he suggests.
You have no business with any ease or happiness of mind,
while your sin remains unconfessed before God.
I say, you have no business with it.
It does not belong to you.
God would not be God,
if he were to permit us to be happy while we are willfully and consciously
persisting in those things which he has forbidden.
What would you think, now, of me, who am a mere human being,
and a poor helpless sinner of the same nature as your own; yet,
what would you think of me, I say, if, after I had detected you in any fault,
I were to say, Well, never mind; try and forget it as fast as you can,
and be sure don`'t make yourself still more uncomfortable by confessing it;
but strongly deny it,
and determine to be happy?`' Would you not in your hearts despise me?
Yet, something of this kind, only infinitely more degrading,
because it relates to an Infinitely Perfect Being,
are the thoughts that hardened sinners entertain towards God.
Hence we read in the 50th Psalm, that, in addressing such persons, the Lord says,
'`You thought that I was altogether such a one as yourself.`'

"`But there is another state, and a far more hopeful and desirable one,
which sometimes follows the commission of sin,
and which was the state of the dear child of whom we have been reading; and that is,
a state of great anguish and remorse.
You observe how feelingly, how impressively, he speaks of it.
'`The lamb,`' he says, placed on the chimney-shelf, and much admired.
To me it was a source of inexpressible anguish.
Continually there sounded in my ears and heart,
'`Thou shalt not steal!`' '`Thou shalt not lie!`'? It was in this sore agony of soul,
that he turned to the true Helper.
It was by yielding to the woundings and prickings
of the righteous Spirit he had vexed and grieved,
that all was healed.
Had he hardened his heart,
by resisting the workings of this faithful and true witness--had
he determined not to be troubled by it,
and persisted in concealing his sin,
how differently might his whole life have afterwards turned out!
How hard he might have grown!
How impenetrable!
How bold in wickedness!
How impudent in a way of lying!
Oh, my children, my dear children, seek above all things, of the Lord,
that tenderness of conscience which will not let you be happy in an evil way.
All that is needed, when we have fallen into sin and transgression,
is that we return unto the Lord our God.
'`Take with you words, and turn to the Lord: say unto Him, Take away all iniquity,
and receive us graciously.`'^
footnote:[Hosea 14:2]

Mr. Allen ceased to speak,
and apparently was deeply absorbed in thought for a few moments; then closing the book,
and looking at his watch, he said it was time for the servants to come in.
He was about to rise and ring the bell,
when an audible burst of tears from poor Gertrude, drew every eye upon her.

She was standing alone by the corner of the side-board,
where she had gone to deposit her work in a drawer
that was dedicated to the use of the children;
and there, with her back towards the rest of the party,
she had been struggling as long as she could,
not against her "`sore agony of soul,`" but, if possible,
against betraying it till she had entered into her little sanctuary,
and poured out her sorrows before her heavenly Father.
But her emotion had been too long working, and had become too intense,
to be any longer restrained.
She leaned her head upon her hands, which she clasped together,
and laid upon the side-board, while she sobbed as if her heart would break.

The children, and also Mrs.
Allen, were eagerly hastening to inquire what was the matter,
but Mr. Allen motioned to them to be still; while Miss Robson,
to take off their attention, engaged them in looking at some drawings with her.
Mr. Allen then went towards Gertrude, and tenderly drawing her near him,
sat down upon a chair that was at hand, but in such a way that, as she stood before him,
he sheltered her from the observation of the others.
He soothed her with the kindest words,
wiped away her streaming tears with his handkerchief,
and as soon as he perceived that she could speak intelligibly,
he asked the cause of her distress, but in so subdued a tone of voice,
that the rest of the party, who were at the other end of the room,
could not hear what passed.
Without immediately answering, Gertrude put her hand into her pocket,
and producing two lumps of sugar, she looked up in his face,
and again bursting into tears, "`I stole them,`" she said.

Mr. Allen expressed some tokens of deep concern at hearing this.

"`But you are very sorry for your fault, I don`'t doubt?`"
said he.

"`Oh, so!--so--so very sorry!`" she at last sobbed out.

"`And have you confessed your sin to your heavenly Father, Gertrude?`"
inquired Mr. Allen.

"`I couldn`'t pray till you read about that poor little boy, sir.
But ever since I have wished I was alone, that I might do as he did.`"

"`Then your heart has prayed, dear child; and God looks at the heart,
and sees what is going on there;
and when He beholds sincere repentance and sorrow for our faults, he forgives us,
like a merciful Father.`"

"`Oh, I have not told you all, yet!`" said Gertrude, still weeping.

"`I dare say I can tell you,`" said Mr. Allen;
"`I don`'t doubt but that the wicked one who tempted you to steal the sugar,
tempted you also to tell a lie to hide your fault.
Whatever sin he draws a poor soul into, he is sure to add lying to it,
if it was not there before.
He tempted you to lie?`"

"`Indeed he did; I told Sarah a wicked lie, I said I had not given the baby sugar,
when I had.
Oh, how wicked I have been!`"

"`Well, my child,
be thankful that the Lord has touched your heart with a sense of your sin.
Your duty now is to confess it humbly before Him,
and to acknowledge it to those of your fellow creatures whom you have deceived.
I dare say you would willingly tell Sarah the truth,
and acknowledge to her how wrong you have acted?`"

"`Oh that I would.
I should be so glad to speak to her before she comes into prayers.`"

"`Come, then, and I will take you to her;`" and leading her by the hand,
Mr. Allen went with her to the foot of the stairs, and called Sarah,
who soon made her appearance.

"`Here is a little girl who has something to say to you, Sarah,`" said he;
"`take her with you into the nursery; and in a few minutes I shall ring,
and you can both come in together.`"

Scarcely had Sarah returned into the nursery,
than Gertrude threw her arms about her neck, and,
as well as her tears and agitation permitted, relieved her burdened heart,
by acknowledging her guilt.

We may believe that Sarah was not long in comforting her, and,
as far as she herself had been offended, in forgiving her.
But Gertrude felt there was a higher than any human being whom she had sinned against;
and, before she returned into the parlour, she went into her own little room, and there,
kneeling down,
relieved her full heart of all its burden by a humble and sincere confession of her sin.
Like the dear child,
whose touching history of his fault and penitence had so pierced her soul,
that she could scarcely restrain her emotion in listening
to it,--she left her solitude "`with joy and transport.`"
The dark thunder-cloud upon her spirit had passed away; and when Mr. Allen rang the bell,
she could follow Sarah to the parlour, a different being from the poor unhappy,
conscious-stricken Gertrude whom Charlotte had summoned to the school-room in the morning.
