== Chapter X. Hasty Spirits.

It had been a source of great satisfaction to Gertrude,
during her long and languishing illness, to hear from Miss Robson, and her young friends,
Harriet and Charlotte, how the affairs of the poor people in the village prospered;
what children got prizes at the Sunday school; what babies were born,
and what names were given to them; and in what way the little frocks and gowns,
and other articles of clothing that were made at the Rectory, were disposed off.

As great also was the gratification which Harriet and her sister derived
in obtaining and communicating intelligence upon these points.
But, as in larger communities than that of Woodside,
the evil passions of human nature will be found to rise up and oppose what is good,
so in that small and sequestered spot,
there was not lacking "`the strife of tongues`" to manifest the presence
of a root bearing gall and wormwood in some of Mr. Allen`'s parishioners.

But, as it was Miss Robson`'s chief object at all times to extract something valuable,
even out of those circumstances which seemed to promise it the least,
she was not discouraged if in their round of visits at the houses of the poor,
they did sometimes meet with behaviour which Harriet,
in the energy of her warm and inexperienced feelings,
would characterize at once as shameful ingratitude, or something equally odious;
but which Miss Robson`'s larger knowledge of human
nature inclined her to consider more indulgently.
Harriet`'s indignation was one day particularly roused (indeed it had often been excited,
though in a less degree, before) by the conduct of a woman named Mary Hayes, who,
having recovered from a rheumatic fever,
during which she had been a pensioner of a benevolent society, of which Mrs.
Allen was the patroness and head, was informed by Miss Robson that,
on the following week, her allowance as an invalid would cease.

"`To be sure,`" exclaimed Mary, "`Mrs.
Allen must do as she likes.
But this I`'m clear and certain of,
that there`'s nobody in the village as more needs
help than I do--so weak and helpless as I am!`"

"`You seem to have recovered your strength pretty well, too, I think,`" said Miss Robson,
rather archly.

"`Your voice is loud enough, I`'m sure,`" said Harriet.

"`It`'s enough to make any body loud,`" she angrily replied.
"`And just to see that Judy Taylor having her half-a-crown
a week!`" adding some epithets so exceedingly rude and injurious,
that Miss Robson without replying, summoned her young people,
and rose to quit the cottage, merely bidding her "`Good morning.`"

Charlotte,
though nearly as much incensed as her sister with
the insolence and ingratitude of the woman,
obeyed the summons of her governess, and followed her out of the room.
But Harriet, forgetting that she was quite as angry, though from another cause,
as the poor woman herself, and therefore as unfit to speak,
remained behind to lecture her upon the impropriety of her conduct.

To give reproof in anger, to be sure,

What`'eer the fault, is not the way to cure.

Would a wise doctor offer, dost thou think,

The sick his potion scalding hot to drink?^
footnote:[Dr. John Byrom.]

I shall not relate to you what passed, for it would be very little to your edification.
You may suppose it was anything but of a healing nature,
when I tell you that in about ten minutes,
Harriet overtook her sister and Miss Robson at the other end of the village,
looking as discomposed and as angry as Mary Hayes herself had looked.

"`What is the matter?`"
said Charlotte;
an inquiry which Harriet answered by pouring forth
many vehement accusations against Mary Hayes,
in the midst of which they were met by Mrs.
and Miss Thomson, who, having made and answered the usual salutations of the day,
were passing on.

Full of the excited and irritated feelings which Mary Hayes had awakened in her mind,
Harriet arrested Mrs.
Thomson`'s progress, by saying, "`Oh, Mrs.
Thomson, I hope you will never do anything more for Mary Hayes.
I hope you are not going to her cottage?`"

It happened that Mrs.
Thomson actually was going to see Mary Hayes; for, living very near Woodside,
she was not only a subscriber to the society from
which the sick poor of that village were assisted,
but she also visited them, and, being in affluent circumstances, and kindly disposed,
she gave away much money and clothing among them.

Of course she was very much surprised by Harriet`'s remark,
and stating that it had been her intention to call on Mary Hayes,
she begged to know what had passed to render it unadvisable;
addressing her words to Harriet, but her looks to Miss Robson,
as supposing her better fitted to inform her of the true state of the case.

Miss Robson smiled,
and interrupted the hasty and voluble explanation that Harriet was pouring forth,
by saying, "`gently, gently, Harriet!`"

Mrs.
Thomson smiled also, and said,
that perhaps Miss Robson would be so kind as to detail the case.`"

To be treated like a child, added to the other indignities that had been heaped upon her,
was quite too much for Harriet`'s towering spirit to brook.
She remained proudly silent, while Miss Robson,
to whom such scenes in human life as they had just
witnessed with Mary Hayes were not by any means new,
quietly and simply informed Mrs.
Thomson that the poor woman, although recovered,
did not like being taken off the list of pensioners,
and had therefore expressed herself on the subject very improperly.
"`But I have not the least doubt,`" she continued, "`that before night arrives,
she will be sincerely sorry for her fault.
Mary Hayes is a very passionate, violent-tempered woman,
and always says more than she intends to say, when her fits of ill-temper are upon her.
And you know, Mrs.
Thomson, when we consider what half-a-crown a week is to a poor woman,
we ought to make some allowance for the pain and disappointment
she would be likely to experience in having it taken away.`"

Mrs.
Thomson, who was extremely goodnatured,
could easily see and make allowance for the difficulties of the case;
and proceeded to extenuate Mary`'s fault as much as possible, addressing herself also,
on that point, to Harriet, who, if I must state the truth,
was in no disposition to be addressed to any advantage at that moment.

I shall not expatiate on the arguments she used to
prove to Harriet what a different condition she,
as the daughter of Mr. Allen, the Rector of Woodside, was placed in,
to that of poor rheumatic Mary Hayes, obliged to labour for her livelihood.
Neither shall I detail the instances of gratitude among the cottagers,
which she brought forward to balance against Mary`'s lack of it;
for as much as is necessary of what she said,
you will be able to gather from Harriet`'s observations when the parties separated;
Miss Robson and her young people to return home, and Mrs.
Thomson and Laura to visit Mary Hayes;
Miss Robson having been very urgent with them to do so,
in the hope that it might tend to heal the wounds which she had
no doubt Harriet`'s fiery zeal had greatly served to inflame.

I hope, Miss Robson, you will excuse my making the remark,`" said Harriet, very loftily,
"`but indeed I think,
if you had heard all that Mary Hayes said to me when I stayed behind to speak to her,
you would hardly have thought it right to countenance her so much.`"

"`I don`'t countenance her ill behaviour, my dear,`" replied Miss Robson;
but I have lived somewhat longer in the world than you have, Harriet,
and I find it a good rule, in dealing with angry people,
to leave the door open for their return out of their ill-tempers.
Passionate persons, of all others, require compassion;
they generally do themselves so much harm, that if no one was found to pity them,
and provide a sort of safety valve for their spirits,
they would be in perpetual danger of explosion.`"

"`Well, really, I do think,`" said Harriet,
still too angry to be convinced she was in the wrong,
"`I really do think that is carrying compassion rather too far.
I can understand why Mrs.
Thomson is so full of love for all her '`dear poor people,`'
as she calls them because they flatter her;
and then it does very well for her to talk about that '`interesting Sarah
this,`' or that '`sweet Susan that,`' as she did to me just now;
and to advise me to seek their acquaintance; but that you,
Miss Robson--`" and there she stopped,
unwilling to say all that her anger inclined her to say.

"`Oh, Harriet dear, indeed you are wrong,`" said Charlotte.
"`Try and forget Mary Hayes.`"

"`I`'m sure, Charlotte, if she had talked to you, as she did to me,
you would have been ten times more angry than I am.`"

"`That would have been a fearful sight to see,`" observed Miss Robson.
"`I am very glad Charlotte escaped the hazard of exhibiting it to us.`"

"`But what did she say to you?`"
inquired Charlotte.

"`Oh, she told me she didn`'t need to be taught by a child like me,
who she had seen a little while ago in baby clothes.
And when I told her she ought to cultivate meekness and humility,
'`Meek indeed!`' said she, '`Yes, you are a meek one!
Don`'t I recollect you, Miss Harriet, from your cradle?`' What do you think of that?`"
There was something in the circumstances of the case,
I shall not undertake to describe what, but assuredly something there was, which,
when Harriet concluded her account by saying "`what do you think of that?`"
inclined Miss Robson to turn her head aside to conceal a smile.

They were now arrived at the Rectory,
and Harriet was still harping upon the string of her grievances.
Miss Robson, therefore, speaking rather decisively, begged to hear no more on the subject.
"`Both you and Mary Hayes will be quite different persons before you go to bed, tonight,
I have no doubt,`" said she.

"`It might be the case, and she hoped it would with Mary Hayes,`" Harriet replied;
"`but for herself, she was quite sure she should always think the same; and that was,
that she had been very improperly treated.
But there`'s mamma,`" she exclaimed, as she observed Mrs.
Allen coming to meet them across the lawn;
"`I`'ll hear what she says;`" and without pausing
to attend to Miss Robson`'s half uttered "`Stay,
stay a moment,`" she had locked her arm in her mother`'s,
and their two heads being drawn very close together,
as she led her aside into a gravel walk,
no doubt remained but that all that was to be told would
be imparted before Miss Robson had time to interpose.

As matters were so far hopeless in relation to Harriet,
she was desirous of turning them to better account with Charlotte; who,
though sufficiently dissatisfied with the way in which her sister had been treated,
was nevertheless in a disposition to listen with
proper respect to what her governess wished to say.

"`You have now an opportunity of learning a lesson, Charlotte,`" said Miss Robson,
as she motioned her to take a seat beside her on a garden bench,
"`which you will often have occasion to remember; and that is,
to let a little time elapse before you speak or act, whenever your temper is ruffled.
It is like putting to sea in a storm, to attempt anything at such times.
Now our dear Harriet is rushing upon the relief of her mind,
and seeking present ease by pouring out her pent up feelings in her mother`'s ear.
And what will be the consequence?
She will get the pity for herself that she wants.
So far the bad, selfish nature will have its will.`"

"`Is it a bad and selfish nature, dear Miss Robson, that Harriet is yielding to?`"
inquired Charlotte.
Does she not think it right that mamma should know what
an ungrateful and ill-behaved woman Mary Hayes is?`"

"`It would be more right for Harriet to remember that blessed counsel of the apostle,
which she has heard very often, and, I believe, learnt by heart very often, '`Brethren,
if a man be overtaken in a fault, you which are spiritual,
restore such a one in the spirit of meekness; considering yourself,
lest you also be tempted.
This would be the right thing for Harriet especially to do,
who is so exceedingly liable to be tempted with a violent spirit herself.`"

"`But what will be the consequences you were speaking of, Miss Robson?`"

"`I think it likely that they will be such as to
occasion a great deal of pain and remorse to Harriet;
for the probability is, that the poor woman, Mary Hayes, when a cooler moment comes,
will be extremely sorry for what she has said, and will wish it could be all unsaid.
She will naturally dread what it may lead to.
She will fear that, if repeated to Mrs.
Allen or your papa,
it may cause them to be so much displeased as to withdraw all other favours from her,
as well as this pension that is now taken off, and under these feelings,
she will lose no time in coming to the Rectory to apologize to Harriet,
and perhaps to me,
and most likely to entreat of us to forbear acquainting your parents.`"

"`Oh how sorry I should be if that were the case,`" said Charlotte.

"`There would be no help for it now,`" returned Miss Robson, "`for Harriet has,
undoubtedly, by this time, related the matter to your mamma,
and related it also under all the strong excitement which
could give a heightened and aggravated colour to it.`"

I can see now,`" said Charlotte, after a few moments silence, "`I can, indeed,
see now how much better it is to let a little time elapse,
than to speak at the time when we are angry.
Oh how sorry Harriet will be by and by, if Mary Hayes should come and apologize;
how sorry she will be for being so hasty.`"

"`It is in this way that rash and impetuous persons must be taught,`" said Miss Robson,
even in the same way as Gideon taught the men of Succoth,
'`with briars and thorns;`' however, dear Charlotte, as you, happily,
are not implicated in her present error, but are in the place of a calm bystander,
endeavour to learn your lesson from it in a more peaceful way.
It may be comprised in few words, and those very precious ones--"`Stand still,
and see the salvation of the Lord.`"
When agitation of any sort disturbs you, even of a pleasurable kind, stand still,
that is, endeavour not to act or speak till your emotions have subsided;
for the probability is, that at such times, we shall, by acting or speaking,
place ourselves in circumstances that are either foolish or sinful; and such as,
in cooler moments, we should be glad to have escaped.
If it is matter of pleasure that is before us,
the vain nature will run out into nonsense, just as Johnny jumps and capers,
and does ridiculous things, because he is promised some enjoyment; and,
if it is of a dark and painful kind, it will spend itself in fury, which,
besides bringing folly, brings sin and shame upon us.
Therefore, when highly pleased, or highly pained, dear child, be still;
and you will feel something better than yourself, and your own wild feelings,
which is saving you from such words and actions,
as in a little time you will be truly thankful to see that you were saved from.`"

When grief or joy shall press upon you hard,

Be then especially upon your guard;

Then is most danger of not acting right,

A calmer state will give a surer light.^
footnote:[Dr. John Byrom.]

Just as Miss Robson had predicted, the matter turned out.
The dinner cloth was no sooner removed, than Harriet was summoned out of the room,
as Mary Hayes wished very much to speak with her.
Her passion had subsided, and she was now as placable and mild, as she had,
a short time before, been injurious and angry.
But, it was too late to ask that Mr. and Mrs.
Allen might not be informed of her misconduct.
Harriet, had left nothing untold upon that point.
Following the hasty and impetuous impulse which urged her, as Miss Robson had said,
to rush upon the disclosure of her feelings as soon as she saw her mother,
she had as she now perceived, done the poor woman a great injury; for Mrs.
Allen was so much displeased with what had been related to her,
that she repeated it to Mr. Allen at dinner, and he on his part was equally dissatisfied,
so that poor Mary had sufficient cause to fear that her
ill behaviour would produce her some serious consequences.

Harriet, sincerely sorry for what she had done to aggravate the affair,
readily forgave the affront that had been offered to herself,
and promised to speak to Miss Robson to try and compose matters.

I dare say, my young readers, you will be able,
without many words of description from me,
to conceive some idea of the painful humiliation of Harriet`'s mind,
as she went to Miss Robson, and related Mary`'s penitence,
and spoke of her own regret for the rashness whereby she had rendered that penitence,
perhaps, unavailing.
Indeed, she was truly brokenhearted and contrite for what she had done, and promised,
with an earnest desire that she might be enabled to keep her word,
that she would follow the counsel of her much-respected friend and governess,
now very weightily enforced upon her;
and whenever she was rushing upon a hasty disclosure of her feelings,
that she would try to be still, and let a little time elapse,
before she either spoke or acted.

"`You must learn how to bear to be uncomfortable a little while,
Harriet,`" said Miss Robson.
"`It is this hurrying out after something to please, or something to comfort,
that does the mischief.
When you are affronted, bear it; at all events, bear it for a time;
don`'t be in a hurry to revenge yourself.
If you have been really ill used, depend upon it, you will be righted at the right time,
and in the right way; but to be in haste about righting yourself,
clearly shows that you are in the wrong there.
'`In your patience, posses your souls.`'`"

I may just add, in concluding this chapter, what you will be glad to hear,
that Miss Robson`'s calm and judicious representations of the case,
and Harriet`'s regret for her own haste and passion,
had their due effect upon Mr. and Mrs.
Allen; and that poor Mary Hayes was forgiven her impetuosity, and restored to favour.
