== Dialogue II.

[quote.section-epigraph, , Ps. 119:37]
____
_Turn away mine eyes from beholding vanity._
____

[.discourse-part]
_Mamma:_ When you were wishing, last night, that you were old enough to sit up to supper,
Mary, I did not say any thing in reply,
because it was too late to enter into conversation then;
but now I should like to hear if that is the only thing for which you wish to be older.

[.discourse-part]
_Mary:_ Oh no, mamma!
There are a great many other things for which I wish to be older.
I should like to be as old as you are, that I might do as you do.

[.discourse-part]
_Mamma:_ You would like, I suppose, to dress like me.

[.discourse-part]
_Mary:_ Yes, I think I should.

[.discourse-part]
_Mamma:_ And to order the dinner, and direct the servants what to do.

[.discourse-part]
_Mary:_ Oh, yes, mamma; I should like that very much indeed.
I often play at ordering the dinner.

[.discourse-part]
_Mamma:_ I suppose you then try to fancy that you are me, and that you are doing as I do.

[.discourse-part]
_Mary:_ Yes, mamma; it is so pleasant to think I am you.

[.discourse-part]
_Mamma:_ Well, my dear, I should be sorry to disturb you at your play,
because it is necessary, at your age, that you should be amused; but, nevertheless,
I must tell you, that this desire of being older than you are,
and of fancying yourself some other person than the little girl you are,
is a wrong feeling to encourage.

[.discourse-part]
_Mary:_ Oh, mamma, how can it be wrong to wish to be as old as you are?
because, if I was as old as you, I should know as much as you do,
and then you would not have to take the trouble of teaching me.

[.discourse-part]
_Mamma:_ But I do not recollect your wishing to be older,
in order that you might be wiser than you are at present.
I think it was, that you might dress like me, and direct the servants; and, in short,
that you might be of more consequence than you are now.
You do not like being passed over as a child.

[.discourse-part]
_Mary:_ I do not think I want to be of consequence, mamma:
I do not think I care about being thought a child.

[.discourse-part]
_Mamma:_ You may not be aware of it, my dear;
but that is the chief desire of your heart in wishing to be older;
and that is the feeling which it is wrong to encourage.
Little girls and boys are very apt to be extremely vain and ambitious.

[.discourse-part]
_Mary:_ What is it to be ambitious, mamma?

[.discourse-part]
_Mamma:_ To be ambitious, is to be anxious for notice.
Did you never see any children fond of being noticed?

[.discourse-part]
_Mary:_ Oh, yes, mamma.
Mary Ann Duff is ready to cry when she comes into the drawing-room and nobody notices her.
Is not that silly?
I am sure I should not care about it!

[.discourse-part]
_Mamma:_ Well, she is a very pretty little girl,
and I dare say has been too much used to be noticed.
But you look rather grave, dear child.
Are you tired of talking with me?

[.discourse-part]
_Mary:_ Oh, no, mamma, I am not tired.
But I am so surprised to hear you say that Mary Ann Duff is pretty!

[.discourse-part]
_Mamma:_ Do you not think, dear Mary, if, instead of saying, "`I am so surprised, mamma,
that you think Mary Ann Duff pretty,`" you were to say,
"`I am so vexed,`" you would speak the truth?
Come, think a little.
Is it not so?

[.discourse-part]
_Mary:_ But you would laugh at me if I were to say so.

[.discourse-part]
_Mamma:_ Why do you think I should laugh?

[.discourse-part]
_Mary:_ Because it would be so silly to be vexed at that.

[.discourse-part]
_Mamma:_
You would feel quite ashamed that any body should suppose
you were vexed because Mary Ann Duff was praised,
would you not?

[.discourse-part]
_Mary:_ Oh, yes, mamma, indeed I should.

[.discourse-part]
_Mamma:_ Then, my dear, you see what a shameful thing it is to be anxious for notice?
Mary.
But, mamma, am I anxious for notice?

[.discourse-part]
_Mamma:_ Yes, dear child, quite as much so as Mary Ann Duff;
or you would not have been vexed to hear her praised.
Now you catch a glimpse of the darkness that is in your heart,
and also of the true light that shows the darkness, and leads to the right way out of it.

[.discourse-part]
_Mary:_ I do not understand you, mamma.

[.discourse-part]
_Mamma:_ Well, I will try and explain it; but I must first ask you a question,
which I hope you will answer truly, because all I have to say depends upon that.

[.discourse-part]
_Mary:_ Oh, mamma!
I am sure, then, I will answer truly: pray ask me.

[.discourse-part]
_Mamma:_ Were you not, then, vexed, very much vexed,
when I said Mary Ann Duff was a very pretty little girl?

[.discourse-part]
_Mary:_ Well, mamma, I think I was very much vexed; but do not laugh at me!

[.discourse-part]
_Mamma:_ You need not fear that, my child.
If I did not know of a remedy for your vexation, I should weep bitterly,
rather than laugh at it; but, happily for you, there is something very near you,
which can take away that evil, foolish feeling which vexed you.

[.discourse-part]
_Mary:_ What could it be that vexed me, mamma?

[.discourse-part]
_Mamma:_ Envy is the name of that bad feeling; it is a dark, ugly weed,
that is very apt to grow fast, if not plucked up as soon as we see it.

[.discourse-part]
_Mary:_ But can we always see where it grows?

[.discourse-part]
_Mamma:_ We should, if we were to attend to that which shows it to us.

[.discourse-part]
_Mary:_ What is that, mamma?

[.discourse-part]
_Mamma:_ The true light, which I spoke to you about yesterday.
This is the good thing which shows you that it is so shameful
to be vexed because you hear another person praised,
that you have cause to fear that every body who knew of your vexation,
would despise you for it.
It is this true light that makes you conscious that you deserve to be laughed at;
that is,
it makes you feel how mean and despicable it is to
grudge that another should be thought well of.

[.discourse-part]
_Mary:_ But, mamma, how does it show the way to get rid of this ugly feeling?

[.discourse-part]
_Mamma:_
Is it not enough that it tells you that there is a bad feeling present in your heart?
Suppose, whilst I am walking this evening past my neighbour Mrs.
Smith`'s house, I were to see a thief getting in at one of the windows,
and I were to go and tell her, there was a thief in her house;
do you think she would say "`Never mind; I do not care whether he robs me or not?`"

[.discourse-part]
_Mary:_ No, mamma, I think she would be very much obliged to you,
and would do everything she could to catch the thief.

[.discourse-part]
_Mamma:_ Well, what does this good feeling, that makes you ashamed of being envious,
so ashamed that you cannot speak of it,
for fear of being laughed at;--what does it do for you,
but tell you that there is a thief in your heart; a bad, wicked feeling,
that will rob you of everything that is kind and good, if you do not drive it out?
It will rob you of all love for your little friends; for how can you love Mary Ann Duff,
if you are vexed to hear her praised?

[.discourse-part]
_Mary:_ Oh, but, mamma, to be praised for being pretty!
I have often heard you say, it is such a poor thing to be praised for being pretty,
or being smart, or any thing of that kind.

[.discourse-part]
_Mamma:_ So I think it is.
Indeed it seems to me so poor a thing, Mary,
that I wonder how you can be vexed to hear any little girl praised for her beauty!

[.discourse-part]
_Mary:_ Oh, mamma! you do turn me so inside out!

[.discourse-part]
_Mamma:_ That is just what I want to do, my dear;
I want you to see the inside of your heart.

[.discourse-part]
_Mary:_ It seems a very ugly one, I think.

[.discourse-part]
_Mamma:_ Indeed it is.
We are told in Scripture, that "`the heart is deceitful above all things,
and desperately wicked.`"
You see how deceitful yours is,
that it led you to think you did not want to be of consequence,
and that you were not anxious for notice, and, in short,
that you were quite free from vanity; whereas,
you now find that vanity is at the root of all this
evil feeling that we have been talking about;
for if you had no vanity, you would not want to be noticed;
and if you did not want to be noticed yourself,
you would not grudge to have Mary Ann Duff, or any one else noticed;
and if you had no vanity, you would not, in your play,
fancy yourself to be a person of importance,
and like to think you are ordering the dinner, and directing the servants, and so on.

[.discourse-part]
_Mary:_ But, mamma, why is that wrong?`"

[.discourse-part]
_Mamma:_ We will talk more upon that subject tomorrow.
We have spoken long enough about it now;
I would only add a few words respecting the true light, which shows the dark,
bad feeling.

[.discourse-part]
_Mary:_ If you please, mamma;
for I do not quite understand how it sends the bad feeling away.

[.discourse-part]
_Mamma:_ Well, suppose when I tell Mrs.
Smith that the thief is in her house, she were to say,
"`What shall I do to get rid of him?`"
and I were to reply, "`You are not able to drive him out yourself;
but I know a kind good friend,
who is strong enough to drive out a whole gang of
thieves;`"--what do you think she would do?

[.discourse-part]
_Mary:_ She would beg of you to bring that friend to her help,
or she would go and ask him herself to help her.

[.discourse-part]
_Mamma:_ How would she ask him?
Would it be in a cold, careless, indifferent sort of way,
or would it be in a very earnest manner?

[.discourse-part]
_Mary:_ Oh, very earnest!
She must wish to be helped to get rid of the thief, you know.

[.discourse-part]
_Mamma:_ Well, dear child, when the thief, Vanity, is in your heart,
robbing you of kind and amiable feelings, and filling you with very bad ones,
and thereby bringing a dark thunder-cloud over you, mind what the true light shows you,
and you will find it shows you this:--first,
that you have got the wicked thief in your heart: next, that you must be quiet and still,
and wait to see what is the best way of getting rid of him: thirdly,
that you can do nothing of yourself, towards driving him out; and lastly, that the good,
loving, tender Spirit of your Father, which is in heaven,
is the only conqueror of this thief; and he conquers him in this way,
by driving him out of your heart, and coming in there himself.

[.discourse-part]
_Mary:_ Oh, mamma! how sweet that must be, to have the good Spirit in my heart,
instead of the bad, dark, evil one.
But will he come of himself?

[.discourse-part]
_Mamma:_ No; you must ask for him; just as if Mrs.
Smith wants the good friend`'s assistance to drive out the thief, she must ask for it;
and this asking for the Spirit, is prayer;
and you are promised in Scripture that you shall not ask for it in vain.
Turn to the 11th chapter of Luke, verse 13, and read it to me.

[.discourse-part]
_Mary:_ "`If ye then, being evil, know how to give good gifts unto your children;
how much more shall your heavenly Father give the Holy Spirit to them that ask him?`"

[.discourse-part]
_Mamma:_ Then, dear child, you have but to ask for the help of this blessed Spirit,
to drive all evil out of your heart;
and this good Spirit will teach you how to pray for what you want;
because it will make you feel and see what it is you most stand in need of;
and often will it make you say, "`Turn away mine eyes, O Lord, from beholding vanity.`"
