== Dialogue VI.

[quote.section-epigraph, , Isaiah 1:3]
____
_The ox knoweth his owner, and the ass his master`'s crib;
but Israel doth not know, my people doth not consider._
____

[.discourse-part]
_Mamma:_ Now, Mary, I am ready to answer, as far as I am able,
the question you asked last night, which, if I remember right,
was an inquiry why your will required to be controlled.

[.discourse-part]
_Mary:_ Yes, mamma.
I wished to know why my will was so bad a one as always to want to be controlled.

[.discourse-part]
_Mamma:_ This question, my dear, leads us into very solemn subjects;
and therefore you must be very attentive and thoughtful,
and consider what you are going to say, before you make any inquiries respecting it.
All that I can tell, or you can learn about the cause of your will being a bad one,
is found in the Bible.
Do you not remember reading there, that "`God made man in his own image?`"

[.discourse-part]
_Mary:_ Yes, mamma; and commanded him not to eat of the fruit of the tree of knowledge;
for in the day that he eat thereof he should surely die.

[.discourse-part]
_Mamma:_ Yes; and he did die a very dreadful death.

[.discourse-part]
_Mary:_ Dear mamma, I thought he lived several hundred years, and had two sons, and...

[.discourse-part]
_Mamma:_ Stay; and let me explain what sort of death Adam died, when he disobeyed the Lord.
It was not the death of the body; but a far worse death.
His soul,
which was created in the image of God--that beautiful
image--__that__ was the part of him that died.
Hence it is, that all Adam`'s children have nothing of the image of God in them now;
but instead of it, the only image that is before their thoughts continually,
is their own.

[.discourse-part]
_Mary:_ Pray, mamma, will you tell me what an image means;
for I do not think I exactly understand you!

[.discourse-part]
_Mamma:_ Go and look in the glass, and tell me what you see.

[.discourse-part]
_Mary:_ I see myself.

[.discourse-part]
_Mamma:_ How so?
You cannot possibly see yourself; for you are standing before the glass,
and looking just the opposite way to that where the figure in the glass is looking?

[.discourse-part]
_Mary:_ Then what I see, mamma, is, I suppose, an image of myself.

[.discourse-part]
_Mamma:_ Exactly so.
It represents you to yourself.
It is your image; and you can very well understand the nature of this image,
and have great satisfaction (too much, alas!) in gazing upon it.
You are scarcely ever weary of looking how its hair curls, and how its...

[.discourse-part]
_Mary:_ Oh, mamma, I know this is very foolish: pray talk of something else.
I know now what an image is.

[.discourse-part]
_Mamma:_ You know what a human image is, dear child, which is the image you bear;
but I have no words capable of expressing to you what that image was which Adam bore,
before he disobeyed God and lost it.
It is sufficient to say that it was the image of God--all glorious, all beautiful,
all majestic, all divine!--so that he might be permitted, nay,
he was _created on purpose_ to delight in it; for when he delighted in this image,
he delighted in God, whom it resembled.
If we were not fallen and sinful creatures,
we should have no delight in any thing but God.
His will would be our will; and we should not know what it was to think about ourselves,
or care about ourselves.
But now we think and care about nothing else: our will is all for self.
It says, continually, what can _I_ get--give _me_ something--let _me_ be taken care of.

[.discourse-part]
_Mary:_ Oh, mamma, I do not think I am saying that always!

[.discourse-part]
_Mamma:_ Not with your lips, my dear.
But think a little,
and I believe you will find that self is the uppermost thing in your mind,
for the greater part of the day;
and it would be very troublesome to you and every body else,
if it were not kept under by the care and instruction of others; and in some measure,
I hope, by your own endeavours to resist it.
Still, with all the teaching you receive, and all the restraint which is put upon it,
your will finds it very hard to think upon God,
and still harder to take any delight in him.
Is not this the case?

[.discourse-part]
_Mary:_ Oh, mamma, I should be very wicked if I said no;
for I am afraid what you say is true.

[.discourse-part]
_Mamma:_ Do not be afraid of speaking the truth, dear child.
It is necessary that you should quite understand the great corruption of your heart,
or you will not be earnest in seeking its remedy.

[.discourse-part]
_Mary:_ Then there is a remedy, mamma!
Oh, I am glad of that!
Pray explain it to me.

[.discourse-part]
_Mamma:_ As soon as Adam lost his beautiful and godlike life,
it pleased his good Creator to make him a promise that the
seed of the woman should bruise the serpent`'s head;
which was as if God had said to him,
"`I will send you a friend that shall deliver you from this evil, serpent-like nature,
that you have brought upon yourself by disobeying my commands.`"
This great deliverer was not to come into the world
for several hundreds of years after that;
but some portion of his blessed spirit was given then to Adam,
as his help and deliverance from that evil nature
which he had got by indulging his own will,
and eating the forbidden fruit.

[.discourse-part]
_Mary:_ Oh, mamma, what a terrible punishment for such a little thing as eating some fruit!

[.discourse-part]
_Mamma:_ It was not what he did that made the greatness of his sin: it was the ungrateful,
rebellious selfishness which it betokened, that caused him to be so severely punished.
Suppose I were ten thousand times more kind and loving to you than I am,
yet my love would be nothing to the love that God bore to Adam;
but suppose that I were to give you permission to enjoy yourself, and play in the garden,
and that I had provided everything I could think
of for your pleasure and that I was to say,
"`You may eat what fruit you like, Mary; but do not eat of such a tree,
because what you gather there will poison you;`" and you
were to slight what I had provided for your happiness,
and take of the poisoned tree--would you not show a very wilful, selfish temper?

[.discourse-part]
_Mary:_ Yes, mamma, I should deserve to be punished.

[.discourse-part]
_Mamma:_ But suppose it were possible for me,
not only to provide beautiful grounds for you to play in,
and pleasant fruit for you to eat;
but also to fill your mind with such delightful thoughts
as made you always good and always happy,
and some envious, wicked person came and persuaded you that you might be still happier,
and still better, and still wiser, if you were to eat of the forbidden tree,
would you not show a very covetous, greedy temper, as well as a very wilful one,
if you hearkened to him?

[.discourse-part]
_Mary:_ Yes, indeed I should.
I ought to be satisfied with being good and happy, and not want more than was given me.

[.discourse-part]
_Mamma:_ Then, if you found, as soon as you had eat of the poisoned fruit,
that your beautiful, happy, and good thoughts were gone, and you had got a set of dark,
covetous, greedy thoughts instead of them,
do not you think you would have just what you deserved,
and what you had brought upon yourself?

[.discourse-part]
_Mary:_ Yes, mamma: I should have nobody to blame but myself;
for I ought not to have listened to the wicked person
that would have persuaded me to disobey you.

[.discourse-part]
_Mamma:_ Then now you can understand why Adam`'s punishment was so great;
and he could not have had a greater, than to lose a blessed, happy nature,
and get an evil one instead; but, even in this unhappy condition,
it pleased the goodness of God to come to his help,
and to give him back a little portion of that blessed nature which he had lost.
It was put into his heart, and it is put into every body`'s heart,
to teach them what is good.

[.discourse-part]
_Mary:_ Then this is the true light,
and the good Spirit that we have been talking about so much, I suppose, mamma?

[.discourse-part]
_Mamma:_ Yes, dear child, this is the deliverer from evil, and the guide into all good;
who tells us when our will is a bad one, and who calls upon us to deny it.
If Adam had minded this teacher instead of the wicked serpent, who was the devil,
he would have escaped all the misery he brought upon himself and upon us also; for,
in consequence of his disobedience, we are all sinners,
being born in his image instead of the image of God.

[.discourse-part]
_Mary:_ But, mamma,
you said that this good deliverer came into the world
several hundred years after Adam sinned.

[.discourse-part]
_Mamma:_ Yes, this great deliverer was the Lord Jesus Christ,
who is called in Scripture the second Adam,
because he repaired all the mischief that the first Adam did.

[.discourse-part]
_Mary:_ How did he do that, mamma?

[.discourse-part]
_Mamma:_ By making the bad nature good again.
He became a man like Adam, and did as Adam ought to have done,
by perfectly obeying the will of God in all things.
But this subject is at present beyond your comprehension;
therefore we will only now speak of what, I think, you may be able to understand.
Let me ask you a few questions respecting what we have been conversing upon.
In whose image was Adam first created?

[.discourse-part]
_Mary:_ In the image of God, which was a beautiful and glorious image.

[.discourse-part]
_Mamma:_ How did he lose this image?

[.discourse-part]
_Mary:_ By following his own will, and disobeying God, by eating of the forbidden fruit.

[.discourse-part]
_Mamma:_ He had then got a life, and nature, and image of his own, instead of the life,
and nature, and image of God.
And was it a good nature that he had got?

[.discourse-part]
_Mary:_ No, a very bad one.

[.discourse-part]
_Mamma:_ Have we the same bad nature?

[.discourse-part]
_Mary:_ Yes, we are born in Adam`'s image.

[.discourse-part]
_Mamma:_ Can we ever hope to regain God`'s image which died in Adam?

[.discourse-part]
_Mary:_ Yes; there is a little portion of it given back to us, to show us what is good,
and to make us love it.

[.discourse-part]
_Mamma:_ What is it called?

[.discourse-part]
_Mary:_ It is called "`light.`"
It is "`the true light that lighteth every man that cometh into the world.`"

[.discourse-part]
_Mamma:_ Have you any of that light?

[.discourse-part]
_Mary:_ Yes, mamma.

[.discourse-part]
_Mamma:_ Then remember, dear child, to obey it; and above all things,
recollect that it calls upon you to deny the evil which you inherit from Adam.

[.the-end]
FINIS.
