== Preface

"`Make the tree good, and the fruit will be good also,`" says our blessed Lord.
It is not, therefore, by lopping the branches of corruption,
that the instructor of youth can hope to be of much service to his charge;
anymore than the physician, who merely attacked symptoms,
instead of going to the root of the disease,
could expect to see his patients restored to health.
That there "`is a balm in Gilead`"--that there "`is
a physician there,`" for the sin-sick soul,
the Scriptures of truth sufficiently testify;
and One not far distant from every one of us.
"`This commandment which I command you this day,`" says Moses,
in the authority of God "`is not hidden from you, neither is it far off, (Deut.
30:11-14.) But the word is very near you; in your mouth, and in your heart,
that you may do it.`"

To a distinct knowledge and consciousness, therefore, of this Word in the heart,
the attention of the child can scarcely too soon, and too earnestly be directed.
For this purpose this work has been published,
with a humble hope that some aid may be derived from
the mode of instruction found useful by the Author,
and which is presented here as hints for the educator to follow out, and enlarge upon,
as opportunity occurs;
for the most effectual teaching is that which springs from the occasion,
and which approaches the heart while the feelings are fresh and livingly excited.

If it should be objected,
that the view here taken is confined to the education of female youth,
it may be answered, that the general idea,
(which is all that the author aims to exhibit) is equally applicable to both sexes.
