== Dialogue I.

[quote.section-epigraph, , Ps. 43:3]
____
_O send out your light and your truth: let them lead me._
____

[.discourse-part]
_Mamma:_ If you wish to weed the garden, Mary, would you go to work at night?

[.discourse-part]
_Mary:_ No, mamma; because I could not see the weeds.

[.discourse-part]
_Mamma:_ Can you see any weeds in your heart?

[.discourse-part]
_Mary:_ I do not think that weeds grow there.

[.discourse-part]
_Mamma:_ Do not annoying and impatient thoughts sometimes sting you like nettles,
when you are told to do anything that you do not like to do; for instance,
when you have done your math wrong, and have to do it over again?

[.discourse-part]
_Mary:_ I do not feel very comfortable just then.

[.discourse-part]
_Mamma:_ And do you never feel as if you were pricked with thorns or briars,
when you see any of your young companions more noticed than you are?

[.discourse-part]
_Mary:_ I feel something like it.

[.discourse-part]
_Mamma:_ Are these feelings like pretty flowers, or are they like ugly weeds?

[.discourse-part]
_Mary:_ They are like very ugly weeds, mamma.

[.discourse-part]
_Mamma:_ Do you see how ugly they are while they are pricking and stinging you?

[.discourse-part]
_Mary:_ No, mamma; for if I did, I would soon pull them up, because they are so ugly.
I wonder why I do not see how ugly they are while they are giving me so much pain.

[.discourse-part]
_Mamma:_ Did you not tell me that you could not see the weeds in the garden at night?

[.discourse-part]
_Mary:_ But, mamma, is it night in my heart?

[.discourse-part]
_Mamma:_ When you are giving way to evil tempers and envious feelings,
you do the same thing to your mind that I would do to this room,
if I were to close the shutters.
If I were to do so, would I not prevent the sun from shining into the room,
and giving me light?

[.discourse-part]
_Mary:_ But, mamma, you puzzle me;
you talk about light and darkness as if I had both inside of me,
and as if it were sometimes day and sometimes night in my heart.
I can see day and night with my eyes; but how can I see what passes in my heart?

[.discourse-part]
_Mamma:_
You do not see what passes in your heart in the same
way as you see the difference between night and day;
but still you can as easily distinguish right from wrong in your heart,
as light from darkness in this room.
You see that you are doing wrong, do you not, when you are impatient, annoyed,
and envious?

[.discourse-part]
_Mary:_
Yes, mamma.

[.discourse-part]
_Mamma:_ And you see that you are doing right,
when you endeavour to keep down these evil tempers, and do not allow them to appear?

[.discourse-part]
_Mary:_ Yes, mamma, I can see this very clear now: so now, I suppose,
it is daylight in my heart, is it not?

[.discourse-part]
_Mamma:_ Yes; now the true light is permitted to shine; you are quiet, and humble,
and willing to be instructed;
and there are no shutters of evil tempers put up to darken your heart.

[.discourse-part]
_Mary:_ Mamma, what do you mean by the true light being permitted to shine?
What is this true light?

[.discourse-part]
_Mamma:_ Look at the first chapter of the gospel of John, and the ninth verse,
and read it to me.

[.discourse-part]
_Mary:_ "`That was the true light which enlightens every man that comes into the world.`"

[.discourse-part]
_Mamma:_ This was spoken of Jesus Christ, my child; and now turn to the twelfth chapter,
and read at the forty-sixth verse, what He Himself says about it.

[.discourse-part]
_Mary:_ "`I have come as a light into the world,
that whosoever believes on Me shall not abide in darkness.`"

[.discourse-part]
_Mamma:_ Now turn to the third chapter,
and read the nineteenth and the two following verses.

[.discourse-part]
_Mary:_ "`And this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil;
for everyone that does evil hates the light, neither comes to the light,
lest his deeds should be reproved; but he that does truth comes to the light,
that his deeds may be made manifest that they are wrought in God.`"

[.discourse-part]
_Mamma:_ From these texts of Scripture, you learn several important things; and first,
you learn that there is a true light enlightening the heart of every person in the world;
and that this true light is the Lord Jesus Christ, the Saviour of sinners.
Next, you are told, that those who believe in this light do not abide in darkness.

[.discourse-part]
_Mary:_ Do these never have any darkness in their hearts, mamma?

[.discourse-part]
_Mamma:_ When the darkness comes, they do not abide in it; that is, when evil tempers come,
like a dark cloud over their hearts, they run away from them.
They get into shelter as fast as they can.
They do not abide in the darkness,
anymore than you would stay in the garden during a thunderstorm.

[.discourse-part]
_Mary:_ What shelter do they get into, mamma?

[.discourse-part]
_Mamma:_ They shelter themselves in the light which they believe in; that is,
they keep close to its directions; and whenever dark and cloudy tempers arise,
the light always directs them to be quiet and still, and neither say nor do anything,
till they feel calm and composed.
Have you never gotten into trouble by showing that you were in a fit of emotion?

[.discourse-part]
_Mary:_ Yes, mamma.
I remember, once, when I was ordered to do some work, when I wanted to be at play,
I was so angry that I twitched my thread till I broke it,
and you sent me out of the room.

[.discourse-part]
_Mamma:_ You can see now that you were wrong in giving way to this dark and violent temper;
and that, if you had been patient and obedient to your instructors,
you would have escaped pain and disgrace, and would not only have been a much happier,
but also a much better child.

[.discourse-part]
_Mary:_ Oh yes, mamma; I see that very plain.

[.discourse-part]
_Mamma:_ You have something in you, then, which shows you what is good.
It makes good manifest to you.
Now the Scripture says "`whatsoever makes manifest is light.`"
(Eph.
5:13.) Therefore, this something, which shows you what is good, is light.
It is the light of God`'s good Spirit shining in your heart,
and showing you that you ought to obey your instructors.
It shows you, also, that it is wrong to allow yourself to get into a fit of emotion;
therefore you are not to put yourself in that state; for if you do,
you turn away from the light, and go into very great darkness.
But persons who will not control their evil tempers, do not turn to this light,
as you are told in one of the texts you read to me: "`He that does evil,
hates the light;`" that is, he hates to see that he is in the wrong.
"`But he that does truth,`" that is, the person that truly fears to offend the Lord,
and in all things tries to please Him,
such a one "`comes to the light:`" he comes to quietness, patience, meekness, and prayer;
all of which, the light teaches him to love; and so he says, very often, to the Lord,
"`O send out your light and your truth, and let them lead me!`"
