== Dialogue III.

[quote.section-epigraph, , Psalm 51:10]
____
_Create in me a clean heart, O God, and renew a right spirit within me._
____

[.discourse-part]
_Mary:_ Will you tell me today, mamma,
why it is wrong for me to play at ordering the dinner, and pretending to be you?

[.discourse-part]
_Mamma:_ Yes, dear child; but in the first place,
I would ask you a few questions on the subject.
How is it, that every now and then, while you are playing at this sort of make-believe,
you turn round to see if I am watching you; and if you think that I am,
you look silly and ashamed?
Why is this?
You do not get embarrassed and attempt to laugh when you
catch my eye while you are playing with your puzzles,
or putting your maps together.

[.discourse-part]
_Mary:_ Because I do not mind your looking at me then, mamma.

[.discourse-part]
_Mamma:_ But you do mind my watching you at the other?

[.discourse-part]
_Mary:_ Yes, I do not like it.

[.discourse-part]
_Mamma:_ Why do not you like it?

[.discourse-part]
_Mary:_ Because I am afraid you will laugh at me.

[.discourse-part]
_Mamma:_ Why would I laugh at you, dear?

[.discourse-part]
_Mary:_ You would think it so silly.

[.discourse-part]
_Mamma:_ But do I think it silly when you are playing ball,
or running with your hoop around the garden, or skipping rope,
or when you are engaged in many other games that I could name?

[.discourse-part]
_Mary:_ Oh, no, mamma, those are not silly things.

[.discourse-part]
_Mamma:_ But it is silly, you think, to pretend to be me, or anybody else but yourself?

[.discourse-part]
_Mary:_ I do not know that I ever thought about that.

[.discourse-part]
_Mamma:_
But you are sure that you do not like me to see you when you are pretending to be me?

[.discourse-part]
_Mary:_ Oh, yes, mamma!
I am quite sure I do not like that.

[.discourse-part]
_Mamma:_ Well, my dear,
I think that you may take it as a sign that there
is something wrong with such a form of play,
if you dislike to be caught at it.

[.discourse-part]
_Mary:_ What is it, mamma, that makes me dislike to be caught at it?

[.discourse-part]
_Mamma:_ It is the good feeling that I want you to observe, and to pay attention to.
It is, in short,
the true light that shows you something of the foolishness in such a form of play;
and foolishness, even in a child, is a thing that must be kept under as much as possible.
You do not like to be foolish, do you?

[.discourse-part]
_Mary:_ Oh no, mamma;
it is because people think children are foolish that I want to be like a woman.

[.discourse-part]
_Mamma:_ I do not think children are foolish because they are children,
but because they have a foolish nature.

[.discourse-part]
_Mary:_ Did you have a foolish nature, mamma, when you were a little girl?

[.discourse-part]
_Mamma:_ Yes, my dear; and I have got the same nature now; only the good Spirit,
the true light, shows me when that nature troubles me,
and then I turn away from it as quickly as I can.

[.discourse-part]
_Mary:_ But, mamma, you never play at make-believe, and pretend to be somebody else.

[.discourse-part]
_Mamma:_ The foolish nature does not act in that way with me now,
because I am too old to play as you do;
but it would fill my head with many vain and idle notions about myself,
if I would let it.

[.discourse-part]
_Mary:_ Has everybody got that foolish nature, mamma?

[.discourse-part]
_Mamma:_ Yes, and it is that which makes them act so foolishly.
Little girls that have no watchful mother or teachers to warn them of the danger of it,
as I am now doing to you, are without any sense of their real state.
They pretend to be somebody important, till they really think they are so;
and so they grow up to be vain, conceited girls,
wondering why everybody does not admire them as much as they admire themselves.

[.discourse-part]
_Mary:_ I think, mamma, I will never play at make-believe any more.
It certainly is a very foolish thing.

[.discourse-part]
_Mamma:_ It is not the playing at it, dear child, that you must first give up,
but rather that which causes you to play in this manner.

[.discourse-part]
_Mary:_ What is that, mamma?

[.discourse-part]
_Mamma:_ The vain mind, my dear, the foolish nature, the evil part, the dark,
ugly weeds which we have said so much about;
these are what must be taken out of your heart.
Now, the true light always shows you when and where they spring up,
and makes you feel ashamed of them.
Pay close attention to feelings of shame, for they generally come from the good Spirit.
Do you know what I mean, when I tell you to pay attention to feelings of shame?

[.discourse-part]
_Mary:_ I think I do, mamma.
You would have me give up anything I was about to do,
if I felt that I would be ashamed anybody might see me doing it.

[.discourse-part]
_Mamma:_
Yes, that was my meaning.
For instance, if I were to come into the room and find you opening my drawers,
or looking into my papers, or taking any cakes or candies off the table,
would you not feel ashamed?

[.discourse-part]
_Mary:_ Oh, yes, mamma, very much ashamed.

[.discourse-part]
_Mamma:_ Why would you be ashamed?

[.discourse-part]
_Mary:_ Because you would think me so sneaky.

[.discourse-part]
_Mamma:_ You would not like to be thought of as sneaky, I suppose?

[.discourse-part]
_Mary:_ Oh, no, I could not bear it.

[.discourse-part]
_Mamma:_ Why would you dislike so much to be thought of as sneaky?

[.discourse-part]
_Mary:_ Because it is such a disgraceful thing.

[.discourse-part]
_Mamma:_ But suppose you were quite sure I was out of the house,
and there was no danger of your being seen by anyone;
and you then felt a wish to look into my drawers, or read my papers, or take a cake,
or anything of that sort; would you think it a disgraceful thing to do?

[.discourse-part]
_Mary:_ I do not think I would be so much ashamed, mamma,
if I was quite sure I would not be seen.

[.discourse-part]
_Mamma:_ There is no shame, then, in prying into other people`'s concerns,
or taking what does not belong to you, if you are not seen doing it?
Is that what you mean to say?

[.discourse-part]
_Mary:_ Oh, no, mamma!
Those are very wrong things to do, whether anyone sees me do them or not.

[.discourse-part]
_Mamma:_ Then should you not be as much ashamed to do them when you are alone,
as you would be if anybody saw you?

[.discourse-part]
_Mary:_ Yes, I think I ought to be.

[.discourse-part]
_Mamma:_ Do you think you are ever alone?

[.discourse-part]
_Mary:_ Oh, yes, mamma, I know I am, very often.

[.discourse-part]
_Mamma:_ I do not mean alone, as to having nobody with you that your eyes can see;
but I mean, is there ever a moment of your life in which someone,
and that a very Great One, is not beholding you?
If you think there is, you are greatly mistaken.
Turn to the hundred and thirty-ninth Psalm, and read me the first four verses.

[.discourse-part]
_Mary:_ "`O Lord, You have searched me and known me.
You know my sitting down and my rising up; you understand my thought afar off.
You comprehend my path and my lying down, and are acquainted with all my ways.
For there is not a word on my tongue, but behold, O Lord, You know it altogether.`"

[.discourse-part]
_Mamma:_ Thus you see, my child, that you are never alone;
and if you would be ashamed that I, or any of your fellow creatures,
would find you doing any sneaky, disgraceful, or foolish thing,
how much more cause have you to shrink from being
found guilty of disgrace and folly and deceit,
in the sight of a pure and holy God!
It is His divine and good Spirit in your heart that
makes you sensible of what is corrupt and unworthy.
Therefore, always attend to it, with reverence and humility;
and when you are tempted to do anything wrong,
do not ask yourself whether you should be ashamed if I should find you doing it;
but ask yourself, am I ashamed that God should see me do this?
And as the cause of all evil is in the heart,
and all vain and sinful thoughts rise up there,
let this short and good prayer be often in your mind; "`Create in me a clean heart,
O God!
And renew a right spirit within me!`"
