== Dialogue V.

[quote.section-epigraph, , Matt. 16:22-23]
____
__Then Peter took Him aside and began to rebuke Him, saying,
'`Far be it from You, Lord; this shall not happen to You!`'
But He turned and said to Peter, '`Get behind Me, Satan!`'__
____

[.discourse-part]
_Mamma:_ You were wishing, yesterday, to know, what was meant by denying ourselves, Mary.
I think I can give you some idea of it, by something that happened today.

[.discourse-part]
_Mary:_ If you please, mamma; though I cannot recollect anything particular happening today.

[.discourse-part]
_Mamma:_ Do you not remember the postman bringing me a letter,
just as I was about to hear you read and say your lessons this morning?

[.discourse-part]
_Mary:_ Oh, yes!
And I did so want you to open it.

[.discourse-part]
_Mamma:_ Yes, you wanted me to open it.
But why?
What could it signify to you whether it was opened or not?
It was not written to you.

[.discourse-part]
_Mary:_ Oh, no, mamma, I know that.

[.discourse-part]
_Mamma:_ But nevertheless you felt a great curiosity to know what was in it,
and who it came from.
Was this not the case?

[.discourse-part]
_Mary:_ Yes, mamma.

[.discourse-part]
_Mamma:_ Well, if you felt a great desire to know what was in it,
though you had nothing at all to do with it,
do you not think I must have desired it a great deal more?

[.discourse-part]
_Mary:_ Oh, yes, mamma.
I wondered what could be the reason why you let it lie upon the table,
all the long time that I was reading and saying my lessons.

[.discourse-part]
_Mamma:_ I was denying myself.
I would have liked very much to have read it;
but I had something else just then to attend to, and so I said to myself, "`No,
you must wait.`"

[.discourse-part]
_Mary:_ But, mamma, could you not have put that "`something else`" by, until another time?

[.discourse-part]
_Mamma:_ Certainly, I could have done so; but then I would have done wrong in several ways.
In the first place, I would have disobeyed the light,
which showed me that my duty then was to hear you read and say your lessons.
It also showed me that by reading the letter,
I would have been gratifying a very vain and wrong curiosity in you,
which made you so anxious to have the letter opened,
that you could scarcely attend to your lessons, but kept eyeing first the letter,
and then me, in hope that you could obtain some information about it.
This wilful curiosity in you, the light showed to me,
and also showed me that I ought to deny and disappoint it.

[.discourse-part]
_Mary:_ Oh, mamma!
You could see that I was wanting you to open the letter?
Well, I thought you never could see that.
I thought I kept it to myself.

[.discourse-part]
_Mamma:_ No, my dear.
Happily for little folks of your age,
it is not very difficult to know what they are wanting.
But to go on with what I was saying; this conduct which you saw in me this morning,
enables you to understand something of what is meant by denying ourselves.

[.discourse-part]
_Mary:_ Yes, mamma, I can understand what is meant by denying ourselves;
but I do not quite see why we should do it.

[.discourse-part]
_Mamma:_ Suppose I took you with me into a baker`'s shop,
and you were to ask me to let you have cookies, and cakes, and pies,
and anything that you desired; do you think I should indulge you?

[.discourse-part]
_Mary:_ No, mamma, I know you would not.

[.discourse-part]
_Mamma:_ Why should I deny you these things?

[.discourse-part]
_Mary:_ Because they would be bad for me.

[.discourse-part]
_Mamma:_ But I suppose you would like some of them very much, if you might have them?

[.discourse-part]
_Mary:_ Yes, I think I would.

[.discourse-part]
_Mamma:_ And yet you are quite satisfied to go without them,
and to think that I know best what is good for you?

[.discourse-part]
_Mary:_ Oh, yes, mamma.

[.discourse-part]
_Mamma:_ Well, then, my dear child,
if you can trust your earthly parent in directing you for the best,
how much more should you obey the commands of your heavenly Father;
and when He requires you to deny yourself,
how much more should you submit to Him without questioning "`why?`"
But though it may be difficult for you, at your age,
to understand the full purpose of the command to take up your cross and deny yourself;
yet you must surely have learned enough from these conversations we have had,
to see what a vain, silly, and selfish little creature you would be,
if you were never forced to control your own will,
but might do as you liked upon all occasions.

[.discourse-part]
_Mary:_ But why is my will such a bad one, mamma, that it always needs to be controlled?

[.discourse-part]
_Mamma:_
This is a question which would lead us into a longer
discussion than would be desirable at this late hour.
Tomorrow, if permitted, we will resume the subject.
Only let me point out to you a striking passage in Scripture
which plainly shows how repulsive to the blessed Jesus,
was any attempt to persuade Him from suffering pain and denying Himself;
for we must always suffer some pain in denying ourselves.
You remember that Peter was one of His favoured disciples; he,
with James and John usually accompanied him when others were not so privileged.
Yet, when Peter would have had him to avoid the sufferings that awaited Him,
saying to Him,
(no doubt in that coaxing sort of way which our evil nature likes,) "`Far be it from You,
Lord; this shall not happen to You;`" the meek and lowly Jesus, with holy indignation,
spurned him away with this severe rebuke: "`Get behind me, Satan!`"
Not Peter, His friend and disciple; but Peter,
then so strongly under the influence of a false feeling,
that he deserved and received the name of Satan!
