== Chapter II. The Governess.

For the first three weeks after Gertrude`'s arrival,
there was little going on in the way of discipline or instruction among the young people;
as during the greater part of that time Mr. Allen was absent in London upon business;
and when he was not present,
the only restraint that appeared to be felt by the two little girls was entirely removed.
They did what they liked with their mamma;
and although she was frequently heard in the course of the day, saying, "`Now,
my dear Harriet, don`'t do so,`" or, "`Charlotte,
I really will not allow this,`" it cannot be said that she was minded; indeed,
her indulgence had produced so much disobedience,
that she herself spoke her wishes and desires only
as if she knew it were the right thing to utter them,
but not as if she expected they were to be attended to, and obeyed.
Noise and confusion, banging of doors, tossing down stools,
cluttering chairs and tables with doll`'s clothes, toys, and all sorts of rubbish,
wrangling and quarreling, and then making up and wildly laughing,
seemed to be the chief occupation of Harriet and Charlotte Allen.
To this sort of activity was occasionally added the playing of tricks on Gertrude,
hiding her doll, or sometimes hanging it by a string to the mulberry tree;
filling her little cradle with stones, broken sticks, dried leaves,
and various other such things, flinging her balls over the hedges,
and many pranks of the like nature,
which were all very hard for a mild-spirited little girl like Gertrude to bear.

Her chief recourse at these times was to get by the side of Sarah in the nursery,
where she was always sure of being protected,
and allowed to follow her little quiet ways of amusing herself without interruption.
Here, too, she found an unfailing source of delight,
in the intimate friendship she was daily forming with little Johnny Allen;--a fine healthy,
happy child, who was just beginning to want a great deal of amusement and attention.
Happy was Gertrude in bestowing both, as she sat by his side on the carpet;
and happy was Sarah (who was no longer young) in being spared
the difficult task of having to stoop down and follow the
fancies of a sprightly child,
wanting everything it beholds, only to have the pleasure of throwing it upon the ground,
and giving others the trouble of picking it up again.
Satisfied in the attention of her young helper,
and keeping a watchful eye over both parties,
the nanny sat at her work-table while Gertrude and Johnny, amusing and amused,
enjoyed life more innocently than most people during Mr. Allen`'s absence.

At length the time approached for his return;
an event that was anticipated with a variety of feelings
by the different members of the family;
for I must inform you, that he was not to return alone,
but was to bring with him a lady named Miss Robson, who, in compliance with his wishes,
had consented to undertake the office of governess to his daughters.
I shall give you a little description of this lady,
so that you may form some idea of one about whom you will
hear a great deal throughout the course of our story.

Miss Robson was a person of good understanding and considerable accomplishments,
who had been accustomed to the tuition of youth from
the time that she was eighteen years of age;
and as she was now thirty-eight,
you will suppose that during so long a period as twenty years (in which she had
learned what it was to deal with the tempers and habits of the young),
she had formed a pretty correct judgment as to the best method of managing them.

In fact, it was owing to the high opinion he entertained of her sense and judgment,
(for she was a distant relation of his,
and he had known her many years) that Mr. Allen had
engaged her services as governess to his little girls.

Many individuals had, at different times, filled that station in his home,
but none of them had stayed longer than a few months.
The wild and ungoverned tempers of the children,
and the injudicious indulgence of their mother,
had rendered it so difficult a task to attempt the right education of them, that,
after a short effort,
it was usually abandoned by their instructress for something
that promised her a better recompense for her efforts.

It may seem strange that so good a man as Mr. Allen
would not have been able to regulate his family better;
but the fact was, that in attending to the duties of his parish,
and other occupations connected with his office,
his time was so fully occupied that he was in a great measure compelled
to leave the management of his children to their mother;
who, besides her fault of too much indulgence in her conduct towards them,
was often very unwell,
and unable from weak health and spirits to control them as they required.
Added to these circumstances,
there was another consideration which had some effect upon both parents,
who were each of them very tender-hearted people, and as you may suppose,
dearly loved their children.
This was their having lost several children in their infancy;
which made them cling with somewhat of "`inordinate affection`"
to those whom it had pleased Providence to spare.
Oh, dear children, how little do you know,
and therefore how little do you (generally speaking)
consider what your parents experience on your behalf!
The dutiful attention that you owe them, however faithfully paid,
can scarcely equal the anxious cares, and various hopes and fears,
which they have been made to suffer on your account.
This is especially true during the tedious and sometimes
sickly period of your infancy and early childhood,
when you had no ability to understand or care for their sorrows;
but which was to them a season of love and tender watchfulness,
that prompted their constant endeavors to ease and
bear the burden of your smallest discomfort.
Oh, if anything should shock our feelings,
and create sensations so revolting that they border upon horror,
it is to witness parents treated with disrespect or unkindness
by the very child that they have carried in their arms,
pressed to their hearts, nourished and cherished, and, as far as human means allow,
endowed with all the comforts and advantages that a child can possess.

But I must not lead you to suppose that the case of Harriet
and Charlotte Allen was as sad a case as this.
What it might have been if they had been allowed to continue
a few years longer in their present indulged condition,
with their high spirits and wild tempers as much uncontrolled as they were now,
we have no power to predict.
But happily for them,
a strong restraint to their dangerous course was now about to be given,
in the steady and wholesome discipline of Miss Robson.

This lady, as I have already told you,
had been accustomed to the care of children from her youth,
having been educated with a view to obtaining her livelihood in that way.
She was, in the truest sense of the word, a Christian;
one who feared God and loved righteousness; and as such,
she took little part or pleasure in the vanities and customs of the world.
Perhaps to some it may seem that she had no great merit in denying such things; since,
from her situation as a governess,
she was not likely to have many temptations to pursue them.
But, you must remember,
that it is not always the _doing or not doing_ of this or the other particular thing,
that marks our character and shows what we really are in our hearts.
For, on the one hand, there are some who unwillingly participate in worldly pursuits,
merely because they are placed in circumstances where
they are not able to follow their good inclinations.
And on the other hand,
there are many more whose _heart and will desire_ to partake of and follow worldly desires,
but who are in situations where they are forced to forgo them.
Now, dear children, do you not see, that those persons who would if they could be wild,
worldly, fashionable, "`lovers of pleasure more than lovers of God,`"^
footnote:[2 Timothy 3:4]
really _are_ all of this in the sight of that Great
and Holy Being who sees not as man sees,
for man looks at the outward appearance, but the Lord looks on the heart?
Indeed they are; for such as our will and wishes are, such we are;
regardless of whether or not we are able to gratify that will and those wishes.
And it was because Mr. Allen was sensible of this truth,
that he so earnestly desired to obtain Miss Robson`'s instructions for his children.
He knew very well,
that it would be of little use for a governess to talk against
the uselessness and vanity of a love of dress,
or of the sinfulness of the world and its pursuits,
if she herself was to be seen following these fashions as far as she could,
and taking more pains to impress upon the minds of her pupils a fear of being uncultured,
than of being ungodly.
His great anxiety, therefore,
was to place his little girls under the care of a
person who acted out the truths of the Bible;
not one who merely talked about them.

Such a person he fully believed Miss Robson to be.
He had known her from her youth,
and had seen her under very trying circumstances and difficulties
keep a steady hold of that faith in God which,
in the words of an old writer, "`anchored her immortal soul to its bishop.`"^
footnote:[Journal of George Fox]
Glad he was, therefore, to delay his return home in this visit to London,
that he might have the satisfaction of bringing her with him as a resident in his family.

Glad, I say, was Mr. Allen; but his wife was not altogether so glad.
Mrs. Allen was not a stranger to Miss Robson,
and though she could not help but respect her character,
she secretly wished that some person of a less rigid mode of thinking
and acting had been selected as the instructress of her children.
But, as she was always in the habit of deferring to the wishes and judgment of Mr. Allen,
and had long been aware that he was only waiting for the
liberation of Miss Robson from a previous engagement,
before proposing to her a place in his family,
she kept her thoughts upon this subject entirely to herself,
and prepared to receive her with the utmost kindness and good will.

To the little girls, Miss Robson was entirely a stranger; and various,
as you may suppose,
were the conjectures that passed between them as to who and what she would be like;
and whether or not they should like her as well as some of their former governesses.

They were standing at the nursery window, together with Gertrude,
when the carriage which had been sent to the neighboring town to meet the coach,
drove up to the door with their papa in it, and a lady who, of course,
was the expected Miss Robson.
Exclamations of joy at the sight of their father,
and of curiosity respecting the stranger,
suspended their occupation of putting on their afternoon dress.
Every head was making its way over another head to obtain a look at the newcomer.
Even little Johnny in the arms of Sarah, appearing in the rear,
seemed to think that something new and strange was taking place in the world.

"`Well, I never saw such a woman!`" was the first exclamation of Charlotte.
"`Why, she is dressed as plain as Sarah!`"

"`What an old straw bonnet!`" said Harriet, "`and, dear me, look how old she is!`"

"`I don`'t think I shall obey her very much,`" continued Charlotte.

"`She may know how to make you,`" said Sarah, "`And though she does wear an old bonnet,
you don`'t know what she has got under it.`"

"`I`'m sure she has got a very ugly face,`" replied
Charlotte in great displeasure at Sarah`'s remark.

"`Beauty is, what beauty does,`" said Sarah,
"`and I dare say we shall see in a little time, that she has got the true beauty.`"

Gertrude was silent during this dialogue, which was now ended by the voice of Mrs.
Allen calling to the children to come down and see their father,
and expressing wonder that they had not finished changing their clothes.

This was soon accomplished,
and Harriet and Charlotte hastened downstairs to give papa a kind kiss of welcome.
Gertrude was glad to wait behind a little while; for,
though no one in the house could more delight in the return of Mr. Allen,
she was in no hurry to make the acquaintance of one whom
she expected to find so intimidating as Miss Robson.
This expectation in little Gertrude had arisen not from any distinct
or precise description that she had received of this lady,
but only from the vague hints which Mrs.
Allen occasionally dropped during the last two weeks whenever
Harriet and Charlotte were more than commonly unruly;
and which hints always pointed to the probability
of their conduct requiring to be altered very shortly.

"`You will soon see what Miss Robson says to that!`" was her usual remark,
when her objections against this or the other action were disregarded by her daughters;
so that Gertrude had learned to attach some rather
alarming feelings to the very name of the new governess.

It was a great relief to her, therefore,
on going down with Sarah and Johnny to see Mr. Allen,
to find that Miss Robson had left the room to prepare for dinner;
and as the children had already dined,
Gertrude only waited to receive Mr. Allen`'s kind welcome,
and then retired with them to the nursery.

At the tea-table in the afternoon, they first met with Miss Robson,
whom they found sitting with Mrs.
Allen only,
Mr. Allen being engaged in his study with one of
his parishioners who had come upon business;
and, as he was likely to be detained some time,
he desired they would not wait tea for him.

"`Come in,`" said Mrs.
Allen, as Harriet, in her boisterous way, burst open the door,
and was then hastily retiring,
nearly overturning her sister and Gertrude who were just behind her,
and about to follow her into the room.

"`Come in, I say,`" repeated Mrs.
Allen, enforcing her command by rising from her chair and coming to the door,
in order to bring the little girls towards Miss Robson.
Having introduced them to her by name, and Gertrude as "`a little orphan girl from India,
placed under Mr. Allen`'s guardianship,`" she desired
them to take their places at the table.

Gertrude obeyed with her usual quietness,
and the other two with their usual bustle and noise.
As soon as they were seated, a deep silence ensued;
such as was sometimes the case in Mr. Allen`'s presence,
who always commanded it whenever rough or foolish behavior was in any way going on;
but which seldom occurred in his absence.
Not to do as they then desired, was something so strange to Harriet and Charlotte,
that they knew not what to make of it; and therefore, like all uncontrolled,
selfish children, who care for nobody`'s feelings but their own,
they began to look first at Miss Robson, and then at each other,
as if comparing their thoughts about her, then laughing,--and, in short,
behaving in so improper a way, that Mrs.
Allen was quite ashamed for them.
Finding at last that her many nods, and frowns, and shakes of the head were unheeded,
she spoke loudly, and told Harriet that "`if she did not cease such behavior,
she would send her out of the room.`"
This reprimand produced some reformation;
for Harriet knew that "`the sending out of the room`" never came except in extreme cases;
and that it involved not merely going out of that room, but generally going into another,
which was papa`'s study,
where she was certain of receiving reproof of a more
severe kind than mamma was in the habit of administering.
There was scarcely anything that Harriet and Charlotte really feared, and,
in a certain degree respected, more than their father`'s rebukes;
for though they were wild and rough tempered children, they were not without feeling.
And when Mr. Allen spoke, it was to the heart and to the conscience,
and they always understood what he meant,
and were deeply humbled by the consciousness of deserving it.

During the time that they had been behaving themselves so improperly,
Miss Robson had been forming an acquaintance with little Gertrude,
in whose mild countenance and gentle manners she saw so much that was engaging,
that she beheld with less concern than she otherwise might the ill behavior of her companions.
"`Here, at least,`" she thought to herself,
"`I may hope for a pupil that will afford me some fruit for my labors!`"
Nor was the good lady discouraged by what she saw in the other two little girls;
for she perceived at once, from Harriet`'s manner at her first coming into the room,
and her mother`'s being obliged twice to speak her wishes,
and even to rise from her seat to enforce obedience to them on that occasion,
that these poor children labored under the severest of all disadvantages--even
that of having been allowed to have their own way,
and not to obey when they were reproved.
It was not the first time by many,
that Miss Robson had been called upon to deal with children like this;
and when she considered their young ages,
and the hope that they were not yet past being brought under proper control,
she felt only stronger desires and more fervent breathings
in her heart to the Father and Giver of all Goodness,
that, aided by His wisdom and power,
she might be instrumental in reclaiming them from their present dangerous condition.

=== Chapter III. The School-Room.

As we have said,
ever since Gertrude had been a resident at Woodside (the village where Mr. Allen lived,
and of which he was the rector,) there had been but little like studying or lesson learning,
or lesson giving, going on.
It was therefore a new thing for her to be summoned at nine o`'clock,
the morning after Miss Robson`'s arrival,
to take her slate and her school books into a room hitherto known to her by the name
of the "`play-room,`" but which was now to be dignified with the title of "`school-room.`"

Finding it hopeless to wait for Harriet and her sister
to gather up their scattered books,
and adjust their hair and their dresses, and at the same time to obey Mr. Allen, who,
from the bottom of the stairs was calling out, "`Children,
Miss Robson is waiting for you,`" Gertrude went down alone,
with her books and slate in her hand.

She was kindly greeted by Miss Robson,
who inquired into her progress in spelling and grammar.
It was found to be but little, owing more to various hindrances,
than to any unwillingness to apply herself.

"`Well, we must endeavor to make up for lost time,`" said Miss Robson,
as she appointed her some spelling words to learn by heart.

About half-past nine, Harriet and Charlotte came in, bustling and noisy,
and shoving each other out of the way to get to their seats.

"`I shall sit there, Charlotte,`" said Harriet, "`I`'m the eldest,
and I have a right to choose my seat.`"

"`Sit here,`" said Miss Robson, calmly, pointing to a stool by her side.
Harriet stood in silence, somewhat awed by the composed demeanor of her governess,
but evidently determined to dispute the matter before she gave up her own will.

"`I always used to sit where Charlotte does, when Miss Singleton was here,`" she replied.

Miss Robson made no answer to this, but again pointed to the stool,
which there seemed no means of escaping.
And Charlotte, who was triumphing at being able to keep her own seat,
looked upon all of this in a way which Harriet well enough understood--plainly
manifesting that she thought it would be great fun to see Harriet
become entangled in an argument with the new governess.
If it were for nothing else, therefore, than to disappoint Charlotte`'s expectations,
it seemed advisable to end the matter by obeying; which she accordingly did,
though so much against her will, that tears came into her eyes,
and she could scarcely conceal them.

Now, dear children, I am aware that these are very ugly feelings that I am revealing;
but at the same time, if you are faithful in looking into your own hearts,
I fear that some among you will be forced to say
that you have known something very like them.
It is because of these ugly feelings that we experience in our childhood,
that we know the truth of that solemn description of fallen human nature,
given by the mouth of God himself, (Genesis 8:21):
"`The imagination of man`'s heart is evil from his youth.`"

But blessed be His holy name, though we are these evil creatures from our youth,
He has not left us without help.
He has promised us a new heart, and a new spirit,
and such a one as shall enable us to overcome evil with good;
for it is a good and blessed Spirit, even His own pure Spirit of truth,
that is offered to all those that sincerely ask for it.
(Matt. 7:7-12)

The acquirements of Harriet and Charlotte were found
to be more extensive than those of Gertrude,
but they were in such disorder as to be of little value.
Their copy-books were blotted and blurred,
and the title-page was ornamented both inside and
out with the names of their respective owners,
Harriet Allen, and Charlotte Allen, in all sorts of hand-writing,
diversified with various drawings of horses, dogs, cows, lions,
etc. which betrayed too clearly the idleness which
had accompanied even their efforts at learning.

"`It may be good to mention, once for all,`" said Miss Robson,
"`that I never allow copy or exercise books to be scribbled in.`"

"`Miss Singleton didn`'t mind that,`" said Harriet, pertly.

"`Perhaps not,`" replied Miss Robson; "`but I am not Miss Singleton.`"

The governess then read, and presented to each of the little girls a little card,
upon which was written the lessons for every day,
and the hours at which these were to be learned and repeated.
This being done, the business of the morning proceeded.

But Harriet,
feeling irritable because of what had taken place on her first coming into the room,
and puzzled and perplexed to know how to deal with the quiet,
steady manner of Miss Robson,
decided she would not be brought under such discipline
without some further attempts at resisting it,
and also of establishing her usual habit of doing pretty much whatever she pleased
with those who did not want the trouble of encountering her unruly spirit.
For this purpose, she began disputing everything that Miss Robson had arranged.
She objected that she did not usually do her French
exercise at this hour with Miss Singleton;
nor her grammar at that hour.
She did not repeat Mangnall`'s questions on this day,
nor her Goldsmith`'s history on that.

"`Well, my dear,`" said Miss Robson, "`what is that to me?
I tell you again, I am not Miss Singleton.`"

Her extreme coolness only added to the fury and folly of poor Harriet.
Oh, she was poor indeed at the present moment;
for heating herself more and more with passion,
she went on with her impertinent speech until, when she finally concluded it,
she was actually crying, though nobody could tell what for.

It is not only sad and sinful to give way to passionate and evil feelings,
but it is also very degrading.
People generally make themselves ridiculous in the eyes of their fellow creatures,
whenever they allow a furious temper to get dominion over them.
Such was truly the case at the present moment with poor Harriet--for indeed,
a sad spectacle she made of herself in the eyes of all present;
especially seeing that Miss Robson, to whom all her passionate nonsense was directed,
sat as motionless as a statue while she was pouring it forth.
And when Harriet had ended by bursting into tears,
Miss Robson only remarked with the utmost calmness,
"`You had better take a short walk in the garden, my dear,
till you feel able to go on with your lessons.`"

Her indifference increased the confusion and rage of the misguided girl; who,
having calculated (or rather mis-calculated) upon drawing her new governess into an
argument--as she had been in the habit of doing with her mother and former governesses,
whenever she wanted to get her own way--was entirely baffled by this mode
of conduct which was as new as it was disagreeable to her.
Indeed, she was wholly overcome by her feelings,
and sobbed so violently that both Charlotte and Gertrude began to cry in sympathy.
It was surely the strangest scene to behold three little girls crying,
and not one of them knew the cause of her tears!
But Miss Robson knew; and, truth be told,
she had met with something of this kind many times
before when dealing with children of unruly tempers.

She felt truly grieved for how Harriet was exposing herself;
but she was assured that the only means of doing her any real good,
was to allow her to be her own chastiser,
by causing her to feel the disgrace and sorrow that evil tempers
naturally and necessarily bring upon those who indulge them.
She took her by the hand,
and leading her to a distant part of the room where there was a small table,
she placed a stool there, and desired her to sit down and compose herself,
and when she felt able, to go on with her lessons.
At first, Harriet resisted this advice;
making herself look still more blamable and still more silly,
by shoving away Miss Robson`'s hand as she pointed to the seat,
and sobbing out the words "`I won`'t!`"--as little
Johnny might have done if he had been able to speak;
but which, from the lips of a girl of eleven years old, was disgraceful indeed.

"`If you don`'t choose to sit down, you must stand,`" said Miss Robson;
"`for I cannot lose time in talking about it.
Only I think it would be better for you to do as you are told.
Come now, yield to what is for your own good.
You will be very glad, in a quarter of an hour, that you have done so.`"

Still sobbing, but rather less violently, Harriet took her seat,
and Miss Robson gently laying her hand on her shoulder, said "`Now,
you will soon be able to go on with your lessons;`" and pointing
to the place in a book from which Harriet was to transcribe,
she returned to her other pupils, whose tears were also wiped away.

The utmost silence was maintained for some time.

Harriet, after this first struggle for dominion, which had ended so disastrously,
at last went on with her prescribed task,
perceiving it best in every point of view to submit to the will of her instructress;
and having finished her lesson to Miss Robson`'s satisfaction,
was allowed to resume her place at the table with the other little girls,
where she conducted herself in a very orderly and
becoming manner for the rest of the morning.
When school was over, its labors and afflictions were forgotten;
for distress is never of long duration in young hearts.

The tear down childhood`'s cheek that flows,

Is like the dewdrop on the rose;

When next the summer breeze comes by,

And waves the bush,--the flower is dry.`"^
footnote:[Walter Scott.]

It might have been expected, perhaps,
that Miss Robson would have taken an opportunity at the close of the morning`'s business,
to discourse with Harriet on the impropriety of her conduct at the commencement of it;
but, besides the fact that she was at all times a woman of few words,
she adopted the plan of letting children learn as much as possible from facts and circumstances,
rather than from formal and set discourses.
She felt assured that,
in consequence of the degrading situation to which her own passionate
and ungoverned temper had been the means of reducing her,
Harriet had that day learned a weightier and more
enduring lesson than had ever been taught her before.
And indeed,
it was evident from her behavior towards her governess for the rest of the day,
that it was one also which had convinced her,
that whoever she expected to frustrate or perplex in the task of managing her,
Miss Robson would not be the person fit for her purpose.
