== Chapter IV. Reproof and Amendment.

In less than a month from Miss Robson`'s appearance at the Rectory,
a great change for the better had taken place in the state of affairs there.
Both Harriet and Charlotte became more orderly and obedient in their behavior,
and so decidedly improved under the tuition of their present governess, that Mrs.
Allen no longer interfered (as she had been too much in
the habit of doing) with the plans pursued in their education.

Gertrude also benefited by the present state of things.
She was not a very quick little girl, yet she was very diligent, and being,
as you have already seen, exceedingly shy and timid,
her advancement in school had hitherto been much hindered by the lack of patience
she had encountered in those who had been appointed to instruct her;
which, because of the weak health of both her parents and then their death,
had chiefly been the different servants that had the charge of
her before she came to Mr. Allen`'s. These persons were not much
used to the task of bearing with the ignorance of childhood,
and patiently waiting for the opening of their mental powers.
Indeed, it is greatly to be feared,
that many who are better fitted by their education to deal with young minds,
are still lacking in that first and great requisite for guiding and managing them properly,
which consists in well understanding,
and constantly acting upon the precious precept of our blessed Redeemer,
"`In your patience, possess your souls.`"^
footnote:[Luke 21:19]

But Miss Robson was not of this number.
She had been deeply exercised in sorrows of various kinds; and often used to say,
that the necessity of obtaining her living by bearing with the tempers and habits of
children in the arduous task of their tuition (which many persons would consider irksome),
had been to her among her chiefest blessings.
For, she said, it took her, as it were,
out of herself and her own particular interests and feelings,
and constrained her to exchange many useless regrets,
and vain considerations about this or the other disappointment,
for the useful occupation, not only of teaching, but also of being taught.
"`I have, on the whole,`" she would frequently observe,
"`learned more that is valuable from my pupils, than they have learned from me.
Many are the precious lessons of patience, and self-control,
and a knowledge of the workings of the human heart,
that they have unconsciously imparted to me.`"

You may be assured, therefore,
that she was not one to feel any impatience or discouragement with the laborious efforts
of Gertrude to accomplish what the other children could do without any effort at all.
For Harriet and Charlotte were remarkably quick and acute in their understandings,
and lacked nothing but Gertrude`'s diligence to become, in due time,
well educated and accomplished girls.

I told you that I would let people and things describe themselves; and so, I think,
I must share with you a little scene in the schoolroom,
which took place about two months after Miss Robson`'s arrival;
which will serve to show you how the nature of the
little girls operated upon themselves and each other;
and also, how the conduct of their governess affected them upon that occasion.
There was one difficulty in spelling which Gertrude was almost always puzzled by;
and that was the proper placement of the two vowels _i_ and _e,_
as they occur in such words as _believe, perceive, receive, niece, chief,_ etc.
This matter has been found puzzling to older minds than Gertrude`'s,
and so Miss Robson observed the frequent misplacement
of these letters with the utmost patience.
But not so Harriet and Charlotte, who used to smile at one another,
and sometimes whispered to Gertrude before she began her spelling lesson,
"`not to put the cart before the horse,`" in a way
that was rather trying to the poor little girl.
And truth be told, it was the sly, quick glance of Charlotte`'s eye,
while she was repeating her lesson, that often so bewildered her,
that it produced the very errors she was laboring to avoid.

One morning when this was more particularly the case, Miss Robson observed it;
and when Gertrude had finished saying her spelling lesson,
and had been corrected in her usual error of misplacing the letters in the words _believe,
receive,_ etc., she said to Charlotte,
"`I think you can write well enough now to take your slate,
and accompany your sister in her exercise from dictation.`"

Much elated, as children generally are with being engaged in something new,
Charlotte was soon ready with her slate, and seated herself with Harriet to write,
as Miss Robson read to them a passage which she selected for a particular purpose.
And as it is a very valuable passage,
and one from which much instruction is to be derived, I shall transcribe it for your use;
just telling you, that it was written nearly two centuries ago, by a wise and good man^
footnote:[Isaac Penington (1616-1679)]
to his children, during a time in which, from various circumstances,
he was obliged to be absent from them.
This man, therefore, like a tender father,
desired to admonish them by letter concerning several things wherein,
from the ignorance and heedlessness of youth,
they were likely to stand in need of warning.

"`And remember this one thing,`" he says, "`which as a father I admonish you of,
and charge you to take notice of and observe; which is this,
that you do not criticize or ridicule one another,
or complain because of the evils you observe in one another;
but first take notice of that evil in yourselves,
and if you find your own hearts cleansed from it, bless God who has done it,
and keep to His grace whereby He did it,
and watch that you are not overtaken in it for the future.
But, if you are guilty of the same evil, or have lately done the same thing,
or are suddenly liable to do it, oh then, for shame,
forbear accusing or blaming one another.
And, in the fear of God, wait upon Him, and pray unto Him,
that you may be delivered from it and kept out of it.
And then, in tender pity, admonish your brother or sister of his or her evil,
and watch to be helpful to preserve or restore them.

But it is the bad spirit and nature (which God will
sharply punish) that is always ready to accuse others;
and though it be ever so bad and guilty, yet it will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible and ashamed of its own.

Dear children, if you bend your minds to learn these things,
the Lord will help you therein, and become your teacher, guide, and preserver,
and pour down His blessings upon you; and you will be a comfort to me and your mother,
and an honor to His Holy Truth; and He also may give me wise,
fatherly instructions to teach you further.
But, if you are careless, foolish, vain, following your own minds,
and what rises up there from the wicked one, you will grieve my heart,
and provoke God against you, to bring evil upon you, both in this world and forever.`"

When Harriet and Charlotte had finished writing this passage,
their slates were put aside till Miss Robson was free to correct them,
which she always did before school ended;
and they proceeded with Gertrude in their other morning tasks.

At the usual hour their school work concluded,
and according to the rule established by their governess
they were leaving the room quietly,
with Harriet, as the eldest, going first.
But, somewhat to their surprise, she and her sister were asked to remain behind,
and Gertrude was sent away alone.

"`I wished you to stay,`" said Miss Robson,
"`because there are so many errors in both your slates, especially in Charlotte`'s,
that I was unwilling to expose you by pointing them out before little Gertrude;
especially because I am assured that, seeing how liable you are,
even with your greater advantages, to make mistakes in spelling as well as her,
you will not for the future be so quick and sharp upon her for her errors.`"

Miss Robson then pointed out the words that were mis-spelled.
In Charlotte`'s slate there were many more than in Harriet`'s, because,
in the heat and eagerness with which she rushed upon her new occupation,
she was less watchful than her sister; but Harriet`'s was still a careless production,
and it is worthy of remark,
that in both their exercises the word _grieve_ had the vowels _i_ and _e_ placed wrong.
Both of them were deeply humbled,
not only by being made to feel their own liability to err,
but also by the manner in which they were reproved
for their unkind conduct towards Gertrude.
They were not, as I have before told you, unfeeling little girls; far from it,
only their feelings, till recently, had not been properly guided or controlled.
Good and bad, like weeds and flowers, had grown up together;
and (alas!) as the evil in fallen human nature sprouts
so much more readily than the good,
that which should have been rooted up,
had overgrown and choked the springing up of the better part.

Harriet took her slate in silence; and with a face overspread with the deepest red,
sat down at her desk to make the necessary corrections in her exercise.
But Charlotte, who, though exceedingly passionate, was,
nevertheless a very affectionate little girl,
and who had become much attached to Miss Robson,
felt her reproof in a way that more deeply affected her than can easily be described.
She, too, took her slate, and sat down to her desk;
but not immediately to correct her exercise,
but rather to think what a different creature she was from Gertrude; who, she was sure,
would not laugh at her in her present humbled condition,
although she herself had so often sported and made
herself merry with Gertrude`'s mistakes in spelling.
Miss Robson, too, she thought, how kindly she had acted,
when she might have exposed her so greatly before Gertrude!

While these reflections were passing through Charlotte`'s mind, Harriet,
having corrected her slate, took it up to her governess,
and then receiving permission to do so, went to join Gertrude in the garden.
Charlotte no sooner found herself alone with Miss Robson, than,
coming towards her with emotion which scarcely left
her the power of speaking so as to be understood,
"`Oh, Miss Robson,`" said she, "`what a naughty girl I am!
What a bad heart I have!`"

"`We all have bad hearts, my love,`" replied Miss Robson, kindly taking her hand,
and making her sit down by her side; "`We all have bad hearts, dear Charlotte,
till God gives us new ones.`"

"`Oh, I`'m afraid I shall never, never--`",
here her sobs impeded her finishing what she intended to say.

"`__You__ will certainly never give or make yourself a good one,`" said Miss Robson,
"`if that is what you fear.
But '`ask, and you shall receive; seek, and you shall find; knock,
and it shall be opened unto you.`' God has the new heart to give.
See here, let me read this precious Scripture to you;`" and taking up her Bible,
which never was absent from the school table, she read from Ezekiel 36:26-27,
these words: "`I will give you a new heart and put a new spirit within you;
I will take the heart of stone out of your flesh and give you a heart of flesh.
I will put My Spirit within you and cause you to walk in My statutes,
and you will keep My judgments and do them.`"

"`Now, dear child, at this moment, the Lord is fulfilling this gracious promise to you.
At this moment He is softening, or taking away, the stony, hard, selfish heart, which,
for the sake of a poor jest, or an unworthy amusement,
has so often made you regardless of poor Gertrude`'s feelings.
I dare say, you would rather undergo any pain at the present moment,
than laugh at her about her mistakes in spelling?`"

"`Oh, I would!
I will never laugh at her again.
Dear Gertrude!
Oh, if I were only as good as Gertrude!
She never laughs at anybody!`"

"`You are different in your natures, my dear.
Gertrude is a remarkably timid, reserved little girl.
You are very high-spirited, impulsive, and fearless.
But what is it that makes you different at the present moment?
Why are you acting contrary to your nature now?`"

Charlotte was silent, but deeply thoughtful at this question;
and Miss Robson did not interrupt the pause till it had continued for some time.
She then rose, and taking Charlotte`'s hand,
she repeated with much solemnity the Scripture promise;
"`And I will put My Spirit within you.`"
"`It is a better spirit than your own, my love, that you now feel,`" said she;
"`even that blessed Spirit which the Lord here promises,
and which our compassionate Saviour has directed us to ask for;
tenderly suggesting to us how surely it will be given,
if only sought for in sincerity and truth.
'`If you, being evil,`' He says, '`know how to give good gifts unto your children,
how much more will your heavenly Father give the
Holy Spirit unto them that ask Him!`' How much more!
Oh, Charlotte, what words are these!
How inviting!
How tender!
Ask, then, and it shall be given you.`"
Then kindly kissing her cheek, Miss Robson left the room; and Charlotte,
as soon as she was a little composed, corrected her exercise,
and then went to join her sister and Gertrude,
whom she found sitting in an arbor in the garden.

Their activities during play-hours generally were such as separated,
rather than to bring these young people together.
The two sisters, indeed, from their similar love of active recreations,
were more often found in each other`'s company than in Gertrude`'s,
whose constant satisfaction in her doll and her cradle,
was so wearisome and insipid to their restless spirits
that they seldom remained long in her company.
But this morning, Harriet, on leaving the school-room,
came to the little arbor where Gertrude usually retired with her little treasures;
and in so gentle and altered a manner, asked if she might play with her.
The little girl was quite surprised,
and being somewhat afraid that this agreeable behavior
concealed a design of playing some joke on her,
rather cautiously replied, "`I know you don`'t like playing with a doll, Harriet.`"

"`Oh, indeed I do, Gertrude,`" replied the other, "`I have been thinking,
that I am not always so kind to you as I should be; nor is Charlotte.
And you are always very kind to us.`"

Gertrude looked a moment or two at Harriet as she said this,
and seemed to have some reply to offer to it.
But Gertrude was not eloquent.
She always felt more than she knew how to express in words,
and finding on the present occasion that her words were not at her command,
she conveyed the meaning of her thoughts by putting her arms round Harriet`'s neck,
and tenderly kissing her cheek.

Harriet, on the contrary, was a powerful talker;
and she had now no difficulty in uttering those feelings which prompted her to
express much regret for every instance of past unkindness to her young friend,
and promises to avoid it for the future.
As a token of her sincerity, she took the doll from the cradle,
with a regard almost equal to what Gertrude herself would have shown;
and was soon as much engrossed and amused as her
companion in the nursery affairs connected with it.

They were thus engaged, when Charlotte was perceived coming over the lawn to join them.
A sort of instinct at the first glance of her,
occasioned Gertrude to pop the doll into the cradle,
and place both under the bench on which she was sitting,
to conceal her prized possessions from danger.

"`Oh, Charlotte won`'t play any tricks this morning,`" said Harriet,
observing this hasty action, and too well detecting the reason for it.

Gertrude did not feel so sure of that as to resume her amusement,
until Charlotte herself, with a kindness and good humor that could not be resisted,
begged to be admitted into their party;
and hearing from Harriet that another doll would add greatly to their enjoyment,
ran off delighted to fetch her own, with which she soon returned,
having added to it all the scattered articles of
its wardrobe that she could hastily collect together.

Gertrude was at first surprised at such unusual attention,
where she had been accustomed to meet only with neglect or even worse;
but as young minds are seldom disposed to inquire
into the causes of this or the other circumstance,
but remain contented with the present moment and
the present thing (so long as they bring pleasure),
she quickly lost her astonishment at the kindness of her play-mates,
and if she had wondered at all,
it would have been that they had not been always as happy
and comfortable together as at the present time.
