== Chapter IX. Judge Not, That You Be Not Judged.

While we leave Gertrude to an interval of quiet and repose,
I shall ask you to accompany me to the parlor, where,
after the visitors had taken their leave, there only remained Mrs.
Allen, Miss Robson, and Harriet and Charlotte;
among whom the following conversation took place, while they were engaged at their work.

Harriet.--What an artificial girl that Laura Thomson is!

Charlotte.--I never saw anything so ridiculous.
How she goes mincing round the room!

These words were accompanied by a variety of slinking and sliding movements,
which Charlotte exhibited as a representation of Laura Thomson`'s movements.

Mrs.
Allen--(trying to suppress a smile).
Charlotte, Charlotte, that really is very wrong.
She should not do so, should she, Miss Robson?

Miss Robson.--I think Charlotte would not herself like to be represented in that manner.

Charlotte.--I represented in that manner?
I hope that I don`'t make myself quite so ridiculous as Laura Thomson does!

Miss Robson.--You may not, perhaps, imitate others in her particular way.
You may not put on a facade after her precise manner.

Harriet.--But, Miss Robson, I don`'t think Charlotte is at all artificial.

Mrs.
Allen--No, really, Miss Robson, I must think you are a little too hard upon Charlotte.

Strengthened by her mother`'s remark, Charlotte assumed the tone of an ill-used person,
and said she believed that, whatever were her faults,
they were not those of imitation and pride.
"`And indeed, Miss Robson,`" she continued,
with a boldness she would neither have felt nor shown out of her mother`'s presence,
"`I think you would be puzzled to mention when you ever saw me
make myself look so ridiculous as Laura Thomson does.`"

Miss Robson.--"`I am not fond of being puzzled, especially by my pupils; for,
if there is to be any puzzling at all between us, I think it is my place to puzzle them.
So I believe, Charlotte, I must give you the puzzle of finding out what I meant.`"

There was a plain straight-forwardness about Miss Robson,
that never allowed her to turn aside from the point
when she believed it to be a right one.
Mrs. Allen felt assured, from Miss Robson`'s demeanor,
that there was something more behind her remark to Charlotte;
and as she herself was a person who had a great (and too much indulged) dislike
to anything she thought disagreeable (such as the reproving of her children),
she chose to end her part in the conversation by leaving the room.
With the departure of her mother, the greater part of Charlotte`'s bravery departed also.
She would have been very glad to have ended the subject,
and so she endeavored to do so by making some remark to
her sister respecting the work in which she was employed.
Her efforts in this, however, were in vain; for Harriet,
being determined to know what was Miss Robson`'s aim,
instead of answering Charlotte`'s remark about her work, returned to the former subject,
by begging her governess to say wherein she thought Charlotte
had shown herself guilty of imitation and pride.

Miss Robson.--"`I don`'t recollect saying she was guilty of either.`"

Harriet.--"`No, not exactly; but you seemed to think she was guilty of both.`"

Miss Robson.--"`I gave Charlotte the puzzle of finding out what I meant by my remarks.
Perhaps, she has solved the riddle;
and then you can hear from her all that I have to say on the subject.`"

While this was passing, Charlotte had been manifesting great signs of restlessness,
looking into this work-box, and that basket,
as if in search of something that she needed, though without naming the missing article.
Harriet constrained her now to return to the point she evidently wished to avoid,
by asking her plainly if she knew Miss Robson`'s meaning?

Charlotte.--(turning red)--"`I believe I do.`"

Harriet.--"`Oh then, do tell me, I must hear what it is.`"

Miss Robson.--"`I will give you two an opportunity to talk.`"

And, as she spoke, she was rising to leave the room;
but Charlotte prevented her by throwing her arms around her,
and hiding her blushing face upon Miss Robson`'s shoulder, as she said to her,
in a low voice, "`Dear Miss Robson, don`'t go.
Oh, you have made me so ashamed of myself.`"

Miss Robson kindly kissed her cheek.
"`Shame is generally a valuable feeling, Charlotte,
and those who can really and deeply experience it,
are never to despair of moral improvement.
I will leave you while you relate to Harriet what I can see she so much wishes to hear;
but as you are thus placed in circumstances which oblige you to be your own reprover,
I must suggest to Harriet that it was not kind to indulge that impatient
curiosity which has drawn you into such a painful situation.`"

Harriet.--"`Indeed I am to blame.
But I will not hear what Charlotte has to tell; I will punish myself that way.
I am sure, dear Miss Robson, you have a reason for everything you say,
or even hint to us, and that is quite enough.`"

Miss Robson was highly pleased with the conduct of both her beloved pupils,
and there the matter was permitted to rest.

But, as I am not without hope that some of my young readers
may derive instruction from the relation,
I shall gratify your desires to know the meaning behind
the remarks which Miss Robson had made to Charlotte.
In doing so, however,
I must go back to some circumstances that had occurred only the preceding week,
and which were known only to Charlotte and her governess.

It happened one morning that a lady stopped at the Rectory,
who wore under her bonnet (as many ladies do) some artificial flowers,
which were articles of finery that Mr. Allen had a particular objection to;
for he always remarked, whenever he saw them,
that it seemed to him little less than an insult upon the lovely
flowers to mimic their beauties with bits of colored cloth.
"`If people desire to wear flowers,`" he would say, "`let them gather them fresh and real.
But I believe it is better for all things to keep their proper places;
the flowers to ornament the ground,
and the spiritual blossoms of good hearts and minds to ornament the ladies.
Those are the flowers that are not artificial, and will never fade.`"

Now, among her other failings,
Charlotte Allen possessed a great deal of vanity and love of dress;
which were shortcomings that found little encouragement in her father`'s house;
for everything there was of the plainest and simplest kind.
But, notwithstanding these restraints upon her fancy,
she seldom saw any fashionably-dressed persons,
that she did not experience more or less a desire to imitate.
On the morning now alluded to,
she had allowed her mind to be so much captivated
by the artificial flowers under the visitor`'s bonnet,
and had so minutely observed and remembered them, that, as soon as the lady departed,
she went into the garden to make an assortment as near like them as possible.
It was a time of day when she usually walked out with Miss Robson
and her sister to visit some of the poor people in the village;
but on this morning she made some trifling excuse
of wishing to employ herself in the garden,
and they, together with Mrs.
Allen, went without her.

And here, I would pause to observe, that it is desirable for young persons,
to always acknowledge to themselves the real reason for all their actions,
especially when they are of a kind which incline them to wish to be alone.
Now, in this case, had Charlotte spoken the truth to herself, and said,
"`I wish to be alone,
because I want to see how I would look with flowers under my bonnet,`" she would,
most likely, have been so ashamed of herself,
that she would have relinquished her intention.
But, by glossing over her design with saying, (and I suppose really thinking),
that she was going to employ herself in gathering flowers--forgetting,
or not choosing to remember,
what she was going to gather them for--she went into a crooked path,
which was likely to lead her further into error than she had intended.
But to proceed.
She made her selection as nearly as possible to the pattern in her memory.
There was a moss-rose and a sprig of jessamine to stand out from the side of one cheek,
and there was a sweet-pea and a bit of mignonette to do the same on the other.

"`But I must also have a bonnet like Miss Smith`'s!`" thought Charlotte.
This was indispensable to the proper adornment;
but certainly no bonnet in her house was of that sort.
"`No matter;
where there`'s a will there`'s a way,`" and so Charlotte believed
she could give a twist and a turn to her own bonnet cap,
which would produce the desired effect.
Accordingly she hastened to the room in which she and her sister slept,
in doing which she had to pass through Miss Robson`'s, which opened into it.

The flowers she had gathered were all twisted together, and placed in order upon the cap,
and altogether tied on before the mirror, and her straw bonnet put over them,
when she recollected that Miss Smith also had a veil that was partly shading her face.
Where was a veil to be found?
She had none; but Miss Robson had one, though she seldom wore it,
except when the weather was cold.
Charlotte had seen her take it out of her drawers, and knew where she kept it.
But to go to Miss Robson`'s drawers in her absence, and to take anything from them!
This was, indeed, a startling consideration;
and she hesitated some time before she could proceed.

"`But you are not going to steal the veil,`" said the artful tempter in her ear,
"`you are going to put it back again almost immediately.`"

Poor Charlotte!
How clearly at any other moment would she have seen the shamefulness of
such practices as she had involved herself in by taking one wrong step!
But now she could see nothing but her own will; and so, to gratify it,
she went to Miss Robson`'s drawers, took out the veil, and tied it upon her bonnet.

Thus adorned like her visitor, who was not only fashionable in her attire,
but fashionable in her manner and conversation, and sprightly and clever in her remarks,
and altogether a sort of person who was likely to
awaken some feelings of admiration in an intelligent,
observing girl,
Charlotte next proceeded to imitate the way in which
Miss Smith had talked during her visit.
Here I must leave you to imagine the scene;
not being willing to expose all the absurdities she uttered.
Perhaps some of my young readers may have happened to meet with a little girl
here and there who has been tempted to indulge (as poor Charlotte then did),
a foolish desire of copying the manners of some one or another
whom she has wished to resemble--in that case,
they can understand as well as I could tell them,
how exceedingly ridiculous she made herself.
I shall only, therefore, relate the conclusion of the matter,
which was indeed a very painful and unexpected one to Charlotte; who,
in her eagerness to accomplish her purpose,
had forgotten to shut the door of Miss Robson`'s room.
Great, therefore, was her confusion, when, on rising from her seat,
and making a low curtsey, and saying as Miss Smith had done on taking her leave,
"`My dear Mrs.
Allen, I must now tear myself away; for, indeed,
it is only by force that I can ever get away from the Rectory;`"--great, I say,
was her surprise, and unutterable her confusion,
in feeling a hand laid upon her shoulder, at the same time that a voice inquired of her,
"`Where are you going?`"

"`Oh, Miss Robson!`" she exclaimed; for it was indeed her governess,
who had returned from her walk, not sooner than usual,
but sooner than Charlotte had calculated upon.

"`Oh, Miss Robson!`" she repeated, as she sat down,
and in extreme confusion covered her face with both her hands.

"`And oh, Charlotte!
I think I must say,`" replied Miss Robson,
standing motionless with surprise a few moments.
Then looking earnestly at her, said,
"`What have you made yourself this ridiculous cap for,
and why have you taken my veil out of my drawers?`"

"`I don`'t know what to say,`" replied Charlotte,
beginning to cry bitterly,--"`I am so ashamed!`"

The flowers, and the finery, and the mimicry of Miss Smith`'s parting speech,
told their own story; nor was it one that greatly surprised Miss Robson,
who had often noted with concern Charlotte`'s disposition
to be pleased with fine clothes and fashionable people,
and also an inclination (not uncommon in young girls)
to imitate the manners of their elders.

"`I shall not say much to you, my dear Charlotte,`" she observed,
after a little interval of silence, during which Charlotte sobbed bitterly,
"`I shall not say much to you,
because I am persuaded that what you are now feeling
is a far better reprover to you than I can be.
But I would earnestly exhort you to remember it when
the present painful impression has passed away.
Yes, I would earnestly counsel you to bear in mind that it is not merely the
folly of mimicry which this indulgence of vanity has led you into,
but also a breach of trust, and a violation of good faith, which is far worse.
When I leave my drawers, I feel that I can so far confide in your principles,
and also in your sister`'s,
as to be persuaded that you will abstain from meddling with them.
I do not believe you ever opened a drawer of mine before.`"

"`No, I never did!`" said Charlotte.
"`I only knew you kept your veil there, because I have seen you take it out.
And to think that, for such foolishness as this, I should do such a thing,
and lose your good opinion!`"...and she burst into fresh tears.

"`You will not lose my good opinion,`" said Miss Robson, affectionately embracing her.
"`On the contrary, I trust henceforth to find you more deserving of it than ever;
for I hope that what has now passed will tend to make you so watchful over yourself,
that you will not again be betrayed into anything so foolish and degrading.
Come, let us get rid of these trappings (which have indeed been traps for you,
poor child!) before Harriet comes up to change her dress.`"

"`It will be long before I want to wear flowers again!`" thought Charlotte, as,
in a kind of scorn at her own folly,
she took off her ornamented bonnet and began to disassemble its adornments.

We might have hoped it to have been long also before
she felt any inclination towards imitation;
but here, I believe, I must again unveil the truth of the matter,
and tell you that it was a secret stirring of envy at Laura Thomson`'s fashionable clothes
that caused her so hastily to forget the humiliation of the preceding week.
Such poor creatures we are when governed by our own evil nature!
