== Chapter X. Hasty Spirits.

It had been a source of great satisfaction to Gertrude,
during her long and languishing illness,
to hear from Miss Robson and her young friends Harriet and Charlotte,
how the affairs of the poor people in the village prospered.
She delighted to hear what children got prizes at Sunday school, what babies were born,
and what names were given to them,
and in what way the little dresses and gowns and other articles
of clothing that were made at the Rectory were being used.

Great also was the gratification which Harriet and her sister derived
in receiving and communicating information upon these subjects.
But as it is common in larger communities than that of Woodside for the evil
passions of human nature to be found rising up and opposing what is good,
so too in this small and sequestered village,
there was no lack of that "`strife of tongues,`"^
footnote:[Psalms 31:20]
which manifested the presence of a "`root bearing bitterness and wormwood`"^
footnote:[Deuteronomy 29:18]
in some of Mr. Allen`'s parishioners.

However,
as it was Miss Robson`'s chief object at all times to extract something valuable
out of even those circumstances which seemed to promise it the least,
she was not discouraged if, during their round of visits to the houses of the poor,
they sometimes met with behavior which Harriet,
in the energy of her warm and inexperienced feelings,
would immediately characterize as shameful ingratitude.
Harriet`'s indignation was one day particularly aroused (indeed,
it had often been excited,
though in a lesser degree before) by the conduct of a woman named Mary Hayes.
This poor woman, having recovered from a rheumatic fever,
during which time she had received financial assistance
from a benevolent society headed by Mrs.
Allen, was informed by Miss Robson that, on the following week,
her allowance as an invalid would cease.

"`Surely,`" exclaimed Mary, "`Mrs.
Allen may do as she likes.
But this I`'m clear and certain of,
that there`'s nobody in the village who needs more
more help than I do--so weak and helpless as I am!`"

"`You seem to have recovered your strength pretty well, I think,`" said Miss Robson.

"`Your voice is certainly loud enough, I`'m sure,`" said Harriet.

"`Well, it`'s enough to make anybody loud!`" she angrily replied.
"`Seeing that Judy Taylor is still receiving her half-a-crown every week!`"
She then added some words that were so exceedingly rude and injurious,
that Miss Robson without replying,
summoned her young people and rose to leave the cottage,
merely bidding her "`Good morning.`"

Charlotte,
though nearly as much incensed as her sister with
the insolence and ingratitude of the woman,
obeyed the summons of her governess, and followed her out of the room.
But Harriet,
forgetting that she was now just as angry as the
poor woman herself (though from another cause),
and therefore just as unfit to speak,
remained behind to lecture Mary Hayes on the impropriety of her conduct.

[verse]
____
To give reproof in anger, to be sure,
What`'eer the fault, is not the way to cure.
Would a wise doctor offer, dost thou think,
The sick his potion scalding hot to drink?^
footnote:[Dr. John Byrom.]
____

I shall not relate to you what passed between them,
for it would be very little to your edification.
You may suppose it was anything but of a healing nature,
when I tell you that in about ten minutes,
Harriet overtook her sister and Miss Robson at the other end of the village,
looking as discomposed and as angry as Mary Hayes herself had looked.

"`What is the matter?`"
said Charlotte;
an inquiry which Harriet answered by pouring forth
many vehement accusations against Mary Hayes,
in the midst of which they were met by Mrs.
Thomson and her daughter, who,
having offered and answered the usual salutations of the day, were passing on.

Full of the excited and irritated feelings which Mary Hayes had awakened in her mind,
Harriet arrested Mrs.
Thomson`'s progress, by saying, "`Oh, Mrs.
Thomson, I hope you will never do anything more for Mary Hayes.
I hope you are not going to her cottage?`"

It happened that Mrs.
Thomson actually _was_ going to see Mary Hayes; for, living very near Woodside,
she was not only a supporter of the society by which
the sick and poor of that village were assisted,
but she also sometimes visited them; and being in affluent circumstances,
and kindly disposed, she gave away much money and clothing among them.

Of course she was very much surprised by Harriet`'s remark,
and stating that it had been her intention to call on Mary Hayes,
she begged to know what had taken place to render it unadvisable,
addressing her words to Harriet, but her eyes to Miss Robson,
as supposing her better fitted to inform her of the true state of the case.

Miss Robson smiled,
and interrupted the hasty and voluble explanation that Harriet was pouring forth,
by saying, "`gently, gently, Harriet!`"

Mrs.
Thomson smiled also, and said,
"`Perhaps Miss Robson would be so kind as to detail the case.`"

To be treated like a child, added to the other indignities that had been heaped upon her,
was quite too much for Harriet`'s towering spirit to handle.
She remained proudly silent,
while Miss Robson (to whom such scenes in human life as they had just witnessed
with Mary Hayes were not by any means new) quietly and simply informed Mrs.
Thomson that the poor woman, although recovered from her illness,
did not like being taken off the list of recipients,
and had therefore expressed herself on the subject very improperly.
"`But I have not the least doubt,`" she continued, "`that before night arrives,
she will be sincerely sorry for her fault.
Mary Hayes is a very passionate, impulsive woman,
and always says more than she intends to say, when her fits of ill-temper are upon her.
And you know, Mrs.
Thomson, when we consider what half-a-crown a week is to a poor woman,
we ought to make some allowance for the pain and disappointment
she would be likely to experience in having it taken away.`"

Mrs.
Thomson, who was extremely goodnatured,
could easily see and make allowance for the difficulties of the case.
She therefore proceeded to downplay Mary`'s fault as much as possible,
addressing herself on this point to Harriet, who, if I must state the truth,
was in no disposition to be addressed to any advantage at that moment.

I shall not enlarge upon the arguments she used to prove to Harriet
what a different condition that she--as the daughter of Mr. Allen,
the Rector of Woodside--was placed in, compared to that of poor rheumatic Mary Hayes,
who was obliged to labour for her livelihood.
Neither shall I recount the instances of gratitude among the poor
which she brought forward to balance against Mary`'s lack of it;
for as much as is necessary of what she said,
you will be able to gather from Harriet`'s observations when they separated.
Miss Robson and the girls then returned home, and Mrs.
Thomson and Laura went on to visit Mary Hayes;
Miss Robson having been very urgent with them to do so,
in the hope that it might tend to heal the wounds which
Harriet`'s fiery zeal had no doubt greatly served to inflame.

I hope, Miss Robson, you will excuse my making the remark,`" said Harriet, very loftily,
"`but indeed I think,
if you had heard all that Mary Hayes said to me when I stayed behind to speak to her,
you would hardly have thought it right to condone her so much.`"

"`I do not condone her ill behavior, my dear,`" replied Miss Robson;
"`but I have lived somewhat longer in the world than you have, Harriet,
and I find it a good rule in dealing with angry people,
to leave the door open for their return out of their ill-tempers.
Passionate people require compassion, sometimes above all others;
for they generally do themselves so much harm, that if no one was found to pity them,
and provide a sort of safety valve for their spirits,
they would be in perpetual danger of explosion.`"

"`Well, really, I do think,`" said Harriet,
still too angry to be convinced she was in the wrong,
"`I really do think that is carrying compassion rather too far.
I can understand why Mrs.
Thomson is so full of love for all her '`dear poor people,`' as she calls them.
It is because they flatter her;
and then it is very easy for her to talk about that '`interesting Sarah
this,`' or that '`sweet Susan that,`' as she did to me just now;
and to advise me to seek their acquaintance.
But that you, Miss Robson--`" and there she stopped,
unwilling to say all that her anger inclined her to say.

"`Oh, Harriet dear, indeed you are wrong,`" said Charlotte.
"`Try to forget Mary Hayes.`"

"`I`'m sure, Charlotte, if she had talked to you as she did to me,
you would have been ten times more angry than I am.`"

"`That would have been a fearful sight to see,`" observed Miss Robson.
"`I am very glad Charlotte escaped the hazard of exhibiting it to us.`"

"`But what did she say to you?`"
inquired Charlotte.

"`Oh, she told me she didn`'t need to be taught by a child like me,
who she had seen a little while ago in diapers.
And when I told her she ought to cultivate meekness and humility,
'`Meek indeed!`' said she, '`Oh yes, you are a meek one!
Don`'t you know that I remember you, Miss Harriet,
from your cradle?`' What do you think of that?`"
There was something in the circumstances of this case--I shall not undertake
to describe what--but assuredly there was something which,
when Harriet concluded her account by saying "`what do you think of that?`"
inclined Miss Robson to turn her head aside to conceal a smile.

They had now arrived at the Rectory,
and Harriet was still harping upon the string of her grievances.
Miss Robson, therefore, speaking rather decisively, begged to hear no more on the subject.
"`Both you and Mary Hayes will be quite different persons before you go to bed tonight,
I have no doubt,`" she said.

"`It might be the case, and I hope it will be with Mary Hayes,`" Harriet replied;
"`but as for myself, I am quite sure that I will always think the same;
that I have been very improperly treated.
But there`'s mamma,`" she exclaimed, as she observed Mrs.
Allen coming to meet them across the lawn.
"`I`'ll hear what she has to say;`" and without pausing to listen to Miss Robson say,
"`Stay, stay a moment,`" she had locked her arm in her mother`'s,
drawn her head close to hers, and led her aside to walk together on a gravel path,
quickly imparting to Mrs.
Allen all that had transpired, before Miss Robson had time to interpose.

Finding that matters were so far hopeless in relation to Harriet,
Miss Robson was desirous of turning them to better account with Charlotte; who,
though sufficiently dissatisfied with the way in which her sister had been treated,
was nevertheless in a disposition to listen with
proper respect to what her governess wished to say.

"`You now have an opportunity of learning a lesson, Charlotte,`" said Miss Robson,
as she motioned her to take a seat beside her on a garden bench,
"`which you will often have occasion to remember; and that is,
to let a little time elapse before you speak or act, whenever your temper is ruffled.
Attempting to do anything good at such times is like
putting to sea in the midst of a storm.
Right now our dear Harriet is rushing to find relief and present ease
for her mind by pouring out her pent up feelings into her mother`'s ear.
And what will be the outcome?
She will indeed get the pity for herself that she wants.
So far, the bad, selfish nature will have its will.`"

"`Is it a bad and selfish nature, dear Miss Robson, that Harriet is yielding to?`"
inquired Charlotte.
"`Does she not think it right that mamma should know what
an ungrateful and ill-behaved woman Mary Hayes is?`"

"`It would be much more right for Harriet to remember that blessed counsel of the apostle,
which she has very often heard, and, I believe, even learned by heart: '`Brethren,
if a man is overtaken in a fault, you who are spiritual,
restore such a one in the spirit of meekness; considering yourself,
lest you also be tempted.`'^
footnote:[Galatians 6:1]
This would especially be the right thing for Harriet to do,
seeing she is so exceedingly liable to be tempted with a passionate spirit herself.`"

"`But what will be the consequence you were speaking of, Miss Robson?`"

"`I think it is likely that taking such a course will occasion
a great deal of pain and remorse to Harriet;
for the probability is, that the poor woman, Mary Hayes, when a cooler moment comes,
will be extremely sorry for what she has said, and will wish it could be all unsaid.
She will naturally dread what it may lead to.
She will fear that, if repeated to Mrs.
Allen or to your papa,
it may cause them to be so much displeased as to withdraw all other favors from her,
along with the financial assistance that has now been discontinued;
and under these feelings,
she will lose no time in coming to the Rectory to apologize to Harriet,
and perhaps to me, and most likely entreat us to forbear acquainting your parents.`"

"`Oh, how sorry I would be if that were the case!`" said Charlotte.

"`There is no help for it now,`" replied Miss Robson, "`for Harriet has,
undoubtedly by this time, related the matter to your mother,
and related it also under all the strong excitement which
could give a heightened and aggravated color to it.`"

"`I can see now,`" said Charlotte, after a few moments of silence,
"`I can indeed see now how much better it is to let a little time elapse,
rather than to speak at the time when we are angry.
Oh, how sorry Harriet will be, if Mary Hayes should come and apologize.
How sorry she will be for being so hasty.`"

"`Yes,
but it is in this way that rash and impetuous persons must be taught,`" said Miss Robson,
"`even in the same way as Gideon taught the men of Succoth, '`with briars and thorns.`'^
footnote:[Judges 8:16]
However, dear Charlotte, as you, happily, are not implicated in her present error,
but are in the place of a calm bystander,
endeavor to learn your lesson from it in a more peaceful way.
It may be comprised in a few precious words--'`Stand still,
and see the salvation of the Lord.`'^
footnote:[Exodus 14:13; 2 Chronicles 20:17]
When agitation of any sort disturbs you, even of a pleasurable kind,
you must _stand still,_ that is,
endeavor not to act or speak until your emotions have subsided;
for by acting or speaking at such times,
it is probable that you shall place yourself in circumstances
that are either foolish or sinful;
and in such as you would be glad to have escaped in a cooler frame of mind.
If we are agitated by an object of pleasure that is before us,
the vain nature will run out into nonsense,
just as little Johnny skips and jumps and does ridiculous things,
because he is promised some enjoyment.
And, if our agitation is of a more dark and painful kind,
then it will spend itself in fury, which, besides bringing folly,
brings sin and shame upon us.
Therefore, whenever you are highly pleased, or highly pained, dear child, be still;
and soon you will feel something better than yourself and your own wild feelings,
which seeks to save you from such words and actions as, in a little time,
you will be truly thankful to be saved from.`"

[verse]
____
When grief or joy shall press upon you hard,
Be then especially upon your guard;
Then is most danger of not acting right,
A calmer state will give a surer light.^
footnote:[Dr. John Byrom.]
____

The matter turned out just as Miss Robson had predicted.
The dinner cloth had just been removed,
when Harriet was summoned out of the room because
Mary Hayes wished very much to speak with her.
Her passion had subsided, and she was now as composed and mild,
as she had a short time before been injurious and angry.
But, it was now too late to ask that Mr. and Mrs.
Allen might not be informed regarding her misconduct;
for Harriet had left nothing untold on that point.
Following after the hasty and impetuous impulse which urged her to rush
ahead and disclose her feelings as soon as she saw her mother,
she had (as she now perceived) done the poor woman a great unkindness.
For Mrs.
Allen had been so much displeased with what had been related to her,
that she repeated it to Mr. Allen at dinner; and he on his part was equally dissatisfied,
so that poor Mary Hayes had sufficient cause to fear that
her ill behavior would produce some serious consequences.

Harriet, feeling sincerely sorry for what she had done to aggravate the affair,
readily forgave the affront that had been offered to herself,
and promised to speak to Miss Robson in hopes that she would help to resolve matters.

I dare say, my young readers, you will be able,
without many words of description from me,
to conceive some idea of the painful humiliation of Harriet`'s mind,
as she went to Miss Robson and related Mary Hayes`' penitence,
and then spoke of her own regret for the rashness whereby
she had perhaps rendered Mary`'s penitence unavailing.
Indeed, she was truly brokenhearted and contrite for what she had done, and promised,
with an earnest desire that she might be enabled to keep her word,
that she would follow the counsel of her much-respected friend and governess,
which was now very weightily enforced upon her; namely,
that whenever she was rushing upon a hasty manifestation of her feelings,
that she would try to be still, and let a little time elapse,
before she either spoke or acted.

"`You must learn how to bear feeling uncomfortable a little while,
Harriet,`" said Miss Robson.
"`It is this hurrying out after something to please, or something to comfort,
that does all the mischief.
When you are affronted, bear it.
Whatever happens, bear it for a time; don`'t be in a hurry to revenge yourself.
If you have been really mistreated, depend upon it,
it will be made right at the right time, and in the right way;
but to be in haste about vindicating yourself,
clearly shows that there you are in the wrong.
'`In your patience, posses your souls.`'^
footnote:[Luke 21:19]`"

I may just add, in concluding this chapter, what you will be glad to hear,
that Miss Robson`'s calm and judicious representation of the case,
and Harriet`'s regret for her own haste and passion,
had their due effect upon Mr. and Mrs.
Allen; and that poor Mary Hayes was forgiven her impetuosity, and restored to favor.
