== Chapter XI. A Farewell.

Another year rolled over the heads of the family at the Rectory,
and brought with it only an increase of weakness and debility
to our poor little friend Gertrude.

It had long been evident that she was gradually sinking
under the disease with which she was afflicted,
and, from the statements I have already made,
you will have been prepared for hearing what may
at first appear to be somewhat melancholy news.
But I hope when you have read the following letter from Mr. Allen,
wherein he gives an account of her peaceful departure from this valley of tears,
you will rather rejoice than regret to take leave of her.
It is addressed to the lady under whose care Gertrude was placed upon leaving India,
and who delivered her over to the charge of Mr. Allen.
This lady had been to see her several times during her long illness;
and upon leaving her at her last visit,
had requested to hear from Mr. Allen respecting her.
Several letters had been addressed to her in compliance with this request;
and at last came the following, with which I shall close this little narrative.

[.asterism]
'''

My Dear Mrs +++_______+++.

The black seal on this letter will have prepared you for its contents.
Our little suffering Gertrude is now a rejoicer with the saints in light,
and if it were not for the fact that you will doubtless be desirous of a few particulars,
I should be glad to avoid recurring to any other account of this
dear child than that which has to do with her present state.
You will, therefore, excuse my being somewhat brief.

On Saturday last, she was extremely languid and drowsy,
and having for several days observed appearances of her departure approaching,
we expected that that day would terminate her sufferings.
But, contrary to what we looked for, she revived towards the evening,
insomuch that she was able to converse a little,
and seemed particularly pleased to have me and our beloved friend Miss Robson near her.
I read a few verses from the 14th chapter of John,
which was always a very favorite portion of scripture with her.
I paused at the words,
"`in My Father`'s house are many mansions,`" for
she seemed as if she had a remark to make;
but she only uttered the words "`all beautiful,`" and smiled.

"`Yes, my love,`" said I, "`all!
There are no mansions like those, Gertrude!`"

"`Oh!
I long...`" but, as if fearing to convey impatience by expressing her wishes,
she did not say more.

"`You long to be gone, dear child,`" said Miss Robson.
"`But we do not wish to part with you, my dear,
while the Lord permits you to remain;`" and our dear friend,
though a person of unusual self-control, was unable to restrain her tears.

Gertrude seemed a little grieved at this,
but the emotion was quickly resisted on the part of Miss Robson, who,
with a pleasant smile, wiping away her tears,
repeated to her little friend and beloved pupil the following lines,
which Gertrude had been fond of hearing during her illness.
They were written by a friend of Miss Robson`'s who was in suffering circumstances.

When they their little hour have stayed,

The roses droop and die;

The lilies of the valley fade,

And so, alas, must I!

But wherefore do I say, alas,

And wherefore do I sigh?

The wintry season soon will pass,

And summer days draw nigh:

The lovely rose will re-appear,

The lilies bloom once more;

And spring, returning fresh and fair,

Creation`'s face restore;

And saints of God shall rise renewed

With better life than this;

To dwell with the Supremely Good,

In everlasting bliss.

She smiled sweetly as though these thoughts were very precious to her; and when I said,
"`Through One, who died for all,
we may hope to rise to everlasting bliss,`" she earnestly exclaimed "`Yes; through Jesus,
the blessed Savior!`"

"`Do you feel that you have no other hope, my love, than what you find in Him?`"
I asked.

"`Oh no,`" she replied quickly.
"`I can only think of God through Him--He is the good Friend that intercedes.`"

"`The sinner`'s Friend,`" said Miss Robson,
"`the Friend that sticks closer than a brother.`"^
footnote:[Proverbs 18:24]

She showed her joy and satisfaction in this blessed thought,
but was too weak to express it.
Our dear Gertrude, as you are aware, was, even in health,
one who seldom gave utterance to her feelings.

After having spent a few minutes in prayer, I took leave of her for the night,
and the girls and Mrs.
Allen came into her room for the same purpose, leaving her, as usual,
under the kind care of Miss Robson.

Having parted with her in such a condition,
we were not expecting to be summoned at day-break with the painful intelligence that
she was suddenly so much worse as to be apparently on the eve of her departure.
Yet such was the case.
We hastened to her room, that is, my wife and myself;
for I did not desire to have my dear girls called up to witness the scene.
It was from our sweet Gertrude`'s living graces, and not her parting bodily struggles,
that I expected them to be instructed.
Happily these struggles were of short duration.
She was passing away as we entered the room,
and that with a smile so beautiful that any feeling
but that of joy seemed forbidden to any of us.
We were all rejoicers, that is, Miss Robson, our faithful servant Sarah, and myself.
But my poor wife, though not the mother of the dying child,
felt her parent`'s heart stirred up within her,
and clasping her arms round the dear Gertrude, as she was supported by Miss Robson,
wept bitterly.

The grey dawning of day, and the solemn circumstances around me,
so forcibly recalled those beautiful and moving lines
of Mr. Cecil`'s on the death of one of his children,
an infant of a month old, who died at day-break, that I uttered aloud the first verse:

Cease here longer to detain me,

Fondest mother, drown`'d in woe;

Now, your kind caresses pain me,

Morn advances, let me go!

"`Your day breaks upon you, happy child!`"
I exclaimed, as I pressed my lips upon her cheek,
and breathed a few words to Him who sees in secret.

One little sigh released her happy spirit; and we had now no pain left,
but that of conveying the news to the young and buoyant natures of our dear children,
who we were sure would, for a time, consider it very mournful tidings.

It was indeed a painful stroke, though long expected;
and I allowed the emotions of nature for a season to have their sway.
And when these had somewhat subdued,
I endeavored to take advantage of the occasion to theirs and all our benefit;
and I hope was not unsuccessful.

"`Thus, my dear children,`" I said, in conclusion, "`we have lost our gentle Gertrude;
but we have not lost that which made her gentle.
For He whose parting words were '`Lo, I am with you always,
even unto the end of the world`"--He who was meek and lowly in heart,
and who calls the heavy laden to come unto Him and be refreshed--He remains to bless us,
and to do us good; to gather the lambs with His arm, and to carry them in His bosom.
Oh then, my children,
cultivate those sweet and lamb-like virtues which
shall make you fit to be gathered into His fold;
so that whenever, and however, your summons shall come,
you may know as peaceful a departure as our gentle Gertrude.`"

Feeling this same desire for myself, and for you, my Christian friend,
and for all my fellow creatures, I rest sincerely yours,

John Allen.

The End.
