name: pdf-previews

on: [pull_request]

jobs:
  pdfpreview:
    name: pdf-previews
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      PRINCE_BIN: /home/runner/bin/prince-books
      PRINCE_NAME: prince-books-20240705-ubuntu24.04-amd64
      CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
      CLOUD_STORAGE_BUCKET: ${{ secrets.CLOUD_STORAGE_BUCKET }}
      CLOUD_STORAGE_ENDPOINT: ${{ secrets.CLOUD_STORAGE_ENDPOINT }}
      CLOUD_STORAGE_KEY: ${{ secrets.CLOUD_STORAGE_KEY }}
      CLOUD_STORAGE_SECRET: ${{ secrets.CLOUD_STORAGE_SECRET }}
      DEV_ROOT_PATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - name: install prince deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgif7
          sudo apt-get install -y libavif-dev
      - name: download pdf binary
        run: |
          curl -s ${CLOUD_STORAGE_BUCKET_URL}/actions/${PRINCE_NAME}.tar.gz > ~/prince.tar.gz
          tar -xvzf ~/prince.tar.gz -C ~ > /dev/null
          printf "$HOME\n" | ~/${PRINCE_NAME}/install.sh
      - uses: 808sAndBR/file-changes-action@v1.2.5
      - name: create pdf previews
        uses: friends-library/dev/actions/ts-pack/actions/pdf@master
        with:
          GITHUB_TOKEN: ${{ github.token }}
